### ISSUE TITLE
It blocks playing music on soundcloud.com

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#1]
Reported here: http://www.reddit.com/r/chrome/comments/28xt2j/%C2%B5block_a_fast_and_lean_blocker_for_chromiumbased/cifl7k2

**Comment by abdulhaleembaram** [comment]
Why don't open a little porn site?

**Comment by gorhill** [comment]
This issue was moved to uBlockOrigin/uBlock-issues-old#1
