### ISSUE TITLE
Beta test 0.3.0.0-rc0

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#100]
Whoever care to try and test: [µBlock 0.3.0.0-beta](https://github.com/gorhill/uBlock/releases/tag/0.3.0.0-beta).

You will have to [install manually](https://github.com/gorhill/uBlock/tree/master/dist#install) so that you won't clobber your existing installation.

**Comment by ialexsilva** [comment]
1- ![sem ttulo](https://cloud.githubusercontent.com/assets/6363160/3708220/30e35f02-1440-11e4-8de5-15b17899c55b.png)
White space at the bottom of the page when selecting element... Only appears at this link:https://github.com/notifications

2- UI: ublock could use the same font httpswitchboard

**Comment by ghost** [comment]
Added 

https://easylist-downloads.adblockplus.org/antiadblockfilters.txt

without any problem.

**Comment by gorhill** [comment]
> White space at the bottom of the page when selecting element

This is normal, the document ends before the bottom of the window. There is no element to select in the whitespace area.

Also, only the issues which were fixed are to be tested, everything else should be filed the normal way, or else this version will never ship.

**Comment by ghost** [comment]
Working great!

![untitled](https://cloud.githubusercontent.com/assets/8084723/3709245/7a95ef32-1451-11e4-8d80-eef530237fe0.png)

**Comment by gorhill** [comment]
@RazielCuts 

Your last comment, was it a false positive? Just want this confirmed, as I plan to release the final I just want to be sure there is nothing wrong with it.

**Comment by ghost** [comment]
Yup, it was false positive. I misread your installation instructions where it said that don't remove the ublock folder.

**Comment by ghost** [comment]
I just updated from the beta to rc0 (without removing the beta first - what do you recommend?). Everything seems to work well. 

It's a pity that you had to go back to `onBeforeRequest` but if it's necessary you had no choice.

**Comment by gorhill** [comment]
> without removing the beta first - what do you recommend

No need to remove the folder, just overwriting the content is fine.

**Comment by ialexsilva** [comment]
working fine... 
Just did not like you have to get down to the bottom of the page to find what you are looking for. should have better organization including markers... ex: href = "#custom"

**Comment by gorhill** [comment]
Yes, I was thinking about being able to collapse groups. Regional lists would be collapsed by default. But that would be another version.

**Comment by ghost** [comment]
Any chance to get export/import feature to Custom lists?

**Comment by gorhill** [comment]
I'm thinking going the same way as HTTPSB, i.e. to have an import/export all data in the _About_ tab.

**Comment by ghost** [comment]
Awesome. :)
