### ISSUE TITLE
Question - How Often Updates For 3rd party filters?

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1002]
Hi,

Is there anyway to say often updates might occur for the 3rd party filters?

thank you

**Comment by gorhill** [comment]
Roughly, every 4-5 days.

**Comment by ghost** [comment]
Hi gorhill,

WOW fast reply! LOL...

Ok I'll just click on them to check, because if you remember, I have all the auto features off in Firefox, so I'm not sure how this is going to auto-update then...

Hmm

Unless, if the auto-update is check marked it just by passes any about:config settings?

If I have the auto-update unchecked then Update Now button should become available when updates are ready?

thanks

**Comment by gorhill** [comment]
> it just by passes any about:config settings?

You are confusing the update the uBlock itself with the update of the filter lists. These are separate things: only uBlock can update the filter lists, Firefox has nothing to do with this.

**Comment by ghost** [comment]
Ok...

But If I the auto-update is unchecked then Update Now button should become available when updates are ready?

thanks

**Comment by gorhill** [comment]
> Update Now button should become available when updates are ready?

Yes.

**Comment by ghost** [comment]
Thanks gorhill :)
