### ISSUE TITLE
0.9.1.0-rc.0 version error

### ISSUE THREAD

**Issue by ozar** [uBlock-LLC/uBlock#1005]
After installing 0.9.1.0-rc.0 (for Firefox) on Linux, the dashboard and the popup version info shows version 0.9.0.1 to be installed rather than 0.9.1.0

I'm guessing that is an error and not the intended behavior for this rc release.

**Comment by gorhill** [comment]
Oops, I forgot to revise the version number. This will be fixed in next RC release.

**Comment by gorhill** [comment]
Fixed in 65890f1e338c46139e956492b7ab1166153d2abb.
