### ISSUE TITLE
Question: Updating to latest uBlock?

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1006]
Hi gorhill,

I tried to update uBlock from 0.9.0.0 to 0.9.1.0 in Firefox; Right Click > Find Updates, but nothing happened. 

When new versions of uBlock come out how do we update them?

thank you

**Comment by harshanvn** [comment]
It is not fully approved on AMO. Once, done it will be automatically updated.
Till then we should manually update.

**Comment by gorhill** [comment]
AMO says:

>  Next Version: 0.9.1.0 [?]
> Queue Position: 142 of 143 

Where [?] =

> This is the newest uploaded version, however it isn’t live on the site yet.

It just take time, we have to accept it. uBlock currently updates more often than new versions can be cleared on AMO, this means it's likely to be stuck at 0.8.8.2. The previous 0.9.0.0 version didn't clear before the new 0.9.1.0.

**Comment by ghost** [comment]
Ahh ok, thank you

What's this accept mean, so what holds this up? I see a lot of addons get updated pretty quick.

**Comment by ozar** [comment]
Just want to add that I've been a bit curious why Mozilla is so slow getting new versions of uBlock posted, too.  Like meuwe noted above some add-ons are getting approved very quickly, such as the case with NoScript.  For instance, NoScript version 2.6.9.17 was released on the NoScript website on March 8th, and it showed up on Mozilla's Add-ons page later the same day.  Then NoScript version 2.6.9.18 was released March 13th (five days later) on the NoScript website and it was posted on Mozilla's webpage later that day.  If it makes any difference, the NoScript dev also had 3 RC releases between those dates released through their developmental channel.

It would seem that there might still be something else going on that is allowing some add-ons to be approved and added to AMO right away.  Perhaps there is some kind of seniority thing involved with add-ons, but just guessing.

**Comment by gorhill** [comment]
> Next Version: 0.9.1.0
> Queue Position: 139 of 150

**Comment by ghost** [comment]
Queue Position, LOL, I guess the little people have to sit at the bottom waiting...

Really, why do some addons get faster updating, is there some politics to this or pay to get there faster?

Something is sure odd about this... hmm

**Comment by gorhill** [comment]
> I guess the little people have to sit at the bottom waiting

The reviewing is all contributed by [volunteers](https://wiki.mozilla.org/AMO:Editors), i.e. they use their own free time for the benefit of all.

**Comment by ghost** [comment]
Yes well, it certainly looks like some preferential treatment of some sort is going on. Because it appears that if you have a smaller project you wait longer. I see big named addons get updated fast.

**Comment by gorhill** [comment]
> Next Version: 0.9.1.0
> Queue Position: 140 of 160

**Comment by ghost** [comment]
How'd it go backwards?

**Comment by ghost** [comment]
This is crazy, if I was a developer I'd want answers on this, why there seems to be some sort of preferential treatment going on...

**Comment by gorhill** [comment]
> Next Version: 0.9.1.0
> Queue Position: 132 of 163

**Comment by ghost** [comment]
gorhill have you contacted Mozilla over this? This should of been done already.

**Comment by gorhill** [comment]
> This should of been done already

No. uBlock is just one extension among many others, there is no reason uBlock should be treated different than other extensions.

Nagging people who do voluntary work reviewing extensions for AMO is inconsiderate, and nagging them about one specific extension as if it deserved some kind of special status is selfish.

I provide the status here just so that people stop asking about the status.

**Comment by ghost** [comment]
Of course nagging isn't the thing to do, no one ever suggested to nag or complain, it was only suggested to contact them and ask them about it.

And it's not about being treated differnet, I don't even know if there is any paying or donation services, I just find it odd that NoScript and Adblock get updated really fast...

I don't know how long you've been using Firefox, but I've been using it since the project started in it's very beginning and in that time I've never seen an addon take this long to get updated, that is all I'm saying.

Again communication was only to see how long Mozilla is saying it typically takes, that is all I was trying to communicate to you. :)

**Comment by gorhill** [comment]
>  Next Version: 0.9.1.0
> Queue Position: 123 of 171

**Comment by gorhill** [comment]
>  Next Version: 0.9.1.0
> Queue Position: 122 of 176

The part which puzzles me is that two days ago, the rank was 123, and yet meanwhile, as per [AMO's "newest extensions"](https://addons.mozilla.org/en-US/firefox/extensions/?sort=created), ~7 new preliminary reviewed extensions were added, more if including fully reviewed ones. I don't know how it works.

**Comment by ghost** [comment]
gorhill you really should contact them, even on the site your addon isn't updated;

https://addons.mozilla.org/en-US/firefox/addon/ublock/?src=search

Something odd is going on here, I get the feeling it's been swept under the rug by mistake.

Like Momma always said; 'You Want Something Right You Gotta Do It Yourself!' LOL...

**Comment by TteokbokkiNari** [comment]
Could ask them on IRC perhaps, or through mail? 

It's quite a big addon with over 100K users already, so having swift updates would be good.

**Comment by samcorbin** [comment]
I just checked the AMO page, 0.9.1.0 is finally approved. 0.9.3.0 though...
