### ISSUE TITLE
[Safari]: Update to 0.9.1 results in zero data

### ISSUE THREAD

**Issue by mike-to-spec** [uBlock-LLC/uBlock#1014]
@chrisaljoudi Just an FYI: I just updated from 0.9.0.0 to 0.9.1.0 and lost all of my stored data in the process. I was able to restore properly from Firefox's backup, so that's good news. 

Note: this is after the failed restore from in 0.9.0.0, so that might cause the problem updating to 0.9.1.0. 

I did restart Safari a few times to see if the data was restored but nothing, it was reset.

**Comment by mike-to-spec** [comment]
If you did expect this, please close the issue then. I just want to let you know in case others might see this issue too.

**Comment by chrisaljoudi** [comment]
@MikhailTNY although this is _expected,_ I hadn't though about it until just now. I'm considering pulling the update to create a fix (though that's quite ugly).

Thanks for pointing this out.

**Comment by mike-to-spec** [comment]
You might want to consider building the pervious 0.9.0.0 build as the new 0.9.1.1 build as that'll ensure everyone gets the previous build in case your fix won't work from .9.1.0 to the future new build.

**Comment by chrisaljoudi** [comment]
@MikhailTNY the fix I'm working on right now should work seamlessly with all past versions.

0.9.1.0 has been pulled for the moment.

**Comment by chrisaljoudi** [comment]
@MikhailTNY okay, just pushed a patched 0.9.1.0 (which is basically just 2d30b04973a9e55f14fbcc7e6f56d088535f455f on top of 0.9.1.0). 

The good news is that everyone will get this patched version, including the few who already upgraded to the flawed 0.9.1.0. Settings will transfer seamlessly.

Thanks for pointing this out. Do let me know how it goes.

**Comment by mike-to-spec** [comment]
@chrisaljoudi I can confirm it is fixed. 

Thanks!
