### ISSUE TITLE
[Request] Please add filter for Estonia

### ISSUE THREAD

**Issue by Er1ch** [uBlock-LLC/uBlock#1016]
I just installed uBlock today and noticed you have filters available for Finland, Sweden, Latvia and Russia but not for Estonia!!! :/

Please add the following to your fun extension. I have been using it for ages on ABP and it works fine on the sites of our tiny country. Also it seems to be actively updated.

http://adblock.ee/list.php

**Comment by sander85** [comment]
I'm the maintainer of this list and would be very happy if it gets included.
If there are any problems, just contact me.

**Comment by sander85** [comment]
I've created pull request for this: https://github.com/gorhill/uBlock/pull/1061

**Comment by gorhill** [comment]
Ok, I've added an entry so that the EST filter list is pulled as an external resource: 4799e5ab849888ffd0ee03ec05f790edc3c5a131.

This is one of the thing I want to do for many other filter lists: convert them to external resources, and have only the most-used generic ones as part of this repo.

**Comment by sander85** [comment]
Ok, thank you!
