### ISSUE TITLE
Unable to load `no` locale

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#102]
I was trying all the available locales, and when trying `no`, the English version is used instead.

**Comment by ghost** [comment]
Through manifest file right? I got error when I changed locale "en" to "no".

**Comment by gorhill** [comment]
I used the command line to switch locale. I will try with the manifest.

**Comment by ghost** [comment]
Give me the cmd command so I can try.

**Comment by gorhill** [comment]
I get an error too:

> Could not load extension from '/media/rhill/permahome/rhill/workshop/ublock'. Localisation used, but default_locale wasn't specified in the manifest.

Strange, `no` is supposed to be supported as per https://developer.chrome.com/webstore/i18n?csw=1#localeTable.

Command line is `LANGUAGE=no chromium-browser`, but that depends of your shell and browser.

**Comment by gorhill** [comment]
Meh, the chrome doc is wrong, the proper locale to use for Norwegian is `nb`. Need a revision asap.
