### ISSUE TITLE
[Firefox on Android] Hostnames in the popup are out of order sometimes

### ISSUE THREAD

**Issue by my-password-is-password** [uBlock-LLC/uBlock#1020]
I just saw this happening and not sure exactly when it happens.  So far this is what I've noticed
- When I try "Open Link in New Tab" ( #1001 ), it happens
- When I try  "opening new tabs in Firefox from 3rd party apps" ( #1017 ), it happens
- Going to a site by typing out the url in the location bar, it <b>doesn't</b> happen
- Opening links in the same tab, it <b>doesn't</b> happen

Screenshot below is from "Open Link in New Tab" on dailytech.
![ublockfirefoxmobilewrongorder](https://cloud.githubusercontent.com/assets/6408935/6656668/eb111478-caed-11e4-9736-12305f83194a.png)

Screenshot below is from opening link, polygon.com, from 3rd party app ( Pushbullet ).
![ublockfirefoxmobilewrongorder2](https://cloud.githubusercontent.com/assets/6408935/6656851/adf68436-caf4-11e4-9620-de683fdfa87c.png)

**Comment by gorhill** [comment]
Seems related to #1019, which might have been fixed by #1021.

**Comment by my-password-is-password** [comment]
<s>It does seem like this issue is fixed with `0.9.1.1-dev.1: Merge pull request #1021 from AlexVallat/master`</s>

Edit: Hmm....  With the new `0.9.1.1` the 1st pary hostname still gets sorted with the rest.

**Comment by my-password-is-password** [comment]
@gorhill "3rd-party filters" tab is broken on desktop Firefox too with `0.9.1.1-dev.1: Merge pull request #1021 from AlexVallat/master`

**Comment by my-password-is-password** [comment]
Doh.  It was one of my other addons fucking things up.  Sorry

TabsInForeground
https://addons.mozilla.org/en-us/android/addon/tabsinforeground/

**Comment by gorhill** [comment]
I had an emergency fix to do, so 0.9.1.1 became the official release, which is 0.9.1.0 + the emergency fix.

So now I have to go back to what we were doing. Next dev built will be in 0.9.1.2.

**Comment by my-password-is-password** [comment]
@gorhill Don't go back!  Disabling TabsInForeground is the fix.

**Comment by gorhill** [comment]
How could TabsInForeground influence the content of the popup? I suspect the problem was fixed by #1021, all the symptoms match: the page hostname for the tab was not the right one.

**Comment by my-password-is-password** [comment]
I have no idea but when I disable TabsInForeground and manualy click to switch tab, it works.

Btw when using `Dev build: use at your own risk`, theres 3p-filters.js error.  FF mobile and Desktop.

![ublock3pfiltersjs](https://cloud.githubusercontent.com/assets/6408935/6657453/ee1a4c72-cb09-11e4-9bfb-2953598b09ab.png)

![ublock3rdpartydashboard](https://cloud.githubusercontent.com/assets/6408935/6657452/ea1c3d06-cb09-11e4-86bd-04b0fa639df7.png)

**Comment by gorhill** [comment]
What is `1561a34d-321a-4d53-8414-d9a410e33053`? Another extension?

**Comment by my-password-is-password** [comment]
I think so.  That was an old screenshot from earlier today.  I opened up the console just now and there was only that one 3pfilters.js error.

**Comment by gorhill** [comment]
It looks like another extension is trying to access uBlock's page, and the browser fires a standard warning that it's not allowed.

**Comment by my-password-is-password** [comment]
Cool, the latest dev build  `0.9.1.2-dev.2` works even with TabsInForeground enabled.  Thanks
