### ISSUE TITLE
Blocking ads on flash player behaves differently on Safari and Chrome

### ISSUE THREAD

**Issue by u128** [uBlock-LLC/uBlock#1023]
A commonly employed technique to block ads on a popular UK based catchup service (4OD) is to allow the video to begin to buffer without an adblocker active, and then to start the adblock extension. This allows bypass of the active adblock check, but still allows ads to be blocked. A simple video of this is action can be viewed here https://www.benbristow.co.uk/2015/02/bypassing-4ods-adblock-block/ .

This feature works with uBlock in Chrome, as seen in the video, but not in OS X Yosemite Safari.

**Comment by chrisaljoudi** [comment]
Safari's extension API has limitations that make it impossible to intercept requests coming from plugins (such as Flash).

Nothing that can really be done about it at this time; sorry.

**Comment by elyrly** [comment]
Interesting trick
