### ISSUE TITLE
Icon on address bar lloks wrong when blocking.

### ISSUE THREAD

**Issue by typhoon71** [uBlock-LLC/uBlock#1024]
Firefox 36.0.1, uBlock 0.8.9.0.

The red icon with an "u" inside looks fine if uBlock is not blocking, but as soon it starts blocking (say, I load a page with ads) the little counter is misplaced.
[It gets put on the bottom right of the red icon, nut it's too low to be readable]

If you select the "Personalize" menu (Firefox one) and just close it, the counter fixes itself.
[It get displayed correctly on thop right of the red icon]

Doesn't seem related to other addons, I tried disabling them and the cosmethinc issue persist.
Not a big problem but annoying. Would it be possible to fix it? 

Thanks anyway, uBlock really is doing it job well.

**Comment by gorhill** [comment]
This was fixed in [version 0.8.9.1](https://github.com/gorhill/uBlock/releases).

**Comment by typhoon71** [comment]
Thanks, I forgot to check git for updates (I'm too used to firefox automatic updates)
