### ISSUE TITLE
[Firefox] empty buttons in addon options

### ISSUE THREAD

**Issue by typhoon71** [uBlock-LLC/uBlock#1026]
From about:addons click on uBlock properties button.

The page that opens has 2 empty buttons (no text on them): they are on the left, one up and one down. 
If I click on disable they go away, if I click on enable they reappear.
The upper one opens chrome://ublock/content/dashboard.html.
The lower one opens chrome://ublock/content/devtools.html.

It's similar to #1018.

FFOX 36.0.1, uBlock 0.9.1.2 (dev package), win7 x64, italian (both OS and FFOX)
Console output (disable/enable):

![console](https://cloud.githubusercontent.com/assets/1866248/6658217/8540d2a8-cb62-11e4-8474-600addadad91.png)

**Comment by gorhill** [comment]
Can you test with [0.9.1.2-dev.1](https://github.com/gorhill/uBlock/releases/tag/0.9.1.2-dev.1)?

**Comment by typhoon71** [comment]
Got 0.9.1.2-dev.1 from your link, it's fixed: the buttons have text on it (the correct one, checked).
Question: the 0.9.1.2 I got from the release page was somehthing different right?
Because I did test that before posting... and it didn't work.

**Comment by gorhill** [comment]
There were no translations available for these strings in 0.9.1.2-dev.1. The [translations were downloaded](https://github.com/gorhill/uBlock/commit/32837deba65fa3188650c7b9acdd14baf2ef2ad7) and included in version 0.9.1.2-dev.2.

**Comment by typhoon71** [comment]
Thanks for fixing it. 
And thanks again for this addon, I really like it and the philosophy behind it.
