### ISSUE TITLE
Firefox: Blank Buttons in Extensions Window

### ISSUE THREAD

**Issue by emariz** [uBlock-LLC/uBlock#1028]
Debian Testing
Gnome 3.14.1
Iceweasel 36.0.1-2
uBlock 0.9.1.1

After upgrading uBlock (from 0.9.0.0) to version 0.9.1.1, there are two blank buttons in the (extended) Extensions window of Firefox.

![ublock_0911_blank_buttons](https://cloud.githubusercontent.com/assets/9307858/6660089/024624ca-cb71-11e4-8856-121edc630443.png)

These blank buttons work: The top one leads to the Dashboard; the bottom one, to the Developer Tools. Yet their titles are missing.

Just in case, I purged uBlock and reinstalled the new version, then tried it with a new profile, but those buttons were blank in all cases.
If this were a localisation issue, I am using Spanish (Spain), ES-ES.

Let me know if I need to provide more information.

**Comment by gorhill** [comment]
Dup of #1026.
