### ISSUE TITLE
[Firefox 36.0.1] Cosmetic filters not applied in advanced user mode.

### ISSUE THREAD

**Issue by magpie514** [uBlock-LLC/uBlock#1029]
## Steps to Reproduce
1. Create custom cosmetic filter (in my test case, disabling Youtube's "recommended channels" sidebar) in advanced user mode. Element hidden is confirmed to be right because it's properly removed from page at this point.
2. Reload page once filter has been set. 
3. Sidebar appears again.
4. Disable advanced user mode.
5. Reload page.
6. Sidebar is now gone.
## Symptoms

I started using uBlock since it had the "advanced user mode" allowing fine tweaking of what's blocked and not, allowing me to get rid of ABP and Noscript. However, I found cosmetic filters never worked, since I was using advanced user mode all the time. After every update I try to see if I can get rid of that pesky Youtube side bar, and for the first time I managed to get the cosmetic filter to work after disabling advanced user mode by accident.
I made sure "Parse and enforce cosmetic filters" and "my filters" are enabled on the filter list, but only disabling advanced user mode changed anything.
## Preferences Different From Defaults

Advanced user mode is enabled, the rest was left untouched from defaults.
## Info

```
uBlock version:
    0.9.1.1
Browser and version:
 Firefox 36.0.1
OS and version:
 Linux Ubuntu 14.10
```
## Other Extensions
- None.

**Comment by gorhill** [comment]
What are the dynamic filtering rules taking effect when you are on Youtube?

**Comment by gorhill** [comment]
Also, be more specific please, I can't reproduce:
1. Give me an exact URL
2. Give me an exact cosmetic filter
3. And as asked above, list the dynamic rules in effect while you are on the page in 1. (a screenshot of the dynamic filtering pane is ok, at least at first)

**Comment by magpie514** [comment]
Gladly.
To be specific:
![snapshot33](https://cloud.githubusercontent.com/assets/323651/6667606/7c1cc4ee-cbed-11e4-9b16-79b933e8c8ef.png)

Those settings allow the site to load faster and is the minimum required to load both comments, video player and such. The site works good enough with those, and I don't get annoying G+ notifications. I might need to enable a few more if I am uploading a video, but I digress.

The example URL would be https://www.youtube.com/feed/subscriptions , with the sidebar at the right.
I block the sidebar using the element picker, ##.branded-page-v2-secondary-col

![snapshot33](https://cloud.githubusercontent.com/assets/323651/6667608/81fb86fc-cbed-11e4-824c-a860b28fdddc.png)
then I click "create" and it gets removed until I refresh the page. Or disable advanced mode. The filter does exist in "my filters"
But this is just an example, any cosmetic filter I create is never applied after reloading. However I noticed some sites, in "normal" mode, seem to load everything even if they are plain text while in advanced mode (for example slashdot, where I didn't allow anything. With the "all: block, images: allow, inline scripts: allow and 1st party scrips: allow" settings above, slashdot shows as unformatted text, but in "normal mode" it loads all formatting and sharing buttons and such, so I am quite puzzled about it. Are dynamic filters only applied in advanced mode?

**Comment by gorhill** [comment]
I don't know why you use `allow` rules rather than `noop` rules, in any case, this is the issue: by using an `allow` rule on `youtube.com`, you are disabling cosmetic filtering. See [Dynamic filtering: disabling cosmetic filtering for the current site](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-disabling-cosmetic-filtering-for-the-current-site).

**Comment by magpie514** [comment]
Oh, I see. I apologize for the bad issue then, my bad entirely.
