### ISSUE TITLE
In the future, will detect uBlock also: "abp://subscribe/?location=LINK&title=NAME"?

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1030]
for example https://archive.today/E5e6X - used method subscribe.

another example http://www.niecko.pl/adblock/ - used method subscribe

**Comment by Deathamns** [comment]
Fixed in ebf840c (at least for Firefox, others support abp: links only on some sites).

**Comment by gorhill** [comment]
It is supported.

For Chromium and Safari, only these:
- https://easylist.adblockplus.org
- https://youtube.adblockplus.me
- https://facebook.adblockplus.me
- https://www.fanboy.co.nz
