### ISSUE TITLE
[Firefox] Wrong font for "U" on button

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1031]
There is no "Ubuntu" font on Windows 7, 64 bit

![ubutoolb](https://cloud.githubusercontent.com/assets/886325/6663033/b931ec22-cbc2-11e4-893b-8ad2e6a253f4.png)
![ubu](https://cloud.githubusercontent.com/assets/886325/6662984/2ed44822-cbc2-11e4-95ab-e4a06dbdeb3c.png)
(enlarged ff-icon16.svg)

**Comment by Deathamns** [comment]
Can confirm.
