### ISSUE TITLE
[Suggestion] temp blocking rules/button

### ISSUE THREAD

**Issue by typhoon71** [uBlock-LLC/uBlock#1032]
Suggestion, or more like a request for a new feature.
When I browse a forum which has a lot of images I want to disable them and read the actual content, but I don't want to do that always. 
I suppose it's possible to add a sensible rule to uBlock keeping it commented out, uncommenting when it's needed.
For ease of use I'd like to have the ability of enabling/disabling a set of rules "on the fly" with a click on uBlock menu, like a on demand filter (temp blacklist).
Would this be possible?

**Comment by gorhill** [comment]
Just use [dynamic filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide) to block/unblock images as you wish.

**Comment by typhoon71** [comment]
Thanks for the tip.
Creating my own rule, active by default (website.com###img) and using dynamic filtering to allow/disallow I do what I wanted. Basically what I asked for is already available.

But there's something I don't understand: using "img" I block all .jpg images, but not .png ones.
Where can I find more info on how those rules are made/work?

**Comment by gorhill** [comment]
> using "img" I block all .jpg images, but not .png ones

Give me specifics so I can see for myself what happens.

**Comment by typhoon71** [comment]
Go to http://exhentai.org/s/65a1bc03a1/82799-2
You'll have a .jpg image loading (SFW), along with some buttons .png

Add this in my rules: exhentai.org###img
Go to http://exhentai.org/s/65a1bc03a1/82799-2 again.
This time the .jpg image is not loaded, but the .png buttons.

(Now you can use use dynamic filtering to enable/disable the custom rule like I wanted)

But if I don't use that rule, and just use dynamic filtering to disallow images on thet domain, both .jpg and .png images aren't shown upon reloading.

**Comment by gorhill** [comment]
> http://exhentai.org/s/65a1bc03a1/82799-2

I don't see any buttons, just one image.

**Comment by typhoon71** [comment]
Those buttons (arrows, for navigation)
![buttons](https://cloud.githubusercontent.com/assets/1866248/6666346/abb4c350-cbe3-11e4-8525-1f565e529ee3.png)
:

**Comment by gorhill** [comment]
I do not see such a navigation toolbar at the link you gave me. Even without uBlock, I only see one image, nothing else.

**Comment by WalterWW** [comment]
> exhentai.org###img

That rule isn't really blocking images, it's just hiding divs with the id=img. This might work on that specific site because of the way that site displays embedded images. But it's apparently not using such divs to display the arrows, and that's why your rule isn't hiding them, while dynamic filtering blocks all images regardless of the html that is used to display them.

If you want to create a filter to block all images on that site you could use this one
    *$image,domain=exhentai.org

**Comment by typhoon71** [comment]
1. You don't see the page cause you should log in, I forgot it became kind of private.
   You answered anyway so np.
2. OK, I understand that the rule I wrote working as I expected by pure chance.
   I understand that "*$image" blocks every kind of image. 
   Would it  be possible to create a rule that forbids .jpg images only (well, based on extension maybe)?

**Comment by WalterWW** [comment]
Yes, you can change the \* in the filter rule to a more narrow pattern, such as *.jpg:

*.jpg|$image,domain=exhentai.org

The $image part might be a bit redundant then but it doesn't hurt either.

edit: it might also be a good idea to add a | at the end to indicate that the filename has to actually end with that extension.

**Comment by typhoon71** [comment]
Perfect, with this I'm set.
Thanks a lot for your time (and patience).
