### ISSUE TITLE
Autoupdate directly from GitHub

### ISSUE THREAD

**Issue by itfarrier** [uBlock-LLC/uBlock#1036]
Please, add this feature.

**Comment by 5t3f4n** [comment]
They do not wish to use GitHub's bandwidth. 

#925 
#922

**Comment by gorhill** [comment]
Closed as `won't fix` in part because of [Github terms of service](https://help.github.com/articles/github-terms-of-service/).

**Comment by TteokbokkiNari** [comment]
What about your own site? http://raymondhill.net/

**Comment by gorhill** [comment]
The consequence of not seeking donations is to equally not seek expenses.

**Comment by TteokbokkiNari** [comment]
I see. Understandable.
