### ISSUE TITLE
[Safari 8.0.5 on 10.10.3 Beta] Lookup's site previews confuses uBlock

### ISSUE THREAD

**Issue by mike-to-spec** [uBlock-LLC/uBlock#1037]
@chrisaljoudi I don't know if you can take reports right now for Safari 8.0.5 on 10.10.3 betas. I just want to give you a quick heads-up: on the latest betas, Apple've added a feature to let you preview sites by performing a Lookup on links in Safari. 

The awesome thing is that the preview already gets the filtering as far as I can tell. The problem? uBlock seems to be focused on the preview's URL even after you close the preview. That means if you refresh the page or go to a different site in the same tab, uBlock remains stuck on the preview's URL not the tab's URL. Which also means that the site remains broken as the rules doesn't match the site. 

Anyway, if it is an Apple bug, better to file a radar now before they release 10.10.3.

**Comment by chrisaljoudi** [comment]
@MikhailTNY Interesting — thanks for pointing this out.

I can see that even after closing the preview uBlock thinks it's still on whatever page you were previewing (this is expected on my part and I'll be trying to figure out a way around it).

But the thing is, I can't reproduce where you said that it's still stuck even after you refresh or navigate elsewhere within the same tab.

Are you sure about that? Can you please list some steps to reproduce that (an example site, etc.)?

Thanks.

**Comment by mike-to-spec** [comment]
> But the thing is, I can't reproduce where you said that it's still stuck even after you refresh or navigate elsewhere within the same tab.

Huh, I tried doing this again after rebooting (_damn keyboard got rendered moot by Lookup_) and I can't do this specific edge case anymore. I'll admit it is difficult to reproduce because 90% of my previews are on the same site but I've seen it many times on Reddit when you preview on sites and then view the comments for that link. I'll report back with the STR as soon as I can figure it out, I might have confused myself on what happened.

**Comment by chrisaljoudi** [comment]
@MikhailTNY okay, I've submitted a bug report to Apple. It is, it seems, impossible to work around this given the misleading events and limited data Safari fires and provides for Force-Touch/three-finger-tap previews. I'll continue to investigate.

**Comment by chrisaljoudi** [comment]
@MikhailTNY that said, it is nevertheless completely unexpected that it would be stuck on the preview's site after you refresh. So if you do reproduce that, please do share the STR.

**Comment by mike-to-spec** [comment]
Cool, let me know if you want me to dupe the report on radar, so they can get to it sooner. 

As for the STR, I haven't been able to reproduce it yet. I think it was just an isolated glitch or I got confused.

**Comment by mike-to-spec** [comment]
@chrisaljoudi Good news, I think they've fixed it in the latest 10.10.3 beta 7 build. I can't reproduce it anymore.
