### ISSUE TITLE
Options-only filter is not working

### ISSUE THREAD

**Issue by LordJZ** [uBlock-LLC/uBlock#1038]
ABP allows omitting the actual filter content, leaving $ options only.

Example:
`$script` -- disables all scripts
`$script,domain=google.com` -- disables all scripts on google.com
`$script,third-party,domain=google.com` -- disables all third-party scripts on google.com

These work in ABP, don't work in uBlock.

Firefox 36, uBlock 0.9.1.0. For testing, create `$script` filter and head to any javascript-using website e.g. facebook.com.

**Comment by chrisaljoudi** [comment]
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide

**Comment by chrisaljoudi** [comment]
and also: https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax

**Comment by LordJZ** [comment]
I see, but uBlock supports filters with options (like `||google.com^$script`) and claims to support ABP syntax.

**Comment by chrisaljoudi** [comment]
`/.*/$script` works, too.

**Comment by LordJZ** [comment]
Why should I? uBlock claims to understand ABP syntax. If uBlock wants to use a different approach for some kinds of filters, that's fine, translate ABP syntax to something else.

**Comment by gorhill** [comment]
Yes, the asterisk is not supported, i.e. `*$script`. Dynamic filtering is by far best to deal with this kind of filter: it can be easily toggled on/off, locally/globally.

I have no problem implementing this however. I will, mostly because of users importing their filters from another blocker.

**Comment by LordJZ** [comment]
Ooh, thanks. Confirmed working.
