### ISSUE TITLE
[Firefox] Chrome-scheme not showing up in popup

### ISSUE THREAD

**Issue by my-password-is-password** [uBlock-LLC/uBlock#1040]
## Steps to Reproduce
1. Go to the dashboard
2. Open up the popup
## Symptoms

The popup says '0 out of 1' but it doesn't show the chrome-scheme in the popup.

<b>Firefox:</b>
![ublockffchrome-schememissing](https://cloud.githubusercontent.com/assets/6408935/6691004/2049396a-cc81-11e4-8bb6-c6dbc1fbe3cb.png)

<b>Chrome:</b>
![ublockchromechrome-scheme](https://cloud.githubusercontent.com/assets/6408935/6691014/30d6f092-cc81-11e4-957a-df9dd3a3d77b.png)
## Info

```
uBlock 0.9.1.2-dev.4
Firefox 33 (desktop) & Firefox 36.0.1 (android)
```

**Comment by gorhill** [comment]
By design.

Only targets to which network requests can be sent are shown in there. The `chrome.webRequest` API can intercept network requests to `chrome-extension://`. But this is not the case for `chrome://`.

**Comment by gorhill** [comment]
Actually, the `chrome-extension-scheme` should not appear in there, it won't be filtered anyways.

**Comment by my-password-is-password** [comment]
Even if you remove it from the 'Whitelist'?

**Comment by gorhill** [comment]
The only purpose of these non-network related "hostname" is to act as a scope for dynamic filtering rules, they should not act as a destination in those rules.

**Comment by gorhill** [comment]
I cannot reproduce that `chrome-extension-scheme` entry in Chromium.

**Comment by my-password-is-password** [comment]
Whoops, was using dev build of Chromium 43.0.2335.0.  You're right stable chrome doesn't show `chrome-extension-scheme`

**Comment by my-password-is-password** [comment]
Sorry,  What about this on android?  Its wrong too?

Opening the popup for behind-the-scene request log.  Shows `behind-the-scene` in the popup.

![ublockffbtspopup](https://cloud.githubusercontent.com/assets/6408935/6691724/6fb77512-cc85-11e4-9f94-56e03d0b23f9.png)

**Comment by gorhill** [comment]
There should be no `behind-the-scene` entry. I get this also on Firefox, might be caused by the changes in 88b517e6faed47dc150e9e246610fdca7a540828.
