### ISSUE TITLE
About 3rd-party filters update

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1041]
I'm slightly puzzled with the process of manually updating uBlock's 3rd-party filters.
uBlock 0.9.1.1 / Firefox 36.0.1 / Windows 7SP1 x64 Premium

1- Purge all caches - ok
2- Apply changes - Do I have to click or not on this ? I updated with and without and results were the same.
3- Update now - ok
4- uBlock filters -- Privacy - 1 used out of 2 -> Restart Firefox -> Update now -> uBlock filters -- Privacy - 2 used out of 3 : means that after a manual update the user must restart Fireox.

I was used to ABP with auto-updates per 24hrs and/or manual updates simply done. uBlock auto-update set to 3-5 days seems lengthy, when an update interval's importance may be randomly tied to an important, non-cosmetic issue, namely in the domain of malware. This is why I prefer to update manually once a day as I do every morning with all system settings concerned by updates.

**Comment by gorhill** [comment]
Can you be more specific about the issue? I can't tell what you are reporting that specifically you think needs fixing.

**Comment by gorhill** [comment]
uBlock will download `checksums.txt` from github at most twice a day.

**Comment by ghost** [comment]
@gorhill commented on [17 mars 2015 18:09 UTC+1](https://github.com/gorhill/uBlock/issues/1041#issuecomment-82484405):

> Can you be more specific about the issue? I can't tell what you are reporting that specifically you think needs fixing.

No issue but where should one ask a question when there seems to be only a place for exposing issues? Up to now I would mention "Not an issue" but being the only one to say so I got to believe issues and simple questions were equally treated.

I still don't have the answers to my two questions above mentioned, but since this is not an issue lack of response is not an issue as well.
