### ISSUE TITLE
[Firefox] uBlock doesn't block at all when installed, until restarting Firefox

### ISSUE THREAD

**Issue by fireattack** [uBlock-LLC/uBlock#1045]
First, the ad is not blocked; second, the filers on chrome://ublock/content/dashboard.html doesn't show.

If ublock needs a restart to work, it should to tell the user to do so.

**Comment by fireattack** [comment]
[Imgur gallery showing the bug](http://imgur.com/a/KRNGq)

**Comment by chrisaljoudi** [comment]
Reproduced/confirmed on Firefox 36.0.1 on OS X 10.10.3.

**Comment by Deathamns** [comment]
Possible fix in the following two commits: c9f6a31, 6c0bde3.

**Comment by chrisaljoudi** [comment]
@Deathamns seems to be resolved as far as I can tell from my testing.
