### ISSUE TITLE
[Firefox] memory leak: zombie compartments and ghost windows

### ISSUE THREAD

**Issue by The-Feminist-Software-Foundation** [uBlock-LLC/uBlock#1046]
uBlock 0.9.11, Firefox 36.0.1, Linux x64.

As titled, there seems to be quite some leaks happening with the versions mentioned.  Compartments are zombified in the hundreds after a while of browsing.

`about:memory` returns a repeating pattern, under `js-main-runtime-compartments` and then `user`:

`[Expanded Principal], ublock:sb:$SOME_NUMBER[$SOME_URL | ] (from: chrome://ublock/content/frameModule.js:195)`

It's always `(from: chrome://ublock/content/frameModule.js:195)`.

**Comment by Deathamns** [comment]
I can't confirm. The compartments are gone after a while, or if I hit "Minimize memory usage" in `about:memory`.
On what pages have you tried, have you disabled/enabled the extension in the meantime?

**Comment by The-Feminist-Software-Foundation** [comment]
Mine stay even after minimising.

Pages tried in the session was an embarrassing mixture of 8chan, Reddit, eBay, Google, and Wikipedia.

I've disabled the extension in the meantime and fired up my old Privoxy adblocking solution.

**Comment by Deathamns** [comment]
I tested these sites, and everything seemed okay to me.
You'll see at least the amount of compartments as many tabs you have opened, more if the tabs have frames in them. Which is also okay.
Not okay would be, if those compartments stayed in the memory after you closed the tabs.

**Comment by gwarser** [comment]
@The-Feminist-Software-Foundation are you using one of these addons https://addons.mozilla.org/en-US/firefox/user/quicksaver/ ?

**Comment by The-Feminist-Software-Foundation** [comment]
Sorry to have wasted your time.  The leak originated elsewhere and was only magnified by uBlock.  Closing bug now and on with the leak hunting...

**Comment by The-Feminist-Software-Foundation** [comment]
The leak seems to be caused by Greasemonkey in conjunction with the [Youtube Link Title](https://greasyfork.org/en/scripts/413-youtube-link-title/versions) script.  Sorry about the mis-reporting!
