### ISSUE TITLE
chromium 19px browserAction icon is fuzzy

### ISSUE THREAD

**Issue by beaufortfrancois** [uBlock-LLC/uBlock#1049]
As you can see, vertical and horizontal edges are not as sharp as they could be. Do you mind sharing the source so that I can update the 19px png icon?
I'm not sure if you use SVG, that's why I'm asking. 

![screenshot 2015-03-19 at 10 06 11 am](https://cloud.githubusercontent.com/assets/634478/6727158/9a8eed88-ce1f-11e4-8327-68adbb8e7df2.png)

Last, but not least, this is a great project! Thank you!

**Comment by my-password-is-password** [comment]
https://github.com/gorhill/uBlock/blob/3c325442fcc73b673df20a7725ac1568857a4017/doc/img/ublock.svg

Don't know if that is the source file but the fuzzy part is the white border when the image get shrunk.

**Comment by gorhill** [comment]
> the fuzzy part is the white border when the image get shrunk

Yes.

The source is https://github.com/gorhill/uBlock/blob/master/doc/img/ublock.svg.

The border is 4-pixel wide when the icon is 128-pixel wide (4/128). This means ~0.5 pixel for 19-pixel wide. Setting the border to 1/19, translate into 8/128, which means a rather different icon than the reference one, and being as close to the reference one supersede not having sub-pixel rendering.

Please, do not submit pull requests, I am done spending time on this.

**Comment by harshanvn** [comment]
@gorhill 
Just wanted your opinion. Is below whitish border expected? It used not to be the case with earlier versions..
![ublock is correct](https://cloud.githubusercontent.com/assets/779630/6730508/b62d7688-ce13-11e4-9736-4a28a772589e.PNG)

**Comment by gorhill** [comment]
> Is below whitish border expected?

It's exactly a 0.5-pixel wide border. Expected.

**Comment by harshanvn** [comment]
Hmmm..OK.
One last question reg. this, and the border color should be in white color? Is it not supposed to be red or whatever ublock icon color is...it looks rather weird.

**Comment by gorhill** [comment]
It's not white. It's in between red and white, because it is a 0.5-pixel wide white border when uBlock's icon is rendered at 16-pixel.

**Comment by my-password-is-password** [comment]
Would these be ok?  I know you hate this issue.  Sorry.

icon19.png
![icon19](https://cloud.githubusercontent.com/assets/6408935/6776178/b20d8150-d0f8-11e4-918e-fae50789989f.png)

icon19-off.png
![icon19-off](https://cloud.githubusercontent.com/assets/6408935/6776181/c2766052-d0f8-11e4-8c76-93a55e7271cd.png)

Heres what it looks like on a black theme.
![ublockicon19onblacktheme](https://cloud.githubusercontent.com/assets/6408935/6776093/8c02b968-d0f7-11e4-9f13-9718b7811752.png)

Current icon19 on a black theme.
![ublockcurrenticon19onblacktheme](https://cloud.githubusercontent.com/assets/6408935/6776289/d792c416-d0f9-11e4-86a4-f57114094d3b.png)

**Comment by beaufortfrancois** [comment]
:+1:
