### ISSUE TITLE
Add the size of the requests to the request log.

### ISSUE THREAD

**Issue by felixq** [uBlock-LLC/uBlock#1052]
Add the size of the requests to the request log.

**Comment by gorhill** [comment]
Why?

**Comment by felixq** [comment]
I have a very limited monthly quota (800MB). And I'm constantly hunting for files that consume the quota. It is difficult to distinguish between many js what is trash and what is not. Having a column with size would allow me to devote myself to the biggest.

Currently I navigate without pictures, but I have found that since developers do not care about the size and number of js, some may reach several megabytes.

Excuse my English, my native language is Spanish.

**Comment by gorhill** [comment]
Just use the Network tab in the developer console. Size is pointless in the context of this extension.
