### ISSUE TITLE
[fennec] ublock options ui doesnt fit on screen

### ISSUE THREAD

**Issue by mihaisucan** [uBlock-LLC/uBlock#1053]
Using ublock 0.9.1.0 on firefox beta for android: options page has several tabs at the top which dont fit on the screen (lg d686 smartphone). Cant scroll to see the tabs. Looks like the page needs small changes to look/work better on small screens.

Thanks for your work. ublock is great!

**Comment by gorhill** [comment]
> screen (lg d686 smartphone)

It would save devs much time if the screen size was disclosed upfront. Now I am being asked to spend time to go look it up myself.

**Comment by harshanvn** [comment]
For Example in Nexus 4 (4.7", 1280 x 768 resolution). The Options UI will be cut down in portrait mode. You cannot scroll it, to see remaining options. In Landscape mode it is fine.

<s>I will provide a screenshot once i reach home. And update this post.</s>

![screenshot_2015-03-20-23-35-19](https://cloud.githubusercontent.com/assets/779630/6758041/5f7e11b4-cf5b-11e4-90f2-7f2b2929c983.png)

v0.9.1.2 (some dev build, not sure which one it is..)

**Comment by gorhill** [comment]
@harshanvn 768px is too narrow? I currently guessed 600px. Will wait for the screenshot (thanks for this) to see how it looks.

**Comment by mihaisucan** [comment]
You should appreciate people using your software and taking the time to report bugs. Sorry I forgot about mentioning screen size and resolution.

Size: 68 mm x 122 mm
Diagonal: 5.5 inch
Resolution: 540 x 960
Orientation: portrait
Density: 200 dpi

(as reported by aida64)

Thank you.

**Comment by my-password-is-password** [comment]
@gorhill On Firefox theres "Responsive Design View" ( <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd> ).  I think you use the CSS values found on http://mydevice.io/devices/ to see what it would look like on the phone.

And on Chrome there's Device Mode found in the console.
![chromedevicemode](https://cloud.githubusercontent.com/assets/6408935/6757712/5821e780-cef0-11e4-8d08-e2bd7005f19e.png)

**Comment by harshanvn** [comment]
> You should appreciate people using your software and taking the time to report bugs.

It is often better to give information upfront, Instead for the dev  to start guessing & hunting for the things. it makes the fix easier.
At least that we can help as the people using the software!! ;)

> And on Chrome there's Device Mode found in the console.

I wish, it is rendered same for firefox too. :(

**Comment by gorhill** [comment]
> And on Chrome there's Device Mode found in the console

Wow I never noticed this. Nice.

**Comment by my-password-is-password** [comment]
Using `0.9.1.2-dev.9` and it looks great on my phone ( Galaxy s4 ).
