### ISSUE TITLE
Youtube annoyances

### ISSUE THREAD

**Issue by TCCB** [uBlock-LLC/uBlock#1056]
Hi, does UBlocker have a way to block youtube annoyances, such as comments, suggested videos, etc. the way Adblock Plus has, as seen here: https://youtube.adblockplus.me/en/ ?

Please let me know, I'm very happy with uBlock, but there are a few things that I feel it's missing this being one of them. 

Thank you.

**Comment by gorhill** [comment]
Click the `+ add` button on that site while uBlock is active.
