### ISSUE TITLE
[Firefox] "Make use of context menu where appropriate" not enforced nor remembered

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#1057]
As reported on [Wilders Security](http://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-31#post-2471528):

> 0.9.1.1 the setting Make use of context menu where appropriate does not stay set. i uncheck it and restart firefox and it is rechecked again. tried this numerous times. also uninstalled and reinstalled and same thing

**Comment by gorhill** [comment]
When de-selecting the setting, `this.contextMenu.toggle(value);` throws an exception.

**Edit:** `vAPI.contextMenu.remove()` is not implemented for the Firefox.

**Comment by Deathamns** [comment]
I thought [it wasn't used](https://github.com/gorhill/uBlock/commit/f20372cf73f4a9908b4e6810ce4e06e6133928c1), my bad.

**Comment by baskerville** [comment]
I'm experiencing this issue (μBlock 0.9.1.0.1, Firefox 38.0.5).
