### ISSUE TITLE
[Request] Show "3rd-party filters list" info when category is collapsed

### ISSUE THREAD

**Issue by my-password-is-password** [uBlock-LLC/uBlock#1058]
So we don't have to expand each one to see what lists we have selected. 

![ublockcollapsedlists](https://cloud.githubusercontent.com/assets/6408935/6762942/c47e4bd0-cf27-11e4-8914-c11abd4bf46c.png)

**Comment by gorhill** [comment]
Good idea. I found myself wondering sometimes if there was anything selected under a collapsed group.

Question: I see the top buttons are touching the navigation bar.. I can't see this here. Is this caused by some custom modifications?

**Comment by my-password-is-password** [comment]
That was from an older build.  Don't remember what build I modified though.

**Comment by my-password-is-password** [comment]
It happened when I pasted my modified files into the new build.

https://github.com/my-password-is-password/stuff/blob/master/3p-NumberInfo.zip

**Comment by chrisaljoudi** [comment]
@my-password-is-password you added this to the CSS file:

``` css
#options {
    margin-top: 0;
}
```

That's what's causing the symptom above.

**Comment by my-password-is-password** [comment]
@chrisaljoudi  Whoops. Thanks.
