### ISSUE TITLE
uBlock for Internet Explorer?

### ISSUE THREAD

**Issue by Decme** [uBlock-LLC/uBlock#1063]
Probably not the best place to ask this, but quick question, would this ever be workable on Internet Explorer?

**Comment by lewisje** [comment]
I know that Eyeo decided to embed the V8 engine to make Adblock Plus workable in IE, but that isn't working so well.

**Comment by my-password-is-password** [comment]
Isn't Internet Explorer going to die in Windows 10 anyways?  I read they have a new browser.

**Comment by Havokdan** [comment]
Two in Windows 10, IE and Spartan, maybe support for Spartan.

**Comment by 0xBRM** [comment]
I read somewhere that Spartan will support Chrom*'s API.

**Comment by chrisaljoudi** [comment]
[On "Spartan" extension APIs](http://www.windowscentral.com/microsofts-spartan-browser-windows-10-reportedly-supports-chrome-extensions).

**Comment by ghost** [comment]
IE will not be developed anymore with Windows 10, it will only be for support for old site and app using it.

**Comment by lewisje** [comment]
Even so, it might be useful to have an IE port for people who are stuck on that browser, like people still using Vista with IE9 (which Microsoft still supports), and if it turns out to be not much harder to support IE8, why not? (Again, looking at ABP, it managed to initially support even IE6, although it ended up scaling back to IE8 because of Server-Name Indication issues with the sites that many of the filter lists are loaded from.)

**Comment by Decme** [comment]
Well just an example, some of my colleagues at work are forced to use IE (they're probably on v11) I myself managed to (illegally) get Firefox onto my work pc, but I noticed the only adblock solution for IE requires running a .exe file ( https://adblockplus.org/releases/adblock-plus-14-for-ie-released ) which won't work, as ALL .exe files at work are blocked from running unless admin approved. There's probably other people out there stuck with IE at their jobs where their computers are even more locked down than mine.

**Comment by lewisje** [comment]
_All_ IE extensions require installation via EXE or MSI; as far as I know, only plugins can be installed any other way, and chances are they're blocked too.

At least you can use Tracking Protection Lists (TPLs) for _some_ protection, I hope.

**Comment by chrisaljoudi** [comment]
I've stashed this until uBlock is stable and complete enough that a developer might be interested in creating the IE port.
