### ISSUE TITLE
[Question] Exceptions to filter in a list

### ISSUE THREAD

**Issue by my-password-is-password** [uBlock-LLC/uBlock#1064]
## Steps to Reproduce
1. Remove/Comment out `behind-the-scene` from "Whitelist"
2. Have "Anti-Adblock Killer | Reek‎" filter selected
3. Try to update
## Symptoms

The list blocks itself from downloading with this filter:  [/anti-adblock$~stylesheet](https://github.com/gorhill/uBlock/blob/master/assets/thirdparties/raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt#L117)  .  When I tried to make an exception that looked like it would work, it didn't.

These didn't work:

```
@@/anti-adblock$important,xmlhttprequest,domain=githubusercontent.com
@@/anti-adblock$xmlhttprequest,domain=githubusercontent.com
@@/anti-adblock$important,domain=githubusercontent.com
@@/anti-adblock$domain=githubusercontent.com
@@/anti-adblock$important
```

Are those not valid exceptions?  Am I not understanding something?

<hr>

These worked:

```
@@/anti-adblock$~stylesheet
@@||.githubusercontent.com/reek/anti-adblock$xmlhttprequest
@@|https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
```

```
uBlock :  some dev build of 0.9.2.0 
Browser: Chromium Dev build 43.0.2340.0 (64-bit)
```

**Comment by gorhill** [comment]
> Are those not valid exceptions?

Yes. But they apply only when the document firing these network requests is `githubusercontent.com`. `behind-the-scene` is not `githubusercontent.com`.

The `important` filter option is meaningless for exception filters, because exception filters always override block filters.

Working as expected as far as your report shows.

**Comment by my-password-is-password** [comment]
Oh, can I use domain=behind-the-scene then?

**Comment by gorhill** [comment]
I am guessing yes, but I never tried really.

**Comment by my-password-is-password** [comment]
Cool, it worked.  Thanks and sorry for bothering.
