### ISSUE TITLE
[Safari] UI is shrunk with latest update

### ISSUE THREAD

**Issue by JBey4you** [uBlock-LLC/uBlock#1066]
Hey there! Little problem here with the latest uBlock update. The UI is shrunk, not sure why. I don't think it happened before. Below, the UI from Safari and the UI from Chrome.

![ublock safari shrunk](https://cloud.githubusercontent.com/assets/7979756/6766564/7ce7b68c-d00b-11e4-8ea5-1e78bbbe86a6.jpg)

![ublock good chrome](https://cloud.githubusercontent.com/assets/7979756/6766566/7efac112-d00b-11e4-9000-0936e5f09d4d.jpg)

**Comment by chrisaljoudi** [comment]
@JBey4you what do you mean by "shrunk"? Can you please provide a "bigger" screenshot (that includes the whole popup with the surroundings)?

P.S.: if there is an issue with the popup sizing, a Safari restart should fix it.

**Comment by JBey4you** [comment]
Well, there is a difference between the first screenshot (Safari) and the second (Chrome). Some text is missing on the left.

Here's a larger screenshot. By the way, I restart Safari and the result is the same.

![capture d ecran 2015-03-21 a 21 02 22](https://cloud.githubusercontent.com/assets/7979756/6766624/afa88b62-d00d-11e4-9c27-415898b992b5.jpg)

**Comment by chrisaljoudi** [comment]
Ah, got it — it only occurred with translations with "longer" sentences. Fixed in 93d26f6.
