### ISSUE TITLE
[Safari]: 0.9.2.0 is now resizing each time you open it

### ISSUE THREAD

**Issue by mike-to-spec** [uBlock-LLC/uBlock#1068]
![](http://miket.d.pr/ulWo/5I5bR7Oe.gif)
## Symptoms

Before 0.9.2.0, the full view was just opened fine without resizing. Now, it is resizing each single time and it is annoying. 

```
uBlock version:
    0.9.2.0
Browser and version:
    Safari 8.0.5
OS and version:
    OS X 10.10.3
```

**Comment by mike-to-spec** [comment]
@chrisaljoudi I think this is another one of those migration bugs. Direct update from .9.1 to .9.2 will result into this bug.

I just collapsed the view and expanded it, now it stay fixed for good. Maybe it was missing a value and kept resizing until it is explicitly set by expanding it again?

**Comment by Betsy25** [comment]
@gorhill Latest fix made the popup opening in Firefox nightly v39 **perfectly fine**.
No more slight flashing and resizing effects whatsoever.
Thanks !

**Comment by Betsy25** [comment]
Seems like the "perfect" opening in FF nightly v39 is gone, and showing temporary auto-resizing issues (although  barely noticeable) again since a couple of commits.
