### ISSUE TITLE
[Firefox] New icon requires restart to apply changes to toolbar

### ISSUE THREAD

**Issue by 5t3f4n** [uBlock-LLC/uBlock#1069]
After upgrading from 0.9.1.1 to 0.9.2.0 the new (u) icon is immediately visible in about:config but the (µ) icon remained in the toolbar until restarting Firefox. Only discovered this "fix" by accident when I restarted to apply the 36.0.4 update.

Safari 8.0.4 did not have this problem. New icon in toolbar was immediately visible.

**Comment by gorhill** [comment]
Once you restarted, did the old icon showed up again?

**Comment by 5t3f4n** [comment]
No, the old one was only there <b>until</b> I restarted.  I have tried quitting/restarting and disabling/enabling back and forth and can't make the old icon reappear. It was probably the one time only. But being a "restartless" extension I'm still guessing this is undesirable behavior. Browser bug?

**Comment by gorhill** [comment]
I don't know, but for such an "issue", not worth  to spend time on this. That an older icon shows instead of  a newer one until Firefox is restarted is certainly not worth spending time and throwing more code in.

**Comment by 5t3f4n** [comment]
If the issue is a purely cosmetic one then I definitely agree. I just wanted to bring it to light in case it was a symptom of a bigger issue.
