### ISSUE TITLE
Combine EasyList and EasyPrivacy

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#107]
Combine EasyList and EasyPrivacy options with this:

<code>https://easylist-downloads.adblockplus.org/easyprivacy+easylist.txt</code>

You could remove EasyList and EasyPrivacy options from uBlock and combine them with EasyPrivacy+EasyList option. You could add EasyPrivacy+EasyList option to Multipurpose section.

**Comment by gorhill** [comment]
That would cause a problem for people who do not want one or the other. I think it's all fine the way it is.
