### ISSUE TITLE
[Firefox Mobile] closing all tabs confuses ublock

### ISSUE THREAD

**Issue by WalterWW** [uBlock-LLC/uBlock#1072]
Steps to reproduce:

Open a random website with no other tabs open, then close that tab to go back to firefox's about:home screen.

Now the dropwdown still shows the number of blocked items from the previously closed tab: http://i.imgur.com/wMCzizP.jpg
~~(this might be related to #1071 )~~

Opening the ublock menu then shows this overview: http://i.imgur.com/RfFP0Rx.jpg
In the screenshot above even my 3rd party block rules are missing. This is what it normaly would look like: http://i.imgur.com/XMPnPmc.jpg

**Comment by gorhill** [comment]
I suspect an exception is thrown, that would explain the cells not being properly initialized.

**Comment by AlexVallat** [comment]
This appears to be a side effect of a more serious issue. In Fennec, we've worked around the lack of a `tabsProgressListener` by notifying of navigation in the httpObserver instead, if it is a main frame (as discussed in #524). Checking in the debugger, perhaps unsurprisingly, no http request is made for about:home, and so no `vAPI.tabs.onNavigation` is called. More seriously, this will also be the case if the page is simply pulled out of session cache from using the back and forwards buttons. This means that the pageStore is still bound to the old URL and therefore the count is wrong, and the popup will be wrong if clicked on.

Looks like we might need to think up an alternative solution...
