### ISSUE TITLE
Blank popup image in dynamic

### ISSUE THREAD

**Issue by DiabSoule** [uBlock-LLC/uBlock#1074]
Whenever I check advanced user the popup becomes half blank with no power button at all. I have tried all I know with no luck. Is there a fix?

**Comment by ozar** [comment]
What browser and operating system?  Are you running the latest version of uBlock?

**Comment by DiabSoule** [comment]
I am using firefox 36.0.1 on Ubuntu 15.04gnome

**Comment by DiabSoule** [comment]
yes latest ublock also

**Comment by gorhill** [comment]
It would be nice to have screenshot of the problem.

**Comment by DiabSoule** [comment]
Not a problem here ya go!
![desktop_022](https://cloud.githubusercontent.com/assets/11603431/6835511/411894a4-d309-11e4-848b-4f4a7e978df6.png)

**Comment by gorhill** [comment]
Looks to me there are some customizations going on in there, I do not have that border with my Firefox 36.0.4, it is only 1-pixel wide on my side.

**Comment by gorhill** [comment]
Do you have custom styles in your Firefox?

Example of how this can cause issues: https://github.com/gorhill/uBlock/issues/806#issuecomment-74438771

**Comment by DiabSoule** [comment]
I am using duckduckgo's dark theme and the blackfox v2-blue addon. I will try with those disabled and see what happens.

**Comment by chrisaljoudi** [comment]
@DiabSoule yep, looks like it's from BlackFox V2-Blue.

**Comment by DiabSoule** [comment]
It is. I just ran it. Can that be tinkered with to make it work?

**Comment by chrisaljoudi** [comment]
@DiabSoule no idea.

**Comment by gorhill** [comment]
The popup uses standard HTML/CSS/JS. That something else interferes with it is something that should be fixed by whoever is causing the interference.
