### ISSUE TITLE
Youtube video playback freeze every 2-5 minutes

### ISSUE THREAD

**Issue by Montago** [uBlock-LLC/uBlock#1077]
Everytime youtube tries to inject commercials, uBlock blocks them, but the video freeze in 5 seconds when it happens. 
The Video freeze but the audio continues. 

This happens in Firefox and Chrome: Although in Chrome the video never resumes !!

Video is played with HTML5 (not flash)

**Comment by gorhill** [comment]
Please give me a URL where you have seen this happen, it saves me time.

**Comment by gorhill** [comment]
Also your filter lists, dynamic rules, etc.

**Comment by Montago** [comment]
https://www.youtube.com/watch?v=lJMKEUrN9yo

regarding uBlock settings, its all vanilla. uBlock is also the only plugin i've installed. 

Adobe Flash has been completely uninstalled on my machine too.

**Comment by gorhill** [comment]
Here is what I observed on Chromium:

I noticed once in a while frame freeze, for a few seconds, like 2-3 seconds, then it resumed fine. By looking at the network request log, I could not correlate this to _"youtube trying to inject commercials"_ as you state. It is random from what I can tell, but that freeze definitely happens.

However, I completely disabled uBlock (in `chrome://extensions`), and re-launched the browser. After skipping the ad at the beginning, the player exhibited exactly the same behavior: once in a while it freezes for a couple of seconds.

So this has nothing to do with uBlock, it's obviously a Youtube issue. If you try to search the web for this issue, you will notice a whole lot of people complain about this. I have seen suggestion to clear the browser cache.

In any case, not a uBlock issue,  Youtube issue, as it still occurs without uBlock.

**Edit:** same issue on Firefox and again, without uBlock enabled.

**Edit:** for the curious, on my side I get a first freeze at the ~24-second mark, Chromium or Firefox, with or without uBlock.

**Comment by Montago** [comment]
thanks

The reason why i jumped to conclusion, was because uBlock would count up 1-3 blockings everytime it froze..

**Comment by gorhill** [comment]
There is a constant flow of network requests blocked when playing a Youtube video: this is because of EasyPrivacy. You can look at what is blocked by opening the [network request logger](https://github.com/gorhill/uBlock/wiki/The-network-request-logger).

**Comment by gorhill** [comment]
By the way, the "freezing" is probably how the video was captured, i.e. I doubt this is even a Youtube issue: it's part of the captured footage (my guess).
