### ISSUE TITLE
whitelist wildcard not working when url contains # as wildcard

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1078]
uBlock doesn't whitelist when the url contains # as wildcard, after wildcard works.
My actual case is with a youtube video with time stamp and the whitelist channel script which adds the user name at the end of the link for whitelisting.

my case:
whitelist "youtube.com/*&user=example"
https://www.youtube.com/watch?v=VIDEOID&user=example ------------- inactive
https://www.youtube.com/watch?v=VIDEOID#t=100&user=example ---- active! - expected: inactive

test case:
whitelist "example.org/*/page"
http://example.org --------------- active
http://example.org/1/page ----- inactive
http://example.org/1/page# --- inactive
http://example.org/#/page ----- active! - expected: inactive
http://example.org/#/1/page --- active! - expected: inactive

**Comment by gorhill** [comment]
Yes, the fragment part is removed before testing a match. I didn't expect users wanting to activate/de-activate uBlock depending on the value of the fragment identifier.

I see the [greasyfork script](https://greasyfork.org/en/scripts/4168-youtube-whitelist-channels-in-adblock-plus) adds the `&user=[...]` at the end, regardless of whether it's adding it to the fragment identifier.

**Comment by my-password-is-password** [comment]
Oh, so the '#' wasn't the comment character?  I've been using it to comment since it turns red for '!'.

**Comment by gorhill** [comment]
It is the comment character, if it is the **first** character.

**Comment by gorhill** [comment]
@anon23462 You say "`http://example.org/1/#page` --- inactive". Are you sure? I can't reproduce that case, and if you look at it, this is expected, as there is no `/` before `page`.

**Comment by ghost** [comment]
Oh, yeah sorry. That one should've been "http://example.org/1/page#" as a case where the whitelisting works since the # is in the url part after the wildcard.
