### ISSUE TITLE
Feature Request: Whitelist wildcard ips

### ISSUE THREAD

**Issue by mnaiman** [uBlock-LLC/uBlock#1081]
Hello, I want to exclude filtering on 192.168._._ or 10._._.\* etc. How to make it possible?

**Comment by ghost** [comment]
> How to make it possible?

I don't think you can, currently.
https://github.com/gorhill/uBlock/issues/669#issuecomment-72550066

> However I realize I didn't take into account that the target of whitelisting could be an IP address. Well it would work with an IP address, but what you want is 192.168.*/, and currently a wildcard at the end of a hostname is not allowed (because it would be impossible to create an efficient dictionary).
> 
> So I need to extend the whitelisting code to support explicitly IP address, and in the case of IP address, the wildcard need to go at the end, when one is used.

**Comment by gorhill** [comment]
Duplicate of #669.

**Comment by scottyd5** [comment]
Hi, I can't seem to get this to work. I have uBlock Origin v1.6.8 installed and I want to whitelist 192.168.1.\* but the line always gets commented out. I've tried `192.168.1.*/` and nothing works.
