### ISSUE TITLE
[Safari]: Escaping uBlock will focus the address bar

### ISSUE THREAD

**Issue by mike-to-spec** [uBlock-LLC/uBlock#1083]
This is something I notice only with uBlock and I'm not sure if it is a bug in uBlock or Safari. 

If you click on uBlock icon, then click away like the toolbar area, Safari's address bar will be focused and this brings up the top ten sites, which gets in the way. 

Other extensions don't do this and I was wondering if uBlock can stop focusing the address bar in Safari.

**Comment by chrisaljoudi** [comment]
@MikhailTNY Hi! I can't quite reproduce this.

[Here's a quick recording of me trying to reproduce it](http://cl.ly/aLiH) — am I doing something wrong?

**Comment by mike-to-spec** [comment]
@chrisaljoudi, hmm, maybe full-screen bug? Try this:
1. Put Safari in full screen mode
2. Open a new tab, go to google.com
3. Click on uBlock and click away again on the toolbar

Does it focus for you? It does for me a few times.

**Comment by mike-to-spec** [comment]
I can also do it when clicking on a link to open in a new tab, so manually opening a new tab isn't the only STR. 

Note, I have Safari set to always open in a tab and CMD+Click is set to open in a new tab.

**Comment by chrisaljoudi** [comment]
@MikhailTNY so it only occurs in full-screen?

**Comment by mike-to-spec** [comment]
@chrisaljoudi I'm starting to think so. I don't recall seeing this on my iMac, where I don't use full screen but on my MacBook, I do use it all the time and I see this more often.

**Comment by chrisaljoudi** [comment]
@MikhailTNY the thing is, I can indeed reproduce it in full screen, but I can also reproduce it with any other extension that has a popover.

**Comment by mike-to-spec** [comment]
OK, then it is a bug in Safari. I'll file a radar. 

Thanks for confirming it.

**Comment by mike-to-spec** [comment]
@chrisaljoudi Can you give me a few examples of your popover extensions, so Apple can test them as well as uBlock.

**Comment by chrisaljoudi** [comment]
@MikhailTNY Sure!
- [eBay Manager](https://extensions.apple.com/details/?id=com.ebay.safari.myebaymanager-QYHMMGCMJR).
- [DuckDuckGo](https://extensions.apple.com/details/?id=com.duckduckgo.safari-HKE973VLUW).

**Comment by mike-to-spec** [comment]
Thanks!

**Comment by chrisaljoudi** [comment]
@MikhailTNY thanks for filing the bug with Apple; appreciated.
