### ISSUE TITLE
[firefox] favicon.ico/favicon.png are categorized as "Behind the scene"

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#1085]
As the title states, when you visit most of the sites in firefox, few of the requests are categorized under "Behind the scene.."
## Steps to Reproduce:
1. Open Network request logger, and select "Behind.." in the dropdown
2. Open below listed of sites..
   <code>http://www.wilderssecurity.com/ </code>
   <code>http://www.tomshardware.com/</code>
3. You will see below requests categorized under "Behind the scene.."
   <pre>
       image   http://m.bestofmedia.com/i/tomshardware/favicon.png
       other   http://www.wilderssecurity.com/favicon.ico </pre>

Note: Am able to get same behavior irrespective of Advanced mode. I do not think, we need to have exact custom filter lists info here, if needed I will provide them. 
## Config:

```
uBlock v0.9.2.1 
FF v36.0.4, W7
No other add-on enabled
```

**Comment by gorhill** [comment]
Network requests for favicons are categorized as behind-the-scene because they occur behind the scene.

**Comment by harshanvn** [comment]
hmm..ok.

So, if i open <code>google.co.in</code>

I see behind-the-scene requests only in firefox, but not in chrome. (I cannot test above other sites in chrome, as they are blocked for me in office.)
Is this expected behavior for Chrome Vs Firefox?
And can these behind-the-scene requests be blocked?

**Comment by gorhill** [comment]
Network requests which ends up behind the scene is very platform-specific: when a network request has no information about which tab it comes from, it ends up in the behind-the-scene category.

For Chromium, I definitely remember favicons being categorized as behind the scene when I was working on HTTPSB. I tried again, going to a site which I was sure its favicon was not in the cache, and it appears now the favicons now are no longer fetched without tab information. It is now pulled as one of the last requests, while before it was pulled before the page itself was requested.

**Comment by gorhill** [comment]
For example another difference between Chromium and Firefox: Github makes use of `navigator.sendBeacon`. The network requests to `google-analytics.com` as a result of `navigator.sendBeacon` ends up as behind-the-scene requests with Chromium, while they are properly reported as originating from the tab from which they were fired with Firefox.

**Comment by harshanvn** [comment]
> Network requests which ends up behind the scene is very platform-specific: when a network request has no information about which tab it comes from, it ends up in the behind-the-scene category.

Thanks! This makes sense to me now.

> For example another difference between Chromium and Firefox: Github makes use of navigator.sendBeacon.

Yes, I do remember it now. You were discussing about these  difference before.

You may categorize this as "invalid issue"
