### ISSUE TITLE
adblocker detection by website

### ISSUE THREAD

**Issue by typhoon71** [uBlock-LLC/uBlock#1087]
I noticed a site I visited some time ago now detects adblockers.
Before I used adblock and I don't remember it noticing it, but I could be wrong.
Here's the site: http://riparodasolo.altervista.org. 
Click on any article and wait for it to load.
You'll get a banner after a while.
If I stop the loading of the page after a bit, I can see the article and the banner doesn't load.
Seems like just at the end of the page there's a redirection if an adblocker is detected.
Is it possible to fix this?

**Comment by gorhill** [comment]
I get same result with ABP.

Sorry but I do not have time to maintain filter lists aside the one needed to address issues specific arising from the use of Peter Lowe's hosts file by default.

**Comment by typhoon71** [comment]
Too bad.

**Comment by gorhill** [comment]
Try

```
! 24/03/2015 12:36:46 http://riparodasolo.altervista.org/
||riparodasolo.altervista.org^$inline-script
riparodasolo.altervista.org###page > #colophon > div:nth-of-type(3)
```

I got curious about the challenge of defeating their obstacles. But as said, as I don't have time for this, "too bad" is also what IRL people are telling me for all the time I spent on this project.

**Comment by TteokbokkiNari** [comment]
> "too bad" is also what IRL people are telling me for all the time I spent on this project.

Some people. :(
You're doing a great job, @gorhill ! A bunch of people appreciate it. Keep up the good work. :)

**Comment by typhoon71** [comment]
No, wait, I didn't mean it like that. I meant it was too bad that I couldn't remove that thing.
I did try to create a filter myself but I failed, that's why I asked here.
I do understand that you're investing a lot of time on this, and I do respect you for doing this.
I would not be able to do something like uBlock by myself, and you do a great job, not asking tips on top of that.
Hence "too bad" meant that I would've lived with that "issue" on that website, since I could live with it (it's not like I need to fix appliance every day).
Will try that rule you posted now!

**Comment by typhoon71** [comment]
Great, it works perfectly.
Btw, I noticed the page now loads faster (the activity indicator on the tab stops right away, before this rule it continued signaling activity for a while).
Thanks a lot.

**Comment by gorhill** [comment]
> I didn't mean it like that.

I know. I meant it more as a reminder for lurkers to not assume I will always be up to figure filter recipes.

Btw, the filters above disable inline javascript, so the site might be a bit crippled, but at least it is readable now.
