### ISSUE TITLE
metrics.js blocked on jhipster development site

### ISSUE THREAD

**Issue by tagliola** [uBlock-LLC/uBlock#1088]
On my development machine, two js files are blocked from a site generated with https://github.com/jhipster/generator-jhipster. I'm not sure on which side of the fence (on jhipster, on ublock or on maybe on a specific filterset) this should be, the files are blocked if served from localhost/127.0.0.1, as well as using the external ip address, as seen by the screenshot.

![jhipster-ublock](https://cloud.githubusercontent.com/assets/1526633/6811193/805df7ec-d266-11e4-8a92-3a2e1d58098b.png)

**Comment by gorhill** [comment]
`/metrics/metrics` is a filter in EasyPrivacy.

**Comment by gorhill** [comment]
EasyPrivacy is 3rd-party to uBlock: https://forums.lanik.us/viewforum.php?f=64.

**Comment by tagliola** [comment]
Thanks, I will proceed there.
