### ISSUE TITLE
Question: AMO Can't Keep Up So uBlock.firefox.xpi?

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1089]
Hi,

Sorry if this has been asked before, I can't find anything.

Since AMO can't keep up with the releases, can we just download the latest uBlock.firefox.xpi, and it will update it ok, doing it this way?

thanks

**Comment by WalterWW** [comment]
Yes, you can install the latest xpi here and it will update your current installation of ublock.
https://github.com/gorhill/uBlock/releases

**Comment by ghost** [comment]
Great thanks, for some reason I always thought once you installed an addon you had to update it through firefox...

**Comment by hackel** [comment]
To clarify, it does not auto-update at this time, correct?  That would be a really great feature, if the XPIs released here checked github for new releases instead of AMO.

Edit: nevermind, this has already been covered in #925 and #1036.
