### ISSUE TITLE
Videos don't work on some websites

### ISSUE THREAD

**Issue by JBey4you** [uBlock-LLC/uBlock#109]
With uBlock, the video here doesn't play: http://recode.net/2014/05/30/apples-jimmy-iovine-and-eddy-cue-explain-the-beats-deal-and-hint-at-the-future-video/.

With AdBlock Plus, it works. Not sure why since I'm using the same lists. Maybe it affects other websites, I only found the problem on Re/code for now.

It's the same with embed videos (see here: http://9to5mac.com/2014/05/28/eddy-cue-apple-has-the-best-product-pipeline-in-25-years-coming-later-this-year/).

**Comment by gorhill** [comment]
Both videos played fine here. What lists do you have enabled?

**Comment by JBey4you** [comment]
My rules, uBlock filters, EasyList,  EasyPrivacy and  FRA: EasyList Liste FR.

**Comment by gorhill** [comment]
Chromium:
- ABP + EasyList + EasyPrivacy = video doesn't work.
- uBlock + EasyList + EasyPrivacy + Peter Lowes' = video doesn't works
- uBlock + EasyList + EasyPrivacy + Peter Lowes's + hpHosts = video works

Google Chrome:
- ABP + EasyList + EasyPrivacy = video works.
- uBlock + EasyList + EasyPrivacy + Peter Lowes' = video doesn't works
- uBlock + EasyList + EasyPrivacy + Peter Lowes's + hpHosts = video works

I will keep investigating and add info to narrow down.

**Comment by gorhill** [comment]
Alright, here is what I found so far:

In _EasyList_, there is this filter: `|v.fwmrm.net^$object-subrequest,third-party`

So uBlock blocks this net request: `http://29773.v.fwmrm.net/ad/p/1?` (type `plugin`)

ABP doesn't block the above request. I have to find out why. I need to find out the exact semantic of `object-subrequest`, my implementation transposes it into `object` request type.

**Comment by ghost** [comment]
Working fine here with Chromium v38x64 and uBlock v0.3.0.2. EasyList also enabled.

**Comment by gorhill** [comment]
> Working fine here with Chromium v38x64

You must have extra lists enabled, because it's not supposed to work.

**Comment by ghost** [comment]
92,325 network filters ＋ 40,500 cosmetic filters.

**Comment by gorhill** [comment]
Ok, I've narrowed the problem.

There is a piece of missing infrastructure which is not part of uBlock, but which is present in ABP, which is that in ABP, whether a request if 1st- or 3rd-party is determined by the **frame** from where the request originates, while in uBlock 1st- or 3rd-party is determined by the **tab** from where the request originates.

Now the interesting thing is that the video will work in Google Chrome if you enable _hpHosts’s Ad and tracking servers_ (which is a list [I wish to enable by default out of the box](https://github.com/gorhill/uBlock/issues/17)), and apparently this is caused by this list blocking an extra request (among others), `http://livepassdl.conviva.com/crossdomain.xml`, which content is:

```
<cross-domain-policy>
    <allow-access-from domain="*" secure="false"/>
    <allow-http-request-headers-from domain="*" headers="*" secure="false"/>
</cross-domain-policy>
```

So as a fix for this bug, I am thinking of just adding `||livepassdl.conviva.com/crossdomain.xml^` to uBlock's filters: the good part of that fix is that we end up blocking more unwanted stuff, rather than allowing more unwanted stuff to make the video work.

Another nice thing with this fix is that it will work as well for Chromium on Linux, while ABP fails to play the video properly on that platform because it's missing things to implement its infrastructure (because Flash is NPAPI).

**Comment by ghost** [comment]
Blocking even more unneeded stuff is always recommended. :+1:

**Comment by gorhill** [comment]
Actually, after further testing, I've narrowed to this filter: `||adm.fwmrm.net^`. Adding this one makes the video work.

**Comment by gorhill** [comment]
Go to _About_ tab in dashboard, `ublock/filters.txt` should be marked as "updated version available". Click the update button at the bottom to force an update. Videos should work afterward.

**Comment by JBey4you** [comment]
Yep, it works now! I see you added <code>$domain=recode.net|9to5mac.com</code>; that means it doesn't work on other websites? (Maybe it's not needed after all?)

**Comment by gorhill** [comment]
I am really worried about site breakage, so I went with a very narrow and conservative solution. 

Personally I use all the multipurpose lists (except Fanboy Ultimate), which will block `adm.fwmrm.net` everywhere, but as I am currently pretty much alone to investigate/fix breakage I can't afford to enable these lists by default. Ideally there would be a little army of volunteers who can track down that sort of things, so then maybe we could enable out of the box these lists, but so far I feel rather lonely (except for the volunteers taking care of the translation work of course).

**Comment by JBey4you** [comment]
I know it's closed, but I found another one! Actually, it's more related to a filter and no uBlock: you can't watch videos hosted on ooyala.com. Popular websites, like The Verge, use this.

The problem is with the hpHosts’s Ad and tracking servers list. I added since you're recommended it. But when you look into the file, you see : 
<code>127.0.0.1 l.ooyala.com
127.0.0.1   l.player.ooyala.com</code>

Are you sure hpHosts’s Ad and tracking servers is a really interesting list to add?

**Comment by gorhill** [comment]
`l.ooyala.com` and `l.player.ooyala.com` are also both in _EasyPrivacy_.

uBlock's filters were updated to add an exception which unbreaks videos on The Verge. Any other issues which are thought to be caused by hpHosts need to be entered in the meta issue #17.

**Comment by JBey4you** [comment]
It works with EasyList enabled actually. (Noted about #17.)

**Comment by gorhill** [comment]
Problem here wasn't really hpHosts, it's that uBlock doesn't follow ABP's interpretation of what is a 3rd-party. I realized that today, and at this point I want to think this through, whether I should follow exactly the same semantic or not. So far for me 3rd-party meant that whatever is embedded in the page, is 3rd-party if not from the same domain, including an `iframe` content. I will have to determine whether I follow ABP's semantic or whether such filters are rare enough to be worth to create custom exceptions to work around those maybe rare issues.

**Comment by gorhill** [comment]
Thanks for having reported by the way, another small step toward being able to use hpHosts eventually maybe.

**Comment by JBey4you** [comment]
No problem. I use uBlock daily, it's a good point for me to notice those kind of things since it's a "problem". ;-)

**Comment by harshanvn** [comment]
personally, i use hpHosts lists along with fanboy ultimate, of course very few of them got used in it as most of them are covered by remaining lists..
i use quite a few of video streaming sites, i have not faced much issue with hpHosts..
maybe by tomorrow, i will visit as many video streaming sites as possible from watchseries.net and see if anything breaks..
