### ISSUE TITLE
Defeat adblock detection?

### ISSUE THREAD

**Issue by mzso** [uBlock-LLC/uBlock#1090]
Hello!
I ran into to this nasty adblocker detection on a website. Example url:
http://www.spoilertv.com/2015/03/once-upon-time-episode-416-best-laid_23.html

[I had this problem with abp too](https://adblockplus.org/forum/viewtopic.php?f=2&t=26012), but with that I could determine the cause.
But lacking a list of rules applied I can't do the same with ublock. Also as far I can tell there's no way to disable a specific rule in ublock.

But it also gets weirder. I don't have the same subscription now that had the problematic rule with ABP, so I've been disabling/enabling subscriptions to figure out which is the cause.
What I found is that if I disable a subscritpion. The detection does not activate for the first reload, but after that it's activated again. Even weirder that the same thin happens when I re-activate the subscription...

**Comment by gorhill** [comment]
I don't maintain filter lists, you should seek help with maintainers of filter lists: EasyList, Reeks' Anti-Adblock Killer, etc. Sometimes it may even be necessary to make use of a user script. The lists maintainers know better about what to do.

If that is of any help, I use default-deny and I do not get the warning, until `cdnjs.cloudflare.com` is unblocked. So there is a script downloaded from `cdnjs.cloudflare.com` which is responsible for the anti-adblocking.

> lacking a list of rules applied I can't do the same with ublock

There is the network request logger, but it currently does not show the effects of cosmetic filters (#308).
