### ISSUE TITLE
Guess the filter!

### ISSUE THREAD

**Issue by Stanzilla** [uBlock-LLC/uBlock#1092]
Currently trying to figure out which filter injects 

```
<style>[href^="http://www.faceporn.net/free?"]
{display:none !important;}</style>
```

into every page. Any clues?

**Comment by gorhill** [comment]
EasyList.

**Comment by maxfenton** [comment]
I freaked out about this today, thinking a site had been compromised. Glad to find an answer in this issue.

**Comment by ktsalik** [comment]
I also noticed this today. Why is this happening? And why this issue is closed? Am I missing something or..

**Comment by chrisaljoudi** [comment]
#161.

**Comment by ktsalik** [comment]
Oh my bad... I saw the issue bad I didn't read all comments.
