### ISSUE TITLE
Removing temporary dynamic filtering rules

### ISSUE THREAD

**Issue by quilloss** [uBlock-LLC/uBlock#1095]
Is there a way to remove all temporary rules used on a page?
I could go to the dashboard and revert all the rules but that includes temporary rules for other pages. A shortcut like the padlock icon to commit rules would be useful.

**Comment by gorhill** [comment]
> Is there a way

No. I talked about it [here](https://github.com/gorhill/uBlock/issues/731#issuecomment-73964956).
