### ISSUE TITLE
[Suggestion] Provide users a preset file to have the same config as gorhill?

### ISSUE THREAD

**Issue by tailHey** [uBlock-LLC/uBlock#110]
Same thing for HTTPSB and eventually for µMatrix. According to what I read about your setup, it seems to be efficient, well-blocking and limited with site-breaking issues.
It could even be a good start for beginners! ^^

**Comment by gorhill** [comment]
Best is to leave it this way: install and move on, that's what people like. My config is what I suggest informally for those who are like-minded, but I don't want the extension to get in the way, install and forget about it right away is a quality I do not want to forfeit. Whoever is curious can just bring the dashboard eventually.

**Comment by ghost** [comment]
@gorhill Very wise words my friend!

**Comment by tailHey** [comment]
My bad, I wasn't dealing with beginners, but with advanced users who are simply curious about your own setup ;)
Perhaps should you tell us more about it somewhere in the documentation to "keep track" of it?

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Block-more,-way-more
