### ISSUE TITLE
The status of adblock warning removal list won't be stored in the backup file.

### ISSUE THREAD

**Issue by blahxblah** [uBlock-LLC/uBlock#1102]
I checked adblock warning removal list and exported backup file.
But when I re-load the backup file the list is unchecked.

**Comment by gorhill** [comment]
Did you click _"Apply changes"_ after selecting the list?

**Comment by blahxblah** [comment]
Yes, I did!!!!

**Comment by gorhill** [comment]
> Yes!!!!

I cannot reproduce.

**Comment by blahxblah** [comment]
https://onedrive.live.com/?cid=B574A3DB9B8977F9&id=B574A3DB9B8977F9%21103

I attach my backup file.

**Comment by gorhill** [comment]
Thanks, I could reproduce.

Found the problem, will fix.

**Comment by gorhill** [comment]
Until the fix is released, to workaround the issue, you need to restore twice in a row the same file, this worked on my side.
