### ISSUE TITLE
Custom rule won't get applied

### ISSUE THREAD

**Issue by jrglkwjrghlkwregb** [uBlock-LLC/uBlock#1104]
uBlock 0.9.2.3

![untitled](https://cloud.githubusercontent.com/assets/11683443/6872822/60d5aa8c-d4b4-11e4-8d3d-c4d344c48b27.png)

**Comment by gorhill** [comment]
I see, this must be a side effect of #1100. That filter list has the same hash as the the one you are trying to include above, and thus it is discarded. Just select it from the preset filter lists, under "Ads".
