### ISSUE TITLE
Feedback on New Site specfic tools -

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#1105]
I believe the current notation to depict whether the feature is active or not is confusing. 

As it is now:

**popup blocker:**
- Active: Cross Mark
-  Disabled: No Cross Mark
##### Strict Mode:
- Active: <b>No</b> Cross Mark
- Disabled: Cross Mark

Instead i think it will be nice to have these icons (**to have same notation for active vs disabled**). Some thing like glow, when it is active and not glow when disabled (as it is now shown by default)

So, if it as below, i believe it avoids confusion to think if a feature is active or not -
##### popup blocker:
- Active: Glow
- Disabled: Not Glow 
##### Strict Mode:
- Active: Glow
- Disabled: Not Glow

Please let me know if this makes sense..

```
uBlock v0.9.2.4
```

**Comment by gorhill** [comment]
...

**Comment by gorhill** [comment]
I removed the dev build. I will release when I am confident that what is there is how I think it should be -- and if it takes two months, then be it.

**Comment by harshanvn** [comment]
Just another observation. Just wanted to bring to your attention -

I believe when toggling strict mode, a refresh button should be presented, as the next consequent action for the user is to click refresh icon :)

**Comment by gorhill** [comment]
> refresh button

Inapplicable, nothing is changed on the page. It is to prevent future full page block.
