### ISSUE TITLE
Small issue with YouTube

### ISSUE THREAD

**Issue by TennoDiablo** [uBlock-LLC/uBlock#1108]
First of all: Thanks for this great project! I tested this as an alternative to Adblock Edge and Firefox is much faster now than before. :)

Unfortunately there is a very little issue depending on YouTube. While playing a video, the right sidebar only shows me the video coming next in autoplay, the other ones are blocked. 

![eg](https://cloud.githubusercontent.com/assets/8669826/6874936/6c0bbc28-d4bb-11e4-9a44-d93fb7ed1ca5.png)

I didn´t change any of the basic settings of µBock and there are only a very few other addons installed (FireFTP 2.0.23, Lightbeam 1.2.1 and Speed Dial 6.7.7). I know these are peanuts compared to other possible bugs, but I just wanted to mention it. :)
- Windows 7
- Firefox 36.0.4
- µBlock 0.8.8.2

**Comment by gorhill** [comment]
Can you give the exact URL where you have that problem?

**Comment by TennoDiablo** [comment]
https://www.youtube.com/watch?v=kemkAAgOJAo

But this doesn´t matter, it happens with every video I watch on YouTube. :)
There would also be a second problem when I go (with Adobe Flash) into fullscreen and YouTube changes the resolution from 480p to 720p, with µBlock the video stops or freezes. After activating the Media Source Extensions and the HTML5 player this is solved, so I decided not to report it (and also because Firefox will activate them by default in the next version coming on Tuesday, as far as I know).

**Comment by gorhill** [comment]
Unable to reproduce:

![d](https://cloud.githubusercontent.com/assets/585534/6875341/18b5edfe-d494-11e4-94dd-f8d0eecc7752.png)

**Comment by SW1FT** [comment]
Try updating uBlock to 0.9.2.3.

**Comment by Betsy25** [comment]
@TheGaladras 
You don't have the **!** removed by accident, in front of the "! https://easylist-downloads.adblockplus.org/yt_annoyances_suggestions.txt" string in the custom list under "3rd party filters" ?

I could perfectly reproduce what you see, by removing the **!**, otherwise I cannot reproduce your problem either. (FF nightly 39, Win7)

BTW, Don't forget to click the "Parse" & "Apply Changes" buttons after changing strings there.

**Comment by TennoDiablo** [comment]
Thanks a lot, guys, I found the mistake.
I updated µBlock from 0.8.8.2 (the version Mozilla listed in the AMO) to 0.9.2.3 from here. The problem was solved as I disabled the cosmetic filters, now I got back the full functionality of YouTube. :)

**Comment by gorhill** [comment]
>  problem was solved as I disabled the cosmetic filters

I can't reproduce with or without cosmetic filters.
