### ISSUE TITLE
[Firefox] Popup always takes priority even without focus

### ISSUE THREAD

**Issue by quilloss** [uBlock-LLC/uBlock#1109]
uBlock 0.9.2.3
Firefox 36.0.4

When a popup opened, the uBlock dashboard opens in the popup instead of the window that currently has focus. This occurs even when the dashboard is opened from the add-ons manager.

Also when a popup is opened, all the dynamic filtering rules are set to the context of the popup window. This might be intentional to ease setting rules for the popup, however it also applies to other tabs not associated with the popup.

**Comment by gorhill** [comment]
URL please.

**Comment by quilloss** [comment]
http://raymondhill.net/ublock/popup.html (7th example)
https://bugzilla.mozilla.org (persona login popup)

**Comment by gorhill** [comment]
I cannot reproduce.

**Comment by quilloss** [comment]
It turns out it is not related to popups at all. The context is always with the last Firefox window opened. I can reproduce with uBlock as the only addon and no plugins.

Might be related to this error that gets logged on the browser console when the dashboard is opened.
Security Error: Content at moz-nullprincipal:{072a6689-92cd-4c44-bc09-9427a1fd6d79} may not load or link to chrome://ublock/content/settings.html.

**Comment by gorhill** [comment]
> Might be related to this error that gets logged on the browser console 

No, @Deathamns said it's inconsequential.

Since I can't reproduce I am waiting to see if someone else can.

**Comment by quilloss** [comment]
Its caused by a conflict with focusmanager.testmode = true.
Its probably set by some Firefox test build that I used previously. This explains why I start having problems only after going to https://bugzilla.mozilla.org.

**Comment by gorhill** [comment]
So is this a bug with uBlock?

**Comment by quilloss** [comment]
According to https://bugzilla.mozilla.org/show_bug.cgi?id=704583 the preference is used to allow multiple windows to have focus at the same time.
I can't see any use for this outside of testing. So its probably best to ignore this issue.
