### ISSUE TITLE
"Your filters" bug

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#111]
Let's say that you add 230 letters inside of "Your filters" box on the same line and then hit Enter, new line does not have a cursor blinking.

![capture](https://cloud.githubusercontent.com/assets/8084723/3714933/bf0c44d4-15c5-11e4-845a-e46344077999.PNG)

Second line, there should have cursor blinking.

**Comment by gorhill** [comment]
Your scroll bar shows it's not completely to the left. Looks like the browser does not bring back the horizontal scroller to 0. Bug should be filed with Chromium devs.

**Comment by ghost** [comment]
Thanks for clarifying.
