### ISSUE TITLE
[Firefox] Tooltips in popup menu doesn't work.

### ISSUE THREAD

**Issue by kasper93** [uBlock-LLC/uBlock#1111]

**Comment by gorhill** [comment]
Settings please.

**Comment by kasper93** [comment]
What exactly do you need? I'm on latest version on aurora branch (38.0a2) I don't know what can be relevant.

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/6878284/eee2c470-d4b1-11e4-8129-b5c119edd4b3.png)

**Comment by kasper93** [comment]
Uh, I just noticed that description of the issue is empty, not sure why. I'm talking about untranslated tooltips. They are empty and while this is not big deal, because probably for most languages strings will be updated soon. I think you should show untranslated string instead of empty one :)

![ublock](https://cloud.githubusercontent.com/assets/1126053/6878337/a0e770ba-d4dc-11e4-8692-af75ade7ac42.png)

**Comment by gorhill** [comment]
> I'm talking about untranslated tooltips

Oh ok. Yes I sent the `messages.json` to crowdin, will update at some point tonight with whatever has been translated.

**Comment by gorhill** [comment]
Crowdin translations were imported yesterday, and a build was released.
