### ISSUE TITLE
Popup blocker global setting?

### ISSUE THREAD

**Issue by alejandrolemus** [uBlock-LLC/uBlock#1112]
From wiki:

> _By default popups are allowed_ unless there is a filter to block them. When this setting is turned on, all popups will be unconditionally blocked for the current site, regardless of filters

Can we have a global setting to turn this on/off?

**Comment by gorhill** [comment]
As seen in issue #1143, this wouldn't be a good idea. Blocking all popups is a last resort step when usual means (the filter lists) do not work on a specific site.
