### ISSUE TITLE
Add subscription(s) when I click on the specific link.

### ISSUE THREAD

**Issue by mikhaelkh** [uBlock-LLC/uBlock#1114]
Links like _adb:subscribe?location=...&title=...(&requiresLocation=...&requiresTitle=...)_
If it is on your list, enable it, if not, put it under custom (if not already in there)

**Comment by sander85** [comment]
Yeah, I've been thinking about similar functionality. It would be great if there would be an option to enable filter with a link. Would make it a lot easier to create a howto: 1. Install extension, 2. Click on this link to enable local filter.

**Comment by RandomAcronym** [comment]
parsing apb:subscribe  was added in [0.9.1](https://github.com/gorhill/uBlock/releases/tag/0.9.1.0). I'm not sure if it checks the default list first thought.
Mozilla has yet to approve the 0.9.1 update on [AMO](https://addons.mozilla.org/en-US/firefox/addon/ublock/versions/), uBlock will not auto-update on Firefox intill they do

**Comment by mikhaelkh** [comment]
uBlock doesn't check whether this subscription is present in his list, it automatically goes to custom.
uBlock also only check `adb:subscribe?location=...&title=...` and do not check `&requiresLocation=...&requiresTitle=...`

**Comment by lewisje** [comment]
I believe that if a subscription URL in the custom list is already in the pre-set list, it just isn't added to the set of subscriptions; however, it is possible that this means that such a subscription wouldn't be automatically subscribed to upon clicking the _abp:_ link.
