### ISSUE TITLE
[Mobile Firefox] Options display incorrectly

### ISSUE THREAD

**Issue by SteveDesmond-ca** [uBlock-LLC/uBlock#1117]
![tmp_15272-screenshot_2015-03-28-14-28-191726407596](https://cloud.githubusercontent.com/assets/195896/6882330/e1973850-d556-11e4-9c41-6e523263eb0d.png)

Steps to reproduce: install uBlock 0.9.2.3 in Firefox Beta (37.0) and select Tools > Addons > uBlock

**Comment by tntc4** [comment]
I see the same result - Android 2.3.4, Firefox 37.0.1

**Comment by chrisaljoudi** [comment]
Does this occur with the latest uBlock beta?

**Comment by tntc4** [comment]
I try the latest beta on my android phone and everithing is look good.
thank you for good working and your patience :)
