### ISSUE TITLE
CHN: EasyList China will cause the firefox hanging on some website

### ISSUE THREAD

**Issue by orsmile** [uBlock-LLC/uBlock#1118]
When I open the http://www.lolking.net/guides/290336 , Firefox will hang.

If i don't use the CHN: EasyList China, the firefox is regular.

Firefox version : 36.0.4
OS:Windows 8.1
CPU:I5 2500K,E3 1230V2

**Comment by gorhill** [comment]
I can reproduce.

**Comment by orsmile** [comment]
I test the other 2 pc, cpu is g1820 and i5 4460 (haswell architecture)

it can't reproduce.

maybe this is the firefox issue?

**Comment by gorhill** [comment]
There are two URLs on that page which are 870745-character long...

That's the problem...

**Comment by gorhill** [comment]
The URLs start as follow:

```
http://lkimg.zamimg.comimage/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ[...]
```

And keep going on for 870745 bytes.

There is clearly a bug on the page, you can see it with "View source". It's easier to debug with Chromium, as the whole browser doesn't hang like Firefox (because multiprocess).

**Comment by gorhill** [comment]
So you will have to contact the web master so that they fix their problem, there is nothing uBlock can do.

**Comment by gorhill** [comment]
Well thinking of it... This is really a crazy edge case, but I could harden uBlock to force it use only, say, the first 4096 character from a URL and discard the rest. Still, the bug is clearly on the page and tthis needs to be addressed by the web master.

**Comment by orsmile** [comment]
ok i will contact the web master
