### ISSUE TITLE
[Safari] lifehacker.com is broken when My Filters box is checked under 3rd party filters tab.

### ISSUE THREAD

**Issue by BillyJoeJimBob** [uBlock-LLC/uBlock#1119]
This happens even if there are no actual filters in My Filters tab.  This does not happen with Chrome or FF.

**Comment by chrisaljoudi** [comment]
@BillyJoeJimBob Hi. I tested that out, and it I can't see anything obviously "broken" on `lifehacker.com`. 

Please provide more details about the version of uBlock you're running, version of Safari, etc., and what exactly is broken.

[You should use the issue template](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#issue-template) — it makes it easier to reproduce and resolve these issues.

**Comment by BillyJoeJimBob** [comment]
Ok, sorry, it was a cache issue on my end.  

-BJJB
