### ISSUE TITLE
Allow blocking Disqus comments

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#112]
Just to get few cluttered sites to load faster without Disqus comments making sites slower to load, quite often users like me only checks one topic on the website and I don't like when I scroll down for example it starts to load Disqus comments, because quite often Disqus comments starts to load after Disqus comments page element is near center of the screen, and there might be some interesting topics under Disqus comments page element (after Disqus loads 100+ comments I'm able to check those topics).

It would be so much better if Disqus could be blocked with uBlock, it causes more problems than solves.

I'm not sure if this blocks Disqus in every site:

<code>||disqus.com/embed/comments/</code>

This blocks Disqus comments, but it keeps that spinning circle kinda image there, so I think it sitll tries to load Disqus comments elements.

This blocks spinning circle kinda element:

<code>http://a.disquscdn.com/next/assets/img/loader-bg.02dfd9d2b2565ee29ab17bc5d83f97d5.png</code>

Or with IP-addresses (found so far)

185.31.17.196
108.168.209.24
73.192.42.188
73.192.42.190
108.168.209.242

**Comment by gorhill** [comment]
I can't start adding everyone's personal choice to uBlock. This is what _"Your filters"_ is, to enter whatever filter which you personally find useful. Disqus is one, there is also Livefyre, and whatever else. For such cases you may want to consider HTTPSB, you won't have to create filters, it's point and click filtering, and you can temporarily allow if you wish with a few clicks.

**Comment by gorhill** [comment]
I personally use HTTPSB to blacklist `disqus.com` (and related), `livefyre.com` (and related), `gravatar.com` (and related), etc. for the reasons you mention, and also because these are also ubiquitous enough to serve as tracker. HTTPSB is really a better tool for this.
