### ISSUE TITLE
[Firefox] alignment differences in the pop-up

### ISSUE THREAD

**Issue by zcater** [uBlock-LLC/uBlock#1121]
There are some differences as how the pop-up appears in Firefox compared to Chrome.

Please look at the following 2 screen-shots.

There are 3 issues:
- the + and - for every site seems to be cutoff on both sides.
- the eye is exactly at the right margin in Firefox
- on the same idea the gray shadow beneath "requests blocked" and "domains connected" is cutoff on the right side.

![ublock in Firefox](https://i.imgur.com/EOX8CPd.png)
![ublock in Chrome](https://i.imgur.com/3NK6Puv.png)

**Comment by gorhill** [comment]
My Firefox fonts do not look like yours, size-wise.

What OS? Did you customize browser fonts?

**Comment by zcater** [comment]
This is on Linux x64 with KDE Plasma 5. I'm using Liberation Sans as a global font.

I tried to modify the fonts in the KDE module but it didn't have any effect on Firefox.

I modified the global font hinting. Aside for the fonts getting sharper or blurrier the spacing is the same.

I ran Firefox in a [firejail sandbox](https://l3net.wordpress.com/projects/firejail/) in order to get a definitely clean profile.

The screen-shot bellow is from that sandbox. As you can see no real changes...

![Firefox in sandbox](https://i.imgur.com/Mu5bmF6.png)

Further than that I see the same spacing in a Windows 7 virtual machine.

![Firefox in Win7](https://i.imgur.com/HqIwqrR.png)

**Comment by ghost** [comment]
I thought this issue was a really minor thing, more of an annoyance than an actual issue, but I can reproduce the same thing here. The dynamic filtering panel in chrome has just a few more pixels of space than in firefox.

**Comment by gorhill** [comment]
Fixed issue 2.
There no issue 3.

Now with issue 1, it's more complicated, because it's entirely caused by the font used.

**Comment by gorhill** [comment]
Mine, pretty similar -- Chromium left, Firefox right:

![a](https://cloud.githubusercontent.com/assets/585534/6886924/132456e2-d61e-11e4-8e32-3efa761a96da.png)
