### ISSUE TITLE
[Firefox] Number of items in badge not updated when newtab url is about:blank

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1122]
## Steps to Reproduce
1. Open Firefox.
2. In about:config, set about.newtab.url to about:newtab, the default 
3. Open a website where uBlock blocks something
4. Open a new tab
5. See that the number of blocked items in the badge has changed
6. Open Firefox.
7. In about:config, set about.newtab.url to about:blank
8. Open a website where uBlock blocks something
9. Open a new tab
10. See that the number of blocked items in the badge stays the same
## Symptoms

Number of blocked items in badge does not change.
## Preferences Different From Defaults

None. Tested with a clean firefox profile and a stock uBlock install.
## Info

```
uBlock version:
    0.9.2.4-ab151/latest git master
Browser and version:
    Firefox 36.0.4
OS and version:
    Arch Linux x86_64
```
## Other Extensions
- None.

And here's a quick 30 second video of the issue being reproduced.
http://a.pomf.se/rhemzm.webm

**Comment by gorhill** [comment]
@Deathamns, @AlexVallat

`tabWatcher.onTabSelect` skips `vAPI.tabs.onNavigation` at line 345 because `busyFlags` is `3` instead of the expected `0`.

**Comment by Deathamns** [comment]
50804eb.

**Comment by AlexVallat** [comment]
So I guess what's happening is that although the tab is still loading when it's switched to, it never fires updates the badge when it finishes loading? When I try it (on Nightly) it doesn't update the badge immediately on switch, but then updates it about half a second later.

Edit: adding some tracing and trying some more, I have found that it can get into a state where `browser.webNavigation.busyFlags` is `undefined` which is not helpful. Could just assume that if it's undefined it counts as not busy, I suppose...

**Comment by Betsy25** [comment]
Just chimming in that I couldn't reproduce on Firefox nightly 39 on Win7. (latest commit)
