### ISSUE TITLE
[Chrome] uBlock not hiding sponsored links on Reddit

### ISSUE THREAD

**Issue by jamesamndj** [uBlock-LLC/uBlock#1124]
I keep seeing sponsored and promoted links on the top of every subreddit. I installed Adblock Plus to see if it could block these links and it does. The lists ABP is using is the same as uBlock so I'm not sure what the issue is.

![](https://i.imgur.com/amwoXWs.png)

**Comment by gorhill** [comment]
- the URL which shows the above
- Browser/version
- uBlock version
- **Any and all** uBlock settings which differs from default

**Comment by gorhill** [comment]
Unable to reproduce with limited information provided.

**Comment by jamesamndj** [comment]
1. https://www.reddit.com/r/videos
2. Chrome 41.0.2272.104 (64-bit)
3. uBlock 0.9.2.3
4. [uBlock Backup File](https://www.sendspace.com/file/vrs8a1). Additional filters added. No other changes.

**Comment by gorhill** [comment]
Using your backup file, uBlock 0.9.2.3, updating all filter lists, this is what I get at the URL you gave me:

![d](https://cloud.githubusercontent.com/assets/585534/6888667/5265a18c-d653-11e4-8fed-226737a612f4.png)

**Comment by gorhill** [comment]
Any other add-ons?

**Comment by gorhill** [comment]
Looking at the DOM, I can see the proper style to hide the above box is properly injected by uBlock:

```
.share,
.goldvertisement,
#console,
.promotedlink, <<<<<<<<<<<
#siteTable_organic,
.sponsorshipbox,
.share.stumble,
.share-button,
#header + #content > #left > #rlblock_left,
#ad_main
{ display: none !important; }
```

**Comment by gorhill** [comment]
If you open the dev console as shown in the screenshot below, and filter the output as shown (using `contentscript`), then refresh the page, are there any error messages?

![d](https://cloud.githubusercontent.com/assets/585534/6888754/7d8b17fa-d655-11e4-82ac-a4de1c2d697a.png)

**Comment by gorhill** [comment]
Only way I can get OP's result is by turning off uBlock for the site.

**Comment by gorhill** [comment]
@jamesamndj How come you do not have the stickied post which shows up in my screenshot?

**Comment by dragons4life** [comment]
@gorhill 
 Can confirm it doesn't happen to me and I am using chrome as well.

**Comment by jamesamndj** [comment]
Sorry for the delayed response. I am using Reddit Enhancement Suite and selected the 'hide' option under the sticky post. Initially installing ublock along with RES did not cause this issue. It has come up in the last few days. Might be a RES problem but I can't tell for sure.

No errors using that filter in the console.

![](https://i.imgur.com/vAaYpRW.png)

**Comment by jamesamndj** [comment]
I disabled RES while keeping ublock enabled and can see the promoted links. I'll try re-installing everything to see if that fixes the issue.

**Comment by dragons4life** [comment]
I am also using RES and have no problems.
Guessing you have already tried purging and than updating everything? @jamesamndj

How about downloading a portable version of chrome and installing the extensions there to check if it's the browser?

**Comment by jamesamndj** [comment]
@dragons4life Yup tried that.
I'll give the portable version a try.

**Comment by gorhill** [comment]
The screenshot below tells pretty much everything: the promoted box has class `promotedlink`, and uBlock is applying the CSS style `display: none !important` to that class. So the element disappears:

![d](https://cloud.githubusercontent.com/assets/585534/6890427/088f297c-d679-11e4-81e5-acc6c4cf3bda.png)

It would help a whole lot if you gave me similar screenshot with all the same information visible.

Notice that I selected the sponsored box in the DOM, this will fill the right side bar with information pertaining to it.

uBlock's `style` can be seen on the right side bar, at the bottom, where `.promotelink` is highlighted: this tells that this style is being applied to the box, i.e. the box is rendered invisible and collapsed as a result.

If for some reasons something, like another extension, was removing the class `promotedlink` from the sponsored box, that would counter uBlock's style. So if you could provide such screenshot that would pretty much tell us what is happening.

**Comment by jamesamndj** [comment]
Here you go
![image](https://cloud.githubusercontent.com/assets/11711506/6890569/d36516b4-d67b-11e4-9937-30913d8ce4c5.png)
![image](https://cloud.githubusercontent.com/assets/11711506/6890570/d64f2f54-d67b-11e4-8609-19fc78f4685d.png)

**Comment by jamesamndj** [comment]
![screen shot 2015-03-30 at 1 25 34 am](https://cloud.githubusercontent.com/assets/11711506/6890582/29a65d58-d67c-11e4-8a86-08ddbfa97e1c.png)
![screen shot 2015-03-30 at 1 25 40 am](https://cloud.githubusercontent.com/assets/11711506/6890584/3438f30c-d67c-11e4-907e-a7e7af35ce81.png)

**Comment by gorhill** [comment]
I don't see any style applied by uBlock in there. Now I wonder, are they even injected? They should appear in the `head` section:

![d](https://cloud.githubusercontent.com/assets/585534/6890721/a55c4eba-d67e-11e4-9662-d2db9ebf70d3.png)

**Comment by jamesamndj** [comment]
Weirdly enough, the promoted links have now disappeared. Thanks for your help.
