### ISSUE TITLE
[Safari] Not able to load this extension in extension builder

### ISSUE THREAD

**Issue by pravinvarma** [uBlock-LLC/uBlock#1126]
HI, I am not able to load this extension into Extension Builder of Safari in Mac platform. It shows select button disabled. Also, I can see from plist file that most of the files and file structure is not available.

Can you please verify?

Thanks

**Comment by chrisaljoudi** [comment]
@pravinvarma Do you have a Safari Developer certificate installed? That's needed to be able to load extensions into the Extension Builder.

**Comment by chrisaljoudi** [comment]
@pravinvarma can you please provide further details? Will have to close this in 2 more days otherwise.
