### ISSUE TITLE
[Request] Remove old hufilter

### ISSUE THREAD

**Issue by gvasicsek** [uBlock-LLC/uBlock#1127]
This is not really an issue, but I don't know where to ask about it. The old hungarian filter list is labeled as HUN: hufilter (obsolete, will be removed)‎. When will you remove it from the filter list?

Thank you for your answer.

**Comment by gorhill** [comment]
Firefox newer version not being cleared on AMO is what is holding me back from addressing all filter list issues, as the version which is waiting to be cleared contains the code to migrate obsolete filter lists to new filter lists in a seamless manner, i.e. migrating users of an obsolete filter list to a good one.
