### ISSUE TITLE
how to blacklist a whitelisted entry in predefined lists

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#113]
when you visit tomshardware.com, i see ga.js(google-analytics.com) is whitelisted. How should we blacklists such a entry in uBlock? 
Currently, i am using HTTPSB alongside. So, is not a problem for me. But i believe it would be nice to blacklist a whitelisted entry..

**Comment by gorhill** [comment]
Fanboy Enhanced stats, line 640.

Any kind of such exceptions, we have to assume the site is (or was) breaking without this. I can't take care of all these, this has to be brought up with EasyList authors, and preferably this has to be investigated first to see whether removing the exception would break the site, I am sure they can use all help which comes their way. Often these exceptions are required for comments to work, or it could just be obsolete by now.

**Comment by harshanvn** [comment]
hi Gorhill, As stated in my original comment, actual bug was created, to find if there is a way to blacklist a whitelisted entry. I was just merely quoting an example here..

And ga.js is not needed anymore now, the site works normally, I was blocking it thru HTTPSB.  (not sure if comments works or not, will check it tonight and update)

And thanks for pointing the culprit list here. It is really difficult to point which lists are causing the issue. Will wait for #43 to be fixed. That will help in these situations..

**Comment by gorhill** [comment]
No, ABP filter syntax doesn't support exception to exceptions.

**Comment by harshanvn** [comment]
hmm..Ok.
Not sure in ABP Chrome. But in ABP Firefox, i could disable an exception too! Please  see the attached screenshot for the same.

![abp](https://cloud.githubusercontent.com/assets/779630/3721872/f3875dbc-1664-11e4-9f53-c057f04567c8.png)

**Comment by gorhill** [comment]
Manually disabling a specific filter is not supported in uBlock (neither in ABP Chrome), that's a different issue than the one filed originally.

**Comment by harshanvn** [comment]
:) OK. No problem.
