### ISSUE TITLE
bit.ly links do not work unless uBlock is disabled.

### ISSUE THREAD

**Issue by Betsy25** [uBlock-LLC/uBlock#1131]
Opening links like http://t.co/rmoLUKgpht (which are seen a lot on sites like Twitter) don't do a thing with uBlock loaded, no matter if bypassed or not. Can only make them work with completely disabling the extension.

Firefox nightly39, Win7, latest commit.

**Comment by chrisaljoudi** [comment]
For reference: doesn't occur on Safari.

**Comment by TteokbokkiNari** [comment]
Hm.. Doesn't seem to occur to me on my install.
Latest uBlock dev build
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:40.0) Firefox/40.0 ID:20150330114816

**Comment by Mikey1993** [comment]
Can't repro on FF Nightly 39.
Latest dev build.

**Comment by Betsy25** [comment]
EDIT: **Please disregard** it is a refresh to http://bit.ly which is in My Filters list. _duh_
Sorry for the trouble everyone :flushed:
