### ISSUE TITLE
[Firefox] Blocking stops working when you move window to other monitor.

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1136]
When I have a tab open on  the 1st monitor and move it to the 2nd monitor all ads reload and display again and the icon shows nothing is being blocked.

**Comment by buawf** [comment]
The Graph of Adguard extension shows a bit of less than the ublock , for memory consumption in MBs .. !!
Make ublock the least in memory consumption , if possible ..
.

**Comment by gorhill** [comment]
@BUAWF 

> The Graph of Adguard extension shows a bit of less than the ublock

What does this have to do with the issue? Please do not pollute with unrelated topic. Also, I seriously doubt your conclusion, this is opposite of what I have measured in the past. I don't know what "Graph" is.

**Comment by gorhill** [comment]
I won't be able to reproduce this, I have only one monitor.

**Comment by DDGo** [comment]
I can't reproduce this problem with two monitors.

**Comment by chrisaljoudi** [comment]
Anyone who could reproduce?
