### ISSUE TITLE
How to block ads inside an extension?

### ISSUE THREAD

**Issue by jemminger** [uBlock-LLC/uBlock#1137]
I've got the delicious.com extension for chrome installed, and it seems now they're serving ads through it after you bookmark a page.

The ad container is identified by `.compose-result .post-bookmark-ad-container`, but I can't seem to block it because of the default whitelist `chrome-extension-scheme`

Example:
![screen shot 2015-03-31 at 10 41 27 am](https://cloud.githubusercontent.com/assets/2272/6921426/c1c875be-d792-11e4-933f-af3a41d7ac37.png)

Is it possible to block these ads?

**Comment by gorhill** [comment]
Can you show me the URL of the image?

**Comment by jemminger** [comment]
Do you mean the URL of the coupon ad image in the sample above?  It looks like it's Google ads:

![screen shot 2015-03-31 at 10 53 16 am](https://cloud.githubusercontent.com/assets/2272/6921668/4ad43c98-d794-11e4-88d9-9285ffd508bc.png)

The ads are being embedded in the delicious.com chrome extension: https://chrome.google.com/webstore/detail/delicious-bookmarks-exten/mnaelnkmidnndgikjbiifihgklnocljd

**Comment by gorhill** [comment]
uBlock does not inject its content scripts on other extension pages. However, you can block behind-the-scene network requests, but this can potentially break important browser functionality, or other extensions. This can be worked around however using dynamic filtering. Here is what you could try, to block the downloading of the ad above but nothing else in the behind-the-scene scope:
- Enable "Advanced user mode" in the _Settings_ pane.
- Add the following rules to the _"My rules"_ pane (click _Edit_, paste the rules, click _Save_):
  - `behind-the-scene * * allow`
  - `behind-the-scene pagead2.googlesyndication.com * block`
- Make the rules stick by clicking _"Commit"_ on that page.
- Go to the _"Whitelist"_ pane, remove `behind-the-scene`, apply changes.

See if this works -- I didn't try it, hopefully I got the details right.

**Comment by jemminger** [comment]
Yes!  That seems to work.  Thanks
