### ISSUE TITLE
[EasyList] Ads sometimes don't get blocked

### ISSUE THREAD

**Issue by ImSpecial** [uBlock-LLC/uBlock#1138]
So I'm not really sure how to report this, but on this site for example http://www.gamefaqs.com/search/index.html?game=final sometimes the ads will get through, seems to be random as far as I can tell, refreshing will fix it but sometimes a refresh will bring them back. I made a quick gif for show.

http://i.imgur.com/SVr8jev.gif

If you need more info let me know.

**Comment by gorhill** [comment]
What Firefox version?

**Comment by ImSpecial** [comment]
v37.0 as of this morning. Also my filter list, all purged and updated less then an hour ago because I thought maybe it was an old list problem.

http://i.imgur.com/ZNxJpMk.png

**Comment by gorhill** [comment]
Ok, I could reproduce.

**Comment by gorhill** [comment]
It's an EasyList issue. The ad I got was pulled from `partnerads1.ysm.yahoo.com`, which is not in EasyList. The closest match in EasyList is `||partnerads.ysm.yahoo.com^`. You need to [report this to EasyList](https://forums.lanik.us/viewforum.php?f=62), they need to add `||partnerads1.ysm.yahoo.com^` as well.
