### ISSUE TITLE
[Fennec] Ctrl+Click unavailable on mobile (affects enable/disable)

### ISSUE THREAD

**Issue by JoeSyr** [uBlock-LLC/uBlock#1139]
On Firefox for Android, the pop-up page offers the same tooltip as on the desktop version: "Click: Disable/Enable ublock for this site. ... Ctrl+Click: Disable ublock only on this page."

As ctrl+click is not available in Android, perhaps it would be appropriate to change the behavior/text to long-press, or simply add a second button. There is certainly plenty of real estate in the current implementation of opening the pop-up in its own tab.
![ublock on fennec](https://cloud.githubusercontent.com/assets/3876538/6925521/e79cc694-d7ad-11e4-8947-05e99e0fdefa.png)

**Comment by gorhill** [comment]
Yes, I have been thinking providing a better way to whitelist a page/site/whole domain today. This would remove the need for that huge tooltip, and this would address the issue here.
