### ISSUE TITLE
Video blocked

### ISSUE THREAD

**Issue by StVol33** [uBlock-LLC/uBlock#1141]
http://lifenews.ru/news/152046
uBlock on- video does not play
uBlock off- video plays

**Comment by gorhill** [comment]
As per provided steps, unable to reproduce, video played fine.

**Comment by dragons4life** [comment]
@gorhill Video got stuck on loading with uBlock, played fine without it.
- Google Chrome

**Comment by my-password-is-password** [comment]
<s>I could reproduce with default settings.  This was blocking it, [||ads.adfox.ru^](https://github.com/gorhill/uBlock/blob/04b3ee25fcff2b009cd5ebb60f10d86e10f810e2/assets/thirdparties/pgl.yoyo.org/as/serverlist#L342) , from  `Peter Lowe’s Ad server list`‎.</s>

<s>Try this, `@@||ads.adfox.ru/*/getCode*$xmlhttprequest`</s>

Not needed.  The video just takes a lil while to load for me.

**Comment by StVol33** [comment]
Unfortunately, it did not help!

**Comment by my-password-is-password** [comment]
What filter lists do you use?

**Comment by StVol33** [comment]
Default!

**Comment by my-password-is-password** [comment]
What if you add these to "My Rules"?

```
lifenews.ru life.ru * noop
lifenews.ru lifenews.ru * noop
lifenews.ru lifenewscontent.ru * noop
```

This was enough.

<s>
and in "My Filters"
`@@||ads.adfox.ru/*/getCode*$xmlhttprequest`</s>

Videos play for me. Have to wait a little.

**Comment by StVol33** [comment]
![2015-04-01_22-16-03](https://cloud.githubusercontent.com/assets/11031379/6949411/ec0f9890-d8bc-11e4-8439-11236d00d1e5.png)
![2015-04-01_22-16-40](https://cloud.githubusercontent.com/assets/11031379/6949415/f503f14e-d8bc-11e4-98f9-1351ef739e37.png)
![2015-04-01_22-17-14](https://cloud.githubusercontent.com/assets/11031379/6949419/f75476bc-d8bc-11e4-8a9e-6a2d7036385c.png)
Sorry! Does not work!

**Comment by my-password-is-password** [comment]
Have no idea then.  Works on both Chrome and Firefox for me.  Maybe see if you can find `m3u8` in the request logs.

```
http://embed.life.ru/embed/playlist/aedd3d9d90994157d6732ad0ea2a05fc.m3u8
http://embed.life.ru/embed/playlist/b43ac38e3bcc8a8af957231d2dbbeff2.m3u8
```

Those are the playlist for the videos.

**Comment by flawrist** [comment]
Could you be so kind to revisit this issue? 
Example: [this page][1] shows no video with uBlock on.

[1]: https://href.li?https://life.ru/944263
