### ISSUE TITLE
YouTube videos seem break

### ISSUE THREAD

**Issue by advcomp2019** [uBlock-LLC/uBlock#1144]
I just updated to Firefox 37. The video on YouTube is now doing this: https://dl.dropboxusercontent.com/u/4643460/theissue.PNG . I have to disable uBlock or reload the page a few times before it will load right. It happens with any videos. I have tried 0.8.8.2 up to the newest. I have even tested AdBlock Plus and have the same issue. I am thinking it is something to do with the MSE getting enabled in Firefox 37.

**Comment by gorhill** [comment]
Provide a URL to the video in the image please.

**Comment by advcomp2019** [comment]
It is with any video on YouTube, not just one.

**Comment by gorhill** [comment]
> It is with any video on YouTube, not just one.

Ugh...  See: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include:

> **Always include a URL**, even if "it happens everywhere".

It just saves time...

**Comment by advcomp2019** [comment]
https://www.youtube.com/watch?v=lsDQYcJebfI

**Comment by advcomp2019** [comment]
I could give 100's of URLs, but that's the one from screenshot.

**Comment by advcomp2019** [comment]
I have been playing around for a while and found out whats might be causing the issue. If anything in the Ads filter list is enabled, I just get a broken YouTube player like you seen in that screenshot.

**Comment by gorhill** [comment]
Did you look at uBlock's request log to see what gets blocked?

**Comment by advcomp2019** [comment]
I am not sure or can't tell, but it looks like maybe https://www.youtube.com/player_204, https://s.youtube.com/, or googlevideo.com
I will say this tho. If I am on the video and hit F5 two times, the video loads right up.

**Comment by TteokbokkiNari** [comment]
Hm, how about trying a test profile for Firefox 37, and then installing uBlock? 
We could at least isolate it to being something in your main profile.
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by advcomp2019** [comment]
Danial, that is the weird thing. uBlock by itself does not see that issue. Once my other add ons is installed, I still don't see the issue. It is once I login to YouTube. Then I see the issue. When I disable uBlock while logged in, the YouTube videos load just fine.

**Comment by gorhill** [comment]
> it looks like maybe https://www.youtube.com/player_204, https://s.youtube.com/, **or googlevideo.com**

`googlevideo.com` should never be blocked, unless you blocked it yourself somehow. The symptom you describe matches well what happens when you block `googlevideo.com`.

Please share all your settings which differs from default ones.

**Comment by advcomp2019** [comment]
my uBlock settings are default.

**Comment by gorhill** [comment]
Nothing blocks `googlevideo.com` by default. Can you provide a screenshot of the request log after refreshing the page for that log? I want to see what is being blocked. It will help if before taking the screenshot you type `-` in the filter field of the request log, so that only blocked requests are displayed.

**Comment by advcomp2019** [comment]
Here is a log: https://dl.dropboxusercontent.com/u/4643460/logublock.PNG

**Comment by gorhill** [comment]
Looks normal to me.

**Comment by advcomp2019** [comment]
I thought so because I have the same config as Firefox 36, and it looks the same and all works fine in that version. I am still confused what else it could be, but for something to deal with MSE getting enabled.

**Comment by gorhill** [comment]
Ok, I've finally received the FF37 update, and I could not reproduce the reported issue, using 0.9.2.4-dev.4 + default settings.

There are sometimes a couple seconds (2-4) of delay after I click a video, but nothing ressembling your issue.

**Comment by advcomp2019** [comment]
So I am not sure what's going on then since it works fine without uBlock or I have hit F5 two times.

**Comment by elyrly** [comment]
Looks fine on my machine

**Comment by advcomp2019** [comment]
By the way, here is all my addons that I use: https://dl.dropboxusercontent.com/u/4643460/addonlist.PNG

Liked I said they all worked fine together with Firefox 36, but it seems like no one can reproduce this in Firefox 37.

**Comment by WiHHi-Z3-PuX** [comment]
I have a similar issue on Safari, youtube won't play any videos, sometimes it loads the html5 player, but it still won't play the video.
I tried disabling all filters and it did not help, tried disabling unlock for youtube, no luck. Whitelisting did not help. The only thing that fixes it is turning ublock off.
Actually it's not the only thing that breaks, google images also don't work. Web search works, image search does not.

**Comment by Maxxee** [comment]
This could be a problem of NoScript.
I know that RequestPolicy and Policeman have a similar problem with Firefox 37 because of enabled MSE support.
The solution for e.g. Policeman is to create a rule to allow requests from youtube.com to [Chrome destination].
What happens when you disable the NoScript extension?

**Comment by WiHHi-Z3-PuX** [comment]
Tried on another macbook pro 13, this one had yosemite - both google image search and youtube work.
So this is most likely related to mavericks/safari 7.

//the only extension I had installed in both cases was ublock.

**Comment by chrisaljoudi** [comment]
@WiHHi-Z3-PuX interesting; sorry about that. I'll investigate.

**Comment by chrisaljoudi** [comment]
@WiHHi-Z3-PuX Fixed in 09825e1.

Thanks for pointing this out!

**Comment by advcomp2019** [comment]
@Maxxee I tried with and without NoScript. Same issue. Then I have another site that I have been trying to get the videos to work but nothing will work unless I disable uBlock for that site. Here is the other site: http://www.siouxlandmatters.com/story/d/story/illinois-couple-gets-whopping-surprise/39194/Aogd_YAgK0GVwjT-yk6bcw

Do you know what should I allow without unblocking the whole site? By the way, AdBlock Plus works fine on that site.

**Comment by Maxxee** [comment]
Hard to think of possible solutions with no other reports of such an issue.
Possible things currently coming to my mind:
- ISP / other entity manipulating your internet traffic
- malware on your system
- corrupt system installation
- corrupt Firefox installation

I wonder why this issue was closed as the OP didn't report a Safari issue.

**Comment by advcomp2019** [comment]
@Maxxee I have test that site many times. It is not my ISP because no uBlock works fine. I have no malware because I have ran cleaners at least once a month. It is not my system because I can reproduce it another system with uBlock. It is not my Firefox install for the same before. Plus I have tried a clean profile with just uBlock installed.

**Comment by chrisaljoudi** [comment]
@Maxxee oh, I apologize if I mis-closed. Will reopen.

@advcomp2019 and @Maxxee: does either of you happen to have a test case that consistently reproduces the issue at hand? That'd be appreciated.

**Comment by advcomp2019** [comment]
@chrisaljoudi It seems that my YouTube issue has fixed itself. I only can get it once a day now. With the other video on like http://www.siouxlandmatters.com/ , all I get is spinning graphic with uBlock enabled. I have to disable uBlock all together or just that site to get it working because I can find the element that is getting blocked.

**Comment by chrisaljoudi** [comment]
@advcomp2019 I was able to come up with these two exception rules to un-break that site:

```
@@||liverail.com/crossdomain.xml$domain=siouxlandmatters.com
@@||liverail.com/swf/v4/plugins/osmf/LiveRailPlugin.swf$domain=siouxlandmatters.com
```

**Comment by advcomp2019** [comment]
I tried adding just liverail.com, and it did not work but those worked. Do I have to use $ stuff because that is only difference from yours to what I used.

**Comment by chrisaljoudi** [comment]
@advcomp2019 adding an exception just for `liverail.com‘ should work, too — what did your filter look like exactly?

**Comment by advcomp2019** [comment]
I did only did: ||liverail.com

**Comment by chrisaljoudi** [comment]
@advcomp2019 ah, well:

`||liverail.com` means "block liverail.com".

`@@||liverail.com` is an exception rule — "do NOT block `liverail.com`".

`@@||liverail.com$domain=siouxlandmatters.com` means "don't block `liverail.com` when it's from `siouxlandmatters.com`".

**Comment by advcomp2019** [comment]
Thanks. I did not know that.
