### ISSUE TITLE
Chrome uBlock stopped working... completely

### ISSUE THREAD

**Issue by mblais** [uBlock-LLC/uBlock#1145]
_(copied here from Chrome Store uBlock support tab)_

Suddenly my uBlock icon is gray and its popup window is mostly blank: see a screengrab here: http://i.imgur.com/cLpX3hi.png

The uBlock Options window is also similarly empty, so no way to report on or fiddle with uBlock settings:
![image](https://cloud.githubusercontent.com/assets/281745/6931117/3a7a8878-d7a5-11e4-9219-7b48716b9dfd.png)

And it's not blocking ads. I tried disabling and re-enabling it, restarting Chrome - no change.

**Will be uninstalling and reinstalling uBlock soon, so if you want me to check anything, request it soon.**

uBlock v0.9.2.3
Chrome Version 40.0.2214.91 m
Windows 8.1 x64

**Comment by gorhill** [comment]
It looks to me like the extension's folder content was tampered with. I don't know where it is located on Windows, but if you know it, look if there are any missing files in it. It should ressemble what is found at https://github.com/gorhill/uBlock/tree/master/src.

Not sure but maybe I heard before some antiviruses or cleaners can mess up uBlock sometimes.

**Comment by mblais** [comment]
I uninstalled and re-installed uBlock, and it seems to be working fine now.
Thanks for the help :-)

**Comment by 0xBRM** [comment]
That's happened to me before, with other extensions as well.
Next time this happens, close Chrom_, open the process/task manager, and close all instances of Chrom_.
It should work.
