### ISSUE TITLE
Proposal: Make local dynamic filtering rules apply to second-level domains by default.

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1148]
When a user visits the site www.foo.com and locally allows all resources from bar.com via the dynamic filtering pane, this rule should apply to all of foo.com instead of only www.foo.com. That is, instead of the rule
    www.foo.com bar.com \* allow
, the rule
    foo.com bar.com \* allow
should be generated.

**Comment by lewisje** [comment]
I think you mean the base domain, or one level up from a public suffix (for example, www.fanboy.co.nz would go to fanboy.co.nz, not co.nz); anyway, it's nice to have the granularity to set the hostname-specific rule from the dynamic filtering pane, and if it's not too cluttered, maybe it could include all the subdomains down to the base domains.

**Comment by gorhill** [comment]
> this rule should apply to all of foo.com instead of only www.foo.com

No. If I browse `groups.google.com`, last thing I want is a rule to apply to whole `google.com`. That a rule apply to what the hostname seen in the URL is the safest approach -- there are no bad surprise for the user.
