### ISSUE TITLE
Allow to choose UI language

### ISSUE THREAD

**Issue by ksdev-pl** [uBlock-LLC/uBlock#115]
If I understand correctly, UI language is now set automatically. Could you add an option to choose language other than system default?

**Comment by gorhill** [comment]
> UI language is now set automatically

It has always been set automatically, according to the language set in browser. The browser decides which language, If the translation doesn't exists, it falls back to English.

If you want to force your browser to a particular language, follow the instructions there:
https://developer.chrome.com/extensions/i18n#locales-testing
