### ISSUE TITLE
Element hiding doesn't work at vk.com

### ISSUE THREAD

**Issue by DotTheI** [uBlock-LLC/uBlock#1151]
Nothing happens when a user is logged into vk.com (that's when you start seeing ads there) and is trying to hide elements, e.g.:

![2015-04-01 21 33 22](https://cloud.githubusercontent.com/assets/10737439/6948585/772aa90c-d8b7-11e4-858b-8bcb317888d5.png)

No red frames  indicating selection show up, thus it's not possible to select anything.

**Comment by chrisaljoudi** [comment]
@DotTheI please provide the browser, uBlock version, etc. that this problem occurs with.

**Comment by DotTheI** [comment]
I am using Firefox 36.0.4 for OS X, uBlock version is 0.9.2.3

**Comment by chrisaljoudi** [comment]
What page does this occur on? I tried logging in and I see no ads.

**Comment by DotTheI** [comment]
I don't see them now either with uBlock enabled. Not sure what happened when the ads were there. Going to try to figure out how to reproduce. Please don't close for the next two days.

**Comment by chrisaljoudi** [comment]
@DotTheI Hi!

Has the problem re-occurred?

**Comment by DotTheI** [comment]
Hi! Not, it has not. Thank you!
