### ISSUE TITLE
Twitch ads still show?

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1152]
I go on RiotGame's stream and I see their 5 minute ad. Is Ublock not working on twitch? I'm using 0.8.8.2 but I've also tried the later versions

**Comment by chrisaljoudi** [comment]
@dakoslug Hi! What browser and browser version is this occurring with?

**Comment by ghost** [comment]
Sorry! Firefox 37.0

**Comment by elyrly** [comment]
odd what filters do you have selected?

**Comment by ghost** [comment]
I don't have any custom filters. Ads don't show up 100% of the time during streams but that might just be because they aren't triggered by twitch.

**Comment by chrisaljoudi** [comment]
Hmm. I've tried to reproduce, but have been unable to.

@dakoslug are you certain that those ads aren't hard-coded as parts of the streams? (As in, the broadcaster is streaming them for a sponsor or such)?

**Comment by ghost** [comment]
It allowed me to skip the ad, so I don't think so. It doesn't look natural to the video source.

**Comment by ghost** [comment]
It's odd because only that specific stream has this problem. I guess it's not a big deal since you can skip but I just found it odd.

**Comment by chrisaljoudi** [comment]
Merged into #1184.

**Comment by ericboehs** [comment]
Still having this problem on Safari
