### ISSUE TITLE
why gorhill leaved from project 

### ISSUE THREAD

**Issue by muhasturk** [uBlock-LLC/uBlock#1155]
Please provide some information, what happening? Why two extension on Chrome store? Why did he/she would like to leave project?

**Comment by chrisaljoudi** [comment]
Everything anyone knows is [here](https://github.com/chrisaljoudi/uBlock/commit/6850fa0a262b8772a502c92750fe7a5bf74515f0).

**Comment by chrisaljoudi** [comment]
Please do see #1153.

**Comment by dandv** [comment]
I've summarized the likely reason (Raymond Hill was overwhelmed with demands from users) at https://github.com/chrisaljoudi/uBlock/issues/1153#issuecomment-89716858.
