### ISSUE TITLE
make advanced user wiki

### ISSUE THREAD

**Issue by muhasturk** [uBlock-LLC/uBlock#1159]
```
 "settingsAdvancedUserPrompt":{
    "message":"I am an advanced user (<a href='https:\/\/github.com\/gorhill\/uBlock\/wiki\/Advanced-user-features'>Required reading<\/a>)",
    "description":"English: "
  },
```

**Comment by Betsy25** [comment]
Hi @muhasturk 
That should be "chrisaljoudi" instead of "gorhill" ;)

**Comment by muhasturk** [comment]
I know but this is not what I try to say

**Comment by lewisje** [comment]
I think that what he meant to say is that the "Required reading" link on the Settings page still points to gorhill's repository, which no longer has any wiki pages, and it should be changed to point to chrisaljoudi.

**Comment by Betsy25** [comment]
Hopefully @chrisaljoudi will implement the [Pull Request](https://github.com/chrisaljoudi/uBlock/pull/1169) with the corrected links soon.
