### ISSUE TITLE
[Feature request] Pause button + an extra

### ISSUE THREAD

**Issue by bugreporter5** [uBlock-LLC/uBlock#1163]
Hello there,

thank you for all your work. I have a small request. Please have a look at the screenshot below. Can you see the first four options? Especially pausing the addon/extension temporarily is far better than opening the extension handler to disable it and re-enable it afterwards.

And the other three options to create filters are very convenient as well, but an "Pause"-option is my top priority.

The original AdBlock for Chrome, if you want to check this out: https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom

Again, thank you very much and I hope you will read this request and may do something about it.

![image](https://cloud.githubusercontent.com/assets/11770413/6963175/350ebb28-d93c-11e4-9151-1959b98b19f6.jpg)

**Comment by blahxblah** [comment]
Don't run on this page - Ctrl+Click the power button
Don't run on pages on this domain - Click the power button
Block and ad on this page - Click the dropper button

**Comment by rodalpho** [comment]
Perhaps Alt+Click could be used to pause the addon?

**Comment by lewisje** [comment]
I think it's convenient enough to go into the Extensions menu to disable and re-enable, but if it doesn't clutter the menu, another button specifically for cancelling all filtering would be useful; for those who don't already use dynamic filtering, a workaround would be to open the dynamic filtering pane and enable "all" (if you do use dynamic filtering, more-specific rules would still override that allow-all rule).

**Comment by MilapNaik** [comment]
I'd like an easier way to pause uBlock. Sometimes pausing uBlock by using the power button is not enough, and uBlock will still stop a website from opening a new tab.

**Comment by gorhill** [comment]
> uBlock will still stop a website from opening a new tab

No, this was fixed in #1142. You have a case?

**Comment by MilapNaik** [comment]
It's specifically when I pause uBlock to click an ad, a new tab will open but uBlock will be reactivated and will close that tab down.

**Comment by lewisje** [comment]
To be more specific, uBlock will be disabled on the domain the ad is _on_ but not necessarily on the domain it links _to_.

**Comment by MilapNaik** [comment]
Correct, which is why I was wondering if there could be a way to pause uBlock in general and not just for the current domain?

**Comment by bkmintie** [comment]
+1 on this feature request
