### ISSUE TITLE
Can't edit and save rule in dynamic filter

### ISSUE THREAD

**Issue by Vyral-Protoss** [uBlock-LLC/uBlock#1168]
I'm trying to add the following rule in dynamic filter : 

\* facebook.com 3p block

but it get deleted when I try to save. Is it normal ?

Thanks for your help.

EDIT : it seems that everytime I use the 3p option, the rule can't be saved.
For example, this rule : 

\* twitter.com \* block

is ok but this rule : 

\* twitter.com 3p block

is not.

**Comment by chrisaljoudi** [comment]
Hi @Vyral-Protoss!

The "deletion" behavior actually means that the rule was invalid (I definitely understand this is something that should be improved).

The reason `* twitter.com 3p block` isn't being accepted by uBlock is that with type-based rules (`image`, `3p`, `3p-frame`, etc.), the destination hostname should always be `*`.

Now, if I understand what you're trying to do correctly, you can achieve it with something like this:

```
* twitter.com * block
twitter.com twitter.com * noop
```

**Comment by Vyral-Protoss** [comment]
Ok, I understand.

Thanks again for the help. :+1:
