### ISSUE TITLE
Safari version

### ISSUE THREAD

**Issue by franciscolourenco** [uBlock-LLC/uBlock#117]

**Comment by gorhill** [comment]
@chrisaljoudi I can't maintain a Safari version myself: I don't have OSX, and neither Windows (I have to try out obsolete Safari/Windows version in a VM -- tedious).

So what is needed is a developer with OSX who can ensure uBlock works fine on latest Safari, and is willing to make it available to others -- ideally forking the project here, keeping it always up to date with latest changes, and making a Safari version available under his/her name.

**Comment by chrisaljoudi** [comment]
@gorhill Okay, I'd be glad to do that (I have OS X and I develop on/for Safari).

I'll start working on it.

**Edit:** cleaned up issue comments so older unsupported builds aren't floating around.

**Comment by chrisaljoudi** [comment]
@gorhill @AdamJ8 Sorry for the delayed reply.

Unfortunately, I hadn't realized it was GPLv3. It's not that I have anything against the license, but I really feel reluctant to try and figure out all the disclaimers that need to be done/lines must not be crossed to conform to the license.

I'm used to much simpler, more permissive licenses like MIT, so I'm a bit naïve about more nuanced ones.

I'd still absolutely love to maintain a Safari port — if you can share what the general rules are about the license and what you think is reasonable, I'll make the Safari build and slightly-modified repo public.

**Comment by gorhill** [comment]
MIT is good for libraries. GPL is good for full apps.

What do you have in mind when you say "slightly-modified"?

**Comment by DomT4** [comment]
Recommended reading featuring nice dropdown menus: http://choosealicense.com/licenses/

Basically, publish the full source, say where it originated, say you modified it and briefly how, and don't screw with the copyright or GPLV3 license and you're golden.

**Comment by chrisaljoudi** [comment]
@DomT4 nice — thanks.

@gorhill sure — please don't hear me advocating one or the other! I simply haven't had any experience with more nuanced licenses (yet).

As for slightly modified: not µBlock itself, but rather the build script for Safari (which currently doesn't run in a "default", minimal environment — requires `python3` and a modification to the `.sh` or a slight rewrite).

**Comment by AdamJ8** [comment]
@chrisaljoudi - While not an expert, I think @DomT4 summed it up, essentially include the 'text' of the license within the source - publish the source and where it originated and the terms should be met?   See http://www.gnu.org/licenses/gpl-3.0.html#howto

**Comment by AdamJ8** [comment]
@chrisaljoudi - Are you sure the build script and/or build tools need to be considered part of the source?  Again, just my opinion, but I've never seen build tools, methods, hardware, etc. considered as part of the source - and as such is not part of the licensed code?

**Comment by chrisaljoudi** [comment]
@AdamJ8 Nope, not sure at all.

Good point!

(*Though it's worth figuring out the right answer anyway so if/when Safari-port-specific modifications are necessary*).

**Comment by joshvickerson** [comment]
Any reason it blocks direct links to Facebook pages or Twitter profiles? Just simple social icon links, not one of the fancy plugins or anything. Working on a site for <a href="http://ritlocalhost.com">a club at my school</a> and we have links to our social media stuff at the bottom and links to Facebook and Twitter are blocked.

Does it have to do with the markup or is it just because it's linking to FB / Twitter?

**Comment by gorhill** [comment]
Just un-select _"Fanboy Social Blocking"_ filter list. All blockers have filter lists which you can remove/add at your convenience.

**Comment by joshvickerson** [comment]
Ah, didn't think of that. Thanks!

**Comment by joelkesler** [comment]
Hello @chrisaljoudi, any idea when you will be making the safari port public?  Would love to start using it :)

**Comment by chrisaljoudi** [comment]
@joelkesler Hey Joel! Submitted PR #517 which will make the Safari version public.

Feel free to take a look at the updated README now/once the PR gets merged (I don't want to post links here to avoid trouble and inconsistency if someone comes across this later on).

**Comment by joelkesler** [comment]
Thanks! That is wonderful :)

**Comment by chrisaljoudi** [comment]
@gorhill just a gentle reminder: this issue might be closable now that the Safari version is public.

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock#safari

**Comment by ashishgandhi** [comment]
@gorhill @chrisaljoudi, I'm unaware of the mechanism Safari extensions use to update. Will the version downloaded from https://chrismatic.io/ublock/ update itself automatically or is manual intervention required?

**Comment by asoksevil** [comment]
Hey there,

I just wanted to point out that 0.8.5.5 nor 0.8.5.4 work on Safari 5.1 (it just crashes after starting up). 0.8.2 used to work perfectly until today...

What happened?

**Comment by chrisaljoudi** [comment]
@ashishgandhi it should automatically update (Safari has its own configuration whether to check for updates automatically or not, but you don't have to check the version and reinstall manually, etc.)

**Comment by chrisaljoudi** [comment]
@asoksevil Safari 5.1... are you on Windows?

**Comment by asoksevil** [comment]
@ashishgandhi I am on Snow Leopard 10.6.8.

It just stopped working mysteriously... then I went to this thread to look up for any new update and that's how I got the latest version (0.8.5.5)

**Comment by chrisaljoudi** [comment]
@asoksevil ah. Did you uninstall the previous version of µBlock completely (with a browser restart) before manually installing this version? If not, please uninstall all versions of µBlock, restart your browser, then install 0.8.5.5.

P.S.: 0.8.5.5 and on, updates will work automagically so you don't have to uninstall or reinstall manually.

**Comment by Deathamns** [comment]
5.1.7 crashes on Windows too (it has a problem with `Object.keys()`), since the introduction of the new dynamic filtering.

**Comment by gorhill** [comment]
- [軽量かつ高速でサイトやYouTubeの広告を非表示にしてくれるプラグイン「µBlock」がMacのSafari機能拡張に対応。](http://applech2.com/archives/42940293.html)
- [웹브라우저 광고차단 종결자 'μBlock'... 구글 크롬과 파이어폭스에 이어 사파리도 지원](http://macnews.tistory.com/2949) (Pity no Korean translator yet, they have to use the English version)

**Comment by asoksevil** [comment]
@chrisaljoudi I did a clean install of uBlock but couldn't manage to get it installed. It crashes immediately upon installing it. 0.8.2 seems to be the only one who works flawlessly on Safari 5.1.

**Comment by gorhill** [comment]
@Deathamns `Object.keys` is not used in dynamic filtering. Do you have a point in the code where you know the crash occurs? We could try to guess what causes the crash and try a trivial workaround.

**Comment by Deathamns** [comment]
@gorhill I didn't say that dynamic filtering filtering is the case, but that it crashes since then.
The problem was here by the way: [storage.js:309](https://github.com/gorhill/uBlock/blob/master/src/js/storage.js#L309).
The keys (path of the filter lists) were too long. I even a shim for `Object.keys`, but it crashed even when the array was manually generated.
When I used a substring of the keys (max. 100, 101 or something like that), then there was no crash.
However, that wasn't a solution, so I gave up thinking that no one will use it on this outdated version.

**Comment by gorhill** [comment]
> it crashed even when the array was manually generated ... When I used a substring of the keys (max. 100, 101 or something like that), then there was no crash

Well then, **if** a workaround could be figured, no doubt it would be ugly, and only for the purpose of supporting a Sept. 2012 browser, which is no longer maintained, and which OSX version has undergone [a huge amount of security fixes](http://en.wikipedia.org/wiki/Safari_version_history#Release_history).

Yes, let's forget about it, not worth. There is a price to use obsolete software, and in the current case the price is that uBlock is not available.

**Comment by spitfire** [comment]
Hi - maybe it's time to finally move this conversation on to the new project?
If I understood you correctly it is now maintained at https://github.com/Deathamns/uBlock right?
I think it would be a good Idea, to close this thread, leave a pointer to the new place, and discuss any issues there..

**Comment by Deathamns** [comment]
@spitfire
> If I understood you correctly

You didn't. That was a temporary fork for developing the Safari port. Everything is on this repository now, and issues can be reported here (but indeed, not in this thread).

**Comment by spitfire** [comment]
So the safari port isn't splitting from the main one (like it was suggested before), and is staying here?

**Comment by gorhill** [comment]
@spitfire https://github.com/gorhill/uBlock/issues/117#issuecomment-70377408

**Comment by iyee** [comment]
"Show the number of blocked requests on the icon" not working on version 0.8.5.6.

**Comment by chrisaljoudi** [comment]
@iyee hmm, "not working" as in the count isn't showing up, or the setting isn't taking effect?

**Comment by iyee** [comment]
@chrisaljoudi the number doesn't show up while the option is checked, for which Deathamns's build acting normally.

**Comment by chrisaljoudi** [comment]
@iyee works fine on Safari 8.0.3 here — is there a non-zero number of requests blocked (as reported in the popover)?

µBlock doesn't show the badge now if the number of blocked requests is 0.

If that's not the issue, please let me know what version of Safari you're using.

**Comment by iyee** [comment]
@chrisaljoudi Version 8.0.2 (10600.2.5)
Have you ever updated this version today? It seems back to normal now.

**Comment by chrisaljoudi** [comment]
@iyee yes. 0.8.5.7 has just been pushed.

**Comment by iyee** [comment]
I'm sorry but there still some trouble here:

+ can't update to the newest version
![screen shot 2015-01-19 at 12 27 11 pm](https://cloud.githubusercontent.com/assets/88564/5795932/8b9c52a6-9fd6-11e4-973e-ffbdf4f42e69.png)

+ the count num doesn't always show up while I reload same page for several times.

**Comment by chrisaljoudi** [comment]
@iyee I'd be happy to open a separate issue for either of these — please feel free to, as well. Your feedback is incredibly important; we can more efficiently resolve this, however, if we could track these bugs neatly.

I'll try to reproduce the lack-of-badge — mind sharing whether the count **does** show up correctly in the popover? This popover:

![Pop](http://chrisly.me/image/41032I2O3L0X/Image%202015-01-18%20at%209.39.21%20PM.png)

**Comment by iyee** [comment]
@chrisaljoudi it doesn't show up now again, really weird as first shows up numbers but then just disappear, for every website I visit, yahoo.com for example.

**Comment by chrisaljoudi** [comment]
@iyee reproduced. #541

**Comment by PatTheMav** [comment]
@all - I would suggest that all further bugs with the Safari version be submitted as "proper" issue posts with Safari as a tag or something instead of clobbering up this issue (as it is "closed") and shouldn't be used for further bug reporting.

**Comment by asoksevil** [comment]
@gorhill Does that mean that Safari 5.1 won't be supported? We might not be able to use the latest version but you can at least release the latest version compatible with it. I'm using 0.8.2, not sure if it's the latest one.

**Comment by asoksevil** [comment]
@Deathamns @chrisaljoudi will you guys keep updating the version for Sari 5,6 and 7?

Thanks!

**Comment by locusathome** [comment]
@Chris, I have next to µBlock another plugin ClickToPlugin which tries, where possible, to make Safari use the HTML5 Quicktime version instead of the Flash version.

I am now back to µBlock 0.8.5.7 because I can use both plugins on Youtube and both do what they have to do, µBlock blocks ads and ClickToPlugin giving me the HTML5 Quicktime.

The moment I use µBlock 0.8.6.0 I see something different, I do not get the HTML5 Quicktime version but I get at the place where the filmcontainer is a warning that I have to update to a higher version of Quicktime or to install Flash.

Back to 0.8.5.7 and all is well again. I have had that a while back also with a version around 0.8.0.7 or so.

Some versions of µBlock interfere with ClickToPlugin and I do not know exactly what.

No problem for me though because I always keep a good working copy to fall back onto but I like to inform you (and indirect @gorhill ) of the fact.

**Comment by chrisaljoudi** [comment]
Official build of Safari port now available at

## https://chrismatic.io/ublock/

**Comment by PatTheMav** [comment]
Will donations be shared with @gorhill?

**Comment by chrisaljoudi** [comment]
@PatTheMav it's up to @gorhill :)

**Comment by chrisaljoudi** [comment]
@PatTheMav see https://github.com/gorhill/uBlock/wiki/Why-don't-you-accept-donations%3F

**Comment by PatTheMav** [comment]
Fair enough - I'd hate to have people forget the amount of work that @gorhill invested in µBlock.
