### ISSUE TITLE
'behind-the-scene * * allow' doesn't seem to work

### ISSUE THREAD

**Issue by sander85** [uBlock-LLC/uBlock#1171]
https://github.com/chrisaljoudi/uBlock/wiki/Behind-the-scene-network-requests describes `behind-the-scene * * allow`, but it doesn't seem to work.

I have these two rules:

```
* * 3p block
behind-the-scene * * allow
```

According to the wiki behind-the-scene request should be passed by default, but they get blocked by `* * 3p block`.

**Comment by AlexVallat** [comment]
Just to confirm, did you add the [Firefox] prefix because you've checked that this is Firefox specific, or because you noticed it while using Firefox?

**Comment by sander85** [comment]
At first it seemed like a Firefox issue but now I can confirm it on Chrome as well.

**Comment by my-password-is-password** [comment]
https://github.com/chrisaljoudi/uBlock/wiki/Dynamic-filtering:-precedence

Says "All cells override the `all` cells."

So the `3p` in `* * 3p block` overrides `all` in `behind-the-scene * * allow`, right?

Try `behind-the-scene * 3p allow`

**Comment by sander85** [comment]
But it also says that local rules override global ones, so shouldn't `behind-the-scene` be considered as local in this case? `behind-the-scene * 3p allow` seems to work, but that's actually not quite what I need. I would like this combination:

```
* * 3p block
behind-the-scene * image allow
```

uBlock seems to see it as a valid combination of rules as none of them is deleted automatically. But it doesn't seem to work. The reason for such a combination is quite simple. Firefox is getting favicons behind the scene. So all favicons get blocked by `* * 3p block`. And I see no way to whitelist them w/o allowing everything that is going on behind the scene.

**Comment by my-password-is-password** [comment]
<s>I think only the local `all` cell overrides the global `all` cell.</s>

And it also says `3rd-party override images`.

**Comment by sander85** [comment]
Ok, in that case there is not much that can be done here :/ I'll close this issue.

**Comment by my-password-is-password** [comment]
@sander85 

Does this work?

"My Rules"

```
* * 3p block
behind-the-scene * 3p noop
```

with 

"My Filters"

```
*$domain=behind-the-scene
@@*$image,domain=behind-the-scene
```

**Comment by sander85** [comment]
WOW, indeed it does! Thanks a bunch, I really appreciate it!

**Comment by neilishere** [comment]
No, it doesn't work for me

> So all favicons get blocked by \* \* 3p block. And I see no way to whitelist them w/o allowing everything that is going on behind the scene.

I'm trying to use "default deny" for behind-the-scene, but `behind-the-scene * 3p noop` overrides "My Filters" - as suggested above.

**Comment by gorhill** [comment]
> but behind-the-scene \* 3p noop overrides "My Filters"

This can't be, `noop` means do not override static filters. Look at the behind-the-scene in the logger and see what it tells about the favicons.

**Comment by neilishere** [comment]
Yes, you are right.  So I tried "My Filters" again (suggested above), but `@@*$image,domain=behind-the-scene` does not work for me.
`@@*$other,domain=behind-the-scene`  works, but allows everything else.

I tried making `@@||*favicon.ico,domain=behind-the-scene` to narrow the scope, but this isn't right.
Thank you.

**Comment by gorhill** [comment]
> I tried making @@||*favicon.ico,domain=behind-the-scene to narrow the scope, but this isn't right.

The double pipe `||` is to anchor to somewhere within the hostname, you don't want to use this in this case. Also you need to use `$` to separate filter options from filter itself.

Try `@@/favicon.ico$image,domain=behind-the-scene`.

**Edit:** modified suggested filter, the more specific the better for filtering engine.

**Comment by neilishere** [comment]
The filter before your edit was somewhat working, before you added `image`  About half the sites in my session would load the icons.  Now I see that some sites use .png or some variation with the word `favicon`.  But not all use .ico.

Now I can't get back to what you had the first time.

Edit: oops, the browser was restarted and I lost `behind-the-scene * 3p noop` because I didn't make permanent. I'll try again.

**Comment by gorhill** [comment]
Best would be for you to paste here the URLs for those favicons you are trying to block -- along with their reported types (image, other, etc.).

**Comment by neilishere** [comment]
My Filters:
`*$domain=behind-the-scene`
`@@/favicon.ico^$domain=behind-the-scene`
Give me this:

![Uploading behind.gif…]()

**Comment by neilishere** [comment]
I'll try again.  Sorry, I had to much blocked on Github
![capture](https://cloud.githubusercontent.com/assets/12305418/7555507/ce3a210a-f71b-11e4-839b-28682f495f77.JPG)

**Comment by neilishere** [comment]
This seems to work (maybe not the most elegant):

`* * 3p block`
`behind-the-scene * 3p noop`

and this
`*$domain=behind-the-scene`
`@@favicon$domain=behind-the-scene`

Gorhill: Thank you for your help - and a great project!! (you must be the hardest working dev.)
