### ISSUE TITLE
The future of uBlock for Firefox

### ISSUE THREAD

**Issue by Piter432** [uBlock-LLC/uBlock#1173]
Hey, Chris!

It's said that @gorhill, the original author of uBlock, has discountinued the development of his extension, but I'm happy about that you are now owner of uBlock. But, there's something terryfing for Firefox users. From information, which I get from Polish sites about software, technology, etc. (mostly from dobreprogramy.pl), you are good at developing extensions for Chrome and Safari, but not for Firefox. So, is this the end for uBlock for Firefox? I hope not, because there's currently no effective ads blocker for Firefox. Of course, I can use AdBlock Plus with Hiding Helper element and AdBlock Plus Pop-up addon, but the problem is that AdBlock Plus for Firefox "eats" more RAM than not installed ads blocker for Firefox and don't have many filters to choose as uBlock.

Please, share some information about this.

**Comment by AlexVallat** [comment]
I have agreed to maintain the Firefox version of uBlock; it won't be discontinued. Chris and I are currently discussing how to organise releases, but one way or another Firefox releases will continue.

I will also be responding to Firefox specific issues, though patience might be required during weekdays as I will generally be completely unavailable during working hours (GMT).

**Comment by ghost** [comment]
@AlexVallat 

How is the review queue for 0.9.1.0 looking on AMO?

**Comment by AlexVallat** [comment]
@kintpuash Currently at 119 of 195, since being submitted on March 13th. :-/

**Comment by ghost** [comment]
@AlexVallat 

A movement of three positions in a week. Ouch. Thanks.

6-7 presumably positive reviews were removed overnight. Does AMO indicate if those reviews were user deleted or a result of administrative action?

**Comment by mva1985** [comment]
I use this extension on my laptop and mobile device and have not had one lick of problems with it.

Thanks for continuing development!

**Comment by AlexVallat** [comment]
@kintpuash No details on the content or rating of the removed reviews is given, only that they were all from the same user, at the same time. That implies spam, but it's only a guess.

**Comment by ghost** [comment]
Pulled most up on Google cache earlier. They looked like different accounts, including a long one in German. There was a user spamming one star reviews couple weeks ago they hammered down on.

Here they are:

> Rated 5 out of 5 stars
> 
> by Aaron Raimist on March 31, 2015 · permalink · translate
> 
> Works very well.
> 
> Rated 4 out of 5 stars
> 
> by fernman on March 31, 2015 · permalink · translate
> 
> Can we please have some Options? I would like to be able to hide the count, for example. I am happy to know ublock is working, without being reminded how effective it is.

(Previous one potentially a violation of user review policy)

> Rated 5 out of 5 stars
> 
> by wagner reatto on March 30, 2015 · permalink · translate
> 
> the best
> 
> android Rated 4 out of 5 stars
> 
> by crazycheese on March 30, 2015 · permalink · translate
> 
> Please support 36/37 (current/beta) mobile - refuses to install
> 
> Rated 5 out of 5 stars
> 
> by alekksander on March 29, 2015 · permalink · translate
> 
> this really is above any star-rating system. simply excellent!
> (user, check developer's page for fresh version)
> 
> Rated 5 out of 5 stars
> 
> by vntgmmrs on March 29, 2015 · permalink · translate
> 
> Firefox opens much quicker with this add-on and blocks the same as the other ad-blocking extension but much faster loading of pages and opening of browser. THANK YOU!!! Also... PLEASE make extension for Android, too.
> 
> Browser performance goes up Rated 5 out of 5 stars
> 
> by Serwis on March 29, 2015 · permalink · translate
> 
> After installing µBlock performance of firefox really increased. Webpages open faster comparing to adblock or any other similar extension.
> No cons so far.
> 
> Excellent! Rated 5 out of 5 stars
> 
> by Jim on March 27, 2015 · permalink · translate
> 
> Firefox loads faster with uBock compared with Adblock plus or Ablock edge even with added filters.
> 
> Rated 5 out of 5 stars
> 
> by Norvexaxar000 on March 25, 2015 · permalink · translate
> 
> Pretty fantastic all around. I can't imagine going back to Adblock after this. Now to wait patiently for >the matrix filtering...
> 
> Rated 5 out of 5 stars
> 
> by Northtech on March 23, 2015 · permalink · translate
> 
> Please add for default whitelist this string — about-scheme.
> Thank you for nice addon.
> 
> Derzeit bestes Addon gegen Werbung,Tracking und Pop-ups 
> 
> Rated 5 out of 5 stars
> 
> by aikidobruce on March 23, 2015 · permalink · translate
> 
> Ich habe mittlerweile einen guten Überblick erhalten, welche Werbeblocker empfehlenswert sind >und welche nicht...

long text removed

**Comment by AlexVallat** [comment]
In that case, I haven't a clue. The only thing I see in the listing is that about a day ago someone deleted 10 reviews, all at the same time. It doesn't say which ones (except as id numbers).

**Comment by ghost** [comment]
Appreciate you looking into it. Possible the other 2 reviews were deleted by the authors. Back on topic, gorhill mentioned in the Chrome store earlier today he felt the extension was effectively feature complete.

Any thoughts? Looking at the code, how close to submission for full review do feel the the Firefox version?

**Comment by AlexVallat** [comment]
I think once we release at 1.0 and no longer consider it to be "experimental" then it will be submitted for full review. As far as I'm concerned, it's not so much that anything is missing, but that there are still a steady stream of bugs being reported, particularly since the 0.9.3.0 change. It would probably be best if those dried up before considering it 1.0-ready!

**Comment by SivaMachina** [comment]
Not sure if this is approiate for this thread. But I forked the greasemonkey script to help with whitelisting youtube accounts for ABP (https://greasyfork.org/en/scripts/4168-youtube-whitelist-channels-in-adblock-plus) and made it work better for uBlock. and removed most if not everything in the code pertaing to ABP

https://greasyfork.org/en/scripts/9116-youtube-whitelist-channels-in-ublock
