### ISSUE TITLE
No UI for Managing Site Specific Switches

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1175]
Unlike the Dynamic Filtering and Static Filtering, there is no UI or editable list to work with to see what sites have had popups blocked, or strict blocking disabled.

Between uBlock and uMatrix, I do a lot of list management, storing large lists in different files that I can import in certain cases.

These rules aren't editable unless you know what site you toggled.

It would be nice to have an editable list much like the dynamic filtering, and possibly a wildcard so I can force disable popups (we might need a way to know they've been blocked, since this probably won't throw up the default blocked browser icon when Chrome itself blocks them). Sites are less than a dozen that I would allow popups for.

It would make sense to have this, given that uMatrix has this for "Strict HTTPS" and I wildcard enable that and disable it if things break, or I care enough about missing images to toggle.

**Comment by chrisaljoudi** [comment]
Site-specific switches are no longer an issue in 0.9.3.5.
