### ISSUE TITLE
[Firefox] Dynamic filtering pane broken for behind-the-scene

### ISSUE THREAD

**Issue by my-password-is-password** [uBlock-LLC/uBlock#1176]
## Steps to Reproduce
1. Open `chrome://ublock/content/devtools.html?tabId=-1` in a tab
2. Open `about:addons` in a new tab and do a "Check for updates"
   - Or open a page where it makes a behind-the-scene request
3. Observe the Dynamic filtering pane for behind-the-scene ( 1st tab )
## Symptoms

The Dynamic filtering pane doesn't get populated.

![ublockbehindthescenebroken](https://cloud.githubusercontent.com/assets/6408935/6990648/2866a648-da26-11e4-9b78-dea7ca8db282.png)
## Info

```
uBlock 0.9.3.0
FF 37.0.1
Win 7
```

**Comment by my-password-is-password** [comment]
It works if you use the black button in the request log but not if you use the toolbar icon. 

![ublockbehindthescenebroken2](https://cloud.githubusercontent.com/assets/6408935/6990702/2e3187cc-da27-11e4-9de1-cab4a987c3b3.png)

I don't remember it working like this.  

Also if you use the toolbar icon the black button stops working.

@chrisaljoudi, the issue template link is broke.  Gets a 404.

**Comment by AlexVallat** [comment]
Confirmed, thanks for reporting this. I've got a fix ready to be merged for it now.
