### ISSUE TITLE
--disable-remote-fonts makes uBlock unusable

### ISSUE THREAD

**Issue by octoploid** [uBlock-LLC/uBlock#1181]
![shot](https://cloud.githubusercontent.com/assets/327746/6993133/cfbbb018-daea-11e4-84d3-b115cabe8db4.png)

Could you please use gifs instead?
Thanks

**Comment by lewisje** [comment]
I didn't think the FontAwesome fonts were "remote"; anyway, I think PNGs would be better because of alpha blending.

**Comment by chrisaljoudi** [comment]
@lewisje at one level, yes, but the sacrifice in interoperability across pixel densities is quite significant. 

Still, it'd be feasible to use SVGs instead. 

At that point, though, that's pretty much as good as just packaging and shipping FontAwesome with uBlock so it's all local.

**Comment by lewisje** [comment]
I briefly looked at the code and didn't see where FontAwesome was called; I originally thought it _was_ local and was surprised that it's not.

**Comment by chrisaljoudi** [comment]
Upon further investigation, FontAwesome isn't actually "remote" currently in uBlock. Chrome's `--disable-remote-typefaces` disables all webfonts included with `@font-face`, "remote" or not.

**Comment by my-password-is-password** [comment]
Found this, https://icomoon.io/

You pick what font library you want ( Font Awesome ) and select just the icons you want to use.

![ublockfontawesomesvg1](https://cloud.githubusercontent.com/assets/6408935/6994105/0aaa6f12-dac2-11e4-84f0-5a20dd86797f.png)

Then you can generate SVG or a subset of the font.

![ublockfontawesomesvg2](https://cloud.githubusercontent.com/assets/6408935/6994109/1ee5ea38-dac2-11e4-8eac-ad8c4a4719f4.png)

Below is the 7 icons generate into svg that I could find uBlock using.  Might be missing some.  I just did a search for "class fa" on github.

https://github.com/my-password-is-password/stuff/blob/master/IcoMoon%20-%20uBlock%207%20Icons.zip

Edit:
Forgot the Power button.  Heres the Font Awesome subset.

https://github.com/my-password-is-password/stuff/blob/master/icomoon%20-%20uBlock%20fontAwesome%20subset.zip

**Comment by chrisaljoudi** [comment]
@my-password-is-password yep; thanks! Very neat.

I've integrated an implementation of that into my local clone of the repo, and will be pushing it very soon (just need to make sure I didn't break anything obvious).

---

Side note: there are problems with the FontAwesome icons in SVG format (misalignment and incorrect sizes) — mainly because FontAwesome doesn't really provide the glyphs in independent SVGs. 

So, I went with _slightly_ different icons for some of them (the differences are visual and minor).

**Comment by chrisaljoudi** [comment]
Hi @octoploid!

Good news! uBlock now uses a set of SVGs it ships with for all the icons. The icons are much lighter, and, of course, it works even if you have web fonts disabled.

There were multiple commits of relevance in the range [a947537...53768aff22dba312ee86ce35885848e69b126e6a).

**Comment by ghost** [comment]
Thank you Chris.

**Comment by octoploid** [comment]
Many thanks.

**Comment by octoploid** [comment]
![fix](https://cloud.githubusercontent.com/assets/327746/7020250/d340fe08-dd17-11e4-815c-88958b2efb61.png)
