### ISSUE TITLE
Canvas Blocking

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1183]
Is it possible to enable blocking for Canvas Fingerprinting ?

Thanks

**Comment by lewisje** [comment]
It sounds like the EasyPrivacy list blocks most scripts that would make use of [canvas fingerprinting](https://en.wikipedia.org/wiki/Canvas_fingerprinting).

**Comment by gitarra** [comment]
There are separate addons for blocking canvas fingerprinting, it may be too broad for the scope of ublock.

Heres one for Firefox: https://addons.mozilla.org/en-us/firefox/addon/canvasblocker/

**Comment by ghost** [comment]
I use CanvasFingerprintBlock for Chrome but sadly there is no way at all to whitelist it, and sometimes a site I allow/need to run JS deviously put Canvas in their main JS.

**Comment by chrisaljoudi** [comment]
Right now, this seems like it's outside uBlock's scope (determining which websites are worthy of trust for `canvas` usage or not is not clear-cut, either).

Will keep an eye on this, though.

**Comment by slrslr** [comment]
> Preventing the canvas image from loading is an identifier in itself. Although the canvas fingerprint will not be sent, the fact that you did not load the canvas image will be. So, you will be sorted into a very small group of tech-savvy users who are also blocking fingerprints, and from there, your ordinary fingerprints will sometimes be enough to identify you completely.

> Using different fingerprints for every request doesn’t work for the same reason submitting no fingerprint doesn’t work. A normal visitor will not change his fingerprint in a session. So, if you change your fingerprint during a session, that behavior is unusual, and it’s enough to categorize you into an irregular group.

[source](https://multiloginapp.com/how-canvas-fingerprint-blockers-make-you-easily-trackable/)

Check canvas fingerprint: https://browserleaks.com/canvas
