### ISSUE TITLE
Twitch.TV video ads are not being blocked.

### ISSUE THREAD

**Issue by distributedlock** [uBlock-LLC/uBlock#1184]
Ads coming from the video on live streaming website http://twitch.tv are not being blocked anymore as of today. I assume they have changed their methods of delivering ads to bypass a variety of several ad blocking extensions.

**Comment by chrisaljoudi** [comment]
Hi @RanadeepPolavarapu!

What browser is this occurring with? Do you have a URL where the issue consistently occurs?

I've tried to reproduce but have been unable to.

**Comment by distributedlock** [comment]
Hi @chrisaljoudi,

The browser is Chrome (v41.0.2272.118 (64-bit)). The URL where this issue occurred was: http://www.twitch.tv/riotgames/popout.

Image of issue:
![screen shot 2015-04-04 at 6 53 53 pm](https://cloud.githubusercontent.com/assets/7084995/6995028/42ce6602-dafc-11e4-83ce-b34b1cbe7637.png)

Please ignore that red box in the middle, I was removing out my bookmarks from the image and accidentally left that box in the image.

I have been able to reproduce the issue several times at that URL.

**Comment by chrisaljoudi** [comment]
@RanadeepPolavarapu still can't reproduce — I was able to see ads with uBlock disabled, but **no** ads with uBlock enabled.

What version of uBlock are you using?

Also, it looks like you have some other extensions running. What are they? Does the problem occur if you disable them?

**Comment by distributedlock** [comment]
@chrisaljoudi I am using uBlock v0.9.3.0. The other extensions were Hola Better Internet, LoL Stream Browser, and Twitch Now. I have disabled them all with only uBlock enabled and I can still reproduce this issue.

**Comment by pedrolucasmag** [comment]
Same with Firefox 36.0.4

**Comment by timvermeulen** [comment]
Were they ever blocked? I'm on Safari 8.0.5 on OSX 10.10.3 (using uBlock 0.9.3) and I think I have never had Twitch ads blocked.

**Comment by Betsy25** [comment]
I get the page below when I have Block 3rd party, 3p scripts & 3p frames enabled globally.
Bypassing those 3, and leaving all my blocklists enabled, got me to a videostream, but it was offline, so was not able to correctly see if the ad itself gets loaded then also.
EDIT: clicking any of the streams at the bottom correctly plays them, no ads encountered.
(Firefox nightly v40, Win7)

![Screenshot](http://i.imgur.com/YUID3kw.png)

**Comment by distributedlock** [comment]
@timvermeulen I don't know about Safari, but on Chrome they were always blocked.

**Comment by chrisaljoudi** [comment]
@timvermeulen Safari doesn't allow for intercepting requests coming from Flash. So, if you're using Safari, do you have plug-ins (incl. Flash) disabled?

That way, Twitch will use HTML5 instead and uBlock will be able to filter those requests.

**Comment by ghost** [comment]
Ah yes this is the exact issue I have. And it's with the exact same stream. I'm on the latest version of firefox 37.0.1

**Comment by timvermeulen** [comment]
@chrisaljoudi That's unfortunate. Twitch does not use HTML5, unfortunately (there are workarounds, but then you lose chat and other features), so disabling Flash will not solve my problem. I suppose I'll just have to accept the ads if I'm going to stick with Safari.

**Comment by boniboni** [comment]
still happening

**Comment by iNfz** [comment]
firefox 37.0.1, ublock just shuts off on twitch stream after hour or two.

**Comment by j0hnlam** [comment]
Can only recreate the problem on Safari (uBlock 0.9.3.5).

**Comment by epitaque** [comment]
It's been happening to me in Chrome recently

**Comment by anishlr** [comment]
This is a problem again. I'm using Chrome (49.0.2623.87 m)

**Comment by distributedlock** [comment]
@anishlr Migrate to [uBlock Origin](https://github.com/gorhill/uBlock). This is currently unmaintained.
