### ISSUE TITLE
remove donorschoose.org from block list

### ISSUE THREAD

**Issue by thejohnfreeman** [uBlock-LLC/uBlock#1185]
Why is this site blocked? I don't consider them malicious. I don't find their ads invasive. When I navigate to donorschoose.org, I want to see the site, not that uBlock has blocked it.

https://github.com/chrisaljoudi/uBlock/blob/04b3ee25fcff2b009cd5ebb60f10d86e10f810e2/assets/thirdparties/pgl.yoyo.org/as/serverlist

**Comment by anothermindbomb** [comment]
What blocklists have you turned on?

**Comment by anothermindbomb** [comment]
Whitelist the site or switch off whatever blocklist you've enabled which blocks this site.

**Comment by chrisaljoudi** [comment]
Hi @thejohnfreeman!

uBlock doesn't maintain those filter lists — they are third-party. It looks like the one you mentioned that has `donorschoose.org` is Peter Lowe's. 

You can disable Peter Lowe's list, whitelist the website, or even use  an exception rule to cancel out the block entry:

```
@@||donorschoose.org
```

**Comment by thejohnfreeman** [comment]
I see. Thanks, everyone.
