### ISSUE TITLE
For some reason Ublock prevents Feedly from opening a link to Kotaku.

### ISSUE THREAD

**Issue by DarkghostX** [uBlock-LLC/uBlock#1186]
When browsing Feedly, and then clicking to open a new tab towards Kotaku Ublock appears to prevent the page from loading. It talks about ||feedsportal.com/c/ but I am not sure what is going on. After trying it out it appears that Ublock prevents the user from going to Feedsportal.com at all. This only started very recently, I have not had this issue before today (Saturday).

I joined Github to submit this issue so I am still kinda new.

I have a full link of what Ublock says is being blocked but I do not know if there are any personal identifiers in that info so if you need me to post the link then let me know.

I am unsure as to whether this is a bug, if it is intended, how much of a danger this feedsportal.com stuff is, what filter list this entry is under, or what so please let me know.

**Comment by chrisaljoudi** [comment]
This is resolved in 0.9.3.5 (soon to be released).
