### ISSUE TITLE
seasonvar.ru blocking does not work

### ISSUE THREAD

**Issue by pvlb** [uBlock-LLC/uBlock#1188]
On the site seasonvar.ru blocking does not work for Firefox 37.0.1 but Chromium 44.0.2358.0 (64-bit Linux) OK... 
Exemple: http://seasonvar.ru/serial-10432-CHernyj_spisok-2-season.html
Compare ABP 2.6.9 http://goo.gl/qEQlbs
and uBlock 0.9.2.4/0.9.3.0 http://goo.gl/vYT4aV http://goo.gl/KBQmpc
Update page, F5 or reload browser not help... BlockLists identical...

**Comment by xDShot** [comment]
It works for me. Firefox 37.0.1 and uBlock 9.3.0.
http://imgur.com/JHOaZY7

**Comment by chrisaljoudi** [comment]
Hi @pvlb!

I've tried to reproduce the issue and have been unable to so far.

However, looking at your screenshots, it looks like _both_ uBlock and ABP are there in the toolbar in all three screenshots.

For instance, in the ABP screenshot, uBlock looks activated.

Am I missing something? Does this issue occur if you disable one and use **just one** of uBlock/ABP at a time?

**Comment by pvlb** [comment]
Use only one blocker. Clean all my filters and rules, clean all caches and update now... to fix this problem :) Perhaps the problem was in the database sqlite.
