### ISSUE TITLE
Element hiding not applying to this website.

### ISSUE THREAD

**Issue by Betsy25** [uBlock-LLC/uBlock#1189]
Website : http://www.universalmediaserver.com/

Even though I have the list (  Fanboy’s Social Blocking List‎ ) containing the element hiding element in it
 **###socialButtons** checked, the item still shows up on the left side of the page.
![Image](http://i.imgur.com/0hxaauD.png)

Anyone able to reproduce please ?

uBlock 0.9.3.0 , Win7 32bit, Firefox nightly v40

**Comment by gorhill** [comment]
`#SocialButtons` is not same as `#socialButtons`.

**Comment by Betsy25** [comment]
Oops :flushed:
Thanks for chiming in @gorhill :)
Fixed.
