### ISSUE TITLE
Need exception for Avianca e-checkin and possible others

### ISSUE THREAD

**Issue by ConorIA** [uBlock-LLC/uBlock#119]
Can load checkin.avianca.com with µBlock enabled. I tried to see what was being blocked, but since it loads in a popup the staistics page didn't seem to find it. (Using out of the box filters)

**Comment by gorhill** [comment]
Does the same problem occur with ABP? If so, than this needs to be dealt with the _EasyList_/_EasyPrivacy_ maintainers.

What is the exact URL address where the problem occurs? Does this require buying flight tickets to see the problem?

Ultimately, whitelisting (power button in popup menu) that site might be the best solution.

**Comment by gorhill** [comment]
Ok, I can reproduce.

**Comment by gorhill** [comment]
Fixed. Go to _About_ tab in dashboard, and there should be on entry which needs to be updated, you can force an update using the _Update_ button at the bottom.

Avianca breaks without google-analytics.

**Comment by gorhill** [comment]
By the way:

>  I tried to see what was being blocked, but since it loads in a popup the staistics page didn't seem to find it

The log of the pop-up tab should still be available in the _Statistics_ tab, you may need to click the refresh icon to force uBlock to enumerate and internally update data for all the tabs:

![to-forum](https://cloud.githubusercontent.com/assets/585534/3753410/faa4a196-1811-11e4-840e-de29bc83ec46.png)
