### ISSUE TITLE
Ability to show infobar in Firefox about blocked windows like in AdBlock Plus + AdBlock Plus Pop-up Addon

### ISSUE THREAD

**Issue by Piter432** [uBlock-LLC/uBlock#1190]
Hey, Chris.

uBlock is perfect for Firefox, but one thing should be as option with ability to disable it. I mean that when using AdBlock Plus + AdBlock Plus Pop-up Addon and after proper configuration to both of them, all pop-up windows are blocked, but there's displayed also an infobar about that AdBlock Plus Pop-up Addon has blocked x (where "x", there's number of pop-up windows blocked by AdBlock Plus Pop-up Addon) pop-up windows.

What do you think about that? :)

**Comment by gitarra** [comment]
Do you mean this?
![firefox-allow-popup](https://cloud.githubusercontent.com/assets/4739888/6997700/f48ee312-dbce-11e4-9e8f-565df3d78b10.jpg)

A notice about the blocked popup and the ability to allow popups?
A screenshot would be helpful to understand exactly what you mean.

**Comment by Piter432** [comment]
Yes. Exactly :)

**Comment by AlexVallat** [comment]
If you just want to block all pop-ups, with a notification and the ability to allow them, then what's wrong with using the "Block pop-ups" option built into Firefox?

**Comment by Piter432** [comment]
The problem is that not all pop-ups, which are sometimes really frustrating, are blocked by Firefox "Block pop-ups" option. Same with installed AdBlock Plus, if AdBlock Plus Pop-up Addon isn't installed. uBlock has it implemented already very well, but the infobar about blocked pop-up/s isn't displaying.

**Comment by sander85** [comment]
Maybe report such pop-ups to Mozilla so they can improve their pop-up blocker?

**Comment by Snapy** [comment]
Use the "strict popup blocker" addon. It will allow you to switch between blocking all popups (very restrictive) and only some (default firefox behaviour).

**Comment by AlexVallat** [comment]
So, if I understand right, you would like it so that if you have turned on the uBlock "block all popups" option for a site, every time a popup is blocked by uBlock, it shows a notification which allows you to turn that option off again? On Firefox this would be an info-bar, but if the functionality is implemented it wouldn't be firefox specific. We would need equivalents for each supported browser.
