### ISSUE TITLE
Infoworld article is cut short

### ISSUE THREAD

**Issue by jruderman** [uBlock-LLC/uBlock#1192]
When uBlock is enabled, only the first two paragraphs of http://www.infoworld.com/article/2905688/applications/mozillas-rust-based-servo-browser-engine-inches-forward.html are shown.

I am using Firefox Nightly on Mac. Updating from the AMO version (0.8.8.2) to the GitHub version (0.9.3.0) did not make the problem go away.

**Comment by PalmerAL** [comment]
It's because of the following rule in easyList:

infoworld.com##.fakesidebar

**Comment by my-password-is-password** [comment]
Yeah, like @PalmerAL said, it was `infoworld.com##.fakesidebar` that is also in Fanboy Ultimate list.

Make an exception in "My Filters"
`infoworld.com#@#.fakesidebar`

Is China still ddosing github?  Its so damn slow for me.

**Comment by chrisaljoudi** [comment]
Hi @jruderman!

Like @PalmerAL said, what's causing the rest of the article to be hidden is the `##.fakesidebar` filter.

However, there's more to the story. The filter is fine — it's not a false positive. What's going on can be seen if you look at the markup of the article:

``` html
... <!-- up until now, the article is visible -->

<aside class="fakesidebar"/>
<!-- ah ha! It's trying to be a self-closing tag;
that just doesn't work out -->

<!-- the article is hidden from here on out
because the browser thinks this is inside the .fakesidebar <aside> -->
...
<p>Don't ditch your existing browser, though. Servo...
```

**Comment by chrisaljoudi** [comment]
[More on how self-closing tags don't self-close](http://tiffanybbrown.com/2011/03/23/html5-does-not-allow-self-closing-tags/).

**Comment by jruderman** [comment]
I reported the problem to EasyList and they've fixed it: https://forums.lanik.us/viewtopic.php?f=64&t=22014&e=0

Does Fanboy Ultimate need its own bug report, or do they update based on EasyList?

**Comment by ghost** [comment]
@jruderman 

> Does Fanboy Ultimate need its own bug report

No, should be all set.
