### ISSUE TITLE
Lots of false positives

### ISSUE THREAD

**Issue by ProLoser** [uBlock-LLC/uBlock#1193]
This is getting a ridiculous amount of false positives to the point where 1 in 3 websites I visit stop functioning properly, and it always takes me a while to notice. Almost any website that uses Facebook OAuth to login doesn't work, clicking on the button does nothing (my guess is that this extension is breaking javascript). This happens on mercuryinsurance website, on uber I believe, on spotify, just a LOT of websites.

**Comment by LocutusX** [comment]
It's not this extension, it's your filters.

Check which filterlists you have enabled and reduce them accordingly. I like my uBlock to have roughly the same "default setup" as ABP, so the only filterlist I have enabled is EasyList. And guess what... the entire internet works just fine for me, no Facebook OAuth issues anywhere...

**Comment by chrisaljoudi** [comment]
@ProLoser Hi!

As @LocutusX mentioned, uBlock will only block as much or as little as you tell it to. The default configuration was carefully chosen in an attempt to reduce overhead and clutter while breaking little (or nothing).

So, if there are some top websites that seem to be breaking with uBlock's default configuration, that is an issue.

Please do provide an example link/steps to reproduce (along with the name/version of the browser), and we'll work on finding out what the problem is.

Your feedback is appreciated!

**Comment by ProLoser** [comment]
I was pretty sure I had the default configuration but I will double check

**Comment by chrisaljoudi** [comment]
Hi @ProLoser!

Any updates?

**Comment by ProLoser** [comment]
Nope definitely still occuring with a default install, in fact in non-power-user mode I would have no way of even knowing what filters are doing this. Go to mercuryinsurance.com and try simply clicking on the login link under my account dropmenu. Nothing works. You can probably view the console to see JS crashing. This is definitely a big problem. Screenshot of active filters after a fresh install:

![screen shot 2015-04-18 at 2 38 49 pm](https://cloud.githubusercontent.com/assets/67395/7217328/c9139ebc-e5d8-11e4-9418-a6dc5df80c57.png)

**Comment by gorhill** [comment]
> Go to mercuryinsurance.com and try simply clicking on the login link under my account dropmenu. Nothing works.

It's not uBlock-specific, you get the same issue with ABP + EasyPrivacy. EasyPrivacy's `/b/ss/*&aqe=` filter blocks the following resource:

```
> http://mercuryinsurance.d2.sc.omtrdc.net/b/ss/mimercuryinsurance.comprod/1/H.25/s12051576711237?AQB=1&ndh=1&t=18%2F3%2F2015%2017%3A47%3A19%206%20240&ns=mercuryinsurance&pageName=corp%3Ahome-page&g=http%3A%2F%2Fwww.mercuryinsurance.com%2F&cc=USD&ch=corp%3Ahome&c3=5%3A30PM&c4=Saturday&c5=Weekend&c6=New&c8=corp%3Ahome-page&v17=5%3A47%3A19%20PM&s=1920x1080&c=24&j=1.6&v=Y&k=Y&bw=1221&bh=896&AQE=1
```

Report to EasyPrivacy maintainers(s): https://forums.lanik.us/viewforum.php?f=64

**Edit:** Curiously, the breakage does not occurs on Firefox, just on Chromium. An illustration of why it's important to share details in bug reports.

**Comment by LocutusX** [comment]
This goes back to what I posted 15 days ago - with only EasyList enabled, there aren't any issues. Looks like the OP was not paying attention.

**Comment by ProLoser** [comment]
I was paying attention, I was saying that with a fresh install there is far more enabled.
