### ISSUE TITLE
Why are 3rd party filters allowed to "overwrite" my filters?

### ISSUE THREAD

**Issue by Maxxee** [uBlock-LLC/uBlock#1194]
My filters should _always_ have a higher priority than any 3rd party filter!

At the very least make it an option.

**Comment by sander85** [comment]
Give some example or test case please..

**Comment by Maxxee** [comment]
A custom filter like "http://x.x.org/*" is overwritten by the 3rd party filter "@@x.x.org$domain=x.org".

Seems like a bug or misbehavior to me because custom filters should always have the highest priority.

**Comment by ghost** [comment]
@Maxxee try `http://x.x.org/*$important` It's uBlock syntax extension.You can see examples in chrome://ublock/content/assets/ublock/privacy.txt

**Comment by Maxxee** [comment]
Indeed, it works as you described. Thanks for the hint.
On my system the examples in chrome://ublock/content/assets/ublock/privacy.txt use ",important" which doesn't work.
But using "$important" - as described by you - works fine.

**Comment by ghost** [comment]
For reference https://adblockplus.org/en/filters#options
