### ISSUE TITLE
External (e.g. Estonian) filters aren't updated automatically

### ISSUE THREAD

**Issue by sander85** [uBlock-LLC/uBlock#1196]
My browser is usually working 24/7 but I can see that the list "EST: Eesti saitidele kohandatud filter‎" was last updated 14 days ago. This should happen more often to keep up with changes.

"Peter Lowe’s Ad server list‎" and "Malware Domain List‎" are updated 5 days ago. So updating seems to work but not for all filter lists.

Browser: Fx 36.0.4/37.0.1
uBlock: 0.9.3.0

**Comment by ghost** [comment]
I just activated that list and got the version 20150328 from `http://adblock.ee/list.php` and this seems to be the latest. Which one do you have?

**Comment by sander85** [comment]
I'm not sure how can I check this version but I can see that I have 344 rules when I should have 346.

**Comment by Maxxee** [comment]
This is a cosmetic bug but still a serious one.
_All_ 3rd-party filter lists are shipped with uBlock's installation file.
All active lists are indeed updated regularly but when you want to inspect them from within uBlock the old shipped versions are shown instead of the latest update.

**Comment by ghost** [comment]
@Maxxee on Firefox when middle clicked? https://github.com/chrisaljoudi/uBlock/issues/860

**Comment by Maxxee** [comment]
@gwarser, I believe I had that problem with left and middle mouse clicks.
After reading through that issue you mentioned I thought that maybe the Clean Links extension was the problem, but after I disabled it and re-enabled it again left mouse click now loads the updated list.
I don't know what happened.

**Comment by sander85** [comment]
Maybe the problem is that the Estonian one isn't included with the extension and is external.
