### ISSUE TITLE
[Firefox] Empty tooltip

### ISSUE THREAD

**Issue by inoyakaigor** [uBlock-LLC/uBlock#1197]
![default](https://cloud.githubusercontent.com/assets/1235286/7004866/39d97b52-dc7a-11e4-8c42-6e4d44ff0a62.png)
build 0.9.3.1

**Comment by Snapy** [comment]
@inoyakaigor  There is no official 0.9.3.1 version but I suppose you're using gorhill's fork and the latest dev version resolves the issue.

**Comment by chrisaljoudi** [comment]
@inoyakaigor looks like it was an issue with missing translations. Notice that 0.9.3.1 isn't official, anyway.
