### ISSUE TITLE
[Filter List] Malware list IMPORTANT question.

### ISSUE THREAD

**Issue by jedipeludo** [uBlock-LLC/uBlock#1199]
Hello there, i would like to know where can i find the source of the following malware list:

http://i.imgur.com/l9p7j3Y.jpg
(The one on with the red square)

My website is in that list, and i can confirm, as you can that there's not such thing as a malware on it.

So, it would be nice if someone could tell me where can i contact the administrator of that list.

**Comment by Nurple** [comment]
Heya, if you click it, it will show you in the address bar. Anyway it's http://www.malwaredomains.com/

**Comment by jedipeludo** [comment]
Thank you very much Nurple!
