### ISSUE TITLE
Possibility to view blocked elements + corresponding filters

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#12]
Feedback from the chrome store:

> It would be nice to see which elements on webpage are being currently blocked and which filter blocks them. In future releases it could really help people to make whitelists. Thank you!

**Comment by zerkms** [comment]
Just as a minor addition: it also might be helpful to show not only the exact filter applied, but also a subscription name that it came from.

**Comment by gorhill** [comment]
I think I will address this one next, as it will also be useful for me as a dev to debug.

**Comment by swrobel** [comment]
Where exactly can this information be viewed?

**Comment by gorhill** [comment]
Check _"Enable the logging of network requests"_ in _Statistics_ tab in the dashboard.

**Comment by anewuser** [comment]
I don't see any "Statistics tab" on Firefox. Is this still being implemented?

**Comment by dpkirchner** [comment]
In 0.9.5, on Chrome, you can view the blocked resources list by clicking the sort icon next to the "on this page" and eyedropper.
