### ISSUE TITLE
Not loading settings

### ISSUE THREAD

**Issue by thepaperpilot** [uBlock-LLC/uBlock#1201]
Using version 0.9.3.0 on Firefox 37.0 on Ubuntu
I've also tried all the versions 0.9.2.0 - 0.9.3.0, same issue.

The issue is that uBlock doesn't load any settings. First time installing it, it wasn't blocking anything until I manually went into advanced mode and told it to block 3rd party and 3rd party frames. Restarting Firefox also resets all the settings (and once again, won't block anything until I manually tell it to in advanced mode) Restoring does the same thing. Telling it to save to a file works, but loading from a file doesn't (it also doesn't close the dashboard tab, like it does when I tell it to restore. Possibly related)

I've tried reinstalling, and using older versions. 

Edit: Also, to clarify, this is not an issue with my rules being temporary. Making them permanent doesn't solve the problem, and the other settings are reset as well.

**Comment by gorhill** [comment]
Can you see error messages in the browser console? (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-J)?

**Comment by thepaperpilot** [comment]
I happened to reinstall my os  between then and now,and can't reproduce the
problem. Sorry I can't help now, but at least working for me now

**Comment by chrisaljoudi** [comment]
If it re-occurrs, let me know and I'll reopen.
