### ISSUE TITLE
document-blocked.html should show filter's origin (filters)

### ISSUE THREAD

**Issue by yfdyh000** [uBlock-LLC/uBlock#1203]
This warning is shows caused filter, but not show the filter belongs filters, it may be difficult to found it, the users usually enabled a number of filters set, contains tens of thousands of filters.

It should transfer the name of the filters. Transfer the ID might be better, get its name, and allow users to click it to view source (like on Settings interface).

Example: `chrome://ublock/content/document-blocked.html?details=eyJ1cmwiOiJodHRwOi8vbHVja3loZWFsaW5nc3RvcmUucnUvIiwiaG4iOiJsdWNreWhlYWxpbmdzdG9yZS5ydSIsIndoeSI6InNiOnx8bHVja3loZWFsaW5nc3RvcmUucnVeIn0=`

Relevant code: https://github.com/chrisaljoudi/uBlock/blob/3d382851007b992b109a24f23e7b65e5947aeece/src/js/traffic.js#L220

**Comment by chrisaljoudi** [comment]
Document blocking is gone in 0.9.3.5. For the moment, it's troublesome and provided little value compared to the frustration it caused.

**Comment by 2vek** [comment]
@chrisaljoudi  Will document blocking be added back in future?
I was using it as sort of productivity tool to block websites like reddit, hn, youtube etc especially on weekdays.

For the time being, I have downgraded back to 0.9.3.0.

EDIT: found an actual valid [use case of that feature](https://www.reddit.com/r/firefox/comments/333nq1/ublock_0935_released_ui_refinements_firefox/cqhf1ma)
