### ISSUE TITLE
Sideload (white) list via text-file

### ISSUE THREAD

**Issue by Finkregh** [uBlock-LLC/uBlock#1204]
Hi,

(i did already search in the bugs and found nothing fitting, so sorry if this should be a duplicate)

I'd like to load a whitelist from a simple textfile which is placed in the users profile/extension-config-dir/...
Usecase: Central configuration of whitelists for all users via e.g. Windows-GPOs

**Comment by chrisaljoudi** [comment]
Hi @Finkregh!

Browser extension APIs don't allow for reading files off the local file system, which makes this impossible. However, users can still use the `import` function in uBlock to quickly load settings from a file:

![import](http://cl.ly/aZPM/Screen%20Shot%202015-04-07%20at%201.54.32%20PM.png)
