### ISSUE TITLE
disable (power button)  function not working

### ISSUE THREAD

**Issue by atomGit** [uBlock-LLC/uBlock#1205]
the "power" button sometimes has no effect - when uB is disabled for a domain, it is not always actually disabled

this problem has existed in at least several of the later versions tested

in the following SS, 3 errors are displayed in the console for blocked resources (JS), yet uB is disabled for this domain...
http://s6.postimg.org/6jvqho8pt/screenshot_74.png

this problem is reproducible:
white-list (power button off) domain: 12bytes.org
close all tabs
load any website
in the same tab, enter the address 12bytes.org
result: uB is blocking JS resources from loading
if the tab is reloaded, all is fine

uB 0.9.3.1 and earlier
FF 36/37x
win 7

**Comment by 0xBRM** [comment]
The power button disables STATIC filtering, so if you want to override dynamic filtering, just select the "All" column.

**Comment by atomGit** [comment]
ok, but that prompts the question as to why the results are not consistent - why are resources blocked initially, but not on reload?

i would guess that you have a good reason for the making the power button work as it does, but without knowing what it is it would seem to me to be more intuitive to make it so that when it is "off", it is completely off and disabled for the domain - both static and dynamic

**Comment by AlexVallat** [comment]
OK, a couple of things.

1) We haven't released a 0.9.3.1 - so please don't expect us to support someone else's fork.
2) The power button does, in fact, disable dynamic filtering too. At least when I tried it, it did.

**Comment by atomGit** [comment]
@Alex

re #1: sorry, didn't realize 0931 was a fork, however this bug applies to at least several earlier versions for at least the last week or more

re #2: this is what users would expect i am sure (off = disable all, not some), however this means my original post is still valid and it's broken (in my case) - also this info conflicts with what Chris stated

**Comment by chrisaljoudi** [comment]
@atomGit I'm sorry? What did I say that was potentially misleading?

**edit:** ah, different Chris. Never mind.

**Comment by AlexVallat** [comment]
@atomGit OK, confirmed with 0.9.3.0. This is because the inline script is being blocked by `onHeadersReceived` before `onLocationChange` is called, so it's using the power button setting for the previous page, not 12bytes.org.

I'm investigating possible workarounds.

**Comment by atomGit** [comment]
ah, yes, i noticed something similar in one of the recent builds where the domains displayed in the pop-up UI were totally not for the current tab/domain (the actual domain in the focused tab wasn't listed at all)

glad you found the problem :)
