### ISSUE TITLE
unable to download files

### ISSUE THREAD

**Issue by atomGit** [uBlock-LLC/uBlock#1207]
uB 0.9.3.1
FF 37.0.1

right-click any link to download something > save as... and FF displays error:
"The download cannot be saved because an unknown error occurred"
there are no error console messages

disabling uB resolves the issue

**Comment by AlexVallat** [comment]
Sorry, I have not been able to reproduce this. Could you verify if it occurs with 0.9.3.0, the latest official release? If so, then perhaps you can give me a specific example of a page and a link that doesn't work.

**Comment by atomGit** [comment]
sorry, this for uB 0.9.3.1 which, i don't even know where i got that version as it isn't listed here

probably nothing to worry about
