### ISSUE TITLE
uBlock and Buffer

### ISSUE THREAD

**Issue by ngocphamm** [uBlock-LLC/uBlock#1208]
Anyone use Buffer and uBlock seems to block it?

I have `buffer.com` on my Whitelist already, but in whatever page I'm in, if uBlock is active, I cannot use the Buffer button (by the extension) to add an article to Buffer.

I also tried rule `* buffer.com * allow` but it doesn't work either.

Can anyone please help?

Thank you.

**Comment by chrisaljoudi** [comment]
Hi @ngocphamm!

Hmm, I can't reproduce the issue (if I understand you correctly). It seems to work just fine with default settings:

![screenshot](http://cl.ly/aZBB/Screen%20Shot%202015-04-07%20at%201.58.44%20PM.png)

Please provide some details — like uBlock settings different from default (if any), what browser and version you're using, URLs to pages where this occurs, etc.

**Comment by ngocphamm** [comment]
Hi @chrisaljoudi,

Thanks for your response.

I use Safari 8.0.4 with uBlock 0.9.3, and it happens on every page that I have uBlock enabled. Let's try with this one: http://fabien.potencier.org/article/13/introduction-to-the-symfony-service-container

The login form, except the social sign in buttons, is fine. 
![screenshot 2015-04-07 16 03 44](https://cloud.githubusercontent.com/assets/395123/7032325/07a5054a-dd40-11e4-8cce-761273bfaf8c.png)

But then after I log in to Buffer, there's a blank modal.
![screenshot 2015-04-07 16 06 08](https://cloud.githubusercontent.com/assets/395123/7032416/af0ca496-dd40-11e4-872c-179eb0fc5b61.png)

And below is the settings that is different from default.

**3rd-party filters** all that's not on the screenshot are unchecked
![screenshot 2015-04-07 16 08 23](https://cloud.githubusercontent.com/assets/395123/7032424/b8dce97c-dd40-11e4-9b9d-f27f13623ef2.png)

**My filters**
![screenshot 2015-04-07 16 09 29](https://cloud.githubusercontent.com/assets/395123/7032426/bbf1bbec-dd40-11e4-820a-b356d023d8c5.png)

**Whitelist**
![screenshot 2015-04-07 16 09 39](https://cloud.githubusercontent.com/assets/395123/7032428/be4e50c6-dd40-11e4-825f-e39313ab10fd.png)

**Comment by Snapy** [comment]
@ngocphamm  Disable Fanboy Social Blocking List.

**Comment by ngocphamm** [comment]
@Snapy But I need it when browsing Facebook.

**Comment by ngocphamm** [comment]
@Snapy Just tried to disable it and Facebook doesn't seem to be real messy. I think it would be it for now. Thank you!

However, @chrisaljoudi, are the Rules suppose to override those defined in 3rd-party lists?

**Comment by Snapy** [comment]
Why do you need it on Facebook ?

**Comment by ngocphamm** [comment]
I thought it would help block more of the annoyance on Facebook. I tested it before and it did. It's not really so right now, though.

**Comment by Snapy** [comment]
You might want to try the filter lists on [this page](https://facebook.adblockplus.me/).
**Edit :** Yes and there is the same for YouTube.
Glad you found what you were looking for.

**Comment by ngocphamm** [comment]
Wow, thank you @Snapy. Didn't even know it's already a custom filter option at the bottom of the page.

**Comment by chrisaljoudi** [comment]
@ngocphamm fixed! Should work as expected now once you whitelist `buffer.com`.

**Comment by ngocphamm** [comment]
Awesome! Thank you @chrisaljoudi !

**Comment by DLDR** [comment]
I had the same problem but the empty space under the title "Simple Composer" remains transparent, it was not displayed. Finally i found the fix: disabling in the extension settings, in the first tab, the hiding of the reserved space for the elements which were blocked.

**Comment by jscheel** [comment]
@chrisaljoudi I still seem to be having this issue. I've updated my extensions and my block lists. `buffer.com` is in my whitelist, but it's still blocked.

**Comment by michalcs** [comment]
Same issue here: buffer composer modal is height:0 and its content is blank
Having buffer.com and bufferapp.com in whitelist doesn't seem to do anything
Have to disable Fanboy's annoyance list for now—which is annoying cause I'd need it to get rid of all other social BS all over the internet... hmmm

**Comment by virtualirfan** [comment]
@airpoint and @jscheel There is a workaround documented at http://www.thinknix.net/2015/09/26/ublock-origin-buffer-playing-nice/.

@chrisaljoudi Might that help with a clue for a more permanent fix?

**Comment by ghost** [comment]
I'm still having trouble with Buffer extension in Safari... my settings
![captura de pantalla 2016-02-14 a las 14 50 21](https://cloud.githubusercontent.com/assets/16371257/13034033/5565a448-d32a-11e5-9586-66b0098aa1b9.png)

![captura de pantalla 2016-02-14 a las 15 22 55](https://cloud.githubusercontent.com/assets/16371257/13034184/e047a346-d32e-11e5-8c59-5b7e28c48307.png)

Thanks!

**Comment by ghost** [comment]
Sorry for the noise above; I managed to type the wrong issue number.

**Comment by kangarooo** [comment]
Still problem.
How to unblock it? 
How to know what to block? I found out that blocked is 
13:51:00		##.ss-social	--	dom	https://buffer.com/add?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DU2J5whBEN3A&text=SIDO%20-%20Fuffies%20im%20Club%20%5BMTV%20Unplugged%5D%20&version=2.13.26&placement=toolbar
13:51:00		##.social-buttons	--	dom	https://buffer.com/add?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DU2J5whBEN3A&text=SIDO%20-%20Fuffies%20im%20Club%20%5BMTV%20Unplugged%5D%20&version=2.13.26&placement=toolbar

**Comment by kangarooo** [comment]
Its with using Buffer app button in Chrome
https://chrome.google.com/webstore/detail/buffer/noojglkidnpfjbincgijbaiedldjfbhh

**Comment by kangarooo** [comment]
How to add exceptions for this and how and where? @@ doesnt work. !! also not. ! not. Trying for 2 days.

**Comment by kangarooo** [comment]
Still problem.
How to unblock it? 
How to know what to block? I found out that blocked is 
13:51:00 ##.ss-social -- dom https://buffer.com/add?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DU2J5whBEN3A&text=SIDO%20-%20Fuffies%20im%20Club%20%5BMTV%20Unplugged%5D%20&version=2.13.26&placement=toolbar
13:51:00 ##.social-buttons -- dom https://buffer.com/add?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DU2J5whBEN3A&text=SIDO%20-%20Fuffies%20im%20Club%20%5BMTV%20Unplugged%5D%20&version=2.13.26&placement=toolbar

Its with using Buffer app button in Chrome
https://chrome.google.com/webstore/detail/buffer/noojglkidnpfjbincgijbaiedldjfbhh

How to add exceptions for this and how and where? @@ doesnt work. !! also not. ! not.

Found solution in ublock My Rules put this
In uBlock origin put this in my Filters
buffer.com#@#.ss-social
buffer.com#@#.ss-twitter
buffer.com#@##sharer
