### ISSUE TITLE
Tab being closed automatically.

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#121]
I went to slice.com, which pulls Amazon orders. When I add tracking info, then click a link that will go to UPS with that tracking number, uBlock closes the tab instantly.

Disabling the extension outright fixes it.

This is with 0.3.1.2.

**Comment by gorhill** [comment]
Do you know the URL address of the pop up which tries to open? (I don't have an account with slice, I can't reproduce as per above scenario)

**Comment by ghost** [comment]
http://wwwapps.ups.com/WebTracking/track?loc=en_EN&track.x=track&trackNums=XYZ

Replaced XYZ with a valid tracking number. Just don't want to make my
address public.

**Comment by gorhill** [comment]
#10 would really be handy to find out what filter was hit.

**Comment by gorhill** [comment]
Forgot to ask: what version of uBlock you had when the bug occurred?

**Comment by ghost** [comment]
0.3.1.2 thought I mentioned it already.

**Comment by gorhill** [comment]
Ah right sorry, didn't notice.

**Comment by gorhill** [comment]
Ok, looks like for some reasons the `/webtracking/` filter is being hit. Investigating.

**Comment by gorhill** [comment]
Ok, found the problem: `/webtracking/*$~subdocument`. Will fix before tomorrow hopefully when I get the time.

**Comment by fysics** [comment]
I've had similar issues on other sites. I'll post details next time I come across it. Simply fixing the filter might not be the best fix -- other ad blockers don't experience this issue when using the same filters.

**Comment by gorhill** [comment]
I didn't mean to say `/webtracking/*$~subdocument` in itself was the problem, problem is the `~subdocument` option (or any request type with `~`), it causes the `popup` option to be set while it should not. Now I can finally sit and make the fix, hopefully before going to bed.
