### ISSUE TITLE
Chrome: Dynamic Filtering settings not working correctly when url pasted into new tab

### ISSUE THREAD

**Issue by dy-dx** [uBlock-LLC/uBlock#1210]
Chrome 42.0.2311.68 beta (64-bit)
Mac OSX 10.10.2

Hi, dynamic filtering has some issues when opening a page in a new tab (but only when pasting the url).

I recorded a video of the bug: http://monosnap.com/file/tE7HDlHYG3xfprijMPgir6NImdezvo

uBlock seems to be blocking all 3rd-party content on this page, until I refresh and the correct settings are applied.

**Comment by chrisaljoudi** [comment]
Hi @dy-dx!

Thanks for the report. Just fixed this in 42dae93, :)

**Comment by gorhill** [comment]
I did not try to confirm, but I suspect your fix might have brought back #516 to life. If I am not mistaken, this will cause subsequent requests on a page where a download occurred to be made in the context of whatever hostname there was for the download URL.

**Comment by chrisaljoudi** [comment]
@gorhill don't believe so. I was aware of that and careful to make sure a regression doesn't occur.

**Comment by dy-dx** [comment]
Thank you so much for the fix!
