### ISSUE TITLE
ublock automaticly blocks mailing with 'list-manage.com/track'

### ISSUE THREAD

**Issue by annban** [uBlock-LLC/uBlock#1212]
Hello! I'm curating a newsletter for startupers (sent with MailChimp), and one of our users reported an issue with ublock. When he clicks on the links in the email while having ublock on, he gets an info that ublock is blocking it from loading due to a filer list-manage.com/track/ (screen here: http://screencast.com/t/vHZAUpvpPUv). Is there any reason for blocking the links from newsletters like that (in other words, classic: is that a feature or a bug?). (he didn't add this to filters manually).

**Comment by gorhill** [comment]
Ok, by the look of it, too many false positives. I relaxed the heuristic on my side to fully comply with #1128.

**Comment by mariusa** [comment]
This still happens to me: I get newsletters in gmail with links like
http://html5weekly.us1.list-manage.com/track/click?u=0618f6a79d6bb9675f313ceb2&id=ab94368de2&e=affdcc77f1

After adding list-manage.com to whitelist, this still happens:
Click from gmail & Chrome: new tab opens, and then closes after 1 second. No warnings. Disabling ublock fixes it.
Copy & paste link manually in new tab: works

**Comment by chrisaljoudi** [comment]
@mariusa Hi!

Are you using uBlock Origin? uBlock shouldn't exhibit this behavior (and doesn't as far as I can tell).

**Comment by mariusa** [comment]
Thanks Chris! Yes, it was uBlock Origin.
Switched to uBlock and now it works fine, thanks!

It's quite confusing to have both in app store, many comments ask what's the difference and which one to pick.

**Comment by gorhill** [comment]
@chrisaljoudi This has nothing to do with strict blocking, this has to do with EasyList: https://adblockplus.org/forum/viewtopic.php?f=2&t=30156.

It was just a matter of updating EasyList.

Strict blocking **does not** cause web pages to close, as reported by the user ("new tab opens, and then closes").

**Comment by chrisaljoudi** [comment]
@gorhill ah, got it. Sorry.
