### ISSUE TITLE
[RESEARCH] Get rid of tricky ad injected by proxy

### ISSUE THREAD

**Issue by flawrist** [uBlock-LLC/uBlock#1213]
Dear community and Chris,

having well-thought tools to fight intrusive content such as uBlock and uMatrix, still there’re cases when
one feels lost and sad. Begin with installing this popular [proxy extension for Chrome](https://chrome.google.com/webstore/detail/anonymox/icpklikeghomkemdellmmkoifgfbakio) (name is omitted intentionally), then surf and notice ad sticked to the bottom of the window. Let’s inspect what happens: proxy injects grayish `<div>` without class or id with named `<iframe>` within. If we add `###iframe-name` to uBlock “My filters”, then `<iframe>` will vanish, however parent `<div>` will remain. Aggrrhhh! 

Could you be so kind and elaborate on this to make one happy again?

![](http://i.imgur.com/IAiZXFC.png)

**Comment by Betsy25** [comment]
Can you copy/paste the filter that you created ?

**Comment by flawrist** [comment]
@Betsy25
Sure, see below, however it removes `<iframe>` only, parent grayish `<div>` remains intact.

![](http://i.imgur.com/1iqrE91.png)

**Comment by chrisaljoudi** [comment]
Hi @sergeevabc! 

Unfortunately, there's not much uBlock can do about this. The extension you mentioned can directly manipulate the pages you see — and it can be completely undetectable by other extensions. It doesn't even have to add that `anymx-frame` ID.

Silly as this may sound, the solution here is to not use the extension you mentioned. There are other ways to use a proxy, and obviously the extension is being invasive.

**Comment by flawrist** [comment]
@chrisaljoudi, do you believe we could handle the issue when more advanced selectors will be supported (by uBlock or by browser with CSS4) to catch parent elements (e.g. `div>iframe#anymx-frame`)?

**Comment by chrisaljoudi** [comment]
@sergeevabc that would enable you to hide the parent `div`, yes, but only as long as the `anonymox` extension is putting in that exact `iframe` ID (which they don't need to do).

**Comment by flawrist** [comment]
Thank you for your comments. Let's be patient then.
Feel free to re-open the issue in case someone has a current workaround.
