### ISSUE TITLE
uBlock for Android/iOS

### ISSUE THREAD

**Issue by nntoan** [uBlock-LLC/uBlock#1216]
Hello,

Is there any chance to convert this browser extension to a native app run under iOS or Android system?

**Comment by RandomAcronym** [comment]
Realistically? No. the way uBlock works relies on stuff built in to browsers that's not built in to iOS/Android naively. An entire new project would need to be devoted to replacing the browser parts and would only work system-wide on jail-broken or rooted devices.
Till then look into Hosts blocking implementations like Adaway or web-proxy blocking like Privoxy.

**Comment by AlexVallat** [comment]
uBlock is available for Firefox for Android. As far as I know, no other mobile browsers support addons.

**Comment by chrisaljoudi** [comment]
Hi @nntoan!

Well, while it's certainly _possible_ to hack together an app that's a "uBlock browser", that's very ugly, a lot of effort, and probably isn't worth it.

That said, I wouldn't be the least bit surprised that Safari/Chrome on iOS/Android start supporting extensions soon.

When/if that happens, we'll be working to bring uBlock to mobile Safari/Chrome as soon as possible.

**Comment by lewisje** [comment]
@chrisaljoudi went into more detail in this closed issue: https://github.com/chrisaljoudi/uBlock/issues/556

With that said, I also know that FutureMind has created an app for iOS 6+ called Weblock that allows you to set up a PAC (Proxy Auto-Config) URL to block some content on Wi-Fi, and that company also created an app for iOS 7+ called AdBlock that sets up a phony VPN profile to block content on all connections, but it focuses on in-app advertising and tends to crash (neither app is free but both are cheap); I think there are also apps for Android that use phony VPN profiles for the same purpose.

**Comment by ghost** [comment]
AdAway is great and got updated recently.

**Comment by lemmy04** [comment]
I don't see a uBlock for firefox on android... at least not with search. Link please!

**Comment by AlexVallat** [comment]
It's the same xpi, it works on both Desktop and Android versions of Firefox. Download it from the Releases page (or from addons.mozilla.org, though that will always be an older version)

**Comment by berryman13** [comment]
"Realistically no, bla bla new project.." Don't comment if you don't know at all hah

**Comment by RandomAcronym** [comment]
@berryman13 please take your own advice.
