### ISSUE TITLE
Part of the scrollbar in Request log hidden under toobar

### ISSUE THREAD

**Issue by my-password-is-password** [uBlock-LLC/uBlock#1217]
The top of the scroll bar is hidden under the toolbar and if theres enough requests the thumb or whatever its called can be hidden too.

![ublockrequstlogscrollbar](https://cloud.githubusercontent.com/assets/6408935/7058661/f148ee3a-de19-11e4-86ed-e7719bb3ca97.png)

And the toolbar is see through. Not sure if its suppose to be like that.

![ublockrequstlogtoolbar](https://cloud.githubusercontent.com/assets/6408935/7058743/b65ed91e-de1a-11e4-9435-a80c670fdd59.png)

```
uBlock 0.9.3.5
Chrome (stable)
Win XP
```

**Comment by chrisaljoudi** [comment]
The toolbar is indeed intended to be see through. 

However, that scrollbar behavior isn't. Will investigate.

**Comment by chrisaljoudi** [comment]
Fixed in fa9a506. Thanks!
