### ISSUE TITLE
obsolete assets

### ISSUE THREAD

**Issue by mat8913** [uBlock-LLC/uBlock#1218]
Correct me if I'm wrong, but I'm fairly sure the following assets can be removed:

```
publicsuffix.org/list/effective_tld_names.dat
adblock-czechoslovaklist.googlecode.com/svn/filters.txt
adblock-plus-japanese-filter.googlecode.com/hg/abp_jp.txt
adblock-chinalist.googlecode.com/svn/trunk/adblock.txt
```

**Comment by chrisaljoudi** [comment]
Hi @mat8913!

The asset from `publicsuffix.org` isn't obsolete at all — it's just not a filter list, but it's still used in uBlock internally.

The rest of them... probably, yes. The reason they're there is that they've changed URLs/locations, and users with older versions of uBlock would have these lists stop working. 

Now uBlock was improved a while ago to support changing URLs/locations of lists seamlessly, so it seems like we should be fine removing those.

I think it'd be better to wait until next release before we do this to simplify potential problems.
