### ISSUE TITLE
Interface broken with standard font set.

### ISSUE THREAD

**Issue by louipc** [uBlock-LLC/uBlock#1226]
If I disable custom site fonts ublock's interface breaks somewhat. The power button and other icons are not displayed properly. In firefox preferences > content > fonts & colors > advanced > uncheck "Allow pages to choose their own fonts..."

**Comment by ghost** [comment]
Install the new beta on the [release section](https://github.com/chrisaljoudi/uBlock/releases) of this repository.  Should work well.

**Comment by louipc** [comment]
Oh nice works. Thanks.
