### ISSUE TITLE
use power button with temporary lock

### ISSUE THREAD

**Issue by Haikuch** [uBlock-LLC/uBlock#1231]
I would like to use the temporary lock with the power button. Currently it stays disabled until I change it, even when I just have to disable ublock only for this tab/session for testing. I see, that it would be tricky because the temp-lock is just for the advanced users but the power button for also for normal ones.

**Comment by chrisaljoudi** [comment]
@Haikuch Hi!

I'm afraid I don't understand. Would you mind rephrasing, perhaps with an example?

**Comment by Haikuch** [comment]
Jup. When I have to use the big power button to swithc ublock off, it stays disabled for this site until I enable it again. Even after restarting Firefox etc. When changing a dynamic rule its only temporary until I click the temp-lock. I would suggest the same temporary mode for the big disable button (in advanced mode only?)

ah ok example if still needed: I go to example.com, do some tests with the dynamic rules that don't work, then I disable ublock because I just want to use the page, but that does not neccessarily mean that I always want to have ublock disabled there and would like that its just disabled temporarily like the dynamic rules.

**Comment by chrisaljoudi** [comment]
@Haikuch so kind of like a pause button, correct?

**Comment by ghost** [comment]
Like the rules behaviour?
Click on the Power: disable temporarily for this website
Ctrl+Click: disable permanently for this website
