### ISSUE TITLE
Make active and inactive state of ublock image in navbar distinguishable

### ISSUE THREAD

**Issue by Speravir** [uBlock-LLC/uBlock#1233]
Maybe this is Firefox specific, but I do not know this; at least my description is, though:

In the moment both the active and inactive state of the navbar image are invoked with the same attribute. According to DOM Inspector for both states the inactive version is called:

```
#ublock-button {list-style-image: url(chrome://ublock/content/img/browsericons/icon16-off.svg);}
```

Only for the active state this is later overwritten with `list-style-image: url("chrome://ublock/content/img/browsericons/icon16.svg");`.

As far as I can see this is done by the script “vapi-background.js”:
- invocation for both states: [line 1472ff.](https://github.com/chrisaljoudi/uBlock/blob/c70a932d86f181a73bec853c8b1e8724ce14c4ca/platform/firefox/vapi-background.js#L1472)
- overwriting only for active state [line 1674ff.](https://github.com/chrisaljoudi/uBlock/blob/c70a932d86f181a73bec853c8b1e8724ce14c4ca/platform/firefox/vapi-background.js#L1674)

There are several ways, how other authors deal with this. I’ve took a fast look into the code of Greasemonkey which supports different icon sizes, here the relevant excerpt:

```
#greasemonkey-tbb {
  list-style-image: url("chrome://greasemonkey/skin/icon24.png");
}
toolbar[iconsize="small"] #greasemonkey-tbb {
  list-style-image: url("chrome://greasemonkey/skin/icon16.png");
}

#greasemonkey-tbb[disabled="yes"] {
  opacity: 0.8;
}
```

_(In fact there’s a bit more related code.)_

The reason is, of course, that someone could then replace the images, for instance with the older versions containing the µ sign. ;-)

**Comment by chrisaljoudi** [comment]
@Speravir Hi!

> both the active and inactive state

I don't understand. Is that different from the distinguishing whether uBlock is active or not?

**Comment by Speravir** [comment]
Hmm, pardon my poor English …

The image in navigation bar shows, whether uBlock is active or not, but I cannot tell this from the CSS code. This code is generated by the Javascript file. In the moment the earlier generated code for all states (I was incorrect above) is simply overridden by the later generated code for the active state icon _without any distinction_ in this code – it uses the usual behaviour of CSS (the later wins):

First generated code results in the image with grey background (<sub>![icon16-off](https://cloud.githubusercontent.com/assets/899244/7102019/5950ac56-e073-11e4-9232-f5aefa40ad71.png)</sub>), mentally linked with “inactive” _(in this place there is more code generated, but this is not important here)_. Only when uBlock is active later the code is generated for the icon with brown background (<sub>![icon16](https://cloud.githubusercontent.com/assets/899244/7102026/7b59f294-e073-11e4-8e76-f38e82fd9616.png)</sub>), hence connoted with “active”.

_NB:
Accidentally I’ve first uploaded the old icon versions with µ sign in PNG format (the ones I consider to put back into the navbar). For what it’s worth I let them stay here:_
- _“icon16-off.png”:_ <sub>![icon16-off.png](https://cloud.githubusercontent.com/assets/899244/7101921/2e3b3efe-e06f-11e4-8ed0-f2f9d930dd90.png)</sub>
- _“icon16.png”:_ <sub>![icon16.png](https://cloud.githubusercontent.com/assets/899244/7101949/90b100b8-e070-11e4-8e1d-3c0692171f9b.png)</sub>

**Comment by AlexVallat** [comment]
OK, I think I understand. The idea is you would like to have both On and Off state icons defined in css rather than directly assigned, so you can override them using a user style sheet (or add-in like Stylish).

I've put together a pull request to implement this (the off button state has the additional css class `off` so it can be identified as `#ublock-button.off` by css): #1239

If there are no objections, I'll merge it in.

**Comment by Speravir** [comment]
I added the changed file into the extension file, and it shows the wanted behaviour. Great!
