### ISSUE TITLE
Content in video tag not blocked

### ISSUE THREAD

**Issue by louipc** [uBlock-LLC/uBlock#1234]
Enable a deny-all dynamic filtering policy.
Visit http://connect.internet.org/ for an example.
See the video of a globe revolving.

I think this might be related to
https://github.com/chrisaljoudi/uBlock/issues/955
https://github.com/chrisaljoudi/uBlock/issues/1152
https://github.com/chrisaljoudi/uBlock/issues/1184

**Comment by chrisaljoudi** [comment]
@louipc Hi!

I've tried to reproduce, and the issue doesn't seem to occur in Chrome. What browser are you seeing this in?

Thanks!

**Comment by louipc** [comment]
Oh sorry I am using firefox version 37.0.1
and uBlock 0.9.3.5 Beta 1
Hmm I just disabled all other extensions and it seems to work properly so there may be some other issue at work.

**Comment by louipc** [comment]
So... I disabled then reenabled all extensions one by one and it seems to work properly now. That's really confusing. Really sorry for the noise. Closing now.

**Comment by chrisaljoudi** [comment]
@louipc out of curiosity, what extensions do you have?

**Comment by louipc** [comment]
A lot of privacy stuff.
https://github.com/muzuiget/referrer_control
https://github.com/dillbyrne/random-agent-spoofer
https://github.com/EFForg/https-everywhere

For blocking some small specific things:
https://github.com/greasemonkey/greasemonkey
