### ISSUE TITLE
Active and hover state UI issues

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1235]
**1) Page overflows container**
![8px](https://cloud.githubusercontent.com/assets/11744855/7100607/6e77dbe4-e06f-11e4-9d51-e6cc2b2b9c5d.png)
The CSS rule (body) is making the container span greater than 100% of the screen width:
`body {
padding: 8px;
}`

Visually notice how the border on the right hand side runs off the screen:
![one](https://cloud.githubusercontent.com/assets/11744855/7100613/b63aa9a2-e06f-11e4-9e2a-0cd647a5564b.png)

When you use uBlock on a small screen, the problem is gap is more apparent.
![small](https://cloud.githubusercontent.com/assets/11744855/7100618/cdf75f5e-e06f-11e4-9375-921b7c658d00.png)

Also if you middle click your mouse, you can pan the document by 8px left and right:
![panning](https://cloud.githubusercontent.com/assets/11744855/7100627/336ff49a-e070-11e4-8476-fd612a288ae1.png)

**2) When clicking into a field, the design of the field changes to the old "border-style" input.**

![revert](https://cloud.githubusercontent.com/assets/11744855/7100561/d49345ce-e06c-11e4-8fff-c3887cd72a14.png)

Compare the active state (yellow with old borders) vs. inactive state (new borders), the left and bottom borders appear to disappear when clicking into an input field.

**3) Hovering over the question mark makes it disappear:**

![inactive](https://cloud.githubusercontent.com/assets/11744855/7100573/63c0346e-e06d-11e4-9736-7d705f0ecc31.png)
![hover](https://cloud.githubusercontent.com/assets/11744855/7100572/63684c72-e06d-11e4-9c1e-9dad9de4f2df.png)

Notice how hovering over the icon makes it disappear (yet still leaving behind a shadow).

**4) Plus toggle button does not work**
![button](https://cloud.githubusercontent.com/assets/11744855/7100592/ce725a20-e06e-11e4-9083-9eab328f4b3a.png)
![button_2](https://cloud.githubusercontent.com/assets/11744855/7100599/f30aacc0-e06e-11e4-8e49-6000a0ac8c3e.png)

Using the last toggle button (+ button) does not do anything. Notice how I can toggle from "-" to "+" yet nothing on the screen changes.

Visible in uBlock 0.9.3.5 (beta)

**Comment by ghost** [comment]
@chrisaljoudi I added a couple more issues I noticed too.

Thanks :+1:

**Comment by chrisaljoudi** [comment]
Fixed in 323dc5f.

One note, though: as far as the last `+/-` toggle,  that's actually "working" (it would show a list of custom filter lists if you had any in the box below).

I agree that it's very confusing; just wanted to let you know, though. I'll figure out something better for it. :)

**Comment by chrisaljoudi** [comment]
@droidery Just noticed some of the ones you added — sorry. Let me see.

**Comment by chrisaljoudi** [comment]
@droidery alright; 25d0611 should've completed this. :)

**Comment by ghost** [comment]
Thanks @chrisaljoudi  Will look forward to it in the next build :+1:
