### ISSUE TITLE
Update filter lists more often (automatically)

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1237]
Gorhill said that uBlock updates filters lists "around every four days". I'd prefer to shorten the interval and I think that the lists should be updated every day by default.

**Comment by ghost** [comment]
Hard on servers we aren't paying for. Install base is over a million.

**Comment by LocutusX** [comment]
4 days is a good hardcoded default. As above poster mentioned, we don't pay for the list provider's bandwidth. 

ABP's hardcoded default is even greater, I believe.

**Comment by ghost** [comment]
uBlock should follow `! Expires:` header. Now there is 36(?) lists with expiration time other than 4 days. For example `easylistlithuania.txt` have `! Expires: 30 days (update frequency)`, but `abp_jp.txt` is set to expire after 6 hours.

**Comment by chrisaljoudi** [comment]
@gwarser What if some list sets `Expires` to, say, 50 years (by accident)?

I think 4 days is reasonable and won't cause any issues (the update frequency certainly hasn't been an issue).
