### ISSUE TITLE
Remove "FIN: Wiltteri‎" from the list of filters

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1238]
Finnish "Wiltteri" project hasn't been maintained since the June of 2014. The homepage has been sold, everything is outdated.
chrome://ublock/content/assets/thirdparties/raw.githubusercontent.com/wiltteri/wiltteri.txt/master/wiltteri.txt

**Comment by gitarra** [comment]
Even though it isnt maintained anymore I still use it as it works just fine. Just my 2 cents.

Also the projects github page is the current homepage https://github.com/wiltteri/wiltteri
