### ISSUE TITLE
Beam.pro not working while uBlock is enabled

### ISSUE THREAD

**Issue by SilenceEngaged** [uBlock-LLC/uBlock#1241]
When trying to open beam.pro with uBlock enabled, it does not load any live streams. When disabled, it does.

**Comment by SilenceEngaged** [comment]
This is on Firefox 37.0.1

**Comment by chrisaljoudi** [comment]
Hi @astcraft.

Can't reproduce here (Firefox 37.0.1, default uBlock settings).

Do you have any special settings (filters, etc.), perhaps? Does this occur on all channels on `beam.pro`, or a specific URL?

**Comment by SilenceEngaged** [comment]
I simply cannot load up beam.pro I've tried disabling all add-ons but uBlock and still nothing. I've also tried default Firefox settings.

**Comment by gorhill** [comment]
Worked fine here too, even with more stringent settings: default settings + block 3rd-party frames + Dan Pollock's list.

**Comment by SilenceEngaged** [comment]
Hmmm. Let me see if I can load up beam.pro. I'll get some screenshots if it helps/ happens again.

**Comment by SilenceEngaged** [comment]
Here is a screenshot if you need it: http://vgy.me/QCeG7G.png

**Comment by SilenceEngaged** [comment]
I don't want to white-list the website because I really don't like ads. :P

**Comment by chrisaljoudi** [comment]
@astcraft what version of uBlock are you using?

**Comment by gorhill** [comment]
@astcraft Looks to me you are blocking more than uBlock's default settings. I get a count of 2, yours is 4.  Sharing your uBlock settings is key to resolve issues.

**Comment by SilenceEngaged** [comment]
I've used 0.9.3.0 and 0.9.3.5. beta 1.

**Comment by SilenceEngaged** [comment]
Seems to be resolved with a reset to default uBlock settings. :)

**Comment by chrisaljoudi** [comment]
@astcraft okay; glad to hear. Enjoy.
