### ISSUE TITLE
3rd-party filters settings page not working properly on Firefox Ultimate 64 bits

### ISSUE THREAD

**Issue by tailHey** [uBlock-LLC/uBlock#1245]
Hello everyone. Here are the steps to reproduce this issue:

-Install Firefox Ultimate 64 bits (latest version, grab it here: http://sourceforge.net/projects/firefoxultimate/ )
-Install uBlock
-Go to the Settings
-Go to the 3rd-party filters tab
-Only three filtering lists appear (My filters, uBlock filters, uBlock filters - Privacy), settings can't be remembered. This bug make uBlock much less useful
http://i.imgur.com/iGKQvZC.png

Thanks in advance, have a good day

**Comment by AlexVallat** [comment]
Have you tried using standard Firefox, or even one of the more mainstream 64 bit custom builds? It seems very likely that this would just be a bug with "Ultimate 64 bits"...

**Comment by chrisaljoudi** [comment]
Hi @tailHey.

Like @AlexVallat said, Firefox Ultimate isn't really "Firefox". It's a build that's made and maintained by some individual — NOT Mozilla.

This doesn't seem to occur with standard Firefox. With all likelihood, Firefox Ultimate is broken.

**Comment by tailHey** [comment]
So, this addon don't work properly neither on Pale Moon nor Firefox Ultimate... Looks like I wouldn't have to bother myself using any Gecko-based Web browser then :/

Thanks anyway, I guess?

**Comment by ghost** [comment]
@tailHey, you should get in contact with whoever it is that maintains Firefox Ultimate. 

uBlock works perfectly fine in Firefox 37.0.1 (32 bit), Firefox 38b3 (64 bit), and Firefox Ultimate 37.0.1 (32 bit), so it's almost definitely an issue with their 64 bit build…

**Comment by tailHey** [comment]
It doesn't seem that the support is very active there.

I was thinking it could be indeed related to the x64 build, since I haven't tried it on the x86 one.
