### ISSUE TITLE
Support exporting interfaces

### ISSUE THREAD

**Issue by agilob** [uBlock-LLC/uBlock#1247]
https://adblockplus.org/en/IAdblockPlus

µblock could work with AdNauseam
https://github.com/dhowe/AdNauseam/issues/234

**Comment by chrisaljoudi** [comment]
@agilob thanks for the suggestion.

I've added this to a list of future features to consider.

**Comment by dhowe** [comment]
+1 for this, as we (adnauseam-devs) would love to add support for ublock in our next release...

the way this works in adblock-edge can be seen [here](https://bitbucket.org/adstomper/adblockedge/src/a184cbb98c2e7f931e71e7dd2d19cfce03133f0c/lib/Public.jsm?at=default)
