### ISSUE TITLE
"Random" button is broken on xkcd

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1248]
> uBlock has prevented the following page from loading:
> 
> ```
> https://c.xkcd.com/random/comic/`
> ```
> 
> Because of the following filter
> 
> ```
> ||c.xkcd.com^
> ```

The culprit seems to be hpHosts:

```
127.0.0.1   c.xkcd.com
```

Please add an exception for this.

**Comment by harshanvn** [comment]
Please report it hphosts maintainers. So, everyone using this list can benefit.
You can simply disable the strictblocking by clicking either of the two buttons -
- Temporary  (If you are unsure or want to visit for once, better to click this one)
- Permanent

**Comment by ghost** [comment]
I was going to, but exceptions have been added here in the past, so I thought I'd report it here too.

**Comment by ghost** [comment]
Off-topic for this issue, but I found something interesting:

> This service is free to use, however, any and ALL automated use is **strictly forbidden** without express permission from ourselves.

**Comment by harshanvn** [comment]
> exceptions have been added here in the past,

Ah, you are right. Lets see if Chris adds an exception, if this site is really benign.

**Comment by gorhill** [comment]
> exceptions have been added here in the past

For filter lists which uBlock wanted to support as out-of-the-box settings. hpHosts is not one of them.

**Comment by chrisaljoudi** [comment]
@nyuszika7h I don't think I'll be adding and exception for this one (because hpHosts isn't enabled out of the box). I've gotten in touch with the hpHosts guys though, about whether the rule is necessary or helpful.

You should feel free to contact them, too.
