### ISSUE TITLE
[uBlock 0.9.3.5 Beta 2] button not appearing in SeaMonkey

### ISSUE THREAD

**Issue by shakeyourbunny** [uBlock-LLC/uBlock#1254]
uBlock is working on Mozilla SeaMonkey with the Firefox XPI, but due to differences between the XUL of Firefox and SeaMonkey the button is not appearing in the UI (where)?

The functionality of the extension seems to be working 100%, I also can configure the extension via the addons manager.

Could you please officially support the SeaMonkey (http://www.seamonkey.at) browser? It has the same source as Mozilla Firefox, but there need to be done only some touches in the install.rdf (different application ID) and there are other hooks in the UI, should not be much work.

**Comment by Axiomatic-** [comment]
I think they developers are already aware of this, see the issues #514 (for SeaMonkey), and #518 (for Pale Moon). I am guessing SeaMonkey (like Pale Moon) does not support CustomizableUI, which is why there is no support for it.

**Comment by AlexVallat** [comment]
Yes, that's about the size of it. If someone who knows SeaMonkey wants to add support for it, they'd be most welcome. I don't know SeaMonkey, and haven't a clue how to add popup buttons to the toolbar.

**Comment by auge8472** [comment]
As a note: Seamonkey (the successor of the Mozilla Suite) has a status bar at the bottom of the window, like it old versions of Firefox had. NoScript for example starts into the status bar.

**Comment by shakeyourbunny** [comment]
I'm not good at programming, but I found some information for extension support on SeaMonkey and the differences to Firefox.

https://developer.mozilla.org/en-US/Add-ons/SeaMonkey_2

install.rdf

```
 <em:targetApplication>
  <!-- SeaMonkey -->
   <Description>
     <em:id>{92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}</em:id>
     <em:minVersion>2.0</em:minVersion>
     <em:maxVersion>2.*</em:maxVersion>
   </Description>
 </em:targetApplication>
/quote>
```

URL icons for Firefox & SeaMonkey see https://developer.mozilla.org/en-US/Add-ons/SeaMonkey_2#URLbar_Icons

Statusbar for Firefox & SeaMonkey see  https://developer.mozilla.org/en-US/Add-ons/SeaMonkey_2#The_Statusbar

I'd really be glad to have it integrated :-)

**Comment by shakeyourbunny** [comment]
Addendum:
How to detect if the browser is SeaMonkey or Firefox:
https://developer.mozilla.org/en-US/Add-ons/SeaMonkey_2#Multi-browser_compatibility

**Comment by AlexVallat** [comment]
Thank you for the links. Unfortunately they describe adding buttons using overlays, and uBlock is a bootstrapped, not overlay, extension. From what I can tell, SeaMonkey simply doesn't support the sort of popup button that uBlock uses, which means that to support SeaMonkey, some new custom UI would need to be written.

I don't mind making little tweaks or fixes just to avoid breaking when run under SeaMonkey, but I'm not going to write SeaMonkey specific functionality, sorry. For that we need a new developer familiar with, and willing to support, SeaMonkey.

**Comment by chrisaljoudi** [comment]
Thanks, @AlexVallat.
