### ISSUE TITLE
Please add new filter to built-in list

### ISSUE THREAD

**Issue by karolzlot** [uBlock-LLC/uBlock#1256]
Please add this Polish regional anti-cookie-popup-filter to the list, because it is good and popular in Poland. It is not easy for many people to add it manually.

Links to website and filter:

http://lubieciasteczka.net/

abp://subscribe/?location=https://dl.dropbox.com/u/25725152/cookiesblock.txt&title=LubieCiasteczka

https://dl.dropbox.com/u/25725152/cookiesblock.txt

**Comment by karolzlot** [comment]
It is similar to "EU: Prebake - Filter Obtrusive Cookie Notices‎", but works better on Polish websites.

**Comment by chrisaljoudi** [comment]
Will add it to suggested filter lists queue.
