### ISSUE TITLE
Safari 8.0.5 - updating fresh installation of ublock 0.9.3.0 for safari causes safari to quit suddenly 

### ISSUE THREAD

**Issue by jlam25** [uBlock-LLC/uBlock#1257]
## Steps to Reproduce
1. install new ublock 0.9.3.0 extension for safari from either safari extensions page or from https://chrismatic.io/ublock/   on either iMac late 2010 or MacBook Pro late 2013 
2. select 3rd party filters tab
3. select update now button to update filters
## Symptoms

After selecting update now button on a new installation of ublock 0.9.3.0 in safari 8.0.5 the update loads normally, but towards the end of the update safari quits suddenly. This has been consistently repeatable for at least the last couple of days. Disabling all other extensions has no affect on safari suddenly quitting when updating filter lists for the first time after the initial download of ublock. Whether selecting many ublock filter selections or keeping with the default ublock filters, safari quits suddenly regardless. Safari suddenly quitting has been consistent after the initial download and update of the ublock extension filters. After safari crashes, opening it back up usually results in ublock filters being updated and appears to operate normally, though there have been some anomalies where the ublock icon popup menu has not displayed the domains for a page. Just displayed the 3rd party scripts/inline and images options. 

Aso noticed in the second day safari extension page would not bring up the ublock extension when searching for it within that pages search bar, even though other extensions known to be on the page were readily displayed when searching for them. Searching for ublock on the extension page would at times not display any indication that action was chosen, even though other extensions would readily display. On one other occasion the safari extension page would indicate this extension not available or something to that extent? I apologize for not having screenshots of my experiences on the safari extension page. I also went to the safari extension page from another link (it may have been on chrisaljoudi's ublock page...?) which did not work. Again I apologize for no screenshots for this, but I mention it in case there are others having the same issue, or it needs to be know there is potentially a problem. 
## Preferences Different From Defaults

![ublock_title bar icon menu](https://cloud.githubusercontent.com/assets/11929091/7151109/bc067ee2-e2ea-11e4-9faa-d018cb5321e4.png)

![ublock_filter menu selections](https://cloud.githubusercontent.com/assets/11929091/7151096/9a467fd2-e2ea-11e4-9da5-48137da5ea1e.png)

![ublock_updating filter lists](https://cloud.githubusercontent.com/assets/11929091/7151178/cabd7b10-e2eb-11e4-92ba-d35ec6dc690a.png)

![ublock_updating filter lists causes safari quits suddenly](https://cloud.githubusercontent.com/assets/11929091/7151181/d804e9f2-e2eb-11e4-8c50-5507b34b0b3f.png)
## Info

```
uBlock version:
    0.9.3.0
Browser and version:
    Safari 8.0.5
OS and version:
    OS X 10.10.3
```
## Other Extensions

*Ka-block!, DisableGoogleRedirect, Disconnect

**Comment by 5t3f4n** [comment]
I used to have this issue and I could reproduce it endlessly by purging caches and updating again.
As of 0.9.3.5 I can no longer reproduce the crash. Has this been fixed?

**Comment by jlam25** [comment]
Thanks for getting back to me. I didn't do a full uninstall/reinstall, just opted to try purging the cache then updating again. Like your experience, that had consistently produced safari quitting too, but I did not have that happen with the new version 0.9.3.5. Seems to work solidly. Thanks. 

My main concern, as a newbie, with safari crashing was security. So if you don't consider that a concern or if there is a reasonable explanation I won't worry about it. I wasn't sure if the Safari crashing was related somehow to the quirky behavior of the Safari Extension page in regards to your extension either not loading after clicking the link to it or not responding to my search for it on the extensions page search box? Other extension searches loaded their respective pages just fine, so I didn't know if it had been taken down from Safari, like the Chrome version was? Maybe a newer version or update was in the process of being implemented on the safari extension page when I had those issues...? Don't know if that is a possible explanation? Anyway didn't know if all those issues were related since they were happening around the same time, so I was simply hoping for an explanation for this behavior before continuing to use it. 

Your extension works great, and I am very happy to have stumbled unto it. I know now that not every extension on the Safari extension page has users best interest in mind, so it is nice to come across a project like yours that is open and made by fellow users who are trying to make and maintain a great product.

**Comment by 5t3f4n** [comment]
I am not the developer of uBlock nor am I in any way affiliated with the project or either of its forks, I apologize if I gave that impression. I was merely trying to offer some input.

I don't know what's currently going on with the Safari Extension Gallery version, but it seems kind of odd.
This link doesn't work at all:
https://extensions.apple.com/details/?id=net.chrisaljoudi.uBlock-96G4BAKDQ9
This one still has gorhill in the ID and µ in the name:
https://extensions.apple.com/details/?id=net.gorhill.uBlock-96G4BAKDQ9
But the author does say Chris Aljoudi. I don't really know what to make of this.

I would personally suggest installing from https://chrismatic.io/ublock/ instead.
It's guaranteed to be "official" and up-to-date, and if nothing else it's less confusing.

**Comment by chrisaljoudi** [comment]
@jlam25 Hi!

There was a tiny issue with uBlock's Safari Extension Gallery page (the link to it from this repository was incorrect).

This has been fixed, and all should be good. uBlock wasn't ever taken down from the Extension Gallery to the best of our knowledge.

**Comment by jlam25** [comment]
Awesome Chris!

Thanks so much for getting back to me, and for your work on a great product. 

Joel Lammi
jlammi02@gmail.com
