### ISSUE TITLE
[uBlock 0.9.3.5 Beta 2] Per-site switches vanished 

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1259]
Google Chrome 41 + 42

Is this intentional?

**Comment by ghost** [comment]
[Also vanished in Firefox](https://github.com/gorhill/uBlock/issues/51#issuecomment-93319766).

**Comment by ghost** [comment]
Chris [mentioned](https://github.com/chrisaljoudi/uBlock/issues/1166#issuecomment-91131026) he took them out for now to work on the UI. Feels they over-complicate the toolbar pop-up as an advanced feature.

**Comment by ghost** [comment]
Aha - I'm a bit surprised that this important change wasn't communicated more prominently. Unless I overlooked something ...

**Comment by ghost** [comment]
Agreed. As the current version is in beta, don't know if Chris plans to add it back in before full release or later.

**Comment by ghost** [comment]
I don't know what you're talking about. They're still there for me.

**Comment by ghost** [comment]
@nyuszika7h 

What release are you using?

**Comment by chrisaljoudi** [comment]
@tlu1024 

> Is this intentional?

Yes.

**Comment by ghost** [comment]
I'm using v0.9.3.5 Beta 2.

**Comment by rll3** [comment]
As a solution to this, I recommend switching to https://github.com/gorhill/uBlock

**Comment by Betsy25** [comment]
> As a solution to this, I recommend switching to https://github.com/gorhill/uBlock
+1, this repo is dead.

**Comment by ghost** [comment]
Oh, I see what you're talking about now. I was thinking of something else.

**Comment by ghost** [comment]
@Betsy25 I wouldn't call it "dead" just because a new version isn't released so often.
