### ISSUE TITLE
Sync with [google|opera] account

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#126]
From Chrome store feedback:

> Is possible to sync with google account? Because I formatted my computer and I forgot export my list.

**Comment by gorhill** [comment]
Opera also supports "Opera Sync", through the same API.

**Comment by iandol** [comment]
Just a mini note to say thank you for being so proactive and supportive to new features for such an excellent tool!

**Comment by fysics** [comment]
I second iandol's comment.

**Comment by ghost** [comment]
Thirded.

**Comment by septs** [comment]
When you want to support the installation of Chrome in other environments without reconfiguring µBlock

API: https://developer.chrome.com/extensions/storage

**Comment by gorhill** [comment]
Of course I know about this API. But it's something I have to design very carefully and think through thoroughly. Nothing worst for a user than an older settings overwriting a newer one on all installations. Since uBlock can save some settings independently of some others, this means to carefully design time-stamped separate blocks of settings. In short, it's not a trivial issue, I don't want to rush it. Meanwhile, workaround is the backup/restore in the _About_ tab.

**Comment by gorhill** [comment]
First implementation will be very safe: the user will have to explicitly import data sitting on sync server, by clicking on the related button in the _Settings_ tab. Information about whether the remote version is more recent will be provided.

**Comment by davidcie** [comment]
@gorhill that sounds promising and 95% of the way to ultimate uBlock bliss! 

Thank you for looking into this. While for many it may seem an odd request I personally move from computer to computer quite often and help friends (re)install stuff on their computers, so this feature will definitely help ensure a smoother experience.

**Comment by denilsonsa** [comment]
Just an idea… Could you just store the options (i.e. which checkboxes are checked, which hosts are white-listed) directly into `storage.sync`?

All the synchronization problems (such as deciding which version is newer) should be handled by the browser itself, and that's why such API is provided.

However, larger stuff (such as the lists contents, or if the white-list or personal list grows bigger), doesn't fit in there (currently a limit of 8KB per item, 100KB total), requiring some workarounds.

**Comment by septs** [comment]
@denilsonsa use gzip compression may be able to get more space.
