### ISSUE TITLE
Add the possibility to give a names to new subscriptions (when manually added).

### ISSUE THREAD

**Issue by thejustsoul** [uBlock-LLC/uBlock#1262]
Is it possible to add the possibility to give names to the subscriptions. Now if you add a new subscription it appears just as a URL, and it would be better if it was the name (or taken automatically from the subscription or manually).

**Comment by lewisje** [comment]
I know that if the subscription file lists its own name, uBlock uses that (as does ABP, even if you had set a custom name); for example, try adding the "Block the EU Cookie Shit List" subscription.

**Comment by thejustsoul** [comment]
@lewisje 
Yes, subscriptions that have "title", title appears. But if you click (or manually) on the link which adds a subscription (`abp:subscribe?location=....&title=Title List`), the name (without "title" in list) is not assigned.

**Comment by Speravir** [comment]
Sorry, but this is actually not necessary at all:

All lines starting with  a “!” are ignored, so they can be used for comments. In default configuration the very first line for own filter lists is such a comment: It reads `! Examples:`. So, in other words - nothing hinders you from writing:

```
! Title of own filter list / purpose / whatever:
http://example.net/filterlist-of-your.choice.txt
```

**Comment by thejustsoul** [comment]
@Speravir 
Moreover, there is a box where you add your custom filters and a comment character? I want to display an additional field for the name when you add a new subscription (even if does not contain or contains "title"). To show a URL, and a meaningful name. Or maybe add the rename subscriptions.

**Comment by lewisje** [comment]
What @thejustsoul wants is to have the name show up in the list of custom subscription checkboxes, not in the parsable textfield to put the custom subscription URLs in, and as I said, some subscriptions already specify their own titles, and uBlock does parse them; take for example "Block the EU Cookie Shit List": https://raw.github.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt

The third line is a comment that ABP and uBlock recognize as specifying the title:

`! Title: Block-EU-Cookie-Shit-List`

It shows up in the list of custom subscription checkboxes as "Block-EU-Cookie-Shit-List" and ideally, there would be a way to specify what the title should be if the subscription doesn't already have one, as you can do in ABP.

**Comment by Speravir** [comment]
Ah, ok. But I still think, this is not that important … (otoh I'm not one of the developers.)
