### ISSUE TITLE
Settings import enables 3rd-party filters not present in backup

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#1264]
First reported in https://github.com/gorhill/uBlock/issues/63

Fix:

```
git cherry-pick 57e0041629ba8f64a3564a2efef5f5c8870e1df4
```

In that branch: https://github.com/chrisaljoudi/uBlock/compare/master...gorhill:chrisaljoudi.

**Comment by chrisaljoudi** [comment]
Done in 2ecc81e35bf7ca560ae76303e467d8ed05ee450c.

Thanks!
