### ISSUE TITLE
title-bar text change: a seemingly minor, but possibly important feature request

### ISSUE THREAD

**Issue by atomGit** [uBlock-LLC/uBlock#1265]
reading Gorhill's comments on the feedback left on the Chrome store, it is readily apparent that many of the comments have a similar theme: uBlock blocks too much / ublock breaks sites / uBlock is too aggressive / etc.

what i think may be happening here is that many people may not be aware that clicking the title-bar on the pop-up leads to the settings, and so i might suggest changing the title-bar text on mouse-over to "Configuration" or "Settings" or whatever, OR adding that text to the title-bar and not worrying about mouse-over, OR changing the default filter-set prefs so uB acts like ABP out of the box, but still changing the title-bar text also

**Comment by LocutusX** [comment]
I like the notion of on-mouse-over changing the "uBlock 0.9.3.5" text to "click for Dashboard" or something. Perhaps with a 1 second delay.

**Comment by chrisaljoudi** [comment]
:+1:
