### ISSUE TITLE
feature request: click hosts to load domains

### ISSUE THREAD

**Issue by atomGit** [uBlock-LLC/uBlock#1266]
FF on Windows
sometimes we don't know anything about a 3rd party domain which is supplying content to the one we are visiting - would be nice if the domains in the pop-up list were clickable so we can load them in a new tab

**Comment by lewisje** [comment]
That might be a bad idea if that domain came from the "Malware Domain List" or something similar (then again, strict blocking mitigates the danger, but you'll just see a message that the site was blocked)..

**Comment by chrisaljoudi** [comment]
I don't think this is going to be helpful to the majority of users. The risk of them accidentally clicking on one of them and getting sent to a place they don't want to be seems higher in comparison.
