### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by MurkBRA** [uBlock-LLC/uBlock#1273]
In my browser I have personal color text and background. Need make a color scheme for all this item or define a base color to text and background.

Im on 0.9.3.5 Beta 2

![9b47e3d36f](https://cloud.githubusercontent.com/assets/12011370/7217023/bd609742-e5eb-11e4-91a8-b0f0ce8df38b.png)
![23cf1cbe02](https://cloud.githubusercontent.com/assets/12011370/7217029/bd914d38-e5eb-11e4-96da-8ddf99184c16.png)
![303d045589](https://cloud.githubusercontent.com/assets/12011370/7217024/bd7b94b6-e5eb-11e4-9d64-a312af866122.png)
![435e09ad61](https://cloud.githubusercontent.com/assets/12011370/7217026/bd834256-e5eb-11e4-89c9-45a3a5e494df.png)
![c936f65826](https://cloud.githubusercontent.com/assets/12011370/7217028/bd8b6e04-e5eb-11e4-866a-3a9d1414aa74.png)
![cb6461edae](https://cloud.githubusercontent.com/assets/12011370/7217027/bd89079a-e5eb-11e4-87ef-a22704fe6bef.png)
![ec19ed4270](https://cloud.githubusercontent.com/assets/12011370/7217025/bd8085ac-e5eb-11e4-8705-0573f75d6de1.png)

**Comment by lewisje** [comment]
I think that you're talking about using the same color scheme for visited and unvisited links in the extension that you've set up in the browser (I'm guessing Firefox because I don't think you can set that in Chrome).

**Comment by MurkBRA** [comment]
If you pay attention I set text color to white and background to black and default is text black and background white. Link visited green and unvisited royalblue. In the beta version (0.9.3.5 Beta 2) you set the color text of main menu/painel (when you click on icon) and now Im asking to do same with this other menu/painel too. And yes, Im on firefox.

**Comment by MurkBRA** [comment]
Here you can see 
Latest release (have no text color config then my browser set white):
![3d8156d31c](https://cloud.githubusercontent.com/assets/12011370/7217544/a3ddd896-e606-11e4-97f3-be58bc082ae5.png) ![2cb3d556fb](https://cloud.githubusercontent.com/assets/12011370/7217548/32701ace-e607-11e4-8f27-d19f316cc698.png)
Pre-release (have a text color config then my browser dont set white):
![bde5fe885f](https://cloud.githubusercontent.com/assets/12011370/7217543/a3b7cd5e-e606-11e4-8bff-56d8d1dab8a8.png)
