### ISSUE TITLE
uBlock website has ungraceful degredation with NoScript

### ISSUE THREAD

**Issue by wolftune** [uBlock-LLC/uBlock#1275]
The unnecessary eye-candy made by JavaScript to fade in the main central content at https://chrismatic.io/ublock/ has too deep a scope. Instead of progressive enhancement, the actual images and text are dependent on the JavaScript. Thus, the content is completely missing when viewing without JavaScript. This should never happen. Simple text and images should never require JavaScript in order to be visible.

**Comment by chrisaljoudi** [comment]
@wolftune Hi! Thanks for pointing this out — you're right.

Should be fixed now.

**Comment by wolftune** [comment]
Indeed, thanks. Incindentally, now that I can see it regularly, I will say that I personally don't like the effect at all. But I don't care enough to discuss that further. I just am happy the site doesn't break for anyone now. Cheers
