### ISSUE TITLE
Tooltips are enabled even if I am an advanced user

### ISSUE THREAD

**Issue by SW1FT** [uBlock-LLC/uBlock#1277]
I'm using Firefox Developer Edition 39.0a2.
See https://github.com/chrisaljoudi/uBlock/wiki/Advanced-user-features#no-tool-tips

Issue comes since 6e317ff as "body:not(.advancedUser) [data-tip]:after {"
was replaced to "body [data-tip]:after {". I've created a pull request https://github.com/chrisaljoudi/uBlock/pull/1279 to fix this.

**Comment by ialexsilva** [comment]
firefox only? 
pt: somente no firefox?

**Comment by SW1FT** [comment]
@ialexsilva No, the Chromium version also has the same problem, just tested with Opera Beta 29.0.

**Comment by SW1FT** [comment]
Issue comes since https://github.com/chrisaljoudi/uBlock/commit/6e317fff591d8e79eab21dc31b0e68a14c16a14c as "body:not(.advancedUser) [data-tip]:after {"
was replaced to "body [data-tip]:after {".

**Comment by dashed** [comment]
Tooltip doesn't show in Chrome.

---

Btw, why is enabling/disabling tooltips even tied to `I am an advanced user` option? As an advanced user, I actually like the tooltips.

Can we compromise to enable/disable tooltips as a separate config option?

**Comment by SW1FT** [comment]
@Dashed Tooltips are nice and all but people that already know what the buttons do don't need that feedback overlaying the popup UI. However, I do agree that maybe we could have a separate option for it.

**Comment by dashed** [comment]
@SW1FT If there is a separate option, to retain default behaviour, maybe it can be automatically be disabled whenever `I am an advanced user` is enabled.

**Comment by chrisaljoudi** [comment]
@SW1FT This is intentional. I'm considering adding a separate setting, but I guess that all depends on how much of a problem it is to have tooltips.

(The tooltips make a large difference in usability).

**Comment by ialexsilva** [comment]
@chrisaljoudi  :+1:

**Comment by dashed** [comment]
Just realized I have an older version installed via the Chrome store: v0.9.3.0.

@chrisaljoudi Is 0.9.3.5 going to be published to the store soon?

**Comment by chrisaljoudi** [comment]
@Dashed Yeah, the Chrome Web Store says it's "Pending Review" — hopefully it'll make it through soon.

**Comment by ialexsilva** [comment]
3-5 bussines days!

**Comment by Gitoffthelawn** [comment]
I like the idea of having the tooltips and advanced being separate options.  Advanced users, especially new ones, may want to view tooltips.

**Comment by lewisje** [comment]
"Advanced users, especially new ones"

😒 :unamused:

**Comment by Gitoffthelawn** [comment]
An individual can be an advanced user, but be new to ublock.  In other words, someone could have the technical savvy and know-how to use ublock to the fullest (and have read all the ublock documentation and wiki), but still not have much experience using ublock.  If this software is to grow in popularity, that is a strong (and vocal) demographic to attract.

**Comment by lewisje** [comment]
http://rationalwiki.org/wiki/Dunning-Kruger_effect

**Comment by Gitoffthelawn** [comment]
lewisje, no, you just don't get it.
