### ISSUE TITLE
Option to see which hiding rules are in effect. 

### ISSUE THREAD

**Issue by Betsy25** [uBlock-LLC/uBlock#1283]
uBlock 0.9.3.5
Firefox v40 nightly
Win7
Rules, install defaults

It's extremely hard to try to pinpoint which rules is stopping us from doing what we want on a page.
(In comparison, in ABP you could open a popup which shows us the hiding rules in effect, including the list responsible for it)

For example on this page : http://alternativeto.net/software/jkdefrag/
Clicking the little wrench icon, and chosing "Report a problem" should open a little overlay in the lower screen, however this is blocked, it is impossible to know using the Network request logger.
Please, could you think about some ABP-like popup users could open that clearly shows them all (hiding-)filters in effect, and preferably which list the rule is fired from ?

**Comment by Speravir** [comment]
Looks similar to my suggestion: [Make it possible to trace down the origin of a filter](https://github.com/chrisaljoudi/uBlock/issues/1232) (issue #1232).
