### ISSUE TITLE
Allow groups for custom rules - REOPEN?

### ISSUE THREAD

**Issue by Gitoffthelawn** [uBlock-LLC/uBlock#1284]
One of the nice features of competing software is the ability to group custom rules.  This is notably absent from uBlock.  Can this functionality be added?

**Comment by ghost** [comment]
Please follow the submission guidelines before submitting an issue, this is not at all going to help the developer in creating this feature!

**Comment by Gitoffthelawn** [comment]
There are no submission guidelines in the table of contents to the ublock wiki.  According to the github documentation, "you can use Issues to organize tasks you'd like to accomplish, such as adding new features or auditing old ones."

**Comment by lewisje** [comment]
The closest thing is here, but it's not linked from the readme or the wiki (although it is in the top-level list of files, on the same page where you would normally see the readme): https://github.com/chrisaljoudi/uBlock/blob/master/CONTRIBUTING.md

Also, both this version and the `CONTRUBUTING.md` file from gorhill's repo seem to imply that feature requests aren't supposed to be posted as issues (gorhill's is more explicit about this).

**Comment by chrisaljoudi** [comment]
#1262

**Comment by Gitoffthelawn** [comment]
Chris, I noticed you referenced #1262.  I think that's different.  From what I can tell, that is for subscription lists.

What I'm suggesting is for manually added rules.  For example, in ABE and ABP, when the user manually adds rules, he/she can add filter groups to organize those rules.  One of the great bonuses of this ability is that it becomes extremely easy for the user to toggle groups of manually added rules.

If you need more details, just ask, and I'll be happy to provide them.
