### ISSUE TITLE
[ALL] uBlock Website (https://chrismatic.io/ublock/) 404 Not Found.

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1285]
## Steps to Reproduce
1. Go to https://chrismatic.io/ublock/ on any browser, with or without uBlock.
2. 404, website is not found.
## Symptoms

The main website for this rendition of uBlock is not found, however it was online prior to the release that came out ~18 hours ago.

**Comment by chrisaljoudi** [comment]
@berryman13 Had some downtime, but should be back up now.
