### ISSUE TITLE
uBlock misblocked an image in image box - could be related with urchinTracker (?)

### ISSUE THREAD

**Issue by s101d1** [uBlock-LLC/uBlock#1286]
In [this website](http://news.detik.com/read/2015/04/20/141606/2892389/10/penampakan-bersihnya-toilet-di-markas-kopassus-yang-dipuji-ahok?9911012), there is an image box at below. 

![http://i58.tinypic.com/sybhmp.jpg](http://i58.tinypic.com/sybhmp.jpg)

If I clicked the "Next" or just click the 2nd or 3rd image (as shown in screenshot above), it won't display the image:

![http://i58.tinypic.com/2zz19a1.jpg](http://i58.tinypic.com/2zz19a1.jpg)

In firefox's console, when the 2nd image is clicked, there is error message:

```
ReferenceError: urchinTracker is not defined
```

If I disabled the uBlock, the 2nd and 3rd image can show when clicked.

FYI I'm using firefox browser in windows.

**Comment by lewisje** [comment]
Some sites are coded to rely on the existence of Google Analytics (urchinTracker is part of an old version of Google Analytics), and cases like this are why EasyList whitelists it on some sites.

**Comment by s101d1** [comment]
I see. So is there solution for this? I can't found whitelist feature in uBlock (firefox add-on).

**Comment by LocutusX** [comment]
It's caused by EasyPrivacy.

Disable the EasyPrivacy list, and the site works fine.

Not a uBlock issue.

**Comment by lewisje** [comment]
A better idea would be to keep EasyPrivacy on and just whitelist Google Analytics on this site, with a whitelist rule like this: `@@||google-analytics.com^$script,domain=news.detik.com`

**Comment by s101d1** [comment]
@lewisje how do you put that whitelist? I have tried it, the whitelist field setting doesn't accept string that start with `@@`

**Comment by lewisje** [comment]
It's not obvious, but it's under "My filters"

"Whitelists" is only for entire pages that you want uBlock disabled on (and I think it only takes domain names); it's a substitute for `@@||domain.tld^$document` because gorhill did not want third-party lists to be able to disable uBlock outright.

**Comment by gorhill** [comment]
> I think it only takes domain names

No, see https://github.com/chrisaljoudi/uBlock/wiki/How-to-whitelist-a-web-site.

**Comment by s101d1** [comment]
@lewisje I have put `@@||google-analytics.com^$script,domain=detik.com` on My filters, it doesn't work.

**Comment by gorhill** [comment]
@sdiwu try `@@||news.detik.com/urchin.js$script,domain=detik.com` instead. You do not need to allow Google Analytics.

You should report the false positive to [EasyPrivacy maintainers](https://forums.lanik.us/viewforum.php?f=64), it's where the issue is, it is not in uBlock.

**Comment by s101d1** [comment]
@gorhill Thanks, it works.

**Comment by lewisje** [comment]
Sorry, I had just assumed that it was being loaded from the main Google Analytics domain, and I forgot that some sites host their own copies of urchin.js and later GA scripts.

**Comment by s101d1** [comment]
I had reported the problem to easy privacy team, the issue should have been resolved with latest filter update.
