### ISSUE TITLE
uBlock website contains tracking pixels

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1288]
Why does the site for a program which claims to be against 'sneaky tracking' contain a tracking pixel<sup>[1]</sup> from service Typekit?

By the way, it's also unusable when blocking third-party resources…

---

<sup>[1] Typekit script loads tracking pixel `https://p.typekit.net/p.gif`</sup>

**Comment by ghost** [comment]
You can block that with a static filter. I presume @chrisaljoudi just wanted to use a nice font not available elsewhere.

**Comment by ghost** [comment]
> You can block that with a static filter.

That's not the concern - it's blocked by default uBlock filter lists.

It just seems _extremely_ hypocritical to use such tracking pixels on a website for a project that claims to be against, and blocks, online tracking.

**Comment by chrisaljoudi** [comment]
@One23 Fixed.

Note: I think it's pretty misleading to say that the uBlock website used tracking pixels. Typekit did — the uBlock website neither triggered nor monitored the request or any tracking associated therewith.

**Comment by ghost** [comment]
Thank you for fixing!  Sorry about the wording, I suppose it was misleading in a way…

**Comment by chrisaljoudi** [comment]
@One23 Not a problem — was just making sure there was no misunderstanding going on.

Thanks for reporting this (I had noticed a while ago but forgot to get back to it).
