### ISSUE TITLE
Using document fonts only breaks the uBlock UI

### ISSUE THREAD

**Issue by dillbyrne** [uBlock-LLC/uBlock#1291]
![ub](https://cloud.githubusercontent.com/assets/2903711/7236988/5545a08e-e790-11e4-9124-ac4876a971f3.png)

steps to reproduce

in `about:config` set `browser.display.use_document_fonts`  to `0` 

click the uBlock panel icon

**Comment by Snapy** [comment]
Update to the latest version before reporting bugs.

**Comment by chrisaljoudi** [comment]
This has already been fixed in [0.9.3.5](https://github.com/chrisaljoudi/uBlock/releases/tag/0.9.3.5).

Mozilla has to approve the update before it's published to AMO. Meanwhile, you can install 0.9.3.5 manually using the `xpi`.

**Comment by dillbyrne** [comment]
Awesome, thanks for the quick response and sorry to waste your time. Keep up the good work! :+1:

**Comment by chrisaljoudi** [comment]
@dillbyrne not a problem!
