### ISSUE TITLE
unlock not working with Firefox nightly 40 for android

### ISSUE THREAD

**Issue by ale82to** [uBlock-LLC/uBlock#1292]
unlock not working at all with latest Firefox mobile nightly.
issue appeared about 2 days ago version 40
anyway unlock has never worked well for me i constantly have to activate and reactivate in add on page to make it work, now even this trick wont work

**Comment by ericfowler303** [comment]
![screenshot_2015-04-20-22-48-37](https://cloud.githubusercontent.com/assets/8892211/7245810/9a87a2c2-e7af-11e4-8d9c-3235288e5dc8.png)

This is what the addon screen looks like in the latest firefox nightly on android. It has also stopped functioning in blocking anything or showing up within the options menu within firefox. Things seemed to be fine a few versions ago.

EDIT: This also occurs in 0.9.3.0 which seemed to be working fine before. I guess this has to do with some changes in the nightly code recently.

**Comment by AlexVallat** [comment]
Confirmed. It seems that Fennec Nightly is not properly creating `nsIAppShellService.hiddenDOMWindow` any more. Until they fix that, uBlock cannot work, so I'd recommend dropping back to Aurora (or a previous build of Nightly).

**Comment by mattcoz** [comment]
Is this still the problem?
