### ISSUE TITLE
uBlock seems to prevent GMail pinned tabs from loading on startup [Firefox]

### ISSUE THREAD

**Issue by LocutusX** [uBlock-LLC/uBlock#1298]
Strange issue, and I can't figure out why uBlock seems to be causing this.

In Firefox, navigate to gmail.com, log in, and pin that tab.
The next time you start Firefox, the pinned tab won't load properly. It'll either be stuck at the "Loading username@gmail.com" progressbar or there'll simply be a blank page.

Adding "mail.google.com" to uBlock whitelist does not change this behaviour, even though the uBlock icon reflects the whitelist addition.

**Disabling or uninstalling uBlock prevents this issue from occurring.**

Firefox 37.0.2, uBlock 0.9.3.5-release with only one 3rd party list enabled (EasyList).

**Comment by desbma** [comment]
Can not reproduce here, with Firefox 37.0.1 and uBlock 0.9.3.5.

**Comment by LocutusX** [comment]
Closing issue, because I can no longer replicate it on one of my PCs (although I can still replicate it on the other one).
