### ISSUE TITLE
[Question/not a bug] Including changes of uBlock origin?

### ISSUE THREAD

**Issue by Speravir** [uBlock-LLC/uBlock#1299]
Despite gorhill said, he’d considered ublock feature complete, meanwhile he published several versions of, what is now uBlock origin, with enhancements, which in my eyes would also be interesting for uBlock, or seem to be necessary changes/fixes. So my question:

Are you intending to add changes valid for uBlock? What I think of are changes like filter list cleanups or the possibility for per-site-switching of filters, just to name some examples, of course not changes like the different icon.

_<sup>Actually I know you added something from his fork, see [gorhill’s complain a week ago](https://github.com/gorhill/uBlock/issues/50#issuecomment-92835377):</sup>_

>  Just on a somewhat related side note: notice how [code changes from here](https://github.com/gorhill/uBlock/commit/64411613294e44cd47cd2c1c7438e7f632d2e7f2) were [imported in the other repo yesterday](https://github.com/chrisaljoudi/uBlock/commit/fa3666f85d7dddfc274f6f27d20c6787d8bc43b8) without properly respecting git history.

_<sup>(And [some comments later](https://github.com/gorhill/uBlock/issues/50#issuecomment-92907020) he added a bit explanation.)</sup>_

**Comment by chrisaljoudi** [comment]
I'm keeping an eye on it and will merge any changes that are appropriate. I won't  be blindly mirroring gorhill's work, though.

**Comment by Speravir** [comment]
THX for reaction.

> I won't be blindly mirroring gorhill's work, though.

I did not expect it differently. :-)
