### ISSUE TITLE
Google ads on Google.com

### ISSUE THREAD

**Issue by JBey4you** [uBlock-LLC/uBlock#13]
Sometimes (but not very often), some Google ads appear on Google.com when you do a research. Here an example. I don't think the lists are the problem since the ads don't appear with Adblock Plus.

If needed, here's the link for the search: https://www.google.fr/#q=appareil+photo+stabilisateur+optique
![capture decran 2014-06-25 a 05 21 53](https://cloud.githubusercontent.com/assets/7979756/3381207/4b4b2c84-fc18-11e3-9ee7-4e069732c4b5.jpg)

**Comment by gorhill** [comment]
Did you select _EasyList List FR_? Also, I found out that there seems to be a missing element hiding selector in that list: `google.fr###rhs`

Edit: Hmm never mind, I need to investigate more, with ABP I don't see the ads.

**Comment by JBey4you** [comment]
Yep, I did. But like I said, it's weird that it works with Adblock Plus, but not with µBlock. Not sure why.

**Comment by gorhill** [comment]
OK, the filter which is supposed to apply is in EasyList:

`###rhs_block > #mbEnd`

Now I will investigate why it's not applied.

**Comment by gorhill** [comment]
Found the problem. Need to querySelectorAll() the added node(s). Somehow I completely overlooked this.
