### ISSUE TITLE
Consider adding a list of resources blocked

### ISSUE THREAD

**Issue by newzealandpaul** [uBlock-LLC/uBlock#130]
It would be useful to have an option that, when enabled, made the popup (the popup that shows when you click on the ublock icon) list the resources blocked on the current page/tab. 

This would make it easier to figure out what potentially nefarious things are being served up, or linked to, by any particular page. It would also help to debug why a page is not displaying correcting.

I apologize if this issue is a dupe. I did read through all the open issues and did not find a feature request that was similar.

**Comment by gorhill** [comment]
You can see what was allowed/blocked in the _Statistics_ tab, if you enable logging. When logging is enabled, there will be an eye icon in the popup, and clicking on it will bring you to the _Statistics_  tab. I want to keep the popup clean and simple, adding list of resources in there would be too cluttering.

**Comment by newzealandpaul** [comment]
Ah, that works perfectly.
