### ISSUE TITLE
Support Palemoon

### ISSUE THREAD

**Issue by anatasiajp** [uBlock-LLC/uBlock#1300]
Can you add support for Palemoon, a really nice browser without Australis: https://forum.palemoon.org/viewtopic.php?f=16&t=7373

Thank.

**Comment by lewisje** [comment]
It has been considered and discussed before; ultimately, the issues are the same as for SeaMonkey compatibility: https://github.com/chrisaljoudi/uBlock/issues/518

**Comment by chrisaljoudi** [comment]
Dup of #518.
