### ISSUE TITLE
Add keyboard shortcut for accessing Network-Request-Log

### ISSUE THREAD

**Issue by vdcbb** [uBlock-LLC/uBlock#1303]
Please add a keyboard shortcut for opening the Network-Request-Log. I'd like to humbly request CTRL+SHIFT+V as the shortcut to use (same shortcut that Adblock Plus uses).

**Comment by lewisje** [comment]
That would be doubly bad; it's bad enough that ABP overrides that shortcut on Firefox (it normally means "paste without formatting" in many Webmail interfaces, and it's useful when composing e-mails, so you don't need to paste into Notepad and then into GMail, Hotmail, Yahoo Mail, etc.).

How about `Accel+Shift+U`, the same as ABP's alternative shortcut? (Here, `Accel` refers to Command on the Mac, and Control on most other computers, including Windows.)

**Comment by vdcbb** [comment]
@lewisje: I have never heard of CTRL+SHIFT+V being used as you describe. I just went and tried it out on several different Webmail interfaces (although none of them Gmail, Hotmail, or Yahoo) and CTRL+SHIFT+V did nothing when tried. Only CTRL+V would paste.

But as I said in my first post, it was a humble suggestion. If it creates problems, and CTRL+SHIFT+U creates no problems, then perhaps it is a better choice. Either shortcut would make using uBlock more efficient for me.

**Comment by lewisje** [comment]
I hadn't heard about it before I saw this thread, and it changed my life: https://adblockplus.org/forum/viewtopic.php?p=64186

This is the related ABP issue, which was rejected, probably because Ctrl+Shift+V doesn't conflict with any shortcut used by the _browser_ or the _operating system_: https://issues.adblockplus.org/ticket/629
