### ISSUE TITLE
Please add Private mode compatibility

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1304]
"[Neither uBlock or Adblock Plus] allow for filters to activate when the browser goes into private mode, which is the point of having SpyBlock [a Adblock Plus fork part of GNU IceCat]. If somebody finds a better blocker that has this  eature, or somebody is willing to add that feature to uBlock then we can consider a change, but by now SpyBlock does exactly what it is supposed to do." - Rubén Rodríguez, GNU IceCat maintainer

If you implement Private mode in uBlock we can replace SpyBlock with it. Can you please implement this feature?

Try adding these lines to say spyblock.html as test object (HTML decode at http://meyerweb.com/eric/tools/dencoder/):
%0A%3Cul%3E%0A%20%20%3Cli%3E%3Ca%20href%3D%22abp%3Asubscribe%3Flocation%3Dhttp%253A%252F%252Fgnuzilla.gnu.org%252Ffilters%252Fblacklist.txt%26title%3DBlock%252Ball%252Bwell%252Bknown%252Bprivacy%252Btrackers%22%3EBlock%20all%20well%20known%20privacy%20trackers%3C%2Fa%3E%3C%2Fli%3E%0A%20%20%3Cli%3E%3Ca%20href%3D%22abp%3Asubscribe%3Flocation%3Dhttp%253A%252F%252Fgnuzilla.gnu.org%252Ffilters%252Fthird-party.txt%26title%3DBlock%252Ball%252Bthird%252Bparty%252Bresources%252Bwhen%252Bin%252Bprivate%252Bbrowsing%22%3EBlock%20all%20third%20party%20resources%20when%20in%20private%20browsing%3C%2Fa%3E%3C%2Fli%3E%0A%20%20%3Cli%3E%3Ca%20href%3D%22abp%3Asubscribe%3Flocation%3Dhttp%253A%252F%252Fgnuzilla.gnu.org%252Ffilters%252Fjavascript.txt%26title%3DBlock%252Bjavascript%252Bdata%252Brequests%252Bwhen%252Bin%252Bprivate%252Bbrowsing%22%3EBlock%20javascript%20data%20requests%20when%20in%20private%20browsing%3C%2Fa%3E%3C%2Fli%3E%0A%3C%2Ful%3E

**Comment by LocutusX** [comment]
Is "Private Mode" the same as "Private Browsing" (New Private Window)?

If so, then you are incorrect. uBlock works perfectly fine in Private Browsing; I just checked.

Your issue report doesn't refer to what browser you are using... it seems you may be using a fork of Firefox, and I don't think uBlock officially supports any Firefox ports. There are already requests to support Pale Moon, Waterfox, etc. so I think you'd need to "get in line" so to speak.

**Comment by ghost** [comment]
IceCat is based on Firefox ESR, currently on 31.x. Should be fine. Just tried it from the Trisquel ppa. It works in private browsing.

**Comment by davidhedlund** [comment]
Hi @LocutusX. My conversation with @rubenquidam (the maintainer of IceCat, and SpyBlock): ``

> Is "Private Mode" the same as "Private Browsing" (New Private Window)?

Yes. The feature is implemented by enabling filter lists that contain
"! Privatemode: true" only if the window is private.

I do that in http://gnuzilla.gnu.org/filters/third-party.txt
which disables any third-party requests from private windows.

''

**Comment by davidhedlund** [comment]
@quidam Can you please join the discussion?

What do you think about kintpuash's comment?

**Comment by ghost** [comment]
Think I get it now.

uBlock allows for the blocking of third party scripts etc., independent of whether or not in private browsing mode. Not sure the special significance of private browsing other than blocking history and cookies which can be done outside of the mode.

**Comment by rubenquidam** [comment]
The goal we had was to make "private browsing" actually more privacy protecting. We do this by blocking all third-party requests done by private windows. To avoid breaking pages that set the static server in a completely different domain (reditstatic -> reddit) there is a whitelist of domain pairs.

For regular windows we use a blacklist instead.

**Comment by gorhill** [comment]
The thing that bothers me with "private mode", is that it casts the concept of privacy as being an exception, not the default.

Let's look at things the other way around: private mode is the natural default mode. It's normal, it's a given.

In this case, the issue here would need to be re-titled: "Please add non-private mode compatibility".

So, why should there be a non-private mode? (which is what this issue would be about if we hold that "private mode" is the default). I failed to see the point of this issue.

**Comment by davidhedlund** [comment]
@rubenquidam Thank you for coming here.

@LocutusX @kintpuash Are you happy with hes reply or are there questions that arise?

@rubenquidam @LocutusX @kintpuash: Are SpyBlock private mode subscriptions (http://gnuzilla.gnu.org/filters/retriever/ and http://gnuzilla.gnu.org/filters/third-party.txt) compatible with uBlock in GNU IceCat 31.6.0 (built from Firefox ESR 31.6.0)?

Can you verify this rubenquidam?

**Comment by chrisaljoudi** [comment]
This is suggesting that certain filter lists should **only** work in "Private Mode". I think that's dangerous and undesirable (right now all filter lists apply regardless of private mode).

Did I misunderstand something?

**Comment by davidhedlund** [comment]
@rubenquidam Can you please comment this?

**Comment by davidhedlund** [comment]
This project is dead, I think the the issue should be merged to [uBlock Origin](https://github.com/gorhill/uBlock/issues) but I cannot do it, because the developer blocked me.
