### ISSUE TITLE
Allow 1st-party image requests

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1305]
For example, if I visit `http://example.com/foo.jpg` directly in default-deny mode, the image should not be blocked.

Not sure if this applies to other resource types.

**Comment by lewisje** [comment]
That's what the `$third-party` specifier is for.

**Comment by gorhill** [comment]
> the image should not be blocked

Do you have an **actual** case where this happens?

**Comment by gorhill** [comment]
I can't reproduce OP's reported behavior. I use default-deny myself, and when I paste `http://static.fsf.org/nosvn/join.en.png` in the address bar, the image shows just fine.

**Comment by chrisaljoudi** [comment]
> For example, if I visit `http://example.com/foo.jpg` directly in default-deny mode, the image should not be blocked.

@nyuszika7h correct. That seems to be the current behavior — do you have a test case where that's not true?

**Comment by ghost** [comment]
I can reproduce this on a clean profile with default settings and just `* * * block` added.

Request log: https://i.imgur.com/wwlL16t.png

As far as I understand, since the document itself is not blocked even in this mode, if the image is the document, it shouldn't be blocked either.

**Comment by gorhill** [comment]
> default settings and just `* * * block` added

If you want 1st-party resources to not be blocked, why not use `* * 3p block`?

**Comment by ghost** [comment]
I do in fact use that now, but the current behavior is still inconsistent IMO.
