### ISSUE TITLE
UI improvements not in FF version ?

### ISSUE THREAD

**Issue by Betsy25** [uBlock-LLC/uBlock#1309]
I just installed the 0.9.3.5 in Firefox, and I'm not seeing any of those nice UI refinements. i.e. all checkmark still look white and black instead of nice blue & the count badge still looks as it always was.

Am I missing something ?

**Comment by alejandrolemus** [comment]
Not completely sure, but I think those are defined by Safari, not uBlock

**Comment by hairycactus** [comment]
Same here. I installed uBlock 0.9.3.5 in my Firefox under the impression that there is a new UI, as implied by the release notes (1st bullet point: _"UI, icons, and color scheme refinement"_):
https://github.com/chrisaljoudi/uBlock/releases/tag/0.9.3.5

Yet it looks identical to previous versions (ie. before the add-on diverged into 2 forks). I thought it was just me. Do the UI changes appear in Chrome's version ?

**Comment by alejandrolemus** [comment]
There are differences, just not those. See below a comparison on Chrome 42.0.2311.90

![ublock_ui](https://cloud.githubusercontent.com/assets/9505902/7303058/dc47ea7e-e9bb-11e4-9919-c473d0d2ae94.png)

![ublock_ui](https://cloud.githubusercontent.com/assets/9505902/7303152/80e699cc-e9bc-11e4-8e4c-8d26423998db.png)
