### ISSUE TITLE
Element hiding performance

### ISSUE THREAD

**Issue by roshambo1** [uBlock-LLC/uBlock#131]
I notice blank elements stay on the page long enough to be noticeable. For example http://filehippo.com/download_ccleaner near the top between CCleaner and Description/Technical, etc.

These blank elements never appear on other adblock extensions but they are slower to load the page overall. Could ublock in the future never show these blank elements without slowing down page loading?

**Comment by gorhill** [comment]
> Could ublock in the future never show these blank elements without slowing down page loading?

It works already for filters which are domain-specific: these can be applied before the primary DOM is loaded.

Maybe I could come up with a heuristic to auto-generate internally domain-specific filters. So the first time there would be a probability the glitch is noticeable, while thereafter it would no longer be (as long as the extension is not re-launched). That would be the best compromise between performance/efficiency and no-glitch cosmetic filters.

**Comment by roshambo1** [comment]
Would be interesting to try if it's not much work.

**Comment by ghost** [comment]
I too am having this issue.
