### ISSUE TITLE
"Acceptable Ads" option [not] missing

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1312]
This is what I found in the AdBlock Plus Filter Preferences main window at the bottom:
- [ ] Allow some non-intrusive advertising
- [View list](https://easylist-downloads.adblockplus.org/exceptionrules.txt)
- [Read more](https://adblockplus.org/en/acceptable-ads)

uBlock do not have this option.

**Comment by gorhill** [comment]
You missed: https://github.com/chrisaljoudi/uBlock/blob/master/MANIFESTO.md:

> The uBlock project does not support Adblock Plus' "Acceptable Ads Manifesto", because the "Acceptable Ads" marketing campaign is really the business plan of a for-profit entity.

uBlock's purpose is not to cater to the business plan of for-profit entities.

**Comment by davidhedlund** [comment]
@gorhill Ah, I got it. Thank you.

**Comment by davidhedlund** [comment]
The main reason why I brought this up is because the EasyList owners are not willing to block "acceptable advertisment" without the option to enable it if you want to as described above.

As a work around I suggested more uBlock inbuilt (subscription) filters in https://github.com/chrisaljoudi/uBlock/issues/1384.
