### ISSUE TITLE
Request log not showing in Firefox/OSX?

### ISSUE THREAD

**Issue by jfml** [uBlock-LLC/uBlock#1313]
Just discovered uBlock and I love it, however when I open the request log (e.g. chrome://ublock/content/devtools.html?tabId=XXX) in FF 37 on OSX 1.9.5 I see the grey bar with icons etc. but only a white page beneath that.

Does anybody know why that might be (I'd be happy to give further info, I run quite a lot of plugins and also a system wide host-filter).

**Comment by ghost** [comment]
Maybe you did not press reload?

https://github.com/gorhill/uBlock/wiki/The-network-request-logger

> Take note that the network request logger in µBlock is a forward-looking logger: this means only future requests can be logged. In the spirit of efficiency, µBlock will log network requests for a tab if and only if there is a logger opened for that tab.

**Comment by jfml** [comment]
Wow, ok! I didn't get that, thanks! (It's working obviously.)
