### ISSUE TITLE
Blocking specific domains while blocking is turned off.

### ISSUE THREAD

**Issue by ZzzZombi** [uBlock-LLC/uBlock#1314]
Is there any way to keep blocking certain domains even when the blocking is turned off?

For example; I want to block adzerk globaly (everywhere) but when I whitelist a certain site (that connects to adzerk) I want adzerk still blocked. Is this possible?

Thank you.

**Comment by lewisje** [comment]
If you whitelist a site, that goes into static filtering; dynamic filtering overrides that: https://github.com/chrisaljoudi/uBlock/wiki/Dynamic-filtering:-quick-guide#important-1
