### ISSUE TITLE
Some filters websites are broken

### ISSUE THREAD

**Issue by Pkaffz** [uBlock-LLC/uBlock#1318]
Hello, these filter websites are not working:

 Peter Lowe’s Ad server list‎ = http://pgl.yoyo.org/as/serverlist (404 not found)
 Block all well known privacy trackers = http://gnuzilla.gnu.org/filters/blacklist.txt (site not working)
 Fanboy+Easylist-Merged Ultimate List‎ = https://www.fanboy.co.nz/fanboy-ultimate.txt (404 not found)
 hpHosts’s Ad and tracking servers‎ = http://hosts-file.net/ad-servers (404 - File or directory not found.)

And also, can you make please checking and updating all filters more often then they checking updates now?

**Comment by lewisje** [comment]
I think the directory structure under `assets/thirdparties` is just an abbreviation, like there never was an `as/serverlist` at pgl.yoyo.org, but this link works just fine: http://pgl.yoyo.org/as/serverlist.php?hostformat=adblockplus&showintro=0&mimetype=plaintext

Similarly, Fanboy Ultimate is at https://www.fanboy.co.nz/r/fanboy-ultimate.txt (notice the `/r/` in the path), and by reading the filter-lists themselves, uBlock knows where to look for updates.

I don't think it's a good idea to overload these third-party servers by checking the filter-lists for updates more often.

**Comment by gorhill** [comment]
> I think the directory structure under assets/thirdparties is just an abbreviation

Yes, this reflects the local location of a filter list, not the remote one. I don't know how OP came up with those URLs, they are not used by uBlock to pull from remote servers -- except for the gnuzilla one.

So there is no issue here.
