### ISSUE TITLE
Filters don't seem to be detected/working on PortableApps.com

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#132]
On the Homepage for PortableApps, there are 5 images blocked above the Log in link, and 4 images blocked in the "Community" block.

uBlock doesn't seem to show them as "blocked", actually I see them under allowed, but uBlock is still blocking them.

I'm using uBlock 0.3.2.0, and every list except those under "Regions, languages" are enabled (none under that section, all under every other section), with the EasyList Adblock Warning Removal Enabled.

I disabled DoNotTrackMe and Disconnect on that site to be sure, and HTTP Switchboard had nothing that should block it. Disabling uBlock for that site shows them all, even with all my other tracker block/privacy addons enabled.

**Comment by gorhill** [comment]
These images are not blocked, they are hidden by cosmetic filters.

µBlock's request log is for **net requests**, not DOM elements. Uncheck _"Parse and enforce Adblock+ element hiding filters."_ and you will see the images appear.

I will never conflate element hiding filters with net request filters, as this would lead to a erroneous sense of privacy protection, as cosmetic filters have complete zero value privacy-wise, while net filters can enhance privacy.
