### ISSUE TITLE
CSS error (typo?) in dashboard.css

### ISSUE THREAD

**Issue by AlexVallat** [uBlock-LLC/uBlock#1320]
Originally reported in https://github.com/chrisaljoudi/uBlock/issues/1315#issuecomment-96222188 but not related to that branch.

looks like dashboard.css ought to be `color: inherit;` not `inherited`?

Possibly something wrong with about.css too? My css-fu is not strong enough to be sure about that, though - I'm not sure exactly what's going on there.

**Comment by gorhill** [comment]
Yes, `inherited` is wrong, it's supposed to be `inherit`.

**Comment by chrisaljoudi** [comment]
Yes, that was wrong. With `about.css`, that seemingly-odd "name" should get replaced with `left`/`right`/etc. at compile-time.

**Comment by AlexVallat** [comment]
@chrisaljoudi Do you mean that this is something that should be added to the compile-time scripts, or that it is something they are supposed to be doing already but are not? Looking inside the released .xpi, it isn't happening at the moment. Not that the loss of a small amount of padding is a big deal, of course.
