### ISSUE TITLE
uBlock 0.9.3.5 at addons.mozilla.org

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1322]
Please upload uBlock 0.9.3.5 to https://addons.mozilla.org/en-US/firefox/addon/ublock/

**Comment by AlexVallat** [comment]
uBlock 0.9.3.5 was submitted to AMO on 19/04/2015 and is currently at position 87 of 120 in the queue for review.

**Comment by ghost** [comment]
@AlexVallat 

With the legacy toolbar support being merged into the main build, would it be prudent to supersede the current release in the review queue if it is not far along?

**Comment by AlexVallat** [comment]
No, I don't think so. 0.9.3.5 has been in the queue for a week already, and the legacy toolbar button stuff is not even part of any release version yet. Like all new features, it will just take it's time to surface on AMO.

**Comment by ghost** [comment]
understood

**Comment by davidhedlund** [comment]
@AlexVallat Thank you.
