### ISSUE TITLE
How to block cosmetic pseudo elements?

### ISSUE THREAD

**Issue by wamatt** [uBlock-LLC/uBlock#1325]
Is there a way to block ::before or ::after CSS elements?

For example on [quora.com](https://www.quora.com), there could be a need to block the suggested stories and the entire gray area.

![image](https://cloud.githubusercontent.com/assets/1271434/7339567/81571b66-ec28-11e4-9f37-2d4ea5019d36.png)

It appears then that the gray area in question, is constructed as a ::after psuedo element on div class `"Standard2ColLayout"`

![image](https://cloud.githubusercontent.com/assets/1271434/7339578/e0cd153c-ec28-11e4-8366-d0431082de1a.png)

So while it remains certainly possible to block those suggested stories with the network filter or even cosmetic filter on a more specific element, both of those methods, will leave a large gray space behind.

While not a big deal, my curiosity is around how to do it at the source. And of course, a general solution would be more satisfying.

**Comment by gorhill** [comment]
You can block whatever CSS selector which can return a non-empty result when the CSS selector is fed to `document.querySelectorAll`. Unfortunately, `:after` and `:before` does not return any result.

**Comment by chrisaljoudi** [comment]
What @gorhill explained is definitely true — however, it applies only to cosmetic rules that aren't qualified with a domain name. If you do qualify them, then the hiding rules will in fact get injected.

For your case, this seems to work in my testing:

```
quora.com##.ContentPageFeed
quora.com##.Standard2ColLayout:after
```

**Comment by ghost** [comment]
<sub>\*it it isn't working for you, use double colon <code>quora.com##.Standard2ColLayout::after</code>
alternatively, use <em>style-injecting rule</em>: <code>reddit.com##*::before:style(display:none !important;)</code>
</sub>

**Comment by david-tap** [comment]
I'm trying to make a scrollbar wider using `site##*::-webkit-scrollbar-thumb:style(width: 18px !important)` but it's not taking effect. I tried using `-webkit-scrollbar` as well.
Am I doing it wrong, or did the behavior change?
