### ISSUE TITLE
[Chrome, Windows 7] Strange bug with specific website

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#1326]
As reported in https://github.com/gorhill/uBlock/issues/134.

It's really a bad bug, this potentially corrupt the parts of the runtime (not the persisted) instance of the static filtering engine when a user creates custom filter using the element picker.

Fix:
https://github.com/gorhill/uBlock/commit/7ad66fdb2c49f18152a7d67cba8898de73317342

**Comment by chrisaljoudi** [comment]
Fixed in 7a8612bfec. Thank you.
