### ISSUE TITLE
about-scheme in uBlock (and uBlock Origin) on whitelist by default.

### ISSUE THREAD

**Issue by Piter432** [uBlock-LLC/uBlock#1329]
By default, both in uBlock and uBlock Origin, on whitelist there are some native pages:
behind-the-scene (not sure in what browser and native page)
chrome-extension-scheme (for Chrome's extension native page)
chrome-scheme (for all Chrome's native pages)
opera-scheme (for all ChrOpera's native pages)

But uBlock and uBlock Origin is also available on Firefox and Firefoxes native pages are about:addons, about:support, etc. and they're not on whitelist in uBlock and uBlock Origin until user add "about-scheme" to whitelist in Firefox or other browser which native pages are starting from "about" like in Firefox.

What do you think of that, @gorhill and @chrisaljoudi? :)

**Comment by gorhill** [comment]
`about-scheme` used to be whitelisted by default. I would have to dig but I remember there was some reasons behind not having these whitelisted by default -- I can't remember why (maybe something to do with blocking popups?). Chromium also supports `about:blank`.

I will put it back in the whitelist by default, and extends the support for `about:[...]` pages: it will now be possible to whitelist specifically some `about:` pages while leaving others un-whitelisted.

**Comment by gorhill** [comment]
Fix is in:

https://github.com/gorhill/uBlock/commit/032d5e0a343af49424f05d8d4900c2795ada6516

**Comment by chrisaljoudi** [comment]
@gorhill yep; thank you. Committed in `da9aaf73e1` (hopefully I didn't screw up the authorship this time :)).
