### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by MurkBRA** [uBlock-LLC/uBlock#1330]
I already report this [here](https://github.com/chrisaljoudi/uBlock/issues/1273) and get fixed but when you try hide a element that text have no color defined as you can see in this pic Im on Latest release 0.9.3.5.
![323a54a6dd](https://cloud.githubusercontent.com/assets/12011370/7353294/d6021dbc-ece8-11e4-933d-c683ba072fb6.png)

**Comment by MurkBRA** [comment]
Fix -> edit this file `epicker.html` and add `color: #333;`
`html, body {`

> ```
> background: transparent !important;
> margin: 0;
> width: 100%;
> height: 100%;
> overflow: hidden;
> font: 12px sans-serif;
> ```
> 
> +`color: #333;`

**Comment by chrisaljoudi** [comment]
@MurkBRA thank you.
