### ISSUE TITLE
Please add "Last updated YYYY-MM-DD HH:MM:SS" for filters

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1332]
In chrome://ublock/content/dashboard.html#3p-filters.html,
- Please add a timestamp when the global filter update was performed.
- Please add timestamps when each filter was updated if disabled filters are not updated.

**Comment by Snapy** [comment]
Already available. If you go over the `purge cache` button, it will say when it was last updated.

**Comment by davidhedlund** [comment]
@Snapy I did that but could not find any date (YYYY-MM-DD HH:MM:SS) timestamp.

**Comment by Snapy** [comment]
There are no date but you know the time of the last update. Isn't it enough to know if a given filter is outdated ?

**Comment by davidhedlund** [comment]
@Snapy No, because it does not let users know if filters are maintained or not.

**Comment by davidhedlund** [comment]
This project is dead, use [uBlock Origin](https://github.com/gorhill/uBlock/issues) instead.

This issue is not relevant any more.
