### ISSUE TITLE
Please add used filter in text box and a import/export button.

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1333]
In chrome://ublock/content/dashboard.html under "One URL per line. Lines prefixed with ‘!’ will be ignored. Invalid URLs will be silently ignored.",
- please replace examples with the used filters in the text field so users can copy/paste the list.
- I also suggest a Please also add a import and export button there.

**Comment by ghost** [comment]
> please replace examples with the used filters in the text field so users can copy/paste the list.

I don't understand that sentence.

> I also suggest a Please also add a import and export button there.

"Import and append" and "Export" are already there, below the textarea.

**Comment by davidhedlund** [comment]
@WyohKnott 
In chrome://ublock/content/dashboard.html#3p-filters.html there's a text starting with "! Examples:" in the text field, right?

> "Import and append" and "Export" are already there, below the textarea.

Only for chrome://ublock/content/dashboard.html#1p-filters.html
but not for chrome://ublock/content/dashboard.html#3p-filters.html

**Comment by Betsy25** [comment]
@davidhedlund said : 

> In chrome://ublock/content/dashboard.html#3p-filters.html there's a text starting with "! Examples:" in the text field, right?

Those are examples (the ! in front of a line treats that line as a comment, or an example in this case), simply deleting the ! in front of a line, makes the filterlist on that line active.
When they would be there by default without a ! in front, all those lists would be active by default, and 99% of users would not be happy with that.

> Only for chrome://ublock/content/dashboard.html#1p-filters.html
> but not for chrome://ublock/content/dashboard.html#3p-filters.html

I believe it's not there on the 3rd party page, because now and then new lists are added, and abandoned ones are removed.

If you do a Backup or a Restore it handles both 1st & 3rd party filters & lists.

**Comment by davidhedlund** [comment]
@Betsy25 said:

> Those are examples (the ! in front of a line treats that line as a comment, or an example in this case), simply deleting the ! in front of a line, makes the filterlist on that line active.
> When they would be there by default without a ! in front, all those lists would be active by default, and 99% of users would not be happy with that.

My suggestion is that the maintainer replace the examples with the filters that is checked on the page.

> If you do a Backup or a Restore it handles both 1st & 3rd party filters & lists.

I think the maintainer should put a note about this in chrome://ublock/content/dashboard.html#1p-filters.html to avoid confusion.

**Comment by davidhedlund** [comment]
This project is dead, use [uBlock Origin](https://github.com/gorhill/uBlock/issues) instead.

This issue is not relevant any more.
