### ISSUE TITLE
Google Images

### ISSUE THREAD

**Issue by fantattitude** [uBlock-LLC/uBlock#1337]
Google Images seems to be broken when µBlock activated…
Strangely I noticed this only recently so must be something Google changed.

![capture d ecran 2015-04-29 a 22 34 24](https://cloud.githubusercontent.com/assets/40499/7400823/e8e85a1c-eebf-11e4-984b-47a7bb52ca9f.png)

**Comment by Betsy25** [comment]
Seems like the culprit is in the EasyPrivacy list, https://github.com/gorhill/uBlock/issues/159#issuecomment-97906674

**Comment by chrisaljoudi** [comment]
Odd; can't reproduce. Using default settings. Perhaps EasyPrivacy got updated meanwhile?

**Comment by Betsy25** [comment]
@chrisaljoudi Most probably geo located, or some specific searches.

**Comment by gorhill** [comment]
Yes, it did get updated: https://hg.adblockplus.org/easylist/rev/8665b534a239 (well, 42 min. ago).
