### ISSUE TITLE
Garmin Connect web pages garbaged when uBlock enabled

### ISSUE THREAD

**Issue by Nick-Payne** [uBlock-LLC/uBlock#1338]
Firefox 37.0.2 on Windows 8.1, uBlock 0.9.1.0. With uBlock enabled, there are what look like field descriptors appearing on the screen where just the data for distance, time, elevation etc should be appearing. A couple of screen shots showing what I mean:

With uBlock off: https://www.dropbox.com/s/gc3q0lhdviy20wf/uBlock_off.png?dl=0
With uBlock on: https://www.dropbox.com/s/py5xfoxgdn7sluw/uBlock_on.png?dl=0

I have a workaround, which is to add connect.garmin.com as a uBlock whitelisted host name. Haven't noticed a similar problem with any of the other web sites I visit.

**Comment by chrisaljoudi** [comment]
This is because of this filter in EasyPrivacy:

```
/metrics/metrics
```

An exception filter needs to be added; something like:

```
@@||connect.garmin.com^/modern/main/js/properties/metrics$domain=garmin.com
```

[Just reported this to the EasyList/EasyPrivacy maintainers](https://forums.lanik.us/viewtopic.php?f=64&t=22543), so it should be fixed soon in an update of those lists.

**Comment by Nick-Payne** [comment]
Thanks for sorting that.
