### ISSUE TITLE
Autoplaying videos, twice

### ISSUE THREAD

**Issue by roshambo1** [uBlock-LLC/uBlock#134]
http://theweek.com/article/index/265825/speedreads-jon-stewart-thrashes-congress-on-immigration-only-obama-and-the-kkk-have-border-security-plans  for example auto plays the first daily show video twice. Expect it to not auto play and only play once when played like adblock does with identical filters.

**Comment by gorhill** [comment]
Can't investigate: "Video not available from your location".

**Comment by roshambo1** [comment]
Willing to try proxy like https://chrome.google.com/webstore/detail/hola-better-internet/gkojfkhlekighikafcpjkiklfbnlmeio/related?hl=en  it's not fast but it should work for this situation then it can be removed or disabled.

**Comment by gorhill** [comment]
Can you verify the problem is still there after fix of #114?

**Comment by roshambo1** [comment]
Works fine now, thanks!

**Comment by gorhill** [comment]
Fix to #114 fixed this.
