### ISSUE TITLE
Version 0.9.3.5: No download for SeaMonkey users from AMO

### ISSUE THREAD

**Issue by RainerBielefeld** [uBlock-LLC/uBlock#1344]
On https://addons.mozilla.org/de/firefox/addon/ublock/versions/ I fond Version 0.9.3.5, what should (and does) wor with my EN-US Seamonkey 2.33.1 (German Language pack)  Gecko/20100101 Build 20150321194901 (Default Theme) on German WIN7 64bit.
For unknown reasons the download button stays greyed out and inactive for SeaMonkey users, while download works without any problems from FF 37. Can you please have a look and make that version available for SeaMonkey users?
FYI:
a) For Test affairs I uploaded a test version with some minimum modifications to AMO at https://addons.mozilla.org/de/seamonkey/addon/smublock/.
b) For test affairs I made available your Version 0.9.3.5 with some minimum modifications at https://sourceforge.net/projects/seamonkeyaddons/files/

**Comment by AlexVallat** [comment]
Seamonkey support is coming soon - it will be in the next version. Until then, you can try the test build here: https://github.com/AlexVallat/uBlock/releases/tag/0.9.3.5-dev-av.2

If you find any SeaMonkey-specific issues with it, or anything you think needs to be included from your modifications, please let me know.

**Comment by RainerBielefeld** [comment]
This issue report **only** is concerning the problem that you add-on, what in install.rdf shows a valid _SeaMonkey_ version for current SM versions and what works fine with SeaMonkey, can not be downloaded from AMO, because for unknown reasons the download button keeps inactive greyed if you visit the AMO ublock versions page (as I wrote in original report). Do you have skills to change that in AMO or good reasons (like "we are pretty sure that that version works fine for FF, but we do not think that it works with SM") to block an add-on what is listed as "SeaMonkey 2.21 and more recent"?  
If that "inactive download button" is not intended by you, that might be an AMO bug (or some operating error).  
So if intended please tell how and why the download from SeaMonkey add-on-manger has been blocked. Several users on _de.comm.software.mozilla.browser_ are rather worried about thatt crazy download behavior.

**Comment by AlexVallat** [comment]
v0.9.3.5 has been marked as compatible with SeaMonkey for AMO, but is still waiting in the queue for review (currently position 84 of 140). Once it passes review and becomes the active version available for download, it should no longer appear disabled for SeaMonkey.

**Comment by RainerBielefeld** [comment]
And there is a separate review for SM and FF users, so that the same version can be downloaded from FF but not from SM? I really really doubt. And can you explain why https://addons.mozilla.org/de/seamonkey/addon/smublock/ with review position 133 of 134 can be downloaded from SM without problems? I will discontinue this discussion here.

**Comment by chrisaljoudi** [comment]
@RainerBielefeld let me try to explain, if I may. 

uBlock 0.9.3.0 didn't declare support for SeaMonkey in its `rdf` (I believe that's the file). The store is aware of that manifest spec, allows/disallows users of different applications to download it. 

Since 0.9.3.0, (namely the 0.9.3.5 release), uBlock does indeed declare support for SeaMonkey. 

The version currently on the store is 0.9.3.0. When 0.9.3.5 makes it through the queue and is approved (along with the new manifest info), the new compatability information will take effect and SeaMonkey users will be able to download. 

It's just a matter of _distributing_ the changes and getting them live.
