### ISSUE TITLE
EasyPrivacy related: eBay chat support blocked

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1345]
Without any retrieved blocks by uBlock (clean icon without any numbers on it) the eBay chat support is still blocked.

**Comment by gorhill** [comment]
Any good reason you are not providing a specific URL where whatever "eBay chat support" can be seen?

https://github.com/chrisaljoudi/uBlock/blob/master/CONTRIBUTING.md: **"Always include a URL, even if 'it happens everywhere' ".**

**Comment by davidhedlund** [comment]
@gorhill http://ocsnext.ebay.co.uk/ocs/cusr?query=597 click on "Chat with us", you need an account to do this.

**Comment by gorhill** [comment]
I clicked "Chat with us" button, and a popup opened, from which a chat session could be started (I obviously did not start). So, can't reproduce using the provided limited details (assuming default settings).

**Comment by davidhedlund** [comment]
@ghorhill The chat will not be loaded so it does not matter if you have the chat window active for a long time. uBlock prevents the chat page to reload which is required for the chat to start when an agent is available.

**Comment by gorhill** [comment]
I get "We're on the way and will be with you as soon as we can. Thanks!". I see no issue so far (assuming default settings since none are provided).

**Comment by davidhedlund** [comment]
@gorhill Yes, I see that message too. But the agent never arrive. Do the "Done" status bar message reload once in a while for you? It doesn't for me.

**Comment by gorhill** [comment]
And this is uBlock's fault... How?

**Comment by davidhedlund** [comment]
@gorhill Because when I disable uBlock I can use the chat.

**Comment by gorhill** [comment]
Disabled uBlock, I get "We're on the way and will be with you as soon as we can. Thanks!" as well.

**Comment by davidhedlund** [comment]
@gorhill Me too, but the difference is that I actually get contact with someone to chat with.

**Comment by gorhill** [comment]
Problem is in 3rd-party filter list, EasyPrivacy. Report to maintainers: https://forums.lanik.us/viewforum.php?f=64.

Workaround: `@@||cschat.ebay.*/TAW/light/util/scripts/log.js`

**Comment by davidhedlund** [comment]
@gorhill Thank your very much for taking your time. I will definitely report it.

**Comment by davidhedlund** [comment]
@gorhill I reported it in https://forums.lanik.us/viewtopic.php?f=64&t=22568&p=69938#p69938

**Comment by davidhedlund** [comment]
@gorhill Could you use the chat with @@||cschat.ebay.*/TAW/light/util/scripts/log.js?

**Comment by gorhill** [comment]
I closed the chat when someone came, I don't want to lose their time. If you think something else is wrong. please use the request logger, this is how I found out that something was blocked.

**Comment by davidhedlund** [comment]
@gorhill Good, then the filter do what it is intended to. Yes of course, I should have used the request logger from the beginning, I'm new to uBlock. Thanks for your patience.

**Comment by davidhedlund** [comment]
@gorhill The only red line I find in the request logger is this:
-  ||rover.ebay.   image   http://rover.ebay.com/roverimp/0/0/14?imp=2064752&lv=tz%3D2%26lt%3D2015-05-01T18%253A07%253A52%253A554%26ref%3D%26ai%3D5513%26res%3D1600x900%26fla%3D0%26slr%3D0%26scd%3D24%26ctb%3D63993&mpt=1430503672560

**Comment by davidhedlund** [comment]
![screenshot from 2015-05-01 20 15 25](https://cloud.githubusercontent.com/assets/6416073/7434907/de5e2510-f03e-11e4-93cb-441401a07efe.png)

**Comment by davidhedlund** [comment]
@gorhill I did not find anything related to @@||cschat.ebay.*/TAW/light/util/scripts/log.js

Where should I look (trying to learn how to use uBlock)?

**Comment by gorhill** [comment]
You are not looking at the request log for the chat window. Launch the chat window, then launch the request log, then select the chat window in the request log (the selector at the top).

**Comment by davidhedlund** [comment]
![screenshot from 2015-05-01 20 20 50](https://cloud.githubusercontent.com/assets/6416073/7434986/a2d4dbaa-f03f-11e4-9574-7a6d64a15585.png)

**Comment by davidhedlund** [comment]
@gorhill Thank you.

**Comment by davidhedlund** [comment]
@gorhill I suggest that the "Request logger" is in the context menu.
