### ISSUE TITLE
Add hover titles [Fixed in 0.9.3.5]

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1346]
- Please make the title "Element picker?" (what's the name of this tool?) show when the dropper is hovered by the mouse cursor.
- Please make the title "Network request logger" (https://github.com/gorhill/uBlock/wiki/The-network-request-logger) show when the eye is hovered by the mouse cursor.

This should help people

**Comment by chrisaljoudi** [comment]
This is already the case, isn't it? (Certainly is supposed to be). 

What version of uBlock/browser are you using?

**Comment by davidhedlund** [comment]
@chrisaljoudi I am using uBlock 0.9.1.0 and it does not show for me.

**Comment by chrisaljoudi** [comment]
@davidhedlund oh. 

I assume you have Advanced User enabled? In older versions of uBlock (0.9.3.0 and earlier), Advanced User being enabled prevents tool tips (hover titles) from appearing. 

This has been fixed in 0.9.3.5. If you upgrade to that, all should be well.

**Comment by davidhedlund** [comment]
@chrisaljoudi Yes I have Advance User enabled. Thank you, this feature is implemented in version 0.9.3.5 that I just upgrade too.
