### ISSUE TITLE
Please add "Network request log" in the context menu

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1347]
I suggest that "Network request log" is in the context menu too. This is useful in popup windows as the location bar (with the uBlock icon) is not visible there. The logger is needed to know which files popups uses. For example, I could not use the eBay chat support but gorhill helped me (https://github.com/chrisaljoudi/uBlock/issues/1345#issuecomment-98181483).

**Comment by chrisaljoudi** [comment]
My first impression is that this is a good idea.

Given the tab-specific nature of the popup, it makes sense to have some other way of performing the various actions (including opening the Request Logger) on pages that don't have a toolbar.

**Comment by davidhedlund** [comment]
@chrisaljoudi Thank you. I hope you add it. Please read https://github.com/chrisaljoudi/uBlock/issues/1345#issuecomment-98181483 for the case report.
