### ISSUE TITLE
Show number of blocked requests for current page load only

### ISSUE THREAD

**Issue by zzottel** [uBlock-LLC/uBlock#1349]
Currently, the number shown at the icon displays the added number of all blocked requests since this tab was opened, if I'm not mistaken (edited, I thought this was the added count for the host at first). To me, this isn't really useful.

I'd prefer that indicator to show only the number of requests that were blocked since the current page was loaded, same for the dynamic blocking content—preferably as an option, as others might like the way it is better.

EDIT: Knowing the full number of blocked requests since a tab was opened has no meaning to me. I want to know how many requests were blocked at the page I just opened, and I want to see to which hosts those requests went to in the dynamic blocking part of the uBlock popup.

My goal in using a tool like uBlock is not only to block tracking, but also to be informed about tracking a site wants to apply. I just started using uBlock, coming from Ghostery, and I miss the Ghostery popup that told me about the trackers that were blocked. I saw that one goal of uBlock is not to be intrusive, so I won't request such a popup, but the count of every blocked request since a tab was opened is meaningless to me—I want to see what is blocked right now, including subsequent AJAX requests, of course, but starting from zero when I navigate to another page.

**Comment by gorhill** [comment]
That's how it is.

**Comment by zzottel** [comment]
This seems to be a recently introduced change. I saw it with v9.3.5 on Firefox/Mac. On Firefox/Windows 7, where v0.9.1 was synced to, it behaved as expected, i.e. number reset to zero with every page load. To check, I now updated to 0.9.3.5 here, too, and now uBlock started to behave like described above.

**Comment by zzottel** [comment]
Ah, no.

This seems to happen when updating from 0.9.1 to 0.9.3.5 _without restarting Firefox._

Once Firefox is restarted, the behavior goes back to the way I expected it to work.

By me, the ticket can be closed. I'd leave it open in case you want to have a look why this is happening, but as it fixes itself with a browser restart, I'd say a a fix is not desperately needed. :-)
