### ISSUE TITLE
NBC embeds not playing

### ISSUE THREAD

**Issue by roshambo1** [uBlock-LLC/uBlock#135]
http://pitchfork.com/news/56171-spoon-perform-do-you-on-the-tonight-show/  video doesn't play with my filters+fanboys ultimate. Works fine with adblock and identical filter lists.

**Comment by gorhill** [comment]
Works fine from here. What filter lists do you have selected? What do you have in "Your filters"?  Browser version, etc. Details please.

**Comment by gorhill** [comment]
Ok, reproduced. It appears one of the multipurpose lists causes the video to play fine.

**Comment by gorhill** [comment]
So there are two possible fixes. Block more:

To add  `||adm.fwmrm.net^` to uBlock's filters

Block less:

To enable pending code re. issue #114, which causes more net requests from `adm.fwmrm.net` to go through.

**Comment by roshambo1** [comment]
Thanks, that works well.

**Comment by gorhill** [comment]
I want to fix this on uBlock side, still undecided which fix to pick. I will always prefer blocking more, but I wonder if this may break a lot of things if I go this route.

**Comment by gorhill** [comment]
Ok I will go with #114 for the fix. Whoever wants to block more can easily select MVPS and/or Dan Pollock's lists, these block `adm.fwmrm.net`. So I will mark as dup of #114. Meanwhile the above is the workaround.

**Comment by roshambo1** [comment]
My opinion is to change it to be like the other adblockers, I don't know about all but fanboy and easylist are easy to get fixed, just post and within a day it's usually fixed. An example where ublock's current way is actually helpful is http://www.hulu.com/watch/670125?playlist_id=1031&asset_scope=all  (proxy needed). It plays the 5s ad, while adblock blocks the ad and forces a 30s wait. If an ad on the video hasn't been seen it forces the wait and then plays ad, I've been meaning to figure out what's doing it and report to fanboy so he can fix it. Just low priority, maybe I'll do it now.

**Comment by gorhill** [comment]
Fixed with fix to #114.
