### ISSUE TITLE
SeaMonkey: Whitelist becomes lost

### ISSUE THREAD

**Issue by RainerBielefeld** [uBlock-LLC/uBlock#1350]
Steps how to reproduce with µBlock 0.9.3.5 from [AMO](https://addons.mozilla.org/de/firefox/addon/ublock/versions/) on EN-US **SeaMonkey** 2.33.1 (German Language pack)  Gecko/20100101 Build 20150321194901 (Default Theme) on German WIN7 64bit:  
0) Launch SeaMonkey Browser  → Add-on Manager → uBlock  
1)  open µBlock dashboard → Whitelist TAB: _you will see some whitelist host names_  
2) add "helpster" into first blank line  
3) [Apply]: _You see list in alphabetic order_  
4) Exit **SeaMonkey**  
5) restart with step 0: _unexpectedly Whitelist will be empty in step 1_  

I did not observe that problem with FF37.0.2 and the same µBlock 0.9.3.5

**Comment by gorhill** [comment]
What happens if you close then re-open the Whitelist tab?

**Comment by RainerBielefeld** [comment]
Switching to an other TAB and back to Whitelist might delete a leading blank line
Closing dashbord (By closing Browser TAB) does nothing bad, Whitelist still will be there when I reopen Dashboard → Whiteboard.
As far as I remember Closing browser also will not delete Whiteboard contents, only happens when I close / reopen the browser.
But I have the suspect that the lost entries still are working, I will try to  prove or refute that later.

**Comment by gorhill** [comment]
I suspect that the uBlock page could be opened by Firefox before uBlock is loaded in memory, which means the page won't be able to fetch data from uBlock to fill its content. Switch panes, or closing the page and reopening the dashboard should fix the issue -- hence why I asked. Not sure I understand your answer though. Does the whitelist come back when you close then re-open the tab?

**Comment by RainerBielefeld** [comment]
It is necessary to exit SeaMonkey to see the loss.
I did not reproduce the loss with any other action.

**Comment by gorhill** [comment]
You are not answering my question.

Does the whitelist data come back when you close then re-open the tab? (or similarly when you select another pane in the dashboard and then re-select the _Whitelist_ pane?)

Yes or no?

**Comment by RainerBielefeld** [comment]
Simply forget it, I am tired with µBlock and dropped it.
