### ISSUE TITLE
How to Use Element Hiding Helper with uBlock?

### ISSUE THREAD

**Issue by MED-PRO** [uBlock-LLC/uBlock#1353]
Hello,
I'm a ABE user and lately I tried to move to uBlock but I could not use Element Hiding Helper Firefox extension anymore.
This extension is very important to me so I want to ask you if there is a way to get it to work with uBlock or (at least) how to import custom rules created by Element Hiding Helper and use them by uBlock
Thank you!

**Comment by Snapy** [comment]
Read the wiki (search for "element picker" : it's what you're looking for).

**Comment by MED-PRO** [comment]
Got it, Thanks!
