### ISSUE TITLE
Suggest new specific and customizable «inline-script» filter

### ISSUE THREAD

**Issue by nestarz** [uBlock-LLC/uBlock#1354]
Currently, inline-script filter blocks everything, but would it possible to aim some specific script like, for example, anti-adblock inline-script ?

Maybe like adguard do (see http://adguard.com/en/filterrules.html#javascriptInjection)

However, thanks for your incredible work !

**Comment by davidhedlund** [comment]
@chrisaljoudi One way to block inline scripts as long as the lines above the generated HTML page remains intact, would be to specify which lines to block.
