### ISSUE TITLE
Help With Element Picker?

### ISSUE THREAD

**Issue by MED-PRO** [uBlock-LLC/uBlock#1355]
Hello & thank you for your great work!
I have started using element picker and I noted that when I hide an element on a page of a website (I.E: an article of a blog) , it applies only to the current URL while the other pages stay unaffected. 
(seems like the created rule applies to a specefic URL of the domain only) 
so how can I apply the rule to all the pages of the same domain? 
I hope my question is clear, thanks for your time!

**Comment by ghost** [comment]
https://github.com/chrisaljoudi/uBlock/blob/master/CONTRIBUTING.md#always-include-a-url

**Comment by Speravir** [comment]
Sorry, but if I would be one of the developers I would consider this as “not an issue” or as “won’t fix”:

For every cosmetic filter there’s a comment with date, time and full address (the URL) for you to see when it was created and from where. But on the _active filter line only the full domain_ is used. In your case it is quite probably something with `blogname.blogcompany-site.tld` (tld is com or net, I guess).  
So to get your filter applied for the whole `blogcompany-site.tld` you only have to remove the first part `blogname.` (note included period).

<sup>_(An even more harsher answer would be: **RTFM**.)_<sup>
