### ISSUE TITLE
Help with the rule please

### ISSUE THREAD

**Issue by fedorvinogradov** [uBlock-LLC/uBlock#1356]
Is it possible to block ads in the beginning of the video located on the page: http://worldcrisis.ru/crisis/1911970
The video originates from http://videochart.net/ and http://moevideo.net/ (I'm not sure but maybe they take videos from youtube).

**Comment by AlexW-13** [comment]
Try: ||adriver.ru^

If that doesn't work, I'll look again in the morning when I'm more awake.

**Comment by fedorvinogradov** [comment]
@weakptr this worked flawlessly, thanks a lot.

If it is possible could you please help a little deeper with other ads in this video which appears from 6 to 8 seconds from start and in the end of the video?

**Comment by lewisje** [comment]
Look in the Network View in the Web Inspector for HTTP requests that happen while the ads are running, to try to find some pattern for the ads (this can be very hard to do, and sometimes there is no reasonable pattern that hits the ads but not the video content).

**Comment by fedorvinogradov** [comment]
@lewisje thanks for the answer.
I solved the issue by adding these filters: ||videochart.net^ and ||moevideo.net^.
And now it is just a normal youtube video.
It looks like an ads provider puts an advertisement layer on youtube videos with some script.
