### ISSUE TITLE
Placeholders for blocked elements are sometimes not hidden

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1357]
I added the following filters:

```
||agar.io/blocker.png
agar.io###helloDialog > hr:nth-of-type(2)
```

Often when I load the site, the placeholder for `blocker.png` still shows up, and I need to reload the page to make it go away.

**Comment by chrisaljoudi** [comment]
Fixed in a9e77b4d48.

Thank you for reporting this.
