### ISSUE TITLE
Some tabs opened with middle click are immediately closed when ublock is running.

### ISSUE THREAD

**Issue by finbreaker** [uBlock-LLC/uBlock#1358]
I notice this issue primarily when middle clicking articles in my RSS feed.  I have confirmed that disabling ublock stops this from occurring, but this is obviously not an optimal solution.

**Comment by finbreaker** [comment]
I have whitelisted my rss reader URL and this does work around the issue.  Not sure if I'd call that a solution though.

**Comment by gorhill** [comment]
So little details in your issue report... See https://github.com/chrisaljoudi/uBlock/blob/master/CONTRIBUTING.md#what-to-include.

Maybe: https://github.com/gorhill/uBlock/issues/173.
