### ISSUE TITLE
[Suggestion] List blocked requests in extension menu

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#136]
Absolutely great work on the extension! I only have a feature request so far: It'd be nice if logging for blocked requests is enabled then the popup menu would list them in a compact way. So we wouldn't  have to navigate all the way to the statistics page.

**Comment by mikhaelkh** [comment]
@LightningW you can click on the eye in popup window to jump to list of requests directly.

**Comment by gorhill** [comment]
Dup of #75.

This would go beyond what I want uBlock to be, and no doubt would lead to feature creep, as users would thereafter want to be able to enable/disable specific filters through point and click in the popup menu, etc. etc. and in the end,  all the efficiency of uBlock, its defining feature, would be greatly diminished.
