### ISSUE TITLE
The filter rules can not be updated automatic

### ISSUE THREAD

**Issue by WoodyLin** [uBlock-LLC/uBlock#1361]
```
 The filter rules can not be updated automatic，and I had checked the "automatic update rules" box. 
 Everytime I have to clear the rules cache, and renew the rules manually.
```

Thx a lot.

**Comment by davidhedlund** [comment]
I was actually just about to report the exact same issue. It makes it impossible to know which filters that have been updated since you have to "Purge all caches" and then click "Update now" which will update all filters.

**Comment by chrisaljoudi** [comment]
I'm afraid I don't understand what the issue being reported is.

What's the symptom? Why do you think the filter lists aren't being updates automatically?

**Comment by davidhedlund** [comment]
@chrisaljoudi Because the "Update now" button is passive (not possible to click on) even if new updates are available. This makes the tile a little bit different ("The filter rules can not be updated") but still related.
