### ISSUE TITLE
Exception rules do not work well in ublock, compared to ABP

### ISSUE THREAD

**Issue by enerai** [uBlock-LLC/uBlock#1363]
In http://www.thisav.com/video/138713/%9F%93%9C%8B%80%84%9F%8C%98%9F%81%87%96.html, the adblocker-killer should be invalid by these three additional exception rules (with the default filter subscriptions):

@@||thisav.com^$elemhide
@@||thisav.com^$image
@@||ad.thisav.com/player/config.xml

ABP is able to work it well. However, in ublock, even if these rules are set, the adblcoker-killer is still valid.

**Comment by chrisaljoudi** [comment]
Fixed in e06faa9 — thanks for reporting this!

**Comment by enerai** [comment]
If the rules (in previous version) is not reset, they would not be valid.

Test link: http://www.thisav.com/video/135022/%E6%AF%8E%E6%97%A510%E7%99%BA%E4%B8%AD%E5%87%BA%E3%81%97%E3%81%99%E3%82%8B%E3%81%BE%E3%81%A7%E7%B5%82%E3%82%8F%E3%82%89%E3%81%AA%E3%81%84%E7%B2%98%E7%9D%80%E3%82%AA%E3%83%A4%E3%82%B8%E3%81%A8%E6%BF%83%E5%8E%9Asex-.html
