### ISSUE TITLE
Unnecessary space

### ISSUE THREAD

**Issue by extrajoker** [uBlock-LLC/uBlock#1364]
I use Google Chrome.
Unnecessary space is shown to the bottom.
![ublock](https://cloud.githubusercontent.com/assets/12291432/7510241/f948cc00-f4d4-11e4-9945-b0067b71e468.jpg)

**Comment by lewisje** [comment]
There should be some icons on the right side of that space, exactly below the "domains connected" counter; the absence of those icons is the real problem, and it could be a problem with localization.

**Comment by extrajoker** [comment]
I know that there are some icons in uBlock Origin.
Are there some icons in uBlock?

This problem does not occur with Mac Chrome, only Windows Chrome.

**Comment by chrisaljoudi** [comment]
@lewisje @extrajoker that's correct — only uBlock Origin has those icons.

I'll investigate.
