### ISSUE TITLE
Safari forgets my filters after restart

### ISSUE THREAD

**Issue by purplealert** [uBlock-LLC/uBlock#1365]
If I block elements from a webpage then the next time the browser is restarted the 'my filters'  tab of the dashboard is cleared and I have to start again.  This happens with OS X 10.10.x and Safari 8.x, possibly others but I haven't tested them.  It also appears to happen with any filter I set, they all get cleared.  Example filters:

www.theregister.co.uk###RegCCO
www.bbc.co.uk###bbccookies

There's an obvious workaround in that I can save my filters and reload them at the start of a new browsing session, but this isn't ideal.

**Comment by ghost** [comment]
I have been able to reproduce your issue. Randomly losing settings after some browser shutdowns, without having done anything to clear/erase settings! Not sure why it happens.

See this related issue (cache/history clearing loses all settings):
#1366

**Comment by purplealert** [comment]
Hello,

I installed the latest release 0.9.5.0 earlier today and I'm delighted to report that you appear to have completely solved the settings storage issue with Safari.  My initial testing, although limited, has found no issues with this at all.

I sincerely appreciate your effort in fixing this, uBlock is a superb piece of software.

Many thanks.
