### ISSUE TITLE
count badge's position moves on safari

### ISSUE THREAD

**Issue by zanderzhng** [uBlock-LLC/uBlock#1367]
![screen shot 2015-05-08 at 8 13 31](https://cloud.githubusercontent.com/assets/867749/7527765/231763c2-f55a-11e4-8144-c0d0d15e6321.png)
![screen shot 2015-05-08 at 8 13 36](https://cloud.githubusercontent.com/assets/867749/7527766/2358a3f0-f55a-11e4-95c6-78be2fb567a9.png)

in new tab, the badge's position was like the first pic, but it moves when switching tabs, like the second pic.

**Comment by chrisaljoudi** [comment]
Yep, I've noticed this. I think it's a Safari bug (there's no way to control the badge position programmatically that I know of).

**Comment by chrisaljoudi** [comment]
I figured out a workaround (it is indeed a Safari bug) — https://github.com/chrisaljoudi/uBlock/commit/df8c82f6b4e46d7325d91090000bf6ac67c5fbfb. Yay.

**Comment by zanderzhng** [comment]
Works great, thank you :)
