### ISSUE TITLE
Can redirect messages be used as in RequestPolicy

### ISSUE THREAD

**Issue by flyingzebras** [uBlock-LLC/uBlock#1368]
![rgb](https://cloud.githubusercontent.com/assets/11916082/7534560/f9aca016-f57b-11e4-9a7f-5f35be5d8bf5.png)

 RequestPolicy 0.5.28 asks if both popups and redirects should be visited (a feature that has been withdrawn in RequestPolicy Continued starting with version 1.0). This is useful to debug popups as they often are redirected.

**Comment by SilenceEngaged** [comment]
Uh. lolwut.

**Comment by flyingzebras** [comment]
@astcraft try reading again.

**Comment by ghost** [comment]
This is actually a feature of Firefox itself.

Options -> Advanced -> General -> Accessibility -> Warn me when websites try to redirect or reload a page

**Comment by davidhedlund** [comment]
@nyuszika7h I didn't know that. Thank you for telling me about it.

**Comment by vzjrz** [comment]
@nyuszika7h Even with that setting turned on a visit to https://youtu.be/btUXT9p1fUQ does not give me a warning and goes ahead and redirects to https://www.youtube.com/watch?v=btUXT9p1fUQfeature=youtu.be with RequestPolicy this doesn't happen.

**Comment by davidhedlund** [comment]
@vzjrz I experienced the same thing with other site too. The add-on NoRedirect can be used also.
