### ISSUE TITLE
Please add a Element picker shortcut

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1370]
That will save much time for anyone using uBlock.

**Comment by 5t3f4n** [comment]
Good idea. It would also allow users who prefer not to have toolbar icons to use the element picker.

Perhaps the same keyboard shortcut as Adblock Plus uses can be used?
uBlock users probably don't use ABP also, and it would be convenient for switchers.

**Comment by gorhill** [comment]
Dup of #256.

**Comment by davidhedlund** [comment]
This project is dead, use [uBlock Origin](https://github.com/gorhill/uBlock/issues) instead.

This issue is not relevant any more.
