### ISSUE TITLE
Global "allow images" taking precendence over user filters ?

### ISSUE THREAD

**Issue by Betsy25** [uBlock-LLC/uBlock#1373]
Hi, I have global allow images enabled, and I have this item in my filters list : 
`||http://www.futbol24.com/i/live/ico_tv.gif`

yet on the site http://www.futbol24.com/Live/ the ico_tv.gif images all show up.

Is it normal that our filters do not have precendence over global rules ?

**Comment by ghost** [comment]
https://github.com/chrisaljoudi/uBlock/wiki/Dynamic-filtering:-quick-guide

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Overview-of-uBlock's-network-filtering-engine

**Comment by chrisaljoudi** [comment]
@Betsy25 yep. As a tip, you might want to use the `noop` global option (gray) instead of `block` in Dynamic Filtering, which basically means "preliminarily allow this request; let it go through to the static filtering engine" (which then looks at your filter lists).

**Comment by Betsy25** [comment]
@chrisaljoudi Oh great ! I never even though about it that way. Thanks a lot !
