### ISSUE TITLE
safari extension download seems inaccessible

### ISSUE THREAD

**Issue by mybluepig** [uBlock-LLC/uBlock#1376]
safari extension link is down.

link from home is below and currently not working
https://chrismatic.io/ublock/ublock-latest.safariextz

link from apple safari extension page also down (probably same link)

**Comment by chrisaljoudi** [comment]
@mybluepig just tested; seems to work. What's your location, if you don't mind?

Would you please share more details as to what error you're getting?

**Comment by mybluepig** [comment]
Ok here is error message from Chrome Windows
I am at Korea, South and I tried from a few ISP, all of them not working.
I may contact cl.ly for reason

This webpage is not available

ERR_CONNECTION_REFUSED
Hide details
Google Chrome's connection attempt to f.cl.ly was rejected. The website may be down, or your network may not be properly configured.
Go to http://cl.ly/

**Comment by chrisaljoudi** [comment]
@mybluepig alright; I was planning a slight change in storage, so I went ahead and did it now since you're reporting a problem.

Please try out the link https://chrismatic.io/ublock/ublock-latest.safariextz and let me know if that works now.

**Comment by mybluepig** [comment]
It works magically, thanks.

**Comment by lucacri** [comment]
Hi, when trying the url on the website and the one you posted before, i get a 404 error from Nginx (404 Not Found
nginx/1.6.2 (Ubuntu))
