### ISSUE TITLE
PDF link missing on scientific journal pnas.org

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1378]
The popular scientific journal pnas.org is missing a crucial menu near the top ("Abstract Authors & Info SI Metrics Related Content PDF PDF + SI").

Example: http://www.pnas.org/content/early/2015/05/01/1422446112.short

**Comment by gorhill** [comment]
I see them just fine with default settings.

**Comment by ghost** [comment]
easyprivacy - `/fingerprint.js`

`@@/fingerprint.js$domain=pnas.org`

**Comment by jmerkin** [comment]
I had the same issue. Adding pnas.org to the whitelist is a workaround for the time being, but doesn't solve the issue.

**Comment by atajik** [comment]
same problem here. just added pnas.org to whitelist
uBlock may need an option to allow unblocking placeholders
