### ISSUE TITLE
uBlock global user filtering is covered up by some whitespace

### ISSUE THREAD

**Issue by Apolloxic** [uBlock-LLC/uBlock#1379]
A thin block of white covers the red block for global filtering whenever there's so many domains it needs a scrollbar. I just came from uBlock Origin to use the main version of uBlock, so I'm not sure if this is normal or not.

![Here's an image of the might be issue](https://cloud.githubusercontent.com/assets/8453833/7646658/141d7ef0-fb0a-11e4-8592-435f0de801a7.png)

Sorry if this is how it's meant to be. Also this is the beta that was released moments ago.

**Comment by gorhill** [comment]
Browser bug: https://github.com/gorhill/uBlock/issues/108.

**Comment by chrisaljoudi** [comment]
Hi @Evolater!

Thanks for your report — and it appears you're running the beta version (0.9.4.5), so thanks for helping out with testing!

What browser is this occurring on?

**Comment by Apolloxic** [comment]
Firefox 38.0.1; Windows 7 64bit

@gorhill Yeah this seems to be duplicate of that issue. My bad.

**Comment by chrisaljoudi** [comment]
@Evolater hmm. Couldn't reproduce with Firefox 38.0.1 on OS X (but that could be because OS X scrollbars aren't allocated space).

@gorhill it doesn't look like that same bug is supposed to occur in 38.0.1 (which is stable channel right now).

I'll have to see if I can get to test this on Windows.

**Comment by gorhill** [comment]
@chrisaljoudi Yeah given no version of Firefox were given I assumed it was the same bug.

**Comment by chrisaljoudi** [comment]
@Evolater oh, had you manually enabled the flag in question (`layers.async-pan-zoom.enabled`)?

**Comment by chrisaljoudi** [comment]
@Evolater did you manually enable the flag in question (`layers.async-pan-zoom.enabled`)?

**Comment by Apolloxic** [comment]
Aha! Sorry for the delay. But that was somehow enabled. I don't remember touching that. But it was true. Making it false fixed it.

**Comment by chrisaljoudi** [comment]
@Evolater Great; sounds like that's the solution until Mozilla fixes the bug. :)
