### ISSUE TITLE
Disable silent subscriptions update

### ISSUE THREAD

**Issue by mikhaelkh** [uBlock-LLC/uBlock#138]
Is there a way to disable silent subscriptions update and do it by user request? A question to both uBlock and HTTPSb. It is useful when you're using limited internet. If there's no way it would be nice to have it in the future. Also, how to disable fetching subscriptions' files from your remote git repository when using `git pull`? As far as i'm concerned gitignore respects only local changes(

**Comment by gorhill** [comment]
I want to re-code how things work in there:
- Provide a setting as suggested

Also:
- Update lazily, i.e only the lists which are in use: there is no point fetching an update of Fanboy Ultimate if it is not in use.

**Comment by gorhill** [comment]
Taking a bit longer than I expected: I am trying to remove any avoidable overhead (like not pulling from cache if I can know in advance it's not in the cache), and also to foolproof as much as possible error cases (like falling back on cached copy if remote server can't be reached, etc.)
