### ISSUE TITLE
Have a problem with some of the firefox themes.

### ISSUE THREAD

**Issue by lagun** [uBlock-LLC/uBlock#1380]
Hi, chris

Half of the ublock console is missing
http://postimg.org/image/7w821txbx/

walnut theme
https://addons.mozilla.org/en-US/firefox/addon/walnut-for-firefox/

**Comment by AlexVallat** [comment]
It looks like walnut may be doing a lot of messing about with the popup CSS, I can't quite figure out exactly what, though. It looks like it replaces panelUIOverlay.css entirely so it's very had to know what specific changes it is trying to make.

I think your best bet would be to try and raise this as an issue with the theme author, as they are much better placed to know what the problem might be.
