### ISSUE TITLE
Phoronix forums broken

### ISSUE THREAD

**Issue by desbma** [uBlock-LLC/uBlock#1382]
Using uBlock with some filters, the Phoronix forums are broken: blank page instead of the usual page.
Example URL: https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/800597-gnome-3-16-on-fedora-22-wayland-vs-x-org/page2

By disabling all filters, and enabling them one by one, it seems it is [this filter](https://github.com/r4vi/block-the-eu-cookie-shit-list) (source [here](https://raw.github.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt)) that causes the problem. This filter is not present in uBlock by default.

However I have [reported the issue to the author, and he could not reproduce](https://github.com/r4vi/block-the-eu-cookie-shit-list/issues/105).

So I wonder if this is really a filter issue or some other effect of uBlock, which is why I open an issue here too.

**Comment by gorhill** [comment]
I can reproduce using that filter list. There is a `##.cookies` cosmetic in that list, and the `body` element of the page contains the `cookies` class. Hence the whole `body` element is removed.

ABP won't apply that filter. AdBlock, Adguard, uBlock do apply the filter.

I have seen users create cosmetic rules for `body` element, so to exclude the `body` element from cosmetic filtering would not be a good idea.

Workaround, create an exception filter:

```
phoronix.com#@#.cookies
```

**Comment by desbma** [comment]
Thanks a lot, @gorhill.

I'll just add an exception rule.
