### ISSUE TITLE
Old filters

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1384]

**Comment by chrisaljoudi** [comment]
Hi @davidhedlund!

Just out of curiosity, what are some examples of advertisement domains ignored by EasyList?

**Comment by davidhedlund** [comment]
@chrisaljoudi 

||addthis.com^$third-party
||are-ter.com^$third-party
||bannerflow.com^$third-party
||doublepimp.com^$third-party
||dvdcdn.com^$third-party
||ebocornac.com^$third-party
||etahub.com^$third-party

to mention a few.

**Comment by davidhedlund** [comment]
I suggest that we begin to block domains primarily (or only).

**Comment by davidhedlund** [comment]
Can you please label this issue "3rd-party filters" @chrisaljoudi?

**Comment by chrisaljoudi** [comment]
@davidhedlund well, I would be happy to, but this isn't really about 3rd-party filters, is it?

(3rd-party filters are about filters provided by someone who isn't uBlock).

**Comment by davidhedlund** [comment]
@chrisaljoudi Oh snap, I was confused.

**Comment by davidhedlund** [comment]
@chrisaljoudi Currently its not possible to update "uBlock filters – Privacy‎", a filter that is part of uBlock. To make it possible you could place the filter somewhere in your uBlock repository and subscribe to it by default in uBlock. Just make sure that the file is not part of uBlock when you distribute it.

Am I correct about this?

**Comment by davidhedlund** [comment]
@chrisaljoudi So where's this Issue on your priority list?

**Comment by flyingzebras** [comment]
Here's some things not implemented by EasyList per https://forums.lanik.us/viewtopic.php?f=62&t=21495&p=71312:
* ||addthis.com^$third-party
* ||dvdcdn.com^$third-party
* ||tube8.com##.main-wrapper > .content-wrapper > .level-up-popup-wrapper

**Comment by davidhedlund** [comment]
@chrisaljoudi Have you set up any new filters?

**Comment by davidhedlund** [comment]
[mylabel:invalid](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Ainvalid%22+in%3Acomments&type=Issues&ref=searchresults)
