### ISSUE TITLE
Please add ClearRefresh button in Request log

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1385]
It was very confusing to me that, in the Request log, you first have to click on clear before you refresh to get a new list. I thought the Refresh button cleared automatically.

I suggest that you add a new button, ClearRefresh, left to the current Refresth. ClearRefresh first clear the list and then add the current log.

**Comment by RoxKilly** [comment]
While I usually would agree that one click is much better than two clicks from a user experience perspective  to accomplish a task, I disagree with this suggestion.  I can understand that it takes a few seconds to figure out that you need to  CLEAR and then REFRESH  to get a new list, but adding a ClearRefresh button has a real downside. I am worried about bloating the UI with multiple buttons that have overlapping functions. If we go down that road I think it will make uBlock more difficult and confusing to use in the long run.  It would be like having a Word processor with the options "Save, Exit, and Save&Exit" as three separate buttons.

If the CLEAR button was useless by itself, I would agree with you, but there is a use case for wanting to CLEAR the list without refreshing the page.  I do this to observe AJAX (xhr) calls.

**Comment by davidhedlund** [comment]
This project is dead, use [uBlock Origin](https://github.com/gorhill/uBlock/issues) instead.

This issue is not relevant any more.
