### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by MurkBRA** [uBlock-LLC/uBlock#1386]
"TypeError: doc.docShell.getInterface is not a function"
I don't know what is that but keeps showing in my console
![32e8412042](https://cloud.githubusercontent.com/assets/12011370/7668289/47b1f302-fc06-11e4-95eb-607cfe0cbdcf.png)

I'm on firefox 38
uBlock 0.9.4.5 Beta 1 and 0.9.4.0

**Comment by AlexVallat** [comment]
This usually means the uBlock framescript has been injected into a firefox window that is not a browser window. I don't generally see so much of it, though - are you using any other add-ons or features that might be showing sidebars or windows or similar?

Just to confirm, though, it's just these warning messages that you are seeing, uBlock is still functioning correctly in normal browser windows for you?

**Comment by MurkBRA** [comment]
Only thing that I noticed it was a slowness to start hiding the elements of the page.
About sidebars addons "autopager" and "Color That Site!"

**Comment by AlexVallat** [comment]
For information, it seems that AutoPager is the issue here. But given that it seems to be out of date and not officially supported on Firefox 38 anyway I'm not too concerned about it.
