### ISSUE TITLE
Behavior of auto-updating filter lists is unclear

### ISSUE THREAD

**Issue by PlasmaMiasma** [uBlock-LLC/uBlock#1387]
With "Auto-update filter lists" enabled, I see the "outdated" status on filter lists.

What is the frequency of checking for updates to filter lists?
What is the frequency of updating an outdated filter list?
These processes do not appear to be synchronized.

Why not update a filter list immediately after finding an update of it?

**Comment by davidhedlund** [comment]
@ParticleMon This issue is marked as "fixing" in https://github.com/chrisaljoudi/uBlock/issues/1361

**Comment by chrisaljoudi** [comment]
@ParticleMon @davidhedlund correct.

A major restructuring of what the update process looks like from the user's point of view is coming. Release probably in 0.9.5.0.

**Comment by davidhedlund** [comment]
@chrisaljoudi Can you please close this issue and refer to the link I provided above? @ParticleMon will let you know if it should be reopened.
