### ISSUE TITLE
Images, Flash objects or inline scripts [Feature]

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1394]
Are there plans to introduce features to block images, Flash objects or inline scripts?

**Comment by ghost** [comment]
`||example.com^$image,object,inline-script` ?

**Comment by davidhedlund** [comment]
@gwarser Can uBlock block inline javascripts?

Adblock Plus can not.

**Comment by ghost** [comment]
https://github.com/chrisaljoudi/uBlock/wiki/Filter-syntax-extensions

**Comment by davidhedlund** [comment]
@gwarser Thank you very much.

**Comment by davidhedlund** [comment]
@gwarser Can I prevent the second `<script type="text/javascript">` but not the rest?

Or can I prevent specific inline JS code?

**Comment by chrisaljoudi** [comment]
@davidhedlund I believe this is quite similar to what #1354 suggested.

I'm still unclear on what a good way to "identify" specific inline-script blocks would be. Does that make sense?

**Comment by davidhedlund** [comment]
Thank you @chrisaljoudi. Confirming duplicated issue of https://github.com/chrisaljoudi/uBlock/issues/1354
