### ISSUE TITLE
Line blocking [Feature]

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1397]
@chrisaljoudi One way to block inline scripts as long as the lines above the generated HTML page remains intact, would be to specify which lines to block by adding a new predefined variable: $line.

Example of syntax to add to block line 7-46: ||youtube.com^$line=7-14

I'm sure line blocking is even more useful in other circumstances.

**Comment by ialexsilva** [comment]
:+1:

**Comment by seanrand** [comment]
David, that's not a good idea. It would be ridiculously volatile if the page source changes in any way and would result in completely undefined page breakage.
What are the actual use cases you're trying to solve with this?

``` html
<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>

<p>My first paragraph.</p>
<p>My first spam.</p>

</body>
</html>
```

example$line=8

``` html
<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>

<p>My first paragraph.</p>
<!--<p>My first spam.</p>-->

</body>
</html>
```

Now say the page source changes in any way (as it does _very_ often on websites).
For example:

``` html
<!DOCTYPE html>
<html>
<body>
<h1>My First Heading</h1>

<p>My first paragraph.</p>
<p>My first spam.</p>
</body>
</html>
```

Which would result in this:

``` html
<!DOCTYPE html>
<html>
<body>
<h1>My First Heading</h1>

<p>My first paragraph.</p>
<p>My first spam.</p>
<!--</body>-->
</html>
```

Now what?

Again, when you're proposing features, what are the actual use cases you're trying to solve that aren't possible to do right now? Provide actual website links and show us the ads that can't be blocked with what we have right now.

**Comment by davidhedlund** [comment]
@seanrand HTML in `<head>` is updated less frequently than HTML in `<body>`. Therefore customized inline-scripts ( `<script type="text/javascript">`) can be blocked this way. You might want certain inline-scripts to be used but not others.

**Comment by seanrand** [comment]
Content in <head> might change just as often if there are scripts inlined in it.
Believe me, "blocking" based on line numbers in the generated HTML definitely isn't the way to go.

You're probably looking for something like [AdGuard's HTML Filtration rules](http://adguard.com/en/filterrules.html#htmlContentFilter) to block certain inlined scripts.

See also: #1354

**Comment by davidhedlund** [comment]
@seanrand Thank you for your suggestion, it is being discussed in https://github.com/chrisaljoudi/uBlock/issues/1354.

**Comment by flyingzebras** [comment]
Line blocking would be useful in my opinion, it can be used as a work around to the pop-up URL redirection issue described in https://issues.adblockplus.org/ticket/2095#comment:16

Some of the most popular sites require certain `<script type="text/javascript">` inline script portions while other `<script type="text/javascript">` inline scripts on the same site act as malvertiser. @chrisaljoudi @davidhedlund @seanrand

Please read 
- https://en.wikipedia.org/wiki/Pop-up_ad#Inline_scripting
- https://en.wikipedia.org/wiki/Pop-up_ad#URL_redirection
- https://en.wikipedia.org/wiki/Pop-up_ad#Background_URL_redirection

**Comment by davidhedlund** [comment]
This project is dead, use [uBlock Origin](https://github.com/gorhill/uBlock/issues) instead.

This issue is not relevant any more.
