### ISSUE TITLE
Can't update filters in Safari (5/20/15 v0,9.4.0)

### ISSUE THREAD

**Issue by BhamJack** [uBlock-LLC/uBlock#1398]
Same issue as previously closed thread. I just installed uBlock (from uBlock site) and attempting to update filters with the uBlock preferences does nothing but dim the filter preferences page. All OS/Safari software is up to date. It lists most enabled filters as "outdated".  Any suggestions?

**Comment by elisabethallan** [comment]
I'm also seeing this issue, same version of uBlock with Safari 8.0.6.

EDIT: Reinstalling the extension seems to fix this; I can then update the filter lists.

**Comment by allegewhd** [comment]
Encountered same problem with 0.9.4.0 today on safari 8.0.7(I use public beta of yosemite)

**Comment by BhamJack** [comment]
OSX 10.10.3 Safrai 8.0.6   MacBook Pro (Retina, 15-inch, Late 2013)
I tried ininstall / reinstall both Apple Site and uBolck site, with and without killing-starting Safari between uninstall and reinstall. Same symptoms, doesn't work.

**Comment by chrisaljoudi** [comment]
Does this occur with the 0.9.4.5 beta version?

**Comment by BhamJack** [comment]
Have not seen a download for 0.9.4.5 beta - I will try if Iget a link.

**Comment by chrisaljoudi** [comment]
@BhamJack oh, sorry about that — should've included the link:

https://github.com/chrisaljoudi/uBlock/releases/tag/0.9.4.5-beta.1

The downloads (including for Safari) are right there at the bottom.

**Comment by BhamJack** [comment]
Thanks, tried it, nice looking "Update Now" button that goes blue with shadow on mouse-over but when pressed same symptom, page goes into dimmed mode. Clicking any other dashboard tab and returning to 3rd-party filters tab restores page to original state but no luck beyond that. Will either the current release or the beta "automtically" update them at midnight or something to see if functionality works? That could isolate if it is interface or code issue (1st 4 default checked filters say "outdated").

**Comment by niteowl2** [comment]
I am experiencing the same symptoms. Reproducible on Safari 8.0.6 with uBlock 0.9.4.0 and 0.9.4.5 Beta 1.
Reinstalling fixes the issue only temporarily on 0.9.4.0. Upon closing/reopening Safari and trying to force an update, the issue is still present. As well as after clearing history and cache. 
The filters also do not update automatically if left alone.

**Comment by drpoutine** [comment]
can confirm the same bug on both 0.9.4.0 and 0.9.4.5 beta 1 
when you press apply changes nothing happens. still trying to figure out a workaround but the best one would be to just use chrome for now.

Running Yosemite 10.4 with Safari 8.0.7 

EDIT: so i installed the extension from the apple gallery and that one seems to work just fine which is weird 0-0 its reporting version 0.9.4.5 on ublock. try to give it a try for those who it isn't working for
