### ISSUE TITLE
Unity web player behind an ad does not load with extension turned on

### ISSUE THREAD

**Issue by SirBraneDamuj** [uBlock-LLC/uBlock#140]
Browser: Google Chrome Version 36.0.1985.125 m

uBlock version: µBlock 0.3.2.1

http://www.cartoonnetwork.com/games/adventuretime/adventure-time-battle-party/

This is the game I tried. With the extension disabled, an ad plays for 30 seconds and then the game loads up. With the extension enabled, a black box appears and neither an ad nor the game will display.

Note that by "disabled" I mean that I clicked the power button to whitelist the page.

I have built the extension manually from source at commit b260fb77d8cecb2912638b829779091fbd0ca4e1 and the issue persists.

**Comment by gorhill** [comment]
Each time I enter the link above, I am being redirected to http://www.cartoonnetwork.ca/tv/adventuretime/games/, regardless uBlock is active or not. For some reasons I can't get to this game.

**Comment by gorhill** [comment]
Ok I see, I need to install Unity web player. Will do it in VM/Windows 7.

**Comment by gorhill** [comment]
Well, no matter what I do, each time I go to http://www.cartoonnetwork.com/games/adventuretime/adventure-time-battle-party/, I end up on http://www.cartoonnetwork.ca/tv/adventuretime/games/, despite Unity web player being installed, as if the page doesn't exist. I can't investigate until I can finally land properly on http://www.cartoonnetwork.com/games/adventuretime/adventure-time-battle-party/. Is this a page just for members or something like that? Even looking directly in the catalog of games I don't see a game titled "Battle Party" listed in there.

**Comment by SirBraneDamuj** [comment]
It might be a USA only game now that I think about it.

On Thu, Aug 7, 2014 at 11:02 AM, Raymond Hill notifications@github.com
wrote:

> Well, no matter what I do, each time I go to
> http://www.cartoonnetwork.com/games/adventuretime/adventure-time-battle-party/,
> I end up on http://www.cartoonnetwork.ca/tv/adventuretime/games/, despite
> Unity web player being installed, as if the page doesn't exist. I can't
> investigate until I can finally land properly on
> http://www.cartoonnetwork.com/games/adventuretime/adventure-time-battle-party/.
> Is this a page just for members or something like that? Even looking
> directly in the catalog of games I don't see a game titled "Battle Party"
> listed in there.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gorhill/uBlock/issues/140#issuecomment-51483911.

## 

_Zachary Thacker_
zpthacker@gmail.com
Cell: 410-458-5072

**Comment by gorhill** [comment]
I think it would be great if another developer from US could investigate this one.

**Comment by gorhill** [comment]
The only obvious difference with ABP out of the box is Peter Lowe's list. Did you try to deselect it (and then click "Apply changes")?

**Comment by SirBraneDamuj** [comment]
I have not tried that. I can give it a try tonight when I get home from
work.

On Thu, Aug 7, 2014 at 11:05 AM, Raymond Hill notifications@github.com
wrote:

> The only obvious difference with ABP, is that Peter Lowe's list. Did you
> try to deselect it (and then click "Apply changes")?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gorhill/uBlock/issues/140#issuecomment-51484427.

## 

_Zachary Thacker_
zpthacker@gmail.com
Cell: 410-458-5072

**Comment by SirBraneDamuj** [comment]
I disabled that list. This time, the ad loaded (and subsequently, the game).

On Thu, Aug 7, 2014 at 11:06 AM, Zachary Thacker zpthacker@gmail.com
wrote:

> I have not tried that. I can give it a try tonight when I get home from
> work.
> 
> On Thu, Aug 7, 2014 at 11:05 AM, Raymond Hill notifications@github.com
> wrote:
> 
> > The only obvious difference with ABP, is that Peter Lowe's list. Did you
> > try to deselect it (and then click "Apply changes")?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/gorhill/uBlock/issues/140#issuecomment-51484427.
> 
> ## 
> 
> _Zachary Thacker_
> zpthacker@gmail.com
> Cell: 410-458-5072

## 

_Zachary Thacker_
zpthacker@gmail.com
Cell: 410-458-5072

**Comment by SirBraneDamuj** [comment]
Actually, scratch that. I forgot to re-enable the extension on the page. I
re-enabled it and the game is still blocked.

On Thu, Aug 7, 2014 at 6:23 PM, Zachary Thacker zpthacker@gmail.com wrote:

> I disabled that list. This time, the ad loaded (and subsequently, the
> game).
> 
> On Thu, Aug 7, 2014 at 11:06 AM, Zachary Thacker zpthacker@gmail.com
> wrote:
> 
> > I have not tried that. I can give it a try tonight when I get home from
> > work.
> > 
> > On Thu, Aug 7, 2014 at 11:05 AM, Raymond Hill notifications@github.com
> > wrote:
> > 
> > > The only obvious difference with ABP, is that Peter Lowe's list. Did you
> > > try to deselect it (and then click "Apply changes")?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/gorhill/uBlock/issues/140#issuecomment-51484427.
> > 
> > ## 
> > 
> > _Zachary Thacker_
> > zpthacker@gmail.com
> > Cell: 410-458-5072
> 
> ## 
> 
> _Zachary Thacker_
> zpthacker@gmail.com
> Cell: 410-458-5072

## 

_Zachary Thacker_
zpthacker@gmail.com
Cell: 410-458-5072

**Comment by gorhill** [comment]
Did you try with **only** _EasyList_ + _EasyPrivacy_, all other lists unselected? (_"Apply changes"_ absolutely needs to be clicked after changing the list selection).

Need a developer in the US to find out why it doesn't work with uBlock while it does with ABP when using same filter lists (_EasyList_ + _EasyPrivacy_).

**Comment by gorhill** [comment]
I have fixed many bugs since my last comment, and some of them could have been behind the bug here. Could you check whether the issue still exists? Thanks. (Try to use only the filter lists with which ABP works for that particular case, which may requires to de-select default filter lists in uBlock, i.e. _EasyPrivacy_, _Peter's Lowe_.

**Comment by SirBraneDamuj** [comment]
Tried again using the following lists:

uBlock filters
EasyList

Problem still happens. Neither the ad nor the game display.

If I turn off EasyList, the ad plays and the game loads normally.

On Fri, Sep 5, 2014 at 6:12 AM, Raymond Hill notifications@github.com
wrote:

> I have fixed many bugs since my last comment, and some of them could have
> been behind the bug here. Could you check whether the issue still exists?
> Thanks. (Try to use only the filter lists with which ABP works, which may
> requires to de-select default filter lists in uBlock, i.e. _EasyPrivacy_, _Peter's
> Lowe_.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gorhill/uBlock/issues/140#issuecomment-54622704.

## 

_Zachary Thacker_
zpthacker@gmail.com
Cell: 410-458-5072

**Comment by gorhill** [comment]
I find this depressing.

So many people ask for things, while on the other hand I just need _one developer_ from the U.S. to _investigate_ -- not fix -- why the problem here, and since I labelled the issue "help wanted" four weeks ago not one single person offered to investigate. No need to know the code, just finding out which net requests is allowed/blocked by ABP while blocked/allowed by uBlock.

**Comment by xPoison** [comment]
@gorhill you could use a 2 way proxy and see the problem yourself.

**Comment by harshanvn** [comment]
I am not sure how much help this could be, i am from India.
I installed unity web player, but could not run in Chrome, for reason it does not detect and provides me a link to install it.
So, tried in firefox and captured the logs for Adguard Extension. uBlock logs from Chrome (note with ~~ABP~~ uBlock in chrome, i get black window, whereas in ~~uBlock~~, it offers me to install unity player)..
http://www.megafileupload.com/en/file/563251/logs-rar.html

**Comment by ghost** [comment]
Chrome 37.0.2062.103, default profile settings.
µBlock 0.5.6.0

The problem is Easylist Privacy. Disable that and the game works from within the US.

**Comment by gorhill** [comment]
@harshanvn Is HTTPSB running, and if so, is UA spoofing enabled?

@thesimplecomputer I am confused then. @SirBraneDamuj said above it didn't work with uBlock with only _EasyList_ + uBlock filters ([link](https://github.com/SirBraneDamuj)).

If it is confirmed _EasyPrivacy_ is interfering, ideally having an exception for whatever blocked net request which is needed would be better than turning off _EasyPrivacy_ everywhere.

**Comment by ghost** [comment]
Seems I spoke too soon. Checking through it again, first of all Chrome wanted me to allow all plugins on the Cartoon Netwok page this time which was weird since it was a totally fresh profile, but then the game worked with both EP and EL disabled, sometimes with only EL disabled.

Whitelisting cartoonnetwork.com meant the game worked WITH both Easylist filters enabled.

@gorhill , I have a Blocked Item log from the page. If you want to see it, where would be the best place to put it? It's only 10 elements and looks like there's only one script which is the culprit.

**Comment by gorhill** [comment]
@thesimplecomputer What I would want is the net request log of uBlock + _EasyList **and** the net request log of ABP + _EasyList_, so that I can compare the difference. Since ABP does not provide a net request log, if I could debug myself I would:

launch **only** uBlock + _EasyList+, use the dev tools _Network_ tab, ensure cache is disabled, then load the page, right-click somewhere in the _Network_ pane, then click _Copy All as HAR_, and paste the result in a text file.

Then repeat above but with **only** ABP + _EasyList_. Then I will be able to see the difference, if any.

There has to be a difference between both extension, I am curious as to what it can be. But there is a dead-lock bug out there (#205) which occurs with uBlock, but not ABP (because they work differently internally), and I am starting to wonder if this is this bug showing up. I still need to file with Chromium devs.

**Comment by ghost** [comment]
@gorhill  Have log results, where do you want it all? Skimming through them, there's location info inside so don't want to dump here. Click my name to get my email unless you've got another idea.

**Comment by gorhill** [comment]
Thanks. You can send the logs to my email: http://pgp.mit.edu:11371/pks/lookup?search=0x761470C2

**Comment by harshanvn** [comment]
> Is HTTPSB running, and if so, is UA spoofing enabled?

I do not believe HTTPSB is running for this site. I will double check this tonight.
And i do not have UA spoofing enabled.

**Comment by gorhill** [comment]
From the logs sent to me, the issue does have the hallmark of issue #205. Will need to confirm with the next release.

**Comment by gorhill** [comment]
Issue #205 was fixed with version 0.6.2.0. Unsure whether it is related, but someone sent me the HAR output, and the look of it did resemble issue #205. Could somebody check whether the issue is still there with 0.6.2.0? Thanks in advance.

**Comment by harshanvn** [comment]
I tried with 0.6.2.0, and the behavior is same as ABP, which was not before. 
i.e., both are offering me to install unity player now, not a black window as happened before with uBlock.
So, i think it should be working now. maybe original poster can test it and see..

**Comment by SirBraneDamuj** [comment]
Original submitter here! I will test this when I get home from work today.

**Comment by arcaneAgilmente** [comment]
Heh, I knew what this was going to be about the second I saw it, I spent a while with this one a few days ago and finally got it working.

Add these to your blocklist. (The adultswim one is optional)
http://ht.cdn.turner.com/adultswim/big/ads/*
http://ht.cdn.turner.com/toon/big/ads/*

and this to your whitelist:
http://bea4.v.fwmrm.net/crossdomain.xml

**Comment by SirBraneDamuj** [comment]
Hi, sorry for the delay. I had a bit of a crazy weekend. "...when I get
home from work today" sorta never happened so I'm just now getting to this.

I manually installed the latest release (0.6.3.2) and the game works now!
It loads similarly to how it loaded with ABP. Great work!

On Mon, Sep 22, 2014 at 7:51 PM, AratnitY notifications@github.com wrote:

> Heh, I knew what this was going to be about the second I saw it, I spent a
> while with this one a few days ago and finally got it working.
> 
> Add these to your blocklist. (The adultswim one is optional)
> http://ht.cdn.turner.com/adultswim/big/ads/*
> http://ht.cdn.turner.com/toon/big/ads/*
> 
> and this to your whitelist:
> http://bea4.v.fwmrm.net/crossdomain.xml
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gorhill/uBlock/issues/140#issuecomment-56460775.

## 

_Zachary Thacker_
zpthacker@gmail.com
Cell: 410-458-5072

**Comment by gorhill** [comment]
Great to hear. So it was that dead-lock bug. It is also affecting some users who may have a combination of extensions, like Adblock Plus and LastPass -- as I've read over at ABP forum.

@AratnitY: these shouldn't be necessary -- since ABP didn't suffer the freeze problem. Maybe you are using Chromium 39? (There is another serious bug affecting Chromium 39 which breaks plug-in filters).

**Comment by arcaneAgilmente** [comment]
@gorhill Nope I'm on Google Chrome 37, I disabled the filters and the game loads just fine! Thanks!
