### ISSUE TITLE
Music play area missing with uBlock

### ISSUE THREAD

**Issue by tobbi** [uBlock-LLC/uBlock#1402]
Go to http://www.ndr.de/ndr2/wir_sind_die_freeses/Wir-sind-die-Freeses-beruehmt-auf-Zeit,audio243710.html 

With uBlock enabled, you don't see the area with the Play button that is supposed to play the episode. If you disable uBlock, it works fine.

**Comment by ghost** [comment]
Easyprivacy `||imrworldwide.com^$third-party`
Please report here https://forums.lanik.us/viewforum.php?f=64
