### ISSUE TITLE
Issue blocking Social Media buttons on slashdot.org

### ISSUE THREAD

**Issue by dinkc64** [uBlock-LLC/uBlock#1404]
The social media buttons are shown for a .5 to 2 seconds after a story loads on slashdot.org when the social 3rd party filters are enabled (or I create a custom one).
How to reproduce: 
1: enable the 3rd party social media filters
2: go to http://slashdot.org with the browser maximized so that you can see below the news entry, where the buttons reside.
3: load some news entries, and watch the social media buttons appear, then disapear.
I was hoping that they wouldn't be shown at all / to begin with when the filter is enabled :)

thanks for the great blocker!

**Comment by ghost** [comment]
https://github.com/chrisaljoudi/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F#cosmetic-filters

Look for 'Generic' and 'Cached generic'

**Comment by dinkc64** [comment]
Thanks for clarification,
best regards,
- dink
