### ISSUE TITLE
Enabling blocked text selection

### ISSUE THREAD

**Issue by gituporabnik** [uBlock-LLC/uBlock#1407]
I found a website where there is no way to select text and open a right-click (context) menu within Mozilla Firefox:
http://zelenisvet.com/

I believe this is not an uBlock issue, however I would like to know if there is a way to unblock it with any uBlock filter.

Thank you!

**Comment by seanrand** [comment]
Blocking inline scripts seems to prevent context menu/text selection hijacking on that site. Might cause other breakage, though.
