### ISSUE TITLE
Site Breakage - cnet.com/news/

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#141]
Looks like ||tags.tiqcdn.com^ is blocking a script that causes the main three panels from 'expanding' or 'growing' upwards when you mouse over them. I temporarily added @@||tags.tiqcdn.com^ to my list to test and reloaded the page and then it worked as expected.

Ideally we'd just allow that one script only for the cnet.com domain.

```
script  http://tags.tiqcdn.com/utag/cbsi/cnetglobalsite/prod/utag.js    ||tags.tiqcdn.com^
```

Also allowing this script appears to cause uBlock to then block several more things, but that doesn't seem to cause anymore breakage.

Up to you on this one, the breakage isn't really that bad... but it's breakage.

**Comment by gorhill** [comment]
You have MVPS HOSTS selected?

**Comment by crssi** [comment]
I don't think this is the case anymore after 7 years.
