### ISSUE TITLE
Social buttons do not get blocked.

### ISSUE THREAD

**Issue by Corsleutel** [uBlock-LLC/uBlock#1415]
Social buttons which do get blocked by Adblock, do not get blocked by úBlock. For example nu.nl, http://www.nu.nl/voetbal/4058406/blatter-wil-imago-fifa-verbeteren-prins-ali-pleit-veranderingen.html, social buttons on the bottom of the news article. 

I have  Fanboy’s Social Blocking List‎ turned on, of course. 3.425 out of 3.426 in use though.

Other than that it's great, seems much better than Adblock!

**Comment by ghost** [comment]
> ! Title: Fanboy's Social Blocking List
> ...
> ! Please report any unblocked content or problems by email or in our forums
> ! Email: easylist.subscription@gmail.com
> ! Homepage: https://easylist.adblockplus.org/
> ! Forums: https://forums.lanik.us/

**Comment by ghost** [comment]
@gwarser

> do get blocked by Adblock, do not get blocked by úBlock

**Comment by ghost** [comment]
![sc](https://cloud.githubusercontent.com/assets/886325/7898199/afc655d0-06f8-11e5-8a9d-8250ca5e90d8.png)
I see only these two in uBlock, uBlock Origin and Adblock Plus.
