### ISSUE TITLE
uBlock can be detected by checking the width of a blocked element

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1418]
It appears to be possible to detect uBlock by simply checking if the blocked element's width 0.

**OS:** Windows 8.1
**Browser:** Firefox Beta 39.0
**uBlock version:** uBlock 0.9.4.5 Beta 1, uBlock Origin 0.9.8.2-rc.1

You can see a demonstration [here](http://cadoth.net/~nyuszika7h/adblock-detect/). Make sure you have EasyList (or Fanboy's Ultimate List) enabled, or add the following filter manually: 

```
-img/ads/
```

 _**Update:** It seems this also works with Adblock Plus._

**Comment by hairycactus** [comment]
I have EasyList enabled in uBlock, & attempted the said <a href="http://cadoth.net/%7Enyuszika7h/adblock-detect/">demo</a>. The result says: <i>"You do not appear to be using an ad blocker."</i>

So I assume I somehow passed the detection test. However, sites like Softpedia is able to detect uBlock at work. What detection method does it use ?

**Comment by ghost** [comment]
Like I said, it just checks if the blocked element's width is 0. (You can just view the source of the script.) Apparently sometimes it gives false negatives, so try reloading, perhaps even `Ctrl-Shift-R`.

**Comment by hairycactus** [comment]
Ok, I opened the demo page again (still negative result) & reloaded it once. The result is now in red: _"You are using an ad blocker!"_

But every time I restart the browser & revisit that page, it _consistently_ gives a negative result, ie. unless I reload the page. Why do I consistently get a false-negative on every 1st attempt ?

> it just checks if the blocked element's width is 0

Ah, I see. I'd been wondering how Softpedia goes about detecting uBlock. So how to make such detectors think that the width is not zero ? Substitute the blocked element with a 1-pixel transparent dummy element ? (This is a wild guess ... I am not trained in this subject matter.)

**Comment by ghost** [comment]
Not sure why that false negative happens.

I think there's probably a way to pretend that the width of the element hasn't been changed, just like the `display: none ! important;` CSS rule uBlock adds is not visible to scripts loaded on the page.

**Comment by gorhill** [comment]
> Why do I consistently get a false-negative on every 1st attempt ?

Because the (generic) cosmetic filter is injected after the DOM of a page is loaded the first time. It's cached and thereafter  it is injected before the DOM of the page finishes loading.

**Comment by lewisje** [comment]
I don't believe there's a way for an extension to make CSS properties (like `width` and `height` and `visibility` and `display`, all of which can be inspected to infer an ad-blocker) look one way to the layout engine and another way to scripts on the page.

Also, to detect actual blocking, rather than just hiding, there are ways to tell whether a resource was loaded; for example, if it's a script, check for the existence of JS objects made by the script (NoScript allows for "surrogate scripts" to mitigate this problem).

**Comment by ghost** [comment]
@lewisje uBlock actually does seem to hide `display: none` from the page's scripts already.

**Comment by lewisje** [comment]
Do you mean that if a script runs `getComputedStyle` on a uBlock-hidden element, and pulls `display` out of that, it won't get `'none'`?

**Comment by chrisaljoudi** [comment]
@nyuszika7h @lewisje nope. I can't think of a reasonable way to collapse elements and still do that. I suggest turning off element collapsing from uBlock's preferences if you want to prevent pages from using that method.

**Comment by lewisje** [comment]
I didn't think it was possible either, like it's possible to hide the added rule _itself_ (I think that's what Shadow DOM is for) but not the fact that the element was collapsed.

**Comment by Betsy25** [comment]
There are more ways apparently, This one is detecting it also (don't have the knowledge to spit out the "why") : http://www.chromeactions.com/magic-actions-for-youtube-volume-control.html

**Comment by gorhill** [comment]
> don't have the knowledge to spit out the "why"

It looks at whatever matches `.adsbygoogle`, a cosmetic filter in EasyList.

Disabling cosmetic filtering for the page prevents the warning.
