### ISSUE TITLE
uBlock blocking CSS from sites like www.woopra.com

### ISSUE THREAD

**Issue by haythamelkhoja** [uBlock-LLC/uBlock#1421]
Hi,
uBlock is blocking CSS from sites like www.woopra.com by default.

**Comment by 5t3f4n** [comment]
Woopra seems to be some kind of website tracking service, which is precisely what uBlock is designed to let you block, so it's hardly surprising if uBlock catches a thing or two.  <sub>(As a side-note, my uMatrix is blocking the entire domain.)</sub> However, uBlock doesn't block anything you don't tell it to. I recommend you either find what filterlist is responsible for blocking it and unsubscribe from it, or use Dynamic Filtering to whitelist it. If you believe it's wrongfully blocked you can contact the filter maintainer and ask them to remove the filter.

Post your:
- Browser + version
- uBlock version
- Any non-default settings
- Any non-default filterlists
- Any other installed add-ons/extensions

**Comment by haythamelkhoja** [comment]
Hi, I understand that, but why would uBlock disable www.woopra.com's main page rendering CSS.

**Comment by gorhill** [comment]
https://github.com/chrisaljoudi/uBlock/blob/master/assets/thirdparties/pgl.yoyo.org/as/serverlist#L2390
