### ISSUE TITLE
[PaleMoon] At high DPI scaling, button placed in statusbar causes pop-up UI to immediately disappear when shown

### ISSUE THREAD

**Issue by Gittyperson** [uBlock-LLC/uBlock#1423]
Hello and thanks for the amazing extension. Using Pale Moon 25.4.1 x86 and this was an issue with uBlock 0.9.4.0 too. If the uBlock icon is in the Status Bar at the bottom, clicking on it will not make the UI appear properly, it disappears after a split second. It will usually work with the third click and after that it's ok, until a browser restart.
Tested a bit with the icon at the top (near the search and navigation bars), and while on the first click there's a small delay, it seems to work better there. Small video here: https://youtu.be/qi6NKddzvLE

**Comment by AlexVallat** [comment]
I wasn't able to reproduce this, but if you're willing to help investigate then please try it on a clean profile, to see if anything else might be interfering with it. If you could also check if anything is reported in the browser error log when the button is clicked (and it fails to show correctly), that would be useful.

Finally, which OS are you using? PaleMoon has different popup behaviour on Linux from Windows.

**Comment by Gittyperson** [comment]
Thanks, it's Windows 8.1 x64. Tried on a clean profile and it happens again. Nothing on the error log while clicking, but I see several entries there at browser startup, for example:

"Timestamp: 01-Jun-15 21:33:15
Warning: Content Security Policy: The page's settings blocked the loading of a resource: An attempt to execute inline scripts has been blocked
Source File: https://github.com/chrisaljoudi/uBlock/issues/1423
Line: 0
Source Code:
try {  for(var lastpass_iter=0; lastpass..."

and

"Timestamp: 01-Jun-15 21:33:32
Error: ReferenceError: ublock is not defined
Source File: javascript:%20ublock
Line: 1"  (three times this one)

**Comment by Gittyperson** [comment]
I think the problem is my 125% - Medium DPI Windows setting (1680x1050 resolution). Did some tests with the default 100% setting and the problem goes away. On the first click the UI is always a bit slower to render but it always opens fine on 100% and this first-click slowness is unrelated anyway (seems like a cache thing or sth.). Hope you can verify and fix the 125% problem.

**Comment by AlexVallat** [comment]
Thanks for the additional information. That's a good find, with the DPI setting. Unfortunately I still couldn't reproduce it, I tried both 125% and 150% scaling but it made no difference. I hope it isn't a Windows 8 thing, I don't have that available to test on.

The second error in the log you report, "javascript:%20ublock", is very curious. I can't think what might cause that. If I think of a way to narrow it down, I'll get back to you.

Just some blind casting about in hope of clues:
- Does having the Advanced User option turned on make any difference? With the popup area expanded or not?
- Any chance you could check if SeaMonkey behaves in the same way, or if this is something PaleMoon specific?

**Comment by Gittyperson** [comment]
Advanced option makes no difference. Tried a bit with SeaMonkey but don't know if and how I can drag the uBlock icon to the Status/Add-on Bar at the bottom, seems it's not possible with SM. It works ok at the top, but so does in Pale Moon.

**Comment by AlexVallat** [comment]
OK, thanks for letting me know. I'm afraid I'm out of ideas now, but we can leave this issue open for reference. If anyone else encounters the same issue, please post here to say so.

**Comment by Gittyperson** [comment]
I think on ad-heavy sites (gazzetta.gr on the video) the issue is aggravated: http://youtu.be/r5EDfwCXyOY (happens mostly after 0:30)

**Comment by Gittyperson** [comment]
This page gets crazy and the pop-up UI is unusable:

http://www.zdnet.com/article/microsoft-quietly-rewrites-its-activation-rules-for-windows-10/#comments-4183e89d-dfec-42c3-b9b2-93765bc8c80b

Video: http://youtu.be/cKuVGIEyEa0

Pale Moon's Error Console: these errors keep coming without clicking the pop-up.

![errors](https://cloud.githubusercontent.com/assets/7165208/9245798/b02c2788-41af-11e5-8c87-5ede99078c98.jpg)
