### ISSUE TITLE
[Chrome] "Change your privacy-related settings" permission required

### ISSUE THREAD

**Issue by jwalton** [uBlock-LLC/uBlock#1424]
I've read [the why](https://github.com/gorhill/uBlock/releases/tag/0.9.8.2), but if I want this setting unchecked, I can uncheck it myself.

**Comment by macpham** [comment]
+1

**Comment by bradleytaunt** [comment]
+1

**Comment by kerwitz** [comment]
:+1:

**Comment by gorhill** [comment]
@jwalton Essentially what you are asking is for uBlock to lie to users. Users expect uBlock to block network requests, not just data transfer, and as it currently is, _Prefetch_ is turned on by default, which means users would leak their IP address when using uBlock, while they rightfully expect that it is not the case.

**Comment by jwalton** [comment]
As a user, I want ublock to block ads.  I, personally, don't really care about leaking my IP address, and I'd rather have the performance benefits of prefetching; this is a trade off I'm willing to make.  I'd be happy if ublock popped up a warning telling me that this setting was turned on, and I'd get better privacy if I turned it off, but I'm not happy with ublock forcing this setting to a value I don't want.

I'm also not really comfortable allowing a third party plugin access to change my privacy settings - here uBlock is making a change which improves my privacy, but I have no guarantees that future versions of uBlock won't change things in a way that negatively affect my privacy.

**Comment by gorhill** [comment]
> I, personally, don't really care about leaking my IP address, and I'd rather have the performance benefits of prefetching

uBlock is for those who care, and pre-fetching actually does add pointless overhead when the network requests are blocked, which occurs a lot with a blocker: a connection is created and established for data transfer which won't occur for blocked network requests. It's more efficient to prevent the connection to be created in the first place. Any other approach is for placebo blockers.

**Comment by jwalton** [comment]
...  And for those of us who care about the half of my comment you didn't
quote?  This would not be the first time I've been burned by an app that
promised never to do evil with permissions I grant it.

**Comment by Betsy25** [comment]
If Chroming's way of prefetching is messing with your privacy, it's better to question the browser you use instead of the tools you use to keep it from doing so.

**Comment by gorhill** [comment]
> I have no guarantees that future versions of uBlock won't change things in a way that negatively affect my privacy.

That's true for all extensions/addons. It's why when it comes to trust, track record is what matters.

**Edit:** I know other blockers which do not require the _Privacy_ permission, and yet send they themselves your browsing history. You have to look beyond the surface. uBlock, being first to serve users' interests, can actually disclose what other extensions do by giving you access to behind the scene network requests.

**Comment by SomeKittens** [comment]
Ironically, the reason I use uBlock is because it makes browsing faster.  If this project is going to be more privacy oriented (to the point where I'm not allowed to configure things) then I'll need to fork it and make my own.  **I do not want to do this**.  I maintain another complicated Chrome extension (Batarang) and it's happened before.  No one ends up happy.

I'd be delighted to open a PR to allow the user to choose their own option.  uBlock doesn't need to lie to users if it sets a default and then lets the user configure.

**Comment by chrisaljoudi** [comment]
I've setup [a poll](https://chrismatic.typeform.com/to/GOoKBy) to see what the user base thinks as a whole. It's much appreciated if you can fill out the poll.

**Comment by gorhill** [comment]
@chrisaljoudi 

> to ensure all requests

You are confusing _connection_  with _request_.

Prefetching did not allow requests to be made without uBlock blocking them, it allowed a connection to be established, which connection would then be used to send the request if ever it wasn't blocked by uBlock.

Establishing a connection is enough for a remote server to see your IP address, nothing else though. That doesn't seem much, but for a blocker it is important, as this violate users' expectation that the remote server doesn't even get to know they exist at all.

**Comment by Gitoffthelawn** [comment]
@chrisaljoudi I think 2 more options could be added to the poll: "Allow the user to easily toggle the preference via the uBlock UI, with a default of Enabled" and "Allow the user to easily toggle the preference via the uBlock UI, with a default of Disabled".

**Comment by Gitoffthelawn** [comment]
What's the status of this issue in regards to Firefox prefectching (as opposed to Chrome)?

**Comment by chrisaljoudi** [comment]
@gorhill thanks — fixed.

**Comment by dragons4life** [comment]
What does "Prefetch resources to load pages more quickly". do, that he wants the plugin to automatically disable it? is it bad? I have it on, but never had any trouble with it, neither do ads show up with it on.

**Comment by jwalton** [comment]
It's a perceptual performance optimization.  When you load a web page, Chrome might start following links on that page and loading them in the background, before you've actually clicked on anything.  Let's say you search for "Dinosaur movies" on google; Chrome might decide to pre-load the first search result before you actually click on it, since you're probably going to click on it, and this way when you do eventually click on it, it will seem like it loaded faster.

**Comment by gorhill** [comment]
@dragons4life 

Go to https://www.browserleaks.com/whois: except for `HTTP Request Headers`, all the rest can be found from just connecting to the web site, no data transferred.

**Comment by dragons4life** [comment]
So it basically loads the ads as well right? but to be honest I never get to even see the ads.

**Comment by SomeKittens** [comment]
@dragons4life Correct.  At issue here is speed vs. privacy.  When uBlock disables this feature, your IP is not leaked to other parties.  However, things go slower.  Not everyone uses an adblocker for privacy - quite a few of us use it to speed up browsing (giant flash ads don't contribute towards making things go zoom).

**Comment by gorhill** [comment]
> things go slower

Unlikely, what really slows down browsers nowadays is all the crap sites serve, and this is taken care by uBlock. To say prefetching speed up things in the context of a efficient blocker is such an unsupported claim. Of course, without a blocker this may make a difference, but the real solution for slow pages is to cut the crap, a feature the browser itself won't ever support, so they use these fancy features as a crutch.

That prefetching feature in the context of uBlock is overhyped. Hard data is what is needed.

**Comment by dragons4life** [comment]
<s>For some reason, I am still on 0.9.5.0, is there a way to automatically update it? tried removing it and re-adding it back via chrome webstore, but didn't work.</s>

edit: nvm

**Comment by gorhill** [comment]
Well... I really thought it was only about the connection itself, but [as per Google](https://support.google.com/chrome/answer/1385029), it's worst:

> If you turn this setting on in Chrome, websites (and any of their embedded resources) that are prerendered or prefetched may set and read their own cookies as if you had visited them before -- even if you don’t visit the prerendered or prefetched pages after all.

In my testing I didn't see any resource downloaded, but then I may have not tested enough web sites, or maybe Chromium doesn't go that far. So this would make prefetching an even bigger concern than I expected.

**Comment by SomeKittens** [comment]
It's worth noting that there are a slew of negative reviews after this change: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm/reviews?hl=en

Again, I'd rather not see this extension become a nanny state over my privacy controls.  Preload is incredibly useful for aggregators like HN where there may be 1-2 sec latency.

**Comment by gorhill** [comment]
> It's worth noting that there are a slew of negative reviews after this change

I see this as a long term project. My decision will be proven right in the long term. People knee jerking without fully understanding what really went on is not a good reason for me to weaken good privacy habits. There will be a setting next version to re-enable it if you want, but prefetching will always be disabled by default, for all the reasons invoked. My track record is that of not compromising users' interests for the benefits of data miners etc., and disabling prefetching is consistent with this.

**Comment by Gitoffthelawn** [comment]
If Google's support documentation is correct (per gorhill's quote of Google's support site above), that's a seriously nasty feature that IMHO should be disabled everywhere.  Personally, I never use Chrome because I don't trust Google to not make such horrible decisions for their subjects... er, I mean "customers".

**Comment by Radagast** [comment]
'network.predictor.enabled' does something similar in firefox, which is a real privacy killer. Maybe these settings should be ported to uMatrix too, as these connections are not blocked by default when this pref is on (default).

Request Policy Continued are also considering adding this [Add a on/off switch for Firefox Network Prediction in preferences #638](https://github.com/RequestPolicyContinued/requestpolicy/issues/638)

**Comment by Gitoffthelawn** [comment]
@Radagast AFAIK, the 'network.predictor.enabled' feature in Firefox does not have the potential cookies issue that Google tells us that their Chrome browser has (see https://support.google.com/chrome/answer/1385029).

To clarify, is there any reason to believe the Firefox predictor system has the same issues regarding cookies (with or without uBlock)?

@gorhill In Firefox, do uBlock Origin and uBlock block requests made by the 'predictor' engine?

**Comment by Radagast** [comment]
@Gitoffthelawn As far as I'm aware, cookies are not set as they are in Chrome but connections to potentially undesirable sites, like social networks, are made when mousing over a button from these places. 

Firefox also has - 'network.prefetch-next' and 'network.dns.disablePrefetch', which also use bandwidth and may violate privacy. Personally, I have all of these disabled in my user.js but that's not for everyone.

**Comment by jwalton** [comment]
`network.dns.disablePrefetch` is not going to do anything for you, privacy wise.  All your DNS queries go to the same server, and the very first site you visit will cause a DNS query.  And, in all likelihood, your DNS provider is your ISP, and they already know your IP, and your address, and your billing information.  The amount of bandwidth used by DNS prefetching is not going to be significant, either.

**Comment by gorhill** [comment]
> As far as I'm aware, cookies are not set as they are in Chrome

Firefox's [Link prefetching FAQ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ):

> Along with the referral and URL-following implications already mentioned above, prefetching will generally cause the cookies of the prefetched site to be accessed

**Comment by Radagast** [comment]
@jwalton Actually, in addition to causing potentially unwanted connections - [DNS prefetching in browsers](https://blog.secure64.com/?p=367) - dns prefetching can cause dns leaks, which is not ideal for preserving privacy and why it's disabled in tor. Also with email clients, for example thunderbird, it can be used to check message receipt by using embedded urls to different domains.

**Comment by ssorallen** [comment]
Prefetching must send cookies for it to be a useful feature. If the prefetched page has authentication that is maintained by a session cookie, prefetching without the cookies would likely result in wasted requests. The result of the user actually navigating to the prefetched page and sending his or her cookies in the request like normal might result in different content. The browser would have to re-request the page on navigation to ensure the content matches pre- and post-cookies, which negates any benefit of having prefetched.

**Comment by chrisaljoudi** [comment]
**Important update:** I'm not sure how I (and others) forgot to mention this, but uBlock doesn't actually implement the feature yet.

uBlock Origin does, but uBlock **does not yet**. Depending on the poll results and the team's discretion, it may or may not be implemented in a future release.

As of the latest uBlock version (0.9.5.0) it doesn't ask for such permissions.

This is a uBlock Origin issue, not a uBlock issue.

**Comment by jwalton** [comment]
What's the difference between uBlock and uBlock Origin?

**Comment by chrisaljoudi** [comment]
@jwalton Check out https://www.ublock.org/faq/

Don't hesitate to let me know if you have any other questions!

**Comment by jwalton** [comment]
@chrisaljoudi Good to know.  :)  Thanks.

**Comment by Gitoffthelawn** [comment]
@gorhill Thanks for the info and quote re: Firefox.  Very helpful.

@all 
Can prefetching or link predicting on either Firefox or Chrome (or any other browsers for that matter) cause cookies to be CREATED (SET) or MODIFIED (not just read)?

**Comment by chrisaljoudi** [comment]
@Gitoffthelawn [for Chrome, yes](https://code.google.com/p/chromium/issues/detail?id=315878).

**Comment by chrisaljoudi** [comment]
@Gitoffthelawn [and yes for Firefox, too, it appears](https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ#Privacy_implications).
