### ISSUE TITLE
Requested ability to temporarily disable blocking on a per-site basis

### ISSUE THREAD

**Issue by Coldblackice** [uBlock-LLC/uBlock#1427]
Can we get the ability to _temporarily_ disable blocking on a per-site basis? And via keyboard shortcut?

Sometimes I find a site that's not loading all the way, and it'd be great if we could disable blocking temporarily for that site via keyboard shortcut, _without_ having to remember to reenable blocking on that site or remember to check the whitelist to find any you've forgotten to reenable.

**Comment by davidak** [comment]
You can disable blocking per site with the big power button:

![ublock](https://cloud.githubusercontent.com/assets/91113/7963289/3c579128-0a12-11e5-8e6b-b73535a2dfc6.png)

then the uBlock Icon is grey and you see that you have to enable it again.

a keyboard shortcut could be added.

**Comment by Coldblackice** [comment]
Thanks, but the problem is that that's _permanent_ -- at least until it's _manually_ re-blocked again. This makes it tedious if you forget to re-enable blocking for a site. It would be very useful if blocking could be done temporarily, and then if/when the site is accessed the next time, blocking is re-enabled.

In other words, it remembers the blocking as long as that tab is open, but once the tab is closed or the user browses away from the site, the temporary unblocking is removed.

**Comment by Gitoffthelawn** [comment]
I don't know for uBlock, but for uBlock Origin, pressing the power button is not the same as disabling the extension.  Strict blocking is still in full effect, even when the power button is off.
