### ISSUE TITLE
Cannot block resources right from Web Inspector's network request log

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1428]
From https://github.com/chrisaljoudi/uBlock/releases/tag/0.9.5.0

"Firefox now lets you block resources right from Web Inspector's network request log! (To try this out, just right click on an entry in the net-log). Thanks to @AlexVallat from the uBlock team for implementing this feature and what he's been doing to make uBlock awesome on Firefox."

I can't do this. What is the expected changes in the Web UI?

**Comment by AlexVallat** [comment]
Show the Firefox Network inspector (Ctrl+Shift+Q, or select it from the Developer menu), then load a page. The Network inspector will list all the http requests made. You can then right-click on any of these, and a uBlock "Block Element" context menu command should be present.

If it isn't, check that you have the uBlock setting "Make use of context menu where appropriate" turned on.

**Comment by davidhedlund** [comment]
@AlexVallat Ok it works. I expected to see an icon as for ABP installed with Element Hiding Helper for Adblock Plus, but uBlock appear in the context menu instead. What do you think of adding a visible icon as ABP do?

**Comment by AlexVallat** [comment]
I think a context menu entry is a more appropriate place for it. It is a contextual command, and belongs with the others. None of the other toolbar icons relate to the selection in any way.

**Comment by davidhedlund** [comment]
@AlexVallat Thank you.
