### ISSUE TITLE
Consider adding source(s) in Network request log

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1430]
The source that blocks an element can be either 3rd-party filters (files), My filters, or My rules. I think it is a bit confusing to know the source of each filter when I investigate Network request log.

**Comment by Snapy** [comment]
You can know the source that blocks an element by looking at the syntax of the filter/rule.

**Comment by Mikey1993** [comment]
@Snapy No, he means the origin of the rule - the list which it came from.

**Comment by davidhedlund** [comment]
@Mikey1993 That is correct.

**Comment by Snapy** [comment]
So this is duplicate of #43 and #1232.

**Comment by davidhedlund** [comment]
@Snapy Thank you for pointing this out.
