### ISSUE TITLE
Clarification of feature removal

### ISSUE THREAD

**Issue by Gitoffthelawn** [uBlock-LLC/uBlock#1431]
I read an issue either in this repo or gorhill's fork in which gorhill explained that uBlock removed a feature that he considered essential.  I have been searching for that issue in both repo's, but so far, I have not been able to find it.

Can anyone clarify what was removed, the rationale, and the implications?  (Or just point to the issue if it's already been discussed.)

**Comment by Snapy** [comment]
Everything is explained in gorhill/uBlock#38 (especially in [this comment](/gorhill/uBlock/issues/38#issuecomment-96618444))

**Comment by Gitoffthelawn** [comment]
There it is!  Thank you Snapy!

**Comment by chrisaljoudi** [comment]
@Gitoffthelawn the reason the features were (for now) removed is that they had no intuitive, meaningful place in uBlock.

A rework of the popup and the settings UI is coming soon, and I plan to reintroduce the features then in a more coherent manner.

**Comment by Gitoffthelawn** [comment]
@chrisaljoudi Sounds great!  :-)

BTW, I have enhanced the uBlock Origin user interface to improve usability for everyone and also to improve accessibility for persons with limited vision.

It is a CSS overlay called uBlock-Deluxe and is available here:
https://github.com/Gitoffthelawn/uBlock-Deluxe

I designed it for uBlock Origin and have only testing it with that fork.  The only reason for the decision to make it for uBlock Origin was because at the moment that I started creating it, uBlock Origin had some features and bug fixes that looked good to me.  It was a fair amount of work, but I'm open to doing something similar for uBlock (non-Origin).

I have significant experience as a professional usability and accessibility engineer, so this sort of work is second nature to me and I enjoy it.

**Comment by chrisaljoudi** [comment]
@Gitoffthelawn Awesome!

Mind sharing some screenshots highlighting the differences? I don't mean to sound demanding, it's just that I'd love to take an overall look before diving in deeper.

Thank you so much for all the help you're offering and the work you've been putting in!

**Comment by Snapy** [comment]
@chrisaljoudi  A screenshot of the popup is available in the first issue.

**Comment by Gitoffthelawn** [comment]
@chrisaljoudi LOL, given everything you've done, I don't think anyone can call you demanding! :-)

You aren't the first to request screenshots, so I might do it.  The uBlock-Deluxe overlay modifies 8 different screens at this time.  I'm reluctant to make screenshots because the screenshots will get out of date whenever I make improvements.  At the same time, I see the value in them.

There is a screenshot in one of the closed issues on https://github.com/Gitoffthelawn/uBlock-Deluxe and well as a cropped version in https://github.com/gorhill/uBlock/issues/276

The screenshot has some rendering issues in those links, but it's close enough to get a general idea and give you an overall look of the uBlock popup.

I recommend taking uBlock-Deluxe for a test drive.  It's a CSS overlay, so it does not modify any functionality; it only enhances usability and accessibility.  A picture may be worth a thousand words, but hands-on experience is worth a million!  ;-)
