### ISSUE TITLE
Adobe Flash Player is suddenly throwing lots of ActionScript errors on some pages and video ads slipping thru on Safari

### ISSUE THREAD

**Issue by phone8588** [uBlock-LLC/uBlock#1434]
ublock causes Adobe Flash Player to throw lots of ActionScript errors on some pages. For example, currently on techcrunch.com, I am getting a number of errors - which sometimes then lead to flash being disabled. Tried checking with various filters and it is the addon itself that causes the behavior. If ublock is disabled from addons page, then page loads fine.

Error #2044: Unhandled securityError:. text=Error #2048: Security sandbox violation: http://cfiles.5min.com/FlexPlayers/modules/reports/ExtLibReportSystemSS_314.swf cannot load data from http://b.scorecardresearch.com/p?c1=19&c2=1000009&ns_ap_an=ExtLibReportSystemSS_314&ns_ap_pn=as3&ns_ap_pv=17%2C0%2C0%2C188&c12=f6fa80f3bbdbaa622dd596885cc7fb58-cs72&name=start&ns_ap_ec=1&ns_ap_ev=start&ns_ap_device=Adobe%20Windows&ns_ap_id=1433537968423&ns_ap_csf=1&ns_ap_bi=&ns_ap_pfm=PlugIn&ns_ap_pfv=17%2C0%2C0%2C188&ns_ap_ver=unknown&ns_ap_sv=2.1411.03&ns_type=view&ns_ap_gs=1433537968423&ns_ap_res=1920x1080&ns_ap_install=1433537968423&ns_ap_lastrun=0&ns_ap_cs=1&ns_ap_runs=1&ns_ap_usage=0&ns_ap_fg=0&ns_ap_ft=0&ns_ap_dft=0&ns_ap_bt=0&ns_ap_dbt=0&ns_ap_dit=0&ns_ap_as=1&ns_ap_das=0&ns_ap_it=0&ns_ap_lang=en&ns_ts=1433537968423&c7=http%3A%2F%2Ftechcrunch.com%2F&c8=TechCrunch%20-%20The%20latest%20technology%20news%20and%20information%20on%20startups&c9=.
    at com.comscore.metrics::Request/sendRequest()
    at com.comscore.metrics::Request/send_NoCache()
    at com.comscore.utils::MeasurementOp/run()
    at com.comscore.utils::DispatchQueue/dispatch()
    at com.comscore.utils::DispatchQueue/enqueue()
    at com.comscore.utils::DispatchQueue/offer()
    at com.comscore.analytics::Core/doNotify()
    at com.comscore.analytics::Core/notify()
    at com.comscore.analytics::comScore$/start()
    at com.fivemin.utils.reportsystem::ReportSystemStreamSense/init()
    at com.fivemin.utils.reportsystem::ReportSystemStreamSense/process()
    at com.fivemin.utils.reportsystem::ReportSystemsMgr/handleClassLoaded()
    at org.minifx.core.elm::AssetsManager/handleExtLibLoaded()
    at ExternalLibraryMgr/handleLoadComplete()

**Comment by phone8588** [comment]
this seems to be a common issue between ublock and ublock origin - https://github.com/gorhill/uBlock/issues/268

**Comment by chrisaljoudi** [comment]
@phone8588 Hi! Thanks for reporting.

> and it is the addon itself that causes the behavior

If you don't mind me asking, how did you reach that conclusion? The error you posted above is because loading from `b.scorecardresearch.com` failed. The request was appropriately blocked by uBlock. (ScoreCardResearch is an analytics company). I tested TechCrunch, and I see the errors in the console from the various requests getting blocked — all perfectly expected and fine.

That said, this is unexpected:

> which sometimes then lead to flash being disabled

Can you please describe a list of steps to reproduce Flash getting disabled?

**Comment by phone8588** [comment]
re: addon itself causes behavior ... i unselected all the filter lists, purged cache and reloaded the page and still it gave the flash error. 

re: lead to flash disabled... this happens when several action script errors keep popping out on Firefox/Win7 on going on certain websites and then Firefox just asks whether I would like to disable the plugin. 

I just checked and this problem doesn't happen on a mac - probably because how the adobe flash sandbox works on the mac. I am not a developer (more an enthusiast) so my technical skills are rather limited to explain better.

On the same theverge.com page on a mac/Safari I am seeing ads when the videos plays ... no such problem on Chrome or Firefox while using same filters.

**Comment by phone8588** [comment]
"On the same theverge.com page on a mac/Safari I am seeing ads when the videos plays ... no such problem on Chrome or Firefox while using same filters."

were you able to replicate video ads slipping thru on Safari?

**Comment by chrisaljoudi** [comment]
@phone8588 That's because current Safari doesn't let extension block requests coming from plugins (like Flash).

If you disable plugins (Safari -> Preferences, disable plugins), then the page will use HTML5 instead of Flash and uBlock will be able to filter the requests just fine.

**Comment by phone8588** [comment]
Re: Safari: Thanks for the trick! :+1: 

Did you figure anything about the Actionscript error problem - anyway to suppress them on Win7/Firefox?

**Comment by phone8588** [comment]
With Flash 18 upgrade. The problem went away.
