### ISSUE TITLE
Allow tasks to be performed that require only limited filtering (even better than disable/enable)

### ISSUE THREAD

**Issue by Gitoffthelawn** [uBlock-LLC/uBlock#1435]
I just posted a comment in https://github.com/gorhill/uBlock/issues/301 regarding a possible opportunity for uBlock Origin.  I want to share that opportunity here as well for uBlock:

From the posts in the uBlock repo, plus those on the uBlock Origin repo, plus functionality available on competing products, it's clear that some people think they want isolated, intentional, and transparent sessions of unfiltered web use.  These requests all sound the same: "I want the ability to temporarily disable uBlock."

To my understanding, this exact functionality is planned for uBlock (but not uBlock Origin).

But what these users are requesting, if looked at openly and thoroughly, actually present a great opportunity for uBlock that I don't think any competing product can claim. In another thread, I think gorhill mentioned that he didn't want to copy ABP functionality; instead he wanted to determine what functions the user really needs, and design a product that accomplishes those. I agree with him completely. So here's something that ABP can't easily do that users want to do: perform web functions that require a little bit of data sharing without performing any unnecessary sharing

In [the issue mentioned above](https://github.com/gorhill/uBlock/issues/301) Majax79 states that in ABP, he completely turns off all filtering (momentarily) to get certain internet functions to work. I doubt that is what he really wants. Likely, he actually wants to keep all filtering ENABLED, except the filtering that is preventing him from performing his task. But the ability to do that easily and quickly is not built into ABP. To my knowledge, no filtering tool has that ability right out of the box. It's a great opportunity for uBlock to do something that no other filtering tool can do.

**Comment by ghost** [comment]
It's hard to determine exact filter/request that _prevent performing task_, but if you know it, you can temporarily allow it using https://github.com/gorhill/uBlock/wiki/Dynamic-URL-filtering (uBlock Origin)

**Comment by Gitoffthelawn** [comment]
@gwarser Right.  That's what can be done, but I think most people don't have the knowledge required to do that, and even for those who do, it can be a time-consuming task involving a lot of trial and error (but, IMO, not as time consuming in uBlock as in ABP).

If uBlock had a temporary limited filtering mode, that would match much more closely what users really want (if my analysis above is correct).

How to accomplish that is not trivial, of course.  In ABP, a user can try to manually accomplish that task using filter groups (which uBlock needs to support for other reasons), but it's hardly a good solution.

An elegant solution in uBlock would represent a substantial leap in filtering technology.

**Comment by ghost** [comment]
Something like this http://git-scm.com/docs/git-bisect ?

**Comment by Gitoffthelawn** [comment]
@gwarser Yes, that is certainly an excellent possibility (and a well proven one).  I think there are many different possibilities.

Another approach, which has its ups and downs, is to have either a special blacklist or whitelist (or both) that can be quickly and easily enabled on demand.  These "special" lists would allow the user to successfully perform tasks that many common filter lists prevent, without completely disabling uBlock filtering.

**Comment by karolgrudzinski** [comment]
I think you want uBlock to behave like PrivacyBadger - it can be configured to allow loading of some third party scripts but blocks setting cookies in this requests, so you can for example have facebook/disqus comments loaded on page but those widgets don't get any information about you - tracking protection don't work because of absence of cookies. I stopped using PB some time ago because it is slow as hell in comparision to uBlock.

**Comment by Gitoffthelawn** [comment]
It sounds like there are some valuable features there that could be added to uBlock.

Blocking everything unneeded most of the time, but having the ability to reduce the amount blocked when performing certain tasks is the goal.

Blocking sometimes breaks things (often without the user being aware), which at times is not a problem (it's a tradeoff).  For more important tasks, the user wants to be as sure as possible that the task is being performed correctly.
