### ISSUE TITLE
3rd party/my filters priority

### ISSUE THREAD

**Issue by Meru** [uBlock-LLC/uBlock#1436]

**Comment by lewisje** [comment]
The answer is the `$important` option, which is supported only by uBlock and uBlock Origin, and only in "My Filters"; an even higher priority is dynamic filtering (My Rules): https://github.com/chrisaljoudi/uBlock/wiki/Filter-syntax-extensions#network-filters

Here is a guide to rule precedence: https://github.com/chrisaljoudi/uBlock/wiki/Dynamic-filtering:-precedence

Next time, please read the wiki.

**Comment by Meru** [comment]
My question is not how to override some setting, but why "my filters" doesn't have highest priority by default. If user adds something to the personal list, isn't it obvious that it should be important.
Also I'm aware that dynamic filtering has a high priority. I believe I mentioned this myself.
And if you also mean that `$important` can help me to disable exception filters, then I don't see how it should be done given that user can have thousands of them loaded through 3rd-party lists. Maintaining a fork of the lists is easier.

Next time, please read more carefully.

**Comment by lewisje** [comment]
> I don't see how it should be done given that user can have thousands of them loaded through 3rd-party lists

If a URL matches any number of static whitelist rules (regardless of origin), but also matches a static blocking rule with `$important` set, and then matches no dynamic rules, it's blocked.

Also, I'm sorry for not noticing that you had already mentioned dynamic filtering.
