### ISSUE TITLE
Missing tabs in request log (Seamonkey)

### ISSUE THREAD

**Issue by MiKiL75** [uBlock-LLC/uBlock#1437]
Windows XP, Seamonkey 2.33.1, uBlock 0.9.5.0
(This bug doesn't occur in 0.9.4.0)

Latest version seem to have difficulties listing opened tabs in Network Request Log.

This is odd to reproduce because this bug doesn't seem to happen always, might need few restart cycles to stumble upon.
1.   Create new clean user profile and select it to default use and restart.
2.   Install 0.9.5.0, after install Network request log usually shows all tabs.
3.   Restart browser and after homepage is loaded, check Network request log, it only shows "Behind the scene".
   ![seamonkey_homepage_only](https://cloud.githubusercontent.com/assets/11736878/8024394/817a7696-0d3a-11e5-9377-a9f37598b22c.jpg)
4.   If you open a new tab and refresh the list, it only shows "Behind the scene" and "new tab".
   ![seamonkey_homepage_google](https://cloud.githubusercontent.com/assets/11736878/8024395/89527a1c-0d3a-11e5-83a4-4faaa9732995.jpg)

Even loading other page in first tab doesn't bring it up on tabs-list.
I also saw that sometimes Element picker icon is missing when first tab (homepage) is active after restart.

Only uBlock related thing what I see in error console is next message when I click Network request log icon.
`Security Error: Content at moz-nullprincipal:{c0c771b7-42c0-4d43-a45c-24ac2fc04d0f} may not load or link to chrome://ublock/content/devtools.html?tabId=1.`

**Comment by AlexVallat** [comment]
Thanks for reporting this, it should be fixed in the next version. I didn't notice the element picker thing, so if that's still an issue after this fix goes in then it would be better to have it as a separate issue to this one.
