### ISSUE TITLE
FYI: Safari 8.1/9.x new content blocking API and auto-update is only allowed on Safari Extensions Gallery

### ISSUE THREAD

**Issue by mike-to-spec** [uBlock-LLC/uBlock#1438]
First, I know it's too early to do anything as you might want to wait until El Cap is near the release date. I just want to give you a heads-up because one of the changes will affect how you can provide auto-updates for your extension. 

_Site you'd want to visit_: https://beta-extensions.apple.com or [the API docs](https://developer.apple.com/library/safari/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html#//apple_ref/doc/uid/TP40014305-CH9-SW5)

A few things of note:
1. They added a brand new API for content blocking that is designed to be extremely fast and lightweight
2. Auto-update will only be offered for extensions hosted on Apple's Safari Extensions Gallery

**Comment by 5t3f4n** [comment]
If I understand it correctly you will need to enroll in the [Apple Developer Program](https://developer.apple.com/programs/enroll/) to host your extensions on the Safari Gallery in the future. Enrolling costs $99 USD per year.

**Comment by mike-to-spec** [comment]
That sucks if it is true.

**Comment by mike-to-spec** [comment]
https://www.reddit.com/r/apple/comments/397bn6/apple_wants_me_to_pay_100_to_continue_publishing/

Looks like Apple is forcing all devs to pay 99$ a year to host their extension, which is BS. I've sent them emails about this horrible idea.

**Comment by chrisaljoudi** [comment]
@MikhailTNY Thanks!

Yeah, I did see that. Reactions, respectively, are:
1. Yay!
2. Crap. :(

**Comment by mike-to-spec** [comment]
It looks like Chris already talked about this on Reddit: https://www.reddit.com/r/apple/comments/398fgq/apples_new_safari_extension_policy_100year_to/

**Comment by 315234** [comment]
So this was discussed back in June, at the time someone on reddit made a donation of $100 to pay for a developer license, but 8 months later uBlock is still not in the Safari Extensions Gallery? Did I miss something, or was the point of the donation was to allow this to happen?
