### ISSUE TITLE
uBlock for iOS

### ISSUE THREAD

**Issue by wtfaremyinitials** [uBlock-LLC/uBlock#1439]
Related to #1216.

With iOS 9, Apple has added the ability to create content filter lists for native Safari. [Documentation here](https://developer.apple.com/library/prerelease/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html). Is creating an iOS app beyond of the scope of this project?

If it is, I'll make a separate one solo :wink:

**Comment by chrisaljoudi** [comment]
@wtfaremyinitials This is indeed planned.

**Comment by wtfaremyinitials** [comment]
@chrisaljoudi :+1:

**Comment by Betsy25** [comment]
> This is indeed planned.

Wow, looking forward to that one ! :+1: 
yet I'm a complete noob, but what I understood from these Safari 9.0 release notes, regarding iOS, it looks like you will need 1 single GIANT .json file, still no add-on possible there, or am I mistaken ?

**Comment by ReddestDream** [comment]
> @wtfaremyinitials This is indeed planned.

Thank you so much! Looking forward to it! ^_^

**Comment by chrisaljoudi** [comment]
@Betsy25 the format is JSON, but there's no reason to believe it's static. (Will be clearer when full documentation arrives).

**Comment by Betsy25** [comment]
> @Betsy25 the format is JSON, but there's no reason to believe it's static. (Will be clearer when full documentation arrives).

I hope for the best, but knowing the company's idea about "user freedom" i wouldn't set hopes too high.

**Comment by wzxu** [comment]
Here’s the relevant WWDC session: https://developer.apple.com/videos/wwdc/2015/?id=511

Looks like there will be change on the OS X side as well. Apparently you still specify the JSON to use so Safari knows about it beforehand and compiles it to bytecode, etc, but there’s also JavaScript API that allows you to modify it dynamically. Pretty interesting!

**Comment by wzxu** [comment]
Introduction to WebKit Content Blockers: https://www.webkit.org/blog/3476/content-blockers-first-look/

**Comment by mike-to-spec** [comment]
Chris just shared more news about Purify here: https://www.reddit.com/r/apple/comments/3b1xz3/sneakpeek_at_purify_adblocking_and_more_on_ios/

@chrisaljoudi I'd like to join the beta team if possible. All of my iOS devices are on iOS 9 and Mac on El Cap.

**Comment by onega** [comment]
Hello! I read in the news about the product that you are developing for the new iOS called Purify, and I would very much like to participate in its beta testing! Dear developers, please write to me at wusatb@gmail.com how to do it and send the link to download this plugin! I know all the necessary software for this test :)
