### ISSUE TITLE
[EasyPrivacy] page breakage: verizon.com account manager

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#144]
I needed to add this to get certain parts of the online account manager for Verizon to work. Mainly the 'getting started' section. They provide buttons to do things like signup for paperless billing, and other B.S. These buttons did nothing until I allowed:

```
@@verizon.com/includes/javascript/omnicode.js
```

MVPS, hpHosts, Dan's, Fanboy's, All Malware, All Privacy, Anti-Adblock, EasyList, Peter's list and both uBlock filters are enabeld.

This is for the FiOS/DSL side and not Wireless, I don't know if they share the same account management website or not. Main site is my.verizon.com which redirects to one of verizon's famously long URLs.

**Comment by gorhill** [comment]
The problem is the filter `||verizon.com/includes/javascript/omnicode.js` in _EasyPrivacy_, so this problem you have needs to be dealt by the _EasyPrivacy_ crowd: http://forums.lanik.us/viewforum.php?f=64 (no need to login, you can post as guess).
