### ISSUE TITLE
Hosts block

### ISSUE THREAD

**Issue by MurkBRA** [uBlock-LLC/uBlock#1440]
Block by Hosts can broke all connection on firefox, then you'll receive connection fail message.
I'm on uBlock 0.9.5.0 Firefox 39.0beta.
I do not know how to reproduce this bug but I know you'll let firefox open by a while until occur.

additional information:
I had already experienced this bug with HostsMan if I rearrange the hosts file like this:
127.0.0.1 www.exe.com 127.0.0.1 www.exe.com 127.0.0.1 www.exe.com 
instead of this:
127.0.0.1 www.exe.com
127.0.0.1 www.exe.com
127.0.0.1 www.exe.com

**Comment by lewisje** [comment]
It is not valid to have IP addresses in any position in any line of a HOSTS file other than the first position in the line: http://www.faqs.org/docs/securing/chap9sec95.html

Also, although it's not mentioned in that link, Windows ignores all aliases in each line after the first 8 (that is, you can't have more than 9 hostnames total per line), and although it's not relevant for the use of the HOSTS file to block content, if you want to specify that a certain hostname may have more than one IP address, make sure to put the IP addresses on adjacent lines; below is an example that I got from running nslookup on various Google domains, with a couple of public DNS servers, to specify just some of the IP addresses for just some Google hostnames:

``` ini
92.242.144.50 google.com www.google.com encrypted.google.com www3.l.google.com
216.58.216.110 google.com www.google.com encrypted.google.com www3.l.google.com
fe80:1::225:90ff:fe19:4b12 google.com www.google.com encrypted.google.com www3.l.google.com
2607:f8b0:4009:80b::200e google.com www.google.com encrypted.google.com www3.l.google.com
2607:f8b0:4009:805::1000 google.com www.google.com encrypted.google.com www3.l.google.com
2607:f8b0:4009:80b::2004 google.com www.google.com encrypted.google.com www3.l.google.com
```

Finally, I'm not sure that hosts-file entries are valid in "My Filters" (in case you're putting some custom filters there); instead, just put in what uBlock converts them to: `127.0.0.1 hostname` -> `||hostname^`

**Comment by MurkBRA** [comment]
Thank you.
