### ISSUE TITLE
 Ublock and Anti-Adblock Killer | Reek‎ isn't working 

### ISSUE THREAD

**Issue by spec1re** [uBlock-LLC/uBlock#1441]
Test: http://antiblock.org/?p=v3&demo

But userscript with Tampermonkey does:

https://greasyfork.org/de/scripts/735-anti-adblock-killer-reek

Cheers.

**Comment by SW1FT** [comment]
You need to have the userscript running otherwise it doesn't work.

**Comment by spec1re** [comment]
That doesn't make any sense, when I run the Anti-Adblock Killer userscript I do not need the Anti-Adblock Killer subscription in uBlock anyway, since it is in the Anti-Adblock Killer userscript already?! 

What I'm missing here?

**Comment by ghost** [comment]
From the link you provided (https://greasyfork.org/de/scripts/735-anti-adblock-killer-reek), it says that both the filter list and the userscript are required.
Subscribing to the filter list is step 2, and installing the userscript is step 3.
![screenshot51](https://cloud.githubusercontent.com/assets/4343306/8087113/a1012624-0f5e-11e5-8ad9-c5c66ad512a3.png)

**Comment by SW1FT** [comment]
@hotdogman did I state otherwise? That's exactly the point here.

**Comment by spec1re** [comment]
Sorry, wasnt aware that I need the userscript, the subscription and uBlock to make it work, because atm I have both Anti-Adblock subscription unchecked in uBlock and it still works?! 

Thanks.

**Comment by lewisje** [comment]
The UserScript won't throw a bunch of errors if you don't have the filter-list, but it _is_ meant to work in tandem with that list, working against anti-Adblock measures in ways that are out of scope for an extension that focuses on blocking network requests and hiding HTML elements.

**Comment by jcosentino** [comment]
To spec1re:
Go to this site:
http://hackintosh.zone/

Try it with the filter enabled (and without Greasemonkey / Tampermonkey script), then use the script without the filter, then finally both.
This shows that they do have to work in-tandem.
