### ISSUE TITLE
TypeError: button is null 

### ISSUE THREAD

**Issue by pachanka** [uBlock-LLC/uBlock#1442]
Hello,

This is not a critical error, but I thought I'd let you know.

 I'm using Firefox 38.0.5 on Debian, with uBlock Origin v0.9.8.2. and uppon startup I get the following error messages:

<pre><code>console.error: 
  [CustomizableUI]
  TypeError: button is null -- chrome://ublock0/content/js/vapi-background.js:1645
console.error: 
  [CustomizableUI]
  TypeError: button is null -- chrome://ublock0/content/js/vapi-background.js:1645
console.error: 
  [CustomizableUI]
  TypeError: button is null -- chrome://ublock0/content/js/vapi-background.js:1645</code></pre>

This plugin is by far the best thing thats happened to my add free browsing, and I'm a huge fan. Thanks for all the hard work.

**Comment by AlexVallat** [comment]
If the issue is with uBlock Origin, then please post it in the uBlock Origin repository: https://github.com/gorhill/uBlock/issues
