### ISSUE TITLE
Cannot add certain custom filters.

### ISSUE THREAD

**Issue by slopsommelier** [uBlock-LLC/uBlock#1443]
Trying to add certain filters results in this:
![screen shot 2015-06-10 at 11 26 58 pm](https://cloud.githubusercontent.com/assets/12841042/8101108/dac4aeb6-0fc8-11e5-854f-0f6698abb64b.png)

EDIT: I was able to add the filter manually by adding them all to the text box at the bottom of the filters preferences, but considering this came directly off of Fanboy's site I still think it shouldn't give you this error message when trying to add it; the other custom filters I added gave me a proper yes/no dialog to add to ublock.

**Comment by lewisje** [comment]
I don't think uBlock supports the `abp:` pseudo-protocol: I'm using uBlock Origin in Chrome for Windows, so it's not directly comparable, but on my system those abp: links do nothing.

**Comment by Gitoffthelawn** [comment]
I also don't think uBlock supports it, and I have mixed thoughts about how ABE and ABP support it.

Although I don't know of any reported problems with that "pseudo-protocol", that type of thing can often be abused.

It's a trade-off, and my personal preference is not to have that "pseudo-protocol", and just to add the URL to the list of filters.

**Comment by ghost** [comment]
For Safari clicking works only on these pages https://github.com/chrisaljoudi/uBlock/blob/master/platform/safari/vapi-background.js#L76
