### ISSUE TITLE
Is it possible to add a 3rd-party filter which is "The user-defined rules of uMatrix"?

### ISSUE THREAD

**Issue by navidada** [uBlock-LLC/uBlock#1444]
I know it's possible to use the "advanced user" enhanced capabilities and create dynamic filters with uBlock, but it seems that doing this (for people that already use uMatrix) is doing all the work again and using an interface which is not as intuitive and granular as uMatrix's. 

Moreover, it seems that no one knows how to prioritize firefox add-ons, and thus, users of uBlock and uMatrix sometimes waste their cpu resources in operating both add-ons, for example If I go to a certain site: a.com 
which has network requests from: b.com, c.com, d.com. e.com.
Let's say I've already blocked (using uMatrix) the requests of b.com, c.com and scripts from d.com.
In the current state of affairs, uBlock might check all these network requests again (even though uMatrix will block some of the along the road), when it could have only checked the network requests of d.com (minus the scripts) and e.com.

Today, I sometimes see that uBlock is trying to block and sometimes authorizes requests from sites that I have already blocked using uMatrix. Although I assume many of the requests being authorized by uBlock are blocked by uMatrix in the end, it's inefficient.

Adding the option for uBlock to use the filters that were already created in uMatrix (which can be very granular, because one can authorize only images from 3rd party sites and nothing else), will decrease the work that needs to be done by uBlock and make it much much faster.

What do you think?

**Comment by lewisje** [comment]
I don't know whether there's a way for the two extensions to share state like that, especially in a cross-browser manner.

**Comment by navidada** [comment]
So the only way of using uMatrix's user-defined rules is exporting them to a file and then importing that file with uBlock?

Maybe there's a way of creating a new add-on "uBlock for uMatrix" which will operate like "Element Hiding Helper for Adblock Plus" which is separate from Adblock but works with it?

Or maybe creating a new add-on which is "uMatrix with uBlock" which will then be able to use uMatrix's rules with uBlock's capabilities and thus improve the total performance of both of them (i.e. eliminating the need to scan/cross reference some network requests, which are going to be blocked by uMatrix, with 50,000+ filters from easylist and the other lists).
