### ISSUE TITLE
Leaking - Or am I doing it wrong?

### ISSUE THREAD

**Issue by lawrencehartkog** [uBlock-LLC/uBlock#1447]
newest µBlock with blue icon in its menu (which means ON somehow, I assume)
current, vanilla safari
dark red bars in the "world sign" column for 3rd party, 3rd party scripts and 3rd party frames, nothing manually set to green
load some page with ads

-> firewall shows that some webtrackers are still contacted by the browser, despite shown in red in µBlock

On chromium with µBlock 0.99 directly from gorhill, the firewall shows nothing for the same page.

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock

Please close this issue.
