### ISSUE TITLE
Palemoon:  uBlock icon on button-bar

### ISSUE THREAD

**Issue by ozar** [uBlock-LLC/uBlock#1449]
Please accept my apologies if this has been posted before and I've missed it during my issues searching efforts.

I'm running uBlock 0.9.5.0 on Palemoon 25.5.0 64-bit (under Arch Linux) and wondering about the uBlock button on the browser button-bar.  Is there some good reason for having the "down-arrow" attached to the uBlock button?  None of the other buttons on my browser seem to have or need this.

Under actual usage, clicking the down-arrow part of the button seems to give the same result as simply clicking the uBlock part of the button.  The problem with having it on there is that it causes the uBlock button to look out of alignment with the other buttons on the bar, and it causes all the buttons to take an an elongated appearance resulting in a loss of space all the way across the browser window.  When I disable uBlock, all the remaining buttons shrink in height to the size of the location url-bar.  Enabling the uBlock button causes all the buttons to grow in height again.  This seems to happen whether you choose the "use small icons" option, or you use the regular size icons under Pale Moon.  I'm guessing the same probably happens with Firefox, or other related web-browsers.

If my description of the issue is not adequate, I'll be happy to work up a screen-shot.

Thanks in advance your consideration regarding a fix or simple tweak for this issue.

**Comment by lewisje** [comment]
That's specific to Pale Moon (the arrow doesn't show up in the latest Firefox), and uBlock does not officially support Pale Moon yet (it might not ever, for all I know); consider switching to Adblock Latitude: https://addons.palemoon.org/extensions/privacy-and-security/

**Comment by ozar** [comment]
I've noticed that the uBlock icon in Pale Moon under Win7 has the same down arrow, but it's attached to the side of the uBlock icon instead of the bottom like it is under Linux.  That's not quite so bad since it only makes the icon wider rather than taller, but it's still seems redundant, and is a waste of space on the button bar.

I did consider ABL before installing Pale Moon, but it's my understanding that it is a memory hog like ABP, and all its other forks and spin-offs.  I tried uBlock-Origin, but it gives no uBlock icon at all under Pale Moon and their website on github recommended using regular uBlock since it does exhibit an icon.  Now, if I can just figure out a way to get an efficient icon enabled for uBlock or uBlock-Origin, all will be good, as uBlock seems to be working great under Pale Moon, otherwise.

**Comment by SvenPM** [comment]
Simple (temp) fix:

``` css
.toolbarbutton-menu-dropmarker[label="uBlock"] {
  display: none !important;
}
```

in userChrome.css or as a Stylish template. Tested with PM4L on Ubuntu Trusty and uBlock.

**Comment by ozar** [comment]
Thanks for the great tip, SvenPM!

That worked perfectly and will do just fine until a permanent fix happens.

**Comment by M1dknyte** [comment]
Thanks for that fix! I'm using the Legacy button on Firefox because of a problem with Tab Mix Plus.That added the down arrow on the right side of the icon. I'm guessing that Pale Moon uses the Legacy button also. 

This is the entry in about:config if you want to check it out:
extensions.ublock.forceLegacyToolbarButton = true

**Comment by ozar** [comment]
Thanks for the fix.  This looks and works great!

**Comment by AlexVallat** [comment]
Sorry it's taken a while for me to reply, I've been away. The arrow is supposed to show to the right of the button, not below it, as ozar mentioned. It does on Windows, but for some reason not on Linux. From some experimentation, I can fix that by tweaking the css so that it displays on the right under Linux too, or if preferred we can have the same fix as gorhill implemented to hide the arrow altogether.

I can see the arguments both ways; palemoon buttons that show popups are supposed to have drop-arrows. For consistency with uBlock on Firefox though, we may prefer to hide it. Any preference, @chrisaljoudi ?

**Comment by M1dknyte** [comment]
Hmm. Personally, I like it without the arrow. That makes the button a square versus a rectangle. With the normal button, I was getting a rectangle button in FF38, but not on FF31ESR. I used CSS to shrink the button width. I just didn't like the wasted space. Thanks for asking!

**Comment by SvenPM** [comment]
There isn't really something like consistent behavior when it comes to addons, some have a dropmarker others don't., so people would have to adapt to either behavior anyway. In this case the dropmarker doesn't make an awful lot of sense, it would, if the icon itself had a function (other than just being an indicator).

**Comment by ozar** [comment]
I too believe that including the down-arrow makes no sense at all in this case, since clicking it doesn't do anything that clicking the icon itself doesn't already do.  It seems totally redundant from my own point of view.

Thanks for looking into the matter, AllexVallat!  :+1:

**Comment by AlexVallat** [comment]
Also note: https://github.com/gorhill/uBlock/issues/264#issuecomment-114592958

PaleMoon has inconsistencies between Linux and Windows that make hiding the arrow problematic

**Comment by SvenPM** [comment]
Seriously, it's a dropmarker, so who cares? Good, there are always people who care about such stuff and make a big drama. If the preferred solution doesn't work and it has to be there for some reason, let it be there. Better an icon with an unneeded dropmarker than having no icon at all, and people can still remove it with a bit of userChrome.css.

**Comment by AlexVallat** [comment]
Agreed. Simplest solution is just to fix the drop marker appearing below instead of besides it on Linux. Should be consistent between Windows and Linux now, and with other PaleMoon buttons that produce popups when clicked.

**Comment by 2017-05-1200-11-20** [comment]
![screensho 2017-08-26 12-58-13](https://user-images.githubusercontent.com/28655355/29740472-3b5a00b4-8a60-11e7-99f9-20c9af4ca532.png)
I get latest upgrade?

**Comment by lewisje** [comment]
Go to https://github.com/gorhill/uBlock to get uBlock Origin; uninstall uBlock, which has not been updated in a long time.
