### ISSUE TITLE
Unable to whitelist Google apps grid

### ISSUE THREAD

**Issue by markreg** [uBlock-LLC/uBlock#1450]
The google apps grid is blocked on default ublock settings. Adding `google.com/gen_204?*` or any variant of such to the whitelist has no effect on the block.

**Comment by lachlansimpson** [comment]
I don't understand why this is something that would be blocked anyway? It should be removed from the black list. If some people want to block it, that's fine, but not everyone does. It is a useful tool, not an ad or tracking service.

**Comment by ghost** [comment]
If you're talking about the grid button near the top right on your Gmail window, you should "disable cosmetic filtering" (the "eye" logo) in your mublock config.

**Comment by lachlansimpson** [comment]
OH! Thanks.

**Comment by markreg** [comment]
@dickfeynman Disabling the cosmetic filter allows ads to show up on the search results page.

I fail to understand how such a huge regression has been overlooked by the author @chrisaljoudi unless this is something exclusively on my end.

**Comment by ghost** [comment]
Not for me. Though I just realized that I'm using mublock-origin, and in my case cosmetic filtering is switched off only for the Gmail page.

**Comment by gorhill** [comment]
It's really a Fanboy's Annoyance List issue, this should be reported to the maintainers: https://forums.lanik.us/viewforum.php?f=64.

Problematic filter is `##div[class^="gb_"] > .gb_ba`.

Workaround: `mail.google.com#@#div[class^="gb_"] > .gb_ba`.

**Comment by gorhill** [comment]
Actually this was fixed already two days ago: https://hg.adblockplus.org/easylist/rev/211bd2370624

Just force an update of Fanboy's Annoyance List.

**Comment by markreg** [comment]
@gorhill Thanks, works after a force update.
