### ISSUE TITLE
Confusion with uBlock Origin

### ISSUE THREAD

**Issue by sammcj** [uBlock-LLC/uBlock#1452]
I'm a little confused as to what https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/ is in relation to this project now and I'm sure I'm not the only one.

Is anyone able to clarify this for us?

**Comment by sammcj** [comment]
Ah, answered my own question, as Gorhill is now developing uBlock again this fork is no longer the 'official' one.

https://github.com/gorhill/uBlock

**Comment by Gitoffthelawn** [comment]
uBlock Origin is a fork of this project, uBlock.  From what I read, gorhill was offered to merge with the main project, but refused.  The result is two separate projects that share much of their code.

**Comment by jangorecki** [comment]
I was also confused. Looking at those graphs may help to understand the relation between two projects:
https://github.com/chrisaljoudi/uBlock/graphs/contributors
https://github.com/gorhill/uBlock/graphs/contributors
I wouldn't call them separate projects @Gitoffthelawn
