### ISSUE TITLE
On Android

### ISSUE THREAD

**Issue by gerroon** [uBlock-LLC/uBlock#1453]
Hi

I started using it on FF Android. It works, but menu interaction is abit slow, wondering if there could be some optimization there.

thanks

**Comment by LifeIsStrange** [comment]
Yeah, it will be amazing ! Can you report your suggestion for uBlock Origin ? 
And uMatrix also :)

**Comment by gerroon** [comment]
Hi

Umatrix does not want to install on FF 38.0.5 on Android

**Comment by AlexVallat** [comment]
Hi @gerroon, if you can be a bit more specific then I might be able to look into it, but I have to say straight away that I doubt there will be much that can be done.

What do you mean by menu interaction? The only interaction uBlock has with the menu is to put it's entry on the Tools menu. There's no interaction involved, it's just there. Do you mean it is slow to update with the count of blocked items? Or that if you click on it it's slow to show the uBlock tab?

**Comment by gerroon** [comment]
Hi

I guess I meant the Ublock Dashboard interaction seems  a bit laggy. I mean its ok I guess given that it is on Android FF, however more speed would not hurt.
