### ISSUE TITLE
Noscript needed?

### ISSUE THREAD

**Issue by gerroon** [uBlock-LLC/uBlock#1454]
HI

DO you think that I can disable Noscript if I am using this addon? Are they targeting the same functionalty?

Thanks

**Comment by Gitoffthelawn** [comment]
It depends on what you want.  NoScript blocks all scripts by default, and implements an opt-in paradigm.  The basic premise of NoScript is that scripts are dangerous and therefore only allow the ones you really need to obtain the functionality you desire.

NoScript also claims the ability to prevent specific types of attacks.  Perhaps someone else can comment on the specifics of those claims and how (or if) those abilities are different than uBlock.  I haven't studied the NoScript code in detail, so I'm not sure what it does under the hood.

uBlock can be configured to allow/block anything of your choosing.  Scripts are just one of the many types of objects that can be allowed/blocked.  uBlock is not specifically tailored to allow/blocking just scripts, but is able to allow/block almost any kind of web content, scripts included.

**Comment by Havokdan** [comment]
Maybe uMatrix...

**Comment by gerroon** [comment]
@Gitoffthelawn 
Thanks for the answer. Much appreciated.

How about Ublock along with Policeman? Same functionality? I think I will keep NScript.

**Comment by Radagast** [comment]
You might find - [My thoughts and observations on ad, tracker and script blockers. Which ones are redundant. Which ones are better.](https://www.reddit.com/r/firefox/comments/39vn01/my_thoughts_and_observations_on_ad_tracker_and/) of interest. Personally, I'd say uMatrix has more in common with NoScript.

**Comment by Gitoffthelawn** [comment]
@gerron Policeman's functionality is more similar to uMatrix than uBlock.  From what I've seen, uBlock can be used with Policeman (or uMatrix).

I recommend defining your goals, and picking tools to meet those goals.  On the other hand, experimenting with a few different tools will give you better ideas of possible goals.  You can create a fresh Firefox profile, and experiment with it all you like.  When you are done, just delete that profile.

**Comment by gerroon** [comment]
Thanks for all the ideas and the recommendations.
