### ISSUE TITLE
Disable Anti-Adblock

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1456]
Disable Anti-Adblock is an extension for Adblock Plus. Is there something similar to uBlock?

**Comment by LifeIsStrange** [comment]
There are two list for protect against anti-ublock, the warning removal list and the anti-adblock killer Reek, but the second list need à userscript (with greasemonkey or other) , you can also Just hide the anti-ublock with the selector (i'm very sorry for my bad english :/) 
or with dynamic filtering (it's generally inline-scripts. 
And sorry if i have bad understund your question, i'm very bad in english xD

**Comment by davidhedlund** [comment]
As @LifeIsStrange said these two filters are used as anti-adblock:
- Adblock Warning Removal List‎
- Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com)

I propose that these filters should be enabled by default. What is your opinion @chrisaljoudi?

**Comment by lewisje** [comment]
As #1441 shows, Reek's list is useless without the UserScript and therefore should not be enabled by default, but the Adblock Warning Removal List _should_ be enabled by default.

**Comment by davidhedlund** [comment]
This project is dead, use [uBlock Origin](https://github.com/gorhill/uBlock/issues) instead.

**Comment by lewisje** [comment]
Anti-Adblock Killer is also dead; use [AAK-Cont](https://xuhaiyang1234.gitlab.io/AAK-Cont/) (all platforms except uBO-Chromium) or [uBlock Protector](https://jspenguin2017.github.io/uBlockProtector/) (uBO on a Chromium-based browser) instead.

**Comment by davidhedlund** [comment]
@lewisje Yes I know but thank you for anyway.
