### ISSUE TITLE
uBlock does not provide list of all elements blocked by cosmetic filters

### ISSUE THREAD

**Issue by nyanpasu64** [uBlock-LLC/uBlock#1457]
In the process of tracking down an intermittently missing Gmail user-switch popup, I discovered that uBlock Firefox cannot show all active cosmetic filters or blocked elements. This makes it difficult to identify malfunctioning filters. Can you provide such functionality in the tray icon?

**Comment by plughie** [comment]
:+1:

**Comment by tofof** [comment]
This is needed.
