### ISSUE TITLE
Could not hide plugin placeholder 

### ISSUE THREAD

**Issue by ivysrono** [uBlock-LLC/uBlock#146]
Test: 
http://www.fodian.net/tools/

rule：
`|http://www.fodian.net/pics/002-1.swf|$domain=www.fodian.net`

**Comment by gorhill** [comment]
I need to add `embed` as a collapsible element.

**Comment by gorhill** [comment]
This was partly fixed a while ago, I added `embed` in the list of elements to query and hide. With ee81436ff54e9e31d3e9595bbf913402584f56c5, the fix is complete.
