### ISSUE TITLE
EasyList adds unexpected content into all webpages

### ISSUE THREAD

**Issue by dvorapa** [uBlock-LLC/uBlock#1460]
Hello, I'm a web designer and I recently used Google Chrome Developer tools, but I found out, that uBlock adds into almost every webpage I open content like the one below (the marked code line in dev tools). I tried to find out, which list does it make and I've discoverred that it is work of EasyList one (concretely this: `EasyList‎  (adblockplus.org): 0 použito z celkových 57 869`). See the example:

![snimek obrazovky porizeny 2015-06-19 20 43 01](https://cloud.githubusercontent.com/assets/5113916/8260520/9771a54e-16c4-11e5-8bd8-7daee1ca8976.png)

You probably ask something like:
**What's wrong with that?**
- It adds this content as an last child of the `body` or `head` and **alternating**, once body, another time head. Why?
- It shows even on webpage without any add at all as you can see in the picture
- CSS selectors like `E:nth-last-child(n)` could be messed up
- `[href^="http://www.face"]` and `[href^="http://www.link"]` are just too much specific

These points doesn't look like good behavior. That's why I openned this issue.

**Comment by ghost** [comment]
https://github.com/chrisaljoudi/uBlock/issues/161

**Comment by Gitoffthelawn** [comment]
The issue #161 that gwarser linked to contains a great explanation for the OP.  The Wiki (recently updated) also links to that information, BTW.

I was thinking... does this technique mess up CSS selectors like `E:nth-last-child(n)` since it is adding another child?

**Comment by dvorapa** [comment]
Oh, I didn't see that, thank you.

The selector mess is another thing I don't like on this uBlock solution...
