### ISSUE TITLE
Filters cannot be non-free in uBlock according to the Free Software Foundation

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1461]
uBlock contains 22 filters distributed as non-free software, 5 of them distributed with the non-free NC clause, 16 filters are distributed without any licenses at all (3 of these filters are enabled by default). They should be distributed under FSF approved licenses found in https://www.gnu.org/licenses/license-list.html to be allowed to be published in the Free Software Directory (https://directory.fsf.org/uBlock).

For example, the filter "Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com)" is distributed under "! License: https://creativecommons.org/licenses/by-nc-sa/4.0/". "Norsk adblockliste" uses both NC and ND clauses which make it even less free.

The non-commercial (NC) Creative Commons clause is non-free. Please ask the authors of respectively filter to redistribute them without the non-free clauses. If they do so the filters will be free.

However, consider to remove these filters until this issue have been resolved to make uBlock 100% free software so it can remain in the Free Software Directory: https://directory.fsf.org/wiki/uBlock
# uBlock non-free 3rd-party filters (https://adblockplus.org/subscriptions copy)

No license: Adblock Warning Removal List
Non-free software (NC clause): Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com)
Enabled by default. No license: Peter Lowe’s Ad server list‎ (yoyo.org)

**Malware domains**
Enabled by default. No license: Malware Domain List‎ (malwaredomainlist.com)
Enabled by default. No license: Malware domains‎
No license: Malware domains (long-lived)

**Social**
No license: Anti-ThirdpartySocial (see warning inside list)‎ (fanboy.co.nz)

**Multipurpose**
No license: Dan Pollock’s hosts file‎ (someonewhocares.org)
No license: hpHosts’s Ad and tracking servers‎ (hosts-file.net)
Non-free software (NC clause): MVPS HOSTS‎ (mvps.org)

**Regions, languages**
Non-free software (NC clause): ara: Liste AR‎ (liste-ar-adblock.googlecode.com)
No license: BGR: Bulgarian Adblock list‎ (stanev.org)
No license: CHN: China: cjxlist (obsolete, will be removed)‎ (cjxlist1.googlecode.com)
No license: DEU: EasyList Germany‎ (adblockplus.org)
No license: DNK: Schacks Adblock Plus liste‎ 
Non-free software (NC clause): ESP: Filtros Nauscopicos‎ (mozilla-hispano.org)
non-respoding license URL        FRA: EasyList Liste FR‎ (adblockplus.org)
No license: HUN: hufilter‎ (raw.githubusercontent.com)
No license: ISL: Icelandic ABP List‎ 
No license: ITA: ABP X Files‎ (dropboxusercontent.com)
Non-free software (NC and ND clause): NOR: Norsk adblockliste‎ (fredfiber.no)
No license: ROU: RO-LIST (modified)‎

**Comment by Betsy25** [comment]
> You are free to:
> 
>  Share — copy and redistribute the material in any medium or format
>  Adapt — remix, transform, and build upon the material

**Comment by davidhedlund** [comment]
@Betsy25 The **NonCommercial (NC)** clause is not a not free content license, according to definitions such as DFSG or the Free Software Foundation's standards.

Anti-Adblock Killer | Reek is proprietary as it is distributed under Attribution-**NonCommercial**-ShareAlike 4.0 International (CC BY-**NC**-SA 4.0).

Here is a copy of the license from https://creativecommons.org/licenses/by-nc-sa/4.0/:

You are free to:
- Share — copy and redistribute the material in any medium or format
- Adapt — remix, transform, and build upon the material

The licensor cannot revoke these freedoms as long as you follow the license terms.

Under the following terms:
- Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
- **NonCommercial — You may not use the material for commercial purposes.**
- ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
- No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

Notices:
- You do not have to comply with the license for elements of the material in the public domain or where your use is permitted by an applicable exception or limitation.
- No warranties are given. The license may not give you all of the permissions necessary for your intended use. For example, other rights such as publicity, privacy, or moral rights may limit how you use the material.

**Comment by Betsy25** [comment]
Since when has gorhill ever asked a single penny for his programs ?

**Comment by davidhedlund** [comment]
@Betsy25 We're talking free software here. Please read https://www.gnu.org/philosophy/free-sw.en.html.

**Comment by seanrand** [comment]
Gutting uBlock by removing filter lists purely on ideological grounds would be a disservice to uBlock users. uBlock itself ~~doesn't bundle or redistribute these lists and~~ is still free as in free whether or not it provides what are basically shortcuts to downloading those filter lists. Indicating what licence each list is distributed under would be a better option.

Edit: Actually, it does - guess I should take a better look at the code before commenting.

**Comment by SW1FT** [comment]
I'm sorry, but who cares? uBlock is providing a free service and you can find all those lists online whether on github or the lists' proprietary websites.

**Comment by davidhedlund** [comment]
@SW1FT I care so I took action and unapproved uBlock and uBlock Origin in the Free Software Directory (FSD) to make clear that this is a real problem.
- https://directory.fsf.org/wiki/UBlock
- https://directory.fsf.org/wiki/UBlock_Origin

uBlock itself is free and the filters are gratis but not free, thus the entire service is not a free. However, the service will be 100% free when all filters have been re-distributed under free licenses. If that happens the FSD entries will be approved again which I'm looking forward to.

**Comment by chrisaljoudi** [comment]
I'm sorry, but providing appropriate protection mechanisms for the users is more important than some licensing formality.

To me, when open, user-focused software has it as a main concern to deal with bureaucratic formalities above all else, it's no longer open or user-focused.

**Comment by davidhedlund** [comment]
@chrisaljoudi These filters have been distributed non-free by people outside the uBlock development team so I do not blame anyone of you guys.

I will contact the Adblock Plus developers who started this filter subscription list (https://adblockplus.org/subscriptions). If that fail I will contact the authors for respective filter.

I only wish that you understand that softwares in the Free Software Directory must be 100% free to be approved. Please do not take it personal that uBlock have been unapproved for a moment. I think you're doing a great job and I understand that you are to limited to maintain each issue. Perhaps the FSF Compliance Lab Team (https://www.fsf.org/licensing/team) will help you, I just asked them.

**Comment by lewisje** [comment]
I'm surprised that anybody bothered to _add_ it to the directory to begin with.

**Comment by davidhedlund** [comment]
According to the Free Software Foundation: "Some of the 3rd-party filters (simple data files) in this software are under non-free licenses. However, it is not clear that the works in question are actually subject to copyright or that the licensing terms could apply. As such, we urge you to use redistribute those filters with caution that someone may try to claim copyright on the works." - https://directory.fsf.org/wiki/UBlock_Origin (see license note when logged in)

**Comment by flyingzebras** [comment]
See https://github.com/gorhill/uBlock/wiki/Filter-list-licenses for license.
