### ISSUE TITLE
Exporting dynamic rules file can result in 0xC2 chars in output

### ISSUE THREAD

**Issue by jamesoff** [uBlock-LLC/uBlock#1464]
Steps to reproduce:
1. With advanced mode enabled, set some permanent rules and different some temporary rules, such that the permanent rules list on the left has at least one empty line
2. Click "Export to file"
3. Observe 0xC2 chars in the output where the blank lines were (appears as capital A with circumflex in browser window and %C2 in the data: URL)

uBlock 0.9.5.0 on Safari 8.0.6 on OS X 10.10.3.

(Edit: typo)

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock

Please close old issues. If they are still relevant, repost them to new repository.
