### ISSUE TITLE
GNU/Linux whitelist filters

### ISSUE THREAD

**Issue by flyingzebras** [uBlock-LLC/uBlock#1466]
~~Please add these filters to chrome://ublock/content/asset-viewer.html?url=assets/ublock/filters.txt~~

~~! ViewTubePlus issue https://forums.lanik.us/viewtopic.php?f=64&t=23545
~~@@http://$xmlhttprequest,domain=pornhub.com|redtube.com|tube8.com|tube8.es|tube8.fr|youporn.com~~
~~@@https://$xmlhttprequest,domain=pornhub.com|redtube.com|tube8.com|tube8.es|tube8.fr|youporn.com~~

**Comment by lewisje** [comment]
That would be better-suited for uBlock Unbreak, but anyway, the author of that UserScript ended up rewriting it to avoid XHRs on those domains.

**Comment by flyingzebras** [comment]
This ViewTubePlus bug have been fixed so there is no need to add the white list filters described above.
