### ISSUE TITLE
[Bug] Toolbar button breaks standard toolbar expansion

### ISSUE THREAD

**Issue by Gitoffthelawn** [uBlock-LLC/uBlock#1467]
In Firefox, when the user reduces the horizontal size of the window, the browser will move extension icons to an "expansion icon" (double right-chevron).

When uBlock is one of those icons, it breaks the standard functionality of that expansion icon.  Once the uBlock icon is included within the expansion icon's dropdown menu, every other left-click on the expansion icon does not function.

To reproduce:
1. Add the uBlock toolbar icon to the Location Bar (navbar).
2. Reduce the horizontal width of the Firefox window until the uBlock icon disappears and the expansion icon appears.
3. Left-click on the expansion icon.  If it works, try it again.  It will fail every other time.

Tested on Win7-SP1 with FF v38.0.5.

I actually tested it with one of the uBlock forks, but am switching to the main project here. The issue likely exists in the main uBlock project, so this is probably the best place to report it.

**Comment by anewuser** [comment]
Please close your old issues here and, if they are still relevant, repost them to the current repository.

https://github.com/chrisaljoudi/uBlock/issues/created_by/Gitoffthelawn
https://github.com/gorhill/uBlock/issues

**Comment by Gitoffthelawn** [comment]
@anewuser I would be willing to do that, but, honestly, is seems to be a waste of time.

Two of the issues I reported on that repo **6 months** ago have not received any response from the developer:
- https://github.com/gorhill/uBlock/issues/1939
- https://github.com/gorhill/uBlock/issues/1940

Another issue that I reported on that repo months ago, which has been confirmed, has also not received any response from the developer:
- https://github.com/gorhill/uBlock/issues/1977

Of the [5 issues I have created on that repo](https://github.com/gorhill/uBlock/issues/created_by/Gitoffthelawn), only 1 of them has received any response from the developer.

As you can see by the issues I have created, I work my hardest to write quality issue reports.

I value my time, and I don't find it to be a good use of time to report issues when I don't even receive an acknowledgement from the developer.

**Comment by anewuser** [comment]
He reads everything and closes all irrelevant issues right away, so I assume he's read and accepted your reports. Anyway, I get your point.

**Comment by Gitoffthelawn** [comment]
@anewuser Thanks for your understanding.
