### ISSUE TITLE
Leaking ads and not updating filters

### ISSUE THREAD

**Issue by naoliv** [uBlock-LLC/uBlock#1469]
I am seeing ads in Google, Facebook and other places. I don't know if this a problem with uBlock, the filter lists or something else.
Trying to take a look at the third-party filters I see only this gray bar (no matter how much I wait, I can't do anything in this tab). I can see that some lists are outdated, but I can't do anything.

![Gray](https://cloud.githubusercontent.com/assets/982338/8314757/ef65bc2c-19c1-11e5-94df-8de45ab3d3b7.png)

Using 0.9.5.0 on Iceweasel  40.0a2
Is there something that I can do to debug this?

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock

Please close this issue.
