### ISSUE TITLE
uBlock Blocks Some MapBox Maps Without Ability to Disable

### ISSUE THREAD

**Issue by robmathers** [uBlock-LLC/uBlock#1470]
uBlock appears to block some maps (seemingly by MapBox) without listing them as blocked elements in the request log. For example, http://www.blogto.com/toronto/the_best_chinese_food_delivery_in_toronto/. That page doesn't load the map tiles, but there's no indication that they're blocked when looking at the uBlock tools. However disabling uBlock on the page restores the map functionality.

This seems like a bug that should be fixed. Maps shouldn't be blocked, and even if they are, it should be apparent that they are, and how to unblock them.

**Comment by HybridDog** [comment]
to me the map is visible:
![2015-06-24-164724_1280x1024_scrot](https://cloud.githubusercontent.com/assets/3192173/8332958/01188c22-1a91-11e5-9aee-f6567487d9bd.png)
