### ISSUE TITLE
uBlock on safari causing an issue for sketchfab.com viewer

### ISSUE THREAD

**Issue by sharno** [uBlock-LLC/uBlock#1473]
Models on sketchfab.com are displayed as dark models with uBlock enabled on Safari
Even trying to put the site on white list didn't solve the issue and only disabling uBlock extension completely solves the issue.

Here is an example of a model:
https://sketchfab.com/models/40ab767100eb44a6be9b42d24d692ca8

It appears dark on safari with uBlock enabled and appears normally when it's disabled.

![screen shot 2015-06-25 at 1 47 23 pm](https://cloud.githubusercontent.com/assets/601606/8353662/c7dc555a-1b40-11e5-99f6-9f6bcbde207d.png)
![screen shot 2015-06-25 at 1 47 00 pm](https://cloud.githubusercontent.com/assets/601606/8353661/c79ac4f0-1b40-11e5-95be-83e6165c464d.png)

**Comment by Gitoffthelawn** [comment]
It it possibly caused by a bad filter.  Which filter lists are you using?

**Comment by sharno** [comment]
Tried unchecking and purging all filters but got the same results. Also, the strange thing is unchecking uBlock filters didn't make "Apply Changes" button to appear.
Still the only way to make the website work fine is to disable uBlock completely from extensions.

**Comment by Betsy25** [comment]
It must be a browser specific issue, since this works as it should in Firefox.

**Comment by rafapages** [comment]
I also have this same issue when rendering textured models in Sketchfab...
