### ISSUE TITLE
Regarding uBlock Poll (Chrome Network Prediction)

### ISSUE THREAD

**Issue by Zearin** [uBlock-LLC/uBlock#1474]
I just took the poll asking (paraphrased): 

> “Should uBlock block requests made by Chrome’s ‘Network Prediction’ feature?”
> 
> [ ] **Yes**, to ensure that no requests “sneak by”
> [ ] **No**; disabling this is up to the user

I voted “No”.  If a user likes the benefits of Network Prediction, then denying them this choice forces them to decide between using uBlock and enjoying the performance gains of Network Prediction.  So, finer granularity is what I was really voting for.

But I don’t think that’s enough.  I propose the following:
- **Add a checkbox to uBlock’s preferences, allowing the user to toggle whether uBlock filters Network Prediction requests.**  If this isn’t possible for technical reasons (i.e. extension constraints), then
- **Add a prominent message to uBlock’s preferences, notifying the user that uBlock leaves Network Prediction requests alone in the interests of user choice.  Remind users how to disable Network Prediction if they so choose.**

IMO this is the most responsible thing to do: preserving choice, while informing users—or reminding those that forget—about Network Prediction, and its relationship with uBlock.

**Comment by Gitoffthelawn** [comment]
And including sufficient information so users can make educated decisions.
