### ISSUE TITLE
Dynamic Filtering: global vs. site question

### ISSUE THREAD

**Issue by Zearin** [uBlock-LLC/uBlock#1476]
In the wiki’s [Dynamic Filtering Quick Guide](https://github.com/chrisaljoudi/uBlock/wiki/Dynamic-filtering:-quick-guide), it says that the first column in the dynamic filtering is for Global rules and the second column is for site-specific rules. 

When I look at the Dynamic Filtering pane in Safari, the icons are a **pin and a globe, in that order**.  This is the reverse of what the wiki.

---

**_Before anyone edits the wiki_, could someone confirm in the JS whether the first column is for global rules?**

It _could_ be that the icons are accidentally reversed.  (They were added in the 0.9.5.0 release, I believe.  Before this, there was no indication of which column was which.)  

If the icons are reversed, then this is a bug and must be fixed!  Otherwise, it’s a simple typo in the Wiki.

---

Please check the code **first** to confirm, though!  

Thanks.

**Comment by ghost** [comment]
https://github.com/chrisaljoudi/uBlock/issues/1371

**Comment by karolgrudzinski** [comment]
Columns order has been reversed -> 3ca6daac736172ab8287b285849a2e2ba30b50e7
