### ISSUE TITLE
Don't update subscription which is not selected(activated)

### ISSUE THREAD

**Issue by chr00t** [uBlock-LLC/uBlock#1477]
https://sw.estiva.org:419/memo/article_b5571b6c478f7c02ece1968247ac996c.html

> uBlock connect to raw.githubusercontent.com in background without user authorization

This is true. I can confirm it on my laptop.
Please explain what this connection doing, and stop doing "phone home" activity.
It looks like malware to me.

0.9.1.0 downloaded from Firefox Add-on (latest version)

**Comment by chr00t** [comment]
Wikipedia:

Malicious phoning home
There are many malware applications that "phone home" to gather and store information about a person's machine. For example, the Pushdo Trojan[8] shows the new complexity of modern malware applications and the phoning home capabilities of these systems.

**Comment by Mikey1993** [comment]
Probably the auto update feature is kicking in in the background.
Nothing to be bothered of.
