### ISSUE TITLE
Ublock has a problem that several adblockers have

### ISSUE THREAD

**Issue by Felipefpl** [uBlock-LLC/uBlock#148]
the automatic download/if not embedding of list(s) in the adblocker, i know it's a very minor thing but i'd like to see some adblocker that doesnt do this kind of thing since it does this without the consent of ppl and after all, the embedding of lists just make what should be a simple extension A LOT bigger.

**Comment by RandomAcronym** [comment]
I think most users expect an ad blocker to block ads by default.

**Comment by gorhill** [comment]
Dup of #138.

**Comment by Felipefpl** [comment]
Sorry but only the part about automatic download is a dupe, the part where users didnt ask to have a lot of lists they didnt choose embedded is not a dupe, this is a thing that only makes ublock bigger, ublock should right after is installed open itself and display a list with all the options (including not standard lists) so the users can choose what THEY want, it's all about choice. ;)
