### ISSUE TITLE
Firefox: missing URL for link from Advanced-user-features

### ISSUE THREAD

**Issue by blueyed** [uBlock-LLC/uBlock#1480]
The following help entry points to a non-existing URL:

```
"settingsAdvancedUserPrompt":{
  "message":"I am an advanced user (<a href='https:\/\/github.com\/chrisaljoudi\/uBlock\/wiki\/Advanced-user-features'>Required reading<\/a>)",
  "description":"English: "
},

(from src/_locales/en/messages.json)
```

URL: https://github.com/chrisaljoudi/uBlock/wiki/Advanced-user-features

The link is used in `chrome://ublock/content/dashboard.html` with the "I am an advanced user" setting.

**Comment by publicarray** [comment]
Thanks for reporting the issue. Can this be closed?

**Comment by yous** [comment]
:+1:

**Comment by blueyed** [comment]
Thanks!
