### ISSUE TITLE
Support for Microsoft Edge Browser

### ISSUE THREAD

**Issue by mmk7003** [uBlock-LLC/uBlock#1481]
Are there any plans to support uBlock for Microsoft Edge Browser????

**Comment by hackel** [comment]
Hopefully not.  Why would the uBlock team want to do anything that might _encourage_ people to use that proprietary garbage?  We all should have a common interest in maintaining an open, standards-complaint web.

**Comment by Betsy25** [comment]
Forget support, uBlock (not Origin) is now being focused on iOS and being a cashcow.

**Comment by foobar13373** [comment]
@Betsy25 Please elaborate on this. I do not get what you intend to tell us.

**Comment by lewisje** [comment]
Once Edge gets proper extension support, it should be no big deal for someone to fork uBlock Origin to run on Edge, because its extension system is similar to Chrome's.

**Comment by nickaein** [comment]
Many users are looking for decent plugins for Edge while there are few extensions available for Edge. Porting uBlock to Edge will be a big plus.

**Comment by ThisIsAlanB** [comment]
@hackel Isn't Chrome the same way?

**Comment by Gitoffthelawn** [comment]
@lewisje wrote: "Once Edge gets proper extension support, it should be no big deal for someone to fork uBlock Origin to run on Edge, because its extension system is similar to Chrome's."

Can you clarify?  It sounds to me that you are saying that Edge has rudimentary extension support, but it's not really effective at this point.  Is that an accurate understanding, or am I misunderstanding what you are trying to convey?

**Comment by lewisje** [comment]
What I mean is that I had read that [Reddit Enhancement Suite was ported to Edge](http://www.geek.com/microsoft/microsoft-announces-new-edge-browser-with-support-for-chrome-and-firefox-extensions-1621686/) early in its development, so the infrastructure is there, but Edge in Windows RTM can't install extensions.

---

Also, if an extension is just a wrapper around a UserScript, you'll probably be able to test it by setting up an IIFE that loads the script into the document, either by pasting that into the console or by turning that into a bookmarklet...

...although to get a bookmarklet to work on Edge, you have to make some random Favorite, then close the browser, then open the resulting .url file (in a cryptically named folder) in Notepad, then change the `URL` to be the `javascript:` URI in the bookmarklet, then add a new section called

```
[Bookmarklet]
ExtendedURL=<that same javascript: URI>
```

...or just add the bookmarklet to Internet Explorer, then go to Edge and import Favorites.

I did just that sort of thing with a couple extensions for Twitch that are being tested in Edge, called [BetterTTV and FrankerFaceZ](http://lewisje.github.io/).

Unfortunately, you can't test a fairly complex extension like uBlock Origin that way, but at least I can say that, as SirStendec (developer of FrankerFaceZ) figured out, Edge does not support scoped CSS, so his use of it in `querySelectorAll` broke when he tried it in Edge.

**Comment by Gitoffthelawn** [comment]
@lewisje Thanks!

**Comment by Xemanth** [comment]
Edge's extension support has been released in the latest (17.3.2016) insider fast ring build 14291 http://changewindows.org/build.php?id=117

**Comment by lewisje** [comment]
Development has ceased on this extension, but surely someone is willing to port uBlock Origin to Edge: https://github.com/gorhill/ublock/

**Comment by brunolm** [comment]
I think someone can close this issue...

It is now available at
https://www.microsoft.com/en-us/store/p/app/9nblggh444l4
