### ISSUE TITLE
how do the hell one can install latest 0.9.9.6 dev version in chrome??????????????????????????????????????????????

### ISSUE THREAD

**Issue by ale82to** [uBlock-LLC/uBlock#1486]
how do the hell one can install latest 0.9.9.6 dev version in chrome??????????????????????????????????????????????

**Comment by lewisje** [comment]
Chrome for Windows (maybe also Stable versions for Mac and Linux) doesn't allow off-store installation of CRX files, so what you'd need to do is load the unpacked extension in developer mode, which makes upgrading a pain and should really only be done if you're _actually developing_ the extension.
