### ISSUE TITLE
[REQUEST] Integrate new features from Gorhill

### ISSUE THREAD

**Issue by marsfan** [uBlock-LLC/uBlock#1487]
Gorhill has a cool new unified filter, badware site detector, and improvements on the selection ui (where you add things to be blocked).

It would be nice to integrate these features into ublock, maybe with the unified filter and badware detectors toggleable in the options menu.

**Comment by lewisje** [comment]
Chris has a history of merging code from gorhill, sometimes without crediting him; he should get around to another round of that soon.

**Comment by foobar13373** [comment]
Development of uBlock (not Origin) has slowed down in the last weeks without further comments and I saw rumours that it became a cowcash and iOS focused. What is going on here? I seriously consider switching to uBlock Origin if we do not hear anything regarding this.

**Comment by RoxKilly** [comment]
How would it be a cash cow on iOS?  Is it being sold for $ in the App Store and does it have a lot of buyers?

**Comment by foobar13373** [comment]
@RoxKilly Actually I'm wondering this, too. Have a look in this issue: https://github.com/chrisaljoudi/uBlock/issues/1481 where this is claimed. That's why I said rumour and not fact.

**Comment by tenkuu** [comment]
I'm guessing it's a cash cow because Chris accepts donations but hasn't done anything recently.
It's iOS focused because he's working on an extension for iOS's new content blocking API.

**Comment by hackel** [comment]
@lewisje @foobar13373 Please stop spreading such fud.  This drama was all resolved long ago.  Chris isn't trying to make money or take credit for work that is not his own.  He's trying to pay for real-world hosting costs and was simply new to Github and wasn't familiar with how to migrate work from another repo while maintaining the correct authorship.  Everything is good now.

Please, join the uBlock development team, get write access to this repository, and import those changes yourself.  That is what is going to keep this project alive, more contributors and people working on it besides just @gorhill in his own repo.

**Comment by marsfan** [comment]
@foobar13373 @tenkuu hackel has a point. Just because of donation requests does not mean he is greedy. The lack of releases is a little weird. I suppose that looking at commit history is a better indication if progress though. 

@hackel if I knew how to add the stuff to the repo. I would have done that. But I only know a little python. Instead I thought I might file a feature request instead just to get the idea out there. I may look into the code and try to teach myself a new language, but I would rather trust the project to skilled people,  like the devs. Though I hate to say it,  responses simply saying a statement is wrong and then basically saying "do that yourself" (even if that was not your intent,  but it can come across that way) is what helps perpetuate these stupid rumors and give people something to latch onto. 

One again,  I don't believe the rumors because they are founded on tiny,  pointless arguments, but I can see why they spread and I will try to help dismiss them.

**Comment by Gitoffthelawn** [comment]
After reading publicly available documents and watching the nice video Chris has posted to YouTube, I must agree 100% with @hackel .

**Comment by hackel** [comment]
@Marsfan I wasn't trying to target you specifically.  I certainly support this request, as does every member of the uBlock development team, I'm sure.  Unfortunately something like this does take a bit of time and effort to accomplish, and everyone is donating their free time.  I just don't think that there was any actual decision _not_ to pull in the latest changes from gorhill (aside from a few specific features which were oddly and unfortunately removed).  People always get busier during the summer.  Hopefully we'll see some progress soon.

**Comment by marsfan** [comment]
@hackel no worries. I understood you weren't targeting me. I just was trying to explain why some of the rumors abound.
