### ISSUE TITLE
[REQUEST] request log constantly updating

### ISSUE THREAD

**Issue by marsfan** [uBlock-LLC/uBlock#1488]
The single biggest issue I have with ublock right now is that when I open the request log, I can only see requests that happen after I open the log. 
Would it be possible (from a technical, or resource conserving perspective) to have the request log update in the background so when I open it, I can see the previous requests.

P.S. I know about the reload page button, but what if something I am doing will be erased or damaged by  reloading, and I want a quick overview of what is going on behind the scenes.

**Comment by lewisje** [comment]
IIRC the reason the request log isn't always running is that it impairs performance.

**Comment by foobar13373** [comment]
I missed this too. Let the user decide whether to enable backlogging or not: in advanced mode display  a counter input that lets the user set if and how far back he wants logging (counter == 0 means disable, like it is now).

Use case: actually I'm sometimes in situation where reloading the page to trigger the logging does not help. Especially on pages where POST data had to be send and I don't want it to be resend (no way to get the logs). Or on pages that switch dynamically between domains (randomly pick ad or badware domain - these will be different the next time). In these cases an auto-log would be really great.
