### ISSUE TITLE
translation?

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#149]
Is there any german translation in planning?

how can I do that?

**Comment by ialexsilva** [comment]
You may contribute by helping to translate this project. I created an entry on Crowdin https://crowdin.net/project/ublock, where you may contribute to the translation work.

**Comment by gorhill** [comment]
German translation is already taken care by @tlu1024 [here on Github](https://github.com/gorhill/uBlock/tree/master/_locales/de), not avaliable on Crowdin to avoid duplicate work.

**Comment by ghost** [comment]
found! I was a little bit confused about Crowdin and Github

thanks ...
