### ISSUE TITLE
Cannot get disqus to load on a site

### ISSUE THREAD

**Issue by nomisunrider** [uBlock-LLC/uBlock#1490]
I have disabled all filters in ublock, but still cannot get disqus comments to load on this website.

twincities.com

Many articles have reader comments via disqus,and no matter what I do with ublock, I cannot get disqus to load.

Here is an example article that has comments:

http://www.twincities.com/localnews/ci_28455940/lake-elmo-freezes-new-home-construction?source=rss

**Comment by sxflynn** [comment]
Here's another example http://www.politico.com/story/2015/07/insiders-say-scott-walker-is-dominant-in-iowa-119942.html?hp=t1_r#superComments

**Comment by publicarray** [comment]
If you are using dynamic filtering just add: `* disqus.com * allow` and `* disquscdn.com * allow` in the "My Rules" tab.

**Edit**
In the urls you have given  I could no find disqus in them. I used http://blog.disqus.com/post/123065919665/our-colorful-community#disqus_thread instead

**Comment by nomisunrider** [comment]
If you load my link in incognito mode on chrome with no addons, you will see the comments at the bottom are powered by disqus.

Adding those options to My Rules did not allow the comments to load.

Regarding your edit, I suspect you have an addon blocking the comments

**Comment by publicarray** [comment]
Unfortunately I don't have the time to look through 60+ hostnames but, you can create your own filters described [here](https://adblockplus.org/en/filter-cheatsheet) and [here](https://github.com/chrisaljoudi/uBlock/wiki/Filter-syntax-extensions). Alternatively you can [whitelist](https://github.com/chrisaljoudi/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button) the domain.

**Comment by gorhill** [comment]
Try:

```
! 04/08/2015, 08:01:46 twincities.com
@@||s.thebrighttag.com/tag$script,domain=twincities.com

! 04/08/2015, 08:02:51 twincities.com
@@||s.btstatic.com/tag.js$script,domain=twincities.com
```

This should be reported to EasyList maintainers so that everybody can benefit from the fix: https://forums.lanik.us/viewforum.php?f=64.

Those filters are to counter `||thebrighttag.com^$third-party` and `||btstatic.com^$third-party` in EasyPrivacy.
