### ISSUE TITLE
AdBlock+ like counter of hits and selective rules enablement/disablement

### ISSUE THREAD

**Issue by birdie-github** [uBlock-LLC/uBlock#1493]
Currently there's no way to see how many times certain rules have been used and also there's no way to enable/disable certain rules.

That would be helpful.

Thank you!

![easylist](https://cloud.githubusercontent.com/assets/4958603/8636775/a7e98fde-288c-11e5-9a50-0fdeb77ecc22.png)

**Comment by lewisje** [comment]
The _only_ ad-blocking extension I know of that has that feature is the Firefox version of Adblock Plus; this would be nice to have in general but I just wanted you to have more context.

**Comment by Gitoffthelawn** [comment]
@lewisje To which feature that @birdie-github mentioned are you referring?  @birdie-github spoke of the hit counter and also the ability to enable/disable certain rules.

I find both features in AdBlock Edge / AdBlock Plus to be very useful.  I believe there was originally a CPU-usage reason for omitting the former feature in uBlock; I have never read a reason the latter feature is not available.

My personal preference would be a hit counter that can be toggled (like ABE / ABP) and the ability to enable/disable individual and groups of rules (especially within custom filters).

**Comment by lewisje** [comment]
Sorry, I was referring to the one that allowed the enabling and disabling of certain rules, although I also think the per-rule hit counter was only ever implemented in ABP for Firefox and its derivatives (like Adblock Edge and Adblock Latitude).

BTW in case the OP wasn't aware, ABP for platforms other than Firefox was not a derivative of ABP for Firefox; most of them were actually built on an old Chrome extension called AdThwart after its maintainer decided to stop maintaining it and let Palant & Co. take over, and although most of the old AdThwart code has been re-written by now as part of an effort to achieve feature parity with ABP for Firefox, they still haven't re-implemented the per-rule hit counter or the ability to disable particular rules (so it's not like it was something that once was there that they then took out).
