### ISSUE TITLE
Fanboy+Easylist-Merged Ultimate List do not update in long time?

### ISSUE THREAD

**Issue by phuc365** [uBlock-LLC/uBlock#1494]
I have tried to update it <i>(Fanboy+Easylist-Merged Ultimate List)</i>, but it always is version 01 June 2015.

Is there a way to update it? This error only on uBlock.

<b>Thank you for your interest.</b>

**Comment by gorhill** [comment]
> but it always is version 01 June 2015

How do you find out about the date?

**Comment by ghost** [comment]
Firefox, middle clicking on list name? Try left click.

**Comment by phuc365** [comment]
I tried left click, and it has been updated. Thank you so much.
