### ISSUE TITLE
Element hiding not working

### ISSUE THREAD

**Issue by rogama25** [uBlock-LLC/uBlock#1495]
http://simple-adblock.com/faq/testing-your-adblocker/
There you can see that element hiding is not working. I use Firefox 39 and latest version of uBlock from this GitHub :D
-Sry. English is not my 1st language :)-

**Comment by lewisje** [comment]
That page works for me; have you enabled the option "Parse and enforce cosmetic filters" in the "3rd-party filters" tab?

**Comment by publicarray** [comment]
I can reproduce with v.0.9.5.0 with default filter lists on mac OS X 10.10.4 and Firefox 39. However this problem does not seem occur in unlock origin.

**Edit**
The static filter responsible is: `/adbanner.` found in: EasyList and Fanboy+Easylist-Merged Ultimate List‎
