### ISSUE TITLE
youtube ads

### ISSUE THREAD

**Issue by jamdox** [uBlock-LLC/uBlock#1496]
youtube ads getting through in safari, updating filters doesn't help

**Comment by publicarray** [comment]
I don't see any ads on youtube however I am using the HTML5 player. Also see [CONTRIBUTING.md](https://github.com/chrisaljoudi/uBlock/blob/master/CONTRIBUTING.md#submitting-issues)

**Comment by AdrianKoshka** [comment]
Same as @publicarray, and not seeing any adds, though am using HTML5 player and http://youtube.com/testtube

**Comment by jamdox** [comment]
Thanks, switching to html5 worked.
