### ISSUE TITLE
whitelist google ad network

### ISSUE THREAD

**Issue by Ugator** [uBlock-LLC/uBlock#1497]
I want to see all ads delivered via the google ad network (i.e. everything from the Google Display Network), but not be tracked by other trackers than google or see other networks ads. Is this possible?
I  added the following static filters:
@@||_google_
@@||doubleclick.net
@@||google-analytics.com
@@||google.com
@@||googleapis.com
@@||googleadservices.com
@@||googlesyndication.com
@@||googletagservices.com
@@||googletagmanager.com
@@||googleusercontent.com
@@||gstatic.com
@@||ggpht.com
these domains are also dynamically allowed. Still ads are not displayed, what can I do?

**Comment by lewisje** [comment]
I think what you need are element-hiding whitelist rules, like `#@#.GoogleAd` (look inside EasyList for more ideas).
