### ISSUE TITLE
Dynamic Filtering Rules - 3rd-Party Blocks all content

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1498]
I have an odd issue that seems to have only appeared in a recent update:

Setting `* * 3p block` in the Dynamic Filtering Rules blocks all 3rd-party content- which is to be expected. I use this feature, then optionally allow specific domains when pages stop working, (often domain specific cdns). However, recently, `* * 3p block` seems to block everything- css, images, scripts hosted by the domain I'm visiting, essentially everything that isn't the raw text of the page.

This isn't how uBlock Origin operates, or indeed how uBlock used to operate. As far as I understand it, setting `* * 3p block` in the Dynamic Filtering Rules should block any domain that is not the domain you're currently visiting from connection, unless you specifically allow it for that domain or globally.

I've turned off all the other filters, so I know its not a rogue 3rd-party filter that is being overzealous.

**Comment by publicarray** [comment]
I am unable to reproduce the issue:
![1498](https://cloud.githubusercontent.com/assets/5497998/8764343/c3890484-2e15-11e5-9259-5ae8dec913d0.png)

Is it possible that another extension is interfering? Without more information there is little we can do to help you.
What browser are you using? Do you have any other dynamic filter rules? what are they? any specific website where this is not working?

**Comment by ghost** [comment]
I've worked out what was causing the issue- I'd added [shutup.css](http://stevenf.com/shutup/shutup.css) as a custom filter, which was killing every page. Not sure, why it was the offender, but- at least now I know.

**Comment by publicarray** [comment]
Glad that it is solved :+1: I had a look at [shutup](http://stevenf.com/shutupcss/) it seems to be a custom stylesheet not a block list for ublock or adblock. If you still want to use it you can refer to [their website](http://stevenf.com/shutupcss/) on how to install it. 

To prevent this from happening in the future, I recommend that ublock does some additional checking to see that the file is indeed a valid block list file.
