### ISSUE TITLE
uBlock crashing websites

### ISSUE THREAD

**Issue by chlendim** [uBlock-LLC/uBlock#1501]
Recently I noticed that some of the websites start crashing and giving this screen.
![Image of the crash](http://s14.postimg.org/xjq3rudnl/crash.png)
and this was on twitch website

I did some research and find out that uBlock is causing that.
after some more testing it turned out that  any EasyList‎ filter if activated will cause this problem but if I don’t activate them, lot of ads pass through and show up

**Comment by louisch** [comment]
I can confirm on that on Firefox 39.0, the EasyList filter with uBlock is causing many sites to not load.

Sites that do load include Google, Wikipedia, Facebook, Reddit.
Sites that do not load include Wikia, Crunchyroll, and seemingly a lot of sites with large banner ads.

**Comment by RoxKilly** [comment]
Is the problem with uBlock or with the Block Lists?  Would be interesting to know whether AdBlock Plus/Edge with the same block list also breaks the sites.

**Comment by chlendim** [comment]
i think its just with the Easylist filter
because i have disabled Easylist filter 2 days ago and i didnt get any crash since
