### ISSUE TITLE
[Request] Easier rule creating/editing

### ISSUE THREAD

**Issue by rayman89** [uBlock-LLC/uBlock#1502]
Besides the element blocker UI which is nice creating rules or editing them is very very far from intuitive from the perspective of a user that know nothing about css html or however it's called.Reading the wiki or other documents some users posted doesn't make things easier for us either. When the element blocker UI fails (does not block exactly what you want or makes a very specific rule that works only on that page load) we are out of luck. So I was wondering if you could improve the user experience for us and create something that makes customizing and creating rules easier for example making a wizard that starts with what the blocker UI has and ask you question that direct you towards creating that rule.

**Comment by RoxKilly** [comment]
You may be interested in uBlock Origin's approach to this problem.  For the life of me I can't figure out how to accurately write my own blocking rules and that has helped.  Check out the [release notes](https://github.com/gorhill/uBlock/releases) to version 1.0.0.0 of uBlock Origin.

**Comment by rayman89** [comment]
Thanks for your response. I know about origin but the IMO the developer is really close minded and hard to deal with so that project has no feature. I think this feature would make the add.on more accessible to a lot of inexperienced users so i would like for it to be considered.
