### ISSUE TITLE
Safari 9.0 uBlock toolbar button opens a box with raw HTML instead of uBlock interface

### ISSUE THREAD

**Issue by gco** [uBlock-LLC/uBlock#1503]
On Safari Version 9.0 (11601.1.39.0.2), clicking the uBlock toolbar button results in a box containing raw HTML instead of the uBlock interface.

```
<!DOCTYPE html>
<html>

<head>
<meta name="viewport" content="width=470"> <!-- When showing as a tab in fennec, scale to full size (150px + 320px)-->
<meta charset="utf-8">
<link rel="stylesheet" href="css/common.css" type="text/css">
<link rel="stylesheet" href="css/popup.css" type="text/css">
<title>uBlock</title>
</head>
...
```

**Comment by heubergen** [comment]
+1 have the same issue here.
Also Safari 9.0

Had to change to a other add-on temporally

**Comment by ghost** [comment]
Tried disable and then re-activate the add-on?

**Comment by heubergen** [comment]
Hmm, seems to work now again.

Will reopen it if needed.
