### ISSUE TITLE
Can't use the elementer selector on hltv.org

### ISSUE THREAD

**Issue by Ulver84** [uBlock-LLC/uBlock#1505]
Hi there :) For some reason I can't block on this specific site. See video for an example (19 seconds long)
https://youtu.be/vTcdtMPKSc8

Kind regards, Martin

**Comment by Ulver84** [comment]
Now it works for some reason, but I can't select the background image which is what I wanted to block, since it takes me to a new site, and I keep hitting it by mistake. Any ideas? :)

**Comment by publicarray** [comment]
This specific rule has to be set manually. Just add the following into `My Filters`
`||static.hltv.org//images/hltv_siteskin8-1.png`
I tested this in chrome but in safari it doesn't work and the image doesn't show in the logger either.
If you want to create your own filters please read https://github.com/chrisaljoudi/uBlock/wiki/Filter-syntax-extensions

**Comment by Ulver84** [comment]
Thanks a lot! :)
