### ISSUE TITLE
Question: filter syntax with verbatim text

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1507]
I have a filter specified as `/avatar/` and get uBlock triggered by `https://encrypted.google.com/search?hl=en&q=avatar` or any other `avatar` text in the URI, but expected it to be triggered by something like e.g. `domain/avatar/file.extension` only. I've looked at https://adblockplus.org/en/filter-cheatsheet and https://adblockplus.org/filters for description of such behaviour, but couldn't find anything related. Could you comment on this?

**Comment by seanrand** [comment]
You'll have to specify it as `/avatar/*` otherwise the filter will be interpreted as a [regex](https://adblockplus.org/filters#regexps).

**Comment by ghost** [comment]
Correct, thank you!
