### ISSUE TITLE
[REQUEST] Faster Mirror(s)

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1508]
Could you do a faster mirror(s) ? Updating lists takes a while. 
You could have a mirror on DigitalOcean for $5/mo. for example.

**Comment by publicarray** [comment]
As an alternative I suggest asynchronous loading of the filter lists.

**Comment by ghost** [comment]
@publicarray Thanks, but having an official mirror for this lists would be much better.

**Comment by lewisje** [comment]
I don't think we need yet another reason to beg for donations; also for the traffic these lists get, I doubt a $5/mo. package will work, and instead we'd get blocked for exceeding our monthly bandwidth allocation.
