### ISSUE TITLE
EasyList China in uBlock blocks Gmail contents

### ISSUE THREAD

**Issue by v998** [uBlock-LLC/uBlock#151]
Comparison  for both ABP and uBlock only enabled the same filter
(all emails contents are blocked) (tested on different emails and gmail accounts)
ABP EasyList China only:
![image](https://cloud.githubusercontent.com/assets/7825360/3897967/a32ef0ba-2266-11e4-895e-7cbbf934ddd8.png)

uBlock  only enabled CHN: EasyList China (中文) (adblockplus.org) 
![image](https://cloud.githubusercontent.com/assets/7825360/3897979/bef77b8c-2266-11e4-8d08-15057ae09b3e.png)

Not knowing why that happens..

**Comment by gorhill** [comment]
There is this filter in EasyList China: `~car.kdslife.com,kdslife.com,pchome.net##div[class^="ad"]`.

`~car.kdslife.com##div[class^="ad"]` would normally mean hide `div[class^="ad"]` everywhere except on `car.kdslife.com`, as per ABP doc. But as per ABP's behavior, it appears the real definition is more complicated.
