### ISSUE TITLE
So this addon is officially abandoned? (Answer: No. "Still minimally maintained")

### ISSUE THREAD

**Issue by user65478** [uBlock-LLC/uBlock#1513]
Hi,
as far as I understood, uBlock is the main project and uBlock Origin is just a personal fork by gorhill where he implements features for his own. However, recently uBlock Origin was developed very actively and got very popular on addons.mozilla.org (lots of positive reviews), while uBlock is stagnating and on addons.mozilla.org there is only an outdated, non-reviewed version of this addon.
I'm just asking for whether this project is officially abandoned, or the developers just went on holiday and will continue development in the near future. I don't want to put pressure on the developers, they can decide to stop developing whenever they like. However, at least it would be fair to announce the  abandonment of this addon, so that the users know whether it's safe to use this addon or if we should search for alternatives. (If it's abandoned, it may contain unfixed (security) issues or be incompatible with modern browser versions)
Speaking of alternatives, is it recommended to switch to uBlock Origin? Does it contain any raw edges as it's a personal fork by grohill only?
P.S. I have read that uBlock Origin is mainly developed for Chrome while uBlock is mainly developed for Firefox. Is this true? Is uBlock Origin recommended for Firefox also?

**Comment by publicarray** [comment]
> I'm just asking for whether this project is officially abandoned, or the developers just went on holiday and will continue development in the near future.

https://github.com/chrisaljoudi/uBlock/issues/1506#issuecomment-127073916

Chis is working on an iOS ad blocker, [Purify](https://www.reddit.com/r/apple/comments/3b1xz3/sneakpeek_at_purify_adblocking_and_more_on_ios/), which is discussed in #1439 

> Does it contain any raw edges as it's a personal fork by grohill only?
> Is uBlock Origin recommended for Firefox also?

https://github.com/gorhill/uBlock/wiki/uBlock-vs.-uBlock-Origin:-Facts

**Comment by RoxKilly** [comment]
I have used both; I currently have uBlock installed on my phone and tablet; uBlock origin on my laptop.  I don't find Origin particularly rough around the edges.  I'm a fan of both add-ons.  I wrote mainly to say that Origin works just find on Firefox.  You can see from its updates page that the Firefox add-on (the .xpi file) is released along with the other versions (https://github.com/gorhill/uBlock/releases).

For the vast majority of users, the two add-ons will be equally helpful in my opinion.  The add-ons distinguish themselves on features revealed only to users who enable the "I am an advanced user" checkbox in the add-on options.  uBlock Origin is growing faster than uBlock in offering advanced blocking/filtering options.  Again, this won't affect most people, and these features have a cost of their own: the more bloated a piece of software gets, the harder it is to maintain, debug, and keep secure, and the more resources it's likely to use (memory, CPU cycles etc....).   I don't know whether uBlock Origin falls relative to uBlock on those parameters so this is just a general observation

When choosing between the two, I think the most important factors are:
(1) how active is development (Origin clearly wins here)
(2) how will the add-on deal with the fact that Firefox will soon block all add-ons that have not been approved by Mozilla (https://wiki.mozilla.org/Addons/Extension_Signing).  The add-on just won't work unless the developers can get Mozilla's green light

**Comment by Gitoffthelawn** [comment]
My understanding is the same as that provided by @RoxKilly: "for the vast majority of users, the two add-ons will be equally helpful".

Here is a good reddit post about the separation: [reddit post](https://www.reddit.com/r/apple/comments/3b1xz3/sneakpeek_at_purify_adblocking_and_more_on_ios/csi6a2a)

This project, uBlock, appears to be very open to anyone contributing, and has a welcoming, friendly, and helpful atmosphere.

I have read that this project is in the queue to get fully approved by Mozilla, so @RoxKilly's concern about that should be resolved before it becomes an issue.

In my opinion, what this project really needs right now is for one or more qualified people to merge some of the changes that have been made in the uBlock Origin fork into this project.  As @RoxKilly pointed out, most people will not notice the differences, but expert uses will likely appreciate them.

Hopefully, this project will develop as a community to reflect the needs of developers and users alike.

**Comment by user65478** [comment]
I have found a statement from August 2 at addons.mozilla.org from one of the developers (well hidden in an answers to a [review](https://addons.mozilla.org/de/firefox/addon/ublock/reviews/731998/)):

> uBlock is still minimally maintained, but if you are looking for more active development and new features, you may wish to consider the uBlock Origin branch

So it looks like this addon is heading towards a slow death and my assumption ("uBlock is the main project") was completely false. Your answers also indicate that uBlock Origin works fine with Firefox, so I think I'll give Origin a try in the near future.

**Comment by Betsy25** [comment]
Since Gorhill gave away the main project, uBlock hasn't been alive for a single minute, so why talking about a slow death ?

**Comment by gorhill** [comment]
> gave away

Transferred maintainership.

**Comment by user65478** [comment]
I just encountered the first raw edge of uBlock Origin. It blocked access to SourceForge.net. First I was shocked and thought SourceForge.net was taken over by hackers (and then it was put on a malware domain list included in uBlock Origin). I searched Google for a news article about a recent hacker attack towards SourceForge.net but I couldn't find one. Then I found out that SourceForge.net is blocked by uBlock Origin all the time because the author personally doesn't like SourceForge.net for some reasons (actually I think in particular he doesn't like the bundled adware that was included in some of the downloads. However, that's all in the past. [This is not an issue any more](https://sourceforge.net/blog/project-mirroring-policies-will-be-revisited-with-our-community-panel-existing-mirrors-removed/)). 
Conclusion: This supported my impression that uBlock Origin is a personal fork only. And you should be aware of some unexpected behaviors.

**Comment by alejandrolemus** [comment]
> because the author personally doesn't like SourceForge.net for some reasons 

Maybe because there is a [reason](http://safebrowsing.clients.google.com/safebrowsing/diagnostic?site=sourceforge.net/) ?

![sf](https://cloud.githubusercontent.com/assets/9505902/9156657/88e257e0-3eaf-11e5-9227-5b916975d97b.JPG)

**Comment by Gitoffthelawn** [comment]
By that rationale, [github would also need to be blocked](http://safebrowsing.clients.google.com/safebrowsing/diagnostic?site=github.com/):

![screenshot - safebrowsing clients google com - 2015-08-09 15-16-31](https://cloud.githubusercontent.com/assets/7672848/9157208/ba0f513e-3ea9-11e5-9aca-3b8f4f07d0bf.png)

**Comment by alejandrolemus** [comment]
@Gitoffthelawn fair enough. I was just responding to the 'is all in the past now' part, and honestly, how this makes uBlock Origin 'raw on the edges', 'personal fork' and gorhill somehow biased or vindictive.

Someone goes to try Origin and the thing that strikes him the most is the blocking of Sourceforge? Not the strict blocking mode functionality, which BTW has a big button to disable it. I guess that came across as fishy. Apologies if that's not the case.

I get that some people dislike gorhill's communication skills, but I don't get the constant need to compare/attack/diminish either version. Lets not forget that he is the creator of uBlock (both, actually) and the one that has made, and is still making, most of the development. Neither project is perfect, so everybody should be using the one that fits them better, and stop the snarky comments.

/rant

**Comment by user65478** [comment]
@alejandrolemus: Actually the main issue is that is was not clear to me why sourceForge was blocked. I really thought this was something serious (like a hacker attack). There was no information why this website was blocked. It just showed a [generic warning message](https://cloud.githubusercontent.com/assets/585534/8160013/14466ca0-133a-11e5-8d3c-28169288f35a.png) I could rule out that this is a false positive because of the filter rule _||sourceforge.net^$other_. (If you add a filter rule like _||blabla^$other_ then it's definitively meant to block the whole website, not just accidentally)
So a hacker attack seemed the only reasonable explanation to me. Would you just click on "ignore" under these circumstances? 
Later, after looking into the filter definition list, I found a comment that "the purpose is to at least ensure a user is warned of the risks ahead" only. The warning message that I was shown, however, never told me that...
So I would definitively call this "raw on the edges", but you are right, there are some legitimate reasons for this. And I appreciate that gorhill wanted to warn users about unwanted software distributed by sourceForce.net. But communication was suboptimal in this case, that's true. I have created a [separated issue](https://github.com/gorhill/uBlock/issues/583) for this.

**Comment by alejandrolemus** [comment]
> Would you just click on "ignore" under these circumstances?

No, I would investigate, like you did. And then appreciate the fact that uBlock warned me.

> there are some legitimate reasons for this. 
> And I appreciate that gorhill wanted to warn users about unwanted software distributed

Exactly!

> I have created a separated issue for this.

And that's a much better way to contribute, IMHO. And again, humble apologies for the obvious misjudgment.

**Comment by gorhill** [comment]
@user65478 

> Conclusion: This supported my impression that uBlock Origin is a personal fork only. And you should be aware of some unexpected behaviors.

You bought into the utterly meaningless "personal fork" meme.

uBlock June 2014 - April 2015: personal project of @gorhill.
uBlock Origin May 2015 - present: personal project of @gorhill.
uBlock May 2015 - present: personal project of @chrisaljoudi.

**Comment by zummuz** [comment]
> So this addon is officially abandoned?

It will never be officially abandoned because maintainer wouldn't be able to collect donations then.

> Actually the main issue is that is was not clear to me why sourceForge was blocked.

Hi, at first you can temporary allow with one button, you can permenently allow with one other button, you can turn off gorhill's uBlock filters – Badware risks‎ (its name already tell us why sourceforge was blocked) which contains just 3 entries for now. Its mouse only solutions, you can make exception rule too. Also you can open that filter and read:

 2015-06-18: http://www.information-age.com/industry/software/123459675/hotbed-malware-another-blow-sourceforge-google-discovers-588-pages-malicious-software
 2015-06-02: https://blog.l0cal.com/2015/06/02/what-happened-to-sourceforge/
 2015-05-28: http://libregraphicsworld.org/blog/entry/anatomy-of-sourceforge-gimp-controversy
 2015-05-17: http://lifehacker.com/antiadware-gets-rid-of-bundled-crapware-on-popular-down-1702818594
 2015-03-11: http://blog.emsisoft.com/2015/03/11/mind-the-pup-top-download-portals-to-avoid/
 2015-01-21: http://www.howtogeek.com/207692/yes-every-freeware-download-site-is-serving-crapware-heres-the-proof/
 2014-11-25: http://blog.tedd.no/2014/11/25/sourceforge-malware/
If this don't enough just google or follow topics about sourseforge on reddit.

> Speaking of alternatives, is it recommended to switch to uBlock Origin? Does it contain any raw edges as it's a personal fork by grohill only?

Check out those projects changelogs: chris slightly reskinned uBlock and focused on safari support because he can't compete with uBlock Origin. If there is no code then there will not be raw edges in it, so yeah, gorhill's uBlock Origin might have some bugs because project is in active development but he fixes them.

It wont be surprise for me if Purify will be non-free and im pretty sure chris hasnt rendered it from scratch.

P.S. english is not my native so I'm sorry if this post looks harsh. No offence I just wanted to help.

**Comment by LimboSlam** [comment]
To add, no this is not abandonedware because if you look closely at commits being actively made they are still (@chrisaljoudi, @AlexVallat) maintaining it and preparing for the next release.

**Comment by ebelinski** [comment]
Ok, is this abandonware _now_?
