### ISSUE TITLE
blocks background video that is no ad

### ISSUE THREAD

**Issue by Jurek-Raben** [uBlock-LLC/uBlock#1514]
Hi,

the recent uBlock for Firefox (on OSX) blocks the background-video on this page: 
www.virtualcreations.de

But the video there is not a commercial or ad, it's part of the design. Why is this now blocking? Can you fix it?

Thx!

**Comment by elyrly** [comment]
I tested the website on the most recent uBlock and couldn't recreate the issue. Can you let us know which filters your using along with custom filers? The background-video needs to be heavily optimized, even with a powerful mac the video is ramping up CPU usage.

**Comment by Jurek-Raben** [comment]
works now here again. thanks for checking.
