### ISSUE TITLE
[bug] Javascript error in vapi-background.js

### ISSUE THREAD

**Issue by Gitoffthelawn** [uBlock-LLC/uBlock#1515]
Javascript error: 'tabBrowser.tabs is undefined' in vapi-background.js in the loop beginning with 'for ( var tab of tabBrowser.tabs )'.

Tested using Firefox 40.

**Comment by Betsy25** [comment]
Was fixed on uBlock Origin with commit https://github.com/gorhill/uBlock/commit/8e4f998a329998e3ce0d9b38e3abe72402092531

**Comment by AlexVallat** [comment]
Is that the same bug, are you experiencing this when viewing page source? Also, is this actually causing any issues, or just showing in your error log?

**Comment by Gitoffthelawn** [comment]
@AlexVallat I am experiencing it in general, not when viewing page source.

I do not know if it is actually causing any issues.  Firefox seems slower, and the disk cache seems to be churning more than usual (I cleared it, but that did not help).  I do not know if either or both of those are related to this bug.

**Comment by AlexVallat** [comment]
The only matching bit of code I could find was https://github.com/chrisaljoudi/uBlock/blob/master/platform/firefox/vapi-background.js#L352 which occurs during window closing. If you are experiencing it in general, as in not when closing a window, then there is something odd going on with your firefox where it is closing windows which do not have tabs. In itself, it is harmless - the code that will fail to run is cleanup code, and if there were no tabs in the window then there's nothing to cleanup anyway.

It might, however, be a symptom of some other problem that is causing performance issues. If something is constantly opening and closing unusual Firefox windows then that's not likely to be good.

**Comment by Gitoffthelawn** [comment]
@AlexVallat I think that's the piece of code I found too.

I was working on another project, and noticed the error in the console, and posted it here.

Unfortunately, I didn't have time to take a closer look at it to see under which conditions the error is triggered.  I doubt I'll have any experimenting time in the near future, so hopefully other users will be able to take a look at their browser consoles and see if they experience the error as well.
