### ISSUE TITLE
incompatible with Firefox Beta 41

### ISSUE THREAD

**Issue by MisterX2000** [uBlock-LLC/uBlock#1516]
uBlock 0.9.5.0 is incompatible with Firefox Beta 41.0b1
I think because of the new Add-on signing in Firefox (http://mzl.la/1J7Lcsp)

**Comment by Gitoffthelawn** [comment]
There should be a pref in Firefox 41's about:config where you can turn off the signing requirement.

**Comment by 5t3f4n** [comment]
If you are referring to `xpinstall.signatures.required`, that is only a temporary workaround. This setting will be removed in version 42.

**Comment by Gitoffthelawn** [comment]
@5t3f4n Yes, unfortunately that is their plan.  But hopefully Mozilla will be done signing everything before 42 is released, or change their minds.
