### ISSUE TITLE
Safari 9.0 (11601.1.43) El Capitan Beta - Youtube ads are playing/unskippable

### ISSUE THREAD

**Issue by ecchi** [uBlock-LLC/uBlock#1518]
I've tried refreshing block lists, but the problem seems to have taken place since El Capitan. Same blacklists are used on Yosemite main-machine without issue. Chrome Stable on El Capitan (basically same lists) don't have this problem either. Seems exclusive to El Capitan Safari 9? Can't verify don't have any other test configs running the beta.

**Comment by nuno-agostinho** [comment]
I also have this issue in El Capitan's Safari 9.0 (11601.1.43).
