### ISSUE TITLE
Javascript-injected Ads Foil Filters

### ISSUE THREAD

**Issue by tinoesroho** [uBlock-LLC/uBlock#1519]
As seen on tinypic.com and photobucket.com

This nasty bit of js-based ad injection has been able to foil my filters. NoScript, it turns out, did nothing to block the javascript file from loading.

At first it was loading as an external .js file, but now it's inline.

The script randomizes the div name, as far as I can tell, and then inserts a div containing ads.

try{(function(A){var R=A+'tr',g="gDeoetenwdNnrpcscya8FUtsaceagTBteeEewprsteeEtec/o.au/:th)j+-90-za(ISlahtms.8qhf4lmcnccr2c3rda656582df6b01ed-1b4f5da781/ptwlmzorjxp_mdawuteaiclgwOenwiochrewotclteuowtMeoteawrwnsw-TwerhwmNaysnmltgticwnmlearwmcpjm/ptws.]_-ZA-[=Clgwcawjzorjxp/o.dka.f.5.216f0e2f8c6f84eddc98c2fc3b/:thw__8qhf4lwonrer=tvtAlafxdiekowcasniaownmcdhawrfBrsiaspliteE6qcharAtAE7",r=g[R](349),W=164,t=g[R](r.length+2,W),E=g[R](W--+2);for(;W>=0;W--){r+=t[g[R](340,6)](W)+E[g[R](340,6)](%28W+157%29%164)}r=W=t=E=g=r[g[R](331,5)](g[g[R]%28340,6%29]%287-W%29);var a=window,b=a[r[0]],c=a[t[1]];
    if((0<=(a[g[2]][t[3]]+c[t[4]])[W[5]](g[6])||0.1>=b[W[7]]())&&!a[r[8]]){a[W[8]]={sm:t[9],lv:346,lal:0.1};var d=t[10],e=c[E[4]][W[11]](g[12]);e&&(d=t[13]+e[1]);var f=c[W[14]](g[15]),h=c[W[16]](g[15])[0];f[t[17]]=r[18];f[g[19]]=!0;f[t[20]]=d+t[9];h[W[21]][g[22]](f,h)};})("subs")}catch(d){};

**Comment by gorhill** [comment]
Filters foil javascript injected ads:

```
photobucket.com##.sidebar > div:first-of-type
tinypic.com##.browse.columns > div:first-of-type
```

**Edit:** as per issue title, I had assumed it was a difficult case and went straight to the browser inspector, but then I tried the element picker and it made creating the proper filters even more simple. Why not just use the element picker?

**Comment by publicarray** [comment]
@tinoesroho next time when you paste code can you please wrap it in <code>```</code> tags? Github uses [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) and allows for easier reading & syntax highlighting.
