### ISSUE TITLE
DNK: Schacks Adblock Plus liste‎ – old version?

### ISSUE THREAD

**Issue by emilstahl** [uBlock-LLC/uBlock#1520]
Why are you using an old version of DNK: @schack's Adblock Plus liste‎?

If you click on the list in uBlock:

```
[Adblock Plus 1.1]
!
! http://adblock.schack.dk/block.txt
! http://henrik.schack.dk/adblock/
!
! Maintained by: henrik at schack.dk
! Last Modified: 06-10-2014
! Expires: 1
```

If you visit the URL http://adblock.schack.dk/block.txt

```
[Adblock Plus 1.1]
! Homepage: https://henrik.schack.dk/adblock/
! Title: Schacks Adblock Plus liste
! Expires: 1 days
! redirect: http://adblock.dk/block.csv
! Redirect: http://adblock.dk/block.csv
! Version: 61
! Maintained by: henrik at schack.dk
! Last Modified: 14-08-2015
```

As you can see, the list is redirecting to `http://adblock.dk/block.csv`which supports SSL – you can update the link to `https://adblock.dk/block.csv`

**Comment by publicarray** [comment]
This is because of #319. But I checked and the list author has updated the list. The issue seems to be resolved. I can make a PR to enable updates again.

**Comment by emilstahl** [comment]
Thanks @publicarray! :)

**Comment by publicarray** [comment]
No problem, you can leave the issue open until the Pull Request is merged.
