### ISSUE TITLE
Basecamp is broken

### ISSUE THREAD

**Issue by sxflynn** [uBlock-LLC/uBlock#1522]
I'm running Safari 8.0.8 on Mac OS X 10.10.5. I have uBlock 0.9.5.1 by Chris Aljoudi. uBlock is breaking the functionality of the project planning website Basecamp. I am providing screenshots to demonstrate, and have made a public project with a login so you can go in and confirm for yourself. Even disabling all of the 3rd party filters doesn't fix the issue, so it's something more fundamental to uBlock's code that is breaking the site. I filed a support ticket with Basecamp and they said:

> I've been looking at it with one of our programmers and it's only blocking a portion of the page. The element it's blocking is "<section data-new-team>". Our first thought was that perhaps it's blocking all "<section>" elements, but that doesn't appear to be the case. Other <section>'s are rendering fine.

They advised me to file a bug report here with uBlock devs.

Test URL - https://basecamp.com/2656763/projects/10215212/accesses
login email - m8r-rufuc31@mailinator.com
login pass - ublocktest123

Screenshot of uBlock turned on
<img width="887" alt="ublock turned on" src="https://cloud.githubusercontent.com/assets/2034081/9318489/fc6de888-4511-11e5-867d-bbf79a7d7ab5.png">

uBlock turned off
<img width="910" alt="ublock turned off" src="https://cloud.githubusercontent.com/assets/2034081/9318490/fc7d4d00-4511-11e5-98ac-e7564b8db289.png">

**Comment by chrisaljoudi** [comment]
I _just_ pushed uBlock 0.9.5.2 which includes a fix for this. :)

Please it out and let me know whether it fixes the issue.

Thanks!

**Comment by sxflynn** [comment]
Are you kidding me? That was fast. Yes it is fixed, thanks!

**Comment by pcalves** [comment]
Was having some issues with [Workflowy](http://workflowy.com/) as well, that update fixed it. Thank you! 🙏

**Comment by GarrettAlbright** [comment]
I can confirm that this update fixed Basecamp for me as well.
