### ISSUE TITLE
uBlock doesn't work on Mailchimp

### ISSUE THREAD

**Issue by mravery** [uBlock-LLC/uBlock#1523]
### Steps to reproduce

(This assumes uBlock has been installed)
1. Create a http://mailchimp.com account.
2. Login on Safari.
3. Login on Chrome and note the differences in rendering.
4. On Safari note the errors in the JS Console.
5. Similarly note the errors in the JS Console for Chrome.

Here are some screenshots:

![screen shot 2015-08-18 at 11 39 54 am](https://cloud.githubusercontent.com/assets/1683929/9321829/f6ead3d0-459d-11e5-8658-2a4b0d41c785.png)
![screen shot 2015-08-18 at 11 40 21 am](https://cloud.githubusercontent.com/assets/1683929/9321830/f76cc502-459d-11e5-8106-b955a25d566d.png)
### Other notes

It is not enough to tell uBlock to whitelist the domain; I have to disable the extension for Mailchimp to render properly.

Safari Version 8.0.7 (10600.7.12) on Mac OS X 10.10.4

**Comment by sxflynn** [comment]
Have you tried upgrading to 0.9.5.2? That fixes a lot of Safari related issues.

**Comment by mravery** [comment]
I'm on 0.9.5.2 for uBlock (Should've mentioned this upfront).

**Comment by mravery** [comment]
Rebooted machine. :shrug: Now uBlock works as expected. Closing.
