### ISSUE TITLE
Possible to use uBlock to block full-screen warning on specific sites?

### ISSUE THREAD

**Issue by Gitoffthelawn** [uBlock-LLC/uBlock#1527]
Is it possible to use uBlock to block the Firefox full-screen warning on _specific_ websites?

The ID of the warning screen is `#full-screen-warning-container`, but the request technically comes from `chrome://browser/content/browser.xul`, not the actual site for which the warning is being issued.

The idea here would be to block the warning for specific sites, not all (which can be easily accomplished by toggling `full-screen-api.approval-required`).

**Comment by AlexVallat** [comment]
I don't think so. uBlock can't block browser chrome elements, it's simply not built for that. If the warning had been injected into the DOM of the page content itself, I suppose it might be blockable, but otherwise no.

**Comment by Gitoffthelawn** [comment]
@AlexVallat Thanks Alex.  I'm thinking Mozilla didn't put it into the DOM of the page because then a page could bypass it.
