### ISSUE TITLE
uBlock Origin removes github folder if named facebook

### ISSUE THREAD

**Issue by PuercoPop** [uBlock-LLC/uBlock#1531]
I noticed while finding 'empty' named folder which I coudn't click. If I disable the extension the page renders as normal.

https://github.com/jgeboski/bitlbee-facebook/

**Comment by gorhill** [comment]
For the benefit of other users, to emphase how the logger is the go-to tool in uBlock Origin:

![a](https://cloud.githubusercontent.com/assets/585534/9523157/9ec68680-4ca6-11e5-9524-c9b727503693.png)
