### ISSUE TITLE
Improvements for the UI to become more user friendly and intuitive

### ISSUE THREAD

**Issue by privacytoolsIO** [uBlock-LLC/uBlock#1532]
First of all: Thanks for your great work on uBlock. We recommend your plugin on our [Website](https://www.privacytools.io/#addons).

I have a couple of suggestions to improve the usability:
- Add a link to the dashboard, clicking on the "uBlock Origin" link is not obvious enough.
- Use mouse hover descriptions / titles for all buttons
- The design of the on/off button is not obvious enough, it could use a message like "uBlock is on/off" underneath the big standby icon.

When it comes to usability, there is one basic rule: "Don't make me think" there is even a book about it. Currently uBlock is making the user think a lot, but it's easy to fix the usability issues.

**Comment by Gitoffthelawn** [comment]
@privacytoolsIO  wrote: "The design of the on/off button is not obvious enough, it could use a message like "uBlock is on/off" underneath the big standby icon."

It's not only not obvious, the icon apparently falsely indicates its function.  It does _not_ turn uBlock on/off!  There is no way to completely turn uBlock (or uBlock Origin) on/off except to disable the extension.

The UI of uBlock is it's weakest asset.  I created the [uBlock Deluxe](https://github.com/Gitoffthelawn/uBlock-Deluxe) overlay to improve on the UI.  I originally created it for uBlock Origin, but Gorhill decided to ban me from his repo, so I haven't bothered updating it.  I'll probably update it to work on uBlock (non-Origin) at some point when I have time.  If/when I do, I'll take your recommendations into consideration.

**Comment by RoxKilly** [comment]
@privacytoolsIO 

> We recommend your plugin on our Website.

I like your site (heard about it on the Security Now Podcast). You are mistaken in the quote above however: this page is about uBlock. Your website recommends [uBlock Origin](https://github.com/gorhill/uBlock), a closely related but distinct add-on

**Comment by privacytoolsIO** [comment]
@Gitoffthelawn Thanks for letting me know.

@RoxKilly Oups, my bad.
