### ISSUE TITLE
Not working with Chrome feature Panels

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1533]
When watching Youtube or Twitch.tv streams I get all the commercials playing. Not working neither uBlock or Adblock. It looks like it does block standard image banner ads, but not on streams/videos.

Also using for Panels the Panel Tabs 1.6.1 widget.

**Comment by publicarray** [comment]
If you are using the flash player than ublock can't block these ads. Try the [YouTube HTML 5 player](https://www.youtube.com/html5) instead. Alternatively you can completely [Uninstall Flash](http://occupyflash.org/#resources).

**Comment by ghost** [comment]
YouTube is already HTML5 by default.

**Comment by publicarray** [comment]
Sorry I won't know as I haven't used flash for last quite a while. I have been playing youtube videos without any video ads. What filter list are you using? what browser & version. Please see [CONTRIBUTING.md](https://github.com/chrisaljoudi/uBlock/blob/master/CONTRIBUTING.md)

**Comment by ghost** [comment]
I posted it does not work with Panels, it does work in default browser mode, but not through panels. So lists are fine.

**Comment by publicarray** [comment]
My apologies, I see what you mean now. Ok so panels are an experimental feature on os x , linux and windows. Interestingly the cosmetic filters don't show up in the logger but appear to be blocked in the pannels.
