### ISSUE TITLE
Blocking /advertisers/...

### ISSUE THREAD

**Issue by steinnes** [uBlock-LLC/uBlock#1534]
It seems that your plugin blocks background HTTP calls to URLs containing `/advertisers/` in them.  Is this a feature?  There are sites which have to do with advertisers (not advertisements) which will break because of this.

**Comment by Betsy25** [comment]
Advertisers don't need ad blockers. If they don't want to step in the dirt they spread, they need to search for another job.

**Comment by steinnes** [comment]
So... blindly blocking any URL string with "advertisers" in it, is a feature?

**Comment by Betsy25** [comment]
I guess it's in the lists because in 99.9999% of the cases it is indeed related to ads, but if you somehow stumble on that one occasion which doesn't, it's easy to make an exception filter for it.

**Comment by gorhill** [comment]
> blindly blocking any URL string with "advertisers" in it, is a feature

It's a 3rd-party filter list issue (`/advertisers/*` is in EasyList). If you think it's wrong, bring the issue to the maintainers of the filter list. Personally I do not believe it's wrong: just disable your blocker when you stumble upon such (rare) false positives.

**Comment by steinnes** [comment]
Thanks!
