### ISSUE TITLE
UBlock Origin breaks site

### ISSUE THREAD

**Issue by sorosch** [uBlock-LLC/uBlock#1537]
Hi,

i have UBlock Origin with Forefox 40.0.3.

I have no problems with UBlock on any site - except with www.focus.de.

The upper part of the site looks like:

https://www.dropbox.com/s/ggniweqxd48rc0d/UBlock%20with%20Wirefox.png?dl=0

The rest of the page is normal. When i reload the page (2-20 times) several times then the page loads suddenly correct. 

What could be the reason? Do someone have also this problem?

Thank you very much
Best regards
George

**Comment by gorhill** [comment]
The project here is "uBlock" not "uBlock Origin". [This is uBlock Origin](https://github.com/gorhill/uBlock/blob/master/README.md).

This is a filter list issue, you get the same result with ABP. Report the issue to the maintainers of [EasyList Germany](https://forums.lanik.us/viewforum.php?f=90).

For what it's worth, I use [Medium mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode), and the page rendered better, except for the dynamic inline ads, which I got rid with a custom filter: `||p5.focus.de/img/fotos/crop278923423/1624877250-cv21_9-w324-h244-oc-q75-p5/*-*-*-*.`.
