### ISSUE TITLE
Interest in skipping t.co and similar?

### ISSUE THREAD

**Issue by clipperhouse** [uBlock-LLC/uBlock#1538]
Would it be in-scope of uBlock to include a “resolver” for t.co links? The DOM of Twitter (and Tweetdeck) usually include the destination URL as an attribute on the href’s.

I’ve [implemented](https://chrome.google.com/webstore/detail/better-bird/dolfbfbhjniibjlmpebhdkjanjlcnolp) this in the past, it’s straightforward enough and can be done inexpensively.

**Comment by publicarray** [comment]
Personally I think if it just t.co links than it is out of the scope. I mean you already created an add-on for that feature. However if for privacy/security reasons (so the user can see the destination url) we resolved link shorteners e.g. bit.ly links than I think people can benefit from that. Correct me if I am wrong but isn't there a caveat? To resolve resolve a url we need to make a request which of course can be a privacy concern. e.g. We send a request for a link (that could be logged) that the user potentially never clicked on.

**Comment by RoxKilly** [comment]
If as @clipperhouse mentioned, the destination is listed as an attribute to the Anchor tag, then there will be no need to make any request.  

I would agree though that implementing a feature that serves only one domain is too narrow.

**Comment by clipperhouse** [comment]
Agree that it shouldn’t make a request, it should only take advantage of what’s in the DOM. Could do similarly for google.com. The attributes are:

Twitter: `data-expanded-url`
Google: `data-href`
Tweetdeck: `data-full-url`

Facebook uses a regular `href` but logging happens via an `onclick`, which could simply be removed.
