### ISSUE TITLE
Links to tweets are blocked on MacStories.net

### ISSUE THREAD

**Issue by johnny121** [uBlock-LLC/uBlock#1541]
Links to tweets are somehow blocked by uBlock 0.9.5.2 on MacStories.net, not sure about elsewhere. Problem occurs here: https://www.macstories.net/news/introducing-club-macstories/ with uBlock enabled:
<img width="743" alt="screen shot 2015-09-14 at 15 43 32" src="https://cloud.githubusercontent.com/assets/833584/9852668/6699bad4-5af7-11e5-8628-18c554cedee8.png"> and is solved with uBlock disabled: 
<img width="772" alt="screen shot 2015-09-14 at 15 44 24" src="https://cloud.githubusercontent.com/assets/833584/9852685/802a0436-5af7-11e5-9f9a-7558c6690630.png">. 
These are the filters I have enabled: 
<img width="697" alt="screen shot 2015-09-14 at 15 46 00" src="https://cloud.githubusercontent.com/assets/833584/9852742/cdeff356-5af7-11e5-8075-34385146c6bf.png">
Thank you for your help and for your work on the uBlock project!

**Comment by ghost** [comment]
Use the logger. Fanboy's Annoyance List, Fanboy's Social Blocking List, and Anti-ThirdpartySocial (which you have all three enabled) all have rules to block twitter.
![asoexpv1vkss 1](https://cloud.githubusercontent.com/assets/4343306/9865158/132274d8-5b18-11e5-9b95-b5143387f55c.png)
`macstories.net#@#a[title="Twitter"]`
