### ISSUE TITLE
Lots of TypeError messages on Facebook [Safari]

### ISSUE THREAD

**Issue by joshvickerson** [uBlock-LLC/uBlock#1542]
I've noticed an issue that seems to only affect Facebook (though, admittedly, the sample size of other sites I tested was very small). It's blocking things just find, but something that it's trying to block repeatedly causes this error message to log to the console:

TypeError: null is not an object (evaluating 'details.url')

It logs this message a lot. The longer I sit on the page the more it logs. Not sure if this is a real issue since everything appears to be working, but it may be something to look into further?

Here's the full error log from the console:

![screen shot 2015-09-14 at 3 57 43 pm](https://cloud.githubusercontent.com/assets/2325487/9860319/6a2bb15a-5af9-11e5-9c61-d32682f9e730.png)

**Comment by publicarray** [comment]
Thanks for the report but I need more information (see [CONTRIBUTING.md](https://github.com/chrisaljoudi/uBlock/blob/master/CONTRIBUTING.md)) as I am unable to reproduce. On the newsfeed I only get a single error after page load:
![screen shot 2015-09-16 at 1 34 09 am](https://cloud.githubusercontent.com/assets/5497998/9881422/20f4c506-5c13-11e5-83ad-e3ecee77eef1.png)
I tried it with uBlock 0.9.5.2, safari 8.0.8 on OS X 10.10.5

Do you have any other extensions installed?

**Comment by joshvickerson** [comment]
After leaving News Feed open for about an hour, I have nearly 400 logs.

![screen shot 2015-09-15 at 11 43 49 am](https://cloud.githubusercontent.com/assets/2325487/9881699/28b34778-5b9f-11e5-97e0-acb87619675b.png)

I'm using uBlock 0.9.5.2 on Safari 9.0 on OS X 10.11 (the GM seed).

The only other extensions I have installed are the 1Password extension and the Pocket extension.

**Comment by publicarray** [comment]
ok since I don't have 10.11 yet I'll just mark the line in question: https://github.com/chrisaljoudi/uBlock/blob/master/platform/safari/vapi-client.js#L195
also @chrisaljoudi is probably better equipped to deal with this.

**Comment by pedrodevoto** [comment]
Same here. It appears that none of the AJAX is working in Facebook, because none of the links work (unless, after I click on a link, I go to the URL bar and hit ENTER, or unless I cmd+click on the link to open it in a new tab), and that is also why it fills up the console with those messages when left alone (because it is trying to get new "news" by AJAX).

**Comment by ghost** [comment]
I'm seeing this same issue on OS X 10.11.15 with Safari 9.1.1 (11601.6.17).

**Comment by ghost** [comment]
Not sure, if its been fixed, but I could see it as well.

![screen shot 2017-01-25 at 11 10 42 pm](https://cloud.githubusercontent.com/assets/3421680/22302191/b4cc4b8c-e353-11e6-8842-d4fb15951448.png)
