### ISSUE TITLE
Please Remove

### ISSUE THREAD

**Issue by LarsOL** [uBlock-LLC/uBlock#1545]
Oh i've just realised that Ublock and Ublock origin are diffrent, 
sorry please remove

**Comment by publicarray** [comment]
You can close the issue and edit its contents, but you can't delete issues in github

**Comment by LarsOL** [comment]
I know, it's a bit off a pain sorry. Close if you can't delete.

**Comment by publicarray** [comment]
no it's fine but I can't close it (I'm not the owner/collaborator) but you should be able to: 
![screen shot 2015-09-20 at 3 13 15 pm](https://cloud.githubusercontent.com/assets/5497998/9979316/342f63e8-5faa-11e5-824a-6f68c1e32ce2.png)

**Comment by LarsOL** [comment]
Oh sorry, didn't notice. My bad
