### ISSUE TITLE
Acceleration of Regex Evaluation

### ISSUE THREAD

**Issue by TraderStf** [uBlock-LLC/uBlock#1547]
Could this be a solution to faster evaluation?
Too far for me.

http://stevehanov.ca/blog/index.php?id=90
https://swtch.com/~rsc/regexp/regexp1.html

**Comment by AlexVallat** [comment]
No. This relates to Regex processing, so what the browser's Javascript engine is doing. I'm not sure what sort of Regex processor each browser currently uses, but it's certainly possible that they may already be based on NFA - it's not a new technique.
