### ISSUE TITLE
Please add this site to your black list

### ISSUE THREAD

**Issue by behrangsa** [uBlock-LLC/uBlock#1548]
Continuously shows pop up dialogs and was impossible to close its tab:

http://thegoodkarma.info/eyJscCI6InRlc3QzIiwiY2l0eSI6IkF1c3RyYWxpYSIsImlwIjoiNTkuMTAwLjI1NS4yMjYiLCJpc3AiOiJBQVBUIExpbWl0ZWQiLCJudW0iOiIwMi04NjA3LTg4MTAiLCJleHBpcmVzIjoxNDQzMDAzODIwMDAwfQ==/

**Comment by publicarray** [comment]
try:
`||thegoodkarma.info$inline-script`
~~or if you want to block the domain (strict blocking):
`||thegoodkarma.info$document`~~

**Comment by behrangsa** [comment]
Thanks. Will do. But It would be great if it was added the to the black
list in the next update.

Best regards,
Behrang
http://www.behrang.org

On Thu, Sep 24, 2015 at 4:17 PM, Sebastian Schmidt <notifications@github.com

**Comment by gorhill** [comment]
> if you want to block the domain (strict blocking):

There is [no strict blocking in uBlock](https://github.com/chrisaljoudi/uBlock/releases/tag/0.9.3.5) -- strict blocking is a uBlock Origin feature:

> **Stress-free navigation** uBlock 0.9.3.5 will no longer stop you from navigating to websites.

**Comment by publicarray** [comment]
@gorhill My mistake, thanks for the correction.
