### ISSUE TITLE
UI feature request - optional grayscale toolbar icon

### ISSUE THREAD

**Issue by gitbees165** [uBlock-LLC/uBlock#1549]
uBlock and Firefox being inseparable, it's almost as if it part of firefox/browser.

The red icon is too much in the way, if you know what I mean. Instead of color changing for enabled/disabled, two different looking grayscale icons for the enabled/diabled would be nice.

**Comment by Gitoffthelawn** [comment]
If it helps you, take a look at the technique I used to change the uBlock icon from red to green in [uBlock Deluxe](https://github.com/Gitoffthelawn/uBlock-Deluxe). The actual CSS code I wrote to accomplish that is [here](https://github.com/Gitoffthelawn/uBlock-Deluxe/blob/master/userChrome.css).

A similar technique can be used to change it to grayscale.

**Comment by lewisje** [comment]
At least it will make uBlock for Firefox and Chrome more consistent with the one platform where it's actually the best ad-blocker: Safari.
