### ISSUE TITLE
Dynamic thumbnails inside products list aren't shown in Allegro.pl

### ISSUE THREAD

**Issue by Mati365** [uBlock-LLC/uBlock#1552]
![przechwycenie obrazu ekranu_2015-09-30_08-42-31](https://cloud.githubusercontent.com/assets/3949262/10186247/9a5fee74-674f-11e5-907a-1ecac2663df8.png)

Without "ublock" everything is working correctly:
![2](https://cloud.githubusercontent.com/assets/3949262/10186284/ebcb4f42-674f-11e5-827a-dfb2972ac57f.png)

**Comment by zummuz** [comment]
Hi, you are using not uBlock, but uBlock Origin (which is good idea) and therefore you should report to another (alive) repository: https://github.com/gorhill/uBlock

It looks like it's filter issue (Easylist), but anyway provide some details please such as: 
what version of uBlock do you use?
what setting and filters of uBlock are activated?
what version of chromium is it?

try to put that filter in "My filters" settings tab of uBlock:
@@||staticpics2.allegrostatic.pl/adverts/otomoto_pl$image,domain=allegro.pl
