### ISSUE TITLE
Fix date format for default settings backup filename.

### ISSUE THREAD

**Issue by yurikoles** [uBlock-LLC/uBlock#1554]
Please use ISO 8601 standard. 
It is really hard to sort backups and find last one according to filename.

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock .

Please close this issue.

**Comment by yurikoles** [comment]
@anewuser its already fixed in uBlock Origin.

**Comment by anewuser** [comment]
@yurikoles  That's why I'm telling people to use it and close these old issues. There are people who still install this dead extension and come to this repository via search engines.

**Comment by yurikoles** [comment]
@anewuser done
