### ISSUE TITLE
Impossible to activate on a flash player website [Safari]

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1555]
The website in question is deezer.com. Ublocks worked great until today. Ublocks has been desactivated for that particular website (without personal actions) and it is Impossible to reactivate it on deezer because the "power button" on the interface is greyed and non clickable. It is the only website on which ublocks behave like this. 
<img width="158" alt="capture d ecran 2015-10-07 a 21 51 10" src="https://cloud.githubusercontent.com/assets/7682547/10349210/9dbbea3e-6d3d-11e5-95c2-c92e919b8800.png"
Also, deezer.com displays yesterday messages that were saying that I had to install flash player (which I not did because Flash Player was already installed on my mac). I think the issue comes from Safari because It works on chrome.

**Comment by 5t3f4n** [comment]
I can't reproduce. Seems like a bug with the popup menu more than anything.
- Open the uBlock dashboard (click on the gear icon with the version number)
- Open the Whitelist tab
- Remove `www.deezer.com`from there
- Click Apply changes

See if uBlock is working again on the site after these steps.
