### ISSUE TITLE
[Enhancement] Implement possibility to invert whitelist

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1557]
I prefer to block ads only on sites that are stuffed with them, and really deserved it. I do this just for one thing: sites have money from this, and can continue to pay for hosting.

But adding each site I want to support to whitelist is boring. Especially when you consider the fact that in Firefox, the extension settings are not synchronized between browsers. So I need to add it about three times on different computers... And sometimes I forget to do that.

But with inverted whitelist this would be easier. On sites which deserved ad blocking, it is hard to forget to turn uBlock back on.

**Comment by zummuz** [comment]
You underestimate big site's income and overestimate hosting prices.
Anyway, in the UI you can click in the global cell (+ all) to make it green and press the lock button or create the rule `* * * allow` in the _My rules_ tab to allow every request from any site. Then, on the site you want to filter ad on you can click in the local (at the column with +/- signs) cell (+ all) to make it grey and press the lock button or create `siteyouwanttofilter.com * * noop` rule in the _My rules_ tab.

**Comment by ghost** [comment]
> You underestimate big site's income and overestimate hosting prices.

Good point, but who told you what I am telling about _big site's_?

> Anyway, in the UI you can click in the global cell (+ all) to make it green and press the lock button or create the rule \* \* \* allow in the My rules tab to allow every request from any site. Then, on the site you want to filter ad on you can click in the local (at the column with +/- signs) cell (+ all) to make it grey and press the lock button or create siteyouwanttofilter.com \* \* noop rule in the My rules tab.

Thanks. I'll try this later.

**Comment by ghost** [comment]
@zummuz

> Anyway, in the UI you can click in the global cell (+ all) to make it green and press the lock button or create the rule \* \* \* allow in the My rules tab to allow every request from any site. Then, on the site you want to filter ad on you can click in the local (at the column with +/- signs) cell (+ all) to make it grey and press the lock button or create siteyouwanttofilter.com \* \* noop rule in the My rules tab."

Thank you. That is almost exactly what I need.
