### ISSUE TITLE
Blocked from uBlock Origin for unknown reasons

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1558]
@gorhill I receive this message when I'm trying to post an Issue in [your uBlock repository](https://github.com/gorhill/uBlock/): "You have been blocked from this repository."

I apologize if I have caused you any problems long ago, I do not remember why I'm blocked. Please consider to unblock me.

**Gitoffthelawn** said: `"@davidhedlund Gorhill blocked me as well. I also have little idea why. I'm guessing it was a control thing because he did it while I was helping out with the FAQ."` - https://github.com/chrisaljoudi/uBlock/issues/1316#issuecomment-147231529

@Gitoffthelawn Ok, I think gorhill get a lot of help if he unblocks many users he blocked back in the days. What do you think @gorhill?

**Comment by dashed** [comment]
I had no idea blocking users is a thing.

Unfortunately:

>  If they @mention you anywhere on GitHub, you won't receive any notifications.
> src: https://help.github.com/articles/blocking-a-user/

/cc @gorhill

**Comment by lewisje** [comment]
Now they're known: https://github.com/gorhill/uBlock/issues/839#issuecomment-148925778

**Comment by LimboSlam** [comment]
Ehh, I hate the way this sounds, blocking a user because says or does too much. Though, I think @gorhill has good reason, but an explanation as to why should be put in.

**Comment by kalamalka** [comment]
are blocks user based or IP?

**Comment by davidhedlund** [comment]
@kalamalka User.
