### ISSUE TITLE
Site-based switches

### ISSUE THREAD

**Issue by freediverx** [uBlock-LLC/uBlock#1559]
Can you explain why site-based switches, which are available in uBlock Origin, are not included in uBlock? I'm actually not very familiar with this feature, but noticed the omission when comparing the two applications.

**Comment by zummuz** [comment]
Because the uBlock Origin is under active development by original creator of the uBlock and this repo is just a dead fork for donations (donations don't go to original developer nor to people who maintain the filters which it uses).

**Comment by gorhill** [comment]
> donations don't go to original developer

"developer" should be plural -- for example @Deathamns has done [magnitudes more work](https://github.com/gorhill/uBlock/graphs/contributors) than @chrisaljoudi to bring uBlock to more people.

**Comment by zummuz** [comment]
@gorhill Yeah, I wasn't correct, and @AlexVallat has done less numerous but much more important commits than him.

**Comment by gorhill** [comment]
>  @AlexVallat has done less numerous but much more important

Yes, bringing uBlock to Firefox for Android was definitely a big milestone. I was using it just yesterday and I can't imagine surfing the web without a blocker on Android.

**Comment by freediverx** [comment]
I would gladly use uBLock Origin if not for the fact that it does not support Safari. I would sooner give up a testicle than use Firefox or Chrome.

**Comment by epheterson** [comment]
+1, I'd like the ability to turn off uBlock for this particular site I'm viewing, as opposed to a global on/off switch, or manually setting per-site rules in settings. Most every ad blocking tool has this feature.
