### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by iamsole** [uBlock-LLC/uBlock#1560]
Our download button on orbitum.com is blocked when ublock is up and running. Can smbd help me with this?

**Comment by ghost** [comment]
> Static filter `||google-analytics.com/analytics.js` found in:
> 
>    [EasyPrivacy](https://forums.lanik.us/)

`@@||www.google-analytics.com/analytics.js$script,domain=orbitum.com`

**Comment by iamsole** [comment]
Where did you find it? Are there any way to remove it from the list?

**Comment by gorhill** [comment]
> Are there any way to remove it from the list?

Ask EasyPrivacy maintainers to add the exception filter in EasyPrivacy: https://forums.lanik.us/viewforum.php?f=64.
