### ISSUE TITLE
Element picker not working in Safari

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1561]
El-Capitan 10.11
Safari 9.0
Website: Any

Pink boxes appear as I move the mouse cursor around but clicking or double clicking has no effect. I have tried picking an element with uBlock both enabled and disabled. Nothing worked.

**Comment by gkarag** [comment]
I have Safari 9 with Mac OS X 10.10 and it behaves kind of the same, but sometimes it does work. It can stop working on a page it was working before after a reload. 

**Update**: I tried to use the debugger on the safari dev console with global breakpoints on all exceptions. Then when I tried to use the element picker, the debugger caught the following exception in a method `cosmeticFilterFromElement`:

```
 "Exception with thrown value: TypeError: CSS.escape is not a function. (In 'CSS.escape(elem.id)', 'CSS.escape' is undefined)"
```

After some googling I have found that this likely relates to a [WebKit issue](https://bugs.webkit.org/show_bug.cgi?id=149175)

**Comment by alfureu** [comment]
+1 Very annoying. Any resolution soon?

**Comment by zummuz** [comment]
> +1 Very annoying. Any resolution soon?

No. uBlock is officially abandoned, finally.

> uBlock is no longer under development for Safari because the extension APIs that made it possible are now deprecated and have been replaced by the new Content Blocking APIs  

\- https://github.com/chrisaljoudi/uBlock/issues/1544#issuecomment-150397875
