### ISSUE TITLE
Custom filters not working when typing site address in address bar

### ISSUE THREAD

**Issue by Revjones** [uBlock-LLC/uBlock#1562]
Hi,

I'm having a strange issue on the Safari version 0.9.5.2 of uBlock.
I created some custom filters for amazon.com in order to most of the page's useless crap (recommendations, recently viewed,...). It's working perfectly fine when I'm launching the website from a bookmark or by clicking a link pointing to it, but whenever I try to access the site by typing its address directly in Safari's address bar, the site will load without any filtering despite de fact that uBlock's icon properly display the amount of blocked content. Only after I hit Safari's "refresh" button the page reloads with proper filtering.
Any clue?

OS X 10.11
Safari 9.0
uBlock 9.5.2
No other extension

Example of filtering used :
www.amazon.com###btfContent
www.amazon.com###sidebar
www.amazon.com###anonCarousel1
www.amazon.com###pageContent > div:nth-of-type(1)
www.amazon.com###rhf-container

**Comment by Freida-Moo-Goo-Gai-Pan** [comment]
You have to disable "preload top hits" in preferences in Safari.   Took me two weeks to figure that out.

**Comment by RoxKilly** [comment]
I may be off but it sounds like in the `preload top hits` context, Safari doesn't allow extensions to hook into the traffic in order to filter it.  If that's the case, I don't know what uBlock could do about it.

**Comment by Revjones** [comment]
Awesome, thank you Freida-Moo-Goo-Gai-Pan. I would never have figured that out!
