### ISSUE TITLE
uBlock blocks legit content, other similar content within same site stays untouched

### ISSUE THREAD

**Issue by jasomdotnet** [uBlock-LLC/uBlock#1563]
Hi,
I have FF 41.0.2 with uBlock 0.9.3.5. I admin http://www.dogva.com/ - site focused on dogs and puppies for sale. 

There are 2 main content types:
- ad (has "ad" mention in main content wrap for .css reasons)
  uBlock blocks it all, see http://www.dogva.com/classifieds/4614-puppie-german-pinscher
- breeder
  everything is ok, see somethings from http://www.dogva.com/breeders

This is funny way how to punish users when they have enabled some kind of adblocker :) uBlocker cannibalizes itself :)

**Comment by ghost** [comment]
This would be a false positive in EasyList (rule: `##.node-ad`) and will affect everyone using EasyList (i.e. not just uBlock).  Might be a good idea to [leave a message on the EasyList forum](https://forums.lanik.us/viewforum.php?f=64) about the issue.

**Comment by jasomdotnet** [comment]
Thank you for a hint.
