### ISSUE TITLE
for safari

### ISSUE THREAD

**Issue by muhasturk** [uBlock-LLC/uBlock#1564]
extension gallery has no ublock

**Comment by lewisje** [comment]
The link to the Extension Gallery still works (note: it's for Safari on OS X, not on iOS): https://extensions.apple.com/details/?id=net.gorhill.uBlock-96G4BAKDQ9

**Comment by AbeEstrada** [comment]
The link to the extension works (apple site), but the "Install" link doesn't.

Both links do not work.
ublock official site https://cloud.delosent.com/ublock-safari-0.9.5.2.safariextz
safari extensions https://chrismatic.io/ublock/ublock-latest.safariextz

**Comment by AbeEstrada** [comment]
Update: now they work

**Comment by tscheepers** [comment]
there seems to be a problem again, the links do not work

**Comment by Firsto** [comment]
not working

**Comment by Firsto** [comment]
now working) installed from here https://extensions.apple.com/details/?id=net.gorhill.uBlock-96G4BAKDQ9

**Comment by rezzo** [comment]
again, not working the links

**Comment by fantasyx** [comment]
the safari unlock is dead.!

**Comment by KOLeC78** [comment]
Safari uBlock on OSX 10.11.4 Not working, and cannot install new (ver. 0.9.5.2) downloaded from GitHub extension. Link to extensions.apple doesn't works also.

**Comment by ylzhou** [comment]
cannot install Safari uBlock 0.9.5.2 on OSX 10.11.5 either. cannot find it on apple's site. Is this extension dead?

**Comment by lewisje** [comment]
I believe it is, and I hope someone ports uBlock Origin to Safari and takes care of that port better than chrisaljoudi did his.

**Comment by anewuser** [comment]
@muhasturk This repository is dead. Please close this issue and follow this new Safari port: https://github.com/el1t/uBlock-Safari
