### ISSUE TITLE
uBlock officially abandoned

### ISSUE THREAD

**Issue by 5t3f4n** [uBlock-LLC/uBlock#1565]
In a [post on reddit](https://web.archive.org/web/20151025221223/https://www.reddit.com/r/apple/comments/3q1vh5/purify_app_developer_attempts_to_remove_rival_app/cwbed6m), Chris states that once the OS X version of his new project is released, he will be dropping uBlock.

> I will be letting go of uBlock once Purify for OS X is available.

I suggest everyone migrate to [uBlock Origin](https://github.com/gorhill/uBlock/) which is in active development and already more feature-complete. It's developed by [gorhill](https://github.com/gorhill/), the original developer of uBlock/µBlock.

**Comment by xHN35RQ** [comment]
Kudos to @chrisaljoudi for making a good decision. Thank you Chris, for doing a good thing for the users of uBlock. :+1: :clap:
