### ISSUE TITLE
close this fork project and keep contributing to the uBlock Origin

### ISSUE THREAD

**Issue by hyiltiz** [uBlock-LLC/uBlock#1567]
Seemingly not much has happened for months either in the main code repo here or in this project's wiki page, while on the other hand, uBlock Origin, which is the original project while this is simply a fork, is still alive and kicking. It is important to keep users away from this fork project where your development is stale. Please kindly develop or direct users to uBlock Origin.

**Comment by RoxKilly** [comment]
With all due respect, I get what you're saying but this is an open source project. Anyone who is interested can contribute. The developers don't work for us.

I think most people who come to github are technically savvy enough to realize that this project is stale. Most 'regular' people install add-ons from the Mozilla or Chrome stores. There, I agree with you, it should be clear when an add-on is not being actively developed.  I don't use the Chrome store but the [description on Mozilla](https://addons.mozilla.org/en-US/firefox/addon/ublock/?src=ss) starts with:

> **NOTE**: Users should be aware that this add-on represents an older fork. The original developer of uBlock is continuing to actively develop the newer fork uBlock Origin.

**Comment by hyiltiz** [comment]
Thanks for the reply! That is very true! It is the end users that I am more
concerned about. Maybe we can make sure that all platforms carry that sign?

**Comment by Zearin** [comment]
> With all due respect, I get what you're saying but this is an open source project. Anyone who is interested can contribute. The developers don't work for us.

This is correct.  Technically, people should contribute where they want.  

However, that being said…

> Seemingly not much has happened for months either in the main code repo here or in this project's wiki page, while on the other hand, uBlock Origin, which is the original project while this is simply a fork, is still alive and kicking. It is important to keep users away from this fork project where your development is stale. Please kindly develop or direct users to uBlock Origin.

…This is also a good point.  

I had similar concerns, and I sent a private email to the owner of this project.  I was curious about why the split occurred, but more importantly I asked about the future of this project.  

I sent that email on 2015-10-16 (18 days ago).  I got no response.  

The problem with abandoned open source projects is that they can provide false hope that a project is capable of being revived at any time.  But when a project like uBlock Origin (with a lot of “shared DNA”) exists, and this project is collecting dust…who will want to contribute to this one?  

And this effect will only grow stronger with time.

**Abandon Hope, All Ye Who Browse Here!**  This project is dead.

**Comment by hyiltiz** [comment]
It is not obvious that this project is a form and now stale since the unlock.org is still up and this projects title directly points to there giving a false impression that this project is the real one, and without even forking through Github. While it is true that all this points can be easily spotted via git logs, it is not so at first look. Pointing people the right direction and avoiding potentially misguiding information is a virtue. Hope the maintainer tries to follow it.

**Comment by RoxKilly** [comment]
I agree that ublock.org should have a similar notice indicating that this project is dormant. Especially since that website appears to still be accepting donations

**Comment by 0xBRM** [comment]
@RoxKilly Of course it does :^] https://translate.google.com/#en/ar/the%20jew and click on the speaker button.

**Comment by chrisaljoudi** [comment]
@CrisBRM Ha, amusing. Just FYI though, the last name actually comes from [Mount Judi](https://en.wikipedia.org/wiki/Mount_Judi).

Not only that, but if you were trying to speculate on my religious views,<sup>1</sup> it seems like "Chris" makes your conclusion unlikely. :wink:

Regarding donations, I've been, with great intention, mostly silent about this, but it's getting ridiculous. One must feel near-infinite entitlement to go as far as bitching about someone accepting donations.

I bet tip jars are catastrophic, too, right?

If you don't feel that something is worthy of your [voluntary, mind you] donation, simply decline to click the button.

The button shows up **only** on the website, so it's hardly an intrusive notion or a forceful request.

<sup>1 I'm not religious, by the way. Not that it makes any difference.</sup>

**Comment by hyiltiz** [comment]
It is good that we have your notice here, @chrisaljoudi . I cannot be less concerned about the donations as is obvious from above; wasn't even aware of them. However, you failed to make it clear that a) this is a fork project by _NOT_ forking through the Github interface (yes you can do whatever you want), so that for first comers it is very difficult to tell which is egg and which is chicken (haha!); b) you somehow own the domain name ublock.org which seems the sensible and reasonable official site name for the uBlock project (yours is _NOT_; yours is a stale fork of that), and use the link to advertise this project in your project front page: https://github.com/chrisaljoudi/uBlock/. These two points gives an (hopefully false) impression that you are pretending to steal away someone else's contributions by making it seem like yours. I would not believe so, but it is good to stay away from all practices that _might_ lead to a conclusion like that.

**Comment by Gitoffthelawn** [comment]
@hyiltiz You may want to verify your "facts" before posting.  Your "facts" are completely backwards.  This repository is the original uBlock Github repository, and has always been.

The uBlock Origin repository, on the other hand, is a fork of this uBlock repository, made by the original author, shortly after he gave away this repository because he did not want to be the maintainer anymore.

If you feel strongly about pointing people to specific repositories and believe it is a virtue, please get involved on winmerge.org and let the millions of people using that project know about WinMerge2011, which despite it's name, is being actively developed.  Your energy will be well-spent there, and at least you will be starting your posts with the correct facts.  See https://bitbucket.org/jtuc/winmerge2011

**Comment by Gitoffthelawn** [comment]
@CrisBRM Your antisemitic comment will not be tolerated.  Bigots have no place here on GitHub.  I have reported your actions to GitHub and the Anti-Defamation League (http://www.adl.org/).

**Comment by seanrand** [comment]
This is getting ridiculous, people. Either contribute on topic in the uBlock Origin repo (if you can) or drop the silly vendetta over here and do something productive with this project.

**Comment by hyiltiz** [comment]
I feel sorry for all of our time in this discussion.

**Comment by harshanvn** [comment]
> do something productive with this project.

@chrisaljoudi 
You say you develop uBlock. Can you give us some insight on what is your plans for this project?

**Comment by trbvm12** [comment]
@chrisaljoudi "tip jars" are for people to express appreciation for someone doing something. You have set up a website with a high traffic name and have done nothing to maintain the software in some time.

That's called 'panhandling'.

**Comment by Gitoffthelawn** [comment]
I may give @chrisaljoudi a tip just for having to endure some of these people.

I may also give some money to the disabled man panhandling in front of my office.
