### ISSUE TITLE
Non-responsive script hangs uBlock

### ISSUE THREAD

**Issue by CheechGe** [uBlock-LLC/uBlock#1568]
I had to disable uBlock to stop a script from hanging up Firefox. Every time I use a link from the home page and go back to the home page I get a message that a scipt is not responding.  Most of the time if I wait long enough it will eventually respond.   Checking the box to ignore (or whatever it does) the script has no effect.

To recreate the problem go to the site:

marketwatch.com

**Comment by lewisje** [comment]
Have you considered switching to uBlock Origin? Unlike this extension, it's actually maintained.

**Comment by CheechGe** [comment]
No, I didn't know there was another version until after I reported the
problem
  I will install the other version and retest, and get back to you.

Thank you for your response.

**Comment by CheechGe** [comment]
Hello James:

Just tried your suggestion and the results are the same.  I had to force 
FF out until I could disable uBlockOriginal.   Once I did that it was fine.

Neither product seem to like the script that gets executed when any link 
on the Marketwatch page is clicked.  In fact FF hung up as soon as MW 
was opened (it's my homepage).

Do I need to report this elsewhere or is responding this way sufficient?

Thanks,

Cheech

**Comment by lewisje** [comment]
Go to https://github.com/gorhill/uBlock/issues to report issues, and be sure to mention any subscriptions you use, any changes from the default settings, and any other extensions you use (chances are it's a problem with one of them, and not with uBlock Origin itself); by the way, it's not "Original," it's "Origin."

**EDIT** Never mind, I see that you've already done that.

**Comment by CheechGe** [comment]
Ok will do.  Yes I was informed of the name mistake and made the correction in the ticket.

C:\Documents and Settings\Frank\My Documents\Dropbox\ScreenShots\winprivacy_error_27.pngC:\Documents
and Settings\Frank\My Documents\Dropbox\ScreenShots\winprivacy_error_27.png

**Comment by lewisje** [comment]
You can't link to a file from your local drive and have it show up on the Internet; I see that's a Dropbox URL so what you can do is go into your Dropbox account and make a public link for that file.

That's advice going forward though, because I saw that on the uBlock Origin issue tracker you've already properly linked the image files, and I think you should just close this issue.

**Comment by CheechGe** [comment]
OK will do thanks.   I didn't relaize it linked to the file as most on the problem systems I'm used
to simply upload the files.
