### ISSUE TITLE
[Firefox] new content types for nsIContentPolicy

### ISSUE THREAD

**Issue by lewisje** [uBlock-LLC/uBlock#1569]
I noticed in Firefox 42 that there is a new `TYPE_EMBED` as distinct from `TYPE_OBJECT` (and the tracking bug also mentioned the long-deprecated APPLET), and that SUBDOCUMENT was split into FRAME and IFRAME (and maybe IMPORT for HTML Imports, I know that was mentioned in the tracking bug): https://developer.mozilla.org/en-US/Firefox/Releases/42#nsIContentPolicy

I realize that you have probably already seen this change, because Firefox 42 Nightly builds started appearing months ago, but I'm surprised to see all the types that have been added to nsIContentPolicy over the years: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIContentPolicy

I wonder whether uBlock for Firefox, if it is ever again actively developed, will support new filter syntax to specially handle these new content types, or maybe just (for consistency with the other platforms) merge them with the existing request-type selectors, like mapping FRAME, IFRAME, and IMPORT to subdocument, EMBED to object, IMAGESET to image, FETCH and BEACON to xmlhttprequest, etc. (or maybe some of these are just mapped to other).

**Comment by anewuser** [comment]
@lewisje Please repost your old issues (if they are still relevant) to the [uBlock Origin](https://github.com/gorhill/uBlock/) repository, and close the original reports here. 

https://github.com/chrisaljoudi/uBlock/issues/created_by/lewisje
