### ISSUE TITLE
README.md should contain a deprecation warning

### ISSUE THREAD

**Issue by her** [uBlock-LLC/uBlock#1571]
Since uBlock for safari is no longer under current development README.md should have a clearly notated warning to users about this at the top of the page.

**Comment by RoxKilly** [comment]
agreed

**Comment by meat-ball** [comment]
that's odd, the developer solicited (and received) the apple developer fee and said ublock was covered for another year.  This is no longer the case?

https://www.reddit.com/r/apple/comments/398fgq/apples_new_safari_extension_policy_100year_to/?limit=500

**Comment by her** [comment]
Why did you just close this without actually addressing the issue?

**Comment by harshanvn** [comment]
Yes Please. An update on this here **and** uBlock.org would be much appreciated.
