### ISSUE TITLE
What happens wit this extension.

### ISSUE THREAD

**Issue by MESWEB** [uBlock-LLC/uBlock#1574]
I see ads from Youtube video embeded on other site. On Youtube I can't comment and not view recomended video at the right sidebar. 
Windows 7, Waterfox 64 withs uBlock 0.9.5.0

**Comment by 5t3f4n** [comment]
The maintainer of this repo has switched focus to another project – a content blocker for iOS. Once the OS X counterpart of that is finished, he [_will be letting go of uBlock_](https://web.archive.org/web/20151025221223/https://www.reddit.com/r/apple/comments/3q1vh5/purify_app_developer_attempts_to_remove_rival_app/cwbed6m). And while a more official/formal announcement has yet to be made, it's clear that this version of uBlock has already been abandoned for quite some time.

You should switch to [uBlock Origin](https://github.com/gorhill/uBlock/) by @gorhill (the original developer of uBlock), which is in active development and is receiving both bug fixes and new features. It is also fully reviewed on [AMO](https://addons.mozilla.org/firefox/addon/ublock-origin/) which means it's signed and you can enjoy automatic updates.

**Comment by MESWEB** [comment]
Thanks. You help me a lot.
