### ISSUE TITLE
reconsider #693 - Romanian Adlist

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1576]
The maintainer of the romanian adblock list explained the reasons for the whitelisted stuff in a comment to #693, please reevaluate the inclusion of ROList in the default 3rd-party filter list.

**Comment by lewisje** [comment]
This extension will soon be abandoned; go over to uBlock Origin, at https://github.com/gorhill/uBlock/

**Comment by ghost** [comment]
He insulted the other guy as a "turd" and failed to explain why profitshare.ro is whitelisted.

**Comment by zosoro** [comment]
i have several times. just ask.

**Comment by ghost** [comment]
He explained it: https://adblockplus.org/forum/viewtopic.php?p=145816#p145816
