### ISSUE TITLE
Missing trackers

### ISSUE THREAD

**Issue by TraderStf** [uBlock-LLC/uBlock#1580]
http://www.anonymousdmp.com/p?f=gif&idp=13c415f9

noscript
img src="http://www.anonymousdmp.com/p?f=gif&idp=13c415f9" alt=""
width="1" height="1"
/noscript

**Comment by lewisje** [comment]
It's probably a third-party list issue, and unless you're on Safari, you should really switch to uBlock Origin, which is *actually being maintained*.

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock

Please close this issue.
