### ISSUE TITLE
Update subscription url for Liste AR

### ISSUE THREAD

**Issue by smed79** [uBlock-LLC/uBlock#1582]
Hi, 
**uBlock** ![uBlock](http://i.imgur.com/7nBumRl.png) use old subscription url for **Liste AR** (القائمة العربية لمانع الشرائط الإعلانية).
- old : `https://liste-ar-adblock.googlecode.com/hg/Liste_AR.txt` (_google code shutdown_).
- new url : https://easylist-downloads.adblockplus.org/Liste_AR.txt (since august 24, 2015).
- forum https://forums.lanik.us/viewforum.php?f=98
- changes https://hg.adblockplus.org/listear/shortlog

Thanks for update!
Med

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock

Please close this issue.

**Comment by smed79** [comment]
Fixed ==> https://github.com/gorhill/uBlock/issues/1061

Thank you.
