### ISSUE TITLE
Statistics with Firefox 41+

### ISSUE THREAD

**Issue by J0WI** [uBlock-LLC/uBlock#1584]
There are no stats for Firefox at all yet and it would be interesting to have some.

In Firefox 41 landed a [major change](https://bugzilla.mozilla.org/show_bug.cgi?id=77999) that improved the performance of ad blockers a lot.

The memory stats of Firefox are located on `about:memory`.

**Comment by Gitoffthelawn** [comment]
+1

From what I've seen, most speed / memory use comparisons between uBlock / uBlock Origin and ABP / ABE are outdated and thus meaningless.  Some of them are also biased and don't compare "apples to apples", which further reduces their value.

I also have not seen any speed / memory use comparisons that compare pure blocking efficiency when element hiding is disabled.
