### ISSUE TITLE
Element Blocking Not Working Properly Unsure if actual issue

### ISSUE THREAD

**Issue by Firedingo** [uBlock-LLC/uBlock#1586]
So I like using this site Twitch.tv but I absolutely hate their new chat whispers feature. Specifically I hate that it overlays the video content for me so up to about 40% of the video content can be hidden by the whisper feature. So my simple solution was to element block the annoying parts except it seems that element blocking seems to fail on that site. I'm unsure if this is a site issue or uBlock issue especially given that element blocking seems to work reasonably consistently on twitter where I have one thing blocked.
Specifically I block the button for the whispers list but upon browser restart it seems the same elements have become unblocked. Does not appear to change if I refresh the page though.

**Comment by lewisje** [comment]
You might want to try the adblockplus forums for help on hiding whispers; with that said, maybe this custom filter will work: `twitch.tv##.whisper-line`

**Comment by Firedingo** [comment]
Thanks. I'll give that a try. From what I can see it uses some varying numbers that probably relate to the active session meaning It's a new element I think that's being blocked each time. :/
You can imagine how quickly the filters list is getting now :/

eg. www.twitch.tv###ember792 > .conversations-list-bottom-bar.js-conversations-list-bottom-bar > .glyph-only.button.conversations-list-icon

**Comment by lewisje** [comment]
I never trust the "Block element" dialog, instead I went straight to the browser's own web inspector to find something that does not change among instances of the element I wish to hide and is not likely to occur in elements that I do not wish to hide.

Please go here for further questions: https://adblockplus.org/forum/viewforum.php?f=2

**Comment by Firedingo** [comment]
Awesome Thanks. I did not know that could be an issue. At least I learnt something :)

**Comment by Firedingo** [comment]
Solution I found was to remove "#ember777 > " so it went ##.conversations
Took some figuring out. So far seems to work good. Thought I should add this in case others might want to copy it.

So the filter lines looked like this
- `www.twitch.tv##.conversations-list-bottom-bar.js-conversations-list-bottom-bar`
- `www.twitch.tv##.conversations-list-bottom-bar.js-conversations-list-bottom-bar > .glyph-only.button.conversations-list-icon`
- `www.twitch.tv##.conversations-list-bottom-bar.js-conversations-list-bottom-bar > .glyph-only.button.conversations-list-icon > .svg-conversations`
- `www.twitch.tv##.conversations-list-bottom-bar.js-conversations-list-bottom-bar > .glyph-only.button.conversations-list-icon > .svg-conversations > path`
