### ISSUE TITLE
Menu Context to temporarily Disable uBlock

### ISSUE THREAD

**Issue by dtiziani** [uBlock-LLC/uBlock#1587]
It would be nice to have a context menu (on the button or on the site) to disable it temporarily.

**Comment by Gitoffthelawn** [comment]
I think the majority of people agree with you.  Many people have asked for this feature, and obviously continue to do so.

Unfortunately, this version of uBlock has not seen updates in quite some time.

IIRC, I participated in a thread asking for this feature in the uBlock Origin repo a while back.  Shortly afterward, Raymond Hill banned me from that repo.  He seemed upset that people were asking for the feature, even though it is perhaps the most commonly requested feature.  Whatever.
