### ISSUE TITLE
Reconsider #607 - removing entry from Unbreak

### ISSUE THREAD

**Issue by Mirkic7** [uBlock-LLC/uBlock#1588]
Site has since that request been upgraded, and entry in Unbreak makes it difficult to block adds (from their local server).
Just disabling Unbreak makes site look as it needs to, without adds, and fully functional.

**Comment by lewisje** [comment]
Does this extension even *have* a built-in Unbreak list? You might be thinking of uBlock Origin, which is at gorhill/uBlock

**Comment by lewisje** [comment]
This extension is no longer maintained; unless you're a Safari user, switch to uBlock Origin.
