### ISSUE TITLE
Odd style tag injection

### ISSUE THREAD

**Issue by colby** [uBlock-LLC/uBlock#1589]
I'm seeing an odd `<style>` tag being injected into my browser when viewing a personal webpage. There is nothing in my webpage HTML that has this. I can turn off uBlock, refresh the page, and the style is gone. Enabling uBlock and refreshing again brings it back.

Is this normal?
## Injected code

``` html
<style>
[href^="http://twitter.com/?status="],
[href^="http://twitter.com/home/?"],
[href^="http://twitter.com/home?"],
[href^="http://twitter.com/intent/tweet/?url="],
[href^="http://twitter.com/intent/tweet?"],
[href^="http://twitter.com/share?"],
[href^="https://twitter.com/intent/follow?"],
[href^="https://twitter.com/intent/retweet?tweet_id"],
[href^="https://twitter.com/intent/tweet?"],
[href^="https://twitter.com/share?"],
[href^="http://www.amazon.co.uk/exec/obidos/external-search?"],
#header + #content > #left > #rlblock_left
{display:none !important;}
</style>
```
## Versions

uBlock 0.9.5.2
Safari 7.1.2

**Comment by colby** [comment]
I only ask because the string `obidos` can be found [elsewhere](https://github.com/chrisaljoudi/uBlock/search?utf8=✓&q=obidos).

**Comment by lewisje** [comment]
Are you sure that no libraries used on your site inject links like those? I can imagine the twitter links came from social-sharing plugins, for example. You might want to link to the webpage in question.

**Comment by colby** [comment]
@lewisje I first noticed it on my [personal webpages](https://github.com/colby/colbyolson.com/blob/master/lib/header.html), but now I notice that I can see odd style tags being included into the `<head>` of _any_ webpage I visit.

I'm inclined to believe this is an overzealous 3rd party filter.

**Comment by lewisje** [comment]
Oddly, I don't see the third-party filters in question; then again I'm using uBlock Origin in Chrome.

**Comment by colby** [comment]
Assuming I can track down whichever 3rd party filter that's causing this, what would be my next step?

**Comment by lewisje** [comment]
Complain to the filter author; this looks like something from Fanboy's Social Blocking List, but I have his Annoyances list (which includes Social Blocking) and I don't see those style rules injected.
