### ISSUE TITLE
Block Youtube controller on some website.

### ISSUE THREAD

**Issue by ve3** [uBlock-LLC/uBlock#1590]
I'm using **Firefox**.
I was **whitelisted** my website but Ublock still block the Youtube controller on my website.
I have no additional of **my rules**, **my filters**.

For example: [This link](http://wimutti.org/%E0%B8%9F%E0%B8%B1%E0%B8%87%E0%B8%98%E0%B8%A3%E0%B8%A3%E0%B8%A1/%E0%B8%9B%E0%B8%8F%E0%B8%B4%E0%B8%88%E0%B8%88%E0%B8%AA%E0%B8%A1%E0%B8%B8%E0%B8%9B%E0%B8%9A%E0%B8%B2%E0%B8%97/)
![fireshot capture 2 - i__ - http___wimutti org_ e0 b8 9f e0 b8](https://cloud.githubusercontent.com/assets/1568262/12731987/11b03b6e-c966-11e5-9248-a2b019942765.jpg)

Play button, settings button, watch on Youtube button, full screen button are missing.

Unchecked **all filters** and reload page and play don't fix anything.
Disable this plugin in Firefox and all buttons are working perfectly.

I don't know why.

**Comment by publicarray** [comment]
uBlock is no longer maintained. I recommend that you switch to [uBlock Origin](https://github.com/gorhill/uBlock).

**Comment by ghost** [comment]
https://github.com/gorhill/uBlock/issues/1377#issuecomment-183843715
