### ISSUE TITLE
Ublock doesn't block ads on di.fm, viasatsport.se, tv3play.se, tv4play.se and similar sites anymore

### ISSUE THREAD

**Issue by Umeaboy** [uBlock-LLC/uBlock#1594]
I noticed that if I choose to block a certain ad request web adress it won't stick to the block. It just resets the list to allow all ads. How can I add equivalent information for future development?

I have opened the log when I play a genre on di.fm, but I don't know what to look for in the output.

**Comment by lewisje** [comment]
I recommend switching to uBlock Origin, unless you're using Safari, where uBO has not yet been ported.

With that said, what precisely do you do when you "choose to block a certain ad request"? You might have been doing it wrong.

**Comment by MacFlurry** [comment]
any chance to update for Safari ?

**Comment by lewisje** [comment]
I've considered trying to port uBlock Origin to Safari, but I've been lazy about it; I surely wouldn't be The Maintainer (TM) of the fork, because I'd rather not shell out the money for the server to host the downloads from (the main reason Chris _was_ soliciting donations BTW).

**Comment by lethak** [comment]
If you are still looking for a solution on di.fm, I made this one https://github.com/lethak/digitally_imported_userscript

**Comment by lewisje** [comment]
Someone else ended up porting uBlock Origin to Safari BTW: https://github.com/el1t/uBlock-Safari
