### ISSUE TITLE
uBlock no longer blocks Twitch.tv ads

### ISSUE THREAD

**Issue by Phoenix100k** [uBlock-LLC/uBlock#1595]
As of this week, the ad that plays when a stream is joined is no longer blocked.

The ads seem to be a of a new variety as many of them have live content; buttons you can "click to learn more" or "click to order now" that are not part of the ad itself, they're overlays.

**Comment by lewisje** [comment]
This extension is no longer maintained; if you're not using Safari, consider switching to uBlock Origin and seeing whether you still have this issue.

**Comment by asoksevil** [comment]
What if you use Safari @lewisje ? What other options do we have?

**Comment by lewisje** [comment]
If you're not using the special features of uBlock (like dynamic filtering or HOSTS files as filter-lists), consider switching to ABP.

**Comment by 5t3f4n** [comment]
This fork is no longer maintained. Uninstall and upgrade to [uBlock Origin](https://github.com/gorhill/uBlock/).

**Comment by asoksevil** [comment]
But what if you use Safari? Adguard extension?

**Comment by lewisje** [comment]
I see at least two comments deleted in this Issue, one of which is mine.
