### ISSUE TITLE
URL over-jumper

### ISSUE THREAD

**Issue by Saentist** [uBlock-LLC/uBlock#1596]
lot of websites try to redirect local (in-site) url via external counting and etc. websites
is it possible for plug-in to cut url unneaded stuff

ex.
site.some/img.jpg << visable by user
to external.site/user/info/grabber/show/site.some/img.jpg

**Comment by lewisje** [comment]
This extension is no longer maintained, but even if it were, this request sounds like something for a dedicated extension or a UserScript, similar to one that I saw for making Google search results directly open rather than opening via Google's own link-tracker.
