### ISSUE TITLE
Wrong redirect to facebook.com via an iframe despite a filter

### ISSUE THREAD

**Issue by birdie-github** [uBlock-LLC/uBlock#1597]
Hi, on this page:

http://www.phoronix.com/scan.php?page=news_item&px=GRUB-2.02-Features

There's this code:

```
<div style="float: left; overflow: hidden;">
<iframe src="//www.facebook.com/plugins/like.php?href=http://www.phoronix.com/scan.php%3Fpage%3Dnews_item%26amp%3Bpx%3DGRUB-2.02-Features&amp;width=200&amp;height=46&amp;colorscheme=light&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;send=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:200px; height:46px;" allowTransparency="true"></iframe>
</div>
```

The problem is, even with Fanboy’s Annoyance List‎ (forums.lanik.us) filter, my Firefox automatically redirects to https://www.facebook.com/plugins/like.php?href=https://www.phoronix.com/scan.php%3Fpage%3Dnews_item%26amp%3Bpx%3DGRUB-2.02-Features&width=200&height=46&colorscheme=light&layout=button_count&action=like&show_faces=false&send=true

even though this subscription should block this iframe.

This does not happen when I'm running Adblock+.

**Comment by birdie-github** [comment]
![log](https://cloud.githubusercontent.com/assets/4958603/13730961/2e1299b6-e980-11e5-859a-e0373c99d825.png)

**Comment by lewisje** [comment]
This extension is no longer being maintained; consider re-posting this in gorhill/uBlock

**Comment by satnatantas** [comment]
@lewisje too bad Gorhill closed issues for non-contributors.

**Comment by satnatantas** [comment]
Ah ok there's reddit for that.

**Comment by satnatantas** [comment]
@birdie-github did you ever solve it? I Tried "NoRedirect" for Firefox and I could not make it work for "facebook/plugins/" URLs. My rules for NoRedirect are:

```
.*facebook.com.*/plugins/.*
.*staticxx.facebook\..*
.*connect.facebook.net.*\.js.*
```

**Comment by ghost** [comment]
>too bad Gorhill closed issues for non-contributors.

@satnatantas
https://github.com/uBlockOrigin/uBlock-issues/issues
