### ISSUE TITLE
Element Picker Mode Not Showing Modal Dialog Box

### ISSUE THREAD

**Issue by Max-108** [uBlock-LLC/uBlock#1598]
uBlock version: **0.9.5.2**
Browser/version: **Safari 9.1**
OS X El Capitan **10.11.4**

For a few weeks now I've not been able to use the Element Picker.  I've tried entering it via the contextual menu, and also by the icon in the dropdown uBlock menu, but while I can select an element, there is no Modal Dialog Box and nothing happens when I click the element that I can see selected in red.

**Comment by herrminni** [comment]
I can confirm this with 0.9.5.0.1 on Ubuntu, too.
Also updating the filters in settings is not working any more, it show the loading-bar with no text and nothing happens.

=> What helped for both, is to go to the settings page and click the button "start from the beginning"

**Comment by Max-108** [comment]
@herrminni, thanks for the workaround.
