### ISSUE TITLE
Changelog links wrong

### ISSUE THREAD

**Issue by kurtextrem** [uBlock-LLC/uBlock#16]
About > Changelog links to the wrong page "https://github.com/gorhill/uBlock/wiki/Change-log" is the right link, but it links "https://github.com/gorhill/uBlock/wiki/Changelog"

**Comment by kurtextrem** [comment]
It's wrong again.

**Comment by gorhill** [comment]
For which language?

**Comment by gorhill** [comment]
Ah I see, German.

**Comment by gorhill** [comment]
Actually it was wrong since I first committed the file, this one was never fixed, I don't know why I marked it as fixed above.
