### ISSUE TITLE
Issues with BBC iPlayer

### ISSUE THREAD

**Issue by baadgers** [uBlock-LLC/uBlock#1600]
Thumbnails and the player don't load with ublock enabled.  Soon as I disabled and refreshed page it works fine, otherwise I just get a black screen and no play button.  I add iplayer url to white list and then homepage the works, but when I click on an episode to watch, it too will have just a black screen unless I add that url to white list or disable ublock

**Comment by lewisje** [comment]
This extension is no longer maintained; try uBlock Origin to see whether it still has this issue (unless you use Safari, then switch to Adblock Plus because at least that's maintained).

**Comment by baadgers** [comment]
Okay thanks. I did switch to origin after I made the post and that worked.  I'll just remove ublock now
