### ISSUE TITLE
Doesn't work with flightrardar24.com

### ISSUE THREAD

**Issue by mobile4** [uBlock-LLC/uBlock#1602]
Subj. If uBlock is on www.flightradar24.com shows blank page. Please fix it.

**Comment by harshanvn** [comment]
This extension is no longer maintained. Consider switching to [uBlock Origin](https://github.com/gorhill/uBlock) and see if it works for you. 
B/w I tried and it loads fine with uBlock Origin.

If you are on Safari, then better go with [Adguard](https://adguard.com/en/adguard-adblock-browser-extension/overview.html#safari).
