### ISSUE TITLE
How to hide strict block warning

### ISSUE THREAD

**Issue by varkmat** [uBlock-LLC/uBlock#1603]
Hi,

i am getting following type of warnings all the time,

i don't want to temporarily nor permanently disable strict blocking for many sites,

so i want to keep strict for particular site but don't want get selecting one of those options

is there a way to hide strict block warning

http://s31.postimg.org/yzu8p3xmz/2016_04_23_3_32_35.png

---

Did read that wiki full.

But there was no mention on how to block popup for a specific site without opening warning popup.

my question is, how to keep blocking the popup and also not seeing this warning?

because this warning pop up causing as much annoyance as the popup ad it self

---

or at least give one more button in warning page, where it says, allow strict blocking for this domain permanently.

**Comment by lewisje** [comment]
This extension is no longer maintained, but even if it were, your idea is still stupid: The warning message is there for a reason, so you don't just see a blank page or a mysterious error; back when I used old Opera with its URLFilter.ini file, I would frequently get vexing problems that boiled down to strict blocking with no indication that it wasn't just the page failing to load.

**Comment by varkmat** [comment]
@lewisje 

You are genius then, There are sites that will keep on opening unwanted pop ups each time you click any part of the site, ublock will block it, but each and every time it will open a pop up and ask you to decide.

what i am saying is that, if i want to keep strict blocking for that site, just add one more button which asking "block the the site permanently without asking permission each time"

so, its not a automation, you decide in the first time, 

for example,  ad.directrev will not break any frame or create any error in the sites i visit, so i don't want to answer the warning question 1000 times.....

**Comment by lewisje** [comment]
If the auto-generated window URL matches a filter with the `$popup` option then it _will_ be closed immediately.

**Comment by varkmat** [comment]
@lewisje, Its all i wanted ! thanks u so much.

**Comment by SW1FT** [comment]
Move over to [uBlock Origin](https://github.com/gorhill/uBlock) as this uBlock is no longer being developed.
