### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by ojii** [uBlock-LLC/uBlock#1604]
I've discovered a false positive in uBlock on the admin console of our website. Unfortunately, access is behind a login-wall, so providing a URL here would be pointless.

The blocked request in the request log looks like this:

<img width="1438" alt="screen shot 2016-04-26 at 4 35 49 pm" src="https://cloud.githubusercontent.com/assets/141122/14810263/f62928ca-0bcc-11e6-9f90-915b2869192f.png">

What would be the best way for us to solve/help solve this issue?

**Comment by ojii** [comment]
The "offending" filter seems to be https://github.com/chrisaljoudi/uBlock/blob/a70a50052a7914cbf86d46a725812b98434d8c70/assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt#L81 which looks extremely broad. I assume the `.com` in the filter was meant to capture TLDs, not part of paths.

Edit: It looks like this is an adblockplus filter. But testing with adblockplus (and the easyprivacy extra filter enabled), adblockplus does not block that request.

**Comment by lewisje** [comment]
This extension is no longer maintained; if you aren't using Safari, consider switching to uBlock Origin, and if you are using Safari, stick with Adblock Plus.

**Comment by ojii** [comment]
@lewisje thank you
