### ISSUE TITLE
uBlock Doesn't Work in Pinned Tabs (Safari)

### ISSUE THREAD

**Issue by philipamour** [uBlock-LLC/uBlock#1605]
uBlock doesn't seem to be working for websites that are under pinned tabs in Safari (latest Safari, latest OS X).

**Comment by harshanvn** [comment]
uBlock is no longer under development. It is abandoned.
Try to use Adguard/ABP for Safari.
For other browsers you could try [uBlock Origin](https://github.com/gorhill/uBlock) (by the original author)

**Comment by philipamour** [comment]
@harshanvn That sucks! 🙁 Thanks for the heads up tho. I wonder why was it abandoned. Will stop using Purify for iOS as well (by the same author @chrisaljoudi ), can't trust it to be maintained. Is there a uBlock Origin branch for Safari?

**Comment by ghost** [comment]
No, and so far there won't be. The best chances Safari users have is someone else picking this up where Chris left it.
