### ISSUE TITLE
Causes Tumblr "k" shortcut on feed to break

### ISSUE THREAD

**Issue by ZachSaucier** [uBlock-LLC/uBlock#1606]
If you have a Tumblr account and go to the home page's feed (at https://www.tumblr.com/dashboard), uBlock breaks the "k" shortcut. 

Users can usually use "j" and "k" to go to the next and previous post in the feed, respectively. uBlock is currently causing this shortcut to break

**Comment by ZachSaucier** [comment]
This extension is no longer maintained. Consider switching to [uBlock Origin](https://github.com/gorhill/uBlock) and see if it works for you.

**Comment by Gitoffthelawn** [comment]
This is caused by an error in one of your lists, and is not a bug in uBlock or uBlock Origin.

**Comment by ZachSaucier** [comment]
As noted in [this thread](https://github.com/gorhill/uBlock/issues/1611#issuecomment-216921655), the problematic list was `tumblr.com#@#.standalone-ad-container` found within EasyList
