### ISSUE TITLE
[Bug] Element Blocker not working in Inspector mode for Firefox 45.0.1

### ISSUE THREAD

**Issue by Corruptinglyneedful** [uBlock-LLC/uBlock#1607]
Not doing anything when I attempt to use it to block an element.

http://i.imgur.com/4VaxD1x.png

It used to work.  What has happened?

Using Firefox x64 45.0.1 and Windows 10

**Comment by SW1FT** [comment]
Move over to [uBlock Origin](https://github.com/gorhill/uBlock) as this uBlock is no longer being developed.

**Comment by Corruptinglyneedful** [comment]
According to whom?  I didn't see any post and there was a Master branch update a few days ago.

If that's the case, that's a huge disappointment.  I left Ublock Origin because Gorhill will not block elements in Inspector mode.

**Comment by SW1FT** [comment]
According to this Github? uBlock didn't get a single update in almost 1 year, you can check it [here](https://github.com/chrisaljoudi/uBlock/commits/master).
Just move on, even if your favorite feature isn't present, plenty of fixes and other features are in uBlock Origin and definitely justify the move.

**Comment by Corruptinglyneedful** [comment]
It says Master branch was updated 9 months ago.

No, this feature doesn't work in this version and it is not present in Ublock Origin, Gorhil told me he would not be adding it since it was a "firefox" only feature.

Nope, this feature is absolutely required to block extremely stubborn cosmetic things.

If I can't get it Ublock or Ublock Orgin than ya'll programs can fuck off.

It's back to Adblock plus for me.

**Comment by harshanvn** [comment]
> Nope, this feature is absolutely required to block extremely stubborn cosmetic things.

uBlock Origin has similar tool at its disposal, its own DOM Inspector (which works in all browsers). **Which sole purpose is to deal with these cosmetic filtering..**
One can access it through the logger, and select <code><></code> option on the right hand side.

> It's back to Adblock plus for me, at least they listen.

No need to be snarky! Gorhill impelemts/implemented whatever features are deemed relevant.

**Comment by Corruptinglyneedful** [comment]
Where is this feature?  I open Inspector mode and I can't find anything.

**Comment by harshanvn** [comment]
Here is an example - Remember to select the tab in the dropdown to access a particular tab.

![ublock dom inspector](https://cloud.githubusercontent.com/assets/779630/15173072/e61fe868-1727-11e6-8647-1d7fc4a7bfe5.png)

Though i would agree if @gorhill can implement some kind of docking mechanism for the DOM Inspector to tie it to a particular tab. However, with his busy schedule not sure if he can get a chance to look at these cosmetic things!

**Comment by Corruptinglyneedful** [comment]
How would you even know what section is what?  How do you even get to that point?

**Comment by harshanvn** [comment]
Try to hover each element after another. You will see its reflection on the site with blue overlay.

**Comment by Corruptinglyneedful** [comment]
How do I activate though?

**Comment by harshanvn** [comment]
I did not get the question, sorry!

**Comment by Corruptinglyneedful** [comment]
How do I activate this feature in ublock origin?  How do I do it?

I can't seem to find it.  I need the exact steps.

Pretend I'm dumb xD

**Comment by hrxn** [comment]
I don't know what went wrong on your side..
You need to open the logger:
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-number-of-requests-blocked

> Click the list icon to open the network request logger in a separate tab. This allows you to inspect real-time network traffic within the browser

And then the `<>` icon

Oh, and by the way, I don't think that you actually need this, because the new element picker mode allows a much broader selection range.

**Comment by Corruptinglyneedful** [comment]
What element picker in Ublock Origin?

**Comment by harshanvn** [comment]
Read the wiki here - https://github.com/gorhill/uBlock/wiki/Element-picker

> Oh, and by the way, I don't think that you actually need this, because the new element picker mode allows a much broader selection range.

I agree with you. I am wondering one would rarely need to open up DOM Inspector!

**Comment by Corruptinglyneedful** [comment]
And how would I utilize that to block cosmetics in 3D mode, within Inspector Tools, within Firefox?

There are certain elements you can't get to with that element picker.  But you CAN get to them in 3D mode, therein lies the problem.

**Comment by harshanvn** [comment]
No, you can not utilize any of the firefox built in tools. This is because the solution choosen by @gorhill was browser independent one. 

Can you give us few example sites where cosmetic filters can only be created by 3d mode. I would like to try and see if uBlock origins element picker works or not

**Comment by Corruptinglyneedful** [comment]
I'm thinking of a lot of adult entertainment sites here.  They have those pesky ads.  Perhaps you could get through with just Inspector mode, but I'm stupid and I need a gui way to do it.

This is why I liked doing it the way I like doing it.

I don't understand a lot of what this stuff is, It's HTML something or Javascript, idk.

All I know is I want to block pesky adds, deep buried in the pages, without ruining parts of the site,  in the fastest and easiest way possible; sometimes the cosmetic filters don't help with that and I have to go deeper.

**Comment by Corruptinglyneedful** [comment]
_Did not mean to close that._

**Comment by hrxn** [comment]
BTW, this 3D mode will be scrapped from Firefox anyway..

**Comment by Corruptinglyneedful** [comment]
What are you on about now?
