### ISSUE TITLE
Goodblock Icon blocking Page Content

### ISSUE THREAD

**Issue by fogoplayer** [uBlock-LLC/uBlock#1609]
The extension blocks elements on the page. Normally, this is not an issue, but on certain websites that have navigation and controls in the lower left, the Goodblock icon prevents users from being able to click on those controls. 

This should be fixed if the body of the visual, in-window portion of the extension was adjusted to be the size of the icon, using margins to compensate for the smaller div.
With Goodblock 
![screenshot 2016-05-10 at 4 05 16 pm](https://cloud.githubusercontent.com/assets/13542612/15160707/02a5dbe6-16c9-11e6-9ed7-62183005f483.png)
Without Goodblock
![screenshot 2016-05-10 at 4 06 06 pm](https://cloud.githubusercontent.com/assets/13542612/15160727/2170a9c0-16c9-11e6-9d0b-76212f668376.png)

**Comment by lewisje** [comment]
You've just opened an issue on an unmaintained fork of uBlock (the original, still being updated, is known as uBlock Origin, and you should consider switching to that); this appears to be the closest thing to a support page that exists for Goodblock, which I had not heard about before reading this issue: https://gladly.zendesk.com/hc/en-us
