### ISSUE TITLE
Can ublock dissable antifeatures like non-selectable text?

### ISSUE THREAD

**Issue by timthelion** [uBlock-LLC/uBlock#1614]
Hello, I noticed that I cannot select text on this page http://whatdotadpoleseat.com/tadpole-food-types/ I feel that ublock or some other software should protect me from anti-features like this. Is that possible?

**Comment by lewisje** [comment]
If you can select text again by blocking some script (whether third-party or inline), then uBlock Origin will be able to help; also, unless you're on Safari, you should move to uBlock Origin, which unlike this extension is still being developed.
