### ISSUE TITLE
This Project is Dead

### ISSUE THREAD

**Issue by asoksevil** [uBlock-LLC/uBlock#1617]
What are your alternatives? Last commit was made on August 2015. Funny how @chrisaljoudi is still seeking for donations toward a dead project (where's that Purify for OSX promise?)

I am currently testing out JSBlocker, which is performing relatively well.

**Comment by dashed** [comment]
@asoksevil https://github.com/gorhill/uBlock

**Comment by hrxn** [comment]
I think he meant for Safari users, for example :stuck_out_tongue_winking_eye:
