### ISSUE TITLE
The certificate ran out.

### ISSUE THREAD

**Issue by n1trux** [uBlock-LLC/uBlock#1618]
related to #1617 and the fact that there are 279 un-resolved issues?

I suppose switching to µBlock Origin is the right choice here.

**Comment by thebuccaneersden** [comment]
Can confirm. 5 days later and this is still an issue.

**Comment by emilstahl** [comment]
Not fixed...

**Comment by n1trux** [comment]
Why would it be fixed? The project is dead. No updates for 9 months.

Use https://github.com/gorhill/uBlock/ instead.

**Comment by z3ntu** [comment]
The certificate was actually renewed on June , so somebody is still in control of the website / the certificate.

**Comment by ghost** [comment]
^ and collecting donations. @chrisaljoudi will you  ~~stop this scam~~ fix this error? Maybe do the right thing and handover the domain to uBlock origin?

**Comment by z3ntu** [comment]
Also many people don't know that uBlock is not developed anymore and that uBlock Origin exists... :(
