### ISSUE TITLE
Script Blocking Permanent Except Can't be Undone

### ISSUE THREAD

**Issue by Industry** [uBlock-LLC/uBlock#1619]
I had a domain block enabled for `||youjizzlive.com^` and when browsing in Chrome's incognito mode, the page came up and I accidentally allowed the page to permanently bypass the no-strict-blocking. This was the first time it happened so I looked for a solution on how to re-block the page.

I came across this [helpful github wiki site](https://github.com/chrisaljoudi/uBlock/wiki/Quick-guide:-popup-user-interface#no-strict-blocking) site but found that [the little icon](https://raw.githubusercontent.com/chrisaljoudi/uBlock/master/doc/img/popup-1h.png) they refer to that's supposed to appear when a page has an exception to the no-script-blocking doesn't on my computer. See [this screenshot](https://i.imgur.com/kUa2cat.png).

So I wasn't sure how to undo what I had done.

I tried replicating the issue in Chrome's regular mode and was able to, but again the icon didn't show up. At least this time I found that the override setting appears under uBlock's My Rules tab.

So I removed the rule.

But _now_ the issue is that the page isn't ever being blocked. It has a permanent exception and I can't get uBlock to stop access any more. I even reentered the `||youjizzlive.com^` in My Rules without any luck.

I'm not really looking for a solution to this particular problem, I'm just bringing it up so that someone can look into the functionality and determine if it's a bug.

**Comment by Industry** [comment]
This seems to work again after restarting the browser. But I don't know, maybe others will have the same issue when switching between Chrome + Incognito

**Comment by Industry** [comment]
This seems to work again after restarting the browser. But I don't know, maybe others will have the same issue when switching between Chrome + Incognito

**Comment by lewisje** [comment]
Your screenshot was of uBlock Origin, which has diverged significantly from this extension; the correct project to complain on, for the future, is https://github.com/gorhill/uBlock/
