### ISSUE TITLE
Make possible to make exceptions from the logger.

### ISSUE THREAD

**Issue by kangarooo** [uBlock-LLC/uBlock#1620]
Make possible to make exceptions from the logger.
In logger when i fin what is blocked user wants to select and make action with it to add to exceptions like its possible in AdBlockPlus very fast and easy. Other wise user needs to learn how to make exception and since no one does that for a day to just do 1 simple thing then god hope they will know how to disable only one list of blocks and not all Adblocker or uBlock.

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock . It already includes the feature you want.

Please close this issue.
