### ISSUE TITLE
uBlock is blocking addthis widget

### ISSUE THREAD

**Issue by MowWow** [uBlock-LLC/uBlock#1622]
Hi,

We're a web development company, and for all the websites we develop, we use the addthis (https://www.addthis.com/) widget for sharing content on the social medias.

for some reason (surely because it contains the word "ad"), the addthis sharing widget is always blocked by ublock (i spent hours searching for the reason why the widget isn't displayed, till i found out it wass ublock)

Is it possible for you to stop blocking addthis widgets by default ?

Thanks a lot !

**Comment by Rimmer7** [comment]
In other words, the filters that block trackers are working as intended.

**Comment by artur-stepien** [comment]
If this is working as intended for you, well. Good luck.
