### ISSUE TITLE
click anywhere on the page -> pop up issue

### ISSUE THREAD

**Issue by rayman89** [uBlock-LLC/uBlock#1623]
I noticed there are many sites now that the first click you
do on the page it makes you open an other tab or pop-up. The pop-up/tab
is almost always closed immediately by ublock but is it possible to
disable that tab/pop-up from ever opening? Thanks for your time.

Example: http://animeflv.net/ or http://gorillavid.in/anq4ij0u58ug1

I'm using firefox 45 ESR x64 on W7 x64

The pop-ups and tabs that open have this format:
data:text/html;base64,PGh0bWw+PGJvZHk+PHNjcmlwdD52YXIgZXBvY2ggPSBuZXcgRGF0ZSgpLmdldFRpbWUoKTt2YXIgX2Vwb2NoRnJvbVdpbmRvd05hbWUgPSB3aW5kb3cubmFtZS5zcGxpdCgnXycpWzNdO2lmKGVwb2NoIC0gX2Vwb2NoRnJvbVdpbmRvd05hbWUgPCAyNTApe3dpbmRvdy5sb2NhdGlvbj0nJzt9PC9zY3JpcHQ+PC9ib2R5PjwvaHRtbD4=

I tried ||data:text/html^$popup to prevent it for opening but it's the same.

I have the default options enabled with anti adblock killer, spa, malaware domains, easy privacy, easy list all the ublock filters minus experimental.

**Comment by tigefa4u** [comment]
i hate this too :rage:
