### ISSUE TITLE
Yandex (biggest search engine in Russia) ads not blocked

### ISSUE THREAD

**Issue by ethaniel** [uBlock-LLC/uBlock#1626]
Notice the first 2 ads + the third one is Yandex promoting it's own website.
They are not gone.

URL: https://yandex.ru/search/?text=%D0%BA%D0%B2%D0%B0%D1%80%D1%82%D0%B8%D1%80%D0%B0%20%D0%BC%D0%BE%D1%81%D0%BA%D0%B2%D0%B0&lr=10620

![image](https://cloud.githubusercontent.com/assets/941973/16898676/4c69fc52-4c0d-11e6-9864-d4052f2ec995.png)

**Comment by SomeUsername13** [comment]
Add `##div.serp-adv-item` to your filters. This seems to work most of the time. It depends on the search result being part of the `serp-adv-item` class. A couple times, the search result appeared to be an ad but wasn't part of the class. I can't read these sites so that makes it harder to identify the issue.

**Comment by VitaliyAT** [comment]
This is ony example. Yandex ads can be everywhere. Page load scripts that checkin ads on page, if not then script recreate all ads structure. CSS-based filters not work against scripts. Until you stay in css-like-filter age you never ever cut adblocks. Userscripts can do job, but nobody did it yet. Nobody add filters (only payed AdGuard as I know) based on userscripts. Who will be first - wil be first.

**Comment by h8nor** [comment]
@ethaniel, they constantly change something, because they live at the expense of advertising. [My recommendation](//github.com/bopoh13/docs/blob/acebc68155f38e476ad77be3828fe704c29581e8/vendor/firefox/adblockedge.txt#L93-L94) on today. Incidentally, this project is dead.

**Comment by ethaniel** [comment]
uBlock Origin solved this with:

yandex.ru##.serp-item:has(:scope > .organic > .organic__subtitle > .label_color_yellow)

**Comment by migueldemoura** [comment]
@ethaniel, why is this issue still open?

**Comment by lulbehanger777** [comment]
Russia is the largest claimed territory on this globe.
And the political course there is a real challenge for the rest of the house...
If Russia had an issue with an other houses,
We'll all be overwhelmed with the reporting all over our precious freedom called the media.
Russia has been a good one in history for centuries old.
Always on standby mode for a few bombs on some "naughty" opposite house holding.
And it's laws in the rural areas over there are not the priorities in the master plan.

Over there everything is legal.
So the interest of them in the www. Scheisse..
Is equal to all the "civilized" houses in this multiversum.

So represented!

<Go: Languages.>
