### ISSUE TITLE
Website not visible 

### ISSUE THREAD

**Issue by honsberg** [uBlock-LLC/uBlock#1627]
this website cannot by viewed because it detects the adblocker

http://www.auto-motor-und-sport.de/fahrberichte/test-fahrt-neuer-porsche-panamera-turbo-11401822.html

http://prntscr.com/bv76qt

**Comment by Luckz** [comment]
use "ublock origin" / https://github.com/gorhill/uBlock#installation , not this ublock, and combine with https://github.com/reek/anti-adblock-killer
