### ISSUE TITLE
[Firefox] Feature request: More private cache / session based

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1629]
Hello,

now: I open domain.xyz and get files on my disc like index.html, wikileaks.jpg and more for caching.
I know: I could disable caching by setting the folder to /dev/null or equivalent. but this makes my browser slow.
My requested feature (can not done by extension):
1. When the browser is starting it will generate a long random string.
2. If a page is read then all filenames are hashed and the filecontent is xor-ed with the random string and be written to the harddrive.
3. The browser can access these files and their contents as long as the random string is know.
4. After closing the browser the files are worthless and can be deleted. Their content is now white noise.

I don't need 300-400MB cached files on my disc. And if somebody (spammers, girlfriend, think of somebody you don't want see) wants to have a look at my files then he/it/she sees only trash or my browser history.

Michael

PS. I've searched the functions of .ext but couldn't find any to alter cached files before they were written to the drive.

**Comment by SW1FT** [comment]
This fork has been dead for 1 year. Just use [uBlock Origin](https://github.com/gorhill/uBlock) which is maintained by the original creator of uBlock.
