### ISSUE TITLE
Domain blacklisted by UBlock 

### ISSUE THREAD

**Issue by yigald** [uBlock-LLC/uBlock#1630]
Hi,

Our domain (track.atom-data.io) is being blacklisted by your extension which is causing us harm. Our domain is clean under virus total and there is no reason for it to be flagged. Please remove the flag immediately.

Thanks

**Comment by Rimmer7** [comment]
Working as intended.

**Comment by yigald** [comment]
Dear Chris,
We would appreciate a clarification per your last email - can you please elaborate as to the reasons for marking our URL.

Many thanks in advance,

Yigal

**Comment by SW1FT** [comment]
This fork has been dead for 1 year. Just use [uBlock Origin](https://github.com/gorhill/uBlock) which is maintained by the original creator of uBlock.
