### ISSUE TITLE
NextDoor.com Sponsored Content/Ads not being blocked

### ISSUE THREAD

**Issue by prdonahue** [uBlock-LLC/uBlock#1631]
![screen shot 2016-08-06 at 2 02 56 pm](https://cloud.githubusercontent.com/assets/4582374/17459048/d5fb0674-5bde-11e6-93ab-d011b09ecddf.png)

**Comment by SW1FT** [comment]
This fork has been dead for 1 year. Just use [uBlock Origin](https://github.com/gorhill/uBlock) which is maintained by the original creator of uBlock.
