### ISSUE TITLE
Could you add userscript based fiters as in AdGuard?

### ISSUE THREAD

**Issue by VitaliyAT** [uBlock-LLC/uBlock#1632]
You (we) try catch ads by css-like filters. I want (need) that uBlock update functionality for userscript based filters. Jquery sintax prefer, but it's not critical. It's higher level then css - more powerful and flexible.

**Comment by SW1FT** [comment]
This fork has been dead for 1 year. Just use [uBlock Origin](https://github.com/gorhill/uBlock) which is maintained by the original creator of uBlock.
