### ISSUE TITLE
rule generation, make general [yahoo]

### ISSUE THREAD

**Issue by curmedgeonly** [uBlock-LLC/uBlock#1633]
I used the picker to hide a fake inbox item for yahoo mail but it created a specific unique instance rule
### yui_3_16_0_1_1470685513716_400960 > .flip-ad-and-rating.search-message-container-ad

How do I use 

 .flip-ad-and-rating.search-message-container-ad

As the rule for anytime?    That per se does not work.  I do not understand CSS myself to make use of that portion.  

Alternatively how could that second bit be combined with XPath (which I only know about but do not understand to use myself) since the placement in the page will be the same?

![screen shot 2016-08-10 at 9 38 17 pm](https://cloud.githubusercontent.com/assets/20962795/17578807/da37591a-5f42-11e6-8695-e458f4459285.png)

**Comment by SW1FT** [comment]
This fork has been dead for 1 year. Just use [uBlock Origin](https://github.com/gorhill/uBlock) which is maintained by the original creator of uBlock.
