### ISSUE TITLE
ublock not able to block sponsored ads from pages

### ISSUE THREAD

**Issue by peopledrivemecrazy** [uBlock-LLC/uBlock#1634]
![](http://puu.sh/qxfsV/f6723a6a01.jpg)

using firefox

**Comment by SW1FT** [comment]
This fork has been dead for 1 year. Just use [uBlock Origin](https://github.com/gorhill/uBlock) which is maintained by the original creator of uBlock.

**Comment by catuss-a** [comment]
@SW1FT I have the one you linked and it shows ads sometimes even on youtube

**Comment by SW1FT** [comment]
@catuss-a That can't be right, I don't see any ads on youtube since I've installed uBO which was a long long time ago. Please make a new issue over at https://github.com/uBlockOrigin/uAssets/issues
