### ISSUE TITLE
uBlocks Plan For Facebook Ads

### ISSUE THREAD

**Issue by teamcoltra** [uBlock-LLC/uBlock#1635]
As of [this post](https://adblockplus.org/blog/fb-reblock-ad-blocking-community-finds-workaround-to-facebook) from Adblock Plus the fix was 

`facebook.com##DIV[id^="substream_"] ._5jmm[data-dedupekey][data-cursor][data-xt][data-xt-vimpr="1"][data-ftr="1"][data-fte="1"]
`
but this has been since fixed. An updated post says to just keep your Adblock list updated, which I believe they use https://github.com/easylist/easylist (further /easylist/easylist_specific_hide.txt) to base this on. I realize that uBlock also pulls from the EasyList as part of our sources.

The most recent code as of the past 24 hours is:

```
facebook.com##div[id^="sponsoredTickerStory_"]
facebook.com##div[id^="substream_"] ._5jmm[data-dedupekey][data-cursor][data-ftr="1"][data-fte="1"]:not([data-timestamp])
facebook.com##div[id^="substream_"] .userContentWrapper > ._1ifo
facebook.com##div[id^="substream_"] div[data-ft*="\"ei\":\""]
```

but this still seems not to be working. As Facebook may get into a war of sorts over blocking, is this worth bumping the update time on the EasyList to being a 24 hour list, or perhaps creating a specific FB list that can be checked more regularly? As one of the most visited websites on the internet I don't think it's too weird to create a special rule surrounding it. 

Just my thought.

**Comment by SW1FT** [comment]
This fork has been dead for 1 year. Just use [uBlock Origin](https://github.com/gorhill/uBlock) which is maintained by the original creator of uBlock.
