### ISSUE TITLE
Safari Technology Preview 14 memory goes up extremely fast

### ISSUE THREAD

**Issue by digitalresistor** [uBlock-LLC/uBlock#1640]
The latest version available from ublock.org when used with Safari Technology Preview 14 causes massive issues, it starts using memory and never lets up until the system freezes. I had to uninstall the extension for now.

Just a heads up!

**Comment by iphoting** [comment]
uBlock locks up STP 14 for me. Had to disable it too.

**Comment by CasualDeveloper** [comment]
Same here.

**Comment by robrepp** [comment]
Same symptoms, same escalation in the RAM consumption on STP14.

**Comment by chrisaljoudi** [comment]
Investigating. (Difficult to do since this freezes STP almost instantly).

**Comment by skyebook** [comment]
FWIW, this seems to happen during blocklist updates

**Comment by caobo** [comment]
@chrisaljoudi Nice to see you back ^_^

**Comment by brianmbutler** [comment]
STP15 is out.  "Fixed an issue where Safari Technology Preview would consume excess memory when certain Safari Extensions were installed"

Testing, but maybe it'll be easier to investigate memory issues.

**Comment by kane-c** [comment]
I can confirm that this issue is resolved with STP 15

**Comment by CasualDeveloper** [comment]
Same here. uBlock now works with STP again, as of v15.
