### ISSUE TITLE
contentscript.js runs even if uBlock turned off

### ISSUE THREAD

**Issue by Jestar342** [uBlock-LLC/uBlock#1641]
Meaning the exception to block content can still be thrown, blocking content. 

I am a web-developer and this is sometimes needed to do my work :)

**Comment by Jestar342** [comment]
By turned off I mean the big blue power button in the uBlock extension controls. If I disable the extension completely, the script does not execute.

**Comment by noma4i** [comment]
Xmas soon. Any news so far?

**Comment by Nitwitsworld** [comment]
My uBlock is doing great on my end. Thanks for the Christmas greetings. :3

**Comment by jononomo** [comment]
I have also noticed that I cannot turn uBlock off.  This seems like an egregious oversight.

My expectation is that with uBlock turned off, I should not see uBlock-related errors being thrown in the console.

However, with uBlock turned off I am seeing uBlock-related errors in the console - specifically "uBlock Origin: aborting content scripts for <some window.location>"

How can I turn uBlock off fully?

**Comment by Nitwitsworld** [comment]
Maybe magic. lol

**Comment by jononomo** [comment]
@Nitwitsworld shut up

**Comment by Nitwitsworld** [comment]
I'm new to this stuff as well. No need to insult a joke. Sheesh!

**Comment by alexandroid** [comment]
I am not sure if it's the same issue or not, but I am getting a blank page when I sign in and try to go to https://aws.amazon.com/marketplace/library. Both in FF & Chrome with uBlock installed. Console shows:

```
contentscript.js:79 Uncaught Error: uBlock Origin: aborting content scripts for
https://aws.amazon.com/marketplace/library?internal-redirect=MARKETPLACE&....
```

Disabling uBlock for the current website or whitelisting aws.amazon.com does not help. JS debugger shows the vAPI as `'undefined'`. Although it looks like it might be a bug on that site because even if I disable extension in Chrome settings, the site still does not work (blank page, nothing in Console).

Update: clearing cookies helped, so it may be unrelated.

**Comment by lavoiesl** [comment]
Same with bankofamerica.com

```
contentscript.js:79 Uncaught Error: uBlock Origin: aborting content scripts for https://sso-ce.bankofamerica.com/am/Consumer/metaAlias/bofa/sp
    at contentscript.js:79
(anonymous) @ contentscript.js:79
Login:1 GET https://sso-ce.bankofamerica.com/am/UI/Login 400 (Bad Request)
```

**Comment by mplogas** [comment]
Same issue when testing a local IdentityServer with a test-webclient
```
Uncaught Error: uBlock Origin: aborting content scripts for http://localhost:4477/Home/Contact at contentscript.js:79
```

**Comment by jorgemmsilva** [comment]
yap, this is happening

**Comment by pdwalker30** [comment]
+1 this is interfering with web development.

**Comment by pherris** [comment]
+1

**Comment by hybridview** [comment]
I also get this uBlock exception on pages where uBlock is turned off. Does the script still need to be injected when disabled due to a technical issue?

**Comment by JCharante** [comment]
I also get this error when trying to look at pictures of kittens over at http://placekitten.com/1920/1080

```
Uncaught Error: uBlock Origin: aborting content scripts for https://placekitten.com/1920/1080 at contentscript.js:79
```

**Comment by mvanderlee** [comment]
+1 this breaks http://labs.play-with-docker.com/

**Comment by elwynelwyn** [comment]
+1, when devtools are open and you have "Pause on exception" enabled (e.g. debugging your own code) this is incredibly disruptive.

**Comment by leafoflegend** [comment]
+1 This is a major problem and will cause any sort of modern web-dev to uninstall.

**Comment by jamesfiala** [comment]
+1 Can confirm. Am modern web-dev and had to uninstall since I can't debug my code. Returning to ABP for now, unfortunately.

**Comment by JCharante** [comment]
+1, have been watching thread since Christmas but finally decided to at least bump it.

**Comment by jyan-zarate** [comment]
Are you guys sure you are reporting this in the right repository?

When looking at the js console for https://upload.wikimedia.org/wikipedia/commons/a/a0/Svg_example1.svg with `uBlock` enabled, I don't see any errors in the console, but when I have `uBlock Origin` enabled it gives the error that @lavoiesl, @mplogas, and @alexandroid have shared.

```
contentscript.js:90 Uncaught Error: uBlock Origin: aborting content scripts for https://upload.wikimedia.org/wikipedia/commons/a/a0/Svg_example1.svg
    at contentscript.js:90
```

This is the repository for uBlock, as the readme points to ublock.org, so why would the error say `uBlock Origin`?

uBlock Origin, which states is not related to ublock.org, has its repo over at https://github.com/gorhill/uBlock and this repo's readme says:

```
About uBlock

Some users might want to check out uBlock Origin: a noteworthy personal fork of uBlock from @gorhill with a slightly different featureset.
```

---

Even if you were creating an issue in the correct repository, the last commit was on the 23rd of August of 2015, so there's little hope of receiving a response here.

**Comment by ajayyy** [comment]
Install uBlock Origin

**Comment by JedMeister** [comment]
FWIW I'm having this issue with uBlock origin too (hence how I found my way here). But I will go post over on the uBlock Origin issues...

**Comment by ajayyy** [comment]
Ok, I just find it crazy this guy still gets donations.

**Comment by mfcallahan** [comment]
Same thing still happening to me in July 2018...

**Comment by mxchinegod** [comment]
Wait I'm confused; this still hasn't been fixed? I'm looking at the console and countless .svg errors are popping up even though I have it disabled. Isn't this more or less invasive action for uBlock to be taking? What does "off" mean if not off?

**Comment by ajayyy** [comment]
Try uBlock Origin, this one is not maintained at all.
