### ISSUE TITLE
uBlock prevents Zopim helpdesk chat widget from working

### ISSUE THREAD

**Issue by s1h4d0w** [uBlock-LLC/uBlock#1642]
I was working at home for a change today and noticed something weird with the chat widget we show in the bottom right corner. I couldn't open it. When I clicked it nothing happened, and firebug didn't show anything in the console. I tried it in both Firefox and Chrome but the same thing. 

It's a widget we use so our users can immediately ask us for help when they get stuck using our product. So I reached out to Zopim, the company that provides us with their chat functionality and they told us it worked fine for them.

That's when I realized I had uBlock installed on both Chrome and Firefox, and after disabling it it worked fine. How can this be fixed? I'm guessing it's some sort of false positive, because this is just a piece of functionality of our website, nothing used for advertisement, etc.

Website of the chat widget: www.zopim.com

I sadly don't have a link to one of our websites because it's a closed community thing.

![2016-10-10 16_20_23-postvak in - helpdesk onsplatform tv - outlook](https://cloud.githubusercontent.com/assets/5654654/19239277/8bf02abe-8f05-11e6-9adf-a60f3013e728.png)

![2016-10-10 16_21_34-postvak in - helpdesk onsplatform tv - outlook](https://cloud.githubusercontent.com/assets/5654654/19239295/a3c503f8-8f05-11e6-93fa-ff2b6d9bd09c.png)

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock

Please close this issue.

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock , and report any filter problems to list maintainers instead of posting on the extension repository. You can use the logger to find out what the problematic filter is: https://github.com/gorhill/uBlock/wiki/The-logger .

Please close this issue.

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock , and use the logger to see what filter rule is blocking your requests and whitelist it or report it to the list maintainers: https://github.com/gorhill/uBlock/wiki/The-logger

Please close this issue.

**Comment by s1h4d0w** [comment]
Ah, found the link on google. Clear.
