### ISSUE TITLE
Will there ever be a Purify for Mac?

### ISSUE THREAD

**Issue by etresoft** [uBlock-LLC/uBlock#1644]
I'm not interested in uBlock Origin.
I paid for 1Blocker but it is hard to keep it running.
I paid for Purify for iOS too.
Money on the table for anyone who wants it. Just sayin'.

**Comment by PCheezo** [comment]
same!

**Comment by anewuser** [comment]
Please don't post off-topic questions on Github repositories. You can reach the owner of this repository with the contact info on his profile page: https://github.com/chrisaljoudi

Please close this issue.
