### ISSUE TITLE
Please block ads on Voot and hotstar

### ISSUE THREAD

**Issue by AbhimanyuAryan** [uBlock-LLC/uBlock#1645]
Please block ads at www.voot.com & www.hotstar.com 

they load ads dynamically from there server. So its sort of possible

**Comment by AbhimanyuAryan** [comment]
<img width="1260" alt="screen shot 2016-10-26 at 4 58 37 am" src="https://cloud.githubusercontent.com/assets/8083613/19707962/e76719fe-9b38-11e6-9107-c3ff9c657c19.png">

**Comment by shaheen12345** [comment]
please block adds www.voot.com
