### ISSUE TITLE
Trouble with Business Insider

### ISSUE THREAD

**Issue by RockyMM** [uBlock-LLC/uBlock#1646]
It appears that Business Insider is doing some ad-blocker detection.

<img width="1069" alt="screen shot 2016-10-28 at 01 31 50" src="https://cloud.githubusercontent.com/assets/1906065/19789288/cb31fcc8-9cae-11e6-8006-3c7ba45fc355.png">

Is there a way around this?

**Comment by ojasp** [comment]
I use uBlock Origin along with Privacy Badger and that seems to take care of it. This can be a workaround in the meantime.

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock .

After replacing the extension, you can report problems like that here: https://github.com/uBlockOrigin/uAssets 

Please close this issue.

**Comment by RockyMM** [comment]
Closed per @ojasp's explanation
