### ISSUE TITLE
Are you blocking bugsnag?

### ISSUE THREAD

**Issue by dejakob** [uBlock-LLC/uBlock#1648]
We are using bugsnag in an Angular project. It seems that uBlock is blocking the angular dependency and because the dependency cannot load, our entire webapp also can't. We are not serving any ads on our site, so I don't get why anything should be blocked...
We're not using the bugsnag plugin to track or store personal data, but to track bugs and crashes on our website...

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock . 

This page explains how to find out what is blocked by the extension and why: https://github.com/gorhill/uBlock/wiki/The-logger

Please close this issue.
