### ISSUE TITLE
Please unblock the sponsor message on troyhunt.com

### ISSUE THREAD

**Issue by Y90SMH** [uBlock-LLC/uBlock#1649]
The blog owner has made a conscious effort to include an unobtrusive sponsor message and yet it is blocked.

This seems against the whole spirit of ad blocking.
There are no scripts/images used, the text is not misleading.

**Comment by p1r473** [comment]
Please don't start whitelisting ads as this user is requesting, or the next thing you know, this will be like Adblock Plus with their "allowed ads"

**Comment by spirillen** [comment]
> ... this will be like Adblock Plus with their "allowed ads"

```bash
sed 's/Adblock Plus with their "allowed ads"/Adblock Plus with their PAID "allowed ads"/'
```
