### ISSUE TITLE
uBlock or Safari up to date?

### ISSUE THREAD

**Issue by Mattel88** [uBlock-LLC/uBlock#1650]
hello is it working for safari? I found a download in the net but after installation all filters are on "old". Is Safari still supported?

**Comment by Mattel88** [comment]
Nobody?

**Comment by xwinus** [comment]
Hi @Mattel88, I've downloaded the uBlock for Safari right now from the official website (https://www.ublock.org) and it works just fine (macOS Sierra 10.12.1, Safari 10.0.1)

**Comment by ghost** [comment]
Hi, I can't download the extension from the official webpage. I also try from the link on the README but it doesn't work too.

Links I have try:
[https://extensions.apple.com/details/?id=net.gorhill.uBlock-96G4BAKDQ9](https://extensions.apple.com/details/?id=net.gorhill.uBlock-96G4BAKDQ9)
[https://cloud.delosent.com/ublock-safari-0.9.5.2.safariextz](https://cloud.delosent.com/ublock-safari-0.9.5.2.safariextz)

**Comment by ghost** [comment]
Fixed! I try again and I can download the file. Don't know what happen.

**Comment by meat-ball** [comment]
this extension is no longer maintained (hasn't been for some time).  I'm not sure why the dev doesn't mention it here or on his ublock web page

**Comment by daBee** [comment]
I am having issues with video player dimensions.   Much too short for vertical video.

http://truckyeah.jalopnik.com/even-the-cops-appreciate-when-you-turn-a-near-crash-int-1791190968

**Comment by meat-ball** [comment]
https://github.com/el1t/uBlock-Safari
