### ISSUE TITLE
How do I override a rule from a list - in this case. the Fanboy list block on the ebay "Scroll to top" arrow?

### ISSUE THREAD

**Issue by Andy2No** [uBlock-LLC/uBlock#1657]
I'd like the "Scroll to top" arrow put back on my ebay pages.  How do I override the rule that's been added to the Fanboy lists that hides the arrow?

This is the filter, from those lists, that stops it being shown, according to the logger:

Static filter ##img[alt="Scroll to top"] found in:

    Fanboy’s Annoyance List
    Fanboy+Easylist-Merged Ultimate List

I don't really see the point in blocking the appearance of the ebay Scroll to top arrow - especially as I still see a transparent box where it should be.  To me, taking this arrow away from me is an annoyance.  I don't see what harm it's meant to be doing, and it's a feature I use a lot, since I have searches set to show 96 items per page.

uBlock Origin is very useful, but the user interface of a bit of a mystery to me.  I see no obvious way of overriding a rule from a list like this, other than unsubscribing from the list, which seems like an overreaction.

**Comment by SamuelWAnderson45** [comment]
This is not uBlock Origin. You are looking for this: [https://github.com/gorhill/uBlock/](https://github.com/gorhill/uBlock/)
