### ISSUE TITLE
Block blockadblock

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1658]
uBlock needs to support defeating https://blockadblock.com/ (this also acts as the example url) as it goes a step further than most blockers. Not only does it use CSS keyframes to show an overlay after a set timeout (meaning running without JS still causes the overlay to show), but they also remove all other DOM elements so you can't just right-click > delete node. The only way to get past it is to run without js and then remove the overlay node.

Pretty sure this is not something that can be defeated by a simple blocklist update.

**Comment by cookiengineer** [comment]
@impala2 Please check out [ublock origin](https://github.com/gorhill/uBlock). The ublock project is not maintained anymore and scam.
