### ISSUE TITLE
Accepting donations is dishonest

### ISSUE THREAD

**Issue by SamuelWAnderson45** [uBlock-LLC/uBlock#1659]
The website has not been updated to reflect the status of the project. It should be taken down, or at least have link to uBlock Origin. At the very least remove the donation button from the site.

There have been no commits since August of 2015. 1.5 years. No status updates. Nothing but silence. @chrisaljoudi I know you got screwed over when all the uBlock drama happened. You got a lot of heat and a lot of it wasn't your fault. I supported you then. But things are different now. You obviously have no intention of developing the project. Stop the donation madness. It's just not right.

**Comment by cookiengineer** [comment]
Can confirm, intensions of @chrisaljoudi are definitely not to support the project and more ripping off as much money as he can while he still has the buzz of unknowing users.
