### ISSUE TITLE
Blocks video plugin loading instead of just blocking the ad.

### ISSUE THREAD

**Issue by blis5fool** [uBlock-LLC/uBlock#166]
There is a site I go to watch Korean TV shows and it appears the uBlock blocks the video plugin loading. Here is the direct link to the page with the video:
http://www.ondemandkorea.com/non-summit-meeting-e07.html?lang=en

I get the "Error loading plugin: Plugin file not found"

If I disable uBlock then the video plays fine but the ad at the beginning of the video is displayed as well.
You can tell it's an ad from the message that's displayed at the top of the video "Advertisement: ..."
If I turn on ABP, the ad is blocked properly.

**Comment by gorhill** [comment]
Thanks for reporting. I traced back the problem to Peter Lowe's hosts file blocking `liverail.com`. Will provide a fix asap.

**Comment by gorhill** [comment]
Go to _"3rd-party filters"_ tab, and see if there is an update for "uBlock filters". If not, restarting (disable/enable) the extension should force a fetch of the fix if you have auto-update enabled.

**Comment by blis5fool** [comment]
Wow. Thanks for the quick turn around. I will check it out now.

**Comment by blis5fool** [comment]
It's working now. Thanks!!
