### ISSUE TITLE
Tiny Little Suggestion

### ISSUE THREAD

**Issue by KatkayApps** [uBlock-LLC/uBlock#1661]
Congratulations to all you guys developing this project. uBlock is FANTASTIC.
I just have one feature request: is there a way for you guys to make uBlock block those boxes and info windows that appear when you watch youtube videos? Some channels insist on annoying the hell out of viewers by showing little boxes about their other videos and subscriptions, etc.

thanks

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock#installation

After replacing the extension, add one of the filters from this page: https://youtube.adblockplus.me/

Please close this issue.
