### ISSUE TITLE
ublock blocks audio playback at vk.com

### ISSUE THREAD

**Issue by vizakenjack** [uBlock-LLC/uBlock#1662]
I'm using the latest OS X, ublock 0.9.5.2 and Safari 10.0.2.

If I turn uBlock on, it doesn't allow to play audio at vk.com. If I turn it off, audio works fine.

**Comment by VerlorenMind** [comment]
Same problem here. Maybe it's an issue with audio ads Vk is using?

**Comment by UserNaem** [comment]
Can't reproduce on uBlock Origin 1.11.0 and Firefox 53.0a2 with all three Russian filter lists enabled. Have you tried updating the extension and\or filter lists?

**Comment by Moris-Shalon** [comment]
Same issue. Music isn't playing before i reclick on it (so there is no skipping to the next one in playlist, before i manually click on play/pause). It's happening only in Safari, in Firefox and Chrome everything is fine with ublock.
macOS 10.12.3, Safari 10.0.3, uBlock 0.9.5.2.

**Comment by stepankuzmin** [comment]
Same here. uBlock 1.11.3.1, Safari 11.0, macOS 10.13

**Comment by Urgarth** [comment]
Hello, this issue we can see in Safari only. Same issue too.
