### ISSUE TITLE
Custom filter: how to exclude all assets which have a string?

### ISSUE THREAD

**Issue by mariusa** [uBlock-LLC/uBlock#1663]
Some assets are blocked, but some aren't.
In My Filters tab, I entered 
*events*

Apply Changes

and then tested on
https://nibiruapparel.com/collections/shirts

These files are still loaded:
https://cdn.shopify.com/s/assets/shop_events_listener-37861b7e433c159ab7ac8932b47d1b8813173005dff35ce87a5900b43e3492ed.js
https://connect.facebook.net/en_US/fbevents.js

How could I block everything with a string in full path?

Thanks

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock . Check out https://github.com/gorhill/uBlock/wiki/Static-filter-syntax .

Please close this issue.
