### ISSUE TITLE
Installing uBlock immediately crashes Iceweasel 45.7.0

### ISSUE THREAD

**Issue by mbuesch** [uBlock-LLC/uBlock#1665]
I'm running Iceweasel 45.7.0 (latest Debian Sid x86_64).
It immediately crashes after uBlock addon got installed. This will also prevent Iceweasel from starting up. To get it running again, uBlock has to be manually removed from the profile directory before starting Iceweasel.

Other addons work fine, though.
This is a recently introduced issue, because uBlock used to work fine before.

**Comment by mbuesch** [comment]
This also happens on a completely new clean profile without any other addons installed.

**Comment by mbuesch** [comment]
This has been fixed in iceweasel 45.7.0esr-3.

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock
