### ISSUE TITLE
ABP X Files: new URL

### ISSUE THREAD

**Issue by gioxx** [uBlock-LLC/uBlock#1666]
There is a new URL for ABP X Files. Can I ask You to modify this: "chrome://ublock/content/assets/thirdparties/dl.dropboxusercontent.com/u/1289327/abpxfiles/filtri.txt" with this? "chrome://ublock/content/assets/thirdparties/raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt"

Thanks.
Giovanni.

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock

Please close this issue.
