### ISSUE TITLE
ublock blocking chromecast button in firefox for android

### ISSUE THREAD

**Issue by wallor** [uBlock-LLC/uBlock#1667]
I need help with this issue.  Can't seem to find option which is blocking chromecast button in Firefox for android.

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock .

Please close this issue.

**Comment by dotnetCarpenter** [comment]
Chromecast for Firefox??!? Chromecast is Chrome only. Don't think this issue has anything to do with ublock

**Comment by anewuser** [comment]
@dotnetCarpenter This repository is owned by a scammer who makes a profit off donations given by misled uBlock Origin users (the real developer of uBlock Origin has never asked for or accepted any donations).  If you want to take a look at the actual project, go to the correct page: https://github.com/gorhill/uBlock
