### ISSUE TITLE
uBlock Origin 1.11.0 breaks Chromium 56.0.2924.87 on Mac

### ISSUE THREAD

**Issue by the-bobo** [uBlock-LLC/uBlock#1669]
When this extension is enabled, Chromium 56.0.2924.87 (latest stable Chromium release) crashes unpredictably on Mac. Playing a youtube video can pretty reliably get it to crash (e.g. https://www.youtube.com/watch?v=cmdFne7LnuA), but even a regular web page will sometimes cause it to crash as well (https://www.chromium.org/developers/version-numbers). 

What can I do to help you debug to determine if this really is uBlock? If I disable uBlock this behavior doesn't happen, which is why I think it's the extension.

EDIT: I'm also seeing this error come up in the console, which I think is related to the uBlock extension, perhaps the file contentscript.js?: `"Uncaught ReferenceError: vAPI is not defined" source: chrome-extension://[a long string that looks like a hash]/js/contentscript.js`

**Comment by anewuser** [comment]
I assume you've already found it by yourself, but this is the repository of uBlock Origin: https://github.com/gorhill/uBlock

**Comment by the-bobo** [comment]
Yes thanks
