### ISSUE TITLE
uBlock blocks Drupal Ajax calls

### ISSUE THREAD

**Issue by mllrmat** [uBlock-LLC/uBlock#1671]
I have a Drupal site that makes extensive use of AJAX calls. The AJAX links are normal href links that have the special class "use-ajax". Drupal AJAX then initiates an ajax call instead of a normal link. This mechanism is blocked by uBlock. This renders the page unuseable. 

Is there anything I can do to make uBlock accept those links?

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock , and use the logger to see what filter rule is blocking your requests and whitelist them: https://github.com/gorhill/uBlock/wiki/The-logger

Please close this issue.
