### ISSUE TITLE
WebAssembly in latest Chrome and Firefox. Are we ready?

### ISSUE THREAD

**Issue by byaka** [uBlock-LLC/uBlock#1672]
[Changelog of Chrome 57](https://blog.chromium.org/2017/02/chrome-57-beta-css-grid-layout-improved.html)
[Changelog of Firefox 52](https://www.mozilla.org/en-US/firefox/52.0/releasenotes/)

So new security hole enabled by default in major browsers. Are we ready for this?
Is UBlock can block this? For example via Dynamic-filtering's panel.
Or WebAssembly **always** adding to page via standard `<script type='text/javascript'>` tags only?

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock , but read this before posting on the repository: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

Please close this issue.

**Comment by byaka** [comment]
Sorry, i confused repo. Ofcourse i use  uBlock Origin and wanted to post there.
