### ISSUE TITLE
[Chrome] ublock started blocking opening of a new tab via ctrl + click on reddit

### ISSUE THREAD

**Issue by danilaml** [uBlock-LLC/uBlock#1673]
I think it started happening about 2 or 3 days ago. When I try to open some link on `reddit` in a new tab by clicking on it via holding `ctrl`, ublock blocks it (it immediately disappears). So far it looks like only `reddit` is affected.

Correction: the tab fails to open ONLY then the link I'm trying to open also leads to the reddit. Link leading to other websites (liek news) open correctly.

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock . That problem has been talked about here: https://github.com/gorhill/uBlock/issues/2452 .

Please close this issue.

**Comment by danilaml** [comment]
@anewuser Thanks. Sorry, just the first repo I've found from google xD. It still has some activity, despite being obsolete.

**Comment by anewuser** [comment]
It only has activity from people who end up here or install it accidently. The owner of this repository just keeps it open because he lures people to give him money.

**Comment by danilaml** [comment]
Wow, shady.
