### ISSUE TITLE
Block for geoIP.io

### ISSUE THREAD

**Issue by BenjaminHoegh** [uBlock-LLC/uBlock#1674]
First uBlock is amazing but It have some a ignoring block of geoIP.io so front-end site where they use phone validation after what country you are in, uBlock fuck it up so they can't validate the phone number

**Comment by anewuser** [comment]
This was the original repository of uBlock, but it has been abandoned. The current and actively developed extension is named **uBlock Origin** .

Please close this issue and use either of these links:

Project homepage/download links: https://github.com/gorhill/uBlock/
Documentation: https://github.com/gorhill/uBlock/wiki
Bugs: https://github.com/gorhill/uBlock/issues
Support forum: https://discourse.mozilla-community.org/t/support-ublock-origin/6746

**Comment by anewuser** [comment]
This was the original repository of uBlock, but it has been abandoned. The current and actively developed extension is named **uBlock Origin** .

Please close this issue and use either of these links:

Project homepage/download links: https://github.com/gorhill/uBlock/
Documentation: https://github.com/gorhill/uBlock/wiki
Bugs: https://github.com/gorhill/uBlock/issues
Support forum: https://discourse.mozilla-community.org/t/support-ublock-origin/6746
