### ISSUE TITLE
UBlock not Shown in Nightly  "55.0a1 (2017-04-02) (64-bit)"

### ISSUE THREAD

**Issue by SkateScout** [uBlock-LLC/uBlock#1675]
With the version from 2017-03-31 the plugin icon was shown in niglty now with the new version it is no longer visible. Also not available under customize.

**Comment by Asfhy** [comment]
I can confirm the bug. Exactly the same. Before updating all ok; after updating the icon has gone but the add-on appears on the list of add-ons as installed.

**Comment by sacnoth** [comment]
I'm on Firefox Nightly 55.0a1 (2017-04-04) (64-bit) and adblocking stopped working completely for me.
Can reproduce this by updating Firefox Nighly to the latest version. Previous versions work fine.

**Comment by amfg** [comment]
Same here, youtube is now basically unusable. Nightly version 2017-04-06 (noticed uBlock missing a few days back).

**Comment by anewuser** [comment]
This was the original repository of uBlock, but it has been abandoned. The current and actively developed extension is named **uBlock Origin** .

Please close this issue and use either of these links:

Project homepage/download links: https://github.com/gorhill/uBlock/
Documentation: https://github.com/gorhill/uBlock/wiki
Bugs: https://github.com/gorhill/uBlock/issues
Support forum: https://discourse.mozilla-community.org/t/support-ublock-origin/6746
