### ISSUE TITLE
Can't upload images/ documents to Facebook [EasyList filter issue]

### ISSUE THREAD

**Issue by VirenMohindra** [uBlock-LLC/uBlock#1676]
## Reproducing the problem:
1. Try uploading any images/ documents to [Facebook](https://www.facebook.com/) through Google Chrome (Version 57.0.2987.133 (64-bit) MacBook Pro).
2. Error occurs (see attached screenshots)

## 3rd party filters
**Problem is in the EasyList filter list.**

### For images:
"Please try again. Make sure you're uploading a valid photo."
### For files:
"There was a problem uploading the file."

## Screenshots (the error I recieved):

![screen shot 2017-04-12 at 6 31 53 am](https://cloud.githubusercontent.com/assets/10460518/24953651/12c1e06c-1f4a-11e7-8783-422eb33a4e69.jpg)

![screen shot 2017-04-12 at 6 36 07 am](https://cloud.githubusercontent.com/assets/10460518/24953731/5ddc7350-1f4a-11e7-8f8e-1c58ea64001f.jpg)

## I went through all my extensions and uBlock was the only one which was causing the blockage.

This issue affects https://www.facebook.com/ and all similar domains but **not** https://www.messenger.com/

## Technical:
**The version of uBlock you're having the issue with; you can find this in uBlock's popup UI**
Example: uBlock 1.12.0
**The browser you're using and its version**
Examples: Chrome (Version 57.0.2987.133 (64-bit) MacBook Pro).
**The OS you're using and its version**
Examples: OS X 10.12.4

**Comment by anewuser** [comment]
This was the original repository of uBlock, but it has been abandoned. The current and actively developed extension is named **uBlock Origin** .

Please close this issue and use either of these links:

Project homepage/download links: https://github.com/gorhill/uBlock/
Documentation: https://github.com/gorhill/uBlock/wiki
Bugs: https://github.com/gorhill/uBlock/issues
Support forum: https://discourse.mozilla-community.org/t/support-ublock-origin/6746
