### ISSUE TITLE
Filter with regex

### ISSUE THREAD

**Issue by jaimejim** [uBlock-LLC/uBlock#1677]
**Quora** uses a particular way to avoid ublock and other ad blockers.  
They sneakily insert frame uses a hash every time it is rendered as below:

`###__w2_q02z7rv_wrapper`

![screen shot 2017-04-13 at 18 23 01](https://cloud.githubusercontent.com/assets/1798358/25011507/449c2368-2076-11e7-9263-ae814f02c295.png)

I could write a script with Greasemonkey, but can we add regex to the Block Element feature in order to block those too? Something like below:

`###__w2_`(.*)`_wrapper`

PS: If this feature already exist, I apologise I din't find it on the issue tracker.

Please note that, for those interested, you can filter Quora's popups and ads by adding the following filters:

```
www.quora.com##[id$="modal_signup_wrapper"]
www.quora.com##[id$="wrapper"]
www.quora.com##[id$="contents"]
```

**Comment by anewuser** [comment]
This was the original repository of uBlock, but it has been abandoned. The current and actively developed extension is named **uBlock Origin** .

Please close this issue and use either of these links:

Project homepage/download links: https://github.com/gorhill/uBlock/
Documentation: https://github.com/gorhill/uBlock/wiki
Bugs: https://github.com/gorhill/uBlock/issues
Support forum: https://discourse.mozilla-community.org/t/support-ublock-origin/6746
