### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by BenderBRod** [uBlock-LLC/uBlock#1678]
Now at the start of videos you have an unskippable ad from 30 s to 3 m

**Comment by anewuser** [comment]
This was the original repository of uBlock, but it has been abandoned. The current and actively developed extension is named **uBlock Origin** .

Please close this issue and use either of these links:

Project homepage/download links: https://github.com/gorhill/uBlock/
Documentation: https://github.com/gorhill/uBlock/wiki
Bugs: https://github.com/gorhill/uBlock/issues
Support forum: https://discourse.mozilla-community.org/t/support-ublock-origin/6746

**Comment by BenderBRod** [comment]
Thank you :)

**Comment by anewuser** [comment]
@BenderBRod Please use the "close issue" button. Hopefully, when people see few recent open issues, they'll realize they're in the wrong place.

**Comment by AsyFrost** [comment]
I've had it as well(win 7), unconfirmed but my friends are using win 8/10 and it never occured to them. I enabled anti adblock killer | Reek with tampermonkey, seems to have resolved it. 

Yes I know this is oudated, but might help for people checking this out.

**Comment by anewuser** [comment]
@AsyFrost  This page isn't just "oudated". It's about a piece of software that you **must not** use anymore. The real thing is at

https://github.com/gorhill/uBlock

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

https://addons.mozilla.org/addon/ublock-origin/
