### ISSUE TITLE
URL Blocking still (?) doesnt work

### ISSUE THREAD

**Issue by pbl987** [uBlock-LLC/uBlock#1679]
Hi!

I regularly get this ad url, opened by a mod:
https://www.youtube.com/oldskooltv_wot/?sub_confirmation=1

|youtube.com/oldskooltv_wot$important,document

=> doesnt work. What can I do?

By the way: is it possible to redirect it to another url, like in hosts file?

**Comment by anewuser** [comment]
This was the original repository of uBlock, but it has been abandoned. The current and actively developed extension is named **uBlock Origin** .

Please close this issue and use either of these links:

Project homepage/download links: https://github.com/gorhill/uBlock/
Documentation: https://github.com/gorhill/uBlock/wiki
Bugs: https://github.com/gorhill/uBlock/issues
Support forum: https://discourse.mozilla-community.org/t/support-ublock-origin/6746

**Comment by pbl987** [comment]
Problem solved. Thank you for your advice.
