### ISSUE TITLE
Better icons (SVG)

### ISSUE THREAD

**Issue by Baegus** [uBlock-LLC/uBlock#168]
I remade the µBlock icon in Inkscape and made a vector (SVG) version of it. I tried exporting it as PNG in various resolutions (128, 64...) and it seems to look better and sharper than the current one.

Here's the SVG: https://docs.google.com/file/d/0B9wXd0Aj8dglUXMxTEdCM1JwU2c/

I can provide the exported PNGs in any resolution, I'm not sure how to pull request images correctly though.

**Comment by gorhill** [comment]
Thanks. I saved it [in the img folder](https://github.com/gorhill/uBlock/blob/master/img/ublock.svg) so that it will now be the official version to work from.

**Comment by gorhill** [comment]
> I'm not sure how to pull request images correctly though.

Like any other file if you work from the console with a clone of your fork. From Github website, I don't know.
