### ISSUE TITLE
popup dialog size issue

### ISSUE THREAD

**Issue by EinsteinXXL** [uBlock-LLC/uBlock#1682]
The size and elements of the pop-up dialog are often not displayed correctly.  It occurs sporadically and I couldn't reproduce it.

**ublock Orign:** v1.12.6
**Browser:** Firefox v53.0.2 (x64)
**OS:** Windows 7 (x64)
**addons:** noscript, self-destructing cookies, profile switcher, keefox, https everywhere, enable-disable weak ssl ciphers, adblocker for youtube, 1-click youtube video downloader, better privacy, enhancer for youtube, menu wizard, no resource Uri leak, random agent swicher, privacy settings

![popupdialog_issue](https://cloud.githubusercontent.com/assets/20692649/26279517/a68698bc-3db6-11e7-9d25-61375ea0fc03.png)

**Comment by bershan2** [comment]
@EinsteinXXL There are a few weird things about your report:
- This is uBlock repo, not [uBlock Origin repo](https://github.com/gorhill/uBlock). They are [different](https://github.com/gorhill/uBlock/blob/master/README.md#beware-ublock-origin-is-completely-unrelated-to-the-web-site-ublockorg) things. (You have uBlock Origin icon on the screenshot.) Not sure how you got to this repo.
- You report having version 1.12.6, but the newest one is 1.12.4 at the time I'm writing this. The latest [public release in Firefox store](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) is 1.12.4, similarly in [uBlock Origin](https://github.com/gorhill/uBlock/releases/latest), there are only few [pre-releases](https://github.com/gorhill/uBlock/releases).

Unfortunately, I can't help you as I use Chrome and have never experienced similar issues before. I can only recommend to (1) figure out what extension you have, (1.5) switching to official uBlock Origin if you have something else or (2) reporting to official repo if you are sure issue is with uBlock Origin.
