### ISSUE TITLE
uBlock has stopped working

### ISSUE THREAD

**Issue by JohnathanStein** [uBlock-LLC/uBlock#1683]
uBlock has stopped working.  It does not block ads, nor display counts.  Websites show ads whether it is installed or removed.

Purging caches does nothing.  The UPDATE NOW button never finishes updating.

Please advise.

--Johnathan

**Comment by UnlawfulCitizen** [comment]
Frankly I would go use UBlock Origin as this project is just a scam at this point.

**Comment by JohnathanStein** [comment]
I got it working; had to purge, uninstall, re-install and whatnot.  No idea why.  Using on WinXP w/Firefox.

I switched to uBlock because AdBlock was hogging resources and slowed things down too much.

Works fine on my Win10 machines with Chrome & Edge.

**Comment by UnlawfulCitizen** [comment]
Throwing it out there Ublock Origin is the guy who wrote this one.

**Comment by JohnathanStein** [comment]
Uh...why is that a problem?

**Comment by UnlawfulCitizen** [comment]
No, just that the Ublock Origin thread seems to be updated where this one has not been updated in over 2 years. 

(Latest commit a70a500  on Aug 23, 2015) 

But if it still works good, if it aint broke don't fix it.

**Comment by JohnathanStein** [comment]
Oh, poop!  So basically, I'm in the wrong area/thread...<sigh>

Thanks...
