### ISSUE TITLE
Random new tab redirect from Google Scholar Button

### ISSUE THREAD

**Issue by WillemKvanderMerwe** [uBlock-LLC/uBlock#1684]
2nd EDIT: Ok I see this is the repo site, none the less this is pretty weird:

For time's sake I will paste my google report here:

Greetings Google overlords,

I would like to report an occasional suspicious occurrence.

Once in a while when i use the Google Scholar Button to search for something, instead of a new tab opening with the search results, a blank tab opens with a popup button that invites me to install something to do with"yogachallengepics.us".

This is very strange as I have no strange extensions and periodically run both HitmanPro and Malwarebytes, Chrome is also up to date. 

I have deleted cookies and cache and there is nothing strange in either my Program files or registry; ditto the PC processes list.

My apologies for the lack of screenshot, I will try to catch it next time.

A quick google search for malware/adware with similar titles yielded nothing.

Benevolent best wishes,
WK vd Merwe 

--end of report--
Naturally I am running uBlock Origin and literally never see any ads, making the above very strange.

Any advice would be appreciated, note that most obvious steps have already been taken, except for getting a screenie or URL of that site.

EDIT: To say it in so many words, this project is AWESOME. This issue is not with uBlock but a question to a learned adblocking community.

**Comment by jyan-zarate** [comment]
This is uBlock (whose development has ceased), uBlock Origin's repo can be found [over here](https://github.com/gorhill/uBlock). If you do open an issue in the other repo, please close _this_ issue.
