### ISSUE TITLE
uBlock for Safari causes Angular app not loading

### ISSUE THREAD

**Issue by SteveLTN** [uBlock-LLC/uBlock#1685]
We have an app built in Angular.js. 

When using uBlock for Safari, and subscribe to "EasyPrivacy", or when adding a custom filter 

```||segment.io^$third-party```

, the Angular app wouldn't load.

We made sure the Angular app itself would work without Segment. By: 
1. Using the same lists in uBlock on Chrome. The app still works
2. Using another ad blocker for Safari, subscribing to the same list. The app still works
3. Blocking the domain `segment.io` in our DNS. The app still works

It turned out, our Angular app would work even if `segment.io` is not accessible, except the case of being blocked by uBlock for Safari.

A test URL is https://sqore.com/organization/sqore. When Angular doesn't load, you see placeholders wrapped in `{{ }}`. Tested on *Safari 10.1* on *macOS 10.12.5*, with *uBlock for Safari 0.9.5.2*.

**Comment by anewuser** [comment]
This was the original repository of uBlock, but it has been abandoned. The current and actively developed extension is named **uBlock Origin** .

Please close this issue and use this instead: https://github.com/el1t/uBlock-Safari#ublock-originfor-safari
