### ISSUE TITLE
Consider selecting "hpHosts’s Ad and tracking servers" out of the box

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#17]
Author of this list is [working to fix the over-zealousness](https://github.com/gorhill/httpswitchboard/issues/348#issuecomment-47169534).

That would be an extra over 19,000 new filters out of the box. I am currently using it, so far no problem, but I browse a limited amount of sites. If other users can try it and see if there are any issues -- i.e. we don't want the extension to break sites with out-of-the-box settings.

**Comment by gorhill** [comment]
The list breaks http://news.yahoo.com/, so that would need to be fixed.

**Comment by gorhill** [comment]
It blocks `use.typekit.net`, which is often used by sites to download web fonts. Need to create an exception filter for this one.

**Comment by gorhill** [comment]
This list blocks `c.brightcove.com`, and this breaks videos on [meteomedia.com](http://www.meteomedia.com/videos/galerie) (and probably other sites).

**Comment by ledti** [comment]
Noticed today that it blocks `s.imwx.com`, which breaks images at weather.com and wunderground.com.

Example: http://www.wunderground.com/news/china-cave-weather-20131002 (was a front-page post at reddit)

**Comment by gorhill** [comment]
Thanks, fixed.

**Comment by ledti** [comment]
It blocks `extras.mnginteractive.com` which is used for css and images at [mercurynews.com](http://www.mercurynews.com/science/ci_26294769/yosemite-fire-feds-charge-hunter-starting-massive-2013).

`@@||extras.mnginteractive.com^` fixed the layout for me.

Edit: Noticed that after scrolling through the article there is a popup in the bottom right corner which although it has a large X to close the popup, clicking that doesn't do anything.

There's also a small photo gallery which has multiple images, but clicking the number hyperlinks do not work as intended. Both of these issues don't seem to be related to `extras.mnginteractive.com`. It seems EasyPrivacy may be part of the cause but I don't know for sure.

There may be more issues.

**Comment by ghost** [comment]
If this filter gets used in a whitelist, there is a way to restrict it
to just css and images. As far as I understand that filter now allows
JS and anything from that domain.

**Comment by gorhill** [comment]
Currently this is what I've added: `@@||extras.mnginteractive.com^$domain=mercurynews.com,denverpost.com`. I suspect there might be more news websites out there which need this one, so I might end up having to add `@@||extras.mnginteractive.com^`.

Ultimately, as said [here](https://github.com/gorhill/uBlock/wiki/%C2%B5Block-and-others:-Blocking-ads,-trackers,-malwares#notes), to block with 100% certainty is to use HTTPSB.

**Comment by gorhill** [comment]
Blocking `adm.fwmrm.net/crossdomain.xml` (`adm.fwmrm.net` is in hpHosts, MVPS, Dan Pollock's) causes the video at the bottom of http://www.huffingtonpost.ca/2014/07/15/nathen-steffel-dead-daughter-photoshop_n_5589744.html to start to play on its own.

When allowing `adm.fwmrm.net/crossdomain.xml`, the video does not auto-play.

Creating an exception such as `@@||adm.fwmrm.net/crossdomain.xml^` is not a good idea since there is already a filter `||adm.fwmrm.net/crossdomain.xml$domain=cc.com|mtv.com` in _EasyList_. Will think more about this.

**Comment by gorhill** [comment]
Too many false positives, I give up. Use at your own risk, and if it breaks stuff, report to the list maintainer(s) (which is not me).
