### ISSUE TITLE
Add option to disable ublock just for a specific page of a website.

### ISSUE THREAD

**Issue by kapraran** [uBlock-LLC/uBlock#170]
Read the title :wink:

**Comment by gorhill** [comment]
`Ctrl`-click the power button. I will let you close the issue once you confirm it works.

**Comment by kapraran** [comment]
Yes it works!! Thanks

**Comment by gorhill** [comment]
Just for the record for the benefit of all users, manually adding an asterisk `*` at the end of a URL-based whitelist directive will disable uBlock for all web pages which match the start of the URL.
