### ISSUE TITLE
Google ads randomly appers on top of the search result

### ISSUE THREAD

**Issue by netkgk** [uBlock-LLC/uBlock#1708]
I'm trying to block element `##.ads-ad` which contains google ads but despite I already have bunch of rules kind of:

```
! 7/18/2017, 4:14:15 AM https://www.google.com/search?q=solrcloud+admin+authentication+authorization+haproxy
www.google.com##.ads-ad
```

the element keep appearing again and again once the page is reloaded.

**Comment by SamuelWAnderson45** [comment]
@netkgk You're at the wrong repository most likely. This version is unmaintained, the maintained version is at https://github.com/gorhill/uBlock/

Best of luck!

Edit: Actually, commits just started up a few days ago. Well, that's promising! Still, be sure you are at the right place (here versus the Origin fork)! Perhaps we'll see uBlock come back to life.
