### ISSUE TITLE
Compatability with Firefox 57+

### ISSUE THREAD

**Issue by lindhe** [uBlock-LLC/uBlock#1712]
This Add-on is currently marked as [Legacy](https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing) by Firefox 55 and will stop working as soon as Firefox 57 is out. Are there any plans on porting it to become a WebExtension?

**Comment by johncf** [comment]
You are in the "wrong" repository. The repo maintained by the original author contains answers you are looking for: https://github.com/gorhill/uBlock/issues/2728 and https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions

**Comment by lindhe** [comment]
I see. Thank you!

**Comment by johncf** [comment]
I think you should leave this issue open, since this is an independent project (see [Wikipedia](https://en.wikipedia.org/wiki/UBlock_Origin)) now and "Compatibility with FF 57+" isn't solved for _this_ project.

**Comment by lindhe** [comment]
Sure. I'll just unsubscribe then.

**Comment by RichardJECooke** [comment]
I think the correct issue is here, for future readers: https://github.com/gorhill/uBlock/issues/622

But even though it's closed uBlock just died on Firefox this week
