### ISSUE TITLE
Ublock origin causing problem with Kayako helpdesk agent panel in Firefox 

### ISSUE THREAD

**Issue by swarnava** [uBlock-LLC/uBlock#1714]
**Screenshot**:-

![Screenshot](https://i.imgur.com/EpEdBEO.png "Screenshot")

DM me for credentials for You can signup for a free trial from https://www.kayako.com/free-trial

**Comment by LifeIsStrange** [comment]
https://github.com/gorhill/uBlock
This repo is not ublock origin
