### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by swooshswoosh** [uBlock-LLC/uBlock#1715]
Since a while I have a problem with youtube.
When I go to my subscriptions video list, only about half of the videos display the preview picture.
When I turn unlock off, all video in the subscription list display their preview picture.

Any other people that have the same problem?

Will

**Comment by swooshswoosh** [comment]
Also the menu column isn't responsive when ublock is active...

**Comment by LifeIsStrange** [comment]
Ublock is dead, go use ublock origin instead

**Comment by shobhit-gupta** [comment]
Yes, youtube with ublock turned on is becoming almost unusable. For example, I am unable to click anything from the Filter Menu shown on search results page, can't even search more than once and have to reload the page to perform a new search etc.

**Comment by fzaffa** [comment]
Can confirm, this extension completely renders the youtube website unusable on `Safari 10.1.2 (12603.3.8)`.

The first video works fine, but from there whenever I click on the channel, or on one of the videos in the sidebar nothing happens and in the console I get an `InvalidAccessError`.

Disabling Ublock works 100% of the time as a solution.

After 15 days, what is the developers' response?

**Comment by swooshswoosh** [comment]
You need to install ublock origin, it works excellent.

Greets

**Comment by Evilkevin22** [comment]
I'm on safari and sadly uBlock makes youtube unusable on that platform to.

**Comment by gurkee9** [comment]
This repo is a fake. A scrammer.
https://github.com/el1t/uBlock-Safari/issues/69
