### ISSUE TITLE
provide an easy way to disable uBlock for a specific page on a website

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#172]
in reference to #170,
I don't think it should be that users open issues asking such things - It should be intuitive out of the box.
Maybe mentioning this in the popup text or somewhere on the whitelist page, or even add a button on the popup to enable the whitelist rule should help avoid such things in the future..

**Comment by gorhill** [comment]
I pondered an idea earlier this week, but although it looks nice to me, I second guess whether less technical users (let's assume a majority of the users) would make sense of it.

Simply said, that would be a target-like button, with three rings:
- Clicking the outer ring would causes the whole button (all rings) to become grayed = disable uBlock for the site (like now)
- Clicking the middle ring would cause it and the ring inside it to become grayed = disable uBlock for page starting with the current URL (useful to whitelist a "channel" on a site)
- Clicking the center ring would cause it to become grayed = disable uBlock for this page only

A tooltip when hovering on a specific ring would inform as to what it does.

Just an idea.

**Comment by Baegus** [comment]
Why not just display the URL with different parts of it highlightable? Maybe with some tooltips under it for more information.

**Comment by gorhill** [comment]
URL is too technical for non-technical users.

**Comment by gorhill** [comment]
Ok I tried the target idea, and it doesn't work. I will go with a newly designed CSS-based tooltip, this works better.

**Comment by gorhill** [comment]
For reference for Crowdin translators to show how `\n\n` looks:

![tmp](https://cloud.githubusercontent.com/assets/585534/4023486/46464706-2b92-11e4-85f6-7b299c8e60f2.png)

**Comment by RapsIn4** [comment]
This does not work for Mac since Ctrl+Click behaves the same as Right Click.

**Comment by chrisaljoudi** [comment]
@Rapsln4 ⌘ click should work.

**Comment by RapsIn4** [comment]
@chrisaljoudi  Thanks! I think you guys should update the hover text though!
