### ISSUE TITLE
How do i whitelist a request blocked by uBlock?

### ISSUE THREAD

**Issue by slrslr** [uBlock-LLC/uBlock#1724]
I am sorry if this was answered already.
I searched and can not find. I read https://github.com/chrisaljoudi/uBlock/wiki/How-to-whitelist-a-web-site
**[MY AIM]** But i do not want to stop ublock 1.14.16 & FireFox 57 on a website, i want to just exclude one of the blocked element. In my case, when i click "requests blocked" in ublock firefox widget (the menu that appears when i click ublock icon in firefox), i see this one was blocked probably inproperly:

x.dpstatic.com -

**[QUESTION]** So what is the fastest way to exclude this URL from blocking? [FEATURE REQUEST] I think it would be very handy if the firefox ublock widget contains a button in "requests blocked" section to quick exclude certain blocked element/url.

**[What i tried]**
add: x.dpstatic.com
into ublock settings / whitelist
add: !x.dpstatic.com or ! x.dpstatic.com or !*x.dpstatic.com
into: ublock settings / My filters

still that url appears as blocked in ublock widget / "requests blocked" / appears there with red color and a "-" sign.

**Comment by nimasaj** [comment]
add @@||domain.com
or @@||domain.com^$document
also have a look at the following link:
https://adblockplus.org/filters

**Comment by slrslr** [comment]
Thank You, it worked when i added:
@@||x.dpstatic.com
or
@@||dpstatic.com
into uBlock origin / My filters
and applied changes.
