### ISSUE TITLE
[Question] How to write a regex filter for cosmetic stuff

### ISSUE THREAD

**Issue by rraallvv** [uBlock-LLC/uBlock#1725]
How can I write a regex filter to remove all the signatures in a forum which happen to have a different **id** each like the one below?
`###post_id_1084306 > .post_wrap > .post_body > .signature`
I was guessing something like this would word, but it doesn't.
`###post_id_/[0-9]+/ > .post_wrap > .post_body > .signature`

**Comment by nimasaj** [comment]
maybe something like this?
##*\[class^="post_id" id^="bla bla"]
look at  '^'

You can also have a look at the following links, they might be helpful for you:
https://adblockplus.org/filter-cheatsheet
https://adblockplus.org/forum/viewtopic.php?t=7702#p48247

**Comment by gurkee9** [comment]
This repo is a fake. A scrammer.
https://github.com/el1t/uBlock-Safari/issues/69
