### ISSUE TITLE
Can't dowload from main page

### ISSUE THREAD

**Issue by itamma** [uBlock-LLC/uBlock#1730]
Hi, 

Sorry for my bad english. I have a problem with the main website (https://www.ublock.org). When I click to download and Safari, there is a problem with cloud.dolosent.com (timeout). The problem is the same with Chrome and Safari. 

Have a good day, 

Florian

**Comment by gurkee9** [comment]
This repo is a fake. A scrammer.
Why? Here the details. this is the original.
https://github.com/el1t/uBlock-Safari/issues/69
