### ISSUE TITLE
block cryptocurrency mining scripts

### ISSUE THREAD

**Issue by z11h** [uBlock-LLC/uBlock#1735]
also see:
http://www.silicon.co.uk/security/cryptocurrency-mining-script-maliciously-placed-sites-223041?inf_by=5a0d1762681db81c218b49f8

**Comment by gurkee9** [comment]
This repo is a fake. A scrammer.
Why? Here the details. this is the original.
https://github.com/el1t/uBlock-Safari/issues/69
