### ISSUE TITLE
Not blocking Email ad in Checker Plus

### ISSUE THREAD

**Issue by jtechpro** [uBlock-LLC/uBlock#1739]
# Ad preview
![Checker plus window](https://i.imgur.com/b47s27T.png "Checker Plus window")

# Steps to reproduce the problem
1. Install the [Checker Plus extension for Chrome](https://chrome.google.com/webstore/detail/checker-plus-for-gmail/oeopbcgkkoapgobdbedcemjljbihmemj?hl=en)
2. Add your email and login to it.
3. On the Checker Plus button popup **Switch to Inbox** from the Menu.

You will see the email ad.

# Filter subscriptions
![](http://i.imgur.com/iVKPfce.png "")

# Screenshot of the Popup window of Checker Plus with uBlock Origin Popup
![As we can see there is no element picker there!](http://i.imgur.com/yli5PyU.png "")
As we can see there is no element picker there!

# The Filtering Log for the Checker Plus extension page.
### We can get the page in a new tab by clicking on **Pop out** in the Checker Plus menu.
![](http://i.imgur.com/EtemxkW.png "")

What did I try?
1. Tried removing **chrome-scheme** in My Filters but it did not work.
2. Tried opening the page [https://mail.google.com/mail/mu/mp/688/?mui=checkerPlusForGmail&hl=en-GB#tl/priority/%5Esmartlabel_promo](url) which is a **frame** that we got first from the above **Filtering log screenshot** and then added the rule `mail.google.com##.vr` using the **Element picker** on that page and it worked on that page only i.e. for that url only but not in the Extension.

# System Configuration
**Browser**: Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)
**OS**: Linux Mint 18.2 Xfce 64 bit
**List of other extensions in chrome**: Checker Plus for Gmail, Pixel Block, Video Resumer
**uBlock Origin:** 1.14.20

# Possible solution:
So I modified it to `||mail.google.com##.vr` but I think it must be included by default in the list. I also doubt that the rule will be more general and **may** block useful elements.

**Comment by krystian3w** [comment]
Bad github project bro - you are using uBlock **Origin**.

https://github.com/gorhill/uBlock / https://github.com/uBlockOrigin/uAssets
