### ISSUE TITLE
Removed images show broken image images links

### ISSUE THREAD

**Issue by njorogle** [uBlock-LLC/uBlock#174]
Screenshot from a kickstarter email in gmail.

uBlock: ![ublock](https://cloud.githubusercontent.com/assets/2047700/4021733/0ce70418-2b02-11e4-88ef-b3fb8ac15553.png)

ABP: ![abp](https://cloud.githubusercontent.com/assets/2047700/4021732/07d9316c-2b02-11e4-968e-98acae72a731.png)

Nothing: ![nothing](https://cloud.githubusercontent.com/assets/2047700/4021731/037e12a4-2b02-11e4-89ea-794a77c01f66.png)

**Comment by gorhill** [comment]
Not sure how, best is if I could reproduce on my computer here so that I can investigate. It is rather unexpected, there is code in there to  collapse blocked elements (if the setting is enabled -- which it is by default).

What filter lists do you have enabled in uBlock?
What filter lists do you have enabled in ABP?

**Comment by njorogle** [comment]
I use the Fanboy's Social Blocking List on both.  I can email you the broken HML if you like - I don't know how else to reproduce.

Edit: looks like ABP is reloading the page to fix the blocked element in a second pass, but it's briefly broken for ABP too.

**Comment by gorhill** [comment]
Can you forward me the problematic email (if there is no privacy issue) in my throwaway Gmail account? Here: `uKOeoIfHQDp8@gmail.com`.

**Comment by njorogle** [comment]
Done

**Comment by gorhill** [comment]
Thanks, I can reproduce it. Now onto finding out why this happens.

**Comment by gorhill** [comment]
Alright, found problem, fix a bit more complicated than thought, related to fragment part of the URL of net requests. Need to think of the best long term solution.

**Comment by njorogle** [comment]
Many thanks.  Nice plugin.

**Comment by gorhill** [comment]
Fix available in 0.5.1.0 beta 2 for now: https://github.com/gorhill/uBlock/releases/tag/0.5.1.0-beta.2.

Will publish into stores when I am satisfied all work as expected.

**Comment by gorhill** [comment]
So about the fix and for the record: after a couple of brain farts and a good night sleep, problem is simply that I was removing the URL fragment from the URL of the `src` property before checking if it was a blocked request. I can't remember why I thought it was a good idea.

**Comment by gorhill** [comment]
Oops, I meant to type "#374", not "#174".
