### ISSUE TITLE
All images on my client's domain are blocked

### ISSUE THREAD

**Issue by doosom** [uBlock-LLC/uBlock#1743]
HI all.

I am using uBlock for quite a time now and can only congratulate for this piece of software it's great! 

Now to my problem. My clients website seems to get blocked by your addon because of the keyword "publicidad" in the domain name (regalos-publicidad.es). Could that be possible? This website doesn't serve any ads to any other domains but is dedicated to marketing gifts thus using the keyword within it's domain name. Is there anything that can be done to unblock this domain? 

Thanks for your help in advance.

Patrick

**Comment by krystian3w** [comment]
**https://forums.lanik.us/ try report to unlock your website**, maybe remove `-publicidad.` or add exception for this website @doosom:

```
@@||www.regalos-publicidad.es^$domain=www.regalos-publicidad.es
```
