### ISSUE TITLE
[Removed; off-topic]

### ISSUE THREAD

**Issue by vassudanagunta** [uBlock-LLC/uBlock#1744]
[Removed; off-topic]

**Comment by chrisaljoudi** [comment]
I saw your kind email.

Please don’t open non-code issues.

**Comment by vassudanagunta** [comment]
How can you be such a low life? Don't you have any self respect?

**Comment by CamilleScholtz** [comment]
[Removed; off-topic]

**Comment by vassudanagunta** [comment]
[Removed; off-topic]

**Comment by chrisaljoudi** [comment]
Do whatever you want, but stop spamming the repo.
