### ISSUE TITLE
Safari uBlock default settings on cars.com

### ISSUE THREAD

**Issue by carsGillen** [uBlock-LLC/uBlock#1745]
Hello, we've used the default settings across all three browsers Chrome, Firefox and Safari. The Safari version is the only one which blocks users from interacting with search widget on our homepage as well as the top navigation. https://www.cars.com

I would be glad to provide any further information in order to squash this bug for Safari users. 
Please contact me at jgillen@cars.com.

Thanks

**Comment by onodera-punpun** [comment]
Hi @carsGillen, Chris Aljoudi is a scammer and this repo is fake. This is the actual ublock: https://github.com/gorhill/uBlock and https://github.com/el1t/uBlock-Safari/releases is an unofficial fork for safari

**Comment by gurkee9** [comment]
yes the user @chrisaljoudi is a scrammer. I never buy your app in App Store e.g Purify
Purify is bad, no update, very old, no,practical features

**Comment by gurkee9** [comment]
@carsGillen 
This repo is a fake. A scrammer.
https://github.com/el1t/uBlock-Safari/issues/69
