### ISSUE TITLE
uBlock prevents using <a download>

### ISSUE THREAD

**Issue by AshleyScirra** [uBlock-LLC/uBlock#1754]
The `<a download>` tag is intended to start a download rather than open a new window. UBlock appears to block these downloads. Is this intentional? These downloads are necessary for some situations, such as our PWA Construct 3 (editor.construct.net) to allow the user to download their work, but UBlock is blocking this and is confusing users.

This appears to have changed recently and may be related to [crbug.com/829427](https://bugs.chromium.org/p/chromium/issues/detail?id=829427)

**Comment by uBlockAdmin** [comment]
Report here https://github.com/easylist/EasyListHebrew/issues
