### ISSUE TITLE
can uBlock provide builtin popup blocking

### ISSUE THREAD

**Issue by Wyvern** [uBlock-LLC/uBlock#1755]
Nowadays many websites have lots of annoying popup ads/tabs to distract users, hope uBlock could support popup blocking ASAP, thanks

**Comment by krystian3w** [comment]
uBlock Origin?

- https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups

- https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt - block pop-up, social buttons, rss buttons 

- https://blog.adguard.com/en/annoyances-filter/, https://kb.adguard.com/en/general/adguard-ad-filters#annoyances
