### ISSUE TITLE
Can't block ember IDs

### ISSUE THREAD

**Issue by anavarre** [uBlock-LLC/uBlock#1758]
Upon trying to hide blocks like `###ember<ID>` I realized this never works. You can try `###ember1750-trigger` at https://www.linkedin.com/feed/ which corresponds to the **Sort by** block for the feed.

I did experience the same issue on many different sites so I wonder if it's simply the Ember JS framework block elements not being able to be filtered out by uBlock?

**Comment by tombakerjr** [comment]
Those IDs are generated on the fly by Ember and aren't likely to be the same between sessions. You may want to try a class-based selector instead.

**Comment by krystian3w** [comment]
`##[id^="ember"][id$="-trigger"]`?

**Comment by anavarre** [comment]
I've been trying to experiment with class-based selectors but wasn't entirely successful. `##[id^="ember"]` is interesting (didn't actually know regex was supported!) though it can be a nuclear option that will block (potentially) all elements on a page. Try on Linkedin for instance.

https://discourse.mozilla.org/t/support-ublock-origin/6746/57 says you can't specify N number of characters either, which is annoying if you'd like to block, say, only `##ember3274`
