### ISSUE TITLE
How to whitelist private networks

### ISSUE THREAD

**Issue by alexanderharm** [uBlock-LLC/uBlock#1759]
Is there a way to easily whitelist the private network ranges?

```
10.0.0.0 – 10.255.255.255
172.16.0.0 – 172.31.255.255
192.168.0.0 – 192.168.255.255
```

**Comment by krystian3w** [comment]
uBlock **Origin** and **regex**?

https://github.com/gorhill/uBlock/commit/a92decd641b539d21f49fcb9c4649e0fe80f4a38

https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site#regular-expression-1917

---

> For **`192.168.0.*`**, use **`/^https?://192\.168\.0\.\d+//`** (no need to escape forward slashes).
> 
> For **`10.0.*`**, use **`/^https?://10\.0\.\d+\.\d+//`.**

**Comment by alexanderharm** [comment]
Thanks for your reply. No idea why i posted the issue here...
