### ISSUE TITLE
button or option to [toggle enable] + [refresh]

### ISSUE THREAD

**Issue by bergerjac** [uBlock-LLC/uBlock#1761]
when I want to unblock:
1. I go to a website, click [ub] icon in the bar
1. click on the on/off button
1. click on the refresh/reload button.

We could reduce clicks by 33% and redundant mouse movement if there was a button or option to [Toggle + Refresh] _simultaneously_

when I want to unblock:
1. I go to a website, click [ub] icon in the bar
1. **[Shift]** click on the on/off button
~3. click on the refresh/reload button.~

whether it's a [Shift] + click **or a new button** beside the current button... this small feature would save a ton of time

**Comment by krystian3w** [comment]
Hard refresh in opionion Gorhill / jspenguin2017 is hard to add to "uBlock".

Autorefresh have disconnect, well "uBlock" maybe have something function should possible.
