### ISSUE TITLE
[Syntax Support] example.com##script#id

### ISSUE THREAD

**Issue by Crystal-RainSlide** [uBlock-LLC/uBlock#1767]
An ad script in `https://www.baidu.com/s?wd=%E7%9A%AE%E9%9E%8B`

```
<script id="ecomScript">
...
<script>
```

I tried to remove it with `www.baidu.com##^script#ecomScript`, but I found that only `script:contains()` is supported.

Then I took some time with the code and got 'setAdsHeight' in the js outline from Firefox's dev tools, then everything works fine, but the time has gone.

Certainly CSS Selector don't support this, but adblocks may support it for simplifing the rules&filtering.

**Comment by ghost** [comment]
Try Ublock Origin, should work fine.

**Comment by Crystal-RainSlide** [comment]
@gwarser Thanks...

Well...

I'm using ublock Origin but get a ublock link towards here from Chinese Wiki: https://github.com/fang5566/uBlock/blob/master/README.md#ublock-origin

Which is still `forked from uBlockAdmin/uBlock`

Bye~

**Comment by gorhill** [comment]
When I `view-source` your URL `https://www.baidu.com/s?ie=utf-8&f=8&rsv_idx=1&wd=%E7%9A%AE%E9%9E%8B`, I get:

    <!DOCTYPE html>
    

No `script` in there.

**Comment by ghost** [comment]
Scroll down - lot of white space.
And this script with ecomScript id is already gone.

**Comment by Crystal-RainSlide** [comment]
Blanklines are just the start.

view-source:http://baidu.com shows that Baidu use some encode to avoid treatment when it was use HTTP.

Disscussion about the example.com##script#id Syntax had moved to https://github.com/uBlockOrigin/uBlock-issues/issues/42
