### ISSUE TITLE
uBO turned on, HSBC.co.uk is throwing errors trying to log in.

### ISSUE THREAD

**Issue by randomgeeza** [uBlock-LLC/uBlock#1769]
When uBO is turned on, HSBC.co.uk website throws an invalid error message when trying to log in. When uBO is off everything works as intended... Have tried adding hsbc.co.uk / security.hsbc.co.uk to the whitelist but it doesn't work. Switching uBO off with the blue button turns everything off, period, and is NOT site specific as it indicates.

Any help appreciated.

**Comment by krystian3w** [comment]
Wrong repo.

From my side - try find rule / list break website and report bug to author list.

**Comment by freaky767** [comment]
if using uBO, report issues to https://github.com/uBlockOrigin/uBlock-issues/issues
