### ISSUE TITLE
Feature Request: Blacklist Mode

### ISSUE THREAD

**Issue by timokau** [uBlock-LLC/uBlock#177]
Hi!
I've missed this feature in ABP and I miss it here, too: The possibility to run the extension in a "black list" mode where it is deactivated on any page by default.
I think that would be a great feature because advertisements generally are nessessary but if they are annoying, I want to be able to disable them.
I don't know how much work it would be to implement this, but I hope you consider it.

**Comment by gorhill** [comment]
This would run counter to what I see as an ideal: people shouldn't accept privacy-invading data-mining without first being asked to opt-in, and with full disclosure of what is done. Ads are just the small visible portion of the whole privacy-invading data mining abuse.

**Comment by gorhill** [comment]
Incidentally, a side effect to fixing issue #682 is to allow blacklist mode.

**Comment by gorhill** [comment]
Blacklist mode using dynamic filtering: https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-%C2%B5Block-everywhere-except.

**Comment by GrantGryczan** [comment]
The link is broken.

**Comment by ghost** [comment]
@GrantGryczan "fixed". Be aware this is "uBlock" repository and link is pointing to "uBlock Origin" wiki.
