### ISSUE TITLE
Not blocking antiadblock.  Pls see the screenshot

### ISSUE THREAD

**Issue by manjusr81** [uBlock-LLC/uBlock#1773]
Not blocking antiadblock.  Pls see the screenshot.    Chrome latest ver.  with windows 2012 server
![2018-06-29_061950](https://user-images.githubusercontent.com/9315238/42067745-79784918-7b65-11e8-8a78-a6580632867a.png)

**Comment by ghost** [comment]
First you have to decide which adblocker you want to use.

![image](https://user-images.githubusercontent.com/886325/42124519-47a3bdd2-7c64-11e8-810f-020a2b7a8ae5.png)

**Comment by publicarray** [comment]
more is not always better...

**Comment by Roph** [comment]
This is the borderline scam version of ublock, you should be using ublock origin. And yes, use only one blocker.
