### ISSUE TITLE
jsecoin.com website completely blocks all content?

### ISSUE THREAD

**Issue by JohnRSim** [uBlock-LLC/uBlock#1774]
Accessing https://jsecoin.com direct blocks all content when visiting the website.. 

![image](https://user-images.githubusercontent.com/364208/42628936-954f9c04-85c9-11e8-9b4d-00bc69f889e4.png)

**Comment by JohnRSim** [comment]
Can you remove line 199 please

**Comment by ghost** [comment]
About "NoCoin adblock list" you may need to ask here https://github.com/hoshsadiq/adblock-nocoin-list but they may not help:

>Mining (Opt-in and opt-out) will be blocked by default. If you see that mining is important, you would have to whitelist the website you actually want to support.

About "Peter Lowe’s Ad and tracking server list" ask here https://pgl.yoyo.org/adservers/ but this is domain blocking list and also may not help (lack of granularity).

If you want jsecoin.com main page and consent mining unblocked in **uBlock Origin** (different project) you may want to ask here https://github.com/uBlockOrigin/uAssets/issues
