### ISSUE TITLE
Affiliate code injection when copy n pasting

### ISSUE THREAD

**Issue by Idontwantojoin** [uBlock-LLC/uBlock#1777]
I find that when uBlock addon for Firefox is enabled, the following code gets pasted into my newsletter / web design when I paste content into MailChimp.

<style type="text/css">[href^="https://www.share-online.biz/affiliate/"]
{display:none !important;}
</style>

This code does not appear when uBlock addon is disabled.

My process:

1. In Firefox, In Mailchimp, within a draft newsletter, click to select and edit a content block (WYSIWYG editor).
2. In another browser tab, go to some other website to grab content, e.g. a paragraph of text with a link within. Use usual 'copy' function.
3) Return to Mailchimp and 'paste' the copied text into the content block.
4) Now flip to look at the code view (rather than the WYSIWYG view).

The code is there. Squirted in. 

Even if I delete the code, it may come back next time I edit the content block in MailChimp.

If I disable uBlock, everything is fine again.

 I was using uBlock 0.9.5.7 addon for Firefox 61 on Mac.

**Comment by ghost** [comment]
Looks like https://github.com/uBlock-LLC/uBlock/issues/161

**Comment by Idontwantojoin** [comment]
Thank you. I literally can't understand the thread. Reading it, it seems that this is kinda desired behaviour but a bit askew owing to words like 'face'. It's beyond me, so have to remove this addon.

**Comment by ghost** [comment]
You should try [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/).

**Comment by Idontwantojoin** [comment]
Thank you, on it!
