### ISSUE TITLE
Caret on textarea with Hebrew language is acting funny

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#178]
Well, just to inform you that this one unfortunetly hasn't yet been fixed (only on 3p-filters page).

I am worndering what is different between handling the textarea on 3p-filters between all others where the caret and the writing direction is following the css style rules (the direction of the writing is affected by
<b>text-align</b>, and the resize grabber is handled by the <b>direction</b> rule).

I have a js code applied to #externalLists on input action, but I don't really understand what it is for yet.

**Comment by gorhill** [comment]
It works fine if `direction` is set to `ltr` for `#externalLists` as far as I can tell.

**Comment by gorhill** [comment]
Actually, in 1st-party.html:
- There is a `dir="auto"` on the `textarea` element
- No `direction` style property set

In 3rd-party.html
- No `dir="auto"` on the `textarea` element
- A `direction` style property set to `rtl`

**Comment by gorhill** [comment]
So just to confirm: in Hebrew language, the handle to resize the textarea is also on the right of the textarea?

**Comment by Mikey1993** [comment]
Yep, this is the fundamental issue.

Maybe this demo can help us in some way (there is a js code to get and set the caret on a textarea element)?
http://demo.vishalon.net/getset.htm

**Comment by gorhill** [comment]
Ok wait, I am confused. What exactly is the issue aside the one I thought it was (in the commit above)?

I tried the caret in both English and Hebrew, and it all works fine as far as I can tell.

**Comment by Mikey1993** [comment]
As of now, when you disable direction rule and add the dir property to the textarea the text behaves well.
The issue aside the one in the commit is that after you last commit, the resize grabber of the textarea is always on the right side of the texarea - I will open a new issue.
