### ISSUE TITLE
Blocking ads on playboy.de

### ISSUE THREAD

**Issue by chetanbasuray** [uBlock-LLC/uBlock#1782]
Hello,
I see this ad below:
https://imgur.com/a/Gq1ZtJn
I tried grabbing the div element for the parent div of the advertising here:
https://imgur.com/a/ysRGEFi
and added new filters:
www.playboy.de##:xpath(//[@id="advertising-1"])
www.playboy.de##:xpath(//div[contains(@class, 'advertising-wrapper')])
But the ads still do not go away.

**Comment by ghost** [comment]
I think the NSFW links aren't really appropriate. We get the gist of the issue without it too
