### ISSUE TITLE
Blocking Google Analytics

### ISSUE THREAD

**Issue by jeepish** [uBlock-LLC/uBlock#1789]
On Symplicity's CSM product https://www.symplicity.com/higher-ed/solutions/csm, our students (I am an IT director for a university career center) are reporting that when using uBlock they are unable to see the legitimate content (job postings). Instead they see a blank content area and the content: {{Base.sectionTitle}}

We are not seeing this problem with other ad blockers (tested AdBlock and Ghostery), only uBlock.

The only external scripts on these pages are Google Analytics -- no ads of any kind.

**Comment by fhferreira** [comment]
+1

**Comment by spirillen** [comment]
> The only external scripts on these pages are Google Analytics -- no ads of any kind.

And how much support do you exspect to get a place like this, with your bad intention of infecting you student computers with google spyware??

**Comment by fhferreira** [comment]
Not, i will only track if they access my site through the Adwords and use this data into conversion funnel

**Comment by jeepish** [comment]
I have no issue with blocking Google Analytics. Block whatever add-on content you want. However, any blocker of any kind should not block the content of the page. If the blocker can't tell between the content the end-user is trying to consume and extensions, scripts, or trackers, then the blocker is failing its designed purpose.

**Comment by uBlockAdmin** [comment]
Hi, Can you please help me to replicate the issue?
