### ISSUE TITLE
Resize grabber of a textarea is always on the right side

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#179]
The resize grabber on the textarea element on the 3p-filters page always on the right - should behave dynamically.

**Comment by Mikey1993** [comment]
in reference to #178 I have tried to get both to behave as it should, but failed to do so.

Either the resize grabber is on the left side (direction="rtl" rule), but the text isn't written properly even with text-align: left rule (the caret issue referenced),
Or I the text is written as it should (dir="auto" property of the textarea + text-align: left rule), but the resize grabber in always on the right side (<b>As it is now</b>).

**Comment by gorhill** [comment]
Ok, I understand the issue. I can think of a solution (embedding the textarea with transparent background as a child of a div which will be resizable as per direction), but I want to see if it can avoided.

**Comment by gorhill** [comment]
Ok I couldn't make the textarea-in-div idea work, too hacky and result doesn't work. I want a clean solution but there doesn't seem to be one, we may have to live with this kink. I could make the textarea larger by default as mitigation.
