### ISSUE TITLE
Blocking of images does not work on certain site

### ISSUE THREAD

**Issue by Juschi1** [uBlock-LLC/uBlock#1790]
1. Go to: https://www.pornhub.com/pornstar/leolulu

2. block any image on the page with element picker mode

3. image reappears after reloading.

example: https://i.imgur.com/1ojooDU.png

They are simple, static images with always the same filename. Easyest task. Dont understand why it does not work.

**Comment by ghost** [comment]
Because Pornhub images are whitelisted (over 250 exception filters in EasyList). Append `important` option to your filter.

**Comment by Juschi1** [comment]
thanks.
Where do I have to put the "important"? For example here:

||test.com/image.jpg

**Comment by ghost** [comment]
`||test.com/image.jpg$important` after `$` if no other options

or

`||test.com/image.jpg$image,important` after `,` with other options

**Comment by Juschi1** [comment]
Thanks. If I do this, the "create" button in the element picker greys out.

See here: https://i.imgur.com/Vf0oByU.png

**Comment by ghost** [comment]
Add filter without it and modify in Dashboard -> My rules.
