### ISSUE TITLE
High CPU with Facebook

### ISSUE THREAD

**Issue by gonzad26** [uBlock-LLC/uBlock#1791]
I've been noticing since last update that with ublock enabled, cpu usage for Google Chrome went high. With Chrome's task manager i see 100% CPU and with Windows i see 30% of usage.

My specs:
Windows 10 1809 x64
Core I7 6700K with 32GB Ram
Chrome version 70.0.3538.102 (Official Build) (64-bit)

**Comment by freaky767** [comment]
Use uBlock Origin, a lot better than this.

**Comment by uBlockAdmin** [comment]
I will look into it.

**Comment by freaky767** [comment]
Why deleting my comments? isnt it true though?

**Comment by krystian3w** [comment]
conflict of interest
