### ISSUE TITLE
Just use uBlock Origin

### ISSUE THREAD

**Issue by freaky767** [uBlock-LLC/uBlock#1792]
it is a lot better, and updated a lot frequently then this scamming extension.

**Comment by sukima** [comment]
And where is the link? Is there a GitHub repo?

**Comment by fatihky** [comment]
Hey @sukima its here if you couldn't find: https://github.com/gorhill/uBlock

**Comment by 3xploiton3** [comment]
thx for this information, but can u prove it?

**Comment by freaky767** [comment]
considering uBlock Origin literally gets updated daily, its quite frequent in patching bugs, and blocking ads. this gets BARELY updated.

**Comment by freaky767** [comment]
for the scamming part, they had a donation page in which they literally wanted money just to keep the website running.

**Comment by LiveChief** [comment]
Close Request.
Not sure why this is a actual issue.

**Comment by ghost** [comment]
Admin is triggered
