### ISSUE TITLE
Bundeling uBlock in Librefox-Firefox ?

### ISSUE THREAD

**Issue by intika** [uBlock-LLC/uBlock#1793]
This is a small question i would like to know if there is any legal issue if i bundle your extension in my project 

https://github.com/intika/privafox-firefox
(Privafox Firefox set for a better security, privacy and performances )

(Thanks a lot for your amazing work :))

**Comment by ghost** [comment]
Are you sure you want "uBlock" and not "uBlock Origin"? You recommend "Origin" on your page.

**Comment by intika** [comment]
ohh sorry i did not notice that i asked the question in the wrong place... thanks a lot for taking time to answer ;)
