### ISSUE TITLE
l and 1 look same!

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1794]
![screenshot 150](https://user-images.githubusercontent.com/18484996/48965383-5f964400-efe6-11e8-8d0d-1a585cacafd3.png)
It's: 1 l 1 l1 l1_0.obj but l and 1 look same!

**Comment by ghost** [comment]
- blame your system default "monospace" font
- Manjaro in uBlock:
![image](https://user-images.githubusercontent.com/886325/48966189-a70fd680-efcc-11e8-903e-0178f379bdc7.png)
- Android in uBlock Origin:
![screenshot_20181124-094034](https://user-images.githubusercontent.com/886325/48966219-58167100-efcd-11e8-94d6-f607680b1d2b.png)

- your screenshot is not from uBlock, uBlock Origin Issue tracker is here https://github.com/uBlockOrigin/uBlock-issues/issues

**Comment by ghost** [comment]
Ok thanks :)

**Comment by krystian3w** [comment]
On look same try zoom 120% or more.
