### ISSUE TITLE
Update Regions, languages

### ISSUE THREAD

**Issue by jcvr1994** [uBlock-LLC/uBlock#1795]
Hi Ublock they can Update Regions, languages is it so outdated

**Comment by jcvr1994** [comment]
optimize your extension is slowing down my browser

**Comment by uBlockAdmin** [comment]
Thanks for your feedback. We are working on it and soon be releasing an optimized version.

**Comment by jcvr1994** [comment]
Upload new version on Google Chrome Store

**Comment by jcvr1994** [comment]
Upload new version on Google Chrome Web Store
