### ISSUE TITLE
uBlock origin breaking 4chan-x plugin

### ISSUE THREAD

**Issue by anaemic** [uBlock-LLC/uBlock#1798]
Hi,
I noticed i was getting an error popup while using the 4chan-x addon on firefox, and googling it seemed to suggest that the error was coming from uBlock not from the addon itself.

anyway, long story short, i added the line;

@@||mayhemydg.github.io^$xmlhttprequest,domain=4chan.org

to my ublock-unbreak list and it sorts the problem out. Just figured i'd post it here in the hopes of having it included someday.

**Comment by ghost** [comment]
The real uBlock Origin is: https://github.com/gorhill/uBlock.
See: 
• https://github.com/gorhill/uBlock/wiki/Badware-risks#ublockorg
• https://github.com/gorhill/uBlock/wiki/uBlock-Origin-is-completely-unrelated-to-the-web-site-ublock.org

"uBlock" (this repository) is a scam.
