### ISSUE TITLE
No more working on latest Chrome version for Windows XP SP3 ?

### ISSUE THREAD

**Issue by Mysteerion** [uBlock-LLC/uBlock#1799]
Hello,

It seems that the latest uBlock extension for Chrome release (version 0.9.5.15 released this Apr 19, 2019) doesn't work with the latest Chrome version available for Windows XP SP3 (Chrome 49.0.2623.112 m). Ads are not blocked (for example on https://zimbra.free.fr/), uBlock button keeps grayed, filtering is disabled, and it can't be enabled. I can access uBlock options, but the Filter Lists tab is empty (I tried to attach a screenshot but I think it didn't work - Github doesn't support my browser either).

I tried to reinstall the extension and keep default settings, with no success. I also tried to disable all other extensions, with no luck. On the Chrome Store, nothing says the extension is not compatible (while this is cleary specified with uBlock Origin).

Please can you help ?

I know that I have a very old Chrome version, but I have to buy another computer to upgrade, and uBlock was a way to better secure my browser.

**Comment by ghost** [comment]
GNU/Linux... / buy new PC / no more it crap food cost more are you have...

**Comment by Mysteerion** [comment]
Please can you configure latests versions of this extension so that  they won't install on incompatible Chrome versions, as uBlock Origin does ? Indeed I  have kept a uBlock Origin version working on my XP computer, while latests versions are told not to be compatible with earlier Chrome versions than 51. Why only uBlock couldn't do that ?

**Comment by uBlockAdmin** [comment]
Thanks for your valuable inputs. we will set it.

**Comment by ghost** [comment]
uBO drop support old chromium - needed 54.

**Comment by Mysteerion** [comment]
Ok but this should be mentioned in uBlock manifest file from version 0.9.5.15 so legacy browser won't update. And please keep on line the latest working version (v0.9.5.14) in Chrome store for those. Otherwise i'll keep using ublock Origin.

**Comment by uBlockAdmin** [comment]
We have set a minimum chrome version to 49.0 in our latest version.
