### ISSUE TITLE
Conflict with HTTPS Everywhere extension in Chrome

### ISSUE THREAD

**Issue by Nocturnalizer** [uBlock-LLC/uBlock#18]
Hi :)

I'm really liking uBlock but I've noticed that HTTPS Everywhere is showing a 'Warning' message whenever uBlock is installed. It seems to occur whenever browsing sites that are using Google Ads and here is the error message:

Warning:
This extension failed to redirect a network request to https://partner.googleadservices.com/gpt/pubads_impl_42.js because another extension (µBlock) redirected it to chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/js/noop.js.

This message actually appears below HTTPS Everywhere in the Extensions menu in Chrome. There don't appear to be any adverse effects going on but it would be nice if there is a fix available so that the conflict no longer happens.

Thanks kindly for any help you can offer!

**Comment by gorhill** [comment]
The last extension installed wins the ability to redirect over others when multiple extensions try to redirect a single net request.

In the current case, it is completely harmless, as the request which HTTP-E would have redirected is a request to block anyways.

But thinking of it, if ever a user installs HTTPS-E **after** uBlock, there is harm, as HTTPS-E will redirect a request which was intended to be blocked, which means uBlock won't be able to block it.

Looks like uBlock has to block outright without using redirection at all. This means #7 will still show the browser's default placeholder when a resource cannot be fetched, that is until I fix it completely (collapsing the DOM counterpart off a request).
