### ISSUE TITLE
Regular expression based filters

### ISSUE THREAD

**Issue by redstoneleo** [uBlock-LLC/uBlock#1803]
I want to block 
`https://upos-hz-mirrorwcsu.acgvideo.com/upgcxcode/07/81/67938107/67938107-1-15.flv?e=ig8euxZM2rNcNbRghbUVhoM1hbNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5QK==&deadline=1557748136&gen=playurl&nbs=1&oi=2000583741&os=wcsu&platform=pc&trid=a197b4e3d1e14af1b7da06f0a41175ff&uipk=5&upsig=a2132a1c5a4b2d94748cdee07b51ea62&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk`
in page http://www.cnblogs.com/iMath/p/LYYDownloader.html
My regular expression didn't work, so what's wrong ?
`/.+?67938107-1-15.flv.+/$domain=www.cnblogs.com`

**Comment by ghost** [comment]
Maybe no support by uBlock 0.9.X...
