### ISSUE TITLE
Washington Post

### ISSUE THREAD

**Issue by Chernobyl1** [uBlock-LLC/uBlock#1805]
WAPO detects adblocker, unable to work around 
![Capture](https://user-images.githubusercontent.com/38861934/59055112-fa9b9080-8849-11e9-9c60-c21991118fce.PNG)

**Comment by uBlockAdmin** [comment]
Thanks for reporting this. I am adding this to my list for further investigation.

**Comment by uBlockAdmin** [comment]
Can you please try it out this if you are using latest version 0.9.5.20?

washingtonpost.com#$#abort-current-inline-script Promise "0x
