### ISSUE TITLE
Update MANIFESTO.md

### ISSUE THREAD

**Issue by jcvr1994** [uBlock-LLC/uBlock#1807]
![UBLOCK LLC](https://user-images.githubusercontent.com/43253672/59369506-2f09c380-8d06-11e9-9dbe-9f5df70afac7.jpg)

**Comment by uBlockAdmin** [comment]
We will update it. Thanks.

**Comment by ajayyy** [comment]
lol, why does it say it doesn't support acceptable ads still

**Comment by uBlockAdmin** [comment]
We will update it soon. Thanks for drawing attention.
