### ISSUE TITLE
I'm getting Chrome, Win10, ads again! Can you get rid of them again, please?

### ISSUE THREAD

**Issue by elofla** [uBlock-LLC/uBlock#1808]
It seems at the last update I started getting the ads on my gmail email account again, which previously were being blocked. The date they started seems to coordinate with the last update, about 2 weeks ago.  Can this be fixed again?  I know its a cat and mouse game! Thanks!

**Comment by uBlockAdmin** [comment]
Can you please share me the screenshot?

**Comment by elofla** [comment]
Here is a screenshot from today. Thanks. - El of LA

**Comment by uBlockAdmin** [comment]
I can't find a screenshot.

**Comment by elofla** [comment]
The screen shot was attached.  Attaching again.

**Comment by uBlockAdmin** [comment]
No attachment. I am seeing this on my end.

![Screen Shot 2019-06-20 at 12 39 05 PM](https://user-images.githubusercontent.com/35694050/59828963-d36cb500-9359-11e9-988c-c998a8fb1468.png)

**Comment by elofla** [comment]
Well then if your system is deleting the screen shots I have attached, I'm
done. Thank you for your time.
