### ISSUE TITLE
Is there anyway to whitelist my api? 

### ISSUE THREAD

**Issue by printedheart** [uBlock-LLC/uBlock#1809]
We have an event api for e-commerce sites that uses a beacon for the sites commerce functions. Is there an application or a review to be added to UBlock?

**Comment by uBlockAdmin** [comment]
Please go through this.

https://help.getadblock.com/support/solutions/articles/6000067137-how-can-i-contact-the-filter-list-authors-to-report-unblocked-ads-or-a-list-problem-
