### ISSUE TITLE
Fail to block non-direct adressed elements

### ISSUE THREAD

**Issue by Dushess** [uBlock-LLC/uBlock#1810]
Started not so long time ago, latest Chrome (actually detected on some early platform, like 74 at latest builds)
It looks like your rules about blocking of page elements simply don't work, unless it's an image.

**Comment by Dushess** [comment]
tested with ###somename sitekeys

**Comment by uBlockAdmin** [comment]
Thanks for reporting an issue. sitekey is not supported. Can you give me a specific use case to help me replicate the issue?

**Comment by Dushess** [comment]
www.reddit.com###header-bottom-left > .tabmenu > li:nth-of-type(3) > .choice[href="https://www.reddit.com/new/"]

an example
actually it means more than half potential of this tool is missing (also text ads, which is same elements, marked by sitekeys)

**Comment by uBlockAdmin** [comment]
I am unable to find out the element. 

![Screen Shot 2019-06-27 at 12 17 05 PM](https://user-images.githubusercontent.com/35694050/60243922-ef7ed200-98d6-11e9-9432-e6f3940aa71b.png)

**Comment by Dushess** [comment]
Ok, then this
###sr-header-area > .width-clip > .srdrop.dropdown > .title.selected

![2669-15](https://user-images.githubusercontent.com/15954961/60277677-b1010b80-9906-11e9-8fe7-b2b38702f59e.jpg)
Basically anything that uses ###

**Comment by uBlockAdmin** [comment]
It's working for me. Here is a screenshot.  Looks like you haven't clicked on create button in pop up on bottom right corner.

![Screen Shot 2019-06-28 at 11 11 07 AM](https://user-images.githubusercontent.com/35694050/60320269-d3426a00-9996-11e9-8313-ea4e7ab2ba74.png)

**Comment by Dushess** [comment]
Seems to be my installation related, a little video coming soon.

**Comment by Dushess** [comment]
Basically
[bandicam video.zip](https://github.com/uBlock-LLC/uBlock/files/3340351/bandicam.video.zip)
![image](https://user-images.githubusercontent.com/15954961/60362748-62c53880-99ea-11e9-8e45-e4de77aa8209.png)

**Comment by Dushess** [comment]
And yes, i know how to, since using this module long time.

**Comment by uBlockAdmin** [comment]
We are able to replicate this issue. This fix will be included in the next version release (in a couple of days). Thank you very much.

**Comment by Dushess** [comment]
Thank you

**Comment by Dushess** [comment]
But for now only reddit is fixed. Tried for example on DA, blocked logo frame (###deviantart-logo > .mark > svg > .wikistick) - as usual don't work for now.

**Comment by uBlockAdmin** [comment]
We haven't released build (v0.9.5.19) yet. It is under QA. I think you will get an update early next week.

**Comment by uBlockAdmin** [comment]
Hi, Can you please verify it your end if you have received v0.9.5.19 update?

**Comment by Dushess** [comment]
Seems to be site-specific. Will look into it.

**Comment by Dushess** [comment]
Not working again, same reddit, just noticed. Some sited are good, some - still do not work. Maybe better switch to Origin, there it's fine....

**Comment by Dushess** [comment]
Browser related, it just sorta broken now. Gonna reinstall, probably NOT use chrome

**Comment by uBlockAdmin** [comment]
Thanks for your valuable inputs. There is a lot of area of improvement in Element picker. We will target it in the near future.
