### ISSUE TITLE
Quantcast Choice broken because of uBlock

### ISSUE THREAD

**Issue by arkoe** [uBlock-LLC/uBlock#1811]
We are using Quantcast Choice on our website to ask consent for cookies, however recently uBlock started blocking some JS files loaded by Quantcast. The pop-up is now broken because of that.

Can you guys fix this? It is quite annoying that uBlock blocks something other than an ad, and asking consent in EU is really important now with the new cookie law (GDPR).

**Comment by uBlockAdmin** [comment]
Can you send me a screenshot to help me find out issue?

**Comment by arkoe** [comment]
![image](https://user-images.githubusercontent.com/8835399/60520949-9522ae80-9ce6-11e9-83d0-c328b1011500.png)

Here you see two files being blocked, and the Quantcast script aborting the display of the UI. These are the (partial) url's of te blocked scripts:

https://privacy-api-gateway.quantcast.com/gvl-proxy?version=
https://audit.quantcast.mgr.consensu.org/

When I disable uBlock, everything works.

**Comment by uBlockAdmin** [comment]
Can you go to 3rd-party filters tab in uBlock Dashboard  and send me a screenshot of Filterlist which are selected?  It seems like issue belongs to Filter list.

**Comment by arkoe** [comment]
![image](https://user-images.githubusercontent.com/8835399/60521766-1d558380-9ce8-11e9-8d0e-60bccfe1d457.png)

However, if it is any setting in the dashboard, it would be an issue for myself only. A lot of our website visitors are either having issues with the pop-up, or same behavior as I experience.

**Comment by uBlockAdmin** [comment]
You are reporting at wrong place. Please report issue over here: (https://github.com/uBlockOrigin/uBlock-issues/issues)
