### ISSUE TITLE
Stripe is block

### ISSUE THREAD

**Issue by NikRpk** [uBlock-LLC/uBlock#1812]
The payment provider Stripe is blocked on some e-commerce sites. 

Reproduce: 
Navigate to the site and click on the top 3 buttons. Then it doesn't go further. Error is resolved when disabling uBlock and/or AdBlock. 
js.stripe.com is blocked by the list EasyPrivacy. 

Example: 
flintmobile.de/preise 

![image](https://user-images.githubusercontent.com/49123781/60666334-14d78700-9e67-11e9-9d07-78fe5d9f47c0.png)

**Comment by uBlockAdmin** [comment]
Please refer the following link to report an issue.

https://help.getadblock.com/support/solutions/articles/6000067137-how-can-i-contact-the-filter-list-authors-to-report-unblocked-ads-or-a-list-problem-
