### ISSUE TITLE
Can uBlock "unwrap" an element like this?

### ISSUE THREAD

**Issue by AnthonyMastrean** [uBlock-LLC/uBlock#1814]
On Atlassian's developer blog, they have this horrible Tweet selection thing. It actually wraps whatever text is selected in a new anchor tag. So, I imagine you can't just block the whole element.

![image](https://user-images.githubusercontent.com/217842/61549506-336c7f00-aa1e-11e9-83ea-7bf115105e02.png)

```html
<a class="inline-tweet-link" href="https://twitter.com/intent/tweet?source=webclient&amp;amp;via=atlassian&amp;amp;text=Git subtree is a great alternative&amp;amp;url=https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree" target="_blank">it solves lots of the problems</a>
```

https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree

I'm inexperienced with custom rules, so I don't know if this is possible or how to write it up.

**Comment by liamengland1** [comment]
Use uBlock Origin and not this barely updated version
