### ISSUE TITLE
uBlock blocking Ads analytics

### ISSUE THREAD

**Issue by fhferreira** [uBlock-LLC/uBlock#1816]
When we access our site we could not track the conversions.

**Comment by uBlockAdmin** [comment]
We appreciate your feedback. Could you please provide us more detail (steps) to replicate the issue?

**Comment by fhferreira** [comment]
@uBlockAdmin thank you for your response. 

When I've access the webpage  I could not load the  GTAG and the Facebook Pixel, so I could not track users in my site and tracking their conversions. 

![image](https://user-images.githubusercontent.com/140686/63215345-86a81f00-c0fb-11e9-8894-1777a5649211.png)

**Comment by uBlockAdmin** [comment]
Hi,
This is a 3rd-party filter list issue, you must report it to EasyPrivacy maintainers, they will need to create an exception for the site, like @@||googletagmanager.com/gtag/js$script,domain=staging.homestaymatch.com, @@||connect.facebook.net^*/fbevents.js$domain=staging.homestaymatch.com

Please refer the following link to report an issue.
https://help.getadblock.com/support/solutions/articles/6000067137-how-can-i-contact-the-filter-list-authors-to-report-unblocked-ads-or-a-list-problem-
