### ISSUE TITLE
OfficeScan antivirus detects spam404scamlist.txt as Virus/Malware

### ISSUE THREAD

**Issue by nminaya** [uBlock-LLC/uBlock#1817]
I had to uninstall this extension from my PC at my job because the antivirus has issued two alerts about the file spam404scamlist.txt.

The IT security guy told me that uninstall this extension from chrome 😅

![image](https://user-images.githubusercontent.com/7952888/63859511-84548900-c975-11e9-9e75-94b3884ee70e.png)

![image](https://user-images.githubusercontent.com/7952888/63859476-6f77f580-c975-11e9-9771-3c5027b68c40.png)

**Comment by uBlockAdmin** [comment]
Thank you very much for reporting this issue. We will fix it.

We had "Spam404" filter list link to (https://spam404bl.com/spam404scamlist.txt) but now we will change it to (https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt)

**Comment by uBlockAdmin** [comment]
Hi,  We have released new version v0.9.5.21. Let's us know if the above issue still exists.
