### ISSUE TITLE
(whitelist) img.akubebas.com

### ISSUE THREAD

**Issue by 3xploiton3** [uBlock-LLC/uBlock#1818]
![](https://i.imgur.com/mwbfbnY.jpg)

remove this rule
`||img.akubebas.com/*.gif$image`
`indoxx1.*##+js(acis, Object.defineProperty, vocabulary)`

broken website [indoxx1.art](url)
![](https://i.imgur.com/YA5pDzh.jpg)

**Comment by uBlockAdmin** [comment]
Please report issue over here: https://github.com/uBlockOrigin/uBlock-issues/issues
