### ISSUE TITLE
26GB of virtual memory

### ISSUE THREAD

**Issue by Thomas131** [uBlock-LLC/uBlock#1819]
Hello!
Suddenly my Firefox consumed a huge amount of Virtual Memory (26 GB and 32 GB once) and CPU usage. I disabled uBlock Origin and within secounds, the Virtual Memory reduced itself to 9 GB. I enabled uBlock Origin again and the Virtual Memory went viral again.

After disabling again, my CPU-Performance is fine, but maybe there were other reasons for the CPU-Performance ...

I don't have problems disabling uBlock Origin since I have uMatrix installed, too.

God bless!
Thomas

**Comment by Thomas131** [comment]
related?: https://www.reddit.com/r/uBlockOrigin/comments/bemo5l/ubo_consuming_107g_of_virtual_ram/

**Comment by uBlockAdmin** [comment]
Please report issue over here: https://github.com/uBlockOrigin/uBlock-issues/issues
