### ISSUE TITLE
Add ⌘-Click for MAC users string

### ISSUE THREAD

**Issue by ialexsilva** [uBlock-LLC/uBlock#182]
if windows <ctrl> else mac show ⌘

**Comment by gorhill** [comment]
Just learned there is also a symbol for `Ctrl`: "Also, there is a standardized keyboard symbol (to be used when Latin lettering is not preferred), given in ISO/IEC 9995-7 as symbol 26, and in ISO 7000 “Graphical symbols for use on equipment” as symbol ISO-7000-2028. This symbol is encoded in Unicode as U+2388 helm symbol (⎈)." Source: [Wikipedia](http://en.wikipedia.org/wiki/Control_key).

Given that `Ctrl` may be different in other languages (for instance, German = `Strg`), I think I should use the standard pictogram, or else it will be impossible for me to replace `Ctrl` and whatever else it is in other languages with the Mac symbol.

Edit: Well I just tried the pictogram for `Ctrl`, and it looks terrible, way too small, and most people won't know what that is. So it is a bit of a puzzle how to solve this.

**Comment by woozyking** [comment]
The symbol for Ctrl in Windows is different from Mac as well, unfortunately. In mac it's ^ I believe.
