### ISSUE TITLE
How to cancel monthly donation?

### ISSUE THREAD

**Issue by serranoarevalo** [uBlock-LLC/uBlock#1820]
I've been donating for a while now and I want to stop doing it. Where is the link to cancel it?

**Comment by uBlockAdmin** [comment]
Hi, 

Can you please tell us which payment gateway you are using for the payment? We tried finding in your name PayPal account but unable to locate it.  Here are few links for cancellation of payment. 

Cancel Stripe Payment:- https://www.jotform.com/answers/1429263-How-to-cancel-an-ongoing-subscription-from-Stripe-account

Cancel Paypal Payment:- https://www.paypal.com/lu/smarthelp/article/how-do-i-cancel-an-automatic-payment-i-have-with-a-merchant-faq2058

**Comment by serranoarevalo** [comment]
itnico.las.me{at}gⓂail.com

**Comment by uBlockAdmin** [comment]
Thanks. Which payment gateway (Paypal Or Stripe) you are using?

**Comment by serranoarevalo** [comment]
Stripe! I followed your link but I don't see the subscription on my account.

**Comment by uBlockAdmin** [comment]
We will check and revert back.

**Comment by uBlockAdmin** [comment]
Hi, We have cancelled your subscription and refunded the most recent $5 payment.

**Comment by serranoarevalo** [comment]
Thanks!
