### ISSUE TITLE
Can anyone ad this site to the list, it doesnt seem to be there.

### ISSUE THREAD

**Issue by rhlkmth** [uBlock-LLC/uBlock#1822]
airartapt.site/

it pops up everytime i visit a site without ssl

**Comment by spirillen** [comment]
@rhlkmth any sources for examples from where it occurs, and maybe a screenshot of the `airartapt.site` ?

**Comment by rhlkmth** [comment]
> @rhlkmth any sources for examples from where it occurs, and maybe a screenshot of the `airartapt.site` ?

It just pops up in a new tab when i visit a site without a secure https connection.

I dont really have any screenshots man, sorry

**Comment by spirillen** [comment]
If a site pops-up every time you visit a non httpS site, I would be suspicious for infection as this is defiantly not an expected behavior on any circumstances
