### ISSUE TITLE
Howdo you add this site to the peter lowe list?

### ISSUE THREAD

**Issue by rhlkmth** [uBlock-LLC/uBlock#1823]
https://areantaid.site

If you visit lookmovie.ag and click on any link, this spammy site pops up. Please block this. Thank you

**Comment by spirillen** [comment]
`areantaid.site` is a blanck page...

<details><summary>Screenshot with Tor</summary>

![Screenshot_20191107_122201 areantaid site](https://user-images.githubusercontent.com/44526987/68385096-58b20400-0159-11ea-9255-3eb692d49f15.png)

![Screenshot_20191107_122338 areantaid site dev-tool](https://user-images.githubusercontent.com/44526987/68385207-85feb200-0159-11ea-8816-2c4541cf9d1a.png)


</details>

I seriously believe you need to check your windows for any infections like in #1822
