### ISSUE TITLE
Request to be added back to whitelist

### ISSUE THREAD

**Issue by Jordan-McMillan** [uBlock-LLC/uBlock#1824]
This change removed a whitelist rule for evestment:
https://github.com/easylist/easylist/commit/e95ef2da029ef7c648d60b5bdac1cacb7b4a5d5c#diff-57814f66f7ce561ca9320be995443b1fL165

The product line affected is called "analytics", which gets used in the url path for api calls.

Would it be possible to restore that line for evestment?

**Comment by Jordan-McMillan** [comment]
wrong repo, sorry

**Comment by spirillen** [comment]
Same answer as here https://github.com/easylist/easylist/issues/4251#issuecomment-551090994
