### ISSUE TITLE
Annoying uBlock pop-up on youtube search bookmark

### ISSUE THREAD

**Issue by pootz10** [uBlock-LLC/uBlock#1827]
Firefox 72.0.2
uBlock Origin 1.24.2

Everytime I click on this [youtube search url saved on my firefox bookmark](https://www.youtube.com/results?search_query=bbb+2020&sp=EgJAAQ%253D%253D) an annoying uBlock pop-up appears.
Please check screenshot below
http://puu.sh/F5M3J/4661b3b9fc.png

If I block pop-ups from youtube the issue is solved, but this way I cannot middle click channels or videos that uBlock will block as it was a pop-up.

If it's not an issue I'd like to know how to solve because I've tested different searches and it didn't happen. I would like to maintain doubleclick.net blocked.

Thanks in advance.

**Comment by Mikey1993** [comment]
I can see this is uMatrix that is blocking the request, isn't it?
Anyhow, uMatrix issues go here:
https://github.com/uBlockOrigin/uMatrix-issues/issues

Also,
This is not the official uBlock Origin repo.
Report here if you have an issue with uBlock Origin:
https://github.com/uBlockOrigin/uBlock-issues/issues

**Comment by pootz10** [comment]
oh, it is indeed. Thank you.
