### ISSUE TITLE
overflow: hidden when blocking elements, impossible to scroll webpage

### ISSUE THREAD

**Issue by jokoon** [uBlock-LLC/uBlock#1831]
The right click menu where you can choose to block certain elements, to avoid popups or other warnings, I pretty useful.

Problem: on many websites, for example the ones using the quantcast thing, after blocking such elements, a overflow: hidden appears in the firefox CSS inspector (the first thing that appear), which makes it impossible to scroll the webpage.

Removing overflow: hidden solves the problem, but I wish this custom CSS rule would not appear.

Is it related to ublock origin?

**Comment by dl74i** [comment]
It's not "related".
Cookie nag screens add those to html and/or body.
```
*##body,html:matches-css(overflow: hidden):style(overflow:auto !important)
```
