### ISSUE TITLE
!!! ALERT - THIS IS AN UNOFFICIAL VERSION !!! PLEASE READ BEFORE POSTING A NEW ISSUE HERE !!! ALERT - THIS IS AN UNOFFICIAL VERSION !!!

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#1833]
This is ***NOT*** the official repository of the uBlock Origin extension on Github.

Proofs:
1. As you can see, no new commits were pushed in more than 6 months..
2. Look at the post of the original creator of uBlock Origin who posted about this repository:
[https://twitter.com/gorhill/status/1063777353678110720](https://twitter.com/gorhill/status/1063777353678110720)

## **Please refer to these OFFICIAL places:**
- Official repository of uBlock Origin extension (Official release): [https://github.com/gorhill/uBlock](https://github.com/gorhill/uBlock)
- Official issue tracker of the uBlock Origin extension (Only for issues about the extension): [https://github.com/uBlockOrigin/uBlock-issues/issues](https://github.com/uBlockOrigin/uBlock-issues/issues)

Thank me later.
Peace out.

**Comment by p1r473** [comment]
Thanks!!!
