### ISSUE TITLE
how to block css?

### ISSUE THREAD

**Issue by blmulang** [uBlock-LLC/uBlock#1836]
I read the custom code description on the wiki, and only mentioned the style of adding a toilet, but did not mention how to modify it.
Maybe I didn’t see it, or I don’t know the wiki translated into Chinese
0.0

**Comment by trickypr** [comment]
uBlock is an unmaintained fork (or steal #1838) of uBlock origin. I strongly recommend you use uBlock origin over uBlock.

https://github.com/gorhill/uBlock
