### ISSUE TITLE
Issue: CMP is being blocked by uBlock

### ISSUE THREAD

**Issue by nmpina** [uBlock-LLC/uBlock#1837]
Greetings,

My apologies for deleting the content of this issue but it contains some private information and for this reason, it should be addressed to the product support using private means of communication (mail,...).

Cheers,

Nelson

**Comment by spirillen** [comment]
Cool to know somebody actually have been reading the EU curt ruling :+1: Hope both your domains stays to enhance our privacy and protect our democracy (or should I say what's left of it)

**Comment by nmpina** [comment]
> Cool to know somebody actually have been reading the EU curt ruling 👍 Hope both your domains stays to enhance our privacy and protect our democracy (or should I say what's left of it)

Thank _spirillen_ for your response. But this is confidential information so I'll have to ask you what you did with the domain? I've checked the commits and it seems you add this domain to a blacklist, considering this domain as an AdWare that must be Blocked.
If so, please, whitelist it. 
Cheers,
Nelson

**Comment by spirillen** [comment]
You asked me the same here: https://github.com/mypdns/matrix/commit/9e621881a552bd2982d90a9ef2d73b52dc630f96#r47263922 rather than responding to the issue: <https://www.mypdns.org/T3683>.

You'll need to use the proper channels and not put issues from third party boards every where else. You request is NOT related to @uBlock-LLC, please write your concerns in the right place. <https://www.mypdns.org/T3683>

**Comment by nmpina** [comment]
> You asked me the same here: [mypdns/matrix@9e62188#r47263922](https://github.com/mypdns/matrix/commit/9e621881a552bd2982d90a9ef2d73b52dc630f96#r47263922) rather than responding to the issue: https://www.mypdns.org/T3683.
> 
> You'll need to use the proper channels and not put issues from third party boards every where else. You request is NOT related to @uBlock-LLC, please write your concerns in the right place. https://www.mypdns.org/T3683

Yes. And I didn't post everywhere. This was direct to uBlock and my mistake was only this one. I didn't answer you here: https://www.mypdns.org/T3683 because I don't want to register to your project.

Once again, this is an issue concerning the Ad Block. I'll ask you to remove the domain from your list.
The part of the screenshots was a bit rude from you.

Thank you

**Comment by iam-py-test** [comment]
> Greetings,
> 
> My apologies for deleting the content of this issue but it contains some private information and for this reason, it should be addressed to the product support using private means of communication (mail,...).
> 
> Cheers,
> 
> Nelson

@nmpina28 
1. This is _not_ the repo for uBlock Origin
See my comment in https://github.com/uBlock-LLC/uBlock/issues/1840
2. The private data you deleted is not really deleted
To delete it, you need to click on _edited_, find the original edit, click _options_, and then click _delete reversion from history_
