### ISSUE TITLE
How to block this chinese novel website ads

### ISSUE THREAD

**Issue by alcwj828** [uBlock-LLC/uBlock#1839]
I use the following website to read some of my fav  Chinese novels i use website from my computer browser because on iphone safari the ads are worse with tons of lewd commercial. so my request is the website always show 3 frames of ads 2 on sides and one biggest square on the lower right side i need help telling me how to block these ads please advise on how i can do this in ublock once good for all thank you.
the website 
https://ajnnan.com/
i tried picking element but didn't work out right. 
please advise.

**Comment by 4yx** [comment]
Firstly, use uBlock Origin (you can find it on https://github.com/gorhill/uBlock), for more info you can see #1838. Then, go to the settings (the "Open the dashboard" button), and to the "My filters" tab. Once you're there, paste the following, and apply changes:
```
! 2021-05-02 https://ajnnan.com
||c.v4dwkcv.com//s/img/dot.gif$image
||g.ieeod0.com/b/1/*/*/*/*.html?uid=*&hlogo=*&&$subdocument
```
These filters worked for me, if they no longer work for you you can try experimenting with the pick element button like I did.

**Comment by spirillen** [comment]
It appears the both domains from the rules are solely used for adware

could you test this by adding the following rules to your filters??

```
||v4dwkcv.com^
||ieeod0.com^
```

![image](https://user-images.githubusercontent.com/44526987/116832936-066b6b00-abb7-11eb-94a3-339d271f9bdf.png)

![image](https://user-images.githubusercontent.com/44526987/116832943-12572d00-abb7-11eb-8a05-3554bdf8f77d.png)

**Comment by alcwj828** [comment]
> It appears the both domains from the rules are solely used for adware
> 
> could you test this by adding the following rules to your filters??
> 
> ```
> ||v4dwkcv.com^
> ||ieeod0.com^
> ```
> 
> ![image](https://user-images.githubusercontent.com/44526987/116832936-066b6b00-abb7-11eb-94a3-339d271f9bdf.png)
> 
> ![image](https://user-images.githubusercontent.com/44526987/116832943-12572d00-abb7-11eb-8a05-3554bdf8f77d.png)

these 2 lines completely remove those frames awesome help thanks a million !!!

**Comment by spirillen** [comment]
I'll thanks you as well, as I now can add them to mypdns.org :smirk: as adware servers

**Comment by iam-py-test** [comment]
@spirillen it appears that `v4dwkcv.com` and `ieeod0.com` are offline.

**Comment by spirillen** [comment]
Keeping them, as they are alive, at least in the WHOIS DB, which means they possibly can/will be back online in a split second.

```bash
pyfunceble -a -d v4dwkcv.com ieeod0.com
```

![image](https://user-images.githubusercontent.com/44526987/120332365-f7c7bf00-c2ee-11eb-8927-ea0f3901f86d.png)

But thanks for your heads up @iam-py-test :+1:

**Comment by iam-py-test** [comment]
> Keeping them, as they are alive, at least in the WHOIS DB, which means they possibly can/will be back online in a split second.
> 
> ```shell
> pyfunceble -a -d v4dwkcv.com ieeod0.com
> ```
> 
> ![image](https://user-images.githubusercontent.com/44526987/120332365-f7c7bf00-c2ee-11eb-8927-ea0f3901f86d.png)
> 
> But thanks for your heads up @iam-py-test 👍

Ok! https://who.is/whois/v4dwkcv.com confirms that their WHOIS is still online.
How can they have WHOIS records but not resolve? 
![image](https://user-images.githubusercontent.com/84232764/120332944-36dd1c80-c2bd-11eb-83ba-e67b171337cb.png)

**Comment by spirillen** [comment]
:smiley: 

That's easy :) just remove any dns records from the zone or simply remove the zone from the dns servers

Try `drill -T v4dwkcv.com`

```bash
drill -T v4dwkcv.com
.       518400  IN      NS      l.root-servers.net.
.       518400  IN      NS      j.root-servers.net.
.       518400  IN      NS      d.root-servers.net.
.       518400  IN      NS      h.root-servers.net.
.       518400  IN      NS      b.root-servers.net.
.       518400  IN      NS      f.root-servers.net.
.       518400  IN      NS      g.root-servers.net.
.       518400  IN      NS      e.root-servers.net.
.       518400  IN      NS      m.root-servers.net.
.       518400  IN      NS      c.root-servers.net.
.       518400  IN      NS      i.root-servers.net.
.       518400  IN      NS      a.root-servers.net.
.       518400  IN      NS      k.root-servers.net.
com.    172800  IN      NS      a.gtld-servers.net.
com.    172800  IN      NS      b.gtld-servers.net.
com.    172800  IN      NS      c.gtld-servers.net.
com.    172800  IN      NS      d.gtld-servers.net.
com.    172800  IN      NS      e.gtld-servers.net.
com.    172800  IN      NS      f.gtld-servers.net.
com.    172800  IN      NS      g.gtld-servers.net.
com.    172800  IN      NS      h.gtld-servers.net.
com.    172800  IN      NS      i.gtld-servers.net.
com.    172800  IN      NS      j.gtld-servers.net.
com.    172800  IN      NS      k.gtld-servers.net.
com.    172800  IN      NS      l.gtld-servers.net.
com.    172800  IN      NS      m.gtld-servers.net.
v4dwkcv.com.    172800  IN      NS      ns3.dnsv4.com.
v4dwkcv.com.    172800  IN      NS      ns4.dnsv4.com.
v4dwkcv.com.    180     IN      SOA     ns3.dnsv4.com. enterprise2dnsadmin.dnspod.com. 1547519214 3600 180 1209600 180
```

Then you can see the complete lookup flow from the root servers and down, here you'll see that `ns3.dnsv4.com` & `ns4.dnsv4.com` are set authorotative DNS servers so let's ask them for any A/AAAA records

```bash
drill -t a v4dwkcv.com @ns3.dnsv4.com.
;; v4dwkcv.com. IN      A

;; AUTHORITY SECTION:
v4dwkcv.com.    180     IN      SOA     ns3.dnsv4.com. enterprise2dnsadmin.dnspod.com. 1547519214 3600 180 1209600 180

drill -t a v4dwkcv.com @ns4.dnsv4.com.
;; v4dwkcv.com. IN      A

;; AUTHORITY SECTION:
v4dwkcv.com.    180     IN      SOA     ns3.dnsv4.com. enterprise2dnsadmin.dnspod.com. 1547519214 3600 180 1209600 180

drill -t aaaa v4dwkcv.com @ns4.dnsv4.com.
;; v4dwkcv.com. IN      AAAA

;; AUTHORITY SECTION:
v4dwkcv.com.    600     IN      SOA     ns3.dnsv4.com. enterprise2dnsadmin.dnspod.com. 1547519214 3600 180 1209600 180

drill -t aaaa v4dwkcv.com @ns3.dnsv4.com.
;; QUESTION SECTION:
;; v4dwkcv.com. IN      AAAA

;; AUTHORITY SECTION:
v4dwkcv.com.    600     IN      SOA     ns3.dnsv4.com. enterprise2dnsadmin.dnspod.com. 1547519214 3600 180 1209600 180
```

As you can see there are no A/AAAA records in the in the zone file, and your `dig` is default asking for the A record unless you tells it something else with the `-t` arg

**Comment by iam-py-test** [comment]
Ok, Thank you for replying. 
I tried `drill -T v4dwkcv.com` and got an error

![image](https://user-images.githubusercontent.com/84232764/120343028-59276800-c2c6-11eb-8e90-985632a033ef.png)

**Comment by spirillen** [comment]
PS: You don't need to visit ripe/Arin to get the whois information, You can do it from your terminal

```bash
whois v4dwkcv.com
   Domain Name: V4DWKCV.COM
   Registry Domain ID: 2081195414_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.ename.com
   Registrar URL: http://www.ename.net
   Updated Date: 2020-11-11T22:21:34Z
   Creation Date: 2016-12-12T02:34:30Z
   Registry Expiry Date: 2021-12-12T02:34:30Z
   Registrar: eName Technology Co., Ltd.
   Registrar IANA ID: 1331
   Registrar Abuse Contact Email: abuse@ename.com
   Registrar Abuse Contact Phone: 86.4000044400
   Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: NS3.DNSV4.COM
   Name Server: NS4.DNSV4.COM
```

You might however need to install jwhois first

**Comment by iam-py-test** [comment]
Ok! Thanks

**Comment by spirillen** [comment]
You need `ldnsutils`

**Comment by iam-py-test** [comment]
> ldnsutils

Ok! Thank you for you help
