### ISSUE TITLE
Warning: This repo is fake - Do NOT open an issue here for uBlock Origin

### ISSUE THREAD

**Issue by iam-py-test** [uBlock-LLC/uBlock#1840]
### This repo is abandoned and fake

@uBlockAdmin has not committed to this repo in **over a year** (last commit was https://github.com/uBlock-LLC/uBlock/commit/58f897d48d4aa5cd45ddf0aeba305f5a518a0463), while @gorhill has committed thousands of times in that time. If you are looking for uBlock **Origin**, you are in the wrong place. See https://github.com/gorhill/uBlock instead. 

If you are here to report an issue, you need to go to https://github.com/uBlockOrigin/uBlock-issues for issues with the extension and https://github.com/uBlockOrigin/uAssets for filter issues.

For those who don’t believe me, see these:

https://github.com/uBlock-LLC/uBlock/pulse/monthly Vs https://github.com/gorhill/uBlock/pulse/monthly and https://github.com/uBlockOrigin/uAssets/pulse/monthly

More data:
https://www.mywot.com/scorecard/ublock.org
https://www.virustotal.com/gui/url/11a9307debbaa61011533299dd99b1e54d2ad81125e9fce98f30d67eb0ae8dcb/community

Newest commit at the time of this issue: https://github.com/gorhill/uBlock/commit/57e660e39bb7ef90075c82c589b6544106d48461 (there were thousands of commits _after_ this was posted)

Please read the explanation on [Wikipedia](https://en.wikipedia.org/wiki/UBlock_Origin#uBlock)

**Comment by iam-py-test** [comment]
Anyone who has _uBlock_ not _uBlock Origin_ installed needs to uninstall it immediately and run an antivirus scan on their computer

**Comment by iam-py-test** [comment]
Also, don’t confuse ublock.org (which is related to @uBlockAdmin) with  ublockorigin.com (which is real)

**Comment by iam-py-test** [comment]
Also, @google you need to take down uBlock from your store

**Comment by iam-py-test** [comment]
Does anyone know if `ublock-origin.com` is legit?

**Comment by nmpina** [comment]
Thank you @iam-py-test for warning me. I thought that I already had deleted that, the history of that but I forgot
Thank you  :)

**Comment by iam-py-test** [comment]
> Thank you @iam-py-test for warning me. I thought that I already had deleted that, the history of that but I forgot
> Thank you :)

I can confirm that the history has been deleted
