### ISSUE TITLE
* * * allow doesn't work

### ISSUE THREAD

**Issue by Heinz14** [uBlock-LLC/uBlock#1841]
I wrote in my rules, as described in #682 for blacklist mode:
```
* * * allow
* * 3p-frame block
* youtube.com * noop
youtube.com * * noop

```
But it's still blocking everything on every site, so it doesn't work.

**Comment by iam-py-test** [comment]
@Heinz14 this repo is _not_ uBlock Origin and is not maintained.
See my comment on https://github.com/uBlock-LLC/uBlock/issues/1840
Try installing the [real uBlock Origin](https://github.com/gorhill/uBlock) and retrying
