### ISSUE TITLE
Unable to whitelist localhost

### ISSUE THREAD

**Issue by mgoku** [uBlock-LLC/uBlock#185]
I tried to add localhost on my whitelist (either way, by clicking power button or by directly write in whitelist editor), but never work. The list will not be saved. 

I think it is because uBlock assume localhost as an invalid host name, and therefore ignore it.

**Comment by Delawen** [comment]
This is happening to me again right now.

**Comment by TrentBrown** [comment]
Hmm... I have the same problem. Looks like this is a regression of a fix that went in back in 2015?
