### ISSUE TITLE
Cannot whitelist localhost

### ISSUE THREAD

**Issue by zwippie** [uBlock-LLC/uBlock#187]
As a webdeveloper, I want to whitelist `localhost` (or more specific: `localhost:3000`) so I can test my webpages that load external scripts (or ads).

I tried to whitelist localhost by pressing the uBlock _power button_ but that does not seem to work.

Manually adding `localhost` (or variations) to the 'Whitelist' settings tab also does not work. After clicking 'Apply changes' the entry is still in the list, but if I change tabs to 'Your filters' and then back to tab 'Whitelist', the localhost entry is gone.

**Comment by gorhill** [comment]
Dup of #185. I will try to push a release today with the fix.
