### ISSUE TITLE
 µBlock 0.5.2.0-rc.0 issues

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#189]
Still shown as v. 0.5.1.0. manifest.json says "version": "0.5.1.0"

MVPS HOSTS marked as "may be obsolete". That was NOT the case in v. 0.5.1.0.

**Comment by gorhill** [comment]
> MVPS HOSTS marked as "may be obsolete"

Likely related to the fact that I forgot to upgrade version number (version number change forces the cache to be flushed because uBlock ships with most up to date version of lists).

**Comment by gorhill** [comment]
Fixed with 1443da323100adaba36b8de0d07acfeb04f609ae.

**Comment by ghost** [comment]
I'm sorry but MVPS HOSTS is still marked as "may be obsolete" in rc1.

**Comment by ghost** [comment]
Just one additional remark: I had noticed that issue with MVPS HOSTS in previous versions and was about to report it but then it was fixed in 0.5.1.0. Now it's there again.

**Comment by gorhill** [comment]
Do you have auto-update enabled?

**Comment by ghost** [comment]
Yes , I have.

**Comment by gorhill** [comment]
Can http://winhelp2002.mvps.org/hosts.txt be reached from your side? Is HTTPSB blocking the connection?

**Comment by ghost** [comment]
Yikes! You are right - shame on me ...

EDIT: But it's still funny that I didn't have this problem with v. 0.5.1.0 ...

**Comment by gorhill** [comment]
~~Actually, another funny thing is that when the remote server fail, it is supposed to fall back on github repo server, so unless this one was also blocked, it should have been updated using the fall back. Can you confirm the github repo was also blocked?~~ Never mind, it's true only if the version on the repo is deemed newer, which is not the case for MVPS.

**Comment by gorhill** [comment]
> But it's still funny that I didn't have this problem with v. 0.5.1.0 ...

Cached assets with a remote counterpart are deemed obsolete when the cache is older than 3.1415928 days, and this is checked every 6 hours. So it probably became "obsolete" according to this by pure coincidence as you installed the release candidate.
