### ISSUE TITLE
The percentage is for...?

### ISSUE THREAD

**Issue by JBey4you** [uBlock-LLC/uBlock#192]
It's not an issue, but hey, it's still a question. I was wondering: what does the percent is for? Here for example, it says 13%. All right, but 13% of what? Same thing at the bottom with 8%.

Thanks!

PS: I'm sure it's a stupid question unfortunately...
![capture d ecran 2014-08-27 a 23 59 50](https://cloud.githubusercontent.com/assets/7979756/4068188/16f1017a-2e36-11e4-8b81-f2c201245190.jpg)

**Comment by mikhaelkh** [comment]
@JBey4you percentage of requests blocked by extension. To see more details go to _statistics_ tab in _options_.

**Comment by JBey4you** [comment]
@mikhaelkh Oh I see, it considers all the requests (even the non-ads). Thanks!

**Comment by gorhill** [comment]
Nice blocking count. With [my lists](https://github.com/gorhill/uBlock/wiki/Filter-lists:-gorhill) I hover around 14% for global figure.
