### ISSUE TITLE
[EasyPrivacy] Website is unusable with uBlock

### ISSUE THREAD

**Issue by JBey4you** [uBlock-LLC/uBlock#194]
There you go: http://www.disneylandparis.fr/index.html

You can't do anything, when you try to click on something, nothing changes. FYI, the website is also broken with Adblock Plus. I guess it's related to a filter...

![capture d ecran 2014-08-28 a 02 33 10](https://cloud.githubusercontent.com/assets/7979756/4069656/ed965310-2e4a-11e4-98f1-6af868904502.jpg)

**Comment by gorhill** [comment]
Adding this filter:

```
/s_code.$script,domain=disneylandparis.fr
```

Causes the links to work. It's a tracker/analytics or something like that, however, I wonder if it causes the site to be fully functional.

If you use Fanboy's Enhanced Stats, which contains a similar filter, the site will work.

**Comment by JBey4you** [comment]
Yep, the site is functionnal now. In reality, I'm not using it haha. I was just on it at this time and I found that it didn't work. So I reported here.

**Comment by gorhill** [comment]
The causes is `||tagcommander.com^$third-party` in EasyPrivacy, I will report to EasyList crew. Let's leave the issue opened so I can remember to report it.

**Comment by gorhill** [comment]
Submitted to EasyList crew: http://forums.lanik.us/viewtopic.php?f=64&t=17966
