### ISSUE TITLE
"Privacy stuff" suggestion

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#195]
You mention on ["Privacy stuff"](https://github.com/gorhill/uBlock/wiki/Privacy-stuff) that you can't guarantee protection against Google Analytics because of possible exception filters in one of the ABP lists.

Perhaps you could add the following command line switch to that site:

`--host-rules="MAP *.google-analytics.com 0.0.0.0","MAP *.googleadservices.com 0.0.0.0","MAP *.doubleclick.net 0.0.0.0","MAP *.googletagservices.com 0.0.0.0"`

This switch works reliably and has the additional benefit that it works also on the Chrome webstore where extensions are disabled.

**Comment by gorhill** [comment]
Can you edit the wiki? I don't mind people fixing/adding stuff to the wiki, that saves me work.

For things that can be blocked with HTTPSB, I believe it is preferable to use HTTPSB, as if a site breaks, it can be unbroken. But that switch is definitely interesting for those requests which bypass the webRequest API.

**Comment by ghost** [comment]
> Can you edit the wiki? I don't mind people fixing/adding stuff to the wiki, that saves me work.

Done!

> For things that can be blocked with HTTPSB, I believe it is preferable to use HTTPSB, as if a site breaks, it can be unbroken.

I agree. I've added a corresponding hint.
