### ISSUE TITLE
[EasyPrivacy] Links are not clickable at http://r7.com

### ISSUE THREAD

**Issue by ialexsilva** [uBlock-LLC/uBlock#196]
The links in this site: http://www.r7.com/ not work (not clickable) with ublock activated
My filters enabled:
![capturar](https://cloud.githubusercontent.com/assets/6363160/4082344/a8551cd6-2ef0-11e4-8dc6-9e68f099474f.PNG)

**Comment by gorhill** [comment]
_EasyPrivacy_ is blocking something.

I found that adding `/s_code_portal_$script,domain=r7.com` in custom filters fixes the problem.

Need to submit issue + fix to EasyList crew.

**Comment by gorhill** [comment]
Submitted: http://forums.lanik.us/viewtopic.php?f=64&t=17984
