### ISSUE TITLE
Better tile image for Opera store

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#198]
I am being asked to provide a better tile image for Opera store:

> Can you make the image a bit more descriptive (e.g. by adding the word "Ad blocker" or something like that), and add some padding on top and bottom, so that the octagon is not stuck to the borders.

I agree with the missing padding, but for words, I just don't know what to do.

I personally dislike "Ad blocker", as ads are just a subset of what need to be blocked in my opinion -- there are the even more important trackers/analytics/data-mining to block, which are not visible unlike ads. I would like the mindset of people to move from "blocking ads" to something more generic -- hence why I refer to uBlock as a "blocker", not an "ad blocker".

Anyway, I am no designer, so if somebody wants to take this one that would be great. The current tile image is checked in at https://github.com/gorhill/uBlock/blob/master/doc/img/opera-300x188.png, so ask for a pull request.

I think they want it asap, they offered to have their designer do it, but I would have to check whether it would be released as part of this project (GPLv3)

**Comment by kurtextrem** [comment]
Simply "blocker" is... nothing for the usual user who just got aware of ad blockers or doesn't know much about those at all. They search for something which blocks ads - it's a meta key. Blocker sounds negative and is too vague. They could they the extension is a "blocker" for parents to keep their children safe.
If there is anything else which could function as description: "Privacy guard". That's what it does - told in a really human way.

**Comment by gorhill** [comment]
I added padding in 2d1151794072056c91910d4b2ecd0aef872a9d8e, it was accepted.
