### ISSUE TITLE
Update punycode.js

### ISSUE THREAD

**Issue by kurtextrem** [uBlock-LLC/uBlock#200]
From v1.2.4 to v1.3.1 (only v1.3 in between)
Not sure if it's worth upgrading though. The new version(s) introduce email "parsing"(?) and could be potential performance decrease.

**Comment by gorhill** [comment]
I don't think it's worth it. The only use for punycode.js is to parse Mozilla's Public Suffix List, which is just domain name stuff. I could maybe use it to render the domain and host names in the request log, but  still, nothing related to email. I rather not change external libraries until there is a tangible benefit for the project.
