### ISSUE TITLE
Video auto-plays when uBlock is enabled

### ISSUE THREAD

**Issue by JBey4you** [uBlock-LLC/uBlock#206]
If you go here : http://www.engadget.com/2014/09/03/samsung-galaxy-note-edge-hands-on/, the video embeded will auto-plays. Plus, you can't stop it... When you disable uBlock, you have to press play to launch it.

I don't know if it's related to uBlock or a filter (maybe EasyList...).

**Comment by JBey4you** [comment]
Okay so actually you can pause it by clicking on the video, but the buttons "Play", etc don't work.

**Comment by gorhill** [comment]
I don t see this behavior with out-of-the-box filter lists.
- What version of browser?
- What filter lists on top of default ones?

**Comment by JBey4you** [comment]
Chrome 38 beta 64-bit (OS X)
![capture d ecran 2014-09-03 a 17 47 01](https://cloud.githubusercontent.com/assets/7979756/4136830/949cf30e-3381-11e4-94f8-ddcee9393add.jpg)

**Comment by gorhill** [comment]
I cannot reproduce on stable version of Chrome or Opera.

I can reproduce on dev version of Chrome 39.

**Comment by JBey4you** [comment]
Weird. So it's more related to Chrome then?

**Comment by gorhill** [comment]
Yes, problem is Chrome, this also occurs with Adblock Plus + _EasyList_.

I saw net requests unexpectedly labelled with a `frameId` of `-2`. I need to dig a bit more and report to Chromium devs.

**Comment by gorhill** [comment]
I see these differences between Chrome 37 and Chrome 39:

Chrome 39:
- `other    http://adm.fwmrm.net/crossdomain.xml` = blocked

Chrome 37:
- `plugin   http://2a86.v.fwmrm.net/ad/p/1?` = blocked

**Comment by gorhill** [comment]
Alright, the problem is that with Chrome 39, the request `http://adm.fwmrm.net/crossdomain.xml` is reported as a request of type `other`, while in Chrome 37 the request is reported as a request type `plugin`. The difference causes this specific request to be blocked in Chrome 39, while it is not blocked in Chrome 37 (because of filter `||fwmrm.net^$~object-subrequest,third-party`, where `object-subrequest` is alias of `plugin`).

My opinion is that the request should be of type `plugin`, not `other`, as it is a request made by the plug-in as far as I understand.

**Comment by JBey4you** [comment]
I guess it's the same for the beta version (Chrome 38)?

**Comment by gorhill** [comment]
> I guess it's the same for the beta version (Chrome 38)?

Search for `http://adm.fwmrm.net/crossdomain.xml` in the _Statistics_ tab in the dashboard, and see what is the type of the request: if it is `other` instead of `plugin`, it's the problem.

**Comment by JBey4you** [comment]
Yep, it's <code>other</code>.

![capture d ecran 2014-09-03 a 19 20 52](https://cloud.githubusercontent.com/assets/7979756/4138158/b0dc221c-338e-11e4-87f0-48ff93bba9dc.jpg)

**Comment by gorhill** [comment]
Actually the problem is worst: **all** requests which should be of type `plugin` (or `object` internally) are labelled as `other`. This needs to be reported to Chromium devs.

**Comment by JBey4you** [comment]
Is it related to Endadget's player only or it could be a bigger problem? I hope for you it's the first one...

**Comment by gorhill** [comment]
> I hope for you it's the first one...

It's the second one. All blockers will be broken, it's not just uBlock who will suffer.

**Comment by gorhill** [comment]
Opened issue with Chromium devs: http://code.google.com/p/chromium/issues/detail?id=410382

**Comment by harshanvn** [comment]
Strange, i am able to reproduce this issue on Chrome v37.0.2062.103 unknown-m (64-bit), Win 8.1

I am able to see these requests (*.crossdomain.xml are of plugin type only).

My Filters..uBlock v0.5.5
![myfilters](https://cloud.githubusercontent.com/assets/779630/4140106/3debfe54-33a1-11e4-836f-bac1e05c466e.PNG)

**Comment by gorhill** [comment]
> Strange, i am able to reproduce this issue on Chrome v37.0.2062.103

If `http://adm.fwmrm.net/crossdomain.xml` was blocked, the problem will happen. It's not supposed to be blocked with default lists.

**Comment by harshanvn** [comment]
> If http://adm.fwmrm.net/crossdomain.xml was blocked, the problem will happen. It's not supposed to be blocked with default lists.

thanks. This makes sense. Its blocked for me.

Also, just an FYI, in Firefox also, crossdomain.xml is reported as of type other.

**Comment by gorhill** [comment]
> reported as of type other

Reported by _what_?

**Comment by harshanvn** [comment]
> Reported by what?

In Dev tools, these are categorized of type "other"..

![other type obj](https://cloud.githubusercontent.com/assets/779630/4150658/bea5ba96-343f-11e4-99e8-b2d1861c22b3.png)

**Comment by gorhill** [comment]
I am not sure what is going on here. The bug **is** that in Chrome 38+, requests of type `object` are reported as requests of type `other`, while they were formerly reported properly as type `object` prior to Chrome 38. It's not speculation: it is definitely the problem. I fail to see how Firefox reports these requests is relevant to the current issue in Chrome.

**Comment by harshanvn** [comment]
Yes it is not directly relevant to our issue here. I am merely stating that Firefox also reports these types of requests the same way. It is just FYI..

**Comment by gorhill** [comment]
In ABP for Firefox the same request is reported as `object`, so there is some kind of mapping internally done somewhere, whether by ABP or maybe deeper in Firefox they are properly typed.

**Comment by JBey4you** [comment]
I found another video which auto-plays (it's normal here), but (!) is kinda broken with uBlock. You can select one particular moment. You can pause though: http://money.cnn.com/2014/09/04/technology/security/apple-celebrity-photos/index.html

With uBlock disabled, you can select the moment you want with the progress bar.

**Comment by gorhill** [comment]
> I found another video which auto-plays (it's normal here), but (!) is kinda broken with uBlock.

Problem is in _EasyList_, same happens with ABP. This should be reported to _EasyList_ maintainers. I would appreciate if you report to them, I don't have that much time on my hands.

Edit: removed suggested filter to fix issue, it works on Chromium 34, but not on Chrome 37.
