### ISSUE TITLE
uBlock v5.5 - Chrome v38 Collected Errors

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#207]
Hi,

Updated uBlock to v0.5.5 by clicking "Update Extensions Now". Update was successful and it is working as expected. However, chrome reported below errors..Not sure if its an issue or not. So, just created a bug for your review!

![image](https://cloud.githubusercontent.com/assets/779630/4140194/5ca7f1a8-33a2-11e4-8250-90e2b8b7a22f.png)

µBlock> readRepoCopyAsset("%s") / onRepoFileError("%s"):
![image](https://cloud.githubusercontent.com/assets/779630/4140221/91746d76-33a2-11e4-8a6a-7d47c2161acf.png)

![image](https://cloud.githubusercontent.com/assets/779630/4140252/fba636ac-33a2-11e4-8c7e-59d594d8540b.png)

Unchecked runtime.lastError while running tabs.get: No tab with id: 22
![image](https://cloud.githubusercontent.com/assets/779630/4140260/154d75fc-33a3-11e4-9b8c-6ea35d6795bb.png)

Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Docum
![image](https://cloud.githubusercontent.com/assets/779630/4140278/43819a16-33a3-11e4-931e-8e13d84fa6a0.png)

Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Docum
![image](https://cloud.githubusercontent.com/assets/779630/4140292/63d66ab2-33a3-11e4-9200-3c16cb5edee8.png)

Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Docum
![image](https://cloud.githubusercontent.com/assets/779630/4140303/86dea506-33a3-11e4-861b-7750fa7ca9c7.png)

Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Docum
![image](https://cloud.githubusercontent.com/assets/779630/4140310/9d2948d4-33a3-11e4-974e-5ef502be4e92.png)

**Comment by gorhill** [comment]
The home/repo file error can occur if your connection to internet dropped when uBlock tried to read the filter lists. Normally uBlock will write at the console which file couldn't be read -- "%s" should be the file name, but it looks like Chrome doesn't format the strings in their error collecting feature. Note that uBlock will make behind-the-scene requests to fetch the remote filter lists, so if you have HTTPSB installed and it blocks behind-the-scene requests, uBlock will fall back loading the local version of the filter lists.

**Comment by gorhill** [comment]
The "No tab with id" seems new with Chrome 37, I don't see it on Chrome 34. It's benign, but I wonder why this happens. Looks like they changed the behavior of the API in there.

**Comment by gorhill** [comment]
Re. `chrome.tabs.get()` error, I filed an issue with Chromium devs: http://code.google.com/p/chromium/issues/detail?id=410868

**Edit:** I was wrong, there is no issue with Chromium, I forgot I had another call to chrome.setIcon(), which was unguarded, unlike the other.

**Comment by gorhill** [comment]
0b64dbf373fe98a313e38c683b981f6de432db30 fixes the "No tab with id: _x_" error.

**Comment by gorhill** [comment]
`readRepoCopyAsset / onRepoFileError` etc. can occur under normal circumstances, so what I will do is craft an error string which is more useful to the user.

**Comment by gorhill** [comment]
Fix completed with 6e77cc385393767afdd5fd3871bd2bb81b6108dd.
