### ISSUE TITLE
z-index higher than greates value?

### ISSUE THREAD

**Issue by kurtextrem** [uBlock-LLC/uBlock#209]
https://github.com/gorhill/uBlock/blob/master/js/element-picker.js#L748
I'm not sure, couldn't find any information about it, but https://hg.adblockplus.org/adblockpluschrome/rev/c1390e515d8c says "0x7FFFFFFF" or 2147483647 is the greatest value possible.

**Comment by gorhill** [comment]
There is no maximum value in CSS specifications.
