### ISSUE TITLE
Element picker appears misaligned on http://xkcd.com/

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#210]
Reported as a comment in #190, it's a different issue than #190 though.

**Comment by gorhill** [comment]
The div main element has a margin of -390px, and a left position of 390px (`position` is `relative`). I suspect the problem is the browser's `Element.getBoundingClientRect` implementation.

**Comment by s-fiebig** [comment]
**Quick fix:** Replace both lines in highlightElements()
`'M', r.left + offx, ' ', r.top + offy,`
with
`'M', r.left - document.body.getBoundingClientRect().left + offx, ' ', r.top + offy,`
As long as the `Element.getBoundingClientRect` isn't working as expected, this works for me, at least, all tested websites looked alright with the picker.

**Comment by gorhill** [comment]
Thanks for the finding, I will try it.

**Comment by gorhill** [comment]
Ok, this works so long as the document is not scrolled. As soon as you scroll, the highlighted rectangle becomes sticky rather than scroll with the position of the highlighted element.

Need something more, will look into it.

**Comment by gorhill** [comment]
Ok, replacing `offx` entirely with `-bodyRect.left` seems to do the trick (also applies to `offy`).

**Comment by pwstokes225** [comment]
This issue seems to be fixed on http://xkcd.com/.
Unfortunately, now it seems to manifest in places where it hadn't before. Such as http://what-if.xkcd.com/ and http://oeis.org/.

**Comment by pwstokes225** [comment]
It looks like the issue after scrolling has re-emerged.
Otherwise, this fix works great.

**Comment by gorhill** [comment]
> after scrolling

?

**Comment by Mikey1993** [comment]
@gorhill Please look at my last comment on #275, there is a new issue regarding this fix I suppose.
Thanks.

**Comment by pwstokes225** [comment]
Perhaps this scrolling issue is unique to me, or to people with similar setups.
I'm on µBlock 0.7.0.5 on Chrome 40.0.2182.3 dev-m (64-bit) on Windows 8.1.
Picking an element without any scrolling works fine:
![No scrolling](https://cloud.githubusercontent.com/assets/764704/4608679/77a91b96-5286-11e4-8c14-6de1679ca7f5.png)
Picking the same element after scrolling slightly results in a misalignment by the amount scrolled:
![Scrolling](https://cloud.githubusercontent.com/assets/764704/4608681/9d153626-5286-11e4-82a0-29b1710bffbf.png)

**Comment by ialexsilva** [comment]
@pwstokes225 I could not reproduce the glitch...
µBlock 0.7.0.5 on Chrome 38.0.2125.101 m (64-bit) on Windows 8.1.

**Comment by s-fiebig** [comment]
@pwstokes225a as ialexsilva I couldn't reproduce this.
µBlock 0.7.0.5 on Chrome 38.0.2125.101 m (32bit)

**Comment by pwstokes225** [comment]
Okay, I have confirmed my issue resulted from a flag in chrome://flags/. I'm not certain which one, but the element picker works fine now that I've reset all the flags to their default.
