### ISSUE TITLE
"Adblock Warning Removal" list doesn't seem to like uBlock anymore

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#213]
Some change in uBlock along the way (It worked before, as I had a cache of these rules) broke the "Adblock Warning Removal" list,
and now uBlock doesn't seem to be able to parse it by entering:
https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
in the "Custom" category.

uBlock just seems to wait some seconds (transparent foreground) and then reports 0 in use out of 0 rules.

**Comment by gorhill** [comment]
Works from here. If the URL is not reachable, it will time out after 15 seconds and of course no filters will be accounted for it. Sometimes `https://easylist-downloads.adblockplus.org` times out, for whatever reason.

Edit: Just to add to this, if ever the content of the URL was previously cached, if the URL can't be reached during an update, the cache of the old version will be kept as a fallback.

**Comment by gorhill** [comment]
I noticed that it takes a while though before the server responds when I try `https://easylist-downloads.adblockplus.org/antiadblockfilters.txt` directly in the browser.

**Comment by Mikey1993** [comment]
Yeah, you are right.
For mysterious reasons it's now working for me in uBlock..

But before that, when I was able to access 
https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
via the browser (but not uBlock),
it was less than 15 seconds, so I don't think that uBlock really waits 15 seconds before cancelling the request.

**Comment by gorhill** [comment]
> I don't think that uBlock really waits 15 seconds before cancelling the request

https://github.com/gorhill/uBlock/blob/master/js/assets.js#L210

Note that it won't wait 15 seconds when the server sends an error response, so maybe the server was sending an error code.

**Comment by Mikey1993** [comment]
I see, seems like we will have to live with the assumption that it was indeed 15 seconds.
Time flies while having fun with bugs :)
