### ISSUE TITLE
uBlock installs Yontoo?

### ISSUE THREAD

**Issue by anandpiyer** [uBlock-LLC/uBlock#215]
It seems like installing uBlock results in the installation of Yontoo, which, according to The Safe Mac (TSM), is an adware (http://www.thesafemac.com/arg-yontoo/). To reproduce this, run the adware removal tool from TSM with and without uBlock.

**Comment by gorhill** [comment]
It's a false positive. There are these entries in various filter lists:

```
||yontoo.com^$subdocument,third-party (EasyList)
layers.yontoo.com (hpHosts)
```

Looks like TSM just performs a plain string search and find the entries above in the filter lists shipped with the extension.

**Comment by anandpiyer** [comment]
Ah okay, thanks a lot!
