### ISSUE TITLE
Consider forcing a reload of the extension when filters have to be reloaded

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#22]
I have noticed that whenever filters have to be reloaded, the memory footprint baseline of uBlock ever inches up. There is no memory leaks, it's just that it seems when temporarily handling MB of data (filter loading/parsing), the browser seems to keep stuff around and this is out of control of the extension. HTTPSB suffers the same problem, and as far as I can tell, other extensions too.

Since in uBlock nothing is temporary (as opposed to HTTPSB), when filters need reloading, simply force a reload of the extension, this way a new background page is created, all clean and tidy.

**Comment by gorhill** [comment]
Need to look into this more, to find out whatever can mitigate the memory footprint climbing when all filters are reloading. Somehow it appears a lot of stuff are stuck in chromium's GC tree. Restarting the extension would probably solve this, but this has the annoying (I suppose) side effect of the extension's tab being closed. Advantage: very simple to implement, I could just add another apply button named _Apply changes and restart_.

**Comment by ghost** [comment]
This would be great indeed.

**Comment by kikaxa** [comment]
> side effect of the extension's tab being closed

Then reopen it after reload? One more permission, though.

**Comment by gorhill** [comment]
With ee81436ff54e9e31d3e9595bbf913402584f56c5#diff-6, it is now an even more attractive idea, had the net filters with a visible counterparts can be applied on already opened web pages when uBlock is launched.

The best time to re-launch would be after a selfie has been generated.

**Comment by gorhill** [comment]
Idea discarded.
