### ISSUE TITLE
Add Option to Allow domain to icon

### ISSUE THREAD

**Issue by SHJordan** [uBlock-LLC/uBlock#220]
I see there is already a Ctrl+click option for the viewed website already, could you add a shortcut for domain like CTRL+SHIFT+CLICK ?

**Comment by kurtextrem** [comment]
Why Ctrl+Shift+click if "click" is enough?

**Comment by SHJordan** [comment]
click disable for all the domain? thats news to me, i first thought it would only disable the extension.

**Comment by gorhill** [comment]
@SHJordan Click creates a whitelist rule for the host name currently appearing in the address bar, i.e. uBlock will be disabled whenever the URL in the address bar matches that host name.

**Comment by SHJordan** [comment]
I see, oh well seems i've misunderstood that. You can close the issue then! Thank you for the brief explanation!
