### ISSUE TITLE
Blocked from (at least) some sites using Cloudfare - Signature hash

### ISSUE THREAD

**Issue by dazito** [uBlock-LLC/uBlock#221]
I just moved over to Opera 25 Dev and while I was browsing my usual websites I started to notice that some of them were blocking me.

Here's the message from CloudFare: 

Error 1010 Ray ID: 166d6xxxx930xxx
Access denied
What happened?
The owner of this website (replygif.net) has banned your access based on your browser's signature (166d6c93c79304a3-mh5).
CloudFlare Ray ID: 166d6cxxxx930xxx • Your IP: xx.xxx.xxx.150 • Performance & security by CloudFlare

If I disable uBlock and wait 10-15 minutes and try again I can access the website. If I turn on uBlock again I'll be blocked once again. So I presume it is something within uBlock that is causing this problem.

You can try on these two links:
http://replygif.net/i/1485.gif
http://simpleprogrammer.com/2014/08/11/negotiate-salary/

So if I've uBlock ON I'm blocked out from all websites using CloudFare... Please fix this or I'm forced to switch back to adblock plus or something...

**Comment by dazito** [comment]
Some more info:
http://www.wilderssecurity.com/threads/error-1010-access-denied.359397/

**Comment by gorhill** [comment]
What other extensions are you using, if any?

Also, which filter lists are you using?

**Comment by dazito** [comment]
Outlook Notifier, Referrer Control,Translator and uBlock

**Comment by gorhill** [comment]
I think it's more likely the problem is caused by the use of _Referrer Control_.

**Comment by gorhill** [comment]
Just to be clear: uBlock will typically block the same as ABP with the same filter lists selected, so the problem will still be there if using ABP with the same filter lists. The CloudFare message occurs usually when first-party cookies are blocked and/or referrer is blanked or assign nonsensical values.

**Comment by dazito** [comment]
You seem to be right or in the correct path to this problem. I changed the referrer to include the http:// and until now no blocks so far. (I was just using www.myreferrer.com without the http:// part)

But the strange thing (before changing my custom referrer) I had this results:

Blocked if I've uBlock active and Referrer Control not active.
Blocked if I've uBlock not active and Referrer Control active.

Blocked if I've both active.

**Comment by gorhill** [comment]
The heuristic used by CloudFare is obscure -- for obvious reasons. As said factors involved I am sure (seen through HTTPSB's use) are 1st-party cookie blocking, strange referrers, but I believe reloading the same web page (they are trying to detect DDoS) is also a factor. There is also what appears to be a cool down period, after which a user will be allowed again to load the page. This often lead to erroneous cause-effect conclusions.

**Comment by gorhill** [comment]
As discussed, false positives when cookies and/or referrer are blocked. uBlock doesn't block these, in order to ensure compatibility with extensions which do (HTTPSB, privacy badger, etc.)
