### ISSUE TITLE
Notify Crowdin translators about changed strings

### ISSUE THREAD

**Issue by Debeet** [uBlock-LLC/uBlock#222]
[Example commit](https://github.com/gorhill/uBlock/commit/70533b93fe44a171f463abbd811c08ca6bf87311)

Unless translators look at commits often they have no way of knowing if a certain string was changed or not. Old translations are used instead.

Translators should be notified about changes somehow on Crowdin, if that's possible. If not then maybe deleting translations for changed strings is an option?

**Comment by Mikey1993** [comment]
It's already happening via an email from Crowdin.

**Comment by Debeet** [comment]
E-mails from Crowdin are related to **new** strings, not the updated ones.

**Comment by Mikey1993** [comment]
Gorhill has been sending an update emails via Crowdin to all the translators.
I think it's sufficient, at least for me.

**Comment by Debeet** [comment]
Once again, these emails notify translators only about new strings. These don't cover the ones that have been updated. There is no way to tell if a certain string was changed unless you watch commits on GitHub.

**Comment by gorhill** [comment]
Yes, sorry. Sometimes the changes are so trivial I don't want to bother contributors and I chose to not send an email.

**Comment by Debeet** [comment]
There's [history on making non-trivial changes](https://github.com/gorhill/uBlock/commit/8accb1f34790233c6b82db1a76b031013d86dbda) to strings as well so notifying translators about these would be great :)
