### ISSUE TITLE
Chrome store: "support for the adblock: links so list can be added automatically"

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#224]

**Comment by gorhill** [comment]
For the record, I plan to implement this the follow way: the ability to import a filter lists through a mouse click will be available **only on [this page](https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web)**.

This is to prevent having to install a special handler in every single page visited, as most pages won't have any such link to filter lists. The special handler will be injected only for the above page.

**Comment by chrisaljoudi** [comment]
@gorhill worth looking at: [navigator.registerProtocolHandler](https://developer.mozilla.org/en-US/docs/Web/API/navigator.registerProtocolHandler).

**Comment by gorhill** [comment]
More work needed to enable support for Firefox, Safari.

**Comment by gorhill** [comment]
For translators:

![c](https://cloud.githubusercontent.com/assets/585534/6559983/f6bf41d6-c65c-11e4-8116-5962edbac211.png)

**Comment by chrisaljoudi** [comment]
@gorhill Safari should be set now. 476fd17555

**Comment by gorhill** [comment]
Feature available in [0.9.1.0](https://github.com/gorhill/uBlock/releases/tag/0.9.1.0).
