### ISSUE TITLE
Typo in commit https://github.com/gorhill/uBlock/commit/0b64dbf373fe98a313e38c683b981f6de432db30

### ISSUE THREAD

**Issue by Landpaddle** [uBlock-LLC/uBlock#225]
-    var unsafeUpdateBadge = function(tabId) {
-        chrome.tabs.get(tabId, safeUpdateBagde);
-    };

'Badge' is misspelled 'Bagde' here. Didn't have time to fork this morning so just submitted an issue.

**Comment by gorhill** [comment]
For reference, chromium dev's advice: https://code.google.com/p/chromium/issues/detail?id=410868#c8
