### ISSUE TITLE
Video playback does not work on nfl and nba sites.

### ISSUE THREAD

**Issue by blis5fool** [uBlock-LLC/uBlock#227]
Video playback does not work on NBA:
http://www.nba.com/video

and NFL:
http://www.nfl.com/big-play-highlights

For NFL, first video might play but the following video might not play. This may be because ads are served every other video.

**Comment by gorhill** [comment]
Looking into http://www.nba.com/video: The video won't play either with ABP and only _EasyList_, so the problem seems to be with _EasyList_.

**Comment by gorhill** [comment]
For http://www.nba.com/video, I found that using this exception:

```
@@||z.cdn.turner.com/*/ads/freewheel/*$object-subrequest
```

Fixes the problem. You should report the problem to _EasyList_ maintainers: http://forums.lanik.us/viewforum.php?f=64

**Comment by gorhill** [comment]
For http://www.nfl.com/big-play-highlights, it works with ABP. So problem is _Peter Lowe's_  list. I have to find the proper exception to circumvent whatever in _Peter Lowe's_ list blocks whatever is needed by the video player.

**Comment by gorhill** [comment]
Go to _"3rd-party filters"_ in uBlock's dashboard, there should be an update shown for _"uBlock filters"_. If, not, purge the cache for _"uBlock filters"_, ensure _"Auto update"_ is enabled, click _"Apply changes"_.

I put in the fix for _EasyList_, until the maintainers fix it.

**Comment by ryanbr** [comment]
I don't see "||z.cdn.turner.com/_/ads/freewheel/_" being hit it Easylist, from the sample pages provided

**Comment by gorhill** [comment]
~~Context? The videos are not working for you?~~ Never mind, I didn't realize who I was talking to. Let me see, I forgot which filter was hit in EasyList.

**Comment by ryanbr** [comment]
I'm referring to the site, I don't see the filter /ads/freewheel/\* being hit. Only tested in Firefox here..

**Comment by gorhill** [comment]
Yes, all work fine if I remove the workaround filter. I don't know what changed since then. At the time I definitely reproduced the problem experienced by the user. No longer an issue it appear.

**Comment by gorhill** [comment]
It is being hit using Chromium 37, but it doesn't prevent anymore the videos from playing properly:

![nba](https://cloud.githubusercontent.com/assets/585534/4436151/578fda7a-4769-11e4-95fc-0d0ac19b0941.png)

**Comment by gorhill** [comment]
Actually it works now because of your change in _EasyList_: https://hg.adblockplus.org/easylist/rev/abcfef2c4c82

**Comment by ryanbr** [comment]
Oh, okay is the nfl.com still affected?

**Comment by gorhill** [comment]
NFL was [because of Peter Lowe's list](https://github.com/gorhill/uBlock/issues/227#issuecomment-55429912), not because of EasyList.
