### ISSUE TITLE
Lists marked "may be obsolete"

### ISSUE THREAD

**Issue by wfdd** [uBlock-LLC/uBlock#229]
I assume this means they're outdated? Obsolete could be interpreted as being permanent, i.e. that the list is no longer necessary.

**Comment by gorhill** [comment]
English is not my first language, so I suppose I picked the wrong word... So "outdated" is your definitive suggestion?

**Comment by gorhill** [comment]
From various dictionaries, I see "out of date" is a common definition for "obsolete", so it doesn't look like the word is wrong.

**Comment by wfdd** [comment]
Well, outdated _could_ mean the same. But 'obsolete' makes me think it's about the list itself, while 'outdated' makes me think it means my local copy of the list. For instance, if my package manager says a certain package is outdated, I'd update it; if it says it's obsolete, I'd remove it, permanently.

However, considering uBlock's (probably) used by people who're not quite as tech-savvy as you or me are, I think something along the lines of 'new version might be available' is much less likely to be misinterpreted.

**Comment by gorhill** [comment]
Ok I will use "outdated", as internally this is really what happens: if the list is too old, it is labelled as such.
