### ISSUE TITLE
Opera requirements for acceptance in Opera store

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#23]
Library:

> I will need specific setting of uglyfy you use to minify yamd5.js because your results differs from mine (As a source I used version from master branch Jun 20, 2014)

Translation work:

> Please supply Summary and Description in other languages or remove them until they will be fully translated.

Build work:

> Remove ./assets/*.sh as these files are useless in production package4.

**Comment by tailHey** [comment]
Reste-t-il encore quelque chose à traduire/faire en particulier pour qu'Opera accepte de publier l'extension ? Je peux m'occuper de la traduction du résumé et de la description en Français s'il le faut ^^

**Comment by gorhill** [comment]
Oui, ils veulent aussi la description détaillée. J'imagine que ça peut être plus court que la version anglaise (ça n'a pas à être une traduction fidèle), mais ils n'ont pas acceptés que je reproduise seulement la description courte dans la description détaillée. J'ai créé des fichiers vides prêts à recevoir les descriptions détaillées.

**Comment by tailHey** [comment]
Je suppose que la description détaillée est déjà prête en Anglais ? Si tu le souhaites je peux en proposer une traduction (pas forcément fidèle, dans le sens où j'éviterais ce qui est trop technique pour pas embrouiller l'utilisateur), tu n'as qu'à me dire ce que je devrais translater !

**Comment by gorhill** [comment]
Il s'agit de juste décrire ce qui est important pour l'utilisateur sans vraiment avoir à reproduire fidèlement. J'ai créé ce fichier pour servir de référence pour traduction: https://github.com/gorhill/uBlock/blob/master/dist/DESCRIPTION-reference.

C'est juste mon avis, mais chacun est libre de traduire comme il veut, pourvu que ça aide l'utilisateur, et qu'il n'y ait pas d'erreurs techniques.

**Comment by tailHey** [comment]
J'ai fait ma traduction, faut-il attendre d'autres traductions ou pourra-t-on soumettre à nouveau à Opera ?

**Comment by gorhill** [comment]
Merci.

Idéalement, j'aimerais avoir les autres traductions, sinon ça compliquerait pas mal les choses de mon côté puisque j'aurais à créer et maintenir deux versions différentes, une pour Chrome store, et une autre pour Opera store. Je vais créer des "issues" pour les traductions manquantes, peut-être que ça va encourager le volontariat.

**Comment by tailHey** [comment]
Une bonne idée, espérons que les volontaires s'y mettent alors ! Peut-être ceux officiant déjà sur HTTPSB, comme moi ?

**Comment by gorhill** [comment]
> Peut-être ceux officiant déjà sur HTTPSB, comme moi ?

Espérons. C'est juste que je préfère que ça soit complètement volontaire, et si je leur demandais expressément, peut être qu'ils se sentiraient forcés, ce que je veux éviter.

**Comment by tailHey** [comment]
> Peut-être ceux officiant déjà sur HTTPSB, comme moi ?
> Espérons. C'est juste que je préfère que ça soit complètement volontaire, et si je leur demandais expressément, peut être qu'ils se sentiraient forcés, ce que je veux éviter.

Je comprends. Alors il faudrait adopter un ton informatif, parce que si ça se trouve, ils ne savent même pas que tu as forké ton propre travail en µBlock !

**Comment by gorhill** [comment]
Closing, because the extension was accepted in Opera store.
