### ISSUE TITLE
Why is %s not expanded? in "µBlock> Beginning to intercept net requests at %s"

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#231]
Hi. This is probably an issue with chromium(?) but can anyone please tell me why %s is not expanded when showing this:
`µBlock> Beginning to intercept net requests at %s`
![s](https://cloud.githubusercontent.com/assets/5661825/4265858/859bcaa2-3c63-11e4-80f9-399a7b56e1af.png)

Thank you in advance.

on chromium linux
Version 39.0.2145.4 (8f3c881c091a8eb8bc9df2ed45e11a4ed35e628a) (64-bit)

**Comment by ialexsilva** [comment]
duplicate? #207

**Comment by ghost** [comment]
oh ignore the red error, it seems to have gone away after the next git pull(and extension reload), which had only one commit (maybe it's just coincidence, or duplicate errors don't show up again?)
this commit: https://github.com/gorhill/uBlock/commit/1e464ccb4ab675f6457949bc5304c606780c215d

**Comment by ghost** [comment]
ok this explains it: https://github.com/gorhill/uBlock/issues/207#issuecomment-54388286
`but it looks like Chrome doesn't format the strings in their error collecting feature.`

**Comment by ghost** [comment]
actually the red error happens only on Update, as gorhill mentioned here:
https://github.com/gorhill/uBlock/issues/207#issuecomment-54388286

because httpswitchboard was blocking all these for me:

```
3:15:45 AM  xhr <a>     https://easylist-downloads.adblockplus.org/easylist.txt
3:15:45 AM  xhr <a>     https://easylist-downloads.adblockplus.org/easyprivacy.txt
3:15:45 AM  xhr <a>     http://mirror1.malwaredomains.com/files/immortal_domains.txt
3:15:45 AM  xhr <a>     http://mirror1.malwaredomains.com/files/justdomains
3:15:45 AM  xhr <a>     http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext
3:15:45 AM  xhr <a>     http://www.malwaredomainlist.com/hostslist/hosts.txt
```

(I'll add them manually to allowed)
