### ISSUE TITLE
Blocking video on vg.no

### ISSUE THREAD

**Issue by Herjar** [uBlock-LLC/uBlock#233]
With uBlock active the videos do not work on vg.no (Norwegian newspaper).
The audio will play, but no video. E.g.:
http://www.vg.no/nyheter/utenriks/simpson-karakter-kjemper-for-skotsk-uavhengighet/a/23296459/

I've noticed a similar issue somewhere else, but can't remember where right now.

**Comment by gorhill** [comment]
[oops, wrong issue.]

**Comment by gorhill** [comment]
I tried, and it worked correctly from here, but I had to enable 3rd-party cookies.

What filter lists do you have selected?

Also, browser version?

**Comment by Herjar** [comment]
Not sure I understood that second post, but I just use default ones I think + the "NOR: Norsk adblockliste".

I tried turning on one at a time and easylist is the one that stops it working. With just that enabled the video stops working. But I guess this is the list that stops most of the ads as well so I probably want to keep it enabled.

For cookies,do you mean "Content setting -> Allow local data."? That's what mine is set to, but the video does not work.

**Comment by gorhill** [comment]
Browser version?

**Comment by Herjar** [comment]
Chrome 39.02150.5 dev-m (64-bit)

**Comment by gorhill** [comment]
Probably a dup of #206. If so, you should have the same problem with ABP.

I opened an issue with Chromium devs re #206: http://code.google.com/p/chromium/issues/detail?id=410382

**Comment by Herjar** [comment]
Yea I get the same problem with APB. Seems I have to wait for chrome devs to fix it then.

Would it be possible to have a whitelist for ads? Not the entire domain, just to see which ads are blocked and then choose some to whitelist.

**Comment by gorhill** [comment]
Closing as dup of #206.

Re. whitelist for ads, you may enter a new issue if you want, but unlikely I would address that anything time soon, if ever. Currently you can create custom filters, including exception filters, and use the request logs to find out what was blocked.

**Comment by gorhill** [comment]
I decided to code a workaround to the Chromium issue. Available in 0.6.3.3.
