### ISSUE TITLE
flickr does not load the page view

### ISSUE THREAD

**Issue by your4ox** [uBlock-LLC/uBlock#235]
https://www.flickr.com/photos/theempress/15084997550/in/explore-2014-09-17
![2014-09-18_153914](https://cloud.githubusercontent.com/assets/8820030/4319669/8d54b690-3f2f-11e4-92a9-0bb1bc695066.gif)

**Comment by gorhill** [comment]
Works fine from here.
- Browser version
- Filter lists selected

**Comment by your4ox** [comment]
Chromium version 39.0.2153.0
µBlock 0.6.2.0

Filters selected:
µBlock filters‎
 Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com): 
 Peter Lowe’s Ad server list‎ (yoyo.org):
 EasyPrivacy‎ (adblockplus.org)
 Malware Domain List‎ (malwaredomainlist.com):
 Malware domains‎ (malwaredomains.com): 
 Malware domains (long-lived)‎ (malwaredomains.com): 

 RUS: RU AdList (Дополнительная региональная подписка)‎ (adblockplus.org): 4 173 
Пользовательские
 https://easylist-downloads.adblockplus.org/easylist_noadult.txt‎: 17 340 используется из 17 376

**Comment by gorhill** [comment]
Ok, I can reproduce with your selection of lists. Investigating.

**Comment by your4ox** [comment]
Sorry. Does not work because of a subscription RU AdList

**Comment by gorhill** [comment]
Found the problem: there is this filter in RU Adlist:

```
||info^$third-party,script
```

I need to fix uBlock's parser, I wasn't expecting that only the suffix of a hostname could be used.

**Comment by gorhill** [comment]
I took the opportunity to review some older code as part of this fix, and re-arrange some code which was meaningful to HTTP Switchboard, but which is not needed for uBlock. This allowed to remove some overhead from the evaluation of pure hostname filters.

As usual, when the changes are meaningful enough to warrant a new benchmark, and to keep track of performance regression:

```
µBlock> onBeforeRequest: 0.128 ms (19054 samples)
µBlock> onBeforeRequest: 0.128 ms (19211 samples)
µBlock> onBeforeRequest: 0.128 ms (19545 samples)
µBlock> onBeforeRequest: 0.127 ms (19840 samples)
µBlock> onBeforeRequest: 0.127 ms (20000 samples)
µBlock> onBeforeRequest: 0.128 ms (20066 samples)
µBlock> onBeforeRequest: 0.128 ms (20215 samples)
µBlock> onBeforeRequest: 0.128 ms (20369 samples)
µBlock> onBeforeRequest: 0.128 ms (20431 samples)
µBlock> onBeforeRequest: 0.128 ms (20583 samples)
```

**Comment by gorhill** [comment]
For the record, for users to understand how this bug could affect them, I searched through the filter lists, and there were only two occurrences of these filters (both in RU Adlist) which were improperly evaluated by uBlock. I have this fixed locally.
