### ISSUE TITLE
Element Hider can't select anything on Wolfram Alpha

### ISSUE THREAD

**Issue by spaghetti2514** [uBlock-LLC/uBlock#237]
Attempting to use the element hider on a Wolfram Alpha results page darkens the page, but hovering over anything does not highlight it and clicking does nothing

The following error is printed to the console when the element hider is activated:
`Error: Invalid value for <path> attribute d="" [element-picker.js:313]`
Using master pulled minutes before making this bug report

This is possibly a duplicate of #99, but behavior seems different

**Comment by gorhill** [comment]
Can you give me a specific URL?

**Comment by spaghetti2514** [comment]
http://www.wolframalpha.com/input/?i=2%2B2

**Comment by gorhill** [comment]
I need to set explicitly `pointer-events` on the `<svg>` element, the web page sets `pointer-events` to `none` in its own CSS.

The error message `Error: Invalid value ...` is benign, it's actually an open issue in Chromium somewhere, an empty path is a valid path.
