### ISSUE TITLE
Net filtering: not worth to use bits of domain name in category hash [performance]

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#238]

**Comment by gorhill** [comment]
Results:

```
µBlock> onBeforeRequest: 0.108 ms (20488 samples)
µBlock> onBeforeRequest: 0.108 ms (20702 samples)
µBlock> onBeforeRequest: 0.108 ms (21068 samples)
µBlock> onBeforeRequest: 0.107 ms (21335 samples)
µBlock> onBeforeRequest: 0.107 ms (21487 samples)
µBlock> onBeforeRequest: 0.107 ms (21634 samples)
µBlock> onBeforeRequest: 0.108 ms (21808 samples)
µBlock> onBeforeRequest: 0.108 ms (21867 samples)
µBlock> onBeforeRequest: 0.108 ms (21984 samples)
µBlock> onBeforeRequest: 0.108 ms (22114 samples)
```

**Comment by gorhill** [comment]
Actually, the `SpecificParty` buckets are not even needed: the logic for that one is in the filters, as opposed to 1st-, 3rd-party, and types. Removing the `SpecificParty` buckets:

```
µBlock> onBeforeRequest: 0.089 ms (19684 samples)
µBlock> onBeforeRequest: 0.089 ms (20017 samples)
µBlock> onBeforeRequest: 0.088 ms (20405 samples)
µBlock> onBeforeRequest: 0.088 ms (20674 samples)
µBlock> onBeforeRequest: 0.088 ms (21033 samples)
µBlock> onBeforeRequest: 0.088 ms (21336 samples)
µBlock> onBeforeRequest: 0.088 ms (21491 samples)
µBlock> onBeforeRequest: 0.088 ms (21685 samples)
µBlock> onBeforeRequest: 0.088 ms (21816 samples)
µBlock> onBeforeRequest: 0.088 ms (21965 samples) 
```

**Comment by ghost** [comment]
Wow! Those figures are only half of the time compared with the ones you published [here](https://github.com/gorhill/uBlock/wiki/%C2%B5Block-vs.-ABP:-efficiency-compared#added-cpu-overhead-to-each-net-request). That's fantastic - µBlock's lead over ABP is getting bigger and bigger! Congratulations, Raymond!

**Comment by gorhill** [comment]
Thanks.

The case here is a good illustration of what I said a while ago in the [last paragraph in there](https://github.com/gorhill/httpswitchboard/wiki/Net-request-filtering-efficiency:-HTTP-Switchboard-vs.-Adblock-Plus) (many other things in the article are outdated though, or even plain wrong as per findings of more benchmarking a while ago).
