### ISSUE TITLE
images blocked...

### ISSUE THREAD

**Issue by ialexsilva** [uBlock-LLC/uBlock#239]
Page:https://likestore.com.br/store/showcase/canaldootario##
blocking images of this site:s3-sa-east-1.amazonaws.com/
Chrome: 37.0.2062.120 m (64-bit)
Default List + Anti-Adblock Killer

**Comment by gorhill** [comment]
I see them fine. As usual:
- Browser version
- Filter lists

**Comment by Baegus** [comment]
Anti-Adblock Killer is hiding them for me on Chrome 39.0.2159.4 dev-m 64-bit

**Comment by ialexsilva** [comment]
Yes is Anti-Adblock Killer =/

**Comment by gorhill** [comment]
Yes, confirmed it is [Anti-Adblock Killer | Reek](https://github.com/reek/anti-adblock-killer#anti-adblock-killer--reek):

```
||s3-sa-east-1.amazonaws.com^$third-party
```

Issue will need to be brought to the maintainer of the list. I will let you deal with this.
