### ISSUE TITLE
Individual Resources No Longer Blocked

### ISSUE THREAD

**Issue by spaghetti2514** [uBlock-LLC/uBlock#240]
Commit 102dc8b596474a98228dbc2817e53466097b3a3d broke blocking of individual resources

To reproduce:
Checkout 987e26e41c4b0e619543e4cda321cd078307feb8
Add filter entry `www.zombo.com/inrozxa.swf`
Visit www.zombo.com
Page should be blank, as the swf content was properly blocked

Checkout 102dc8b596474a98228dbc2817e53466097b3a3d or later
Visit www.zombo.com with the same filter entry in place
swf file is not blocked

Have confirmed with a javascript file on a less accessible site as well

**Comment by gorhill** [comment]
You're right. I couldn't reproduce at first because I had more local changes and the problem doesn't show with these. Investigating.

**Comment by gorhill** [comment]
Oops, the order of some statements were wrong.

In general, I advise against using "live" version of the repo, as it happens I use the repo as a backup device when I make a lot of changes, i.e. I can't guarantee the extension will always be in a good state, but in truth I am actually happy to see it is used, as appreciate the testing before even a release candidate.
