### ISSUE TITLE
Create a basic web page to test various net and cosmetic filters at a glance

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#241]
Something simple, but a quick test which for example would have found immediately #240.

I picture a simple web page with a simple set of tiles, some which are a match to filters, some which are not a match. Not sure where I could host it though (maybe github.io, I never looked into this).

**Comment by spaghetti2514** [comment]
Github Help has straightforward instructions on setting up Pages for your repo, and that does seem like a good choice for this

https://help.github.com/articles/creating-project-pages-manually

**Comment by gorhill** [comment]
This is a start: http://raymondhill.net/ublock/tests.html
