### ISSUE TITLE
cracked.com videos don't play

### ISSUE THREAD

**Issue by arcaneAgilmente** [uBlock-LLC/uBlock#243]
I'm using both ublock and httpswitchboard with the following filter lists enabled: http://i.imgur.com/akK6wlX.png

Disabling ublock on cracked.com allows videos to play but then social buttons come back because httpswitchboard is missing Fanboy's social blocking list.

I've tried using the logging features of both extensions to try and figure out how to fix this issue but I haven't had any luck.

**Comment by gorhill** [comment]
Can you give me a specific URL I can use a test case where the problem occurs?

**Comment by gorhill** [comment]
Ok, I tried this one: http://www.cracked.com/video_19098_the-only-way-to-make-celeb-nude-leak-scandal-fair.html and I get the same problem with ABP, so this is likely an _EasyList_ issue.

**Edit:** Never mind, even without a blocker the video doesn't work: the page tries to download http://www.cracked.com/ui/shared/scripts/jwplayer/skins/billy.xml, and this thing doesn't exists on their server.

**Edit 2:** Err, my Flash is disabled, I have to try again all this.

**Comment by gorhill** [comment]
Ok, it's hpHosts, it blocks `cdn-i.dmdentertainment.com`, which is needed by the site. I will add it to uBlock's filters.
