### ISSUE TITLE
I have to update the lists, even though I shouldn't

### ISSUE THREAD

**Issue by JBey4you** [uBlock-LLC/uBlock#246]
In the uBlock settings, I chose to have auto-updates enabled. Even though, sometimes, uBlock asks me to update the lists manually. Any idea why?

![capture d ecran 2014-09-22 a 20 15 55](https://cloud.githubusercontent.com/assets/7979756/4361515/d1ed5bc4-4284-11e4-8dfc-ba0ca287fcaa.jpg)

**Comment by gorhill** [comment]
Remote server issues. Today I noticed EasyList server was not responding. So uBlock will give up waiting for an answer, and the list is still marked as obsolete. It will try again later, etc.

**Comment by gorhill** [comment]
Try it manually: https://easylist-downloads.adblockplus.org/easylist.txt.

I could get a response, but it seemed after uBlock's timeout period. I suppose EasyList server is more busy during some part of the day, leading to the slowness.

**Comment by JBey4you** [comment]
Since we are talking about the settings, it's not possible to remove a list added manually, right? The Anti-Adblock Killer for example, if I want to remove it, what should I do (if I can do something of course)?

**Comment by gorhill** [comment]
Remove the entry from the textarea, click _Apply_.
