### ISSUE TITLE
uBlock sometimes breaks since 6.3.3 on Chrome 39

### ISSUE THREAD

**Issue by HitomiTenshi** [uBlock-LLC/uBlock#247]
Chrome Build 39.0.2166.2 dev-m (64-bit)

Settings don't seem to load and blocking doesn't actually happen anymore. Restarting Chrome multiple times helped fixing this, but that doesn't work every time.

Happened on me when I click on links in applications that boot chrome up and uBlock doesn't initialize on time.

![](http://puu.sh/bL8dg/3410f0267a.png)

![](http://puu.sh/bL8wk/705f6e09c9.png)

**Comment by gorhill** [comment]
~~What browser/version?~~

Oops, it's in the title. Sorry.

What build of Chrome 39 are you using?

Edit: I ask because I wonder if this is related to this: https://code.google.com/p/chromium/issues/detail?id=415189#c12

**Comment by gorhill** [comment]
Crap, I can reproduce in qemu. Weird, if I use my local build, it works fine, but with the version from Chrome store, it's broken.

**Comment by gorhill** [comment]
Issue went away when I forced a reload of the extension.

If I disable _"Predict network actions to improve page load performance"_ though, extension doesn't work well. Is this your setting?

**Comment by HitomiTenshi** [comment]
Yeah I disabled that feature. Okay I'll reload, hope this is going to be fixed.

**Comment by chrisgeo** [comment]
Actually, after restarting Chrome, it looks like it's the issue you mentioned.

**Comment by HitomiTenshi** [comment]
> Actually, after restarting Chrome, it looks like it's the issue you mentioned.

I have to agree on that, it seems to be a chrome issue. Happens only if you disable the "predict network actions" feature in chrome.

**Comment by ghost** [comment]
Do a clean install of uBlock and try Chromium 39.0.2171.0, it fixed my problems.

https://storage.googleapis.com/chromium-browser-continuous/Win_x64/296935/chrome-win32.zip

**Comment by gorhill** [comment]
Looks like this was a chrome dev version issue.
