### ISSUE TITLE
uBlock has crashed

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#254]
Screenshot taken from Chromium Console:

![untitled](https://cloud.githubusercontent.com/assets/8661552/4424602/074c9ed2-45a1-11e4-9065-e0cf326e0823.png)

Chromium 39.0.2170.0 and uBlock 0.6.4.0. uBlock 0.6.3.3 didn't have this issue.

**Comment by gorhill** [comment]
What URL should I go to to see the issue?

**Comment by ghost** [comment]
Happens with many different URL.

Examples:

www.suomi24.fi
www.html5test.com

I try to find more Console screenshots for you. It just crashed again but forgot to take a screenshot.

**Comment by gorhill** [comment]
I didn't see any problem from here (using Chromium 37).

When you say "crash", you mean "Awww snap"?

If so, this is an issue for Chromium devs, _especially_ if this happens on an unstable version of Chromium. Javascript does not crash, is not supposed to crash.

**Comment by ghost** [comment]
Noup, system tray balloon appears which says that uBlock has crashed. uBlock 0.6.3.3 didn't have this issue. You have to wait for a while before uBlock crashes, keep Console window open at the same time.

**Comment by gorhill** [comment]
> tray balloon appears which says that uBlock has crashed

Yes, that's the equivalent of "Awww snap" for extensions -- since their page is not visible. I will see what I can find with version 39 of Chrome, but this is at this point an issue for Chromium devs. One way to find more info is to start the browser from the console, when it crashes, more info should be dumped at the console.

**Comment by ghost** [comment]
How do I start browser from the Console?

**Comment by gorhill** [comment]
I don't know about Windows. For Linux just type `chromium-browser` in a terminal.

**Comment by gorhill** [comment]
I tried using Chrome 39.0.2166.2 dev-m (the most up to date version I could get), and no issue. Very likely related to using a bleeding edge version of Chromium (39.0.2170.0). A crash definitely needs to be reported ASAP to Chromium devs, so they can more easily identify which commit is responsible for the regression.

**Comment by gorhill** [comment]
Please report the problem to Chromium devs, there is nothing I can do with this: Whenever a crash occurs, this is an issue for Chromium developers.

**Comment by ghost** [comment]
Done:
https://code.google.com/p/chromium/issues/detail?id=418174

**Comment by gorhill** [comment]
By the way, I don't understand the content of your log. When there is a crash, it looks more like what is seen there: https://github.com/gorhill/uBlock/issues/159

**Comment by ghost** [comment]
I noticed the same thing, but I have no idea how to get that unfortunately.

**Comment by ghost** [comment]
Here's a link for Chromium 39.0.2171.0 so you can test it.

https://storage.googleapis.com/chromium-browser-continuous/Win_x64/296928/chrome-win32.zip

**Comment by gorhill** [comment]
Apparently, disabling hardware acceleration "un-broke" uBlock, as reported in #255. Maybe that would work for you as well.

**Comment by ghost** [comment]
Interesting why it didn't crash 0.6.3.3.

**Comment by gorhill** [comment]
New version of Font Awesome?

https://github.com/gorhill/uBlock/commit/33df6bad0311c86083adb524b987d7616a31ae60

**Comment by gorhill** [comment]
Just to be sure I understand, turning off harware acceleration fixed the problem for you?

**Comment by ghost** [comment]
Weird things are happening, I removed uBlock and re-installed, also downloaded 39.0.2171.0 and uBlock does not crash anymore, I didn't disable hardware acceleration and it's still working. I might close that Chromium issue which I posted.
