### ISSUE TITLE
Shortcut

### ISSUE THREAD

**Issue by Havokdan** [uBlock-LLC/uBlock#256]
You can assign a shortcut to activate the element hinding? ESC already out of the way, like to have a shortcut.

**Comment by Betsy25** [comment]
+1

**Comment by AdKiller** [comment]
+100

Pretty please...

**Comment by dromer** [comment]
Yes!

Feeling more frustrated with this every day.

**Comment by AdKiller** [comment]
bump

**Comment by foss-** [comment]
+1
I am amazed, this has only 4 participants.

**Comment by Csokis** [comment]
+1

**Comment by jackklika** [comment]
Please!

**Comment by Dachu23** [comment]
+1 
(Please!)

**Comment by Betsy25** [comment]
> +1
(Please!)

This project is dead. It's [https://github.com/gorhill/uBlock](https://github.com/gorhill/uBlock) that you need.

**Comment by foss-** [comment]
https://github.com/gorhill/uBlock/issues/1307
https://github.com/gorhill/uBlock/issues/2224

**Comment by harl** [comment]
Can you please create a global reference to the command/call used to start the element picking process (somewhere around that gotoPick > launchElementPicker function in popup.js) ?
We should then be able to go from there and create a keyboard shortcut for it ourselves.

**Comment by caribbean-apple** [comment]
+1
