### ISSUE TITLE
Small icons (16px and 19px) are blurry

### ISSUE THREAD

**Issue by CoolOppo** [uBlock-LLC/uBlock#262]
###### A small aside

_I am making this a separate issue from #258 because this is a separate thing from having all-new icons. This one is outside the realm of subjectivism, so hopefully this is something we can all agree on. The changes I made in #258 did seem a bit unnecessary; I just thought I would give it a go._

---

The 16px and 19px icons are pretty blurry, and, luckily, there's an easy fix. The icons need proper [hinting](https://wikipedia.org/wiki/Font_hinting)!

Here's a comparison between the current icon its properly hinted counterpart. I tried my best to remake the current icon, and I did use the same font. In addition, the scaled images are [scaled using nearest-neighbor](https://en.wikipedia.org/wiki/Image_scaling#Algorithms) so that you can see them unadulterated!
### Current 19px Icon (Scaled)

![Current 19px Icon](http://i.imgur.com/rHB7jPY.png)
### Proposed 19px Icon (Scaled)

![Proposed 19px Icon](http://i.imgur.com/LMiuQFX.png)
### Current 19px Icon (Actual Size)

![](http://i.imgur.com/ZM354UC.png)
### Proposed 19px Icon (Actual Size)

![](http://i.imgur.com/DPUMnvQ.png)

**Comment by gorhill** [comment]
What I don't like with the one you suggest is that it's off centered. But really, the thing is I don't even see an issue here, if you look at the badge over the icon, it looks similar when zoomed it, and yet it look just fine.

![a](https://cloud.githubusercontent.com/assets/585534/4542752/1524f7c0-4e25-11e4-9cb2-d1539a175246.png)

![a](https://cloud.githubusercontent.com/assets/585534/4542775/5d117414-4e25-11e4-9383-a051d8b888a6.png)

**Comment by CoolOppo** [comment]
It is not off-center; it is hinted.

# [Font Hinting](https://wikipedia.org/wiki/Font_hinting)
