### ISSUE TITLE
Add AdGuard subscriptions?

### ISSUE THREAD

**Issue by cbuijs** [uBlock-LLC/uBlock#263]
Not sure if it is allowed or not, but maybe start using or add the AdGuard subscriptions as well, or have them as an option?

http://adguard.com/en/filters.html

They seem to be more manicured and look a bit more clean/better then easylist stuff. But not a lot.

**Comment by gorhill** [comment]
I don't think it is a good idea, there are enough lists in there already, to help most people get started. Adding more lists with duplicated purpose will just lead to UI bloat.

AdGuard's list can always be added as custom lists. But they have syntax extensions which are unsupported (examples: `$$script`, `jsinject`, `urlblock`, `jscript` etc.). This would need reverse engineering as I can't find doc about these.

It appears they extended the syntax to be able to inject javascript from the lists, which really sounds like a bad idea security-/privacy-wise. As far as I can understand, this allows any list author to design a list which could inject arbitrary javascript in your pages, through AdGuard, and there is no guarantee that whatever injected javascript is not malicious.

Vaguely assessing something as "more manicured" means nothing without many specific examples of where it is better, and also without looking where it might be worst.

And to be honest, I am unable to trust AdGuard so far given what I have observed, so I just can't include their lists in uBlock.

**Comment by cbuijs** [comment]
Makes sense and is fair. I was just wondering as the quality of the lists looked to be better. But if they deviate that much (didn't see that), I think it make no sense either. Sorry for putting this one up! :-).
