### ISSUE TITLE
µBlock 0.6.6.0-rc.0 is phenomenal (Not an issue)

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#264]
As the title says, phenomenal work gorhill.

**Comment by kurtextrem** [comment]
How much is the "page load" decreased with this on?

**Comment by ferronrsmith** [comment]
if you use ublock is it necessary to have disconnect also or can I remove it ?

**Comment by Mikey1993** [comment]
@ferronrsmith Nothing is a necessity for uBlock to "work".

**Comment by gorhill** [comment]
@kurtextrem I don't know really. Not pulling and waiting for resources from the network will surely contribute to reduce page load time (and bandwidth), that's just what I can tell. I suppose on bloated page this won't even be noticeable.

@ferronrsmith Keep it. To find out whether it's worth keeping your other blocker, try a diff of benchmark data to find out what is not blocked by one but blocked by the other. Here is what I get for uBlock/Disconnect with [latest benchmark](https://github.com/gorhill/uBlock/wiki/%C2%B5Block-and-others:-Blocking-ads,-trackers,-malwares) (which I need to update once 0.6.6.0 is out): https://www.diffchecker.com/y5gj3ed5. The diff shows what was **not** blocked.

As you can see, uBlock blocked things Disconnect didn't, and Disconnect blocked things uBlock didn't. Selecting _"Fanboy's Anti-Facebook"_ in uBlock will take care of `facebook.com/net` that was taken care by Disconnect. We can see uBlock "blocked" `ajax.googleapis.com` (not really block, it's the local mirroring), whereas these were not blocked by Disconnect. Etc.

The _"206 lines added. 91 lines deleted"_ at the top means uBlock blocked 206 things that Disconnect didn't block, and Disconnect blocked 91 things that uBlock didn't block.

Maybe I will take time today to create these diffs for reference. One thing I expect this will show is that keeping ABP with uBlock is pointless.

**Update:** uBlock/ABP: https://www.diffchecker.com/4c5aox70. I have to say I was surprised to find out `googletagservices.com` is **not** blocked by ABP-EasyList-EasyPrivacy. This was taken care in uBlock by local mirroring. Also, `google-analytics.com` is **not** blocked by ABP-EasyList-EasyPrivacy. This is taken care by _"Peter Lowe's"_ in uBlock.

**Comment by ghost** [comment]
@ferronrsmith Page loading time has decreased a lot, there's a huge difference between the last Stable version of uBlock and this RC0 version. At least my Chromium opens pages a lot faster.

Great job indeed gorhill.

I don't recommend Disconnect, even Chrome Web Store starts to block it in the future:

http://forum.piriform.com/index.php?showtopic=41701

**Comment by ferronrsmith** [comment]
@gorhill and @YouTubeCenterBugReporter thanks for the insight, very good answers. Well after removing ablock plus & disconnect my browser feels much lighter and pages are loading faster. Thanks @gorhill great tool

**Comment by gorhill** [comment]
@ferronrsmith Actually, I need to correct my earlier "keep it". If I use a diff of uBlock (gorhill)/Disconnect, suddenly this shows there is no point keeping Disconnect: https://www.diffchecker.com/cc8o7ymk.

"uBlock (gorhill)" is uBlock with my [personal selection of lists](https://github.com/gorhill/uBlock/wiki/Filter-lists:-gorhill). Frankly these extra lists do not cause much site breakage in my experience. I know people with absolutely zero tolerance for site breakage, and yet they find these more aggressive settings all fine.

**Comment by harshanvn** [comment]
Great Idea with Local Mirroring concept!
I have a question regarding how it works with below scenarios -
          - How often the resources cached with local mirroring are flushed? I mean if the website offers an updated version of the resource, shouldn't user be downloading the latest resource?
          - Would it add any benefit if a user browses under Incognito mode? Would the resources be still cached?

Thanks!!

**Comment by gorhill** [comment]
@harshanvn Currently they are flushed when the cumulated size reaches 6MB, then least recently used resources are flushed until 5MB is reached. I have a TTL (time-to-live) parameter in there, but not used yet. I have to study more about this (hence the _experimental_). Note that local mirroring targets resources which are deemed reasonably immutable. So when querying `ajax.googleapis.com` for jquery 1.7.1, it's safe to assume the result won't change, ever. Re. incognito, no special treatment, so yes, what would normally cache in non-incognito still will be cached (or else one would actually end up being _less_ incognito from the external internet point-of-view, i.e. you IP would show up in more server logs).

**Comment by gorhill** [comment]
I ran a new benchmark with uBlock 0.6.6.0-rc.0 and ABP 1.8.5 with the same lists (except Peter Lowe's because there is no easy convenient way to install it in Adblock Plus -- so I assume users are likely to not bother).

Here is the resulting diff: https://www.diffchecker.com/5z91i47m

In red what ABP blocked which was not blocked by uBlock.
In green what uBlock blocked which was not blocked by ABP.

I suspect the only two requests not blocked by uBlock which were blocked by ABP is just the result of the page content changing between the time I benchmarked uBlock and ABP.

Filter lists:
- ABP: Out of box settings + EasyPrivacy, Malware domains, Fanboy's Social Blocking List, Anti-ThirdpartySocial‎ + "Acceptable ads" disabled
- uBlock: Out of box settings + Anti-ThirdpartySocial‎ + Local mirroring enabled and primed (as it would be through normal use).

What local mirroring accomplished in the above benchmark... Prevented connections to:
- `2mdn.net`
- `ajax.googleapis.com`
- `cloudflare.com`
- `fonts.googleapis.com`
- `googletagservices.com`
- `gstatic.com`
- `janrain.com`
- `jquery.com`
- `twitter.com`

And since the remote resources were available locally, preventing the connection didn't cause page breakage.

**Comment by kurtextrem** [comment]
I wonder how that will work out with "jquery-latest" and ajax.googleapis.com/ajax/libs/jquery/2/jquery.min.js (= loads the latest 2.x.x version available). But nevertheless great feature. Really looking forward to it.

**Comment by ghost** [comment]
That comparison was impressive, very interesting to see how adblocker's are blocking stuff and how much they let ads through. Keep up your great work gorhill.
