### ISSUE TITLE
Element Picker not working

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#265]
Hi,
The picker mode on  http://www.jeuxvideo.com doesn't work
I wanted to hide the cookie message on this website but when I clicked on the button to use the picker mode nothing happened.
Everything works fine with the others website. This is the only one that I have an issue with.
(I'm using chromium 37. I tried with chromium 40 and same problem).

Thanks.

**Comment by gorhill** [comment]
I can reproduce. I need to investigate why.

**Comment by gorhill** [comment]
Ok, there is an element with id `global` on the page. I had no idea the browser allowed an element to be used directly using their id name as a variable in the global context.
