### ISSUE TITLE
Element picker seems to inherit some style rules (not RTL languages friendly)

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#266]
Element picker seems to behave wrongly when using Hebrew (RTL language) Chrome version.

<h3>Scenario 1:</h3>

On <b>RTL/Hebrew</b> pages, such as Google.co.il, Element picker shows the "Cosmetic filters Click, Ctrl-click" text (seems like it needs only a right margin of 1em without the left margin to look as it should), and the rules that follow not right.

Pic:
https://i.imgur.com/HSWpWFD.png

<h3>Scenario 2:</h3>

On <b>LTR/English</b> pages, such as edition.cnn.com, Element picker shows <b>only</b> the "Cosmetic filters Click, Ctrl-click" text not right (the rules start with hashtag properly).

Pic:
https://i.imgur.com/LpLOWIF.png

**Comment by Mikey1993** [comment]
When repeating the first scenario when having the browser set to English (Instead of Hebrew), it behaves the same, which probably means that the Element Picker inherits some CSS rules from the page, and not the chrome user based language.

**Comment by gorhill** [comment]
Working on it. Good point about the page, make sense.

**Comment by gorhill** [comment]
I think I've got it right, if you can confirm (I checked that all is fine as before for LTR languages). Using the same examples you posted:

![a](https://cloud.githubusercontent.com/assets/585534/4516048/20063bf6-4bdf-11e4-8ce9-2884404ebbd2.png)

![b](https://cloud.githubusercontent.com/assets/585534/4516049/322a489a-4bdf-11e4-891a-869f8020511d.png)

Edit: Actually, I've moved the buttons back to the right side, given that the textarea is always LTR.

**Comment by Mikey1993** [comment]
IMO, the buttons on the textarea should always be on the <b>right</b> side, at the same order for all languages (from LTR): Create, Pick, Quit

I also think that it's better, if the "Cosmetic filters Click, Ctrl-click" (and all the headers) would be displayed as it should, but from LTR (Like in Scenario 1, but with a right padding, instead of the left one)
+
the rules should be always from LTR (because the id's, classes, URIs and etc will always be in English)

All in all, I think the page needs to be LTR, but should only display the translated text without any position change.

What do you think?

**Comment by gorhill** [comment]
Ok, corrected as suggested:

![a](https://cloud.githubusercontent.com/assets/585534/4516309/7c8222ae-4bef-11e4-8ac6-e8fdab71006e.png)

![b](https://cloud.githubusercontent.com/assets/585534/4516310/806cdb84-4bef-11e4-9160-caa672415b2c.png)

**Comment by Mikey1993** [comment]
This is almost perfect!
I also think that the buttons should just do shift right by 1 place so that the Orange button (Create), would be the most left in the pack :)

**Comment by gorhill** [comment]
> Orange button (Create), would be the most left in the pack

Ok done, so I will check in the fix. Thanks for the help.
