### ISSUE TITLE
"Enable Context Menu" isn't intuitive to understand

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#267]
It's not common to enable such feature as it's enabled on default on ABP, so I think that the majority of users won't understand that the "Block Element" is enabled by the following option:
"Make use of context menu where appropriate"
up untill they enable it (or read your Wiki)

Questions that will rise by users:
1) What is the context menu at all??
2) What do you mean "where appropriate"?
3) What will be enabled by this checkbox and where do I see it?
4) Voodoo?

I think it's better to change it to something like:
"Enable blocking elements on a page via right click context menu"

Or/and add an explenation of the setting like it's done with the question mark on some settings.

All in all, I feel that this setting (Only the "block element" in the context menu, not ALL the other following features that will fall under this setting of course) should be enabled by default for all users as it is currently with all the other ad blockers out there.

Makes sense?

**Comment by SW1FT** [comment]
I agree and also think it should be enabled by default.

**Comment by gorhill** [comment]
This comes from HTTPSB. Not everybody were happy with the context menu being populated by the extension. Anyway, I turned the default to enabled.

**Comment by Mikey1993** [comment]
What is your stand about changing the text of the setting in the dashboard and providing more info about it?

**Comment by gorhill** [comment]
@Mikey1993 It's just that I want the text to still be valid if ever I add more stuff in the context menu. If I make the text specifically for "block element", than adding more stuff in the context menu will force me to revisit the text, something I am trying to avoid. Having to update `messages.json` is one of the tedious task in this project, so I try to minimize the need for update.

**Comment by Mikey1993** [comment]
@gorhill I understand that, but these kind of things will always happen, whether it is now, or later.
Providing your users a better understanding of what's going on, is ,IMO, has a higher usability priority than not updating the `messages.json` file and finding yourself with untranslated text in various languages for some time.

**Comment by gorhill** [comment]
> finding yourself with untranslated text in various languages for some time

?

What specifically do you have in mind in the above sentence?

**Comment by Mikey1993** [comment]
@gorhill If I understood you right, your point is that if you change/add the strings too often, there will be times when there won't be a complete translation in time for the release, or even not at all <b>for some time</b>.

**Comment by gorhill** [comment]
I was just explaining why I chose _"Make use of context menu where appropriate"_ over something like _"Enable blocking elements on a page via right click context menu"_. If ever I add more entries in the context menu, I would have to come back to the first sentence anyway (having one setting per entry doesn't make sense IMO), so I chose to go with the first sentence now to make it future-proof.

**Comment by Mikey1993** [comment]
Yes, I understand. but it's just too uninformative.
Most of people (and even myself in the first time looking at this setting), have no idea what the "context menu" is.

IMO,
There should be 2 entries in the settings.

First: "Enable blocking elements on a page via right click context menu".
- Because, as you have said, people didn't like when the context menu was cluttered on HTTPSB.

Second: "Enable right click context menu additional features"
(or without the additional)
- Becuase this way, users will try, of course, enable this setting and click the right button on their mouses, which is a lot better than just declaring that there is a context menu (But what do you mean??).

Hope you will consider that.

**Comment by cpatulea** [comment]
Thanks for allowing the context menu to be disabled (I prefer to disable it).

**Comment by gorhill** [comment]
https://www.google.ca/search?q=context+menu
