### ISSUE TITLE
Unable to overrite exception filter - @@/advertisement.js

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#268]
As said in the title, not able bypass above exception filter.
Tried to add the below, but of no use..

||/advertisement.js^$important
(or)
||/advertisement.js,important

This can be tested at tomshardware.com

Chrome v37 (Stable build), W8.1

**Comment by gorhill** [comment]
That's not a valid filter. The `||` are to anchor to a hostname label, but there is none in your filter.

**Comment by harshanvn** [comment]
Ok Thanks. I thought we could do that for direct resource name itslef.
After i added complete url, it is working as expected.
||m.bestofmedia.com/sfp/images/js/advertisement.js^$important

Thanks!
