### ISSUE TITLE
Feature: Search rules inside cached lists

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#269]
This will help to debug and fix breakage of pages faster (identify what list is blocking and breaking the page).

**Comment by Mikey1993** [comment]
Maybe also add a column of "List"/"Origin" in the table that is in the statistics tab, so that while debugging you can clearly see the list that the rule came from.

**Comment by gorhill** [comment]
Yes, I thought a filtering option for the list would be great. For the second suggestion, this is dup of #43. This one is challenging though, as this would force uBlock to forfeit some efficiency.

**Comment by Mikey1993** [comment]
How about adding a column to the requests logging table with a button of "Whitelist" next to each row that will add the rule with the `important` label to the whitelist rules (Except, of course, the Dynamic filtering rules as per the current design)?

**Comment by gorhill** [comment]
The `important` filter option doesn't apply to exception filters: by default exception filters override any block filter -- so the `important` option is pointless. This is why `important` was introduced, to prevent block filters from being overridden by an exception. In any case, the suggestion is a dup of #68.

**Comment by gorhill** [comment]
> identify what list is blocking and breaking the page

Duplicate of #43.
