### ISSUE TITLE
Make the Element Picker popup extendable

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#271]
If the rules in the textarea, or the one that are inlined are too wide for it to show as a whole, it would be inconvenient to add it.

Maybe the elements of the popup Element Picker could also be resized on initial pick and every time you pick a rule from below the textarea?

Example:

URL: http://www.huffingtonpost.com/2014/10/03/nurses-unprepared-ebola_n_5926828.html
Pic:
![Element picker](http://i.imgur.com/ey4ikSy.png)

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock

Please close this issue.
