### ISSUE TITLE
Feature request: "Reset to defaults" button

### ISSUE THREAD

**Issue by bconway** [uBlock-LLC/uBlock#272]
With changes to default block lists and the like, it would be nice to be able to reset uBlock to its default state without need to go into your Chrome profile folder and wipe out settings.

**Comment by ghost** [comment]
There could be 3 different buttons:

Restore default
Export settings
Import settings

**Comment by ialexsilva** [comment]
duplicate #137 :+1:

**Comment by gorhill** [comment]
Fixed with a61975b798a813f8755b5d660de920f4412da68a.

**Comment by bconway** [comment]
Great, thanks!
