### ISSUE TITLE
Picking an element to hide seems to display broken on this site

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#275]
On this site:
http://www.ducea.com/2006/05/30/managing-apache2-modules-the-debian-way/

The element picker red rectangles behave strangely (something like a mirror) when picking of trying to select an element interactively.

Also, there is an error in the console window as the image shows:
`Error: Problem parsing d=""`

Every click on the "Pick" button creates a new, same, error line in the console.

Pic (Selecting the header of the page):
![Elemet Picker](http://i.imgur.com/Z9EIKm4.png)

**Comment by gorhill** [comment]
Dup of #210.

**Comment by gorhill** [comment]
For the record: `Error: Problem parsing d=""` = https://code.google.com/p/chromium/issues/detail?id=264123

**Comment by Mikey1993** [comment]
This is still broken even with uBlock v0.7.0.5 and #210 fixed, but only when you pick the `<em>` tags on this page.

For example, If you hit the "Pick" button and hover the button over the text that is on the 3rd passage, 2nd row:
"apache2-mpm-worker or apache2-mpm-perchild"
You will see that the selection isn't highlighted right.

**Comment by gorhill** [comment]
Ok, it's a different issue than the original one. It affects inline elements spread on multiple line.

[MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement.offsetLeft):

> However, for inline-level elements (such as span) that can wrap from one line to the next, offsetTop and offsetLeft describe the positions of the first border box

**Comment by Mikey1993** [comment]
opened a new issue (#312), so it will be easier to track the new identified issue.
