### ISSUE TITLE
2 issues regarding "Enable experimental features" text

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#279]
First one:
The "Enable experimental features" is wrong on Crowdin.
It should be "Enable experimental features <b>(Experimental features)</b>"
There is no string of the marked in bold text on Crowdin.

Second one (Adds to the first issue + reported by myself on Crowdin):
IMO, the text should be shown as:
"Enable experimental features (About)"
Because if the "About" was "Experimental features", there would be an odd double translation in the same sentence.

Cheers,
Mike.

**Comment by ialexsilva** [comment]
:+1:
