### ISSUE TITLE
Parse and enforce Adblock+ element hiding filters option not working properly.

### ISSUE THREAD

**Issue by zerodrek** [uBlock-LLC/uBlock#28]
I've only seen this, noticeably, on http://deviantart.com so far.

With the option on, it looks like this:

![with option on](https://cloud.githubusercontent.com/assets/2582474/3422606/3303763c-ff50-11e3-859a-0e1fb544e8dd.PNG)

With the option off, the ad is blocked, but you can still see other elements on the page:

![with option off](https://cloud.githubusercontent.com/assets/2582474/3422608/40f19814-ff50-11e3-8beb-deb010f562ff.PNG)

**Comment by gorhill** [comment]
Need to test following related issues to validate fix: #7.
