### ISSUE TITLE
Create a tutorial for Dynamic Filtering for novice users

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#280]
As the title says, when there's a feature like Dynamic Filtering we need a proper tutorial how to maximize the efficiency, and which settings are recommended to use.

Not all users are so familiar about these kind of great features.

**Comment by gorhill** [comment]
You could make one?

**Comment by ghost** [comment]
I have no idea how to maximize the efficiency. This is totally new feature for me. And how to even use it properly.

**Comment by s-fiebig** [comment]
I like the Dynamic Filtering feature and think the current wiki page describes it well. Do you think a bit more "help" in the GUI itself would help? E.g., one-time pop-ups describing the cells (inline, 1st party).

**Comment by ghost** [comment]
I don't understand the Wiki page at all, like I said this is completely new feature for me, never heard of it before. I'm clueless how to use it properly.

**Comment by gorhill** [comment]
> I'm clueless how to use it properly.

Don't use it. You don't have to. It's for users who can use NoScript-like extensions. As said in the wiki:

> Of course, blocking portion of a page may cause page breakage, sometimes benign, sometimes severe. It is up to the user to choose how to make use of this feature.
