### ISSUE TITLE
espn.com video clips won't play

### ISSUE THREAD

**Issue by turmoggy** [uBlock-LLC/uBlock#281]
With updated default filters. Chrome 38 64 bit

**Comment by gorhill** [comment]
Works fine from here on Chromium 37. Does ABP have the same problem using the same lists on Chrome 38?

Edit: Ok, I tried Chrome 39 on Windows and it worked fine.

What other extensions you have installed?

**Comment by gorhill** [comment]
I ask "What other extensions you have installed?" because there is an [open issue in Chromium](https://code.google.com/p/chromium/issues/detail?id=412786) about deadlock issues, which may occur with extensions installing a mutation observer while some Flash-based net requests are blocked (you should get the same problem with ABP if so).

**Comment by turmoggy** [comment]
-Tried Chrome 38 32 bit and 64 bit versions and got the same issue. Disabled every extension besides ublock. 
-Tried clearing cookies.
-Firefox with adblock edge works fine
Ublock worked fine with Chrome 37 64 bit with all my extensions. 

Here are my extensions

checker Plus for Google Calendar
FlashControl-whitelisted espn
Google Dictionary
Humble New Tab Page
Lastpass
LinkClump
Magic Actions for Youtube
Smart Up
Tampermonkey
Type Ahead Find
WikiWand Wikipedia Modernized
Ublock

Here's a video of demonstrating the error. I disabled every extension besides ublock. When I disable ublock the video plays. 

http://a.pomf.se/btgnvi.mp4

**Comment by gorhill** [comment]
From where do I install Chrome 38?

I tried the beta/dev versions, both were 39.

**Comment by turmoggy** [comment]
https://www.google.com/chrome/browser/#eula

http://www.neowin.net/news/google-chrome-38-now-available-for-download

38 is the official release just a few days ago.

**Comment by gorhill** [comment]
...

I had coded a nice workaround for [Chromium issue 410382](https://code.google.com/p/chromium/issues/detail?id=410382), and for curious reasons, it doesn't work anymore on Chrome 38 -- but works on Chrome 39...

I can fix with a broader workaround, but this might cause who knows what side effects, as the only possible fix now is to re-type request of type `other` as type `object`, which would not be good if the net request is really something else than a plugin request.

**Comment by turmoggy** [comment]
I played a few videos on espn and it appears to be working.
