### ISSUE TITLE
Dynamic filtering: is the ability to filter 1st-party `iframe` really needed?

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#282]
In retrospect, I don't see much use for this. I may remove it unless a good reason not to is brought forth. Making uBlock UI simpler by removing a useless feature would be helpful.

**Comment by kikaxa** [comment]
I'd like to ask same question about 1stparty/embed scripts. Do we need them at all, or as a separate options?

**Comment by gorhill** [comment]
For script, definitely. Scripts are linked to page behavior, so you want that kind of granularity. At worst, a 1st-party `iframe` can be removed using the element picker -- but I really doubt users will ever feel the need to block all 1st-party `iframe` by default.

**Comment by gorhill** [comment]
> Do we need them at all, or as a separate options?

Yes. They are more likely to be used "off" by default, and in such case they are useful to "fix" pages. I will be collating examples over time:
- [Examples of usefulness of blocking inline script tags](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-Examples-of-usefulness-of-blocking-inline-script-tags)
- [Examples of usefulness of blocking 1st-party script tags](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-Examples-of-usefulness-of-blocking-1st-party-script-tags)

There might also be users who use them "on" by default, and in such case it's always nice to just allow 1st-party to un-break a site rather than allow all.

**Comment by ghost** [comment]
> Making uBlock UI simpler by removing a useless feature would be helpful.

Sounds good to me.

In addition, could the extra space be used to make the first cell of each row say something like "This site" and "Default"? Maybe even including a "1st" and "3rd" in the top of the other cells, while pushing the `<script>` and `<iframe>` tags to the bottom.

In comparison to HTTPSB where the leftmost cell contains a domain name, it is much less intuitive to understand what the cells do while looking at them for the first time.

**Comment by puff-m-d** [comment]
Hello,

IMHO, I agree not only to keeping the uBlock UI simpler but to keeping uBlock simpler in general. As a user of both uBlock and HTTPSB (future uMatrix), I like how they complement each other. uBlock is and should stay a simple install it and forget it extension and those that want more control and/or options can also add HTTPSB. I use the combination of the two and they do all I need for them to do. If more options are added to uBlock and uBlock and HTTPSB start to overlap more, it starts to defeat the purpose of the two separate extensions. Again, this is just my opinion on this.....

**Comment by gorhill** [comment]
> If more options are added to uBlock and uBlock and HTTPSB start to overlap more

No worry, I don't intend to add more than what is there. I just wanted to provide that little extra step to give the user the tool to easily block js / iframe for those users who do not want a complicated airplane-cockpit UI.

**Comment by gorhill** [comment]
I keep trying to find sensible uses for blocking 1st-party `iframe` tags and I can't come up with anything. All the others I [could justify](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering---examples), but for 1st-party `iframe` tags, nothing. If anybody think of something (that make sense preferably).

I did try to remove the cells for 1st-party `iframe`, but that messed up badly the UI in my opinion. Still, not a good reason enough to put something in there nobody will ever use.

**Comment by gorhill** [comment]
Fixed in 0.8.5.0: gone.
