### ISSUE TITLE
Add "Adblock Warning Removal List" from Easylist to the available blocking lists?

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#286]
Would be a great add to the "Anti-Adblock Killer | Reek" list that is already present.

"Adblock Warning Removal List" URL:
https://easylist-downloads.adblockplus.org/antiadblockfilters.txt

<b>Number justification:</b>
When enabling both lists (Anti-Adblock Killer | Reek && Adblock Warning Removal List),
I can see that "Adblock Warning Removal List" is enabling 60 additional rules.

**Comment by SW1FT** [comment]
Yes, please.

**Comment by gorhill** [comment]
I have to look whether I can use just a URL in the preset filter lists, I don't want to copy this file into the project, as it doesn't come with an explicit CC license.

**Comment by ghost** [comment]
+1

**Comment by gorhill** [comment]
With fix to #224, it can easily be added directly from Adblock Plus' own web site.
