### ISSUE TITLE
"Start from scratch..." string isn't very intuitive...

### ISSUE THREAD

**Issue by SW1FT** [uBlock-LLC/uBlock#288]
Instead of being "Start from scratch...", it should be "Reset to default settings".

**Comment by Baegus** [comment]
+1

**Comment by trietbui85** [comment]
Agree with you @SW1FT

**Comment by ialexsilva** [comment]
:+1 simple "Reset All Settings"

**Comment by gorhill** [comment]
"Reset all to default settings"?

I just want to be sure it is understood that all custom filter rules and whitelist entries will be removed as well.

**Comment by SW1FT** [comment]
@gorhill yeah, sure.

**Comment by Baegus** [comment]
That's what the alert is for. ;)

**Comment by Mikey1993** [comment]
+1 for:
Change button to "Reset to default settings" 

+

An alert after clicking the button saying: "Caution! this will also remove all your custom filters. Are you sure you want to proceed?"
