### ISSUE TITLE
"Enable experimental features" breaks twitch.tv

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#289]
Workaround: disable _""Enable experimental features"_.

**Comment by gorhill** [comment]
Disabling _"Enable experimental features"_ --- which causes the mirrors to be flushed -- and re-enabling it fixed the problem. So I will have to find out which locally mirrored requests causes the problem, and avoid to cache this one (or these).

I suspect `s0.2mdn.net`.

**Comment by gorhill** [comment]
I am going to remove entries in there which are not known to be immutable.

Removing:

```
s0.2mdn.net
    [^\\]*2mdn\.net\/instream\/html5\/ima3\.js
b.scorecardresearch.com
    ^b\.scorecardresearch\.com\/beacon\.js
cdn.quilt.janrain.com
    ^cdn\.quilt\.janrain\.com\/
```

**Comment by tailHey** [comment]
Not entirely sure of it, but something similar seems to also happen with malwaretips.com.

Some scripts don't work with experimental features enabled, disabling then enabling it again and it works. The scripts I'm dealing with can't be seen without being logged in (for instance, focusing on the Alerts item display the list of latest alerts, but this isn't the case on the first time with experimental features enabled).

µBlock 0.7.0.0, using Opera 24.0.1558.64 with customized HTTPSB

**Comment by gorhill** [comment]
Ok I logged-in malwaretips.com with the feature on. The "Alerts" pop-up displayed to just fine, before and after resources are locally mirrored. What exactly are the steps to reproduce the problem?

**Comment by tailHey** [comment]
I can't say for sure, maybe it's also related to filters I use? Anyway since then I can't reproduce the issue anymore :S

**Comment by gorhill** [comment]
Images not displaying with the feature turned on and resources locally mirrored -- so it works first time, not subsequent reloads of the page:

http://www.sbnation.com/2014/10/5/6916597/nba-new-tv-deal-espn-turner-24-billion

**Comment by gorhill** [comment]
Argh. Problem is the caching of `www.googletagservices.com/tag/js/gpt.js`. This sucks, as this forces users to hit Google servers.

When blocking outright `www.googletagservices.com/tag/js/gpt.js` though, the page displays all fine.

**Comment by chrcoluk** [comment]
Hi guys.

How do you enable these experimental features? I see no such option in my settings tab and want to try local mirroring.

**Comment by Snapy** [comment]
@chrcoluk It's not available anymore due to too many problems with non-trivial fixes.

**Comment by chrcoluk** [comment]
ok then I suggest updating the wiki.
