### ISSUE TITLE
Experimental feature breaks Twitch Now

### ISSUE THREAD

**Issue by SW1FT** [uBlock-LLC/uBlock#292]
I don't know the technical details about this but, when I try to login on to my account using Twitch Now, it never actually logs in if I have the Experimental feature on.

You can check Twitch Now here: https://github.com/Ndragomirov/twitch-now

**Comment by gorhill** [comment]
I could login fine. Maybe you don't have an updated version of [this asset](https://github.com/gorhill/uBlock/blob/master/assets/ublock/mirror-candidates.txt) -- which was fixed in #289?

**Comment by SW1FT** [comment]
EDIT: I've downloaded uBlock 7.0.2 from Chrome Store to my Opera beta, and it seems to have fixed this.

**Comment by gorhill** [comment]
Ok, I will assume this is a dup of #289. I will send an update to Opera store today, but the review process there takes longer, so it might be ready tomorrow.
