### ISSUE TITLE
safelinking.net is broken

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#293]
The site isn't usable with uBlock.
It's because of the following filter:
||safelinking.net^

**Comment by Mikey1993** [comment]
I have tried to manually insert
`@@||safelinking.net^$third-party`
into whitelist, but it's not unbreaking the site...,

`@@||safelinking.net^$~third-party`
This one did it for me.

**Comment by gorhill** [comment]
Doh, you're right I made a mistake. We want the exception only for first-party, not 3rd-party.

**Comment by Mikey1993** [comment]
No worries.
Thanks, it should be alright now :)
