### ISSUE TITLE
Add "Prebake - Filter Obtrusive Cookie Notices" to the available blocking lists?

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#295]
Github link:
`https://github.com/liamja/Prebake`

Filter list raw link:
`https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt`

The license on this one seems to be pretty forward:
`Licence: https://raw.github.com/liamja/Prebake/master/README.md`

~~<b>Number justification:</b>
814 used out of 814
When enabling all non regional lists. 
(If enabling the russian lists, the number falls to 366 used out of 814)~~
The number justification is wrongly based because the filter lists are loaded asynchronously, so there is no way to know reliably with uBlock how much unique filters this list is adding to the existing ones.

The list seems to update frequently.

**Comment by gorhill** [comment]
This has been addressed since a while.

**Comment by Mikey1993** [comment]
How this has been addressed?

**Comment by gorhill** [comment]
It's in there?

**Comment by Mikey1993** [comment]
I see.
My mistake for not checking the latest dev version.
I've been waiting for the latest stable, therefore didn't noticed the list has been added.

Cheers :)
