### ISSUE TITLE
Add an easy way to enable/disable experimental features from the popup?

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#298]
<b>Option 1:</b>
Maybe some icon with a tool tip that says "Enable/Disable Experimental features", just like the element picker one?
If experimental features are ON, the icon will glow, either it will be grayed out?

<b>Option 2:</b>
Add a label says "Enable/Disable Experimental features" next to a checkbox.

I don't see any harm exposing this setting to the masses, the opposite,
I think this will help a lot for of users that just set this option on the first time they installed the extension, but then forgot about this setting, to fix their problems a lot faster.

**Comment by kurtextrem** [comment]
Strg+Shift+click => Add a red glow (aka background shadow) around the on icon?

**Comment by gorhill** [comment]
We are going to have to hold back about "keeping adding stuff".

At this point, I am more in a code-stabilization mood. It's easy to overdo and destroy a piece of software. It's a recurring theme to be asked to keep adding stuff. The primary goal of uBlock is still the same as originally set: very simple, and whatever else is an extra (and tucked away), out of the way of mainstream users.

So in short: No experimental feature visual will pollute the main UI of the extension.

**Comment by Mikey1993** [comment]
I don't intend to see it implemented right away.
I am creating this issue for the future, maybe in some point you will have this "eureka" moment related to one of these "adding stuff" issues.

All in all, I also, truly want to see uBlock thrive :)
