### ISSUE TITLE
id.ogplanet.com is broken

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#303]
This rule should be added:
`@@||amazonaws.com^$~third-party,domain=id.ogplanet.com`
- I wasn't sure if some page on this sub domain uses a 3rd-party content, but to be safe, I've added it.

**Comment by gorhill** [comment]
What is broken? What should I look for? Before creating an exception filter I need to see what is wrongly filtered, as this could be an EasyList/EasyPrivacy problem (thus issue would be with them), or a hosts file problem (thus issue is here).

**Comment by Mikey1993** [comment]
Sorry, false alarm.
it seems like a recent update to whatever list that caused the breakage of the page CSS + login form - after purging and updating the same lists that we site was breaking with, the website works as intended.

**Comment by Mikey1993** [comment]
Also, if we already brought up the update process, I have a question:
How is auto-updating feature works and when does it update the lists? (Time or/and action based?)

Thanks.
