### ISSUE TITLE
Website partial breakage

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#304]
Website:

www.nsaneforums.com

Which part is broken:

There should have text formatting tools above the text box, but Experimental Features hides text formatting tools section:

![untitled](https://cloud.githubusercontent.com/assets/8661552/4602984/3067bfd0-5155-11e4-9e97-2a642a25314e.png)

When Experimental Features is disabled text formatting tools section appears correctly.

Edit: This also affects other websites also, i.e www.tweakscene.com.

**Comment by gorhill** [comment]
Can you verify this still happens once you get v 0.7.0.4? Might be dup of #301.

**Comment by ghost** [comment]
I just noticed that you released version 0.7.0.4, I will report as soon as I get this version.

**Comment by ghost** [comment]
Fixed by 0.7.0.4, closing the issue.
