### ISSUE TITLE
Feature: logging of blocked elements

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#308]
Would be a useful feature for debugging a site visual breakage with the already existed request logging.

**Comment by gorhill** [comment]
You mean "hidden" (not same as "blocked")?

**Comment by Mikey1993** [comment]
I think both wold be appropriate to log, but the "hidden" are the important ones, yes.

**Comment by gorhill** [comment]
I don't understand what you mean by "both would be appropriate to log". Blocked requests are already logged in the _Statistics_  tab.

**Comment by Mikey1993** [comment]
I thought you are referring to whether the "Hide placeholders of blocked elements" setting is on or off.
Or am I getting confused?

**Comment by gorhill** [comment]
Ok, I think I understand. You distinguish elements hidden as a result of blocked net requests, and elements hidden as a result of cosmetic filters.

**Comment by Mikey1993** [comment]
Exactly.

**Comment by ghost** [comment]
Maybe show already blocked elements when in element picker mode?
