### ISSUE TITLE
Suggestion: add another stat when left clicking on icon showing how many data has been saved thanks to this addon

### ISSUE THREAD

**Issue by tailHey** [uBlock-LLC/uBlock#31]
The title speaks for itself ^^

**Comment by gorhill** [comment]
Impossible to know, it's not downloaded so there is no way to know how much is saved. And to make matter worst, the data which is not downloaded would probably cause more data to be downloaded, etc. I can count only the number of requests which were blocked.

**Comment by gorhill** [comment]
Closing, as there is no way to know how much bandwidth is saved.
