### ISSUE TITLE
EasyList - 0 used

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#311]
![untitled](https://cloud.githubusercontent.com/assets/8661552/4604217/7123d07c-518c-11e4-92d4-d65f4586db6c.png)

**Comment by gorhill** [comment]
What other lists you have selected?

**Comment by ghost** [comment]
Check my backup file:

http://multiupload.biz/ul_rirzyvqi8vb0

**Comment by gorhill** [comment]
Is there a better way to get this? I obviously am someone who won't let script/frame to load from that kind of site. Just tell me, do you have Fanboy Ultimate selected?

**Comment by ghost** [comment]
If I untick EasyList and manually add it:

![untitled](https://cloud.githubusercontent.com/assets/8661552/4604252/cd206bcc-518e-11e4-8de5-04c13b98e027.png)

**Comment by ghost** [comment]
I have Fanboy Ultimate ticked, ignore my above post, maybe Fanboy is zeroing EasyList.

**Comment by gorhill** [comment]
That's it, EasyList is a subset of Fanboy Ultimate.
