### ISSUE TITLE
Add "updated on %date" text to each filter list

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#313]
Would be good to know when each of the lists was updated.
This will also help in some false positives situations as I had in #303.

**Comment by ialexsilva** [comment]
Add a tooltip: last update date: %date%

**Comment by Mikey1993** [comment]
Yeah, I agree that with the current UI, tooltip is a better approach IMHO.

**Comment by SW1FT** [comment]
This would be great, I've thought about this as well a while ago.

**Comment by gorhill** [comment]
For translators:

![d](https://cloud.githubusercontent.com/assets/585534/6566463/2c3db4cc-c690-11e4-9bcb-f5bafe4ce15f.png)

**Comment by alejandrolemus** [comment]
Why not add <code>updated</code> or <code>last update:</code> before those strings? Would be easier to know what it means, IMO.

**Comment by gorhill** [comment]
I want to be able to reuse these strings elsewhere too, which I won't be able if I make them specific. I am completely unsure whether `Last update: {{ago}}` works for all languages.

**Comment by alejandrolemus** [comment]
Maybe you could define <code>Last update</code> and <code>{{x units ago}}</code> as separate strings, and in this specific case build the tooltip from both? That way they are still independent and reusable (<code>Last update</code> seems like it could come handy in other situations, too).
Not that this is a really important issue, just trying to contribute with options here. Anyways, I would say that in Spanish <code>Last update: {{ago}}</code> would work just fine.

**Comment by Bushido1** [comment]
In Estonian [b]Last update: {{ago}}[/b] is good also and more understandable.

**Comment by gorhill** [comment]
Ok I will add a new string, `Last update: {{ago}}`, then translators can pick whatever is best, and if ever there is a language for which no meaningful translation can be found, then a translator can fall back on `{{ago}}`, which will give same result as it is now.
