### ISSUE TITLE
TypeError while using element picker

### ISSUE THREAD

**Issue by pwstokes225** [uBlock-LLC/uBlock#315]
On http://environmentsforhumans.com/, using the element picker results in the error "Uncaught TypeError: Cannot read property 'length' of null" (referring to line 441 of element-picker.js).
The element in question:
![element](https://cloud.githubusercontent.com/assets/764704/4609955/fd695396-52a8-11e4-939c-3abcd57f0f5a.png)

**Comment by pwstokes225** [comment]
Also occurs on https://software.intel.com/, with this element:
![intelerror](https://cloud.githubusercontent.com/assets/764704/4612220/8f127d5c-52c4-11e4-8718-dd43f8a718e8.png)

**Comment by ialexsilva** [comment]
:+1:
