### ISSUE TITLE
http://www.inc.com/ is broken

### ISSUE THREAD

**Issue by ivan** [uBlock-LLC/uBlock#316]
http://www.inc.com/ is missing stylesheets when uBlock 0.7.0.5 is enabled (default filters).

**Comment by Mikey1993** [comment]
`127.0.0.1 inc.com`
`127.0.0.1  www.inc.com`
in hpHosts’s list.

**Comment by ivan** [comment]
It's also blocked by Peter Lowe’s Ad server list‎, which is enabled by default.
