### ISSUE TITLE
µBlock 0.7.0.6 not working

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#324]
The new version of µblock is a litlle buggy :/
It's impossible to select a list( it's empty) and it makes chromium 40 crash (sometimes) when i try to restore the settings from a file.

http://www.hostingpics.net/viewer.php?id=517093Capture.png

**Comment by HitomiTenshi** [comment]
Yep, just got that too. It seems I lost all subscriptions except **Your filters**‎, **µBlock filters** and‎ **µBlock filters – Privacy**‎.

**Comment by HitomiTenshi** [comment]
I think the typo in assets/ublock/filter-lists.json from

commit 69b6027174bcc788068a6f1a4ef3c2d936290e3e

caused that issue. I sent a pull request.

**Comment by gorhill** [comment]
Yes, sorry about all this, thanks @HitomiTenshi for the fix.

I've been panicking at the breakage here, really scrambling. All should be fine now.

I think from now on I will post a release here a wait a while before posting to the store(s).
