### ISSUE TITLE
[EasyList,EasyPrivacy] Allow filter

### ISSUE THREAD

**Issue by SMUsamaShah** [uBlock-LLC/uBlock#328]
What is the way to explicitly **allow** a script on a page instead of blocking it? Livestream on a website is not running because its script is being blocked.

**Comment by gorhill** [comment]
Can you give me a URL? I will look into this.

**Comment by SMUsamaShah** [comment]
This is the url http://live.geo.tv/live.aspx

I guess streaming is not working because `http://live.seenreport.com:82/media/js/fingerprint.js` is being blocked with the filter that blocks `/fingerprint.js`

Also this url http://live.express.pk/
It shows an ad first, may be that is the reason but I haven't checked what is wrong with it.

**Comment by gorhill** [comment]
I could make the first link work with those two exception filters:

```
! To counter EasyList's "||imasdk.googleapis.com^$third-party"
@@||imasdk.googleapis.com^$domain=live.geo.tv
! To counter EasyPrivacy's "/fingerprint.js"
@@||live.seenreport.com^*/fingerprint.js
```

Second link I could make the live video work with these exception filters:

```
! To counter EasyList's "||imasdk.googleapis.com^$third-party"
@@||imasdk.googleapis.com^$domain=live.express.pk
! To counter EasyPrivacy's "/ping.gif?"
@@||i.n.jwpltx.com/v1/jwplayer6/ping.gif?$domain=live.express.pk
```

**Comment by SMUsamaShah** [comment]
so @@ allows explicitly? I can do the rest if @@ is what I need to allow a script on a domain

**Comment by gorhill** [comment]
To get the fix: purge the cache for "uBlock filters" and click "Update now", or restart uBlock with auto-update enabled.

**Comment by gorhill** [comment]
Yes, prefixing a filter with `@@` means to override any blocking filters.

**Comment by gorhill** [comment]
Required fixes in EasyList/EasyPrivacy: http://forums.lanik.us/viewtopic.php?f=64&t=19046
