### ISSUE TITLE
Need translation of detailed description: German

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#33]
Reference detailed description in https://github.com/gorhill/uBlock/blob/master/dist/DESCRIPTION-reference.

Detailed description must go in: https://github.com/gorhill/uBlock/blob/master/dist/DESCRIPTION-de.

It doesn't have to be an exact translation, what matters really is a good description of what the extension does, as per Opera web store requirements (issue #23). Just do what you think is best.

**Comment by ghost** [comment]
Done.

**Comment by gorhill** [comment]
Thanks.
