### ISSUE TITLE
Individually disable filter entries / whitelist elements from toolbar popup

### ISSUE THREAD

**Issue by Donald42** [uBlock-LLC/uBlock#331]
Adblocking extensions frequently break webpages in unusable ways. The log page in uBlock shows which requests were blocked, but there is no way to individually whitelist blocked element (or disable the corresponding blacklist entries that blocked it) from there.

The Ghostery extension has a very nice interface for this which displays the block and allows you to disable it (temporarily or permanently) right there, both in the toolbar popup and via buttons injected into the page. Being able to test filter blocks one at a time using such an interface makes it very easy to figure out what may need to be whitelisted for a page to work as desired. Is there any chance such an interface could be added to uBlock?

**Comment by SW1FT** [comment]
+1, this would be very helpful. It's one of things I miss from Ghostery.

**Comment by lardissone** [comment]
+1 I came here to mention Ghostery feature to whitelist some elements in specific sites.

**Comment by beigexperience** [comment]
I'd like to override specific rules from a subscription list too.

**Comment by GrayFace** [comment]
This needs to be done in UI. In logger there's the dialog "Static filter ||blablabla found in:", which must allow disabling selected filter entry. I vaguely remember AdBlock having a way to disable filter entries.

**Comment by GrayFace** [comment]
The worst offenders are popup rules. uBlock treats all links opened by a middle click as popups, even 1st party links of the site itself. This leads to a host of links not opening on effected sites.
