### ISSUE TITLE
Cosmetic filter not working on smbc-comics.com

### ISSUE THREAD

**Issue by pwstokes225** [uBlock-LLC/uBlock#333]
The cosmetic filter `www.smbc-comics.com###sharebar` does not appear to work.

**Comment by gorhill** [comment]
There is an exception filter in Fanboy's Social:

```
last.fm,smbc-comics.com#@##sharebar
```

As per ABP's filter syntax, exception filters override block filters. I get same result with ABP.

**Comment by pwstokes225** [comment]
I see, I should have checked my filter lists. I'll close this issue.
