### ISSUE TITLE
How to block a div by class inside an iframe?

### ISSUE THREAD

**Issue by 4n0n1mo** [uBlock-LLC/uBlock#337]
Could someone help me with that?

**Comment by gorhill** [comment]
Currently the element picker doesn't work inside an `iframe`: issue #88. I don't see technical difficulty in implementing this, it's just being busy with other things.

Current workaround would be to use the browser's element inspector, or maybe open the URL of the `iframe` into it's own web page and from there use the element picker as usual.

What's the URL of the `iframe` and `div` class name?

**Comment by 4n0n1mo** [comment]
I've tried to go to the iframe page directly, but it won't load when accessed directly.
This is the page:
http://br.advfn.com/bolsa-de-valores/bovespa/petrobras-PETR4/grafico/tempo-real?mode=html5

I've created an account only for you login:
User: disporegister
Password: 123456

I would like to know how to block the following element:
`<div class="onchart-tv-logo wrapper">`

Thanks for your help and this awesome extension.

**Comment by gorhill** [comment]
This filter works for me: `br.advfn.com##.onchart-tv-logo.wrapper`

**Comment by 4n0n1mo** [comment]
Awesome, thank you very much for your help :)

**Comment by kudataz** [comment]
@gorhill uhm sorry i want ask too..
how block this area `<div id="z2c7">`
please your help

**Comment by webgolub** [comment]
I have a div with `###epom-pushdown-_random symbols_`
How can i block this div?
