### ISSUE TITLE
Omnibox and third-party script issues

### ISSUE THREAD

**Issue by spetroll** [uBlock-LLC/uBlock#338]
Hi,

today using the omnibox to search with Google, I was sent to `https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8` and an empty page was displayed. I tried reinstalling Chrome and resetting my settings, and only after I disabled uBlock it worked again. I'm using the latest version of Chrome, the rules are updated and this issue started last night .

It also appears to cause troubles with logging in to Gmail, commenting on reddit and even loading the preview of this issue, blocking JavaScript that are supposedly third-party.

For example for this page, it blocks these requests:

<code>
script  https://assets-cdn.github.com/assets/frameworks-da
bc650f8a51dffd1d4376a3522cbda5536e4807e01d2a86ff7e
60d8d6ee3029.js *$~third-party,script,important
script  https://assets-cdn.github.com/assets/github-d01013
daa80c5a341ba3ddb684f2f26679eb369d67459151d5175a63
4a9e98a5.js *$~third-party,script,important
script  https://github.com/gorhill/uBlock/issues/new    *$inline-script,important
</code>

**Comment by gorhill** [comment]
Looks to me like you have dynamic filtering turned on, and you are dynamically blocking inline and first-party scripts.

uBlocks comes with all dynamic filtering turned off by default. This is how your settings appear to be:

![a](https://cloud.githubusercontent.com/assets/585534/4780542/3e10959e-5c6d-11e4-8d1e-479e961d6213.png)

There should be no red areas at the bottom when dynamic filtering is turned off.

**Comment by spetroll** [comment]
You're right, thanks. I wasn't aware of this feature, but that makes perfectly sense.
