### ISSUE TITLE
Visual popup inconsistency of the "Dynamic filtering" feature

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#340]
I have managed to get uBlock to get (what I believe) a corrupted profile, which on filehippo.com isn't accounting the global rules of blocking the 3rd party scripts and frames.

<h2>Steps:</h2>
1. Download and load my (cleared from personal "Your filters") profile: https://mega.co.nz/#!aIpXhKTC!CiIQdh_k6SCKROipmU9WxS6P_6S5n_Snd8rjMxat370 
2. Enter this site: http://www.filehippo.com/
3. Open uBlock popup.
4. Notice that the global rules of 3rd party scripts and frames are marked red, <b>BUT NOT</b> the domain rules (grayed), when it should of course marked red because of the global rules.
5. Notice that the 3rd party blockage isn't really blocking the assets by enabling the logging feature.
6. Click the 3rd party domain level rules -> boxes become red.
7. Reload the page and the 3rd party blockage  now IS actually working.

Note: Clicking on "Start from scratch..." fixes the problem, But after loading the above profile, the issue appears again.
Note 2: I haven't noticed this issue before on other sites.
Note 3: I've also checked this with importing this 'corrupted' profile to a fresh profile of chrome, same results.

**Comment by gorhill** [comment]
If I use `http://filehippo.com/` in the address bar I see `allow` rules which override the global `block` rules.

**Comment by Mikey1993** [comment]
`http://filehippo.com/` - GOOD
`http://www.filehippo.com/` - BAD

**Comment by gorhill** [comment]
Well the implementation will try to find and use rules on ancestor hostnames. If I block `google.com` I wouldn't be too happy to find out that `groups.google.com` is not blocked. Isn't?

The real problem here is that there is no UI yet in the dashboard to inspect the dynamic filters, otherwise you would have been able to spot the reason why `www.filehippo.com` was not blocked.

**Comment by Mikey1993** [comment]
So you mean that the <b>global</b> rules, aren't really global?
Because as far as I can see it, the fundamental problem here is that the global rules aren't being applied to all the sites, and I have no visual cue for why it's happening as you have mentioned.

When you decide to enable the blockage of 3rd party assets with the global rules, you would expect them to be, as what it's promises to be - global.

Am I right?

**Comment by gorhill** [comment]
> So you mean that the global rules, aren't really global?

No I don't mean this.

Your filters for `filehippo.com` override global rules. Whatever descendant hostnames of `filehippo.com`, i.e. `www.filehippo.com` will inherit filters from `filehippo.com`.

If you allowed `filehippo.com`, it's safer and more convenient to propagate these filters to related descendant hostnames.

Imagine if I block 1st-party scripts for `crappy-site.com`, only to find out that 1st-party scripts on `really.crappy-site.com` are not blocked. Now, **that** is bad.

**Comment by Mikey1993** [comment]
Right, I see and agree that the current behavior is the right one.

But if so, then why the 3rd party scripts & frames domain level rules boxes aren't grayed out on `www.filehippo.com` as they are on `filehippo.com`? 
Because someone might also think that this <b>visual inconsistency</b> is a bug (as I did).

**Comment by gorhill** [comment]
Yes, I could display them with the darker shade.

**Comment by Mikey1993** [comment]
Thanks.
Hope to see this fixed in the next version.
