### ISSUE TITLE
How to find out which exactly got blocked on the current website?

### ISSUE THREAD

**Issue by frdmn** [uBlock-LLC/uBlock#341]
Hello,

I just switched from AdBlockPlus to uBlock and im not sure how to access the "blocked elements on the current website". Right now I have a issue that something is blocked which actually shouldn't and I want to find out what I have to do to make it visable again.

I assumed I just click on here: ![bildschirmfoto 2014-10-27 um 15 09 41](https://cloud.githubusercontent.com/assets/944459/4792012/ec015492-5de2-11e4-919c-eabb354372ad.png), but that doesn't show my desired informations.

I think I just don't know where to look at. Can somone help me out?

**Comment by gorhill** [comment]
Once you create a filter with the _"Block element"_ tool, you will find this filter in the _"Your filters"_ tab the uBlock's dashboard.

**Comment by frdmn** [comment]
I didn't created any filters at all, I just subbed to the defaults. Not sure why these elements get blocked, thats why I was asking how to find out which filter is responsible for a "block" :P

**Comment by gorhill** [comment]
Oh ok, I misunderstood. Go to the _"Statistics"_ tab in the dashboard, and there you can activate the logging of net requests. Refresh the page and you will be able to see what happened to every net request on the page. (This doesn't include cosmetic filters though.)

Once you activate the net request logging feature, there will be an _eye_ icon in the popup which you can use to quickly go to the _Statistics_ tab.

**Comment by frdmn** [comment]
Exactly, this was what I was looking for:

![bildschirmfoto 2014-10-27 um 15 49 06](https://cloud.githubusercontent.com/assets/944459/4792663/73d5cb1e-5de8-11e4-97b8-b41e07cf0d99.png)

However, how do I find out where this is comming from (e.g. unblock that specific request for the future)?

**Comment by gorhill** [comment]
> unblock that specific request for the future

That is issue #68. Currently you have to manually create an exception filter in _"Your filters"_ tab.

Issue #236 needs to be addressed first in order to be able to address #68.

**Comment by frdmn** [comment]
Aaah okay, I see. Thanks for the quick replies. Great extension so far! :+1:

**Comment by frdmn** [comment]
@gorhill Sorry to bother you again but I can't seem to get it working:

I try to allow the following blocked requests for GitHub:

![bildschirmfoto 2014-10-28 um 11 51 29](https://cloud.githubusercontent.com/assets/944459/4807086/a1ccee96-5e90-11e4-8bfd-b6bbd612f96c.png)

These are my filters:

```
|| collector-cdn.github.com ^
|| github.com/_stats
|| google-analytics.com ^
```

Tried restarting Chrome, but it's still blocked. Can you help me?

**Comment by gorhill** [comment]
Do not use spaces inside the filters, and "allow" filters need to be prefixed with `@@`. Should be:

```
@@||collector-cdn.github.com^
@@||github.com/_stats
@@||google-analytics.com^
```

See [Adblock Plus filters explained](https://adblockplus.org/en/filter-cheatsheet#exceptions).

If you want to allow the above net requests **only** on Github:

```
@@||collector-cdn.github.com^$domain=github.com
@@||github.com/_stats$domain=github.com
@@||google-analytics.com^$domain=github.com
```

**Comment by frdmn** [comment]
Works like a charm. Thanks again!

**Comment by ergo-pwyss** [comment]
Hmm, sorry to bother again, but I don't get that running...

I try to get the images from http://www.technorms.com/44981/autofill-keepass-passwords-browser
They are comming from cdn.technorms.com
So I tried:
- open uBlock Icon/settings/My filters
- add a line `@@||cdn.technorms.com^`
- click "Apply changes"
- switch the tab and reload
