### ISSUE TITLE
Element picker text selection inheritance

### ISSUE THREAD

**Issue by pwstokes225** [uBlock-LLC/uBlock#343]
On https://disqus.com/
![disqus](https://cloud.githubusercontent.com/assets/764704/4786318/dfac80f0-5d91-11e4-8007-406cffc2f8e4.png)

and http://horriblesubs.info/
![horriblesubs](https://cloud.githubusercontent.com/assets/764704/4786322/e3662d68-5d91-11e4-8568-8d9cd91af7c0.png)

Note that text outside the `<textarea>` is also affected.

**Comment by Mikey1993** [comment]
I can't reproduce anymore.

**Comment by pwstokes225** [comment]
This is still occurring for me using µBlock 0.7.2.1 on the Google Chrome stable channel (v39.0.2171.71) on Windows.

Another example is https://imgur.com/:
![](https://cloud.githubusercontent.com/assets/764704/5328539/0f6aeacc-7dcf-11e4-9fce-6aa04b1b2dc0.png)

**Comment by Mikey1993** [comment]
Can't reproduce on https://imgur.com/ + Chrome 39.0.2171.71 either.
Do you have any other extensions that might interfere?

**Comment by gorhill** [comment]
I can reproduce. The colors are pretty though, it would be sad to get rid of them.

**Comment by pwstokes225** [comment]
Ok. I will close this issue.
It is minor and not everyone seems to be affected.
Worst case scenario is a site that makes either the selection colour or text invisible.
But that would be annoying at most.

**Comment by gorhill** [comment]
I was just trying to be funny.

**Comment by pwstokes225** [comment]
My apologies. I read your earlier comment as "can't reproduce". I'll try to read more slowly.
