### ISSUE TITLE
uBlock crashes

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#345]
Hi,

I'm using chromium 40.
When I try to restore the settings in µblock from a file, chromium crashes.  However  when  I restart the browser my settings are applied. I'm having this issue since µBlock 0.7.0.7.
I don't know if i'm the only one having this issue. Maybe my profile is corrupted...

Thanks.

**Comment by gorhill** [comment]
You need to report this to Chromium devs with repro steps: https://code.google.com/p/chromium/issues/detail?id=418174

Javascript does not "crash", so when a web page crashes, the problem is in the browser, and this needs to be reported to Chromium devs.

**Comment by gorhill** [comment]
The fact that your settings are properly restored upon restart is interesting. This would indicate the crash occurs when the chrome API `chrome.runtime.reload` is called. Might be of interest to Chromium devs.
