### ISSUE TITLE
NSL issue on forum-entraide-informatique.com

### ISSUE THREAD

**Issue by tailHey** [uBlock-LLC/uBlock#347]
Hello everyone!

My friend @littleboy62 and I have spotted a NSL issue on a certain website. We're both using Opera Stable.
Here is the step-by-step to reproduce the trouble:

1-Opera mustn't be opened until the cache and browsing leftovers are cleaned (Use PrivaZer or CCleaner for that, built-in cache cleaning for Opera could work too I guess).
2-Go to this website: http://www.forum-entraide-informatique.com/ .
3-Click the "Je redécouvre mon forum" button.
4-Click the "Connexion" button at the right of the bar located at the top.

Then, the webpage is dark, and NSL. Disabling µBlock for this website doesn't work either, the whole addon must be disabled to workaround the problem. Please take a look at it, if you need some answers don't hesitate to ask us. Thanks in advance!

**Comment by gorhill** [comment]
"NSL"?

**Comment by tailHey** [comment]
@gorhill: Sorry, Never Stop Loading

**Comment by gorhill** [comment]
uBlock or not uBlock, I get the same behavior: The page load, but it doesn't display very well, and except for _Accueil_, no links work. This happens without uBlock loaded either.

**Comment by tailHey** [comment]
Did you follow exactly the steps? Did you try with Opera Stable (up to date)?

**Comment by gorhill** [comment]
Yes, same on Opera. A black pane decends, and aside _Accueil_, no links in it works. The text is barely readable, because colors. With or without uBlock in memory.

**Comment by littleboy62** [comment]
Hi everyone.

I allow myself to clarify my little manipulation.

In fact, I've disabled the website by using ublock, without success.
Then, I've disabled completly this extension, on opera (opera://plugins).

Now, the site loads quickly, without any problem.

If you want more information, there is no problem.

Best regards,
Thomas.

PS : Sorry for my poor english.

**Comment by gorhill** [comment]
This is what I get with **and without** uBlock:

![a](https://cloud.githubusercontent.com/assets/585534/4873268/571023a6-6209-11e4-821b-9cc46ee76147.png)

> PS : Sorry for my poor english.

Parlons français si c'est plus facile, le site est français de toute façon.

**Comment by tailHey** [comment]
Peut-être est-ce lié aux listes de filtres sélectionnées ?

**Comment by littleboy62** [comment]
Re ;)

Moi j'ai ceci par contre, en désactivant µblock complètement :
![fei](https://cloud.githubusercontent.com/assets/7793828/4873290/cc44a998-620a-11e4-83f8-dc38f3864c56.png)

Je vais voir tester avec µblock activé, avec le site en liste blanche.

++

**Comment by gorhill** [comment]
J'ai la même chose, mais lorsque je clique _Connexion_, j'ai le panneau noir. Même dans Firefox sans aucun bloqueur.

**Comment by littleboy62** [comment]
Quand je clique sur connexion, j'ai ceci :
![fei](https://cloud.githubusercontent.com/assets/7793828/4873309/201ba818-620c-11e4-9c76-3526e2c1abeb.png)

Et si je me connecte, j'ai ceci :
![fei2](https://cloud.githubusercontent.com/assets/7793828/4873310/2e7cbb4a-620c-11e4-9439-47553137f640.png)

Toujours avec l'extension complètement désactivé dans les réglages d'opera.

Avec l'extension d'activée, mais avec le site mis en liste blanche, j'ai toujours la page noire qui se charge en permanence.

++

**Comment by gorhill** [comment]
Ok, donc pour reproduire j'ai besoin d'un compte..

**Comment by gorhill** [comment]
C'est quoi les autres extensions?

**Comment by gorhill** [comment]
OK, j'arrive à reproduire la page noire a cliquant sur une série de liens au hasard à la gauche de la page. Cependant je suis aussi capable de reproduire cette page noire **sans** uBlock en mémoire. Quand je regarde le contenu de la page, il n'y a pas de tag `body` dans la page. Je crois qu'il y a un problème dans la page même, et les symtpômes de ce problème sont plus susceptibles de se manifester selon le "timing".

Si je suis capable de reproduire le problème **sans** uBlock, il n'y pas d'autre explication que le problème est du côté de la page, ou encore un bug dans le navigateur. Je vois que le dernier script chargé en mémoire au moment où le problème survient est: http://www.forum-entraide-informatique.com/support/styles/Wide/theme/cdnav/js/main.js

Donc il y a quelque chose dans ce script, sensible au timing, qui bloque le chargement du reste de la page.

J'arrive à reproduire le problème à volonté maintenant, en cliquant sur les liens à gauche de la page un après l'autre. Éventuellement la page noire "NSL". Sans uBlock.

![a](https://cloud.githubusercontent.com/assets/585534/4873402/db78f292-6210-11e4-97dd-0db28c295ae0.png)

Ci-dessus, le contenu de la page noire-- **sans uBlock**: le tag `body` est manquant a l'appel.

**Comment by littleboy62** [comment]
Merci à toi, ça permettra à l'admin d'y voir plus clair.

Bonne soirée.

**Comment by gorhill** [comment]
Note que je n'arrive pas à reproduire sur Firefox, donc ça peut très bien être du côté du navigateur. Je vois dans le script des expressions contenant `webkitAnimationEnd` etc. spécifiques à Chromium. Cette information peut-être utile à l'admin.

**Comment by littleboy62** [comment]
Je l'ai prévenue, vu qu'il a aussi ce souci sur google chrome (donc basé sur chromium), je pense la même chose, car j'ai du le prévenir sur firefox, pas de souci sur ce navigateur.

**Comment by my-password-is-password** [comment]
Is it some kind of caching issue caused by "local mirroring" in uBlock's `Enable experimental features` ? 

Uncheck `Enable experimental features` and the page loads fine.

I made a vid of when `Enable experimental features` is enabled and it gets stuck.  And when I disable cache and reload it loads fine.

http://uux3.altervista.org/nsl.webm

**Comment by gorhill** [comment]
> Is it some kind of caching issue caused by "local mirroring" in uBlock

No, I can reproduce the problem with no extension at all. There is some kind of deadlock occurring. To me it looks like a Chromium-specific issue with CSS animation, or something.
