### ISSUE TITLE
suggestion : add a function to display the blocked items.

### ISSUE THREAD

**Issue by littleboy62** [uBlock-LLC/uBlock#35]
Hello everyone ! :dancer:

Firstly : this addon is working great ! Thanks a lot for this good work !  :+1: 

But I am like I am... I'll wish, if possible, display  the blocked elements... :

Actually... I'd like to be able to see the blocked elements somewhere... 
For instance, Ghostery shows a popup, while µBlock doesn't show anything, only the number of blocked requests...

I'm curious. ^^
I want to check everything before allowing it. ^^
So  I like especially having control on my computer, as in privacy...

I prefer to see by myself the blocked elements. 
Because if there is any problem, it will be easier to fix. 

So, this is my question : Is it possible ?

Thank you in advance,

Best regards,
Thomas.

**Comment by gorhill** [comment]
Dup of #12, "Possibility to view blocked elements + corresponding filters".
