### ISSUE TITLE
Adding site to white list is not working for keep.google.com.

### ISSUE THREAD

**Issue by inDigazzZ** [uBlock-LLC/uBlock#351]
I've added keep.google.com to whitelist and there is info about sucessfuly loaded CSS at page, but...
look at screenshot.

If only i disable uBlock - then links and text look as they should be.

![2014-11-03_11-55-52](https://cloud.githubusercontent.com/assets/7425050/4879295/85850930-6327-11e4-9a1a-715f7b4a1160.png)
![2014-11-03_11-58-40](https://cloud.githubusercontent.com/assets/7425050/4879296/858c0b68-6327-11e4-8549-9b108d5d7ac8.png)

**Comment by gorhill** [comment]
Disable _"Local mirroring"_ if you want the web fonts themselves. There is a problem in Chromium I believe regarding data URI: https://github.com/gorhill/uBlock/issues/291

**Comment by gorhill** [comment]
Dup  of #291.

**Comment by gorhill** [comment]
Actually... Maybe I should avoid local mirroring when a site is whitelisted?
