### ISSUE TITLE
Saw some warning in Chromium about directory name

### ISSUE THREAD

**Issue by my-password-is-password** [uBlock-LLC/uBlock#352]
I forgot to screenshot it but in Chromium's collect errors I saw an orange warning saying `"Cannot load extension with file or directory name _metadata. Filename..."`.  I think the underscore in `_metadata` is what its complaining about.

**Comment by gorhill** [comment]
That folder is added by the Chrome store.

**Comment by my-password-is-password** [comment]
Oh sorry.  Another question not related to this is when I went looking for the uBlock extension folder, I see there is a folder for all the  previous versions of uBlock. 

![ubdir](https://cloud.githubusercontent.com/assets/6408935/4885709/8fb79644-6376-11e4-9c09-b6968a41b687.png)

 Inside them they all only have the `assests` folder remaining.

![ubassets](https://cloud.githubusercontent.com/assets/6408935/4885713/93bca84c-6376-11e4-99ff-35dd938d7a81.png)

Is there a reason why these folders remain on my computer taking up 120mb.  Is it a Windows or Chrome problem?

![ub120mb](https://cloud.githubusercontent.com/assets/6408935/4885794/319568c4-6377-11e4-827e-0fac07842eff.png)

**Comment by gorhill** [comment]
> Is it a Windows or Chrome problem?

No clue. I don't use Windows, neither Chrome. I suspect you can all remove the old versions, I don't know why they are not removed. Probably something to report to Chrome. I don't know if Chromium suffers the same problem, but in any case from a user's point of view, the Chrome store is failing there.

**Comment by my-password-is-password** [comment]
Ok thanks.

Its a chrome problem. 

https://code.google.com/p/chromium/issues/detail?id=329943
