### ISSUE TITLE
Fix Broken page Isohunt

### ISSUE THREAD

**Issue by ialexsilva** [uBlock-LLC/uBlock#355]
http://isohunt.to/ is broken
Version 38.0.2125.111 m (64-bit) / uBlock 0.7.0.9 and default list of filters loaded.

**Comment by gorhill** [comment]
Same problem with ABP. [malwaredomains.com](http://www.malwaredomains.com/) blocks `isohunt.to`. I rather not create exceptions to hostnames in malware domains.

**Comment by gorhill** [comment]
[Why it was added](http://malwaredomains.lehigh.edu/files/domains.txt):

```
isohunt.to malicious malwareurls.joxeankoret.com/ 20141017
```

**Comment by gorhill** [comment]
So you can:
- Notify http://www.malwaredomains.com/ if you think it is a false positive
- Create you own exception filter

But countering an entry in a malware list for everybody is not an option here.
