### ISSUE TITLE
the ‘Experimental features’ messed with jQuery icons

### ISSUE THREAD

**Issue by notxx** [uBlock-LLC/uBlock#357]
the jQuery icons are css sprites, and the image url of css sprites is related. because the path of css itself is now 'chrome-devtools://devtools/bundled/images/' based, the image url is now like 'chrome-devtools://devtools/bundled/images/ui-bg_glass_75_e6e6e6_1x400.png'.
so maybe attach these images into extersion package is one option, or we could just modify then image url in the css.

**Comment by gorhill** [comment]
OK I'm lost here. Where can I see the problem? A page is not rendered properly? URL?

**Comment by notxx** [comment]
http://api.jqueryui.com/theming/icons/
it's now like this
![image](https://cloud.githubusercontent.com/assets/785476/4937548/58e724b8-65c4-11e4-9a32-639be16ea6ef.png)
and it should be like this
![image](https://cloud.githubusercontent.com/assets/785476/4937569/780ee7b8-65c4-11e4-9f04-52982bc3963a.png)

**Comment by gorhill** [comment]
Look like this will be a limitation of local mirroring. The `chrome-devtools://` thing has nothing to do with the problem. Problem is that it seems the document containing the data: URL is used as the document from where the resource was loaded, and thus the relative URLs inside the CSS are expanded with the wrong location prefix.

This means we will have to exclude stuff from being locally mirrored.
