### ISSUE TITLE
Click to unblock temporarily a frame

### ISSUE THREAD

**Issue by dungsaga** [uBlock-LLC/uBlock#358]
I use Dynamic Filtering to block third-party frame, and I cannot see embedded Youtube video anymore. I wish that the blocked frame is visible with a button "Click to unblock this frame (url: http://youtube.com/...)", so that I can choose which frame I want to unblock temporarily.

**Comment by dungsaga** [comment]
This requested function seems conflict with option "Hide placeholders of blocked elements". I wonder if an exception can be made for blocked frame in this case.

**Comment by gorhill** [comment]
Fixed in 0.8.5.0: possible to create dynamic filtering exceptions (dark gray).
