### ISSUE TITLE
the ‘Experimental features’ messed with jQuery-UI datepicker l10n

### ISSUE THREAD

**Issue by notxx** [uBlock-LLC/uBlock#362]
it should look like this
![image](https://cloud.githubusercontent.com/assets/785476/4990759/ab7fdd9a-69c6-11e4-9ca0-6ae86cef73a8.png)
and now it's like this
![image](https://cloud.githubusercontent.com/assets/785476/4990761/bfee4226-69c6-11e4-97b6-f33f88462df7.png)
i think the root is base64'ed js file is not decoded using utf-8 charset.

**Comment by gorhill** [comment]
Is there a URL I can use to test for fixes?

**Comment by notxx** [comment]
http://jsfiddle.net/qo2o2s0j/

**Comment by notxx** [comment]
it looks like i've found the cure
change
data:application/x-javascript;base64,YWxlcnQoJ+a1i+ivlScp
into
data:application/x-javascript;**charset=utf-8**;base64,YWxlcnQoJ+a1i+ivlScp

then the javascript is decoded correctly.

check
http://jsfiddle.net/xf8ov1jj/
(sadly the jsfiddle editor is crushed by my code)

**Comment by gorhill** [comment]
> data:application/x-javascript;charset=utf-8;

I want to investigate further, I can't do this blindly. Some data is binary, sometimes it may be a charset. I may have to revive code I had, to extract charset.

**Comment by notxx** [comment]
JavaScript are always text, and always have charset of ISO8859-1 or utf-8. so I think always using utf-8 charset for JavaScript is acceptable.

发自我的 iPhone

**Comment by gorhill** [comment]
It's not only javascript being mirrored, it's not only text being mirrored. I [used to use charset before in the data: URI](https://github.com/gorhill/uBlock/blob/52538d1e4188d0039433d78f820d361b53290a32/js/mirrors.js#L219), until I converted to an ArrayBuffer. I will just bring back that code, which read the charset from the HTTP headers, not hard-coded.

I just wanted the real life scenario you encountered to inspect the HTTP header etc. to verify that all the information I need is in there in.

**Comment by notxx** [comment]
I could not find any public page with jqueryui l10n in Chinese or other eastern Asia locale.

发自我的 iPhone

**Comment by gorhill** [comment]
It's ok, [your jsfiddle here](http://jsfiddle.net/qo2o2s0j/) works as a test case.

**Comment by gorhill** [comment]
Ok looking into this now.

Unfortunately, the `charset` is not specified in the response headers when receiving the resource through XHR. That is a problem. I suspect that normally, the browser will use the charset of the page, if one for the resource is not specified. But it looks like the browser may not be doing this for when the resource is from a `data:` URI. I feel like there is a browser issue here given the inconsistency.

I can't hard-code for `UTF-8`, because it could very well happen the resource is actually in another charset. Anyway as said above, I can't also just blindly add `charset=`, given that the resource may be something else than text (`image/png`, `font/woff`, etc.)

**Comment by gorhill** [comment]
I will go with some heuristic to figure whether `charset=utf-8` can be slapped for when charset is not specified. Found [some documentation](http://dev.w3.org/2006/webapi/FileAPI/#enctype) which I will use as the rationale for now for the chosen solution:

> 5 . If the "getting an encoding" steps above return failure, then set encoding to null.
> 
> 6 . If encoding is null, then set encoding to utf-8.

**Comment by gorhill** [comment]
This [page](http://greenbytes.de/tech/tc/datauri/#l-plain-text-cs) says "with no charset (default should be US-ASCII)". If true, using UTF-8 seems entirely acceptable given UTF-8 intersects completely with ASCII over the ASCII set.

**Comment by notxx** [comment]
yeah. totally agree.

发自我的 iPhone
