### ISSUE TITLE
Yahoo mail ads are not being blocked 

### ISSUE THREAD

**Issue by victorh2007** [uBlock-LLC/uBlock#364]
µBlock used to block the banner ad in Yahoo mail, now it no longer does.

It's at the top of the inbox (inside the inbox).

Link to screen shot:

http://imgur.com/1dvhT8C

**Comment by gorhill** [comment]
I don't have a Yahoo mail account. If you get the same problem with ABP, then the issue rests with 3rd-party EasyList, and thus the issue needs to be raised with EasyList crew.

So if you can confirm the same problem occurs with ABP + same filter lists.

**Comment by gorhill** [comment]
Looks like someone else is having similar issue: https://adblockplus.org/forum/viewtopic.php?f=2&t=26118&sid=4fd49721e990b61f009dd8ba0d5b2482

**Comment by victorh2007** [comment]
Yes, it happens with Adblock Plus also.
