### ISSUE TITLE
Broken layout on https://codeanywhere.com/

### ISSUE THREAD

**Issue by trietbui85** [uBlock-LLC/uBlock#371]
When uBlock is enabled, layout of https://codeanywhere.com/ is broken.

**Comment by gorhill** [comment]
Working fine from here.

I had one occurrence where the layout was broken, and in the console there was a 404 error message about one of the CSS file. But refreshing the page, and the server properly returned the resource.

**Comment by gorhill** [comment]
I got a few more occurrences of 404 ("not found"), including with Adblock Plus (uBlock disabled). To me it seems the site is just failing to return the `https://codeanywhere.com/min/production.min.css` resource on a random basis. So more like a server problem, unrelated to uBlock.

**Comment by trietbui85** [comment]
I see. It's fine to close this issue.
Thanks.
