### ISSUE TITLE
statistics tab in RTL (Hebrew) is uncomfortable to view and interact

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#375]
When viewing the statistics tab in RTL language (Hebrew, for example), the data that should only appear as LTR (like URLs, filter) is aligned as RTL.

<h2>2 Issues:</h2>

<h4>First:</h4>

The data that should be LTR:
1. Filters - Appear backwards and hard to copy.
2. URLs - Appear on the right side of the cell, and hard to copy.
3. Types - IMO should have the strings on Crowdin, but as of it now.. oh well...

The data that should stay RTL:
1. Headers

<h4>Second:</h4>

I also think that all the data should be placed in the center of it's cell (except domain and logAllowed/logBlocked headers), without any use of explicit margins and paddings.

Simple `text-align: center` ?

**Comment by gorhill** [comment]
Ugh... I wanted to see the bug and here is what I experienced: https://code.google.com/p/chromium/issues/detail?id=432088

Don't you have this problem?

**Comment by Mikey1993** [comment]
@gorhill Nope, I am on Canary channel and I don't see this issue (and never did), but it's unrelated to this issue I presume..

**Comment by gorhill** [comment]
Ok for Filters and URLs, fixed.

For Types, these can be used in a filter as is, which would not work if translated.

For alignment, I refer the current way, URLs/filters anchored to the right.

**Comment by Mikey1993** [comment]
@gorhill 
First of all, thanks for fixing this.
Second, can you please elaborate about the reason behind not translating Types? I don't really get to the bottom of your sayings..
I believe it should be consistent as done with the translation of uMatrix.

**Comment by gorhill** [comment]
In uMatrix, types in _"My rules"_ are not translated, as they are part of the syntax.

In uBlock, types can be part of the syntax too: `||example.com^$image`. So if someone wanted to create a net filter out of a request in the log, I believe it is better if they can see the type which can be used as is to craft a filter.

**Comment by Mikey1993** [comment]
I see.
Thanks for clarifying this.
