### ISSUE TITLE
Error loading plugin: plugin file not found

### ISSUE THREAD

**Issue by phypan11** [uBlock-LLC/uBlock#377]
This is exactly same issue as #166. Please refer to http://www.ondemandkorea.com/three-meals-a-day-e06.html

This website shows Error loading plugin: plugin file not found as of now. It worked just fine before. Could you tell me how to fix it.

**Comment by gorhill** [comment]
I just tried it and it works fine from here, using the default filter lists.

What filter lists you have selected?

**Comment by gorhill** [comment]
Given that it works fine from here + no feedback for days, closing.
