### ISSUE TITLE
Feature: auto backup preferences to file every X time.

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#382]
It's a nice feature to have if you would like to backup your preferences every X time.

I, personally, would use it for my backup to be the as updated as it can be if something happens to my browser profile.

It really shines if you are using the BLOCK/allow-some policy, especially with 1st and 3rd contents, as I do.

It will also be a good practice to show the user when was the last time the backup procedure occurred, and show errors if the backup failed in the `About` tab.

**Comment by gorhill** [comment]
Not possible. It is not possible to save to disk without user interactions (the file picker dialog box). In the fight between security vs. convenience, security has the upper hand in browsers.

**Comment by kurtextrem** [comment]
`chrome.storage.sync`?

**Comment by gorhill** [comment]
> `chrome.storage.sync`?

#126
