### ISSUE TITLE
Uncaught SyntaxError when entering element picker mode

### ISSUE THREAD

**Issue by pwstokes225** [uBlock-LLC/uBlock#387]
On https://o.smium.org/.

**Comment by Deathamns** [comment]
[#L870](https://github.com/gorhill/uBlock/blob/master/src/js/element-picker.js#L870): disabled -> disabled="disabled"

[#L876](https://github.com/gorhill/uBlock/blob/master/src/js/element-picker.js#L876), [#L877](https://github.com/gorhill/uBlock/blob/master/src/js/element-picker.js#L877): missing closing tags for &lt;li&gt; 

[#L877](https://github.com/gorhill/uBlock/blob/master/src/js/element-picker.js#L877): &amp;ensp; -> \u2002
