### ISSUE TITLE
Chrome Web Store

### ISSUE THREAD

**Issue by puff-m-d** [uBlock-LLC/uBlock#389]
Hello,

Did you publish the latest version 0.7.0.11 to the Chrome Web Store? Normally Google pushes out new versions within 2 hours or less. It is now working on almost 2 days since you released 0.7.0.11. I am just wondering if the Chrome Web Store is delaying your latest version for some reason... Then again it may just be because of the holidays here in the States...

**Comment by gorhill** [comment]
Yes, published to the Chrome store, however it is marked "Pending Review". I suspect it's because [the whole project changed a lot since last version](https://github.com/gorhill/uBlock/compare/0.7.0.10...master) from the store's point of view.

**Comment by puff-m-d** [comment]
I had a feeling "Pending Review" might be the reason. Thanks a lot for your response.

**Comment by puff-m-d** [comment]
Chrome Web Store updated...
