### ISSUE TITLE
Could you add an overview of all whitelisted sites?

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#39]
Feedback from the Chrome store:

> Could you add an overview of all whitelisted (I mean: whitelisting by clicking the enable/disable button in the drop down menu) sites to the settings? What would be even better: an option to import/export those filters.

**Comment by gorhill** [comment]
I think I will work on this one next. I suppose many users have their customized whitelists they would like to import from other blockers.

**Comment by ghost** [comment]
Currently, there is no way to list all whitelisted websites. Forgotten websites could start to clutter that list.

An option to selectively remove a website from the list will solve the problem.
