### ISSUE TITLE
Unable to click certain links

### ISSUE THREAD

**Issue by fwosar** [uBlock-LLC/uBlock#390]
Using uBlock I am unable to click on certain links. This issue is most prominent on Reddit. For example:

http://www.reddit.com/r/chrome/

At the top of the page you can browse to other sub-reddits. All of those links are disabled for some reason except "Random".

**Comment by gorhill** [comment]
The links work for me.
- Browser/version?
- What filter lists do you have enabled?
- Do you have custom filters? If yes, which?
- Do you have dynamic filtering enabled for that site?

**Comment by gorhill** [comment]
Looks like same thing is happening to someone **without** uBlock installed: http://www.reddit.com/r/chrome/comments/2nwm1n/unable_to_click_certain_links/

**Comment by kurtextrem** [comment]
Had the same problem. I assume it's one of the things the chrome team is currently testing (regarding the renderer) - it's like always: the next update (hopefully) fixes that
