### ISSUE TITLE
Move `de` and `fr` translation to Crowdin

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#391]
@tlu1024, @tailHey:

It's just very tedious to do all the patching manually here. Crowdin does that automatically whenever I add/change strings, and also offers to notify translators whenever important changes occur.

Currently there are changes in `_locales/en/messages.json` which are not patched into the German/French versions. Crowdin would have done that without any extra work for me.

**Comment by tailHey** [comment]
I understand, it makes sense, what are we supposed to do? I don't see the French part in µBlock's Crowdin project page.

**Comment by ghost** [comment]
It's okay for me. Makes sense.

**Comment by gorhill** [comment]
@tailHey, ok I will create slots for French/German. I don't know if you guys can upload translations though, if not, I can do it, but then all translations will be in my name as if I was the author.

**Comment by tailHey** [comment]
@gorhill: If I can't upload the existing translation, I'll just play at copy-paste game :P

**Comment by gorhill** [comment]
I will give you "Manager" status, so you can upload `messages.json` for the target language: go to target language (French, German), than click little gear, then upload translated `messages.json` file. Does not work for the description though, for whatever reason.

I will downgrade to "Proofreader" once you are done importing.

**Comment by tailHey** [comment]
Uploaded, will work on remaining strings, thank you.

**Comment by gorhill** [comment]
Thanks all.

By the way, you can still push if you wish your translation work on github with the changed translations, it's just that it makes everything easier if all the Crowdin translations are in sync with the project here.
