### ISSUE TITLE
Dynamic Filtering UI friendliness issues

### ISSUE THREAD

**Issue by Strongbird** [uBlock-LLC/uBlock#393]
Heya. Big fan of this extension. I do have some qualms regarding the Dynamic Filtering UI, though.

1) The ? icon to go to the documentation. It's only visible when you hover over the line to close the matrix UI again. I'd advise making it visible whenever the box is open and also a slightly darker gray to make it more defined.

2) The script and iframe text does not stand out very well. I have heard complaints that, especially on monitors which are color-calibrated, the text is nearly invisible against the dark background. I'd advise darkening them along with the ? symbol.

3) Could use more tooltips. Basic functionality tooltips on hovering over each square would be appreciated. Overall, I've also noticed that the tooltips when hovering over the on/off icon and element picker icon feel /slightly/ too slow to pop up with their fade-in animation. Reducing that duration by ~100 milliseconds would be nice.

**Comment by gorhill** [comment]
3) is #346, fixed in 0.7.2.0.
