### ISSUE TITLE
A Small Request for uBlock

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#394]
Hi gorhill,

Can you please add Fanboy's Turkish list to default Regions, languages list in uBlock?
Here is the source : https://secure.fanboy.co.nz/fanboy-turkish.txt

Thanks,
yigido

**Comment by gorhill** [comment]
Problem with this list is that it appears abandoned: it hasn't been updated since June 2013.

**Comment by ghost** [comment]
I did not realize that. Sorry.
Anyway, I will add it manually.

Thanks,

**Comment by gorhill** [comment]
The list is licensed Creative Commons, so someone could copy it to its own project on Github and take over maintaining the list. If it is back to be maintained, I will include it.
