### ISSUE TITLE
Overzealous cosmetic filters

### ISSUE THREAD

**Issue by Landpaddle** [uBlock-LLC/uBlock#395]
There's an overzealous cosmetic filter in Fanboy’s Annoyance List‎ and Fanboy’s Social Blocking List‎ that hides an element of functionality on http://bandcamp.com/

div class="bcweekly-share-n-browse"
        div class="share-buttons"

This also contains the 'Browse past shows' link to peruse older Bandcamp Weeklies. Figured I'd bring this slight bit of breakage to your attention.

**Comment by gorhill** [comment]
You need to bring this to the attention of the maintainers: [Report incorrectly removed content](http://forums.lanik.us/viewforum.php?f=64)

**Comment by Landpaddle** [comment]
I've made a post, but it's not showing up on their forum list. Odd. I'm going to give it a day and assume they manually review new poster's topics before trying again.

**Comment by Landpaddle** [comment]
Alright, commit at https://hg.adblockplus.org/easylist/rev/e8c2a4a2e626 has been made. Feel free to close the issue. I will make sure to alert filter list maintainers in the future about these kinds of issues.

**Comment by gorhill** [comment]
> I've made a post, but it's not showing up on their forum list. Odd.

If you formally subscribe to the forum I think the posts will appear immediately, current behaviour is to prevent spamming.
