### ISSUE TITLE
R7.com

### ISSUE THREAD

**Issue by ialexsilva** [uBlock-LLC/uBlock#397]
How to reproduce:
1) Load http://www.r7.com/
2) The site keeps loading loop and links are unclickable...

I Have 39.0.2171.71 m (64-bit) and µBlock v0.7.0.11 with default list!

**Comment by gorhill** [comment]
As far as I can tell, culprit is

```
://adv.$domain=~forex-tv-online.com
```

in EasyList, which can be overriden by adding

```
@@://adv.$domain=www.r7.com
```

to your filters (to prevent a script from being blocked), until the fix is added to EasyList.

(paging @ryanbr)

**Comment by gorhill** [comment]
This needs to be reported to and fixed by maintainer of EasyList. Please report to them so that everybody can benefit the improvement: http://forums.lanik.us/viewforum.php?f=64
