### ISSUE TITLE
Element picker can pick its own elements

### ISSUE THREAD

**Issue by pwstokes225** [uBlock-LLC/uBlock#398]
![button](https://cloud.githubusercontent.com/assets/764704/5298905/122733ce-7c0d-11e4-8ab6-6f8d29076583.png)
Creating this cosmetic filter and reloading the page results in an element picker popup without buttons:
![buttonafter](https://cloud.githubusercontent.com/assets/764704/5298907/148cd4f2-7c0d-11e4-86df-5e0a775f16df.png)

**Comment by gorhill** [comment]
Fixed with 8693ab738d4638d994eee256f86d509ad1957aff.
