### ISSUE TITLE
Select element to block

### ISSUE THREAD

**Issue by roshambo1** [uBlock-LLC/uBlock#4]
Thanks for this, it's noticeably faster than adblock*. One thing I rely on that's missing is the ability to block an element from the context menu or at least clicking the icon and selecting an element to hide. Any plans to add something like this?

**Comment by gorhill** [comment]
See https://github.com/gorhill/uBlock/wiki/Element-picker

**Comment by fysics** [comment]
Love the fix! Super fast and easy to use.
