### ISSUE TITLE
It would be nice to be able to globally enable/disable the filtering

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#40]
Feedback from the Chrome store:

> It would be nice to be able to globally enable/disable the filtering (without having to disable the whole extension). Sometimes I want to browse multiple sites without adblockers and it's much easier to temporarily pause filtering globally than to turn it off (and then on back again later on) for each site separately.

**Comment by ghost** [comment]
I wouldn't mind this feature if it isn't too difficult to implement. But sometimes people are instructed by websites to just disable adblockers. So asking the user `are you sure?` would be a nice plus to allowing users to disable it completely globally.

**Comment by Baegus** [comment]
I think it's pretty unnecessary since you can just disable the extension with right click -> Manage.

**Comment by insanitybit** [comment]
Duplicating a feature that is already handled by the browser doesn't seem like the best thing to spend time on.

**Comment by gorhill** [comment]
So far it is unlikely I implement such a feature, because I just can't see a sensible case for it.

What is often referred as "Pause blocking everywhere" to me translate into "Allow tracking/data mining everywhere" [1], something which I have a hard time to find useful.

[1] uBlock's default filter lists is a statement it cares more than just "blocking ads".

**Comment by mozillamonks** [comment]
It's useful if you're part of points programs that require you to use affiliate links.

**Comment by ghost** [comment]
This is annoying enough for me that I've had to switch back to Adblock Plus, since that extension makes it easy to do this. I'm a fontend dev, so I have to frequently turn on and off all blocking to make sure the ads on the sites I develop aren't breaking the site.

> I think it's pretty unnecessary since you can just disable the extension with right click -> Manage.

Firefox doesn't make it that simple. You'd have to go to the extensions page, hunt for the extension, then disable it.

**Comment by gorhill** [comment]
> Firefox doesn't make it that simple. You'd have to go to the extensions page, hunt for the extension, then disable it.
- Open _Extensions_ page
- Pin it

Result: you now have one place now to enable/disable **all** add-ons, so you can easily test any add-on combo.

**Comment by gorhill** [comment]
As a side-effect of dynamic filtering, it's possible to disable uBlock for all sites:

![a](https://cloud.githubusercontent.com/assets/585534/6097114/04368716-af7e-11e4-8ca8-49ffdaa49fa6.png)

It's a matter of toggling global setting of `all` to `allow` (green) in the dynamic filtering pane.

So I close as fixed, since that side effect of dynamic filtering addresses the original issue.

**Comment by Gitoffthelawn** [comment]
For users researching this issue: See https://github.com/gorhill/uBlock/issues/255#issuecomment-106779773 for why the above workaround will not always work.

Summary: uBlock was improved to include strict blocking; this has the side-effect of breaking the above workaround.
