### ISSUE TITLE
Element picker button appearance on certain sites

### ISSUE THREAD

**Issue by pwstokes225** [uBlock-LLC/uBlock#401]
On http://example.com/ and http://example.org/:
![](https://cloud.githubusercontent.com/assets/764704/5327922/d257cca8-7db1-11e4-8e29-0b35c736d56c.png)

On https://live.com/:
![](https://cloud.githubusercontent.com/assets/764704/5328048/f74edb54-7db7-11e4-8b1b-35819b54c0bd.png)

On https://paypal.com/ and https://netflix.com/:
![](https://cloud.githubusercontent.com/assets/764704/5328082/9c01a086-7db9-11e4-94f2-6e18cffb7e41.png)

On http://horsenation.com/:
![](https://cloud.githubusercontent.com/assets/764704/5328038/9cd9f35c-7db7-11e4-9a96-86742a5be705.png)

**Comment by gorhill** [comment]
By the way, I could not load `https://live.com/` for whatever reason, but by the look of it, resetting the default `min-width` should fix the problem there.

**Comment by pwstokes225** [comment]
That site seems to require inline `script` tags. Perhaps that is why it would not load?
Looking now, `min-width` does appear to be cause, so your fix should work.

**Comment by gorhill** [comment]
I am not blocking scripts. Here is what Chromium tells me:

> Chromium's connection attempt to live.com was rejected. The website may be down or your network may not be properly configured.

Weird.
