### ISSUE TITLE
Can't click on Dropbox's "Set visibility / expiration" option

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#408]
As [reported on reddit](http://www.reddit.com/r/chrome/comments/2nqyeu/so_many_adblock_versions_which_should_i_use/cmp5und):

> Was trying to share a file via Dropbox using the "Set visibility / expiration" option. Clicking that link doesn't do anything in uBlock, but works fine in Adblock and Adblock Plus.

I am also waiting for some feedback re:

> What filter lists did you have selected in uBlock?
> What filter lists did you have selected in ABP?

**Comment by gorhill** [comment]
I don't have a Dropbox account. So if somebody feels like investigating this one... I will try to create on later on this week when I have time.

**Comment by my-password-is-password** [comment]
I couldn't reproduce the clicking "set visibilty / expiration" not doing anything.  If they mean clicking the radio buttons after clicking "set visibilty/ expiration"... i think you need a pro/business account, https://www.dropbox.com/en/help/5888  . 

![ublockdropbox1](https://cloud.githubusercontent.com/assets/6408935/5361781/dbf489f4-7f82-11e4-972d-0922b1e06b2a.gif)

The only problem I had when enabling every filter list was a japanese list blocking 

```
logger-
analytics-
```

which would stop showing the folders or files on dropbox.

![ublockdropbox2](https://cloud.githubusercontent.com/assets/6408935/5361867/71ad861c-7f83-11e4-886c-3fdf0354bc89.png)

Used this to fix it.

```
@@logger-$script,domain=dropbox.com
@@analytics-$script,domain=dropbox.com
```

**Comment by gorhill** [comment]
[OP said it was Fanboy Social](http://www.reddit.com/r/chrome/comments/2nqyeu/so_many_adblock_versions_which_should_i_use/cmpyj5s). He wasn't testing ABP with same filter lists as with uBlock. You could still submit your findings to [Report incorrectly removed content](http://forums.lanik.us/viewforum.php?f=64)
