### ISSUE TITLE
Blocking Speedtest.net

### ISSUE THREAD

**Issue by kuutamosusi** [uBlock-LLC/uBlock#409]
![untitled](https://cloud.githubusercontent.com/assets/9836897/5381305/8ccff396-80a8-11e4-8316-72dad9a58f36.png)

**Comment by sooqua** [comment]
"hpHosts’s Ad and tracking servers"‎ filter is to blame

**Comment by gorhill** [comment]
Thanks for the finding @sooqua.

**Comment by tp0** [comment]
Is there a whitelist rule can be used with the hpHosts’s list?
