### ISSUE TITLE
Tripadvisor

### ISSUE THREAD

**Issue by 0xBRM** [uBlock-LLC/uBlock#411]
Take [Restaurant Gordon Ramsay](http://www.tripadvisor.com/Restaurant_Review-g186338-d719242-Reviews-Restaurant_Gordon_Ramsay-London_England.html) for example. Can't open the photos, nor change the language unless you whitelist the whole domain/page.

**Comment by sooqua** [comment]
Disable the "Fanboy’s Annoyance List‎" filter

**Comment by 0xBRM** [comment]
@sooqua Must I really for a single entry? 

> tripadvisor.com##.overlay

**Comment by sooqua** [comment]
You can write an exception:
tripadvisor.com#@#.overlay
in Your filters

**Comment by 0xBRM** [comment]
@sooqua You're right, wasn't familiar with the syntax so I was the one to blame. Thanks.

**Comment by gorhill** [comment]
> You can write an exception

Or better, report the problem to [EasyList crew](http://forums.lanik.us/viewforum.php?f=64) so that the problem can be fixed for the benefit of all.

**Comment by 0xBRM** [comment]
@gorhill [Done](https://hg.adblockplus.org/easylist/rev/e9ddd3f39fe2).
