### ISSUE TITLE
In mac, how to do ctrl-click? 

### ISSUE THREAD

**Issue by byzhang** [uBlock-LLC/uBlock#412]
When I press "control" in the keyboard, and click the mouse, it's right click and shows context menus.

**Comment by gorhill** [comment]
Someone [mentioned](https://github.com/gorhill/uBlock/issues/182) that the Command key needs to be used instead of Ctrl.

**Comment by byzhang** [comment]
Thanks!

**Comment by JMoVS** [comment]
maybe this should be told as such in the case of an OS X operating system
