### ISSUE TITLE
Domain whitelist. (modify)

### ISSUE THREAD

**Issue by bestpika** [uBlock-LLC/uBlock#413]
How do I write domain whitelist rule?
(3rd-party filters)

this site

> http://2nyan.org/wallpaper/

hava the ad script

> googlesyndication.com^$third-party

but it had adblock killer script
when I open any image link, then it will redirect to http://2nyan.org/share/please_turn_off_adblock.html
(it said I have to close adblock or add @@||2nyan.org^$document to whitelist)
(I know $document not support)

How could I write domain whitelist rule?

> @@||2nyan.org^

(not work)

or other?
(I write it in a text file and put it on Internet to subscribe)
https://googledrive.com/host/0B6idnXD_0g9XNDlLWjVTWGlCbDg/abp/demo.txt

**Comment by my-password-is-password** [comment]
![ublockwhitelistdomain](https://cloud.githubusercontent.com/assets/6408935/5427067/8e0eecba-8339-11e4-9add-925967a47389.png)

I was able to see the images when I did this.

**Comment by gorhill** [comment]
> How could I write domain whitelist rule?

Click the green button to disable uBlock for the hostname of a web page:

![popup](https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/popup-1.png)

**Comment by my-password-is-password** [comment]
@gorhill, I was trying to comment out a line in the Whitelist tab with a '!' and "#" but the textarea turns red and the "Apply changes" button stays disabled.  If comments aren't allowed, i'm cool with that.  Not asking you to add it.  Just wondering.

**Comment by gorhill** [comment]
@my-password-is-password The whitelist field does not support commenting out. This is something I have added locally though (not checked-in yet), [as part of fix to bug #405](https://github.com/gorhill/uBlock/issues/405#issuecomment-66614521). A special noop exception bucket will be created just to hold commented out whitelist directives.

**Comment by bestpika** [comment]
I know [Whitelist] tab, but I want to use [3rd-party filters] to subscribe my rule list.
And I write

> @@||2nyan.org^

in [Your filters] > WORK
but in my text file > NOT WORK

I don't know why...

may be you can try subscribe my text file (only this file) and browse the web site ( http://2nyan.org/wallpaper/ ).
https://googledrive.com/host/0B6idnXD_0g9XNDlLWjVTWGlCbDg/abp/demo.txt

**Comment by gorhill** [comment]
> but in my text file > NOT WORK

How about:

```
@@|http:$domain=2nyan.org
@@|https:$domain=2nyan.org
```

This will whitelist all requests originating from `2nyan.org`.

**Edit 1:** By the way, your block filter should be `||googlesyndication.com^$third-party` instead of `googlesyndication.com^$third-party` (it helps to be more specific where possible).

**Edit 2:** `@@||2nyan.org^` should work in the text file. You have to ensure to purge the cache for your remote text file (then _"Apply changes"_) in order to force a reload of the changed content.

**Comment by bestpika** [comment]
I edit my demo.txt

> https://googledrive.com/host/0B6idnXD_0g9XNDlLWjVTWGlCbDg/abp/demo.txt

and [Purge all caches] then [Update now]
then clean chrome cache
then browse http://2nyan.org/wallpaper/
then open any image link...
...redirect to http://2nyan.org/share/please_turn_off_adblock.html ...orz

(I am only subscribe this demo.txt)

I try browse http://2nyan.org ...the script still blocked
![img](http://i.imgur.com/dxOZvlN.png)

well, this is work

> @@||googlesyndication.com^$domain=2nyan.org
> https://googledrive.com/host/0B6idnXD_0g9XNDlLWjVTWGlCbDg/abp/demo2.txt

this is still not work

> @@||2nyan.org^

**Comment by gorhill** [comment]
> in [Your filters] > WORK
> but in my text file > NOT WORK

Ok, I see what is happening: You do not have _"Your filters‎"_ selected in the _"3rd-party filters"_ tab, which means that your custom local filters are not enforced, hence nothing is blocked on the site: that why it "worked" with _"Your filter"_.

Now, once your filters are enforced, the site detects the blocking, and redirect to that warning page.

Since uBlock doesn't support `$document` and since from what I understand your want to "whitelist" the site using a filter list (for other people to use I suppose), then what I suggested above works:

```
@@|http:$domain=2nyan.org
@@|https:$domain=2nyan.org
||googlesyndication.com^$third-party
```

If you put this into the remote file, it should work as well. Change your file to the above and I will test again from my side.

**Comment by my-password-is-password** [comment]
I think he misunderstanding what @@||2nyan.org^ does.

show_ads.js is from googlesyndication.com so @@||2nyan.org^ has no affect on it.

if it was http://2nyan.org/show_ads.js then that filter would affect it.

**Comment by bestpika** [comment]
I think I misunderstanding the @@ rule...
Domain whitelist rule not use @@||abc.com...

**Comment by gorhill** [comment]
@my-password-is-password Yes, this would work even better:

```
@@||googlesyndication.com^$script,domain=2nyan.org
```

Instead of my three filters.

**Comment by bestpika** [comment]
So...I write rule domain whitelist in [3rd-party filters] have to like this?

> @@|http:$domain=2nyan.org
> @@|https:$domain=2nyan.org

**Comment by gorhill** [comment]
> So...I write rule domain whitelist in [3rd-party filters] have to like this?

Actually use this one only instead, more concise:

```
@@||googlesyndication.com^$script,domain=2nyan.org
```

This means: do not block scripts from `googlesyndication.com` when visiting `2nyan.org`. This way you do not need to whitelist the whole site.

_Whitelisting_ means to completely **disable** uBlock for a specific site, page, etc.

Filters starting with `@@` are **exception** filters, to cancel _existing block_ filters.

**Comment by gorhill** [comment]
This is what I get with `@@||googlesyndication.com^$script,domain=2nyan.org` + default filter lists:

![a](https://cloud.githubusercontent.com/assets/585534/5427579/1cca420a-8372-11e4-8deb-3074750e6d27.png)

**Comment by bestpika** [comment]
Yes, it works. Thanks a lot.

**Comment by my-password-is-password** [comment]
And you can add `2nyan.org##ins` to hide those boxes under the image
