### ISSUE TITLE
Element picker popup language inheritance

### ISSUE THREAD

**Issue by pwstokes225** [uBlock-LLC/uBlock#414]
This leads to some font inconsistencies.

Consider http://rakuten.co.jp/
![rakuten](https://cloud.githubusercontent.com/assets/764704/5435399/e1d2a9a0-84a5-11e4-96ee-04ed6a5fba2c.png)

or https://mail.ru/
![mail](https://cloud.githubusercontent.com/assets/764704/5435402/e5e8607a-84a5-11e4-951e-1792edcd88e4.png)

**Comment by gorhill** [comment]
I can't reproduce on Chromium/Linux. Something specific to Windows and/or Chrome?

![a](https://cloud.githubusercontent.com/assets/585534/5435703/dd91ee0c-842b-11e4-888a-088e8655130f.png)

**Comment by pwstokes225** [comment]
Chrome seems to be choosing an appropriate font given the `lang` attribute of the webpage.
For Japanese, monospaced text appears in "MS Gothic" and normal text appears in "MS PGothic". I imagine both of these fonts are indeed specific to Microsoft Windows.

**Comment by gorhill** [comment]
> given the lang attribute of the webpage

From what I read, I can set the `lang` attribute for specific elements. Will see if this helps.

**Edit 1:** It works.
**Edit 2:** However it dos not work if the brower itself is launched using `ja` locale. In this case, it appears I cannot prevent the bad font from being used, using `lang` has no effect. Looks like a Windows Chrome-specific issue there (fonts looks fine with Linux/Chromium)
