### ISSUE TITLE
Support built-in external filter lists

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#418]
This will allow to add filter lists as built-in filter lists, but without increasing the storage footprint of uBlock. Any filter lists which is not critical do not really need to be part of the package, though they may be offered as a choice in the selection of lists.

Example, from Chrome store:

> Can you add Prebake (filters obtrusive EU cookie law notices) to uBlock filter list?

Not critical to the point of having to package it, but nice to have as a built-in list which can be enabled with a simple checkbox.

**Comment by ghost** [comment]
Given that this is now supported, would it be possible to add the "Adblock Warning Removal List" to the default lists?

Last I remember, it wasn't added due to licensing concerns about bundling it, but I see no harm in downloading it externally.
