### ISSUE TITLE
Memory leak each time popup UI is brought up

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#419]
This is really a Chromium bug ([first reported for µMatrix](https://github.com/gorhill/uMatrix/issues/79)). This affects _all_ extensions (except maybe event page-based extensions):

https://code.google.com/p/chromium/issues/detail?id=441500

Starring the Chromium issue may help.

**Comment by RandomAcronym** [comment]
This bug has finally had someone assigned to it.

**Comment by chrisaljoudi** [comment]
@gorhill http://src.chromium.org/viewvc/blink?view=revision&revision=191383

:)

Do you know whether patches like this have to travel all the way down the release chain? (`Canary` -> `Beta` -> `Stable`?)

**Comment by kurtextrem** [comment]
It will be merged into stable I assume.

**Comment by Stanzilla** [comment]
Yay, bug is marked as fixed

**Comment by gorhill** [comment]
"M-43" means Chromium 43 I am guessing?

**Comment by kurtextrem** [comment]
Yeah, I've asked now. Although stable will have to wait a while... it has been updated this week.
