### ISSUE TITLE
z-index higher than greatest value

### ISSUE THREAD

**Issue by kurtextrem** [uBlock-LLC/uBlock#421]
http://www.sitepoint.com/managing-css-stacking-contexts-hostile-environment/ "How big can z-index be anyway?". No need to use 4999999999 and 5999999999 when 2147483648 is the highest value possible

**Comment by gorhill** [comment]
Why is this an issue?

**Comment by kurtextrem** [comment]
Does it make sense to use a higher value than the highest value possible? It's not really a huge deal or something, but it could be irritating if you look through the source ("so the 599... element has a higher index than the 499.." and in reality they have the same)

**Comment by gorhill** [comment]
The spec doesn't set a max. The author makes an unbsustantiated assumption about all implementations. I don't have to buy his assumption, and I don't. Actually, it appears Chromium uses `float`. Please, I rather spend time on real issues (give me a case where a real problem occurs), not dreamed ones.

**Comment by gorhill** [comment]
Sorry for having been snappy. The fact that it's the [second time](https://github.com/gorhill/uBlock/issues/209) you open an issue for such a non-issue didn't help however.

**Comment by kurtextrem** [comment]
No worries. Yeah, I know that it's the second time. I wasn't sure if you
get a notification once it's closed (I can't reopen). Sorry for wasting
your time (again), I didn't mean it as huge issue, just a friendly poke
about it. :)
Am 17.12.2014 23:31 schrieb "Raymond Hill" notifications@github.com:
