### ISSUE TITLE
uBlock prevents google fonts from loading sometimes

### ISSUE THREAD

**Issue by cosban** [uBlock-LLC/uBlock#427]
The issue begins if a font loaded from the google fonts api is used on an external site which links to a separate site using the same font. If the link which connects the two is clicked, the font begins to not load on both sites.

Below is proof of the bug:
This is the site before navigating to it from another domain.
![image](https://cloud.githubusercontent.com/assets/849963/5516039/749749b6-8844-11e4-816a-2e366f5ac4c1.png)

ublock prevents the font from loading after navigating to it from the other site (clicking a link)
![image](https://cloud.githubusercontent.com/assets/849963/5516036/51b8832e-8844-11e4-8668-8e7b2ef26040.png)

This is the error message within the console.
![image](https://cloud.githubusercontent.com/assets/849963/5516030/10a81bba-8844-11e4-8b55-748ce61c7913.png)

ublock is then turned off which allows the font to load:
![image](https://cloud.githubusercontent.com/assets/849963/5516055/dc1af380-8844-11e4-92a7-937d408c88f3.png)

The issue is able to be fixed by clearing the browser cache, but upon performing the navigation sequence again, the bug is reproduced.

**Comment by gorhill** [comment]
Do you have _"Experimental features"_ selected?

**Comment by cosban** [comment]
The issue does not persist if experimental features are turned off so if this issue does not fall under the correct umbrella, it may be closed.

**Comment by gorhill** [comment]
Ok so it's a dup of #291.
