### ISSUE TITLE
[Fanboy's Social] Issues with font-family: FontAwesome

### ISSUE THREAD

**Issue by lellerez** [uBlock-LLC/uBlock#428]
For some reason µBlock prevents Chrome from showing FontAwesome font.
- I've tested with IE 11 and it works well
- I've tested with Chrome and disabled µBlock -> works just fine
- I've tested with Chrome + µBlock without selecting any block list -> still doesn't work

Example screenshots:

http://i.imgur.com/Vz1laMs.png
http://i.snag.gy/MCYGG.jpg

Example site: http://murobbs.muropaketti.com/ (eg. reporting button icon, forum's first page icon etc...)

**Comment by gorhill** [comment]
Did you enable _"Experimental features"_? If so, that would be a dup of #291.

**Comment by gorhill** [comment]
No feedback, but from the look of it certainly dup of #291.

**Comment by alanc10n** [comment]
I'm seeing this problem without Experimental Features enabled, on Windows (Chrome 39.0.2171.95) and Linux (39.0.2171.65 Ubuntu 14.04). I am using a brand new, stock install of uBlock. To repro, go to http://fontawesome.io/icons/ and search for "fa-twitter". You'll see that this icon, and several others, like fa-linkedin, fail to load. Disable blocking and they render correctly. Let me know if there is more info I can provide to help run this down. Note that most of the icons load fine in either case, and only some fail to load when blocking is enabled.

**Comment by gorhill** [comment]
Ah ok. This is a filter list issue: _Fanboy Social Blocking List_. This was brought to them before, they are aware: http://forums.lanik.us/viewtopic.php?f=64&t=17545.

**Comment by alanc10n** [comment]
Oh, I see now. Thanks!

**Comment by CumpsD** [comment]
Verified, turning off that list lets me see fontawesome icons on sites again :)

Is there a way to not disable the list entirely but just some entries in it?

**Comment by gorhill** [comment]
> Is there a way to not disable the list entirely but just some entries in it?

No.

**Comment by ghost** [comment]
Is there a possibility of something similar to this being added?
Being able to disable filters without disabling the entire list is very useful.
![abp_preferences_2](https://cloud.githubusercontent.com/assets/4343306/5848439/1dc9db44-a19e-11e4-8790-71b176e059a7.png)

**Comment by gorhill** [comment]
@hotdogman Issue #68.

Keep in mind uBlock is different, and I don't have as a goal to be a UI clone of ABP. My approach is to look at what problems we are trying to solve, and offer the solution which I think best resolve that problem, not merely cloning ABP's features. Efficiency will **never** be sacrificed in the name of cloning ABP's features.

One purpose of [dynamic filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide) is to get the ability to override static filtering (_EasyList_, _EasyPrivacy_, etc.) It works well for the most part to solve the same problems which the filter lists solve in your screenshot.
