### ISSUE TITLE
Report the filter list containing the filter of a blocked request

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#43]
I saw it as a separate issue, it was [originally reported](/gorhill/uBlock/issues/12#issuecomment-47338369) in #12 by @zerkms:

> Just as a minor addition: it also might be helpful to show not only the exact filter applied, but also a subscription name that it came from.

**Comment by gorhill** [comment]
Ideally, the exact filter list and line in that list would be great.

**Comment by gorhill** [comment]
Not a straightforward feature. If uBlock were to keep track of where each filter originate exactly, it would gain a good chunk of memory and CPU footprint. Not going to happen. However, another solution is to reverse lookup, which in the current case is completely acceptable, since it's only a UI thing, and only for users which have an interest in that kind of information.

**Comment by gorhill** [comment]
With the compiled filer lists in 0.8.8.5, this feature become closer to feasibility.

A compiled filter list could have an extra field which would be the offset at which the original filter is to be found in the original raw filter list.

It should be possible to infer a compiled filter entry from any live filter. So it would be a matter of finding the inferred compiled filter entry in any of the compiled filter lists which have been used to load the current filters. Since we are dealing with normalized entry, a plain string search can be used, fast.

But still, this will have to be on-demand only, as pointed out somewhere above. But more technically feasible now.

**Comment by chrisaljoudi** [comment]
#1232
