### ISSUE TITLE
YouTube issue

### ISSUE THREAD

**Issue by Windstapper** [uBlock-LLC/uBlock#431]
![untitled](https://cloud.githubusercontent.com/assets/10179290/5520239/32a84f36-8980-11e4-9a3e-36b471ee6db3.png)

How do I block this? I have Canary 41.0.2256.0. Forgot to mention uBlock version 0.8.2.1.

**Comment by gorhill** [comment]
Give me the URL. Also, how were you blocking it before using uBlock?

**Comment by Windstapper** [comment]
https://www.youtube.com/watch?v=JGCsyshUU-A

I haven't used any other blocker than uBlock, uBlock is the only blocker I trust.

**Comment by gorhill** [comment]
It's a Youtube setting:

![a](https://cloud.githubusercontent.com/assets/585534/5520275/8128bbca-8947-11e4-8af0-bacf1c9e6063.png)

**Comment by Windstapper** [comment]
Gosh dang it. _Sense of shame_
