### ISSUE TITLE
Need to update memory footprint screenshot in Chrome store

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#435]
This screenshot is dated, it's from when Chromium was leaner, when the filter lists were somewhat smaller, and when Fanboy Social Blocking List was not selected by default.

**Comment by kurtextrem** [comment]
(this time no own issue)
Merry christmas to you and your family. Thanks for the great ad blocker and privacy guard.

**Comment by gorhill** [comment]
@kurtextrem Thanks by the way.

Screenshot was updated at some point, I will update it again whenever I feel it is outdated.
