### ISSUE TITLE
Weird whitelist issue

### ISSUE THREAD

**Issue by kurtextrem** [uBlock-LLC/uBlock#436]
First of all:
I have "https://www.youtube.com/" in my whitelist (whitelists the homepage of youtube only).
Problem:
I watch a video (https://www.youtube.com/watch?v=Zcez5g4eJjQ for example), click the uBlock icon, click the green power button. It turns gray, as it should. However, after focusing the video page again, the uBlock browser action icon is still red. Upon reloading it stays red. Nothing is added to the whitelist.
Expected:
The whole youtube domain is added to the whitelist.

Notes:
I suspect a change in 0.8.2.1 (can't tell if 8.2.0 as well) as 0.8.1.2 was working.

**Comment by gorhill** [comment]
Ugh sorry. Silly bug. Will fix asap.

**Comment by gorhill** [comment]
Ok good thing is that this happened only in scenarios resembling yours, i.e. having an already existing page-based whitelist directive, meaning the likelihood of most users being unable to whitelist as in your scenario was probably very low. At first I though it was affecting everybody.

**Comment by kurtextrem** [comment]
Yeah, no hurries. That's why I named it "weird", as it probably didn't affect anybody apart from me because of my weird settings.
