### ISSUE TITLE
uBlock doesn't show custom filters in network requests

### ISSUE THREAD

**Issue by mikhaelkh** [uBlock-LLC/uBlock#439]
For example, go to `https://nnm-club.me/` with and without filter `nnm-club.me###header > .b-page_newyear > .b-head-decor`. Statistics is the same.

**Comment by gorhill** [comment]
Cosmetic filters are not network filters, hence they do not show in the network request log.

**Comment by mikhaelkh** [comment]
Ok. It would be nice if you add them too.
