### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document'

### ISSUE THREAD

**Issue by gavin20** [uBlock-LLC/uBlock#440]
Hello,

Recently I've noticed the following reoccurring message via Chrome console for any page I navigate to -

 **Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '[href^="//adbit.co/?a=Advertise&"],
[onclick^="window.open('http://adultfriendfinder.com/search/"],
a[data-redirect^="this.href='http://paid.outbrain.com/network/redir?"],**

Complete message located here: http://pastebin.com/GHUZbwaz

Please let me know if you require additional details. Thank you.

**Comment by gorhill** [comment]
You have custom filters?

**Comment by gorhill** [comment]
In the pastebin content, I see cosmetic filters which are not possible. The `important` filter option applies only to network filters, not cosmetic filters. Cosmetic filters have to be legal CSS rules, or else expect uBlock to break.

**Comment by gorhill** [comment]
All these filters are invalid filters:

```
div[class="xpdopen"]^$important
div[class="tvcap"]^$important
div[class="_Ak c"]^$important
div[class="_OKe"]^$important
div[class^="_OKe"]^$important
partnership_analytics^$important
Twitch.tracking^$important
ad_actions^$important
advertisement new_advertisement^$important
```

And assuming you remove the illegal `^$important` part, the following entries are unlikely to accomplish anything, I am not aware of any HTML tags matching any of these:

```
partnership_analytics
Twitch.tracking
ad_actions
advertisement new_advertisement
HID[class="appbar-guide-notifications"],
google_companion
VIEWSTATE
```

So you are using nonsensical cosmetic filters. See [Writing Adblock Plus filters](https://adblockplus.org/en/filters)

**Comment by gavin20** [comment]
Understood - I'll remove all of my custom filters and rebuild. Thanks

**Comment by gorhill** [comment]
There is really not much uBlock can do here, it's the old computer maxim: [garbage in garbage out](http://en.wikipedia.org/wiki/Garbage_in,_garbage_out).
