### ISSUE TITLE
"Can't find variable: pR" and a broken websites in Safari on mac

### ISSUE THREAD

**Issue by VFK** [uBlock-LLC/uBlock#444]
On some websites i'm getting the error `Can't find variable: pR` in console and all website's scripts looks broken.
_flickr.com_ - try to open any photo and the page won't be fully loaded.
_hummingbird.me_ - i see only a blank gray page.
There are other sites with the same error, but i don't remember which.
I'm getting this error only on Safari, chrome works fine.

**OSX Yosemite 10.10.1 (14B25)**
**Safari 8.0.2 (10600.2.5)**
No other extensions except **uBlock 0.8.2.3**

**Comment by Deathamns** [comment]
That was a typo, which has been fixed, just not pushed to the master branch.
If you're building if for yourself, then you can build it from [here](https://github.com/Deathamns/uBlock/tree/ports/xpi), or change pR to rS in this [line](https://github.com/gorhill/uBlock/blob/master/platform/safari/vapi-client.js#L362).
