### ISSUE TITLE
Would you support ABP_Link?

### ISSUE THREAD

**Issue by ivysrono** [uBlock-LLC/uBlock#446]
Test:https://code.google.com/p/my-abp-lists/

**Comment by gorhill** [comment]
Dup of #224?

**Comment by ivysrono** [comment]
yes.
This and sync settings are most important tasks fo ublock,in my opinion.

**Comment by arcaneAgilmente** [comment]
The issue with syncing is that ublock and umatrix both quickly get bigger than the allotted space google lets extensions sync.
I simply export settings for both extensions and then save them to google drive every now and then.

**Comment by vitorgalvao** [comment]
> The issue with syncing is that ublock and umatrix both quickly get bigger than the allotted space google lets extensions sync.

If the lists themselves were being synced, that’d be a problem, but doing that wouldn’t make sense. The only thing that would need to be synced is a list of what lists the user wants. Yes, this can become a problem if you start adding a large number of custom filters, but if you have that much, at that point maybe it makes sense to build an external list yourself.

**Comment by gorhill** [comment]
Yes, I thought about not saving the custom filters themselves (as someone could cut and paste _"Fanboy's Ultimate"_ in there, there is no restriction).

However the other issue that is holding me back is the fact that fetching resources remotely (teh sync "cloud") at start up time could cause a delay in how fast uBlock (or uMatrix) are up and ready to filter. I worked hard to resolved as best can be that issue for uBlock, and introducing the need to poll a remote server at start could undo all that work to ensure very quick readiness, and yet again having users come back to complain about how uBlock doesn't filter as expected existing tabs at start-up time.

Maybe a way to address this is to just warn the user that there is remote data available for fetch, and let the user pull explicitly by clicking a button, upon which uBlock would pull the remote data then force-restart itself once complete.

**Comment by gorhill** [comment]
Dup of #224.
