### ISSUE TITLE
Adware Medic finds DreamsAdNetwork in ublock extension

### ISSUE THREAD

**Issue by JustinAiken** [uBlock-LLC/uBlock#449]
Installed uBlock through the [Chrome Store](https://chrome.google.com/webstore/detail/cjpalhdlnbpafiamejdnhcphjbkeiagm)...

Running Adware Medic flags the extension: 

![ublock](https://cloud.githubusercontent.com/assets/1568662/5575295/95c47d14-8f94-11e4-9784-fa14a4d69e14.png)

I'm going to guess that's a false-positive - some URL in one of the blacklists triggering it?  Thought I should mention it though...

**Comment by gorhill** [comment]
Yes, I can see `||dreamsadnetwork.com^` in the Japanese filter list (the non-obsolete one).

There have been other cases where apparently some malware removal tools spot something in one of the filter lists which ship with the extension (one was TSM Adware finding `yontoo` in EasyList/hpHosts). I've seen comments in the past about "Avast! not liking uBlock".
