### ISSUE TITLE
Weird blocking behavior

### ISSUE THREAD

**Issue by rauchg** [uBlock-LLC/uBlock#451]
I believe it's eagerly filtering JS / DOM elements based on the `twitter` match?

socket.io homepage with extension:
![image](https://cloud.githubusercontent.com/assets/13041/5589486/cb3f5fde-90fe-11e4-83e8-26f21f6d7486.png)

without extension:
![image](https://cloud.githubusercontent.com/assets/13041/5589489/d5ca3096-90fe-11e4-88a5-74b97ac87d64.png)

I understand if `uBlock` wants to block the Twitter platform widgets, but the other demo is hosted 100% by us.

Thanks for the great extension!

**Comment by gorhill** [comment]
It's because of the `##.tweets` filter present in _"Fanboy's Social Blocking List"_. You need to [report to them](http://forums.lanik.us/viewforum.php?f=64) so that they fix it. You will get same behavior with ABP + _"Fanboy's Social Blocking List"_.

**Comment by gorhill** [comment]
I should have added, meanwhile you can use a custom filter as a workaround: `socket.io#@#.tweets` should work.

**Comment by gorhill** [comment]
Fixed by Fanboy: https://hg.adblockplus.org/easylist/rev/fa0c93ed117a
