### ISSUE TITLE
Github Issue

### ISSUE THREAD

**Issue by gpedro** [uBlock-LLC/uBlock#452]
![gh problems](http://i.imgur.com/DjNwMiq.png)

I've tested and is caused by uBlock 

I'm using Chrome 39.0.2171.95 (64-bit), OSX 10.9.5

**Comment by gorhill** [comment]
I can't reproduce.

Repro steps? Filter lists? Custom filters?

**Comment by gpedro** [comment]
Steps:
1 - disable/enable\* uBlock
2 - close the current tab from github
3 - open new tab from github
- (enable) ? buggy : works

I recently installed, do not set anything.

**Comment by dashed** [comment]
I experienced the same problem with a vanilla installation on Chrome.

The problem seems to go away when you disable "Fanboy’s Annoyance List‎".

**Comment by gorhill** [comment]
Yes, there is a `##.social-count` cosmetic filter in _"Fanboy's Social Blocking List"_, so the count widget should dispappear as per this 3rd-party filter list. I am trying to understand why it does not disappear on my side.

**Edit:** ok there is an exception filter: `github.com#@#.social-count`. So now I would need to investigate then why it's not working for OP. I still cannot reproduce.

**Comment by dashed** [comment]
@gorhill The issue in question doesn't occur all the time (at least for me; but it was annoying). I was going to report this issue, until I realized it was a 3rd-party filter list. So I thought it was out of scope. I'm unable to discern the exact reproducible steps. 

As far as I can tell, clicking on links that are part of the SPA of GitHub (i.e. no hard refresh) doesn't seem to create the issue.

**Comment by gorhill** [comment]
The only way I can think how this could happen is if the generic filters arrive to the content script before the specific ones (the ones specific to a hostname). I am currently assuming the `contentscript-start.js` is **always** executed before `contentscript-end.js`. But given the symptom described here, this may not always be the case by all appearances.

**Comment by gorhill** [comment]
Ok I can reproduce on my very old laptop, I can investigate now.

**Comment by ArnaudLigny** [comment]
I encounter the same problem, but I am unable to reproduce systematically. It's erratic...

uBlock default settings + "FRA: EasyList Liste FR" enabled.

**Comment by dashed** [comment]
Can confirm that fix seems to work.
