### ISSUE TITLE
Can't disable google-analytics.com blocking

### ISSUE THREAD

**Issue by AlistairB** [uBlock-LLC/uBlock#453]
Hi,

I have switched off 'uBlock Filters - Privacy' and EasyPrivacy, but www.google-analytics.com is still being blocked.

I have also tried adding whitelist '||google-analytics.com' which it won't allow me to apply and also 'www.google-analytics.com' which doesn't do anything.

I only want to block ads, not interfere with tracking.

How can I achieve this?

Cheers

**Comment by gorhill** [comment]
> I only want to block ads, not interfere with tracking

Un-select _EasyPrivacy_ and all selected filter lists **except** _EasyList_ in the _"3rd-party filters"_ tab in the dashboard:

![a](https://cloud.githubusercontent.com/assets/585534/5592169/f999f5e4-9188-11e4-8bcf-9fea021e21b9.png)

Don't forget to click _"Apply changes"_ once you have deselected the filter lists.

**Comment by gorhill** [comment]
There is `google-analytics.com` in _"Peter Lowe's Ad server list"_.

**Comment by AlistairB** [comment]
Ah got it thanks very much!
