### ISSUE TITLE
[Fanboy's Social] Strange filter ".net/p.gif?"

### ISSUE THREAD

**Issue by ArnaudLigny** [uBlock-LLC/uBlock#458]
| Type | URL | Filtre |
| --- | --- | --- |
| image | http://p.typekit.net/p.gif?s=4&h=domain.tld&f=16324.16321.16322.17275.17276.17270.17271.17265.17269.17272.17273.17267.17268.17266.17274&app=&_=1420237886020 | .net/p.gif? |

Related to #17?

**Comment by gorhill** [comment]
It's in [EasyPrivacy](https://easylist-downloads.adblockplus.org/easyprivacy.txt). hpHosts is only pure hostnames. Why is this an issue?

**Comment by ArnaudLigny** [comment]
OK, I have disabled the _EasyPrivacy_ filter and I still see a/my problem: obviously not related to the filter...

**Comment by gorhill** [comment]
> still see a/my problem

What is the problem?

**Comment by ArnaudLigny** [comment]
The social logos disappear on this website, under the baseline: http://juliendubreuil.fr

Maybe another/the same font problem as usual :-)

**Comment by gorhill** [comment]
It's a cosmetic filter, `#social-icons` from _"Fanboy's Social Blocking List"_. Cosmetic fitlers do not appear in the network request log.

**Comment by ArnaudLigny** [comment]
OK, thanks for this really quick analysis / answer.

It could be interesting to have an (debug) option to see this kind of filter in log?

**Comment by ArnaudLigny** [comment]
See release [0.8.2.8](https://github.com/gorhill/uBlock/releases/tag/0.8.2.8).
