### ISSUE TITLE
Ads don't get blocked before page loads

### ISSUE THREAD

**Issue by sstouffer** [uBlock-LLC/uBlock#460]
I don't believe this happens all the time but found a good page that provides an example. At the following page, as you click through the pictures, you'll see a blocked ad appear at the top of the page and everything shift down for a fraction of a second, then shift back up. This is with only the easylist filter and nothing else. 

Adblock Plus also has the same problem, but Adblock (getadblock.com) does not. With Adblock, as you click through the slideshow of pictures, the page remains static, with no shifting around.

http://www.dpreview.com/articles/8635354300/beautiful-dreamer-garret-suhrie-landscapes

**Comment by gorhill** [comment]
Title is misleading: The ad is blocked. The placeholder however is collapsed later.

I don't know anything about AdBlock's code, aside that it's the most CPU intensive blocker out there. I see there is also a re-layout occurring with AdBlock, the whole page shift upward, though I didn't see the ugly placeholder.

That said, given how trivial the issue, the simplest fix is to just create the appropriate cosmetic filter:

```
www.dpreview.com##.ad.top
```

Result is even better than with AdBlock, there is no page shift upward. Even better, [submit the filter to EasyList crowd](http://forums.lanik.us/viewforum.php?f=62) so everybody benefit from it regardless of the blocker used.

**Comment by gorhill** [comment]
By the way, I see AdBlock redirect the `iframe` to `about:blank`, which may explain why you do not see Chromium's default placeholder (the gray ascii face). Very early in the project I had to stop using redirection for blocked contents, [for good reasons](https://github.com/gorhill/uBlock/issues/18).

**Comment by sstouffer** [comment]
Thank you for the detailed response! I have since submitted a report to easylist. Keep up the great work!
