### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JeremyWW** [uBlock-LLC/uBlock#461]
Sorry if I'm posting this in the wrong place. Is there such a thing as a specific filter list for Facebook (the site itself) that I can subscribe to? Tried searching but can't find anything. I don't want to use EasyList as it breaks too many sites for me so I'm taking a very 'light' approach to ad blocking on a 'DIY' basis. Facebook ads though are a pain. Thanks.

**Comment by gorhill** [comment]
Here is a couple of filter lists, [from Adblock Plus](https://facebook.adblockplus.me/en/):

```
https://easylist-downloads.adblockplus.org/fb_annoyances_full.txt
https://easylist-downloads.adblockplus.org/fb_annoyances_sidebar.txt
https://easylist-downloads.adblockplus.org/fb_annoyances_newsfeed.txt
```
