### ISSUE TITLE
adding mixpanel.com to the safelist/whitelist

### ISSUE THREAD

**Issue by CorySchnurr** [uBlock-LLC/uBlock#463]
Can this be done?

**Comment by gorhill** [comment]
What do you mean?

Pasting `mixpanel.com` in the textarea in the _Whitelist_ tab in the dashboard?

**Comment by gorhill** [comment]
Ok I see, `mixpanel.com` is blocked by Peter Lowe's, so I need to add `@@||mixpanel.com^$~third-party` to uBlock's filters.

**Comment by CorySchnurr** [comment]
thanks!!!

**Comment by ofekih** [comment]
ublock origin is still blocking mixpanel for me

**Comment by davidhariri** [comment]
Need to add `*.mxpnl.com` as well

<img width="541" alt="screen shot 2017-03-02 at 12 12 50 pm" src="https://cloud.githubusercontent.com/assets/5245670/23518492/9a720c72-ff41-11e6-8880-3ec6ad1a9d97.png">

**Comment by DmytroLitvinov** [comment]
I agree with the previous author. Could you please add to whitelist, @gorhill ?
![image](https://user-images.githubusercontent.com/16066485/30151451-2afef47a-93b8-11e7-85ec-336934edebb0.png)
