### ISSUE TITLE
EasyPrivacy enabled by default

### ISSUE THREAD

**Issue by lox** [uBlock-LLC/uBlock#465]
The EasyPrivacy list tends to block lots of real-time applications, due to the blocking of `pusher.com`. This list is disabled by default in ABP, shouldn't it be optional in uBlock too? 

For context, we've seen an increase in complaints of real-time functionality not working on 99designs.com for users who are using uBlock.

**Comment by gorhill** [comment]
> shouldn't it be optional in uBlock too

No. uBlock has users' privacy in mind first and foremost. It's why it pains me to see uBlock often described as an "ad blocker". Ads do compromise users' privacy, but that's just the visible tip of the iceberg.

> an increase in complaints of real-time functionality not working on 99designs.com for users who are using uBlock

The real fix is to [report what you think should not be blocked to the maintainers of _EasyPrivacy_](http://forums.lanik.us/viewforum.php?f=64), not forfeiting all the protection _EasyPrivacy_ brings to users.

**Comment by lox** [comment]
Fair enough, although nothing will kill adoption like causing functionality issues with websites. Have a look at the list of logos on the frontpage of http://pusher.com/ for some idea of what sort of sites are likely to break for users. 

For posterity, here are the links of the related forum thread:

https://adblockplus.org/forum/viewtopic.php?f=2&t=27287&p=114403#p114403

**Comment by gorhill** [comment]
> For posterity, here are the links of the related forum thread:
> 
> https://adblockplus.org/forum/viewtopic.php?f=2&t=27287&p=114403#p114403

You did not provide **any** specific technical details in order to allow the problem to be solved. Provide specific details of what should not be blocked and it will be addressed, assuming it doesn't go counter to _EasyPrivacy_ purpose.

> We've noticed an increase in complaints of users on `99designs.com` not getting real-time notifications and updates, which we've traced down to the _EasyPrivacy_ list being enabled by default in uBlock ... Pusher.com provides push notifications over web sockets. The block means those push notifications doesn't come through

Except that Chromium-based browsers are yet unable to block websocket-based network requests, so something does not make sense in your original assertion.

Asking all users to not use _EasyPrivacy_ to fix vague technical problems specific to `99designs.com`, which you are not disclosing, is of course not an option.

Why don't you provide technical details to help the maintainers of _EasyPrivacy_ to fix the issues specific to `99designs.com`?

**Comment by gorhill** [comment]
I tried [the demo](https://html5-realtime-push-notifications.pusher.io/), and the notification worked all fine it seems:

```
xmlhttprequest    https://html5-realtime-push-notifications.pusher.io/notify?message=qq
```

This was not blocked, and I have _EasyPrivacy_ enabled, and the demo worked all fine, I saw the notification widget at the top.

The one request which **was** blocked is this one:

```
script  https://stats.pusher.com/timeline/v2/jsonp/1?session=NTEwMzAwNjQ0&bundle=MQ%3D%3D&key=NDllMjZjYjhlOWRkZTNkZmMwMDk%3D&lib=anM%3D&version=Mi4yLjM%3D&features=WyJ3cyIsImZsYXNoIl0%3D&timeline=W3siaW5zdGFuY2VzIjoxLCJ0aW1lc3RhbXAiOjE0MjA3Nzg5NjkyMTN9....
```

Looks to me something that should be blocked, and that did not prevent the demo from working.

**Comment by lox** [comment]
You make a fair point, let me investigate more and provide some specifics.
