### ISSUE TITLE
[EasyPrivacy] Breaking things on wordpress.org and WordPress Administration Dashboards

### ISSUE THREAD

**Issue by deconf** [uBlock-LLC/uBlock#466]
I have multiple reports from my users, about uBlock breaking things on wordpress.org and on administration dashboards, here are some examples:
- wordpress.org

https://wordpress.org/plugins/google-analytics-dashboard-for-wp/screenshots/

http://postimg.org/image/akmedfvl5/ (no banners and screenshots are displayed)
- WordPress admin dashboard (Google Analytics Dashboard widget gets blocked)

http://postimg.org/image/rhep332j1/
- and same thing on plugin's settings page.

I was able to replicate the issue only when the Easy Privacy list is enabled (which is a default).

Here is a screenshot of the Console Log:

http://i.imgur.com/U8kAPuf.png

**Comment by gorhill** [comment]
_EasyPrivacy_ is third-party to uBlock. You need to contact [the maintainers of _EasyPrivacy_](http://forums.lanik.us/viewforum.php?f=64) to have the problem fixed for all users, not just uBlock's users.

From what I quickly gather, it appears the filter `/google-analytics-` is involved.

**Comment by deconf** [comment]
Thanks for the quick response, I'll do that!

**Comment by ve3** [comment]
Please add /google-analytics-for-wordpress to unblock because of EasyPrivacy that all of Yoast Google Analytic users have broken page.
For more detail please see https://wordpress.org/support/topic/reports-tab-is-broken-after-updating-wordpress-to-version-43?replies=10
