### ISSUE TITLE
Missing: a "color-blind friendly" setting

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#467]

**Comment by deaffob** [comment]
Yes please add this setting.... I'm using your µMatrix and it's like night and day for me who's green-red color blind...

**Comment by dekonnection** [comment]
+1

The extension is amazing, but dynamic filtering is also extremely frustrating for colorblind people like me (deuteranomaly).

**Comment by ghost** [comment]
I am part of the 0.4% of deuteroanomalous so I'm interested in this (although it's not that bad for me).

I don't know much about it so here what I've gathered so far:

What needs to be targeted is deuteroanomalous (4.9% + 0.4% of the population) and deuteranopia (1.1% + < 1%). Protanopia and protanomalia both affect 1% of the male population but providing a color palette for deuteranopia should work with protanomalious people too. Tritanopia and tritanomalia prevalence is less than 1 per 1000.

There are tools to simulate protanopia and deuteranopia:
- Adobe Photoshop: by using View > Proof Setup > Deuteranopia
- Vischeck online: http://www.vischeck.com/vischeck/vischeckImage.php
- This excellent tool is designed to help choose complementary colours, but also have a Vision simulation function: http://paletton.com/

Here's what I have obtained with the popup colours:
- Normal vision: http://i.imgur.com/HEWkkyr.png
- What a deuteranope sees: http://i.imgur.com/0L1pEpJ.png

Various articles about the subject with recommendations:
- https://msdn.microsoft.com/en-us/library/bb263953.aspx
- http://jfly.iam.u-tokyo.ac.jp/color/
- http://help.adobe.com/en_US/creativesuite/cs/using/WS3F71DA01-0962-4b2e-B7FD-C956F8659BB3.html
- This tool ( http://www.snook.ca/technical/colour_contrast/colour.html ) is used to validate text colour over background colour against W3C WCAG 2.0 recommendations.

So either:
- create a colour palette not being based on red/green difference. For example this palette:
  https://color.adobe.com/Color-Blind-Safe-color-theme-880514/
- use patterns in the background colours. By using CSS3's "repeating-linear-gradient" for example (https://css-tricks.com/stripes-css/) or use symbols in the background to add information redundancy for colorblind people.

**Comment by ghost** [comment]
Here's the colours I propose next to the current ones, in various colour-blind configuration.
Feedback would be appreciated.

Proposed colours:
- Allow: rgba(106, 140, 104, 1) / rgba(106, 140, 104, 0.4) / rgba(106, 140, 104, 0.75) 
- Noop: rgba(0, 19, 110, 1) / rgba(0, 19, 110, 0.4) / rgba(0, 19, 110, 0.75)
- Block: rgba(255, 194, 57, 1) / rgba(255, 194, 57, 0.4) / rgba(255, 194, 57, 0.75)

![ublock palette proposed normal vision](https://cloud.githubusercontent.com/assets/6247191/7275072/18dfbae4-e902-11e4-8727-48e1d11a1343.jpg)

![ublock palette proposed protanomaly](https://cloud.githubusercontent.com/assets/6247191/7275074/18f56ad8-e902-11e4-83f4-3d65061c7236.jpg)

![ublock palette proposed protanonopia](https://cloud.githubusercontent.com/assets/6247191/7275077/19011e0a-e902-11e4-858c-13992418de5a.jpg)

![ublock palette proposed deuteranomaly](https://cloud.githubusercontent.com/assets/6247191/7275075/18f6748c-e902-11e4-8950-eeda77a452d5.jpg)
![ublock palette proposed deuteranonopia](https://cloud.githubusercontent.com/assets/6247191/7275073/18e0d294-e902-11e4-8c0e-c3ad6f1ea90a.jpg)

**Comment by gorhill** [comment]
@WyohKnott awesome work, having an actual colorblind person contributing the solution is best. For uMatrix I was sort of left to my own devices, and not sure I picked the optimal solution from what I see here.

For my fork, I would just plainly go along with these colors, however with a change in the mapping: I would swap the blue and the almost completely unsaturated green, so as to keep the noop color as close as possible to the original one. What do you think?

**Comment by ghost** [comment]
I haven't mapped them yet, it was just a test for how the shades would interact.
I was thinking:
- allow: yellowish-orange, it's the most bright of the three, so I was thinking of associating it with allow.
- noop: unsaturated green, as it is the most neutral in my opinion.
- block: navy blue, it's closer to night blue, which might be better to associate with an off setting.

**Comment by ghost** [comment]
@gorhill There's one colour in the css that i'm not sure I've ever seen in the popup before so I didn't include it in my test:

``` css
#firewallContainer > div.allowed.blocked > span:nth-of-type(1):before,
#firewallContainer.minimized > div.isDomain.totalAllowed.totalBlocked > span:nth-of-type(1):before {
    background-color: rgb(192, 160, 0);
    }
```

In which context does _div.allowed.blocked_ happen? I've never seen that orange shade before when using µBlock.

**Comment by gorhill** [comment]
@WyohKnott It's the little coloured label at the left of a row, which indicates whether all requests were blocked, allowed, or some blocked some allowed:

![c](https://cloud.githubusercontent.com/assets/585534/7276635/fb618a20-e8d8-11e4-9400-f3b07a634408.png)

In the above picture, that label for entries for `wired.com` and `adobedtm.com` is yellowish. Note that this label is kind of redundant to the pluses/minuses in the right-most cells.

**Comment by RobotCaleb** [comment]
First, thanks for the color blind support. I'm color blind and am a strong advocate for not relying on color alone to convey meaningful information.

@WyohKnott mentioned "use patterns in the background colours. By using CSS3's "repeating-linear-gradient" for example (https://css-tricks.com/stripes-css/) or use symbols in the background to add information redundancy for colorblind people."

I'd love to see such a thing implemented. Further, just because you have colors that color blind people are more likely to differentiate doesn't mean that any meaning is applied to them. Especially without a legend anywhere.

Edit: I just realized I commented here, but have only looked at the colors chosen in uMatrix. I see you reference this issue from uMatrix, so presumably there's carryover.

**Comment by ghost** [comment]
@RobotCaleb my tests with patterned background (not shown in this discussion) were not conclusive because the areas are small and it reduces the readability of the plus and minus signs.

I know the colours chosen don't convey their meaning, I've looked if there was a international implied standard like green = allowed, red = forbidden, but I couldn't find any information about that. Maybe we could add a legend explaining the colours meaning next to to the checkbox in the option panel.

**Comment by gorhill** [comment]
> Especially without a legend anywhere

That was also true for the black/white scheme I chose in uMatrix before porting the new scheme. I don't remember ever anybody asking for a legend for that old scheme. It does seem natural to me to associate dark blue (night) with block and bright yellow (day) with allow.
