### ISSUE TITLE
Whitelist wildcard

### ISSUE THREAD

**Issue by aleksandargosevski** [uBlock-LLC/uBlock#468]
Hi,

I'm trying to add new items in the white list with wildcards, but when I hit Apply, app comment out those lines.

Here is the video (gif) - http://cl.ly/image/1S391o1u3u2E

Thanks

**Comment by gorhill** [comment]
That's because:

> Complex syntax occurs if and only if at least one / appears in a whitelist directive.  [...] Wildcards can be used at any position. However, when a wildcard is used within the hostname portion of a directive, **it cannot be at the end of the hostname**, and also must be at the boundary of a hostname label.

So
- Does work: `*fe-local/`
- Does not work: `*fe-local*`, `*fe-local*/`

**Comment by aleksandargosevski** [comment]
Thanks.
