### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by mattryanharris** [uBlock-LLC/uBlock#469]
uBlock seems to be blocking font-awesome

**Comment by gorhill** [comment]
URL?

**Comment by mattryanharris** [comment]
It was blocking it on my site, http://classstatus.co

Bottom right corner uses font awesome

**Comment by gorhill** [comment]
_"Fanboy's Social Blocking List"_ does that, it blocks social widgets.

**Comment by gorhill** [comment]
Un-select the list if you do not want Social widgets to be blocked/removed.

In latest version, I removed the list from being active in fresh installs.
