### ISSUE TITLE
Popup UI Sizing 

### ISSUE THREAD

**Issue by spaghetti2514** [uBlock-LLC/uBlock#470]
With the new dynamic filtering enabled, the popup UI will occasionally be created with a size as if dynamic filtering wasn't enabled, but will contain the dynamic filtering in the page
![screen shot 2015-01-10 at 3 08 52 am](https://cloud.githubusercontent.com/assets/1966861/5690998/974d4612-9876-11e4-8522-0d812c1098e6.png)
Obviously this is still pre-release, but I thought I should make a report now in case you weren't aware of it

uBlock version: latest HEAD
Chrome version: 39.0.2171.95

**Comment by gorhill** [comment]
Might be related to http://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-20#post-2445709

I can't obviously release until I figure what is going on.

What OS are you on?

**Comment by gorhill** [comment]
Closest I found for an explanation: http://stackoverflow.com/questions/14644152/chrome-extension-page-popup-html-doesnt-resize

**Comment by spaghetti2514** [comment]
I'm on OS X 10.10.1
~~Can't reproduce it since 9fc136e, so all is good~~

EDIT: Spoke too soon. Got it to happen again by spamming the extension's button for a little while
![screen shot 2015-01-10 at 4 45 50 pm](https://cloud.githubusercontent.com/assets/1966861/5693589/45334d96-98e8-11e4-8ca0-6050869da505.png)

EDIT EDIT: I did of course update and rebuild and reload before testing again
