### ISSUE TITLE
Can't click on some Dynamic Filtering domain rows with Torch browser

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#471]
I am fully aware that this is an esoteric problem due to the low population of Torch (Chromium based browser) users with uBlock (or maybe I am wrong), but as a long time user myself (as you can clearly see from the statistics on the video) I can't hold back from reporting it.

I am using the latest version of Torch 36.0.0.8667 (8667), and having the issues of not being able to green/gray/red some domain rows of the Dynamic Filtering as shown in the video.

**Notes:**
1) I am ABLE to change/click the top selectors (Images, inline scripts and etc.), but not the lower ones (the domains).
**Update: From domains, I can only select the current domain I am visiting (with and without `www` at start), but not other domains.**
2) No `+` or `-` signs are shown, although the domain rows are colored.
3) No problems on stable and dev Chrome versions with the same settings (tested via a backup file).
4) Resetting to default settings doesn't help.
5) No reload button is shown after changing any selector.

**Comment by Deathamns** [comment]
[`Math.log10`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log10#Browser_compatibility), there's a polyfill too.

**Comment by Mikey1993** [comment]
So maybe use the polyfill until the Torch browser updates to some newer Chromium version that supports this?

You may leave this issue open until this one gets resolved, and then revert the polyfill.

**Update:**
I can confirm that changing
`Math.log10(x)`
to
`Math.log(x) / Math.LN10`

in `popup.js` resolves all mentioned issues.

Can this one get into the stable release, so I won't need to rebuild the extension myself every version?

**Comment by gorhill** [comment]
@Deathamns Thanks for finding the cause.

Looking again, I don't know why I used `Math.log10`, I usually avoid using things which have not been in the browser for long, and I see it only appeared with Chromium 38. I will publish an update today, there might be users still on Chromium 37 and less.
