### ISSUE TITLE
Blank domain row in Dynamic Filtering table

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#473]
<h2>Steps:</h2>

1) Enter: http://www.ynet.co.il
2) Observe the popup for the Dynamic Filtering rows.
3) A blank domain row appears first or second (consistently on these 2 positions) after loading the page.

**Comment by gorhill** [comment]
There is a request to `http://s3-eu-west-1.amazonaws.com/exposebox/winwin/ynet-winwin-widget-new.html Failed to load resource: net::ERR_BLOCKED_BY_CLIENT` on the page.

However, as per PSL, `s3-eu-west-1.amazonaws.com` is not an effective domain, it is a public suffix. Trying to extract the effective domain name from `s3-eu-west-1.amazonaws.com` results in an empty string.

I need to use the hostname when I get a blank effective domain name.

**Comment by gorhill** [comment]
I am just going to repackage this as part of 0.8.5.1.
