### ISSUE TITLE
No uBlock icon for popup windows ? (Firefox)

### ISSUE THREAD

**Issue by Betsy25** [uBlock-LLC/uBlock#474]
Is it normal that I don't have a toolbar icon (in FF) for popup windows ?
Like when you click some video link on pages like these http://www.drakulastream.eu/football-live-streaming-video.html

**Comment by gorhill** [comment]
There is no official version of uBlock for Firefox, it's a preview development version, not ready to have issues filed for it.

In any case, yes it is normal, it's a browser behavior, not an extension behavior. Same thing happen with Chromium. Workaround is to copy/paste the URL in a normal tab.

**Comment by my-password-is-password** [comment]
In firefox you can force popups into new tabs in `about:config`

http://kb.mozillazine.org/Browser.link.open_newwindow
`browser.link.open_newwindow  = 3 (default)`

http://kb.mozillazine.org/Browser.link.open_newwindow.restriction
`browser.link.open_newwindow.restriction = 0`

and you can also disable window open features
http://kb.mozillazine.org/Prevent_websites_from_disabling_new_window_features
`dom.disable_window_open_feature.toolbar = true`

**Comment by Betsy25** [comment]
Thanks @my-password-is-password 
setting **dom.disable_window_open_feature.toolbar** to **true** allows us to see the uBlock icon.
