### ISSUE TITLE
layout problem with http://www.androidiani.com/

### ISSUE THREAD

**Issue by stefanocaselli** [uBlock-LLC/uBlock#481]
Hi,
there's a layout problem on androidiani.com. 
Example:
http://www.androidiani.com/forum/android-tips-tricks/193216-info-guida-batteria-inizializzazione-e-calibrazione-tutta-la-verit.html
when ublock is enabled the text is aligned on a little column on the right of the page, making it difficult to read.

![image](https://cloud.githubusercontent.com/assets/10347571/5699811/db88ab26-9a30-11e4-96be-ad7be0dab894.png)

instead it should be like this:

![image](https://cloud.githubusercontent.com/assets/10347571/5699824/0cc03a56-9a31-11e4-82d5-23230f781986.png)

**Comment by gorhill** [comment]
How web sites design their pages has nothing to do with uBlock.

The DOM element containing the text has the CSS `overflow` set to `hidden`, this causes the layout problem. uBlock doesn't re-style web pages, it block network requests or collapse DOM elements according to filters.

You may want to try Stylish, and use `blockquote { overflow: visible; }` for that page.

**Comment by stefanocaselli** [comment]
I'll try. thanks
