### ISSUE TITLE
Disabling uBlock for this page/site doesn't work anymore

### ISSUE THREAD

**Issue by teuneboon** [uBlock-LLC/uBlock#482]
I'm working on a project and I'm developing that on localhost:8000. I disabled ublock for that entire site(I use the fontawesome reddit icon on it and I want to actually see it when developing). It used to work fine until today, now enabling/disabling uBlock for both the entire site or just an entire page still seem to add the uBlock postload:

```
<style class="ublock-postload-1ae7a5f130fc79b4fdb8a4272d9426b5">#content > #center > .dose > .dosesingle,
#content > #right > .dose > .dosesingle
{display:none !important;}</style>
<style class="ublock-postload-1ae7a5f130fc79b4fdb8a4272d9426b5">.fa-reddit
{display:none !important;}</style>
```

Some specs:
Platform: Linux
Browser: Chrome Version 40.0.2214.69 beta (64-bit)
µBlock: 0.8.5.0

**Comment by gorhill** [comment]
Does uBlock icon shows as being disabled? You are trying to disable what URL exactly?

Also, can you see what related whitelist directive you see in _Whitelist_ tab?

**Comment by teuneboon** [comment]
The icon shows as disabled, I'm trying to disable "http://localhost:8000/#hosts". In the whitelist tab I see this:

```

localhost
```

**Comment by gorhill** [comment]
What version of uBlock worked fine? The last time I touched this part of uBlock was with version [0.8.2.0](https://github.com/gorhill/uBlock/releases/tag/0.8.2.0).

**Comment by teuneboon** [comment]
I'm not really sure to be honest. Last time I worked on this project from
this PC was last Wednesday and iirc it worked back then. Might have
overlooked it back then though

**Comment by gorhill** [comment]
I don't have a local server to test, but I suspect the `:8000` is tripping the whitelist code. I will look if I can fix it blind, or do you have a URL which use a port that I can use as a test case?

**Comment by teuneboon** [comment]
I don't have a public URL with that port and a proper testcase right now, but if you happen to have Python installed you can run `python -m SimpleHTTPServer` in a directory and it will serve that directory on `:8000`.

I also noticed one more thing: if I open an `<a>` link to my testpage in a new tab(middle-mouse button) uBlock will be disabled(the reddit icon shows). If I refresh after that it will dissapear again.

**Comment by gorhill** [comment]
Ok, spotted the problem, a silly logical error introduced in 0.8.5.0. Will fix asap, as this affect not only localhost, but all whitelisted pages (i.e. a serious bug).

**Comment by teuneboon** [comment]
Seems to be fixed now, thanks
