### ISSUE TITLE
Feature: Filter blocked/allowed requests in the statistics

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#483]
For me to unbreak a site has become broken by the Dynamic Filtering rules, I would want to be able to compare 2 runs:
1 **with** the blockage of 3rd party scripts/frames on
&
1 **without** the previously enabled blockage.

I would then be able to compare the 2 run results, and identify which domains needed to gray out/whitelist in the popup.
This also means that the "main_frame" in the statistics table should **always** be there for the visual comparison.

**Comment by gorhill** [comment]
Yes I was planning to have fields to narrow visible results.

**Comment by gorhill** [comment]
For translators:

![a](https://cloud.githubusercontent.com/assets/585534/6462571/3df17ca2-c178-11e4-92b9-634126b092bb.png)

**Comment by gorhill** [comment]
![d](https://cloud.githubusercontent.com/assets/585534/6472546/44f1f718-c1c1-11e4-8485-8ae6edc25d4b.png)

**Comment by gorhill** [comment]
Filtering feature in 8b1ecfc09cfe2db45c193109d0f141e196da554e.
