### ISSUE TITLE
[EasyPrivacy] broken page with ublock

### ISSUE THREAD

**Issue by TooYellow** [uBlock-LLC/uBlock#485]
I didn't see a master post for broken sites so created this ticket.

http://thesweethome.com/

The drop down menu (circled in red in the screenshot) doesnt work with ublock enabled.

![capture](https://cloud.githubusercontent.com/assets/6325025/5703610/cb83f626-9a36-11e4-8234-a11bb43d4888.PNG)

**Comment by gorhill** [comment]
A third-party filter list is causing this: _EasyPrivacy_. You have to [report the problem to the maintainers of the list](http://forums.lanik.us/viewforum.php?f=64).

**Comment by gorhill** [comment]
Tell them these two filters are blocking needed scripts for the page to work fine:
- `||telize.com^$third-party` blocks `http://www.telize.com/geoip?callback=chooseCountry`
- `/ga-event-tracking` blocks `http://thesweethome.wpengine.netdna-cdn.com/wp-content/themes/thewirecutter/js/ga-event-tracking.js?ver=1414007796`

**Comment by gorhill** [comment]
Cc'ing @ryanbr as it is unclear whether OP will report.
