### ISSUE TITLE
Puush is being blocked out.

### ISSUE THREAD

**Issue by dragons4life** [uBlock-LLC/uBlock#486]
Puush images is being blocked out by this extension, is there a way you can fix it?

http://a.pomf.se/srtrdc.webm

Also just noticed it happen with pomf.se while uploading the video, why are this websites even being blocked by the extension tough? also i understand i can white list them, but there is no reason as to why they should be blocked, so just reporting it, just in case.

**Comment by gorhill** [comment]
`a.pomf.se` appears in one of the malware domain list.

You will need to create an exception if you want to unblock the site. Two ways:

Static filter: `@@||a.pomf.se^` (to use in "My filters" tab)

or

Dynamic filtering rule:

![a](https://cloud.githubusercontent.com/assets/585534/5705762/ae82cbf2-9a49-11e4-8d62-3fec91734003.png)

which is dynamic rule `a.pomf.se a.pomf.se * allow`. If you want to allow `a.pomf.se` from anywhere, the dynamic rule would be `* a.pomf.se * allow`.

**Comment by dragons4life** [comment]
Thank you, how did you  make that graph pop-up on the side?

**Comment by gorhill** [comment]
If you check _"I am an advanced user"_ in _Settings_, it will become available. You are on your own though if you break web sites or proper filtering using this feature, use at your own risk, it's usually for users who have an understanding of what it's all about.
