### ISSUE TITLE
malwaredomains.com

### ISSUE THREAD

**Issue by JeremyWW** [uBlock-LLC/uBlock#487]
There seems to be an issue with malwaredomains.com. These lists won't update today. Clicking on the list in uBlock directs to http://mirror1.malwaredomains.com/ which returns 'This web page is not available', however http://www.malwaredomains.com/ seems to be fine.

**Comment by gorhill** [comment]
I don't get it... Why not file an issue with the site owner?

**Comment by JeremyWW** [comment]
You're right - sorry. I wasn't thinking it through.

**Comment by JeremyWW** [comment]
I did as you suggested and got this reply (quoted):

"they were not supposed to grab the lists directly. I asked them to make a cached copy on their server (like adblock does)."

**Comment by gorhill** [comment]
Ok, I had not realized that could become a problem -- this used to be a much smaller project.

This could also become a problem on Github if it's abused. So I will remove the remote server URL, and so the fetching will fall back to Github. I will just update this list less often to not run into the same problem on Github.

**Comment by JeremyWW** [comment]
Great. Look forward to the update...

**Comment by gorhill** [comment]
If I am not mistaken the effect should be immediate whenever an update cycle is triggered. Can you verify on your side?

To confirm the change took place, you won't see the domain name `malwaredomains.com` aside the lists' name.

**Comment by JeremyWW** [comment]
Yep. All good. Thanks.

**Comment by JeremyWW** [comment]
Do you think it might be necessary to do the same with other filters, such as hpHosts and MVPS?

**Comment by gorhill** [comment]
No idea. These lists are marked as obsolete after 4 days, so it's not like every user is requesting very often.
