### ISSUE TITLE
The blocking of inline javascript does not propagate to frames

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#490]
I need to use the `sandbox` directive for embedded frames, just like in uMatrix.

Test page: http://raymondhill.net/httpsb/httpsb-test-js-1.html

**Comment by Deathamns** [comment]
If the `sandbox` directive in HTTP headers behaves same as setting the iframe's sandbox attribute, then it will have a side-effect where it won't load plugins, and there's no way to enable them in sandboxed frames.
Simply sending to iframes the same CSP that is sent for the main_frame wouldn't work?

**Comment by gorhill** [comment]
> Simply sending to iframes the same CSP that is sent for the main_frame wouldn't work?

It has been a while I worked with all this.

It's something I [used to do with HTTP Switchboard](https://github.com/gorhill/httpswitchboard/commit/32af1f69a3942d9994be56508c033fd4c2e7bef5) -- as this is the simplest way. The [comment in the code says](https://github.com/gorhill/uMatrix/blob/master/src/js/traffic.js#L714):

> For inline javascript within iframes, we need to sandbox

Guess I will have to try again to find out again why this was not working. There must be a commit in there somewhere related to a bug explaining why it did not work.

**Edit:** [This is the commit](https://github.com/gorhill/httpswitchboard/blob/e456114b120e578b7e03a1e5ba87c840d4db9c78/js/traffic.js) where I started to use `sandbox` instead of reusing same CSP header for subframes as the one for root document.

**Comment by Deathamns** [comment]
I'm not sure if I understood the problem, but is it that `Content-Security-Policy: script-src 'unsafe-eval' *` doesn't work when applied to iframes?

**Comment by gorhill** [comment]
I will have to try again. It's not clear from the commit why I replaced with `sandbox`. I suspect I might have been confused at the time about the another problem of inline script not being blocked if it was previously allow to execute (because in mem-cache).

According to [this](https://w3c.github.io/webappsec/specs/content-security-policy/#which-policy-applies) it seems your idea should work fine:

> The embedded resource, however, is **controlled by the policy delivered with the resource**, or the policy of the embedding resource if the embedded resource is a globally unique identifier

**Comment by Deathamns** [comment]
Just for the record, I tested it, and setting `Content-Security-Policy: script-src 'unsafe-eval' *` for sub_document will result "Inline javascript: OFF" in your tests (both in Chrome and Firefox).

**Comment by gorhill** [comment]
Yes, just got the result myself, it works. (though I had to fix a little problem with the network request result cache). So easy fix, I like it like that.

**Edit:** Works in FF too, expected, but great to see no complications.
