### ISSUE TITLE
Ability to block ads on whitelisted page

### ISSUE THREAD

**Issue by kurtextrem** [uBlock-LLC/uBlock#491]
I know that request sounds kinda weird, but it makes sense if you want to support pages. There is, for example, a german tech site (called "Golem"), it has great written articles and needs the ad revenue. I'm not that kind of bad guy, who doesn't turn of adblock if they ask to do without blending in popups "You have adblock enabled, please turn off to read the page". But I like my pages clean, I want to read news articles without having an ad banner in there. Ads on the sidebar which I don't mind are fine.
This leads to this suggestion:
Introduce filters which stay even after whitelisting a page.

How to reproduce:
a) Open a page (with ads)
b) Whitelist it
c) See all the ads
d) Add filter for an distracting ad

Expected result:
Ad is gone next refresh.

Instead:
Ad is gone after adding the filter, but on reload it's there again.

I know there is the syntax to "disable" filters, but I think we can all agree it is easier to turn off blocking all ads and adding elements to the block list than using the disable syntax to turn off all EasyList filters. That'd be a never-ending task for larger sites with a lot of different ads.

**Comment by gorhill** [comment]
You are asking a lot, I can sense huge code complication for a very specific narrow purpose.

**Unlikely.**

uBlock's code base is maturing well so far, and what you are asking I see would mess up a lot the work done. Frankly not the kind of complication I would want to see in uBlock (so fork/etc.)

Also, re. "that kind of bad guy"... Let's not be judgmental: users have the right to do whatever they want, and no amount guilt-inducing propaganda -- convenient to the ad industry -- is going to change this.

**Comment by gorhill** [comment]
Alright, this is in the same line as requesting blacklist mode in uBlock, and I have closed all such issues as "won't fix": #445, #177.
