### ISSUE TITLE
Thepiratebay leaves behind blocked element divs

### ISSUE THREAD

**Issue by fysics** [uBlock-LLC/uBlock#50]
![ubuntu server 14 04 download torrent - tpb](https://cloud.githubusercontent.com/assets/1084381/3520109/b2df9464-0728-11e4-906e-df479010438c.jpg)

I think I still have only the default filters turned on.

http://thepiratebay.se/torrent/10398445/Ubuntu_Server_14.04

**Comment by gorhill** [comment]
Looks like there is a HTML element with a property id which is not of type string. I wasn't expecting this. This causes uBlock's element hider script to be aborted.

**Comment by fysics** [comment]
Thanks! That fixed it.
