### ISSUE TITLE
Reporting false positives since an update on 2015-01-23

### ISSUE THREAD

**Issue by Kraust** [uBlock-LLC/uBlock#500]
I do not usually put up issue tickets on projects like this, but I realized that after an update on 01/23 that uBlock was blocking images from a popular domain puu.sh. I am not using any out of the ordinary filter subscriptions (http://puu.sh/ewW3r.png), and was just able to whitelist the domain in the mean time.

I'm not sure if this is an issue with uBlock or with any subscription in particular. I Just wanted to bring it to someone's attention.

**Comment by gorhill** [comment]
Looks like malwaredomains.com is blacklisting `puu.sh`. However I just checked and it's no longer in the latest version.

I will pull the changes from the mirror

**Comment by gorhill** [comment]
Fixed with 014cabf4c2f2cc08faabf2fd35bc0897723c8432
