### ISSUE TITLE
No indication for locally mirrored resources in the network log

### ISSUE THREAD

**Issue by Deathamns** [uBlock-LLC/uBlock#503]
Previously the entries had a yellow background if they were mirrored.

Note that, if you have Experimental features on when the browser/extension starts up, then it seems that local mirroring won't get activated. You have to go to the Preferences, and disable/enable Experimental features (probably this should be in another issue, but it's related).

**Comment by gorhill** [comment]
Investigating why loading `mirror_candidates.txt` fails.

**Comment by gorhill** [comment]
Need to split this bug in two: there are two different unrelated issues, and I prefer to keep a 1-to-1 mapping between commits and issues.
