### ISSUE TITLE
[Firefox] Cosmetic - Icon count misaligned in options menu

### ISSUE THREAD

**Issue by rodalpho** [uBlock-LLC/uBlock#506]
When the uBlock icon is moved to the Firefox options menu (the 3 lines "hamburger" menu), the blocked count is misaligned below the icon instead of offset inside it.
![ublock_optionsmenu_count](https://cloud.githubusercontent.com/assets/747832/5761362/f77ee29e-9ca8-11e4-8ca0-269217dc9c33.png)

**Comment by gregseth** [comment]
In a related manner, the icon count is also misaligned in the icon bar (on Mac OS X only, OS X 10.10.2, Firefox 35.0.1).
![capture d ecran 2015-02-05 a 22 09 43](https://cloud.githubusercontent.com/assets/2717031/6069407/490959aa-ad84-11e4-91f2-055f91b8ad1a.png)

**Comment by chrisaljoudi** [comment]
Dup of #545 (probably).
