### ISSUE TITLE
[Firefox] Filter does not apply after refresh

### ISSUE THREAD

**Issue by Matthewus** [uBlock-LLC/uBlock#511]
I created a rule for this site: http://logout.hu/temak/os_alkalmazas/listaz.php that looks like this: logout.hu###page > .adbigtop.nohead. but it is only working until i refresh or i navigate on the site.

**Comment by Deathamns** [comment]
Can't confirm. It will be hidden for me all the time after I add the rule.

**Comment by gorhill** [comment]
> only working until i refresh or i navigate on the site

Can you cut/paste the rule exactly as it appears in the _"My filters"_ tab in the dashboard? The symptom you describe is as if there is a problem with the rule.

**Comment by Matthewus** [comment]
It seems to work now, first i copied the filters from my ABP filter backup file, now that i copied directly from the ABP window it works fine. Some filters look different in the ABP backup, it looks like that caused my problems.
