### ISSUE TITLE
Feature Request: Facbeook Annoyances Blocker

### ISSUE THREAD

**Issue by MaXimus666** [uBlock-LLC/uBlock#512]
Can you add the filters for Facbeook Annoyances Blocker that ABP has which basically blocks the right pane of Facebook's recommended pages which are full of ads?

**Comment by gorhill** [comment]
I don't feel comfortable adding these. There are no mention of CC license in them. You can add a URL to whatever external list you wish at the bottom of the _"3rd-party filters"_ tab in the dashboard.

**Comment by gorhill** [comment]
Can be imported using external filter lists.
