### ISSUE TITLE
No short description for My Rules tab in the dashboard

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#513]
Might be confusing for novice users, who didn't enable the "I am an advanced user" option to see this tab and don't understand what it supposed to be.

A thought:
Can we generate this tab only if the "I am an advanced user" is checked?
If not, it will have some text saying that this tab is for advanced users and can be seen by enabling this option?

**Comment by gorhill** [comment]
Yes, the hint, I forgot to add it in `messages.json`, it's in the HTML.. So how about:

> Rule syntax: <code>source destination type action</code> (Documentation)

"Documentation" would link to https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax.

For the _"My rules"_ tab, I was planning to hide it, but then I thought that a user may still want to see the rules even after deactivating dynamic filtering (dynamic filtering is disabled when turning off "advanced users")

**Comment by Mikey1993** [comment]
The hint (basic syntax explanation) above should be good enough for people to be interested in going to the documentation, but I think that you should follow the design pattern as with the other tabs in the dashboard, with at least a sentence before this hint explaining that this list is for advanced users and is only becoming active if they check the  "I am an advanced user" checkbox.

**Comment by chrisaljoudi** [comment]
PR #538

**Comment by Mikey1993** [comment]
Actually, No text in the latest FF version on the `My Rules` tab.
Reopening.

**Comment by gorhill** [comment]
It shows for me: v0.8.5.7. The text should be there, there is nothing platform-specific in the resolution of that bug.

**Comment by Mikey1993** [comment]
That's very strange, text is shown now on FF for me.
Might be some Nightly shenanigans.
Closing, again.
