### ISSUE TITLE
[Firefox] Feature Request: Seamonkey Support

### ISSUE THREAD

**Issue by Xylemon** [uBlock-LLC/uBlock#514]
I figured I put up the issue now since the Firefox version has hit Alpha. Work on this issue should be started after the Firefox version is finished however.

**Comment by Deathamns** [comment]
Actually, only the toolbar button and popup are the problematic parts for supporting older versions.
I've made [some changes](https://github.com/gorhill/uBlock/commit/48134d94695b833083405927318413dc261f5aab) which made it possible to install the extension from version 24 (including SeaMonkey), but there is no button nor popup.

**Comment by gorhill** [comment]
> Work on this issue **should** be started

It's all voluntary work... Do you plan on working on the SeaMonkey version?

I see a Seamonkey version with it's own platform-specific branch, so that any changes to the code for it does not endanger the Firefox version, and the Firefox version does not end up with too much code specific to another browser.

**Comment by Xylemon** [comment]
@gorhill Sorry if that sentence sounded demanding. I was trying to say if someone is going to start work on a Seamonkey version, they should wait until after the Firefox version is completed.

I suppose you could have a separate XPI for a Seamonkey release, though I'm not entirely sure how necessary it is.

@Deathamns I've also noticed there are some other problems with the settings window, on my end it seems to not save anything changed and the "3rd Party Filters" tab never loads. I hope that with a Seamonkey release, uBlock takes advantage of the Status/Addons bar.

Edit: Seems my addon that makes the Addon Manager appear in a separate window was causing the above issues. So it seems the only real issue is the lack of a button for uBlock.

**Comment by Xylemon** [comment]
I don't know if this is something on my end or if it is related to forks like Seamonkey, but version of uBlock after 0.9.1.1 seems to have a major bug. The 3rd Party Filters page works for the first session after installing uBlock, but next time the browser restarts, the entire page is gone and nothing is blocked.

**Comment by kernelOfTruth** [comment]
so - is it supposed to work on seamonkey ?

I tried it on 2.33 and there was no u-icon to be found

besides that - great work :+1: 

I'm using it both on Chromium & Firefox

**Comment by Xylemon** [comment]
There is no official support for Firefox forks like Seamonkey or Palemoon, but they should work fine except the lack of an icon, so it's bothersome that this is happening.

**Comment by kernelOfTruth** [comment]
@Xylemon that's actually not a problem as soon as it works

I'm only having a hard time to figure out on how to configure the matrix for a site without the icon XD

**Comment by gorhill** [comment]
The network request logger gives you access to the matrix.

**Comment by kernelOfTruth** [comment]
@gorhill https://github.com/gorhill/uBlock/wiki/The-network-request-logger thank you very much !

I guess that'll make seamonkey my block-as-much-as-possible browser ;)

(knowing that things can be set up via dashboard, but I don't bother right now)

**Comment by logological** [comment]
Folks, Firefox is not a fork of SeaMonkey.  It's more like the other way around.  (SeaMonkey is the continuation of the Mozilla Application Suite, of which Firefox was spun off as a standalone browser.)

**Comment by MiKiL75** [comment]
Here's some further testing what @Xylemon mentioned about 0.9.2.0+ not working in Seamonkey.

Tested in Windows with clean Seamonkey 2.32, 2.32.1, 2.33 and 2.33.1 installs.

There does seem to be something between uBlock 0.9.1.1 to 0.9.2.0 that breaks with Seamonkey 2.33 or 2.33.1. After browser restarts (1 or 2 restarts needed) there's no blocking, empty 3rd Party Filters-page,
empty My Filters-page, feels like uBlock can't load settings). Downgrading uBlock 0.9.1.1 works fine.

I tested further and did clean install for Seamonkey 2.32 and 2.32.1, went testing uBlock 0.9.1.1 thru 0.9.2.4 (latest dev) restarting browser, reseting settings, adding my own filters and everything worked fine,
3rd Party Filters-page shows up correctly and blocking works.

So what changed in Seamonkey 2.33 that affects uBlock 0.9.2.0+ ?

**Comment by Xylemon** [comment]
@MiKiL75 Thanks for further testing this. I'm actually on Seamonkey 2.32.1 (Linux) and this is happening, so it's interesting to see it breaks on 2.33 Windows. I really hope this can get fixed soon.

**Comment by Xylemon** [comment]
Any news on this?

**Comment by Xylemon** [comment]
Fortunately, the 0.9.3.5 release seems to have fixed the issue that started after 0.9.1.1. Now all we need is the fix for the button/panel.

**Comment by Xylemon** [comment]
So now it seems that Seamonkey support is finally here, but something is still missing. There is no button on the addons bar (not really necessary) and if you use Default Deny like I do, there's no button on the email window so you have no control of the emails you receive.

**Comment by AlexVallat** [comment]
I suspect adding support for the email window in Seamonkey would be more than just enabling the button, if they've structured it like Thunderbird. From a quick experiment I can't even access the mail windows through the remote debugger, so I don't think support for them will be added any time soon. Maybe if we get Thunderbird support it might be possible to make it work with Seamonkey Mail too.

As far as I can tell, there is no addons bar in Seamonkey. The window buttons on the bottom left are not a toolbar, and neither are the connection buttons on the bottom right.

**Comment by Xylemon** [comment]
Other addons like NoScrpit and ABE utilize the bottom right bar. I also know ABE has a button from the email window, perhaps it would be useful to study those addons.

**Comment by wmchan4** [comment]
Hi, I have Seamonkey 2.33, uBlock, Session Manager and a few other extensions installed. 
Speaking of u0 not starting on browser reset, I have two observations.
(1) I have totally 3 windows in my current session. When SM starts, I find that u0 is only enabled 
in the first opened window, but for other 2 windows it's disabled, including the context menu items
and the ad-blocking functions.
I have a workaround of that: go to Addon Manager, reset (disable and enable) u0. Then u0 will be
activated in all 3 windows.
(2) I can consistent see the following messages popping up in the SM Error Console (use 
Shift-Control-J to open it.) 
I think that they should indicate some sort of performance issues but I don't know what 

## they are. The messages are pasted below:

Timestamp: 16/5/2015 22:06:10
Error: NS_ERROR_NOT_INITIALIZED: 
Source File: chrome://ublock0/content/js/pagestore.js

## Line: 203

Timestamp: 16/5/2015 22:06:07
Error: NS_ERROR_NOT_INITIALIZED: 
Source File: chrome://ublock0/content/js/async.js

## Line: 201

Timestamp: 16/5/2015 22:06:26
Error: NS_ERROR_NOT_INITIALIZED: 
Source File: chrome://ublock0/content/js/tab.js

## Line: 191

**Comment by AlexVallat** [comment]
I haven't been able to reproduce the startup issue you describe. On the other hand, it appears that you aren't actually using uBlock, but are using uBlock Origin. In which case, you might like to try reporting it on their issue tracker: https://github.com/gorhill/uBlock/issues

If I've misunderstood, and you actually use this uBlock instead, then could you try disabling other addons one by one to see if some incompatibility with any of those is causing the problem? If not, please give detailed steps I can use to reproduce it. What I tried was: 

SeaMonkey 2.33.1
Open 3 tabs with different addresses. Observe uBlock icon enabled, with count shown, for each.
File, Quit, Exit, "Save and Quit" button.
Start SeaMonkey. Observe uBlock icon enabled, with count shown, for each tab. Context menu visible, enabled and working for page on each tab.

**Comment by wmchan4** [comment]
Oh thanks, you are right that I am using uBlock0, not uBlock.
And yeah, it only happens in u0. I remember than your version does not have 
this problem when I started using that.
I think I should file a new issue at gorhill's page since there's no similar issues 
about that.
