### ISSUE TITLE
Images fails to load on solarmovie.so for first time

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#525]
As the title says, type "solarmovie.so" and hit enter -
- It will navigate to solarmovie.is and images will not reload.
  If you refresh now, images will load properly. Looks like an issues when websites redirect..
  ![ublock solarmovi so issue](https://cloud.githubusercontent.com/assets/779630/5789893/7424587c-9ea4-11e4-866c-ec29a9f3a0a1.png)

**Comment by gorhill** [comment]
They did load for me, although in a delayed manner.

**Edit:** Sorry I did not notice the dynamic filters.

**Comment by harshanvn** [comment]
that's weird. I waited almost 30 seconds. images didn't load. Just tried again. Same thing.

However if i type "solarmovie.is", images load instantly..

**Comment by gorhill** [comment]
The only way I could make the images load is by unblocking 3rd-party scripts: the page needs jQuery.

**Comment by harshanvn** [comment]
Yes. it needs jquery. As in my screenshot, can you please whitelist jquery instead and have 3p scripts blocked.

This way configured, Chrome loads images fine even when hit solarmovie.so...

**Comment by gorhill** [comment]
Hmm, strange, I see inline scripts blocked with your configuration, while it should not.

**Comment by gorhill** [comment]
Ok I see the problem. It's a regression from fix to issue #516.

So it appears with Firefox, the request for the root document is processed before `onNavigation()` is fired.

**Comment by harshanvn** [comment]
OK. I see below errors in Dev console. just FYI..
![ublock solarrmovie](https://cloud.githubusercontent.com/assets/779630/5790017/af3773ac-9eab-11e4-80ea-f075a6484a6e.PNG)

Edit:That might be the reason its only a fx issue but not chrome..

**Comment by gorhill** [comment]
I see the same problem with Chromium.

**Comment by gorhill** [comment]
Frankly I don't know how to solve this: it's like we have to accept that #516 won't be fixed if we want to reliably disable inline scripts..

**Comment by gorhill** [comment]
The whole problem with #516 is that the browser API is lying to the extension: it says "I am loading a new root document in that tab" while this is absolutely not what is happening, it is really opening a new root document somewhere but not in the current tab.

**Comment by harshanvn** [comment]
> I see the same problem with Chromium.

that's weird. Shouldn't chrome and chromium be working the same way..

> browser API is lying to the extension: it says "I am loading a new root document in that tab" while this is absolutely not what is happening

Ok. Maybe create a bug/clarification entry at chrome and mozilla. See what they say..just a thought..

Adding another test, issue also replicable in gmail. Inbox will load only after page refresh. 
![ublock gmail](https://cloud.githubusercontent.com/assets/779630/5790050/616ae7b0-9ead-11e4-968e-e3a9e7c9031d.png)
