### ISSUE TITLE
[Firefox] Unable to autoscroll the Dynamic Filters in the popup

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#528]
As the title says:
It's not possible to auto scroll (clicking on the mouse wheel and moving the mouse to the scrolling direction), while scrolling simply with the scrolling bar and the mouse wheel is working.

I am using FF Nightly (v38).

**This works fine with Chrome, so I account this as a specific problem with the Firefox build.**

**Comment by Deathamns** [comment]
I guess this is a limitation of the popup panels in Firefox. Test it with other extensions.
Another limitation is that you can't use context menu (right click) in the popup.

**Comment by Mikey1993** [comment]
@Deathamns I currently don't know any extension which has a popup which can auto scroll.
If someone finds any, please test and report.

**Comment by Deathamns** [comment]
You don't need to test, it's a fact. I just said to test it, if you don't believe me.
But there's Ghostery (on a page with many trackers).

**Comment by Mikey1993** [comment]
@Deathamns I see, that's a shame..

**Comment by Dimas-sc** [comment]
Can you open a bug at bugzilla?

**Comment by Mikey1993** [comment]
@Dimas-sc Less asking, more doing.
Anyway, here you go: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1123421
cc'ing this bug may help to raise awareness.

**Comment by Dimas-sc** [comment]
I ask because you opened the issue here and I thought you could have entered the bug before. Less aggressive and more intelligence please.

**Comment by Mikey1993** [comment]
@Dimas-sc Sorry, not being aggressive.
Anyway, it seems like someone categorized the bug as needed.
We have a chance now.
