### ISSUE TITLE
[Firefox] Local caching font issue (fonts.googleapis.com)

### ISSUE THREAD

**Issue by gitarra** [uBlock-LLC/uBlock#529]
Tested with Firefox Nightly and Firefox Developer Edition.

When you enable µblock's experimental local caching feature the fonts stop working on [this website.](http://www.verkkouutiset.fi/)

µblock shows the requests as yellow but the fonts do not work on the pages.

I'm getting the following errors in the web console:
- Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://fonts.gstatic.com/s/robotoslab/v6/y7lebkjgREBJK96VQi37Zo4P5ICox8Kq3LLUNMylGO4.woff2. This can be fixed by moving the resource to the same domain or enabling CORS.
- downloadable font: download failed (font-family: "Roboto Slab" style:normal weight:normal stretch:normal src index:2): bad URI or cross-site access not allowed source: http://fonts.gstatic.com/s/robotoslab/v6/y7lebkjgREBJK96VQi37Zo4P5ICox8Kq3LLUNMylGO4.woff2
- etc

Local caching also seem to cause weirdness on CDNs covered by the HTTPS Everywhere addons rulesets but thats for another issue and time.

**Comment by gorhill** [comment]
Works fine for me. Does it work if you disable HTTPS Everywhere?

**Comment by gitarra** [comment]
This seems a bit tricky to trigger, it isnt related to HTTPS Everywhere I've just noticed some interesting behaviour with that addon and µblock local caching, but its another thing.

I tried to reproduce this again and was able to after some work, heres the steps I used:

Installed Firefox Developer Edition (cleaned profile). Installed µblock, enabled experimental features.
Restarted browser.
Went to the site, the fonts work fine. Navigated mindlessly around the site just clicking links around.
Restarted browser.
Navigated to the site again clicked a couple of links.
Restarted browser.
Now when I fired up Firefox this time and navigated to the site the fonts work no more.

When the fonts work there is only a single request to http://fonts.googleapis.com/css?family=Oswald:400,700|Roboto+Slab:400,700. Then the issue starts to manifest and there pops up requests to woff and woff2 files at fonts.gstatic.com, until the fonts stop working and there are repeated requests to fonts.gstatic.com, its like the page is trying to repeatedly load the fonts but fails and gives up.

Here is a screenshot showing the page with web console while having local caching disabled:
[Web console and page with working fonts](https://cloud.githubusercontent.com/assets/4739888/5790532/be2d4770-9ea5-11e4-9ab7-8a4984357478.PNG)

Here is the web console and µblock request log when the fonts do not work:
[Fonts broken web console](https://cloud.githubusercontent.com/assets/4739888/5790535/e43486e0-9ea5-11e4-8e25-b597056fde76.PNG)
[Fonts broken request log](https://cloud.githubusercontent.com/assets/4739888/5790536/e58b7dbe-9ea5-11e4-9e97-7a577ca05800.png)

**Comment by gitarra** [comment]
Another site with the same issue: http://muropaketti.com/

Now I got how to reliably reproduce on a clean profile, it requires two browser restarts:

With experimental features enabled, visit the site. The fonts work, note only one request to fonts.googleapis.com.
Restart browser.
Visit the site, the fonts load a bit funky, flashing on and off, theres a few requests to fonts.gstatic.com now.
Restart browser.
Visit the site, fonts do not work. The amount of requests to the samel font files on fonts.gstatic.com at page load increases every browser restart.

**Comment by gorhill** [comment]
Dup of #291.
