### ISSUE TITLE
[Firefox] Element picker: pressing escape to exit

### ISSUE THREAD

**Issue by rrooij** [uBlock-LLC/uBlock#530]
When selecting the element picker mode, you can't quit the mode until you've selected an element. Wouldn't it be nice if it stopped when pressing ESC? It already stops when hitting ESC when the user has already selected an element, but not if the user hasn't. 

I tried to implement it myself and saw the method onKeyPress already added as eventlistener. Can the eventlistener be applied earlier on? I tried with no luck.

Firefox user btw.

**Comment by gorhill** [comment]
Works on Chromium, so this is specific to Firefox.

**Comment by rrooij** [comment]
> Works on Chromium, so this is specific to Firefox.

Ah, that's a pity.

**Comment by gorhill** [comment]
I didn't look, but I suspect it's fixable.

**Comment by Deathamns** [comment]
A `window.focus()` will fix it.

**Comment by Deathamns** [comment]
Fixed in f1bcc0a.
