### ISSUE TITLE
Separate "I am an advanced user" checkbox

### ISSUE THREAD

**Issue by Parent5446** [uBlock-LLC/uBlock#532]
Not sure if this has been mentioned already, but the "I am an advanced user" checkbox seems to do two things: turns on the dynamic filtering interface and removes tooltips.

Would it be possible to split that into two different checkboxes? I do want to get rid of the tooltips, but there is no need for me to turn on dynamic filtering since I use uMatrix for that and it would be redundant.

**Comment by gorhill** [comment]
When you enable dynamic filtering, you are not forced to expand the popup UI and create dynamic filtering rules.

**Comment by Parent5446** [comment]
Is there some way to close the dynamic filtering panel that I don't know about? Because right now when you click on the extension icon the panel is open by default, and there seems to be no way to close it.

**Comment by gorhill** [comment]
The panel is never opened by default, it has to be opened by the user the first time, even after enabling _"Advanced user"_. Clicking the label _"requests blocked"_ toggle the panel on/off.

**Comment by Parent5446** [comment]
Ah I see now. I did not notice the "requests blocked" toggle previously. But the panel was open by default when I enabled "advanced user".
