### ISSUE TITLE
[Feature Request] [Firefox?] Bringing uBlock icon to popup windows..

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#533]
Hi Gothill,

It would be nice to see uBlock icon on pop-up windows. For example, if you open a hangout from gmail (URI:mail.google.com), it opens up in a new window (URI: plus.google.com), but uBlock icon is missing in that. So, it will not be possible to view the current enforced rules (like dynamic filtering ones) of uBlock. One has to look at n/w request logger to amend the rules.

Noscript's does come up on these popup windows :). So, i think it might be possible for uBlock too. But not sure about Chrome.

Thanks!

**Comment by Deathamns** [comment]
Dupe of #474.

**Comment by harshanvn** [comment]
Ok, thanks for the link. I should have searched for it before posting.
And @my-password-is-password suggestion, gives me what i want. 
Love firefox :)
