### ISSUE TITLE
Dynamic Filtering, Inline Scripting Reporting Issue

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#534]
Hi,

It looks like inline script blocking is not properly reported in both firefox and chrome.

<b>In Firefox</b>, items blocked through inline script, are not reported in popUI, but its reflected in Request logger.

![ublock dynamic filtering logging firefox](https://cloud.githubusercontent.com/assets/779630/5791687/086a1ebe-9f0d-11e4-83d5-71ce0170ef50.png)

<b>In Chrome</b>, it is vice versa. It is reported in popUI, but not in Request Logger..

![ublock dynamic filtering logging chrome](https://cloud.githubusercontent.com/assets/779630/5791686/06ea7a5c-9f0d-11e4-995a-833d30cb9f8a.png)

Thanks!

**Comment by gorhill** [comment]
I do get the same exact same behavior for both browsers when I submit both to the same **exact** steps: inline script blocking not reported in the pop UI, but reported in the request log. Did you force a page refresh for Chrome the exact same way you did for Firefox?

**Comment by harshanvn** [comment]
Ok. At the time i was testing in Chrome, i had 0.8.5.3. In Fx, it is 0.8.5.6. So, difference in behavior.

Now, i have updated chrome version too, and both behaves the same. (i.e., block is not reflected in popup UI, but reflected in Request Logger).

**Comment by gorhill** [comment]
So this become dup of #502.

Currently a log entry is created whenever a CSP header is added to disable inline scripts. Fix to #502 would require a log entry is created **only** if CSP header is added **and** at least one inline script tag is found on the page. And since this would be done after the page has been bound, both the pop UI and request log would report properly.

**Comment by harshanvn** [comment]
Ok, Thanks. At the time that defect was logged, inline script is logged in popUI

**Comment by gorhill** [comment]
> inline script is logged in popUI

Yes, before #516. Different symptoms, same underlying issue in need of same solution.
