### ISSUE TITLE
[Firefox] Please allow uBlock to install onto Firefox 36, have to downgrade from the latest beta because it doesn't support past 35

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#535]
Title basically says it all.

**Comment by harshanvn** [comment]
what error are you getting?
I have it installed on nightly...

**Comment by Deathamns** [comment]
You can install it from version [24](https://github.com/gorhill/uBlock/blob/master/platform/firefox/install.rdf#L20)+. But "official" support is from 29, which is still less than 36.
I have it installed on FF 24, 29, Nightly, SeaMonkey latest, Pale Moon latest.

**Comment by dkvasnicka** [comment]
I'm on Firefox 36.0 (I'm on the beta channel) and it says the addon cannot be installed because it's "corrupt" :)

![screen shot 2015-01-20 at 15 13 10](https://cloud.githubusercontent.com/assets/708118/5818580/edfbbafa-a0b6-11e4-8a4c-a0847f220743.png)

**Comment by Deathamns** [comment]
@dkvasnicka Try to download the extension first, then drop it into the browser window.

**Comment by gorhill** [comment]
@dkvasnicka Do you have Avast? Apparently there is [a feature in Avast which can prevent the **direct** installation of an add-on](https://github.com/gorhill/uBlock/issues/543#issuecomment-70588452).

**Comment by dkvasnicka** [comment]
@Deathamns  that worked, thanks! (no Avast here)
