### ISSUE TITLE
Feature request: option to temporarily load a blocked element

### ISSUE THREAD

**Issue by rekcuFniarB** [uBlock-LLC/uBlock#539]
For example, when I filter all images by dynamic filter it would be very useful to right click on a blocked image placeholder and select an option "display this element", which will temporarily display selected element until reloading of the page.

Without this function I find dynamic filters not very useful.

**Comment by gorhill** [comment]
Won't fix, not worth the effort, and extra code = overhead for all, not just ones using feature. Will re-open if I change my mind.

**Comment by seanrand** [comment]
@gorhill, seeing that this is a wontfix, would you consider a more generic approach to temporarily disabling dynamic filters for the current tab or browser session?

For example: A user has globally blocked third-party scripts and third-party frames and added noop whitelists for all his frequently used websites.
When visiting other random websites that break without third-party scripts or frames, the user has to add noops for each of them, cluttering the list of dynamic filtering rules with at least one noop rule for each website.

Being able to easily add temporary dynamic filtering rules for rare or one-off visits to those websites would be a nice to have feature. Maybe by ctrl-clicking in the dynamic filtering pane, ctrl-clicking the refresh button on the dynamic filtering pane to temporarily add a local `domain * * noop
` rule, or some other non-obtrusive way.
"Temporary" meaning either for the current tab, until refreshing the tab, or for the current browser session - whatever you would consider the best choice.

These temporary dynamic filtering rules wouldn't get added to the list of rules, or automatically removed again after refreshing/closing the tab/browser, or there could be a separate list of currently active temporary rules.
That would keep the list of dynamic filtering rules short and limited to frequently visited websites, without having to go through the list once in a while to remove rules for obscure websites or having to remove the dynamic filters via the pane before closing the tab.

As I said, it'd be a _nice to have_, I understand that it might not be worth the effort/overhead.

**Comment by matrixik** [comment]
I like similar behaviour in NoScript ("Temporarily allow")
http://www.ghacks.net/2013/05/25/top-5-noscript-features-that-you-may-not-know-about/

![ff-noscript-ghostery-footer](https://cloud.githubusercontent.com/assets/201930/6185192/df2d3b44-b36b-11e4-84fa-48a49b509af5.jpg)

**Comment by gorhill** [comment]
@seanrand 

> cluttering the list of dynamic filtering

Fixed in 0.8.7.1: all rules are temporary by default.

**Comment by seanrand** [comment]
Well that was quick ;)

Can't really explain how I missed that massive discussion from two days ago before writing my essay.
