### ISSUE TITLE
[EasyPrivacy] µBlock blocks FB login inside a FB app.

### ISSUE THREAD

**Issue by tleunen** [uBlock-LLC/uBlock#544]
We are using this function from Facebook to know the status of the current user `FB.getLoginStatus(callback)`, but with µBlock enabled, the callback is never fired by Facebook.

The only requests blocked by µBlock are:

```
||facebook.com/connect/ping?    sub_frame   https://www.facebook.com/connect/ping?client_id=xxxx

||google-analytics.com^ script  https://www.google-analytics.com/analytics.js
```

Is there something I can do to resolve this?

**Comment by gorhill** [comment]
I've seen `||facebook.com/connect/ping?` added yesterday to _EasyPrivacy_. You should report the problem to _EasyPrivacy_ maintainers. See https://forums.lanik.us/viewtopic.php?f=62&t=20541.

**Comment by gorhill** [comment]
Just curious: What is the FB app specifically?

**Comment by tleunen** [comment]
Sure, it's WSOP on FB: https://apps.facebook.com/poker_wsop/

**Comment by tleunen** [comment]
I don't have the issue with ABP btw

**Comment by gorhill** [comment]
You will if you use _EasyPrivacy_.

**Comment by tleunen** [comment]
Ok this has been resolved by the EasyPrivacy team. Thanks @gorhill for the help!
