### ISSUE TITLE
GUI for user-created filters?

### ISSUE THREAD

**Issue by alabrand** [uBlock-LLC/uBlock#55]
I'm well aware I can add my own filters already but similar to how Element Hiding Helper works I'd really appreciate some form of GUI to make the process a lot simpler, if not doable at all. As it stands I believe I'm forced to install Adblock Plus a long with Element Hiding Helper in order to create my own filters and then import them to uBlock.

**Comment by gorhill** [comment]
You mean like #4 ?

**Comment by alabrand** [comment]
Exactly. Just like that. I don't need it to be a priority but it'd make browsing a tad more enjoyable than it already is.

**Comment by gorhill** [comment]
Working on it. I want to do it well, to make it not too technical to be usable by any user, so I am taking my time.

So confirmed, dup of #4.
