### ISSUE TITLE
Add to addons.mozilla.org

### ISSUE THREAD

**Issue by sgarrity** [uBlock-LLC/uBlock#550]
Would be nice to be able to find/install via addons.mozilla.org. Thanks.

**Comment by Deathamns** [comment]
It will be there when it's ready. But it's still in beta.

To make it happen, at least these issues should be addressed:
**Preliminary Review**
- Support only from version 29 (for the time being).
- [x] #507
- [x] #522
- [x] #553

**Full Review**
- [ ] Implement toolbar button and pop-up with native API instead of `CustomizableUI`, which probably will be the cure for following issues: #474, #506, #514, #518, #545, #549, #579, #590, #631, #638
- [ ] #505
- [ ] #526

**Comment by nkestrel** [comment]
AMO's [preliminary review process](https://addons.mozilla.org/en-US/developers/docs/policies/reviews) is intended for experimental addons like this.

**Comment by pwr22** [comment]
It might be good to take advantage of this, because then people testing these (beta) builds won't have to manually come check for updates

**Comment by Deathamns** [comment]
@nkestrel  If it will be sent to AMO, no one will consider it as beta.

@pwr22 They don't have to install it manually, but first they will have to wait a bunch of time before it will be reviewed. The first review usually takes weeks, then if they don't like something, it will be rejected, and after we send a fixed version weeks of waiting follows again, because it will be put at the queue again. So, while they would review it, we can finish it, and send a final version instead of a beta.

**Comment by nkestrel** [comment]
> no one will consider it as beta

"ranked lower than fully-reviewed add-ons. Install buttons will have caution stripes and a notice that the add-on is experimental and not fully reviewed by Mozilla"

> after we send a fixed version weeks of waiting follows again

"Preliminary reviews are appropriate for experimental add-ons and provide a way to get user testing and feedback without going through the longer, more thorough review process. We aim to complete these reviews in under 3 days."

**Comment by Deathamns** [comment]
It doesn't work like that. Users expect quality from things that are on AMO.

Also, what you're quoting maybe was true a few years ago, but nowadays reviews are taking quite some time. Here's the latest [report](http://blog.mozilla.org/addons/2015/01/14/add-ons-update-59/).

> Most nominations for full review are taking less than 9 weeks to review.
> Most preliminary reviews are being reviewed within 6 weeks.

**Comment by gorhill** [comment]
I remember [this article](http://omniref.com/blog/blog/2014/09/08/writing-extensions-for-firefox-is-barely-worth-the-trouble/) from not too long ago:

> each review cycle takes weeks to complete. Couple a capricious rejection process with a latency that’s measured in weeks, and you’ve got the primary reason that we’ve released five full updates to our Chrome extension, in the time that we’re still awaiting one full approval from Mozilla

**Comment by nkestrel** [comment]
In my recent experience, the first preliminary review for an addon can take weeks like a full review, but after that it is possible for subsequent preliminary reviews to be granted in a matter of minutes.

**Comment by Deathamns** [comment]
@gorhill That article isn't far from the reality, but it depends on many factors...

@nkestrel Your extension seems to be relatively simple, so it's easier to review.

Giving it a second thought, exactly because of these long delays we probably should send it for a preliminary review, so basically while they get to reviewing it, we may finish it in that time.

**Comment by Deathamns** [comment]
@gorhill I marked 507 for Full Review. So, what then? May I send it or you will?

**Comment by gorhill** [comment]
If you don't mind taking care of the AMO version, that would be great -- I can't take any more tasks, rather the opposite.

Given how the project has grown, I will open an issue "Change official ownership to 'The µBlock Development Team'" in code/docs, though in the store it's fine to just use our own name for publication (gorhill = Chrome/Opera store, Deathamns = Firefox add-ons repo, Chris Aljoudi = Safari, etc.)

**Comment by gorhill** [comment]
Was it submitted to AMO?

**Comment by Deathamns** [comment]
No. I'm waiting for 0.8.6.0.

**Comment by Deathamns** [comment]
Could we include the non-minified versions of the JS files in the `lib` directory (since reviewers may have problem with that)?
Also Punycode.js has newer versions.

**Comment by chrisaljoudi** [comment]
@gorhill I think @Deathamns meant to merely **include** the non-minified versions, not necessarily use those (so just having `publicsuffixlist.js` in addition to `publicsuffixlist.min.js` in `lib`). I think 084f092 replaces them fully.

There are often certain, though minimal, performance advantages to using minified versions of libraries.

@Deathamns could you confirm?

**Comment by gorhill** [comment]
> performance advantages to using minified versions of libraries

To reduce bandwidth and possible load/parse time. I doubt it matters for a long running background page

**Comment by chrisaljoudi** [comment]
@gorhill yep, indeed. I guess it is insignificant; apologies.

**Comment by Deathamns** [comment]
@chrisaljoudi The performance gain from parsing is probably close to irrelevant for these small files, but the point here is to help the work of reviewers. If we would still include the minified versions, they would still need to do the extra work for verifying if the files are the same (by the way, I tried minifying publicsuffixlist.js from GitHub with the tool @gorhill mentioned in that file, but the minified results weren't the same, which would get a guaranteed rejection, since they won't start hunting for the correct file on GitHub, or tweak on the settings in the minifyer).

**Comment by chrisaljoudi** [comment]
@Deathamns sure, that makes sense.

It was quite silly to think about performance differences; sorry about that.

**Comment by Deathamns** [comment]
@gorhill Have you tried uploading any previous version to AMO? Because I get the error: Duplicate UUID found.
If it was you, then you can finish publishing it, or delete it to allow me to send it.
If not you, then someone else was kind enough to upload it for us (this happened with my extension too about a year ago).

**Comment by gorhill** [comment]
> If not you, then someone else was kind enough to upload it for us

What now? (I guess you were being sarcastic with "kind enough"). Who knows, maybe someone not nice uploaded it after putting in not nice stuff in it?

**Comment by Deathamns** [comment]
I'll write an e-mail then, but first I wanted to know if it was you, so we could resolve the issue faster without contacting AMO people. But if not, then I'm sending a mail...

**Comment by gorhill** [comment]
>  I wanted to know if it was you

I did try once just to see what would happen but it also got rejected because of "Duplicate UUID", which led me to think you started the process -- which I thought was nice that this was all taken care of.

**Comment by nkestrel** [comment]
Just change the <id> value in install.rdf. Preferably don't use a generated UUID as it is unnecessary and unfriendly (the id is used for the xpi filename). Most addons use the structure _name@website_ or _name@author_, so something like _ublock@gorhill_.

**Comment by gorhill** [comment]
@nkestrel Would `uBlock@https://github.com/gorhill/uBlock` works?

**Comment by Deathamns** [comment]
That id is not really seen by users, so its user-friendliness doesn't really matter.
But the real problem is that quite a few people have already installed it with the current id, if I would change the id for the AMO version, then no one would get automatic updates from AMO.

**Comment by sn260591** [comment]
@Deathamns But in what a difference if at the moment people all the same update ublock manually? You can change the id in the next version (0.8.6.1) and put it on the AMO.

**Comment by pwr22** [comment]
@sn260591 I believe all those existing installations will begin to update automatically

**Comment by ghost** [comment]
Any update on the AMO front?

**Comment by Deathamns** [comment]
I just received a response from the editors, hopefully I can upload it soon.

Note that I'll send version 0.8.6.0 with a small change: it will be installable only for Firefox 29+.

@gorhill What kind of screen-shots you want to have on AMO?

**Comment by gorhill** [comment]
@Deathamns re. screenshots, whatever you think a user may want to see before installing the add-on.

**Edit:** Not the charts though, as these were made using data from Chromium, so we can't use them for Firefox.

**Comment by gorhill** [comment]
Actually, I will repeat [this manual benchmark](https://github.com/gorhill/uBlock#memory) for Firefox.

**Comment by gorhill** [comment]
@Deathamns Here, official mem chart for Firefox: https://raw.githubusercontent.com/gorhill/uBlock/master/doc/benchmarks/mem-usage-overall-chart-20150205.png

**Comment by matrixik** [comment]
Looks really nice. Maybe in next benchmark you can also check μ Adblock for Firefox: https://addons.mozilla.org/en-US/firefox/addon/micro-adblock/
I'm using it now and it feel quite lightweight and have some nice additions like: `Remove Google/Yahoo/Naver/Daum redirect URLs from search page.` and `Option to enable/disable Mozilla Polaris tracking protection.`

**Comment by gorhill** [comment]
@matrixik The details of the benchmark [are here](https://github.com/gorhill/uBlock/wiki/Firefox-version:-benchmarking-memory-footprint). You just have to follow **carefully and exactly** every step to find out.

**Comment by pwr22** [comment]
@gorhill thanks for including Bluhell, barely below uBlock :)

**Comment by gorhill** [comment]
@pwr22 I wondered if uBlock could even be below Bluhell if cosmetic filters were not loaded (there is an option for this in uBlock), which would make uBlock and Bluehell a bit more comparable -- as Bluhell doesn't have DOM filtering.

**Comment by pwr22** [comment]
I'm very happy with uBlock now and will be switching. It is the memory \* tab and more performance of ABP that caused me to switch in the first place. I have a low power netbook and ABP was actually locking up FF on pageloads

**Comment by Xylemon** [comment]
"Implement toolbar button and pop-up with native API", is there any progress on this?

**Comment by eridal** [comment]
I just installed uBlock on my desktop, and removed the ABP .. now after firefox have sync'ed across all my devices I have no adblocker except on desktop

I would need to reinstall ABP, until this gets out there

**Comment by gorhill** [comment]
For translators:

![c](https://cloud.githubusercontent.com/assets/585534/6151870/cec62ada-b1e6-11e4-8914-8bf862a26f39.png)

**Comment by ghost** [comment]
Make uBlock available for Pale Moon and fantasies such as Mozilla's latest won't get into the way.
I'm running Firefox but should Mozilla continue their dictatorship (see what happened with Australis) I'd be seriously thinking of abandoning the ship. Whatever, should this extension signing prevent uBlock in any way of being available on Firefox that I'd quit this browser. I've been waiting too long for an add-on that would perform as uBlock does, so if it had to be blocked by a company's hysteria I'd move away from that company, and that is no joke.

**Comment by midi** [comment]
It's live: https://addons.mozilla.org/en-US/firefox/addon/ublock/

**Comment by sgarrity** [comment]
Awesome, thanks.

**Comment by coctic** [comment]
Will new versions be on addons.mozilla.org? Now it says the current verison is 0.8.8.2, Version 0.9.1.0 can be found deep in versions history.

What about newer versions from github?

**Comment by EchoDev** [comment]
@coctic 
New version have to be reviewed by Mozilla before they get an 'official' update on the addons.mozilla.org site but you are free to just update using the xpi provided on github.

**Comment by coctic** [comment]
I know, and I updated manually. I just wanted to ask about plans to upload new versions to AMO. If the problem is with review, then I'll just wait.

Thanks.

**Comment by gorhill** [comment]
@coctic see #1006.
