### ISSUE TITLE
Feature request: off by default

### ISSUE THREAD

**Issue by Epskampie** [uBlock-LLC/uBlock#551]
Hi, first of all, thanks for the work on uBlock, it works great!

I would like to propose a feature where nothing is blocked by default, exept on the sites where i explicitly enable ublock. Mostly I don't mind ads, and I want site to be able to generate revenue through them, exept for a few exceptions where they are really obnoxious.

I would really like it if uBlock supported this mode, which is in essence an exact reversal of the way it works now (on by default, can be disabled forever on a site by a single click).

**Comment by gorhill** [comment]
This has been requested before: #177.

Sorry, but I personally can't support this, it's like asking me to give users the ability to opt out of corporate stalking, of being data-mined by default. uBlock serves users' interests, not data miners' interests.

Ads are only the small visible portion of the corporate stalking. Users should care even more about the portion that is not readily visible. Turn on _"I am an advanced user"_ mode and select only _EasyList_ as the active filter list, and see for yourself all the remote connections, even without ads on the page.
