### ISSUE TITLE
[Firefox] Please make µBlock Thunderbird compatible

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#552]
Many Firefox extensions also work in Thunderbird as both are Gecko based. I have installed, e.g., Adblock Plus and it blocks a lot of requests in those cases where I allow HTML mails. 

I tried to install µBlock in Thunderbird v. 31.4.0 but got an error that it was incompatible. I assume that only minor adaptions would be neccessary to make it work in Thunderbird. Would be great to have it available for that email client, if possible!

**Comment by gorhill** [comment]
I didn't even know add-ons could be installed in Thunderbird. Sounds pretty cool.

So far @Deathamns is to go-to dev for the Firefox version of uBlock. Hopefully at some point I will have a good grasp enough of the platform-specific code of Firefox that I will also be able to address Firefox issues.

**Comment by gorhill** [comment]
Ok, I could make it installable in Thunderbird by adding:

```
    <!-- Thunderbird -->
    <targetApplication>
        <r:Description>
            <id>{{3550f703-e582-4d05-9a08-453d09bdfdc6}}</id>
            <minVersion>31.0</minVersion>
            <maxVersion>31.0</maxVersion>
        </r:Description>
    </targetApplication>
```

In `install.rdf`, however it seems there are further compatilibility problem afterward: the dashboard is non-fonctional, no icon in toolbar, etc. Not even sure it's actually filtering.

**Comment by ghost** [comment]
> I didn't even know add-ons could be installed in Thunderbird. Sounds pretty cool.

Oh yes, there are a lot of them:

https://addons.mozilla.org/en-US/thunderbird/

**Comment by gorhill** [comment]
@tlu1024 Actually I knew it supported add-ons, I meant, I didn't know we could install Firefox add-ons.

**Comment by ghost** [comment]
> Ok, I could make it installable in Thunderbird by adding:

Funny, that didn't work on my system ... I'm still getting a message that it is incompatible.

**Comment by gorhill** [comment]
@tlu1024 It was a quick test, so I entered **my** Thunderbird version, you may have to adjust for yours.

```
<minVersion>31.0</minVersion>
<maxVersion>31.*</maxVersion>
```

**Comment by ghost** [comment]
@gorhill Raymond, my Thunderbird ID is the same as yours, it's also used in all other extensions I've installed. I've also added 

```
                   <maxVersion>38.0</maxVersion>
```

to be sure that it works with 31.4.0.

**Comment by jostyee** [comment]
so maybe it could work on [Postbox](http://www.postbox-inc.com) , too?

**Comment by DaAwesomeP** [comment]
Is there any progress on this? Adblock Plus works great in Thunderbird, and this would be a great upgrade to that. The options button seems to open a really small windows where the `3rd-party` tab loads endlessly. Also, you must not have double brackets in the UUID. This is what I used:

``` xml
<!-- Thunderbird -->
<targetApplication>
    <r:Description>
        <id>{3550f703-e582-4d05-9a08-453d09bdfdc6}</id>
        <minVersion>31.0</minVersion>
        <maxVersion>38.0</maxVersion>
    </r:Description>
</targetApplication>
```

**Comment by DerekTurtleRoe** [comment]
I thought Firefox add-ons and Thunderbird add-ons were exactly the same in terms of code and everything?

**Comment by DaAwesomeP** [comment]
Yes, in the way that the code is written. However, Firefox and Thunderbird function differently. For instance, there are tabs in Thunderbird, but there is no address box. Extensions in Thunderbird usually open their options in new windows.

**Comment by DerekTurtleRoe** [comment]
Oh OK. Good to know. So basically we need to just write a modified version for Thunderbird that adheres to the Thunderbird GUI pretty much?

**Comment by voidzero** [comment]
Heya, can't wait to try this out... ABP is costing a lot of RAM!

**Comment by DaAwesomeP** [comment]
Yeah, RAM usage overall in Thunderbird is pretty bad, and ABP makes it worse.

**Comment by DerekTurtleRoe** [comment]
It is a problem in most web browsers for some reason. Chrome, Firefox, and any forks of those as well. I have noticed even Opera and Safari are starting to do it as well (although I never use either except for development and testing).

Also, AdBlock Plus has a fairly nefarious way of allowing advertisements in my opinion. Yeah, it is open-source and free, but I feel uncomfortable using a plugin that accepts money in exchange for ads when the whole purpose is that I don't have ads anymore, except for sites I whitelist.

Anyway, if I can help with the Thunderbird port at all, let me know and I will look into it. I have a feeling the developer might want to do it himself though.

**Comment by DaAwesomeP** [comment]
The purpose of GitHub and open source projects is that everyone can
help. From my try with it, it seems that the options windows (normally a
tab in Firefox) is really small and doesn't really work. The popup view
when you click the icon also doesn't work.

**Comment by DerekTurtleRoe** [comment]
I know, but that doesn't mean that people want certain ports or something written by somebody else. It is up to the author of the original software to decide.

I think in the latest version of Firefox and Thunderbird they made some additional changes to make it easier for Thunderbird add-ons and Firefox add-ons to work better, so hopefully at some point it will be practically the same thing.

**Comment by davidhedlund** [comment]
@chrisaljoudi @gorhill Adblock Edge works with Thunderbird (and more importantly with Icedove) and do not come with a white list. To sad it will be stopped: "**This addon will be discontinued on June 2015**" - https://addons.mozilla.org/en-us/thunderbird/addon/adblock-edge/?src=search

Adding this here so you can plan you development schedule.

**Comment by DerekTurtleRoe** [comment]
Does Adblock Plus work in Thunderbird?

**Comment by coctic** [comment]
Adblock Plus does work in Thunderbird. It is very useful for RSS.

**Comment by DerekTurtleRoe** [comment]
Hm. I can look into it when my dev machine is up and running. Until then, maybe somebody could look at Adblock Edge and Adblock Plus and see how it works there?

**Comment by DaAwesomeP** [comment]
One main problem with uBlock is that is improperly opens it settings page. I think that that may be part of the problem. It needs to open a window with the settings page, not a tab in Thunderbird.

**Comment by DerekTurtleRoe** [comment]
I thought opening a new tab is the default action in Chromium, Firefox, Thunderbird, and forks and derivatives?

Isn't that a preferences thing? Like an option you should be able to tick a check box or something?

**Comment by davidhedlund** [comment]
Thunderbird don't open up new tabs with CTRL+T like Firefox. However, both softwares open Add-ons in a new tab. @vgturtle127

**Comment by DerekTurtleRoe** [comment]
That's what I thought. So couldn't you just add something to the preferences that told it to open a new window?

**Comment by davidhedlund** [comment]
@vgturtle127 You mean new tab? Yes that should be possible but I'm not a Mozilla developer.

**Comment by DaAwesomeP** [comment]
You can try it. Clicking the options button doesn't really work. Last time I tried it is opened a really small window where nothing worked in it. I'm not a Mozilla developer either.

**Comment by davidhedlund** [comment]
@DaAwesomeP What option button? Do you mean in Thunderbird?

**Comment by DaAwesomeP** [comment]
The settings button for the addon as found in `about:addons`.

**Comment by AlexVallat** [comment]
The settings are a relatively easy thing to handle. It is, in fact, entirely possible to open a web page in a new tab in Thunderbird, and we could do so for showing the options page.

The real difficulty is that the thunderbird window is not like the firefox window. It doesn't have the same structure, and things which uBlock assumes about window/tabBrowser/browser/document do not hold true. It would probably not be too much of a stretch for uBlock to work where Thunderbird has opened a web page in a new tab, but that's very rare and not very useful. Where you'd actually want it to work is for pages in the message panel in a mail tab.

To get uBlock to work with Thunderbird there would probably need to be some structural changes, or at least some quite heavy compatibility layer between the uBlock cross-browser API and what Thunderbird actually provides. I don't know for certain that it would be possible, as I don't know Thunderbird in depth, but assuming that it is possible it's going to take a fair bit of work from someone who knows Thunderbird quite well.

**Comment by DerekTurtleRoe** [comment]
Well, I'm getting a shiny new Samsung 850 EVO SSD soon, and after that I want to upgrade my OS from 7 to 8.1. Hopefully after that I can start my full-time development stuff. Until then, I am going to research Thunderbird and see what I can learn. I'm going to assume that Thunderbird is similar to Firefox, but I thought Mozilla said they would only be maintaining it from now on? Like security updates and bug fixes only? Is there a fork which would add features and stuff? If so, we should investigate that too...

**Comment by ghost** [comment]
> I thought Mozilla said they would only be maintaining it from now on

No, it's still under development by the community, and a new version with a lot of new features will be released in the coming weeks, see

https://blog.mozilla.org/thunderbird/2015/04/thunderbird-38-goes-to-beta/

**Comment by davidhedlund** [comment]
Very good.

**Comment by DerekTurtleRoe** [comment]
Awesome, community made applications are great!

I will download the beta when I get my dev machine up and running and start testing.

**Comment by davidhedlund** [comment]
@chrisaljoudi Is this a high priority?

**Comment by AlexVallat** [comment]
This is unlikely to happen.

@vgturtle127 suggested he might investigate working on it https://github.com/chrisaljoudi/uBlock/issues/552#issuecomment-100104400 but I've heard nothing since then.

I won't be developing it myself, as I explained in my earlier comment, and I am fairly certain that @chrisaljoudi won't be either.

**Comment by DerekTurtleRoe** [comment]
Sorry I have been silent for a while. I have had computer issues as usual and I also am currently at a friends funeral.

I will back in about a week or so, and around the same time I will try to get back on the saddle and see what I can whip up.

I may need some assistance with it though, as my system has an extremely small hard drive and I keep running out of space.

**Comment by davidhedlund** [comment]
@vgturtle127 Thank you in advance.

**Comment by flyingzebras** [comment]
@vgturtle127 Can you try to make uBlock Origin Thunderbird compatible.

**Comment by DerekTurtleRoe** [comment]
My development machine is currently under construction, when I get it back up and running, I will continue working on all of my GitHub projects, which will include looking into this.

**Comment by flyingzebras** [comment]
@vgturtle127 Basic Thunderbird support have been added in https://github.com/gorhill/uBlock/releases/tag/1.2.2b2.

**Comment by flyingzebras** [comment]
Basic Thunderbird 38.3.0 support have been added in uBlock Origin 1.2.2b2: https://github.com/gorhill/uBlock/releases/tag/1.2.2b2.

**Comment by ale5000-git** [comment]
@gorhill: Apparently it can no longer be installed in Thunderbird.

Any workaround?

**Comment by davidhedlund** [comment]
@ale5000-git This project is dead, use [uBlock Origin](https://github.com/gorhill/uBlock/issues) instead. Specifically see https://github.com/gorhill/uBlock/issues/117

**Comment by ale5000-git** [comment]
@davidhedlund: I know, I have just confused the page

**Comment by davidhedlund** [comment]
@ale5000-git Its easy to do that, I has happens to me too with this project.

**Comment by davidhedlund** [comment]
@ale5000-git Thunderbird must get WebExtension support first: https://bugzilla.mozilla.org/show_bug.cgi?id=1396172

**Comment by tlcarpenter** [comment]
I'm running TB 52.4.0 installed on Xubuntu 16.04.3. I downloaded version 1.14.18 of "uBlock0.webext.xpi" and "uBlock0.firefox.xpi" from "https://github.com/gorhill/uBlock/releases". When I attempt to install "uBlock0.webext.xpi" using TB's "Add-ons Manager/Install Add-on From File..." I get the error "This add-on could not be installed because it appears to be corrupt." I am able to install "uBlock0.firefox.xpi" using TB's "Add-ons Manager/Install Add-on From File...".

**Comment by davidhedlund** [comment]
@tlcarpenter https://bugzilla.mozilla.org/show_bug.cgi?id=1396172

**Comment by davidhedlund** [comment]
@tlcarpenter Can you please report https://bugzilla.mozilla.org/show_bug.cgi?id=1396172 to https://github.com/gorhill/uBlock/issues/117 ?
