### ISSUE TITLE
Compare to Privacy Badger

### ISSUE THREAD

**Issue by cgarvis** [uBlock-LLC/uBlock#554]
How does this compare to EFF's [Privacy Badger](https://www.eff.org/privacybadger)?

**Comment by naugtur** [comment]
It's differnt :trollface: 

But seriously, apples to oranges. Privacy Badger can be set to only block sites from setting cookies to track you. If you want to keep most of the privacy while still watching most of the ads online (those that work without cookies), stick to the PB.
uBlock allows blocking page elements, ads, so not just tracking, but content as well. (and it says it's more advanced than adblock syntax, but I don't know the details) and it works with well known lists of ads. Should block everything there is.

I'm not a uBlock contributor, so this answer is probably incomplete.

**Comment by gorhill** [comment]
@naugtur Privacy can and do block network requests, not just cookies.

@cgarvis I ran benchmarks a long time ago -- consider these obsolete and useless. The difficulty in benchmarking Privacy Badger is that it needs to be "trained" first, and even if I tried to train it before I benchmarked, I didn't feel too confident I trained it well enough that the results could be trusted. So eventually I stopped benchmarking it.

So given how time consuming benchmarks can be, I prefer to let some interested third-parties to find out.

**Comment by gorhill** [comment]
Ok I will have to be more strict with issues. The entry here is not really an issue, it's more of a question which can be answered by anyone willing to test for themselves.

**Comment by rodneyrod** [comment]
So I guess the question new users are asking is, like myself, do I gain anything by having uBlock AND Privacy Badger installed or does it just end up duplicating functionality?

Furthermore, what about other tracker blocker solutions like Ghostry and Disconnect? Am I gaining anything by running more than just uBlock?

**Comment by gorhill** [comment]
Re. Ghostery/Disconnect: [µBlock and others: Blocking ads, trackers, malwares](https://github.com/gorhill/uBlock/wiki/%C2%B5Block-and-others:-Blocking-ads,-trackers,-malwares#data-diffs).

In the end, it's all about the filters/rules. I use default-deny, so surely Privacy Badger is no match. So it's how you use uBlock and which filter lists are selected which answers your question.
