### ISSUE TITLE
[Android] Please consider Android version

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#556]
I know that you're already very busy with the existing µBlock versions. Nevertheless, an Android version would be very welcome at some point in the future. I'm not talking about a version for the Android version of Firefox (#524) but about a **native** Android apk that blocks system-wide and would be able to replace both [Adaway](https://f-droid.org/repository/browse/?fdfilter=adaway&fdid=org.adaway) and [Adblock Plus](https://f-droid.org/repository/browse/?fdfilter=adblock&fdid=org.adblockplus.android). 

It would require root access and would probably be removed from the Google Play Store as happened before to both apps above.

So ... just an idea if you will ever feel bored ;-)

**Comment by haarp** [comment]
Adaway employs DNS poisoning while Adblock Plus (Android app) creates a forced proxy server that all requests go through.

That's fundamentally different from what browser extensions are doing. There is nothing uBlock can do here.

**Comment by ghost** [comment]
@haarp I know how Adaway and ABP on Android work. I was explicitly **not** talking about a browser extension.  Thus, I don't understand your reply. 
It should be possible to use the platform-independent code of µBlock for an Android version. I know that won't happen in the foreseeable future (if I remember correctly gorhill mentioned somewhere that he doesn't even own a smartphone). Nevertheless, I opened this issue as a placeholder for a possible  development sometime.

**Comment by haarp** [comment]
uBlock is written in Javascript. It's platform-dependenant, the platform being a browser. And even if it could run stand-alone, what is it supposed to do? uBlock blocks requests in the browser and modifies websites. How is that supposed to work outside of a browser? To get global blocking in the entire Android OS, a fundamentally different method is necessary, like those utilized by Adaway and Adblock for Android.

**Comment by ghost** [comment]
µBlock's engine is platform-independent, that's why it was possible to create Firefox and Safari versions. And I know, of course, that a different method for global blocking would be necessary (I had already presaged this in my first post), probably a proxy server like ABP does it. And, btw., gorhill was already [thinking](https://github.com/gorhill/goproxy) about such a solution some time ago.

**Comment by lwatsondev** [comment]
Yes, it's platform independant across the _browser_ platform. Platform independence doesn't mean it should run on literally anything that can execute code.

**Comment by behrmann** [comment]
I would be quite content if there was a version of uBlock for Firefox on Android. Does this already work or are there any plans?

**Comment by ghost** [comment]
Does just installing the xpi not work?

**Comment by lwatsondev** [comment]
No, see my comments on #524

**Comment by chrisaljoudi** [comment]
**System-wide,** system-level blocking only depends on the network requests being made, and that includes all the requests the system can capture.

In other words, a system-wide blocker can't be making decisions based on, say, what **page** an XHR request is coming from. It _might_ be coming from a webpage in a browser, but it might also be coming from an app, a background service, a system software update, or any number of sources — and those aren't "pages" with URLs.

So, a system-wide µBlock would:
- have no concept of Dynamic Filtering
- have no concept of cosmetic filters (just ignores them)
- not understand/enforce `$thirdparty`, `$domain`, `$script`, `$image`, etc. rules
- have a different concept of what whitelisting means, or none at all
- ...

That's a lot.

While µBlock's conceptual core is platform-independent, it's still **very much a browser extension** by nature (`background.js`, `pagestore.js`, `contentscript-start.js`, ...).

A system-wide blocker like the one you're talking about would **only** really share the matching engine µBlock has (actually just _part_ of it).

That's not a "version of µBlock" — that's a sibling at best; a different, though related, project.
