### ISSUE TITLE
confused by "That said, it's important to note that using a blocker is NOT theft. "

### ISSUE THREAD

**Issue by Pomax** [uBlock-LLC/uBlock#558]
linguistically, there is no contrast, which the "that said" construction generally sets up. Nothing in the preceding text even remotely implied that blocking _is_ theft, so emphasizing it actually isn't reads odd.

In fact, before seeing this project's README.md, I'd never heard anyone make that comparison other than the tweet you link to, and as a personal opinion in 140 characters (even if tweeted by someone respected in web tech) is just that; a throw-away opinion. The paragraph literally comes out of nowhere, talking about a problem that as far as I know doesn't exist; the README.md is a lot better with that paragraph just removed entirely

**Comment by gorhill** [comment]
> I'd never heard anyone make that comparison other than the tweet you link to
- https://www.google.ca/search?q=adblock+is+theft
- https://ca.search.yahoo.com/search?p=adblock+is+theft

**Comment by Pomax** [comment]
yes, search engines will find results. That doesn't change the fact that it's a topic that doesn't seem to be an _actual_ issue, and certainly not one that pervades the general tech communities. Seeing this billed as an out-of-left-field paragraph in a README.md on a blocker plugin is a little bit like going to a Chinese acrobatics performance, and suddenly being told about how Falun Gong shouldn't be repressed. That's a great opinion to hold, but has nothing concretely to do with the thing we actually came for =)

**Comment by gorhill** [comment]
I do believe it is an issue, as I see that line spouted mindlessly too often. So it's my preemptive counterpoint to that "argument" often raised regarding blockers. I did not write the README according to what _you_ have never heard, I wrote it according to what I've been hearing.

**Comment by Pomax** [comment]
fair enough. As an out-group visitor, it's weird to see that in a README.md, but it's your project.

**Comment by RandomAcronym** [comment]
@Pomax I believe "that said" works because the readme tries to say that µBlock is a "Blocker", not an "Ad Blocker", but also make clear that there is nothing wrong with blocking ads, It's just not the main focus of µBlock.
