### ISSUE TITLE
setting page address bar says chrome:\\ in firefox

### ISSUE THREAD

**Issue by kalyanac** [uBlock-LLC/uBlock#559]
The settings page address bar says:

chrome://ublock/content/dashboard.html

in Firefox. 

Also 

figuring out how to get to the settings page is pretty darn hard. I just started clicking randomly and figured it out. I had to click on the top black bar to get to the settings page. maybe a button would help. 

and is it possible to stop showing the number of blocked items on the button?

**Comment by gorhill** [comment]
> The settings page address bar says `chrome://ublock/content/dashboard.html`

Why is this an issue?

**Comment by kalyanac** [comment]
its not an issue. I was just confused with the leading "chrome://" when I am using Firefox.

**Comment by ghost** [comment]
https://en.wikipedia.org/wiki/Chrome_Mozilla

**Comment by kalyanac** [comment]
Sorry, I dont have enough knowledge in web technologies to make much sense of it. But it seems like you dont think its an issue, thats all I need to know. 

thank you

**Comment by RandomAcronym** [comment]
I beleve this will explain it better.

> In a Web Browser, the chrome refers to the browser's user interface: that is, any toolbars, menu bars, tabs, and everything that surround the web page being displayed. It must not be confused with the Google Chrome web browser which is often refer as "Chrome".
> [Mozilla](https://developer.mozilla.org/en-US/docs/Glossary/Chrome)

Mozilla uses [Chrome://](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial/The_Chrome_URL) too, even before Google released a browser.

**Comment by kalyanac** [comment]
I see. that helps. thanks!

**Comment by RandomAcronym** [comment]
No problem @kalyanac , I remember back when I first used Google Chrome thinking that would confuse someone.
