### ISSUE TITLE
EasyList doesn't block all ads

### ISSUE THREAD

**Issue by arcaneAgilmente** [uBlock-LLC/uBlock#56]
Due to the way Adblock Plus makes their lists, not all ads get blocked. There is a set of lists for Adblock Edge that allow everything to get blocked. Would it be possible for these to be implemented in the future? (Apparently some people have issues using them, could they be replicated by removing all the exceptions? As an optional list of course.)

https://bitbucket.org/adstomper/adblockedge/issue/78/adblock-edge-is-using-adblockplusorg

**Comment by kurtextrem** [comment]
I think those are to make some websites work which would break otherwise.

**Comment by gorhill** [comment]
Yes, it's their purpose. I originally thought wrongly they were to allow ads on some sites, but it is really to unbreak sites -- thought there might be a lot of obsolete rules overall, including in the exception rules.

**Comment by arcaneAgilmente** [comment]
Yes however they still let "acceptable" ads through and that can't be disabled. (As well as things like Hulu and the like.) I would just like the option of having them available. (Provide a "This will break things warning. If you have trouble use the regular EasyList instead." when someone checks the filter box?)

**Comment by gorhill** [comment]
I think I would prefer the issue here being addressed by issue #6. Issue #6 is a bit of a "challenge" too, not because of code, but because the local storage is limited, and I worry at this point a user could run out of local storage if using a lot of external lists. This is why I am taking my time for #6, but I might address earlier than later now, as the request for such feature comes up regularly.

**Comment by arcaneAgilmente** [comment]
That's another way to do it. I was just hoping for something automated because I've never been able to get the ABE No-Mercy lists to even load. (But apparently other people have)

**Comment by gorhill** [comment]
> never been able to get the ABE No-Mercy lists to even load

Then this will be a good list to use as test case for when I address #6.

**Comment by arcaneAgilmente** [comment]
Maybe you could have in an option that allows for picking of which specific filters we would like enabled/disabled?

**Comment by gorhill** [comment]
~~Another option could be "Ignore exception filters", with a prominent warning about sites breakage. I just wonder how many users of blockers really long term use that kind of stricter approach. I wouldn't want to start to throw settings in there if there is not a solid demand for it. I don't want to start to create settings at the whim of anybody's personal view, but rather if there is a real user base out there asking for a specific feature.~~ bad idea: there might be "bad" exception filters in there, but we can't just disabled **all** exception filters, there are not all "bad".

**Comment by gorhill** [comment]
With fix to #6, users can subscribe to their choice of external lists.
