### ISSUE TITLE
[EasyPrivacy] 6000.ru JavaScript error

### ISSUE THREAD

**Issue by gaydenko** [uBlock-LLC/uBlock#563]
Any section selection form the main page of 6000.ru (it is SPA) results in JavaScript error reporting. Probably it is similar to https://github.com/AdguardTeam/ExperimentalFilter/issues/290

**Comment by gorhill** [comment]
You will find javascript errors reported on some sites even without a blocker. The real questions are:
- Is the site broken by the use of the blocker?
- If yes: Is the breakage causes by one of the filter lists?
- If yes: find out who maintain the list and report the issue to the maintainer

**Comment by gorhill** [comment]
_EasyPrivacy_  contains the block filter `||yandex.ru/metrika/`, so you will have to report to EasyPrivacy maintainers the issue for `6000.ru`: https://forums.lanik.us/viewforum.php?f=64
