### ISSUE TITLE
[Firefox] Please make µBlock auto-update

### ISSUE THREAD

**Issue by slacka** [uBlock-LLC/uBlock#566]
Assuming you continue to focus on performance and not add any features that might negatively affect it, could you use firefox's auto update addon infrastructure? µBlock has allowed me to once again use an adblocker on my netbook. Thank you for such a great piece of software!

**Comment by Deathamns** [comment]
Depends on #550.

**Comment by GithubUser5462** [comment]
I don't want to nag or something and you'll probably be uploading it to AMO soon, but are you sure you can't make a github hosted version updateable?

The pdf.js and Shumway addons by Mozilla have development versions uploaded on github and they are both updatable. 

https://github.com/mozilla/pdf.js#firefox
https://github.com/mozilla/shumway#extension

Links in the description. Just a suggestion, sorry if it doesn't work / isn't possible, i don't really know how github and addons work.

**Comment by Deathamns** [comment]
It's possible to make it update-able from GitHub, but what's the point if AMO will do it for us?

**Comment by gorhill** [comment]
Sort of dup of #550.
