### ISSUE TITLE
[EasyPrivacy] Angular site not working

### ISSUE THREAD

**Issue by farski** [uBlock-LLC/uBlock#571]
We're seeing issues with our Angular-based site when using uBlock; it hangs on changing state. The logs don't show anything related to the site being blocked, but when the site's domain is whitelisted it starts working again. Shouldn't the site's own domain be whitelisted by default?

**Comment by gorhill** [comment]
I need a URL to investigate myself what is the problem.

**Comment by farski** [comment]
http://beta.prx.org

**Comment by gorhill** [comment]
When unblocking Google Analytics, the links work fine. So you need to report to the maintainers of EasyPrivacy: https://forums.lanik.us/viewforum.php?f=64

Another solution which is better IMO is to ensure the links are still functional when visitors block Google Analytics. Just like the [non-beta version of your site](http://www.prx.org/), where links still work fine with Google Analytics blocked.
