### ISSUE TITLE
Twitter's Follow button is blocked on twitter.com

### ISSUE THREAD

**Issue by fizz** [uBlock-LLC/uBlock#573]

**Comment by gorhill** [comment]
I see it fine. What filter lists you have enabled? Also, any custom filters?

**Comment by chrisaljoudi** [comment]
@fizz @gorhill couldn't reproduce the Follow button getting blocked on twitter.com — I see it fine.

**Comment by darakian** [comment]
I can also see the follow button.
-Firefox 35, uBlock 0.8.5.7

**Comment by fizz** [comment]
Hmm, I am using the Safari version of uBlock, with default settings. I updated its filter lists and it's no longer blocking the follow button, so I'm closing this.
