### ISSUE TITLE
Enable a Blacklist-only mode

### ISSUE THREAD

**Issue by mcdado** [uBlock-LLC/uBlock#577]
I'm not sure if this is possible at the moment.
I would like to have uBlock opt-in for hostnames in a simple way, simply by the click of a button if possible. By default it would need to be off. This because, assuming the privacy concerns, I would still like to give a change to a website first, and then decide to block it, not the other way around.

**Comment by gorhill** [comment]
> I would still like to give a **change** to a website first

I guess you meant "chance".

Anyways, dup of #177.

**Comment by mcdado** [comment]
Yup that's right…
Anyways, that's the reason I'm currently using AdBlock instead of ABP. I guess beyond the ideal reasoning, technically this could be an opt-in feature/mode. Up to you…

**Comment by gorhill** [comment]
Thing is, the safe assumption which is most likely to be true is that by default web sites are going to force your browser to connect where it's not really needed. So if you want to give a chance to a web site, it's better you do it expressly than by default.

**Comment by gorhill** [comment]
Incidentally, a side effect to fixing issue #682 is to allow blacklist mode.
