### ISSUE TITLE
[Firefox] Button label with number of blocked requests switches to superscript with red background

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#579]
after entering interface customization mode.
Rright click on the button -> Customize and then Exit Customize

![up](https://cloud.githubusercontent.com/assets/886325/5858201/a61cb404-a251-11e4-82a0-520cbb1511f1.png)
![2](https://cloud.githubusercontent.com/assets/886325/5858337/aef4002c-a252-11e4-8af1-558f30e8c705.png)

Fx 36b2, uBlock 0.8.5.7

**Comment by Betsy25** [comment]
I can confirm this behavior with FF38.

**Comment by Deathamns** [comment]
Possible fix in 9fe8f414.
Also, now the the browser's default positioning is used (the red icon you see on the screenshot above).

**Comment by ghost** [comment]
Looks good. Thank you.

**Comment by ekerazha** [comment]
Occasionally, I still see the red badge in v 0.8.9.1.

**Comment by Deathamns** [comment]
@ekerazha It changes to red permanently, or just for a moment after you did some customization?
If it's permanent, and you're using the default theme, then I don't know.
When it just flashes to red for a moment after customization, then that is normal.

**Comment by ekerazha** [comment]
@Deathamns Permanently and without touching the customization UI.
I'm not sure but it could happen when you recover a browsing session after a browser crash.

P.S.
I tried to deliberately crash Firefox but I couldn't reproduce the issue... I'll look at it when it will happen again.

**Comment by gorhill** [comment]
I've seen this too. It's permanent. But I've been trying to figure what triggers this, no success so far.

**Comment by TteokbokkiNari** [comment]
Last time my video driver crashed it became red permanently. 
Not sure if it can help it any way, but it might give some leads?

**Comment by ekerazha** [comment]
@gorhill I just found a way to trigger it:
1) Resize the browser window until the icon gets hidden.
2) Restore the window size.

**Comment by gorhill** [comment]
@ekerazha Nice one!

Now will be to figure how to fix this. Or it could be argued it is a Firefox bug, not sure.

**Comment by Deathamns** [comment]
25d5166. They may be other cases too when the icon is removed/hidden from its area.

**Comment by alejandrolemus** [comment]
Seems OK now in 0.9.0.1 for the resize/restore (I think you can see a <i>really</i> fast color change while restoring the windows size) 
Too bad, red was kinda cool :)
