### ISSUE TITLE
playhd.eu*.html filter may not be working correctly, please check.

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#58]
Hi Gorhill,

When i visit playhd.eu (http://playhd.eu/9zkcjejdcr6x, beauty and beast serial), I see a pop up opening up and it goes different ad sites each time.

I tried few filters adding my self like.. 
||great-discount.net
||icubeswire.com
||zxxds.net
||playhd.eu/advertisement.js
||onclickads.net

but each time i visit above url, a new site is redirected to thru 
http://playhd.eu/test4.html (or)
http://playhd.eu/test2.html (or)
http://playhd.eu/test3.html
I see below filter is applied to block the above html page -
playhd.eu*.html 

But not sure if it works correclty. As it redirects to other sites..Please check.

Thanks, Harsha

**Comment by gorhill** [comment]
uBlock doesn't support the `$popup` filter option: https://github.com/gorhill/uBlock/wiki/What-%C2%B5Block-can-and-can-not-(currently)-do#%C2%B5block-has-all-the-features-abp-has.

Chromium has a popup blocker built-in, but as seen above, it doesn't seem to work reliably in this particular case. So I guess I will have to implement the `$popup` filters.
