### ISSUE TITLE
Block images applied as a background image

### ISSUE THREAD

**Issue by cyrusdavid** [uBlock-LLC/uBlock#584]
https://cipherli.st/

I'm looking at the background image applied to the `<body>` element. Is it possible to block that through a filter or rule?

**Comment by pwstokes225** [comment]
I don't think it can be done using the element picker UI, but a custom net filter will work:
`||cipherli.st/img/lock-trans.png`
Note that you might have to perform a cache refresh (`CTRL+F5`) for the filter to actually take effect.

**Comment by cyrusdavid** [comment]
Awesome! Thanks @pwstokes225 :sparkles: :sparkles:
