### ISSUE TITLE
[Firefox] Can't find Button/Addon's Icon

### ISSUE THREAD

**Issue by AMZMA** [uBlock-LLC/uBlock#590]
can't find button
![Image of Yaktocat](http://puu.sh/eWIbx)
but, addon still working finely ![Image of Yaktocat](http://puu.sh/eWILb)

Firefox 28, uBlock 0.8.6.0

please don't tell me to upgrade my firefox

**Comment by Deathamns** [comment]
You can install it for older versions (from version 24), but proper support begins from 29.

**Comment by ghost** [comment]
> Make an ad block that is less resource intensive
> Requires it to be used on the most resource intensive versions of Firefox

Wat

**Comment by fung00** [comment]
Seems like it should be pretty easy to provide an icon for the many, _many_ users like myself, who have no intention of adopting the idiotic Australis UI, and who will be sticking with either FF28 or one of the forks that retain the older UI. You don't accept donations, but I can promise our undying gratitude...

**Comment by Marcehs** [comment]
+1 for missing icon in Pale Moon.  I have tried a variety of different solutions to block ads and trackers but I have to hand it to ublock.  It is by far the best out of everything I have tried!  Big thumbs up.

**Comment by sixxi** [comment]
+1 for this palemoon is very good browser.

**Comment by mattatobin** [comment]
What was the last version before refactoring to target CustomizableUI (Australis). Namely the last version to use toolkit widgets?

**Comment by gorhill** [comment]
As far as I can see, it has always used `CustomizableUI`. The only change made by @Deathamns was to allow uBlock to keep working if `CustomizableUI` can't be found.

**Comment by mattatobin** [comment]
If that is true then it was NEVER fully compatible with Pale Moon.. or any Firefox version before 29.

**Comment by gorhill** [comment]
That's what @Deathamns said [above](https://github.com/gorhill/uBlock/issues/590#issuecomment-71304821).

**Comment by mattatobin** [comment]
My suggestion is to NOT allow it to be installed for versions of the browser you do not support.

Thanks for the information though. I do hope you will consider adding a tookit widget in your fallback code because from what I am told everything else is functional.

Peace,

Matt A. Tobin
Pale Moon Add-ons Site Administrator and Team Leader

**Comment by gorhill** [comment]
> I do hope you will consider adding a tookit widget in your fallback code 

I think best would be for a dedicated developer to take care of a specific version for PaleMoon. It's just a matter of copying firefox platform-specific code to a palemoon platform-specific folder. This keeps both version separate, changing code in one version won't put in danger the other version, etc. When it comes to platform-specific code, my opinion is that one dev/one platform is best given that we all do this on our free time.

**Comment by beastielper** [comment]
Just wanted to add that I installed yesterday on Firefox 35.0.1 and have the exact same problem...

**Comment by radry** [comment]
+1 for Pale Moon. Toolbar icon is missing.

**Comment by gorhill** [comment]
Duplicate of #518.
