### ISSUE TITLE
BreakoutList.com site is somewhat broken

### ISSUE THREAD

**Issue by cjbarber** [uBlock-LLC/uBlock#591]
The site is a listing of fast growing startups, and some of the logos on the site: 'pinterest-logo', 'reddit-logo', 'twitter-logo' get blocked by uBlock

**Comment by gorhill** [comment]
Fanboy's Social, EasyList et al. are 3rd-party to uBlock. Please report their maintainers: https://forums.lanik.us/viewforum.php?f=64
