### ISSUE TITLE
Quick "Don't run on this page/domain" button

### ISSUE THREAD

**Issue by alongubkin** [uBlock-LLC/uBlock#594]
AdBlock has quick "Don't run on this page" and "Don't run on this domain" buttons in its menu. It'd be cool if these were added to uBlock as well, because they are much faster than going to Options > Whitelist.

**Comment by Snapy** [comment]
@alongubkin For "Don't run on this page" ctrl + click the big power button.
For "Don't run on this domain" just click the big power button.
Read the [documentation](https://github.com/gorhill/uBlock#documentation) and the [wiki](https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site).

**Comment by gorhill** [comment]
Thanks @Snapy.
