### ISSUE TITLE
[Safari] Turning off uBlock for domain doesn't make the site load properly, disabling uBlock does

### ISSUE THREAD

**Issue by akaralar** [uBlock-LLC/uBlock#595]
I've spotted a website that doesn't load even when uBlock is turned off for that domain, but the site loads properly when uBlock is disabled by going to Preferences -> Extensions and disabling uBlock altogether. I also tried leaving uBlock enabled for that domain but allowing all the connections it tries to establish and that doesn't seem to work either. What is the difference between disabling uBlock completely or disabling it for a domain only?

Here are 2 screenshots that illustrate the behaviour of website with uBlock enabled and disabled:

uBlock enabled or disabled for that domain:
https://dl.dropboxusercontent.com/spa/6d4j003yz96ozkz/ssrpr12v.png

uBlock completely disabled as an extension:
https://dl.dropboxusercontent.com/spa/6d4j003yz96ozkz/0cv78cdb.png

Don't think this is simple drop down menu issue, it makes the site completely unusable as many of the hyperlinks on that page aren't working as well but it's hard to prove with a screenshot :)

the website in question is yemeksepeti.com (istanbul.yemeksepeti.com is the one i'm using) which is the most popular food delivery website in Turkey. 

I'm on OS X 10.10.1 with Safari 8.0.2, uBlock 0.8.6.0

thanks for this great blocker for all who are involved!

**Comment by gorhill** [comment]
@chrisaljoudi Can you please revise the [changes I made](https://github.com/gorhill/uBlock/commit/da7398d5853cbfa1b8e832e8b907aab9aa281e6e) to the Safari-specific code? By coincidence I had questioned in a comment earlier this week that portion of the code.

It looks to me whitelisting has been broken since a while in Safari.

**Comment by chrisaljoudi** [comment]
@gorhill the modifications look fine indeed — whitelisting seems to work in general.

However, I can still reproduce this issue (#595). I'll investigate to see what's going on.

**Comment by chrisaljoudi** [comment]
@gorhill @akaralar PR #596 has the fixes. **Surprisingly,** the problem wasn't with the whitelisting (although that got a bunch of bug fixes, too). It was because of a certain event handler µBlock was attaching to the page.

Anyway, things work better now — the dropdown works fine even without whitelisting the website!

**Comment by akaralar** [comment]
thanks for the quick fixes! although the drop down issue is gone, there were other issues on the page and they are not solved yet. for instance when you click the name of a neighbourhood normally it goes to a new page with restaurants that are serving to that neighbourhood. with ublock enabled the spinner spins constantly. screenshot: https://dl.dropboxusercontent.com/spa/6d4j003yz96ozkz/ggf5nwow.png

it is possible to select the neighbourhood from the drop down and click go, and list the restaurants. however various ui elements in that page were missing which were being loaded from images.yemeksepeti.com. i only encountered this once, and this problem faded away once i included yemeksepeti.com in whitelist. but when you make modifications to onscreen filters such as minimum serving amount, restaurant score etc the same spinner from above is encountered. so whitelisting doesn't solve that issue. screenshot: https://dl.dropboxusercontent.com/spa/6d4j003yz96ozkz/m_w70erd.png

should i open a new issue about this?

i would be happy to share my membership credentials or anything else if it will help you debug the issue, just send me an email.
