### ISSUE TITLE
Preformance: µBlock vs Adblock Edge vs Bluhell Firewall [Firefox]

### ISSUE THREAD

**Issue by LordBadmintonofYorkshire** [uBlock-LLC/uBlock#599]
Does anyone know / can anyone test how µBlock compares to Adblock Edge and Bluhell Firewall in Firefox?

Adblock Edge is a slimmed fork of Adblock Plus that removed 419 kb of unnecessary bloat (http://adstomper.bitbucket.org/Differences_files/Diffs.png). I use ABE on my computer.

Bluhell firewall (49,4 kb) uses "seven hard-coded blocking rules covering about 8400 .com and .net domains" from EasyList. It is more lightweight than ABE, but doesn't block as much as ABE does. I use this add-on for Firefox Mobile since I want a really lightweight ad blocker for my smartphone. Comparing Bluhell Firewall and µBlock is probably a bit like comparing apples and oranges, but I'm still a bit curious how µBlock matches up to it.

By the way, µBlock is compatible with Element Hiding Helper, right?

**Comment by kofalt** [comment]
You may find these links useful, from the docs:

https://github.com/gorhill/uBlock/wiki/%C2%B5Block-and-others:-Blocking-ads,-trackers,-malwares
https://github.com/gorhill/uBlock/tree/master/doc/benchmarks

From other tickets, I believe the maintainer has mentioned that benchmarking every blocker under the sun is a significant time sink, so I bet he'd appreciate some help there.

**Comment by gorhill** [comment]
Anybody can run benchmarks, it doesn't have to be me. I run the ones which interest me, but I don't have the time to run everybody's idea of what should be benchmarked.

Adblock Edge is no different than Adblock Plus, it's essentially a code mirror of ABP, without an "acceptable ads" checkbox.

**Comment by LordBadmintonofYorkshire** [comment]
Ok. I don't know how to properly run benchmarks and I think my computer is a bit too laggy - due to being full of software - to give proper results.

Ah, ok. I should have guessed that since they only removed unnecessary stuff and didn't change the code to optimize the add-on.
