### ISSUE TITLE
Possibility to add new filter list from custom url

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#6]
From the feedback section in the chrome store.

**Comment by ghost** [comment]
Started using this with my own list (to sync my filters across my browsers at home/work) and noticed that there is no automatic update of my list? Even removing it (and hit "Apply") does not appear to clear the internal cache.

**Comment by gorhill** [comment]
Yes, currently hard-coded to update every two days like the other built-in lists. Guess we should open a new issue, as I want to think carefully about the best way to implement this, without affecting in a bad way the older code that was written around the idea that there were no such things as external lists.

**Comment by gorhill** [comment]
@aen0 If you can stand waiting a bit, it will be in the next release:

![to-forum](https://cloud.githubusercontent.com/assets/585534/3712275/a3565036-1507-11e4-976f-33b1f6c64be6.png)

I am just waiting for a bit of translating work to be done so that I can ship that button translated in other languages as much as possible.

**Comment by ghost** [comment]
Thank you.
