### ISSUE TITLE
LinkedIn is unusable with uBlock

### ISSUE THREAD

**Issue by lifyd** [uBlock-LLC/uBlock#600]
I want to be able to take advantage of uBlock's blocking features (essentially off-site of LinkedIn), so I don't really want to add LinkedIn to my exceptions list. 

However, I can't use LinkedIn _at all_ while using uBlock.

Please help, thanks.

**Comment by gorhill** [comment]
I don't understand the issue. LinkedIn seems to work fine for me. Give me a specific URL and tell me what exactly is wrong on the page.

**Comment by Havokdan** [comment]
Linkedin works for me too.

**Comment by skrzepto** [comment]
Works good for me as well.

**Comment by Azunyan-** [comment]
I was able to login and go to different pages without any problems. Could the problem be because of some custom filter?

**Comment by elyrly** [comment]
Works fine for me. Do you have specific <divs> block?

**Comment by chrisaljoudi** [comment]
@lifyd please share steps to reproduce — which should include what lists you have enabled, and custom lists/filters if any.

**Comment by gorhill** [comment]
No reproducible, no feedback.

**Comment by lifyd** [comment]
Unable to reproduce it as well. May have been a client-based bug rather than with the Extension.

Problem solved.
