### ISSUE TITLE
Missing icon in Pale Moon

### ISSUE THREAD

**Issue by LimboSlam** [uBlock-LLC/uBlock#601]
Hey everyone, I'm new here. Um.... well I'm not a dev or have any experience in coding, but I love your extension. So I'm using it on FF and decided to give it a try on PM, but I had some trouble installing it at first, then tried it the next day and it installed, now it's missing the icon. My PM v25.2.0 (x64) and the FF capability UA is Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.2) Gecko/20150112 Firefox/31.9 PaleMoon/25.2.0

**Comment by gorhill** [comment]
Dup of #590.

**Comment by LimboSlam** [comment]
So does this mean you're fixing the issue? Please let me know so I can inform the users of Pale Moon. Thanks  :)
