### ISSUE TITLE
[Chrome] Washington Post Layout Issues

### ISSUE THREAD

**Issue by erigion** [uBlock-LLC/uBlock#602]
Switched from ABP to uBlock recently and noticed there was large blank space at the top of Washington Post blog pages.

http://www.washingtonpost.com/blogs/capital-weather-gang/
http://www.washingtonpost.com/blogs/dc-sports-bog/

Using version 0.8.5.7

**Comment by gorhill** [comment]
Problem is in EasyList, APB also suffers the same problem.

The filter `/ads.css` in EasyList is the problem, it blocks a needed CSS file: http://css.washingtonpost.com/wpost/css/combo?token=20141201130100&inttoken=201410130600&c=true&m=true&context=eidos&r=/2.0.0/external-header-base.css&r=/2.0.0/fonts.css&r=/2.0.0/header.css&r=/2.0.0/footer.css&r=/2.0.0/ads.css

I created an exception filter to bypass the problematic block filter: `@@||css.washingtonpost.com/*/ads.css`

Could you report as well the issue to EasyList maintainers: https://forums.lanik.us/viewforum.php?f=64

**Comment by gorhill** [comment]
CC @ryanbr.
