### ISSUE TITLE
Cannot Change Preferences in Firefox

### ISSUE THREAD

**Issue by jimmybob** [uBlock-LLC/uBlock#603]
Hello,

I'm currently running ElementaryOS Luna (Ubuntu 12.04) with Firefox 35.0 and when I go to the addons and hit preferences for uBlock it says the following:

File not found

Firefox can't find the file at chrome://ublock/content/dashboard.html.

```
Check the file name for capitalization or other typing errors.
Check to see if the file was moved, renamed or deleted.
```

I've tried chaning the URL to µ but it still gives me an error. Any ideas?

**Comment by Deathamns** [comment]
In that case the extension couldn't start at all. Check the Browser Console (Ctrl+Shift+J) when enabling or installing the extension. JavaScript (JS) errors are the relevant ones.

**Comment by jimmybob** [comment]
Hi, I was able to get the dashboard to come up. Seems like it's working now, but here is the some of the errors that came up:

window.controllers is deprecated. Do not use it for UA detection. https-everywhere.js:326

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
