### ISSUE TITLE
uBlock breaks this forum

### ISSUE THREAD

**Issue by the-trooper0000** [uBlock-LLC/uBlock#607]
Page is http://forum.pcekspert.com/
This is how it's supposed to look:
http://i.imgur.com/aFJDOWP.jpg

And this is how it looks with uBlock enabled:
http://i.imgur.com/yq8HWUr.jpg

As you can see it looks like uBlock is blocking all of the images, not just adds, so navigating the page becomes impossible (that little new post arrow for example).

**Comment by Snapy** [comment]
@the-trooper0000 It's because of this filter `||pcekspert.com^`.
It's present in Peter Lowe's Ad server list so report the bug on his website.
Meanwhile whitelist the website or use dynamic filtering.

**Comment by pgl** [comment]
I've removed the domain from the list. Thanks for the note about the false positive, @the-trooper0000.

**Comment by gorhill** [comment]
@pgl Is it really a false positive? Usually I prefer to provide a fix which allows 1st-party requests but still block all other requests, i.e. `@@||pcekspert.com^$~third-party` in the current case. This fixes the site while blocking `pcekspert.com` as a 3rd-party.

**Comment by pgl** [comment]
@gorhill Yes, it's definitely a false positive - pcekspert.com isn't an ad server, so shouldn't be on my list. (Also, I don't have support for custom options in AdBlock format.)
