### ISSUE TITLE
uBlock breaks r7.com

### ISSUE THREAD

**Issue by ialexsilva** [uBlock-LLC/uBlock#609]
uBlock breaks the site "http://r7.com" completely, the site is in a loading loop and the links are not clickable...
uBlock Version: 0.8.5.7 with default list loaded...
Chrome Version: 40.0.2214.91 m (64-bit)

**Comment by gorhill** [comment]
EasyList issue.

Custom filter `||assets.r7.com/assets/schumi_core/base/application-*.js` seems to fix it. Can't tell if this breaks something useful, I don't know the site enough.

You may want to report the fix to EasyList maintainers: https://forums.lanik.us/viewforum.php?f=62
