### ISSUE TITLE
Suggestion: Don't forget to always push for latest version in Opera Web Store

### ISSUE THREAD

**Issue by tailHey** [uBlock-LLC/uBlock#61]
The title speaks for itself (and it's about HTTPSB as well). I know Opera staff can take some time to review an addon, but µBlock is still at 0.1.4.2, whereas the 0.1.2.0 version have just been released :S (HTTPSB is also late :/)

**Comment by gorhill** [comment]
I did it today with version 0.2.0.0. I don't mind the review, it is also an advantage for users, it's that it's time consuming on my side, I have to use a virtual machine to run Windows, copy files across the VM and host, etc. I find it discouraging to have to go through all these steps.

**Comment by tailHey** [comment]
The thing is, people (using Opera browsers) would love to have automatic updates for both HTTPSB and µBlock, but because of this, they become quickly obsolete in Opera Web Store...
Either you'd find a way to reduce the time needed for the review, or you'd code an automatic update feature (in this case, the first manual installation would be the last one).
I'm not talking about this to bother, I'm just thinking about inexperienced Opera users which would like to benefit from latest versions of both HTTPSB and µBlock without having to do it manually

**Comment by kikaxa** [comment]
FFS why would you use windows for this?
They have linux version for several month now, both bleeding edge(get from desktop blog), or on the main site for slowpokes.

Also self-updating addons are against the rules of opera.

**Comment by gorhill** [comment]
> FFS why would you use windows for this?

Well I need to test at least _once_ on Windows, so I take the opportunity to do it on Opera (and Yandex sometimes). It's not too bad with some scripts. I uploaded a new version to Opera store now, so people have to wait anyways because they do not review during the week-end.

**Comment by kikaxa** [comment]
Yep. But i naively though that javascript is crossplatform :), and opera guys check this for you anyway.

**Comment by gorhill** [comment]
I did have an issue on Windows once. There was the filename of a 3rd-party asset which wasn't working on Windows. These things happen, best it to double check it works all fine as expected.

**Comment by gorhill** [comment]
Ok I wont.

I want to keep the pile of issues as clean as possible (limited time, etc.)

**Comment by tailHey** [comment]
@gorhill : "Ok I wont"

Does that mean you won't update the Opera Store version anymore?

**Comment by gorhill** [comment]
O f course not, I mean I won't forget.
