### ISSUE TITLE
Does uBlock aim to supersede Ghostery?

### ISSUE THREAD

**Issue by reverofevil** [uBlock-LLC/uBlock#611]
Could you clarify on the front page on the following issues, please?
- The `uBlock` is able (or will be able) to block unwanted scripts as `Ghostery` does, isn't it?
- What kind of interception API does it use? `webRequest`?

**Comment by gorhill** [comment]
From [manifesto](https://github.com/gorhill/uBlock/blob/master/MANIFESTO.md):

> µBlock's sole purpose is to give users the means to enforce their own choices

So if a user uses a filter list of "unwanted scripts" or crafts his/her own filters for "unwanted scripts", uBlock will respect these filters.

> What kind of interception API does it use? webRequest?

The code is open, anybody interested in these technical details can find out easily, no need to clutter the front page with that level of technical details. It's browser dependent anyways.
