### ISSUE TITLE
bmnvhmjhkjhgk

### ISSUE THREAD

**Issue by limanseba** [uBlock-LLC/uBlock#612]

**Comment by Xylemon** [comment]
I see this as a very important issue, this needs to be top priority.

**Comment by DomT4** [comment]
[![Huh](https://2.bp.blogspot.com/-PrBQ6Bh2phg/T4hupUtYn2I/AAAAAAAAADI/_70J5XphPoY/s1600/ConfusedDog.jpg) ](https://2.bp.blogspot.com/-PrBQ6Bh2phg/T4hupUtYn2I/AAAAAAAAADI/_70J5XphPoY/s1600/ConfusedDog.jpg)
