### ISSUE TITLE
[Safari] Infinite Spinning Beachball on adding a 3rd party filter

### ISSUE THREAD

**Issue by heyjared** [uBlock-LLC/uBlock#613]
Safari Version 8.0.3 (10600.3.14) on Yosemite 10.10.2
Repro:
1. Open preferences, 3rd-party filters
2. Scroll to the bottom text box, add "https://www.shopback.sg/assets/adblock/whitelist-shopping.txt"
3. Click Apply Changes
4. Screen frozen indefinitely.

EDIT: seems to be caused by same problem as #527

**Comment by gorhill** [comment]
I can confirm it worked fine on Firefox, Chromium.

However, no filter where used, because all the filters on this list come with the `document` option, which is [not supported by uBlock](https://github.com/gorhill/uBlock/wiki/What-%C2%B5Block-can-and-can-not-%28currently%29-do#%C2%B5block-has-all-the-features-abp-has).

**Comment by chrisaljoudi** [comment]
@jaaaaared @gorhill hmm, haven't been able to reproduce yet (Safari Version 8.0.3 (10600.3.18) on Yosemite 10.10.2).

Have you been able to consistently reproduce it, @jaaaaared? It'd be great if you can share a more detailed list of steps (how you open the preferences window, for instance).

Not to say this isn't an issue, but to confirm what @gorhill said: none of the filters from that list will be used.

**Comment by heyjared** [comment]
I've reinstalled uBlock from the Safari Extensions gallery. I'm not sure what difference it made, since I think it was the same version of uBlock, but now the lists update successfully. Now, unable to reproduce the bug.

But as you say, `document` is not supported so I still can't use the whitelist.

**Comment by chrisaljoudi** [comment]
@jaaaaared interesting. Did you happen to upgrade Safari to the latest beta? (I notice that the version you reported initially was one seed behind the latest).

**Comment by heyjared** [comment]
@chrisaljoudi Well currently I am on Version 8.0.3 (10600.3.18), but that happened only today. It works fine currently.

**Comment by chrisaljoudi** [comment]
Closing this and #527 — new stable Safari is out as of today (along with public release of 10.10.2). We'll see if people experience the issue at this point.
