### ISSUE TITLE
[Safari] uBlock 0.8.6.0 Breaks Other Extension - ClickToPlugin

### ISSUE THREAD

**Issue by d4v1dv00** [uBlock-LLC/uBlock#615]
The latest version breaks ClickToPlugin, prior that both works perfectly together.

**Comment by chrisaljoudi** [comment]
@d4v1dv00 which behavior of ClickToPlugin is broken? A test case would be great to get the problem solved.

**Comment by chrisaljoudi** [comment]
Ah, the issue is on YouTube. PR #619 fixes this.
