### ISSUE TITLE
[Firefox] Support Firefox Sync

### ISSUE THREAD

**Issue by TobiX** [uBlock-LLC/uBlock#617]
It would be really nice if µBlock would sync its settings (filter subscriptions, custom filters, exceptions, etc.) via Firefox Sync.

(See http://stackoverflow.com/questions/23482565/how-do-you-sync-firefox-addon-extension-preferences for how to get this to work)

**Comment by Mosrite** [comment]
+1

**Comment by brwolfgang** [comment]
Couldn't find any non-obsolete documentation about how to do it. But surely it's a great idea

**Comment by kofalt** [comment]
I was going to ask about this feature specifically for custom filters I create.

Despite the obnoxious warning on [these docs](https://developer.mozilla.org/en-US/docs/Archive/Mozilla/Firefox_Sync/Syncing_custom_preferences), I am 90% sure this works:

> for each `services.sync.prefs.sync.<pref>` preference

So I'm pretty sure all the addon has to do is add `services.sync.prefs.sync.<pref>: true` values.
This seems to agree with @TobiX's link.

**Comment by deaffob** [comment]
It would be really nice for the sync to work with Chrome Sync also... :smile:

**Comment by 1n5aN1aC** [comment]
+1

**Comment by ivysrono** [comment]
+1

**Comment by mikhoul** [comment]
- 1000000000000000000000   ;-)

**Comment by desbma** [comment]
As a workaround, for Firefox on Linux, you can copy uBlock configuration file for example to a Dropbox folder, and then create a symlink to it on the different machines that will share the configuration.
Ie. with:

```
mv -v {~/.mozilla/firefox/PROFILE_NAME/extension-data/,~/Dropbox/}ublock.sqlite
ln -sv {~/Dropbox/,~/.mozilla/firefox/PROFILE_NAME/extension-data/}ublock.sqlite
```

**Comment by ryanbuening** [comment]
+1 For Chrome sync as well.

**Comment by iAHTOH** [comment]
+1 Firefox and Chromium

**Comment by hackel** [comment]
Now that µBlock supports Firefox Mobile, this has become 10x more important.  Especially since rules are a bit more cumbersome to create on mobile, this would be an ideal solution.

**Comment by martinrotter** [comment]
+1 for Firefox.
Must have feature.

**Comment by stevereinhardt** [comment]
+1 for Firefox. Would be amazing. I'm having to export and constantly overwrite each instance with the updated whitelists.

**Comment by desbma** [comment]
FYI, [uBlock Origin](https://github.com/gorhill/uBlock) supports this.

**Comment by Gitoffthelawn** [comment]
@desbma Does Origin use the native Firefox Sync, or some other method?

**Comment by desbma** [comment]
Yes [it uses](https://github.com/gorhill/uBlock/issues/80) Firefox Sync.

That's the reason I made the switch to uBlock Origin.
I was  a bit annoyed by all the drama after the fork, and honestly I think @gorhill acted as if he wanted fuel the flame war, so I purposly stayed with uBlock from this repo.

But as of of now, on a technical ground, uBlock seems abandonned, and uBlock Origin has more features, is available and updated on [addons.mozilla.org](https://addons.mozilla.org/) (which means automatic updates), is lighter when you first install it, is [meticulously optimised for performance](https://github.com/gorhill/uBlock/issues/672), etc. 

So the choice is quite easy :)

**Comment by hackel** [comment]
uBlock origin only supports a manual sync process.  Changes are not synced in real-time across all machines.  It's a great start, but still not ideal.

**Comment by justinlosh** [comment]
+1

**Comment by TobiX** [comment]
Closing, since uBlock Origin supports this.
