### ISSUE TITLE
Shortcut keybind to the Element Picker would be handy [was "Thank you"]

### ISSUE THREAD

**Issue by alabrand** [uBlock-LLC/uBlock#62]
Thank you for the latest update. The Element Hider works fantastically well, even more so than the Adblock Plus counterpart. I mean... It's just so insanely blazingly fast! I often found myself seeing the elements before they were hidden on Adblock Plus, as if they were being removed really, really slow. But here? I never see them again, even with several hundres of them applied on one site.

Edit: Oh, and a shortcut keybind to the Element Picker would be handy. Saves me the trouble of not having to have the icon visible.

**Comment by gorhill** [comment]
You're welcomed. The trick for the element hider to work well is to use cosmetic filters which are specific to a web site. This way the CSS styles can be injected before the page has been displayed in the browser. The element picker enforces this.

I changed the title of the entry here as an issue to track the keyboard shortcut for the element picker. I am not sure though the shortcut can work when the extension icon is not visible. If not, workaround would be a menu entry in the context menu.

**Comment by gorhill** [comment]
Dup of #256 (I will keep #256 opened because the main issue was not about the shortcut)

**Comment by Spartacode** [comment]
So is there a hotkey menu? or a keyboard shortcut? I thought i seen a page somewhere but cant find it again to save my life. please tell me i am wrong or right. Thanks
