### ISSUE TITLE
Consider moving some code used by µBlock.URI to platform-specific side

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#620]
Firefox has utilities to parse URL and extract effective domain names using the public suffix list.

Not sure but I am assuming this is faster than the current JS-based solution. So if we move that code to `vAPI`, Firefox would gain something while the other platforms (Chromium/Safari) would just still rely on the current solution.

But first I would like to find out whether there is a clear gain in using [nsIEffectiveTLDService.getBaseDomainFromHost](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIEffectiveTLDService#getBaseDomainFromHost%28%29) over [publicsuffixlist.js](https://github.com/gorhill/publicsuffixlist.js).

**Comment by chrisaljoudi** [comment]
It's unclear whether `nsIEffectiveTLDService` is supported/works at all in Firefox (I get a deprecation warning when trying code [from the documentation you linked](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIEffectiveTLDService#getBaseDomainFromHost%28%29)) — followed by an error.

**Comment by gorhill** [comment]
Well I ran some quick benchmark and that made no difference. Closing.
