### ISSUE TITLE
Do not block tracking sites by default

### ISSUE THREAD

**Issue by andras-tim** [uBlock-LLC/uBlock#625]
I think, the tracking sites works for users and not against! It collects data about browser, resolution, enter and exit pints, etc., what will be a huge point for future plans of developers! This can be a base for user get a more useful page, service!

In other hand, Google Analytics and others was made well, can not block page loading (lazy loading), minimized memory consumption, CPU usage, ...

I think, what user know, what are they (because he is a "privacy solder"), he/she can turn on this function.
I can imagine this like welcome wizard of AdBlock Plus.

**Comment by gorhill** [comment]
> tracking sites works for users and not against

**Comment by andras-tim** [comment]
Sorry, the original title was confused.

**Comment by gorhill** [comment]
I understood what you meant. I just disagree. This has been brought [before](https://github.com/gorhill/uBlock/issues/564), I am not going to debate this every single time there is such a request.
