### ISSUE TITLE
[Chromium] CSS calc() in old version 33-

### ISSUE THREAD

**Issue by 7nolans** [uBlock-LLC/uBlock#627]
chromium 26+ support css calc(), vh and em, but not together.
chromium 34+ work fine.
![chrome33error](https://cloud.githubusercontent.com/assets/10723201/5941256/70622008-a718-11e4-8143-2b98232c1978.png)

**Comment by gorhill** [comment]
You are still using Chromium 26?

**Comment by 7nolans** [comment]
No, but many people used Chromium 31-32, because there no problem with NPAPI, DIRECT-WRITE, encrypted user settings, if used portable version from usb.
