### ISSUE TITLE
[Chromium] Chrome pinned tabs

### ISSUE THREAD

**Issue by lliotte** [uBlock-LLC/uBlock#628]
Ad blocking doesn't work on pinned tabs when browser starts. I need to unpin them, refresh (so ads get blocked) than pin again. After browser restart I must do that all over again.

**Comment by gorhill** [comment]
What version of uBlock?

**Comment by lliotte** [comment]
µBlock v0.8.5.7 from Chrome Web Store
Google Chorme Version 40.0.2214.93 m

**Comment by gorhill** [comment]
Ok, so it's certainly dup of #587, fixed in 0.8.6.0.
