### ISSUE TITLE
[Firefox] Forcing fonts in browser eliminates rendering of main toggle in toolbar

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#629]
To recreate: Go to Preferences>Content>Advanced>Allow pages to choose their own fonts>Uncheck>Press Ok

Firefox 35.01; Linux Mint Mate 17.1 64 bit

**Comment by chrisaljoudi** [comment]
Not a bug — the icon is from [Font Awesome](http://fortawesome.github.io/Font-Awesome/), and you're disabling the ability to use that.

The alternative would be to use an image, arguably worse at some level.

**Comment by chrisaljoudi** [comment]
@gorhill what do you think? Doesn't seem like it's worth it to move to a PNG/SVG.

**Comment by gorhill** [comment]
I wish all icons were standalone SVGs as this would remove the need to ship with the whole Fontawesome, but I am not an artist. If one would step forward to contribute SVG-based icons that would be great.

**Comment by chrisaljoudi** [comment]
@gorhill I'd be happy to. I'll have to browse through to make sure I catch all the places where FontAwesome is used.

Will have something by the end of today.

**Comment by ghost** [comment]
> but I am not an artist

@gorhill Efficient code can be construed as artistic

> Will have something by the end of today.

@chrisaljoudi 

Right on. Was hoping for something with a dinosaur theme. Maybe a volcano as well. But seriously, thanks guys for looking into it.

**Comment by ferongr** [comment]
How about using the equivalent SVG files from https://github.com/encharm/Font-Awesome-SVG-PNG instead?

**Comment by gorhill** [comment]
@chrisaljoudi I would like any changes to go in a separate branch, as I would like to decide whether I agree with the changes before committing them to master.

**Comment by chrisaljoudi** [comment]
@gorhill sure. For just this modification, or just everything from this point on?

**Comment by gorhill** [comment]
Just this, I just want to be sure I like it -- sorry f that sounds rude. I liked the Fontawesome ones (except for the fact this causes dependencies on Fontawesome), except for the big power button, which I thought was too confusing ("power on/off"). I tried to craft an alternative once but I didn't like it and ended up scrapping it. Aside the confusing look, I thought it didn't fill the space well, because circle.

**Comment by chrisaljoudi** [comment]
Okay.

Disabling fonts on Firefox breaks everything that uses font icons. [This is an active bug on Mozilla's tracker and has been 'Assigned'](https://bugzilla.mozilla.org/show_bug.cgi?id=789788). This is why I'm marking the issue as a browser bug (I personally don't think it's a bug, just an unfortunate limitation, but whatever the Mozilla community thinks is fine).

Individual image files are somewhat of a pain to manage, and are certainly way more of a pain to embed and use.

As far as having to load all of FontAwesome goes, I've been working on a solution that bundles exactly just the icons that are needed. I'll push this soon if there aren't any issues. Meanwhile, there certainly haven't been any efficiency issues brought up about the icons

**Comment by gorhill** [comment]
By the way, I recant my previous "except for the big power button": I like it now, I think the change in color made the difference.
