### ISSUE TITLE
Adfly

### ISSUE THREAD

**Issue by ialexsilva** [uBlock-LLC/uBlock#63]
Currently the ublock is blocking all elements of the site http://adf.ly/
It would be nice block only part of advertising on the site...
![capturar](https://cloud.githubusercontent.com/assets/6363160/3574760/71820364-0b81-11e4-99c7-eed99bdcf4f1.PNG)

**Comment by gorhill** [comment]
I see that _Peter Lowe's Ad server list_ causes everything from `adf.ly` to be blocked.

This exception rule appears to work: `@@||adf.ly$~third-party`.

Edit: I wouldn't want to add this rule for everybody, I rather let people choose whether they want to allow anything from this site.

**Comment by ialexsilva** [comment]
the code works thanks...

**Comment by gorhill** [comment]
Actually, I will add this rule, it unbreaks the site if you visit it, without allowing `adf.ly` as 3rd-party anywhere else.
