### ISSUE TITLE
yBlock makes toolbar double height on Firefox 35.0.1 on OS X 10.9.5 

### ISSUE THREAD

**Issue by JMoVS** [uBlock-LLC/uBlock#631]
The problem  with yBlock for me is that it makes the toolbar have double height compared to standard way:

![bildschirmfoto 2015-01-28 um 20 23 14](https://cloud.githubusercontent.com/assets/7354506/5944972/8c81c956-a72b-11e4-8b8f-0b7e2c407ff5.png)
![bildschirmfoto 2015-01-28 um 20 23 34](https://cloud.githubusercontent.com/assets/7354506/5944974/8e3ed036-a72b-11e4-941b-e40152821248.png)

**Comment by gorhill** [comment]
Fixed in [0.8.9.1](https://github.com/gorhill/uBlock/releases/tag/0.8.9.1).
