### ISSUE TITLE
ads on google

### ISSUE THREAD

**Issue by atomGit** [uBlock-LLC/uBlock#635]
uB 0.8.6.0
FF 35

tried several filter sets including the ones i used with ABE and still seeing ads on google all the time - has something to do with AB element rules not being understood by uB i suspect

also, if i use the uB element picker to block the ad containers (below), they are hidden only until the next search

`www.google.com###rhs_block.r-rhscol-10.rhstc5
www.google.com###t402-prompt-iframe`

gorhill - i saw a comment you made about this a day ago where you apparently had element blocking disabled without knowing it -- i see no option to disable it, other than the "Parse and enforce cosmetic filters." option, which is enabled in my case

if i use the generic easylist, some ads are blocked, while others are not

UPDATE: just did some more messing around with the filter subscriptions and now the ads are not appearing -- not sure what to think, but i'm wondering if another filter set is killing the easylist rules??? it seems like the ones i'm picking absolutely should not be (my focus is on ads, malware and privacy, US-EN only) -- also seems like dumping the entire cache and re-loading the filters may have cured the problem

**Comment by gorhill** [comment]
If you create cosmetic filters which are illegal CSS rules, uBlock may become unable to have a working cosmetic filtering engine: garbage in garbage out. That's the only explanation I see to explain what you describes.

Example, enter `google.*###foo < bar` (invalid CSS rule) in your custom filter, and ads will now be showing in Google search results.

Users who create custom filters are expected to know how to craft filters.
