### ISSUE TITLE
apam404 filters not working?

### ISSUE THREAD

**Issue by atomGit** [uBlock-LLC/uBlock#636]
i loaded the spam404 filters and none of the sites i tested are blocked - also tested with only the spam404 filter-set and no others

i'm not sure what exactly is supposed to occur, but i would think they shouldn't be loading

example: `validcheats.com`  is on their block-list, but the site loads, albeit without the css

**Comment by chrisaljoudi** [comment]
I believe µBlock doesn't block explicit navigation requests. If you type `validcheats.com`, µBlock will let you go there — but it will block any _resources_ coming from `validcheats.com`. 

However, if some other site tries to open a popup with `validcheats.com` (or a script/image/iframe/whatever from there), µBlock will prevent that.

**Comment by gorhill** [comment]
@atomGit As per Adblock Plus filtering semantic, the main document must never be blocked:

> "Site blocking" was a feature in Adblock 0.5 that allowed filters to be applied to web pages as a whole and prevent you from navigating to a page that matched some filter on your list. The main reason why this function wasn't kept in Adblock Plus 0.6 is: preventing you from seeing a page you explicitly requested doesn't have much to do with ad blocking.

<sup>Source: [Adblock Plus: FAQ - Advanced functionality (Dec 6, 2011)](https://web.archive.org/web/20111206122411/https://adblockplus.org/en/faq_features#siteblock)</sup>

Theoritically, the `$document` filter option should allow full page blocking, but as per ABP this option never applies to blocking filter, just exception filter -- and anyway it's not used by Spam404.
