### ISSUE TITLE
[Safari] µBlock breaks when toolbar icon is hidden

### ISSUE THREAD

**Issue by henkthefreeze** [uBlock-LLC/uBlock#639]
When I remove the icon from the Safari toolbar and restart the browser, µBlock fails to load and appears broken. When I restore the icon to the toolbar and restart everything works again. 

Interesting little bug or is this intended behaviour? I would expect it to work even when the icon is not visible (based on experience with other add-ons).

Even so, thanks for a great add-on!

**Comment by OMCS** [comment]
I can confirm this behaviour occurs on Safari 8.0.3 (OS X 10.10.2 if that's relevant). I'm not sure if it is by design or not but I'd really appreciate the option to hide the toolbar icon.

**Comment by gorhill** [comment]
> I'm not sure if it is by design

No, not by design. uBlock still blocks fine when I remove the button with Chromium.

**Comment by fletom** [comment]
+1

I hid the icon because the red block count stands out way too much, then uBlock stopped working altogether. Even clicking the preferences checkbox didn't bring anything up.

**Comment by chrisaljoudi** [comment]
@OMCS @jochemkeller ack. I'm working on some major-ish changes, and this is coming up on my list directly afterwards. 

@fletom sorry about that — but FYI, you can disable the badge block count from  μBlock's preferences without having to remove the icon.

**Comment by henkthefreeze** [comment]
@OMCS thanks for mentioning OS X 10.10.2 and Safari 8.0.3. I have exactly the same versions and forgot to include!

@gorhill sounds like a bug then? I think it has to do with Safari 8.0.3

@fletom you can disable that right here:
![screen shot 2015-01-31 at 20 57 39](https://cloud.githubusercontent.com/assets/1217959/5989544/eae466f4-a98b-11e4-8ec5-5e5093cd5850.png)

@chrisaljoudi thanks so much! :+1:

**Comment by chrisaljoudi** [comment]
@jochemkeller it is indeed a bug and I think I have a good idea of where the problem is (**not** core  μBlock). 

If I weren't on my iPhone, I'd push the fix within a few minutes. :)

**Comment by fletom** [comment]
@chrisaljoudi and @jochemkeller Thanks for the tip!

**Comment by chrisaljoudi** [comment]
Fixed with 30f1c9ebaf56fda68636a369de7af3c3a5eb4399.

**Comment by henkthefreeze** [comment]
Thanks so much! Eagerly awaiting the release 😃👍
