### ISSUE TITLE
Move vertical scrollbar to right side of drop down.

### ISSUE THREAD

**Issue by vonHabsi** [uBlock-LLC/uBlock#640]
Whenever you change one of the settings and you refresh the page, you need to move the mouse over to the left side to scroll down the lsit of domains to see which new ones have appeared or need adjustment.

It is rather awkward and it would be better for the scroll bar to be on the right of the refresh button, or immediately to the left, ie to the right of the domains list.

**Comment by gorhill** [comment]
I disagree.

I did not designed it this way as an afterthought, the opposite. I'm expecting by now most people have a mouse wheel, which mitigates the need to use the scroll bar.

I just can't stand seeing the scroll smack in the middle of the UI, as the scrollbar itself is not key information, and having an area with low intrinsic information value in the middle is definitely not a good thing IMO.

**Comment by gorhill** [comment]
Also for the record, when the scroll bar was placed on the right, it would cover partly the right-most cells. Currently it does the same to the left-most cells, but given the purpose of the left-most cells, it's not crippling like it would be if it were the right-most cells.
