### ISSUE TITLE
No "statistics tab" on Firefox

### ISSUE THREAD

**Issue by anewuser** [uBlock-LLC/uBlock#642]
[This issue](https://github.com/gorhill/uBlock/issues/12) mentions a certain "statistics tab", which one can use to see each individual filter that has been applied to a page. However, I don't see any stats anywhere on the latest test version of uBlock (0.8.6.0-rc.1) for Firefox. 

I wasn't able to find more info about it. Is this tab still being implemented on the Firefox version of uBlock? I've already checked the "I am an advanced user" box.

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/releases/tag/0.8.5.0

> New network request logger

**Comment by anewuser** [comment]
I'm sorry for being slow today, but how to launch it?

**Comment by anewuser** [comment]
I've finally realized that the eye icon opens it. Please consider making it clearer or adding a text link ("view log") to the dashboard, so other people can find it by themselves.

**Comment by gorhill** [comment]
There is a tool-tip for that icon: "Go to request log".

**Comment by anewuser** [comment]
Firefox 36 sometimes shows the raw URL of the dashboard in the "floating status bar" when I hover it, but I don't get any tooltip.

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Advanced-user-features ?
