### ISSUE TITLE
Whitelisting Google Analytics

### ISSUE THREAD

**Issue by jpillora** [uBlock-LLC/uBlock#644]
I'd like to allow GA on http://jpillora.com/xdomain/. As to be expected, uBlock stops `http://www.google-analytics.com/analytics.js` loading by default. I'd like to allow all requests to `www.google-analytics.com`. Adding `www.google-analytics.com` to the Whitelist section in Options seems to have no effect as this list only refers to 1st party domains, not 3rd party domains.

**Comment by Betsy25** [comment]
While on that site, check the "allow" checkbox for this site (greening the second zone in the advanced popup) works as expected for me.
I checked it by using Fiddler as a proxy, when you check allow next to the entry, and reload, it's being requested here.

Or do you really want to allow it globally ?

**Comment by jpillora** [comment]
Globally, it'd just like to allow GA across all sites.

**Comment by Betsy25** [comment]
Confirmed. Allow Globally doesn't work for "google-analytics.com"

Edit: Weird, on second try it did work.
@jpillora do you have "\* google-analytics.com \* allow" in your "My rules" list ?

**Comment by ghost** [comment]
Allow it with [Dynamic Filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide)

**Comment by jpillora** [comment]
Ah awesome, I'll give that a shot

**Comment by Betsy25** [comment]
I think it might be much more usable for new users to make "advanced features" the default.
Only thing that might make it more clear is some "Globally" and "On This Site"' kinda column headers.

**Comment by gorhill** [comment]
@jpillora `@@||google-analytics.com^` in _"My filters"_ should work.

@Betsy25 @tlu1024 Dynamic filtering is for advanced users, it should not be suggested as a solution.

**Comment by jpillora** [comment]
Thanks @gorhill, that worked, and thanks for the awesome extension.

**Comment by ghost** [comment]
@gorhill 

> Dynamic filtering is for advanced users, it should not be suggested as a solution.

Yes, I generally agree. On the other hand, I think Dynamic Filtering is probably easier to grasp for an unexperienced user than fiddling around with filter syntax.
