### ISSUE TITLE
Support `font`, `media` filter options

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#649]
Just found out instances of such in:

EasyList:

```
||oboom.com/assets/raw/$media,domain=oboom.com
@@||turner.com/adultswim/big/promos/$media,domain=video.adultswim.com
```

Fanboy's Social:

```
/social-icon-$~font
```

**Comment by lewisje** [comment]
To my understanding, ABP supports all of the filter options that nsIContentPolicy does, because it was originally a Firefox extension; however, I also know that webRequest is not that fine-grained, and ABP has re-mapped those options as well as it can for the Chrome extension.

**Comment by gorhill** [comment]
There is [remapping too in uBlock](https://github.com/gorhill/uBlock/blob/master/platform/chromium/vapi-background.js#L393) (I remember you looking at it). Now I just need test cases where these request types occur in order to validate that whatever fix works fine. The fix is trivial but I still need to be able to test with real world cases. I wasn't able to get `media` from `video.adultswim.com` -- which would be `other` in Chromium. I want to find out if I can rely on the extension part to transpose `other` into `media`.

**Comment by ghost** [comment]
@gorhill 

Were you considering adding this list?

https://www.fanboy.co.nz/fanboy-antifonts.txt

**Comment by gorhill** [comment]
@kintpuash No, I didn't know that list existed. I doubt this would be a popular filter list, I don't plan to include it.

One thing I have meant to do since long now is to create a wiki page to collate all the interesting filter lists a user _could_ want to use, and this one would go there. Anybody can go ahead and create that wiki page, so there would be one central repository for where to find all the lists of interest to more than just a handful of people.

This is how actually I plan to solve #224: only the filter lists on that wiki page will have the ability to be added to uBlock through a click on a list.

**Comment by ghost** [comment]
Those sound like great ideas. Somewhere in the bowels of discussion was someone using roughly 900,000 filters? He happen to mention where he got the extra lists?

**Comment by gorhill** [comment]
@kintpuash 

You can try http://hosts-file.net/?s=Download, the first file, `hosts.zip` has over 840,000 entries.

Disclaimer: I never tried to use a list with such a number of entries.
