### ISSUE TITLE
Mind the referrer in popup blocker heuristic

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#65]
Right-clicking and opening in a new tab this link:

http://adf.ly/

Should work. However, the newly released popup blocker sees the new tab as an unwanted popup and clobbers it.

The popup blocker heuristic is too strict. It needs more data to make a better decision about whether a new tab is an unwanted popup or not.

**Comment by gorhill** [comment]
Link in issue #58 used to test whether popup blocker still work.

**Comment by harshanvn** [comment]
yes, pop-up blocker still works after this heuristic fix..
One thing i observed after #58 fix, is that a new tab opens up briefly and then gets closed. Is this an expected behavior? Not sure how ABP+ works in this scenario. I have to install it and see.

Thanks for implementing this feature. Much appreciated. This would removed few annoyances i face from time to time, by visting above type sites.

Also, its time to update the wiki, that pop-up blocker works now ;)

Thanks!!

**Comment by gorhill** [comment]
> Not sure how ABP+ works in this scenario

Yes, ABP has same behavior. Problem is that there is no way to synchronously block a popup in Chromium.

However, even though uBlock and ABP exhibit the same behavior (blinking of tab or window), they block the popup differently internally. uBlock does it so that the content of the popup will **not** generate any net request.

From what I've seen of ABP's code, the popup quite probably has time to make a net request for the main document in the popup. So there is a bit of a privacy issue there.

I just hope that the way I did it will hold, as it's neet privacy-wise to prevent completely any net request by the popup.

**Comment by harshanvn** [comment]
thanks. Good to see that uBlock does not generate any net request on the blocked window/pop-up. This is what i was looking in the statistics tab before to see if anything is logged on that.

I don't mind if the pop-up appears briefly, as it blocks all the net requests originating from it.

**Comment by harshanvn** [comment]
hi gorhill, In the below site (flashx.tv), 2 out of 3 pop-ups are blocked. 3rd pop-up (when you click on close button-image on the flash frame), the resultant pop-up is not blocked..

http://flashx.tv/video/DBZL907WMFQ84C1/thelisteners05e07hdtvxvid-fumavi

For reference, ABP+ blocks this pop-up..

Let me know if you want me to create a new bug.

Also, the element picker does not identify any frames (divs) on the flash player. Is this expected?

**Comment by gorhill** [comment]
Found the problem, but we should open a new bug for new sites where it's not working.
