### ISSUE TITLE
[EasyPrivacy] not possible to sign-up

### ISSUE THREAD

**Issue by muhasturk** [uBlock-LLC/uBlock#652]
Try to sign-up https://www.getcloudapp.com/. ublock prevent it.

**Comment by gorhill** [comment]
_EasyPrivacy_ blocks `mxpnl.com` and `segment.io`, both apparently needed by the site. Report the issue to _EasyPrivacy_ maintainers: https://forums.lanik.us/viewforum.php?f=64
