### ISSUE TITLE
Firefox 35.0 - Youtube videos do not load

### ISSUE THREAD

**Issue by phoenix87ta** [uBlock-LLC/uBlock#653]
With latest ublock enabled in Firefox 35.0 on Xubuntu 14.04 64-bit, youtube videos do not load.  The video player appears and plays the loading animation, but the video never loads.  Disabling the plugin for youtube makes videos work again.

Any further information I can provide?

**Comment by gorhill** [comment]
Are you using [freshplayerplugin](https://github.com/i-rinat/freshplayerplugin)?

**Comment by phoenix87ta** [comment]
Sure am.

**Comment by gorhill** [comment]
Dup of #578.

I think you guys should also report the issue to freshplayer developer. uBlock just care about network requests, so that it doesn't work with freshplayer I can't make sense of this, unless freshplayer is causing different network requests from being made.

**Comment by phoenix87ta** [comment]
Switched to HTML5 player.  Works like a charm.  Thanks.
