### ISSUE TITLE
Feature: Make users be able to file a report about a site/ad/suggestion etc.

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#657]
I think it may be beneficial for you to open some random email, and just send there user reports about not blocked ads/broken sites or suggestion (make it possible for user to classify the intent of the report so you will be able to arrange it in your mail box).

This way, the users won't be frustrated on the first time they encounter a broken site, and maybe will be even happy to report it.

For novice users, who don't know about Github, or even heard of, it's super beneficial - for you, to see what people are reporting about, and for the users for reporting the issues they encounter of course.
People who do know Github existence, will continue to report here, so everyone is happy.

I think this can work if implemented correctly and intuitively for users to report easily (maybe via a little flag in the extension popup? for example: https://fortawesome.github.io/Font-Awesome/icon/flag/ ).

**Comment by gorhill** [comment]
No time for this. It's a hobby, not a job.
