### ISSUE TITLE
Add acceptable ads

### ISSUE THREAD

**Issue by mikhaelkh** [uBlock-LLC/uBlock#66]
Add [acceptable ads](https://adblockplus.org/en/acceptable-ads) ABP subscription. You can find it [here](https://easylist-downloads.adblockplus.org/exceptionrules.txt). Of course it should be disabled by default.

**Comment by gorhill** [comment]
What's going on with you? I just closed a similar entry you created on HTTP Switchboard.

For the record: "Acceptable ads" is the business plan of a for-profit company (Eyeo GmbH), and has nothing to do with add-ons which are meant to serve users' interests only.

**Comment by mikhaelkh** [comment]
@gorhill, of course I know that, but you said that it's uBlock's purpose so I duplicated it here. At least give users a choice. Blocking ads completely has its disadvantages, it prevents to exist free products which does not serve well users' interests.

**Comment by gorhill** [comment]
> "Blocking ads completely has its disadvantages, it prevents to exist free products which does not serve well users' interests"

That's the marketing pitch used to promote ads in general, and the _"Acceptable ads"_ business plan in particular. You agree with the slogan, good for you.

Users have the choice to import this list in the _"Your filters"_ area by clicking the _"Import and append"_ if they want. Users can also easily turn off uBlock for a specific site if they think letting the ads (and analytics, trackers) go through is doing good.

**Comment by mikhaelkh** [comment]
OK, I forgot about contributions, Kickstarter, freemium. I share your concern for privacy, just wanted to know your opinion.

**Comment by kurtextrem** [comment]
I guess we need the "Add 3rd party filter via URL" feature.

**Comment by torzsmokus** [comment]
@gorhill you seem to have a strong opinion on zero acceptable ads and maximum privacy, which is fine.
what I dislike is that you are forcing that opinion on the users of µBlock.

I mean, I would like to use µBlock for blocking annoying, distracting and CPU-/battery-consuming ads. I have no problems with targeted text ads, tracking and stuff. I am totally with the [Acceptable Ads Manifesto](https://acceptableads.org/). I am having a hard time telling this to µBlock, it seems quite impossible.

I would expect all filter list to clearly split between adblocking and privacy concerns. let me decide.

should I file a new issue about this?

**Comment by torzsmokus** [comment]
well, I have found out that the main filter lists are split in a similar way I wanted; the list that mixed everything up was hufilter. I disabled that subscription (and others from the Privacy section) and added the Acceptable Ads list manually. I’m still suggesting to add that one to the top of all lists, maybe disabled by default.

**Comment by gorhill** [comment]
@torzsmokus 

What part of

> "Acceptable ads" is the business plan of a for-profit company (Eyeo GmbH)

did you not understand? Such a list has no place in FOSS.

**Comment by 0xBRM** [comment]
@torzsmokus 

> what I dislike is that you are forcing that opinion on the users of µBlock.

Firstly, it's his project, not yours. If you disagree with his vision, fork it. Secondly, and most importantly, he gave you the tools to do as you so desire (it's called YOU BLOCK for a reason). You can import any list your heart desires, override static filterring by using the dynamic filterring features, and so on.

**Comment by ghost** [comment]
@torzsmokus µBlock is free software, it's impossible by definition for the developer to force his opinion on the users, if rejecting a shady business strategy can even be called an opinion anyway.

**Comment by DomT4** [comment]
The idea of any advertiser taking their potential customer's privacy seriously is quite an amusing one. Most advertisers entire model is personalisation of content, which requires tracking and analytics. As ABP rather tellingly says:

> In particular, we want to require that every user's privacy is respected (e.g. mandatory Do Not Track support). However, we are not yet in a position to enforce that requirement.

There's also the fairly obvious problem that Acceptable Ads lists are vulnerable to one person being influenced by a certain company, and then having the power to silently tweak the list for everyone who uses it. Not pointing fingers, just pointing out the inherent problem with the lists in general.

> what I dislike is that you are forcing that opinion on the users of µBlock.

Seriously, it's not like he's hardwired the code to crash your computer every time you try and install a custom ad-supporting list. That would be _forcing_ his opinions onto you. "Sure you can use the list, I just won't be adding it by default" isn't exactly an holding-you-at-gunpoint view to take.

**Comment by RandomAcronym** [comment]
There are so many reasons why acceptable ads(™Eyeo GmbH) are so very wrong.
I can't even.

But ranting at comment boxes is a bad idea anyway, and this is not even one of those.

**Comment by Cephel** [comment]
There are no "acceptable" ads. Period.

People who install this addon know this very well, and I'd wager that's precisely _why_ they installed it.

**Comment by torzsmokus** [comment]
yeah, y’all are right – _forcing_ is way too harsh wording. maybe _pushing_ would have been a better fit, but still a bit strong.

after installing µBlock, enabling the Hungarian filterset and noticing that way more gets blocked than I wanted, I made the mistake of whining here instead of finding out how to achieve what I wanted, i.e. to block annoying ads but nothing more (definitely not GA and stuff). so after calming down, I had a look at my options, disabled the privacy filters and the Hungarian filterset that does not distinguish between ads and trackers. I also found out how to import the _Acceptable Ads_ whitelist by hand. now I’m more or less fine.

anyway, I find opinions like @Cephel ’s offensive. I installed the addon because I do not want annoying ads to drain my battery and distract my attention. I am fine with Google text ads and analytics. don’t expect everyone to think in black&white just because you do.

**Comment by Cephel** [comment]
I find your opinion stupid. Not offensive, stupid.
Being offended does not give you certain rights. It's just whining.
if you want to change it for yourself, enable the ads yourself. I don't want history repeat itself like with adblock plus who started with a few innocent "acceptable ads" and who are now literally being paid for unfiltering ads. Ironically advertising on adblock has become a profitable business.

The _only_ solution that works, the **ONLY** solution that works, is to not make any exceptions, block everything, then tell people "if you want to allow something, do it yourself". But it should be disabled by default.

**Comment by gorhill** [comment]
People are free to agree with the _"Acceptable ads"_ thingy, or not, it's irrelevant to this project. The only reason why _"Acceptable ads"_ is not included is because it is one specific business plan of one specific for-profit entity. uBlock is user-interests-driven, not business-plan driven, that's all there is to it.
