### ISSUE TITLE
[Feature Request] Support for the SeaMonkey browser

### ISSUE THREAD

**Issue by alabrand** [uBlock-LLC/uBlock#661]
Is it possible to add support for the SeaMonkey Browser or otherwise make it possible to install uBlock on it?

**Comment by gorhill** [comment]
It is supported: https://github.com/gorhill/uBlock/blob/master/platform/firefox/install.rdf#L26

**Comment by alabrand** [comment]
I assume all I gotta do is install the latest .xpi from the "releases" page?

**Comment by alabrand** [comment]
It works. I downloaded the latest Seamonkey and the latest uBlock. Both work without any issues so far.

**Comment by meltres** [comment]
Got it, thanks. On February 2, 2015 at 01:56:41 GMT+8, Raymond Hill notifications@github.com wrote:It is supported: https://github.com/gorhill/uBlock/blob/master/platform/firefox/install.rdf#L26  —Reply to this email directly or view it on GitHub.
