### ISSUE TITLE
[idea] show active user filters in blocked requests

### ISSUE THREAD

**Issue by Sigi-cz** [uBlock-LLC/uBlock#662]
sorry, I'm just guessing the names, because i cant switch uBlock language
I'd like to see (in dynamically filtered list under "3rd-party frames), if any of filters I created are active on current page. maybe with option to enable/disable/remove that filter.

**Comment by gorhill** [comment]
uBlock doesn't distinguish internally where filters come from. There would be a resource cost to support this, and I don't intend to sacrifice efficiency for features which are unlikely to be useful to the majority of users.
