### ISSUE TITLE
[Chromium] Tests #4-8 on http://raymondhill.net/ublock/popup.html are not working

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#663]
uBlock version: 0.8.6.0 from Chrome Web store
Browser version: Chrome 40
OS: Win 8.1 x64
Tested using the default filter lists.

As the title says, 4 through 8 on http://raymondhill.net/ublock/popup.html are not being blocked.
4 does not close
5 does not close
6 is not empty
7 is not empty either
8 does not close when clicking on test.

https://a.pomf.se/xfypiz.gif

**Comment by ghost** [comment]
6, 8, and 11 fail on Firefox.

**Comment by Deathamns** [comment]
8th should not close when clicking (see #507).
For some of the rest you have to remove the `about-scheme` and `data-scheme` entries from the  Whitelist.

**Comment by ghost** [comment]
> 8th should not close when clicking (see #507).

Whoops, my bad, should've looked/read a bit more.

> For some of the rest you have to remove the about-scheme and data-scheme entries from the Whitelist.

After removing about-scheme and data-scheme from the whitelist, all tests pass on Firefox.
After removing about-scheme and data-scheme from Chrome:
4 and 5 do not automatically close
6 and 7 are not empty, they show the example.com page

**Comment by gorhill** [comment]
@Deathamns I removed `about-scheme` and `data-scheme` from default whitelist. I didn't realized the negative side effect to blocking popup.

**Comment by Deathamns** [comment]
@hotdogman
Supporting 4 and 5 probably will need some work in Chrome.
6 and 7 should be supported if you remove the whitelisted schemes, but it seems something is not right there. Maybe `vAPI.tabs.onUpdated` doesn't fire when opening a window (because if you refresh the popup 6 after it loaded, then the iframe won't load)?

@gorhill You mean you didn't push a commit for it, or just wanted to remove it?

**Comment by gorhill** [comment]
I will push a commit when I am done with the other stuff.

**Comment by Deathamns** [comment]
By the way, this issues is basically a duplicate of #510.

**Comment by ghost** [comment]
> By the way, this issues is basically a duplicate of #510.

Whoops, didn't notice. My apologies.
