### ISSUE TITLE
Can't open datacenter.biathlonresults.com, jQuery was not found.

### ISSUE THREAD

**Issue by andrey-budko** [uBlock-LLC/uBlock#665]
Can't open http://datacenter.biathlonresults.com/ if uBlock is enabled.

JavaScript console:
Error: jQuery was not found. Please ensure jQuery is referenced before the SignalR client JavaScript file.
ReferenceError: $ is not defined.

Works fine with AdBlock Plus

uBlock 0.8.6, Firefox 35

**Comment by Mikey1993** [comment]
Add this exception filter to your "My filters" list:
@@||info$script,domain=biathlonresults.com

**Comment by gorhill** [comment]
It opens fine with default filter lists. What are your filter lists? Custom filters? Etc. Details please, saves time to all.

**Comment by andrey-budko** [comment]
It breaks after enabling
RUS: RU AdList (Дополнительная региональная подписка)‎

Full list of subscriptions I used:

My filters‎: 0 used out of 0
µBlock filters‎: 119 used out of 119
µBlock filters – Privacy‎: 2 used out of 2

EasyList‎ (adblockplus.org): 52 557 used out of 52 593
Peter Lowe’s Ad server list‎ (yoyo.org): 2 402 used out of 2 452

EasyPrivacy‎ (adblockplus.org): 9 739 used out of 9 745

Malware Domain List‎ (malwaredomainlist.com): 1 511 used out of 1 525
Malware domains‎: 17 244 used out of 20 125
Malware domains (long-lived)‎: 2 737 used out of 2 737

Fanboy’s Social Blocking List‎ (adblockplus.org): 11 487 used out of 11 490

RUS: RU AdList (Дополнительная региональная подписка)‎ (adblockplus.org): 6 860 used out of 6 860

**Comment by Mikey1993** [comment]
Right, this is why I was able to reproduce this.
`RUS: RU AdList (Дополнительная региональная подписка)‎` is not a list which is enabled by default.

**Comment by gorhill** [comment]
@andrey-budko So you are telling me that ABP with RU Adlist does not have the problem? (I can't try right now as https://easylist-downloads.adblockplus.org/ is down.)

**Comment by gorhill** [comment]
Ok, I could finally try it with ABP and it does not have the problem. This filter is the cause:

```
||info^$third-party,script
```

Investigating.

**Comment by andrey-budko** [comment]
With ABP I use «RuAdList+EasyList» preset. It refers to:
https://easylist-downloads.adblockplus.org/ruadlist+easylist.txt

**Comment by gorhill** [comment]
Problem is here: https://github.com/gorhill/uBlock/blob/master/src/js/static-net-filtering.js#L1321

> TODO: transforming `^` into `*` is not a strict interpretation of ABP syntax.

**Comment by gorhill** [comment]
Investigating for best fix. I will experiment with one that I figure could actually increase uBlock's efficiency of the network requests handler -- will benchmark to validate. I will take my time, I don't want to rush things.

Meanwhile, workaround above by @Mikey1993 works.

**Comment by gorhill** [comment]
After changes to fix the bug:

```
µBlock> onBeforeRequest: 0.131 ms (8664 samples)
µBlock> onBeforeRequest: 0.131 ms (8763 samples)
µBlock> onBeforeRequest: 0.131 ms (8839 samples)
µBlock> onBeforeRequest: 0.130 ms (8914 samples)
µBlock> onBeforeRequest: 0.131 ms (8988 samples)
µBlock> onBeforeRequest: 0.131 ms (9033 samples)
µBlock> onBeforeRequest: 0.130 ms (9192 samples)
µBlock> onBeforeRequest: 0.130 ms (9206 samples)
µBlock> onBeforeRequest: 0.129 ms (9324 samples)
µBlock> onBeforeRequest: 0.129 ms (9329 samples)
```

Also, this was after I moved the start of profiling to the platform-specific code (the earliest entry point into uBlock's code), something I forgot to do with the [last results](https://github.com/gorhill/uBlock/wiki/%C2%B5Block-vs.-ABP:-efficiency-compared#added-cpu-overhead-to-each-net-request) (I will revise the last results to use the results here).
