### ISSUE TITLE
[Chromium] Opening up Developer Tools logs to the request log

### ISSUE THREAD

**Issue by my-password-is-password** [uBlock-LLC/uBlock#666]
I was looking through the request log for a youtube video and I saw a .xml file, `https://r2---sn-8xgp1vo-uv5z.googlevideo.com/crossdomain.xml`, logged as image.

![ublockxmlimage](https://cloud.githubusercontent.com/assets/6408935/6000455/ea4d6ada-aa92-11e4-9438-e6ab440ca293.png)

Opened the .xml in a new tab to look at it and see if would log correctly but it logged it as `inline-script`.  Then I opened the Developer Tools and every time you open it it logs to the request log.

![ublockinspectlogging](https://cloud.githubusercontent.com/assets/6408935/6000552/021d5c6e-aa94-11e4-8594-654c8b9cd7b1.gif)

Chrome 40.0.2214.94 m
Windows XP x64
uBlock 0.8.6.0 ( store )

**Comment by gorhill** [comment]
For the `inline-script` thing, this is this [issue](https://github.com/gorhill/uBlock/issues/502#issuecomment-70087054). Currently, `inline-script` is logged regardless of whether there are really any inline script tags.

For the extra request when opening the dev console, well, Chromium is firing that request, so uBlock will report it. If you think Chromium should not fire that request, you will have to open an issue with them.

**Comment by my-password-is-password** [comment]
Firing that request means making a new request?  I opened up Fiddler and there are no new request  being made each time I open the dev console.

**Comment by gorhill** [comment]
I mean Chrome API is calling the `onBeforeRequest` handler:

![a](https://cloud.githubusercontent.com/assets/585534/6001075/8147d3c4-aab3-11e4-851e-eca0535a0144.png)

**Comment by my-password-is-password** [comment]
Oh, ok.  Gonna close this since its a chromium issue.

Sorry
