### ISSUE TITLE
[Firefox] Context menu item capitalization

### ISSUE THREAD

**Issue by d125q** [uBlock-LLC/uBlock#667]
Excuse my OCD, but Firefox follows a Title Case capitalization for its context menu items (unlike Chromium, I think). So, "Block element" should really be "Block Element".

Thank you for all the hard work.

**Comment by jimporter** [comment]
I'm guessing you mean "title case". Sentence case looks like this. Title Case Looks Like This.

**Comment by d125q** [comment]
Yes, I meant title case. Sorry.

**Comment by Deathamns** [comment]
Fixed in 37540a0.
