### ISSUE TITLE
[politics]

### ISSUE THREAD

**Issue by Aranjedeath** [uBlock-LLC/uBlock#668]
Here's a news article for you to read.
http://www.theregister.co.uk/2015/02/02/google_amazon_taboola_microsoft_adplock_plus_unblock

TL:dr; big companies are now flat out buying out exceptions in adblock plus. This leads me to believe the adblock lists may no longer be trustworthy. I don't know what to do about that, but figured I'd file a bug preliminarily.

**Comment by brwolfgang** [comment]
It looks like it's optional for users to activate "trusted sources with non-invasive ads" (or as the ABP site says "By doing this you support websites that rely on advertising but choose to do it in a non-intrusive way"), it seems that the local whitelist is tampered, not the general list itself. But I need to investigate it to be sure.

More on [The Verge](http://www.theverge.com/2015/2/2/7963577/google-ads-get-through-adblock)

**Comment by gorhill** [comment]
Those who pay are put in a [special list](https://easylist-downloads.adblockplus.org/exceptionrules.txt) which is not part of uBlock.

When I pull EasyList, EasyPrivacy, all the changes are visible for anybody to consult using Github diff tool, or even better using [EasyList's own repo](https://hg.adblockplus.org/easylist/summary).

**Comment by gorhill** [comment]
Here is the sub-forum where ABP decides what goes in the exception list: https://adblockplus.org/forum/viewforum.php?f=12. If you worry, you can follow that forum and check that the exception goes into that special filter list which is not supported by uBlock.

I personally do not doubt that there is a clear separation between the content of EasyList and ABP's "acceptable ads" campaign.
