### ISSUE TITLE
Allowing Salon.com comments

### ISSUE THREAD

**Issue by fncll** [uBlock-LLC/uBlock#670]
How can I create a filter that will allow the comments section to appear on Salon.com articles ([example article](http://www.salon.com/2015/02/01/why_smoking_pot_feels_so_good_new_neuroscience_explains_marijuana_and_the_brain/))? I used the element picker and ended up creating a rule that, based on my browsing around on the issue, seems like it should work:

```
* amazon-adsystem.com * allow
```

But it does not.

**Comment by hotdogman** [comment]
It works for me with the default filters.
I think the comments aren't loading for you because you're browsing the HTTPS version of Salon.com, but livefyre.com (the site for comments) is getting blocked because it's HTTP, and thus gets blocked due to the mixed-content policy.
Allow mixed content or try browsing the HTTP version of Salon.

**Comment by gorhill** [comment]
Comment section appears fine with default filter lists.

**Comment by fncll** [comment]
Thanks. I guess it was the Easylist doing it. Since it prevents a whole lot of other crap on Salon.com pages perhaps someone can help me figure out how to allow comments but not the rest?

**Comment by gorhill** [comment]
EasyList is part of default filter lists, and comments display just fine with it.

What in your config differ from default settings?

**Comment by fncll** [comment]
It certainly isn't for me. I have no filters or rules of my own. When I enable EasyList, comments no longer appear. 

The only filters I have otherwise enabled are the first three in the list:

```
My filters‎: 0 used out of 0;
µBlock filters‎: 70 used out of 70
µBlock filters – Privacy‎: 1 used out of 1
```

My whitelist is generated, I assume, by the program and contains 

```
about-scheme
behind-the-scene
chrome-extension-scheme
chrome-scheme
data-scheme
file-scheme
opera-scheme
```

I have nothing in the "Custom" box at the bottom of the 3rd party filters page.

I've updated, purged caches and reloaded. 

I then used the "Restore to default settings" option, updated all lists, and same result: Comments simply don't appear with EasyList enabled and they appear when it is not enabled.

The prefs I have selected are

```
Hide placeholders of blocked elements
Show the number of blocked requests on the icon
Make use of context menu where appropriate
```

**Comment by schalox** [comment]
These rules seem to work for me:

```
www.salon.com fyre.co * noop
www.salon.com livefyre.com * noop
```

**Comment by elyrly** [comment]
In my case Ghostery was blocking the comment section from loading via Livefyre `http://zor.livefyre.com/wjs/v1.0/javascripts/CommentCount.js`

**Comment by gorhill** [comment]
Nobody has been able to reproduce that bug so far, using provided details.

**Comment by fncll** [comment]
I'm closing this. I don't know what more information I can provide and the inability to reproduce the problem is immaterial. I'll just go back to a different product.
