### ISSUE TITLE
µBlock fail, ABP ok

### ISSUE THREAD

**Issue by pvlb** [uBlock-LLC/uBlock#671]
Not work filter ||http://animevost.org/692х200.swf, in ABP for Firefox ok.

**Comment by my-password-is-password** [comment]
In the request log the url looks like this, http://animevost.org/692%D1%85200.swf

`||animevost.org/692%D1%85200.swf` works

**Comment by Sayueri** [comment]
Blocked just fine for me. Tested in Firefox, Chrome and Opera.

http://imgwiz.com/images/2015/02/03/5brPh.jpg

**Comment by gorhill** [comment]
`||http://animevost.org/692х200.swf` is not a valid filter.

`|http://animevost.org/692х200.swf` is valid.

[Writing Adblock Plus filters](https://adblockplus.org/en/filters):

> **two pipe symbols** in front of the filter which makes sure the filter **matches at the beginning of the domain name**

`http` is not a domain name.

**Comment by my-password-is-password** [comment]
@gorhill, `|http://animevost.org/692х200.swf` works for you?

**Comment by gorhill** [comment]
@my-password-is-password yes. I tried it with `|http://animevost.org/favicon.ico`, because I don't know where on the site is OP's URL.

**Comment by my-password-is-password** [comment]
Its on the main page http://animevost.org/.  Its where @Sayueri screenshot points to

**Comment by gorhill** [comment]
I don't see it in the log.

**Comment by my-password-is-password** [comment]
you have click 2 play?

**Comment by gorhill** [comment]
Works: `|http://animevost.org/692%D1%85200.swf`

Doesn't work, because Unicode character: `|http://animevost.org/692х200.swf`

There should be no Unicode character in a filter itself, as it's not allowed anyway in a URL, it should always be percent-encoded. This is supported by the fact that Firefox reports a percent-encoded URL in the log, and in it's own list:

![a](https://cloud.githubusercontent.com/assets/585534/6019433/682bfe36-ab6e-11e4-9780-17d0aa0f4fc2.png)

**Comment by gorhill** [comment]
Actually, there should be no Unicode character in a filter itself, as it's not allowed anyway in a URL, it should always be percent-encoded. This is supported by the fact that Firefox reports a percent-encoded URL in the log.

**Comment by gorhill** [comment]
Ok, I am all confused now, I should never comment right after I wake up. Will be back later.

**Comment by pvlb** [comment]
Work in ABP FF ||animevost.org/692х200.swf must work in µBlock. Why perversion punycode/percent-encoded in the filters? Corrections will not be? Pipette does not create a filter, and starts advertising. Open the code view (Chrome/FF) and select the file to filter = fail... http://goo.gl/DnnY9R 
In FF 'network.standard-url.escape-utf8  → false' use it in µBlock?

p.s. NoScript avtoblock: OBJECT,shockwave-flash@http://animevost.org/692х200.swf

**Comment by my-password-is-password** [comment]
<s>It doesn't work in ABP FF.
You can see the red error message,  `The pattern you entered no longer matches the address to be blocked/whitelisted and will have no effect on it.`, when I replace `%D1%85` with `x`.   Refreshed the page and the .swf was still there.</s>

Nevermind, forgot to do `network.standard-url.escape-utf8 = false` like you said.  It does work after you set it to false.

**Comment by gorhill** [comment]
So there are two issues.

> Pipette does not create a filter

The element picker currently doesn't extract URL from `object` element. I now fixed this locally.

The other issue is dup of #498.

**Comment by pvlb** [comment]
It work in ABP for Firefox ok. http://goo.gl/TP6xKd + network.standard-url.escape-utf8 → false. 
yes, dup of #498. thanks for the fix! ;)
FF: OK, Chromium:  Issue 68718 and other

**Comment by gorhill** [comment]
Second part is dup of #498, so closing as such since 1st-part is fixed.
