### ISSUE TITLE
issue - vr-zone.com

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#674]
Posted by @harshanvn

> another test case (disabled dynamic filtering as seen in the screenshot) , having the similar issue - vr-zone.com
> ![ublock vrzone](https://cloud.githubusercontent.com/assets/779630/6025497/eeb9fcb6-abf8-11e4-9b51-85c52ac8facb.png)

**Comment by gorhill** [comment]
Can't repro.

**Comment by harshanvn** [comment]
<b>Apart</b> from below Filters Lists, everything else selected
- region filter lists section
-  EasyList without element hiding rules‎

If i resize the window (from normal to maximize or vice-versa), then the frames gets repositioned properly. 
This is on Windows 8.1 machine.

**Comment by gorhill** [comment]
> If i resize the window (from normal to maximize or vice-versa), then the frames gets repositioned properly

Well then this looks like a problem specific to the web page, due to the way it is designed. uBlock just add `display: none ! important` to DOM nodes, and whatever happens to the layout as a result is the responsibility of the browser/page.

**Comment by harshanvn** [comment]
Ok Thanks for your input.
I see the behavior with noscript is also inconsistent. Some times it collapses and some times it is now.
So, you may close the issue.
