### ISSUE TITLE
URLs displayed right after the filter lists redirect to nothing

### ISSUE THREAD

**Issue by maxxyme** [uBlock-LLC/uBlock#675]
When you go to the filter lists tab, you see urls just after the filter names.
And if you click on them you navigate, but not always to user-friendly urls.

e.g.
_EasyList_ : http://easylist-downloads.adblockplus.org/ => 403 Forbidden
Anti-Adblock Killer | Reek : http://raw.githubusercontent.com/ => https://github.com/
Spam404 : http://spam404bl.com/ => blank page with link to http://www.spam404.com/

+
Malware domains‎ : no URL ?

**Comment by elyrly** [comment]
Looks to be outdated websites more then anything else. Everything looks fine in the /filter-lists.json @gorhill might be time to change the a href=""

**Comment by gorhill** [comment]
It's just because I link to the effective domain of the remote home of a list. For lists which are not remotely downloaded, there is no effective domain. Some are hosted on Github so the effective domain is `github.com`. Etc. It's all done programmatically.

**Comment by maxxyme** [comment]
OK so basically you can't really do anything different than that?

**Comment by gorhill** [comment]
I could manually set the relevant URL to the a front page of a remote server in `filter-lists.json` and use this in the UI.
