### ISSUE TITLE
Localization is tied to language used in browser

### ISSUE THREAD

**Issue by maxxyme** [uBlock-LLC/uBlock#676]
(at least in Google Chrome) µBlock is in French because my Google Chrome is in French (I'm a French user and/or can't change the install at work) but I'd like to use µBlock in English.

How do I do that?

**Comment by Deathamns** [comment]
Dupe of #622.

Your answer is in the referenced issue.

**Comment by maxxyme** [comment]
OK thanks, didn't find this issue.

**Comment by gorhill** [comment]
Apparently you can do this for Windows: https://support.google.com/chrome/answer/95416?hl=en.
