### ISSUE TITLE
[Firefox] Blocking Facebook on Non-Facebook Sites

### ISSUE THREAD

**Issue by gituporabnik** [uBlock-LLC/uBlock#677]
I have a question regarding blocking Facebook from all websites except from facebook.com.
In Adblock Plus for Firefox the filter for this function was:
||facebook.*$domain=~facebook.com|~127.0.0.1

My questions are:
1) Can I use the same filter line for µBlock as well?
2) Do I paste it to "My filters", "My rules", or to "Whitelist" tab?

I am using µBlock in Firefox.

**Comment by elyrly** [comment]
Can you give me an example of websites using Facebook other then facebook.com?

**Comment by gorhill** [comment]
@elyrly It's everywhere, Facebook is notoriously ubiquitous.

@lencc The filter will work, in _"My filters"_.

**Comment by gituporabnik** [comment]
As I have read the filter should be blocking content (access and traffic to and from domains Facebook.com) except when we are actually on Facebook.
I just found the social blocking list within µBlock's "3rd party filters", which may also help.

Thank you!

**Comment by Snapy** [comment]
@lencc You should try Anti-ThirdpartySocial (was Anti-Facebook) which aims to block Facebook everywhere except on Facebook.
