### ISSUE TITLE
[Firefox] Distribution build instructions/script?

### ISSUE THREAD

**Issue by 2mac** [uBlock-LLC/uBlock#678]
I can't find documentation on building the Firefox plugin from the git source, only Chromium.

Are there plans to document, or is there an included script that can do this?

**Comment by jsta** [comment]
Is this the function of the script "make-firefox-meta.py"?

**Comment by gorhill** [comment]
> is there an included script that can do this?

`./tools/make-firefox.sh all` from the project 's root. The `xpi` file will be in `dist/build/`.
