### ISSUE TITLE
[Firefox] Unwanted slideshow component blocked

### ISSUE THREAD

**Issue by Armonth** [uBlock-LLC/uBlock#679]
uBlock under Firefox with gorhill list (https://github.com/gorhill/uBlock/wiki/Filter-lists:-gorhill) but tried with the standard list too, not custom filters.

I detected a slideshow don't working in ITWorld ( http://www.itworld.com/article/2876757/10-signs-you-ve-been-coding-too-much-for-too-long.html ). No other plugins, if I disable uBlock, the slideshow works again.

I'm new using uBlock (installed a few days ago) and not noticed this problem before in ABP+Ghostery, I want to know if is some 'legit' is being filtered by accident or is site blame...

**Comment by gorhill** [comment]
> with gorhill list

I added a note to [that page](https://github.com/gorhill/uBlock/wiki/Filter-lists:-gorhill):

> **Important:** Use at your own risks, you are on your own. Time is precious and I have none left.

Just use default filter lists if you were using ABP+Ghostery.

**Comment by Armonth** [comment]
Sorry if reply again but I think you missed the part after link to your list "but tried with the **standard list too, not custom filters**". Anyway, missed to say, but for add further information:
- With the standard list, the site blocks count marks 30, click to next and browser go to slide 2 (working), then next/prev 'stops to work' and every click mark gets +1 blocked (don't get images, only the "Next slidershow" image after 11 pages of not refresh slidershow).
- With your list, the count ups to 49 without touch anything and the slider just don't work...

**Comment by gorhill** [comment]
> With the standard list, the site blocks count marks 30, click to next and browser go to slide 2 (working), then next/prev 'stops to work'

Same issue with ABP. Please report to EasyList maintainers: https://forums.lanik.us/viewforum.php?f=64
