### ISSUE TITLE
Ability to create a net filter easily from an entry in the request logs

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#68]
That would help users help themselves.

For instance, with out-of-the-box settings, comments do not work on Fox News web site. There is something in _"Peter Lowe's Ad server list"_ which breaks comments on Fox News. With this feature, a user would be able to whitelist whatever blocked which is breaking the comment section, rather than disable the whole Peter Lowe's list (it is useful).

Conversely, some unwanted requests which go through could be easily blocked with this feature.

**Comment by gorhill** [comment]
With the new revamped network request logger, there is now a lot of possibilities.

**Comment by mike-to-spec** [comment]
I want to write in and say this is definitely a powerful feature to have in uBlock. 

As a new user to uBlock starting out with the 3rd party blocked by default, I actually have the network logs open in its own window almost all the time to help me figure out which rule blocked the comments, images, and so on. Without looking at file names or types in the network logs, it is next to impossible to figure out what to whitelist based on basic URLs in the uBlock's main view. 

As I continue to build my rules, the less often I'll need my network logs to be opened. However, when I do need to open it, I would love to be able to create rules from there without also having to switch views, it would speed up the whole process for me.

**Comment by gorhill** [comment]
> without also having to switch views

Meanwhile, the popup UI in the request log will be filled with the data of the tab being logged.

**Comment by tyaremco** [comment]
I found the way ABP displays their request log to be very easy to use.  The request log is embedded in a UI pane immediately below the page (like how the Firefox developer tools are displayed).  You could white/blacklist individual requests from the context menu.

**Comment by ekerazha** [comment]
@chrisaljoudi
Is this enhancement planned?

**Comment by chrisaljoudi** [comment]
@ekerazha Yes.
