### ISSUE TITLE
Blacklist mode (instead of whitelist)

### ISSUE THREAD

**Issue by tomparys** [uBlock-LLC/uBlock#681]
Hi there,
since I'd like to support plenty of Internet sites by displaying their advertisement, and only block some offenders with too flashy ads,

I'd like to request a blacklist mode - where uBlock is disabled by default, but you can enable it for a given site.

Since it looks like ad blockers are becoming the majority now, I think this would be a responsible move.

Thanks a lot for your time and a great extension!

**Comment by dashed** [comment]
https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site

**Comment by tomparys** [comment]
I'm confused, that's appears to be the opposite of what I'm asking for. The article is about whitelist mode (on by default, turn off adblocking on certain sites), whereas I'm asking about blacklist (i.e. off by default, only adblock certain sites). I'm not seeing it mentioned anywhere in the article itself either. Have I missed something?

**Comment by dashed** [comment]
Oh oops. Yea, you're right. I probably need some coffee :sleepy:

**Comment by Mikey1993** [comment]
#177 + #577

**Comment by tomparys** [comment]
Damn, I should have searched for it first, I was too eager, mea culpa.

Is there any way I can close/delete the issue?

**Comment by gorhill** [comment]
Incidentally, a side effect to fixing issue #682 is to allow blacklist mode.
