### ISSUE TITLE
contentscript-end.js: remove overhead of short-lived function expression

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#683]
We can get rid of the closure, hence the overhead of the function expression created for each image/iframe/object's load/error event.

**Comment by chrisaljoudi** [comment]
@gorhill line no.?

**Comment by gorhill** [comment]
Core code.

**Comment by chrisaljoudi** [comment]
@gorhill sure, was just curious — sorry. :)

**Comment by gorhill** [comment]
The `onAnswerReceived` function was created for each load or error event.

I was laconic because I was about to commit the changes.
