### ISSUE TITLE
Blocking ads in an iframe of a page that is a local file

### ISSUE THREAD

**Issue by oskarkv** [uBlock-LLC/uBlock#684]
I have a local file `page.html` that is a little "app" I wrote for reading russian texts. What it does is to look up words in online dictionaries and shows the dictionaries in iframes. But in those iframes, uBlock does not block the ads. Can this be fixed?

**Comment by chrisaljoudi** [comment]
What's the `iframe`'s `src`?

**Comment by oskarkv** [comment]
For example http://www.lingvo-online.ru/ru/Translate/ru-en/%D1%81%D0%BB%D0%BE%D0%B2%D0%BE but it changes while using it.

**Comment by gorhill** [comment]
uBlock is disabled by default for local files. Turn it on by clicking the big power button. It's supposed to work.

**Comment by oskarkv** [comment]
Oh! It does work. Thanks!
