### ISSUE TITLE
[Chrome] Options window, too small and cannot be resized

### ISSUE THREAD

**Issue by Taomyn** [uBlock-LLC/uBlock#685]
I just installed uBlock but the options window is very small and difficult to use. I cannot resize it only scroll the content, and I cannot see all the tabs.

![clipboard01](https://cloud.githubusercontent.com/assets/4365929/6037010/8a0629c4-ac4e-11e4-843e-7c588735b1d9.jpg)

I disabled all the other extensions in Chrome (x64, Win8.1) and restarted and it's still the same.

**Comment by gorhill** [comment]
What version of Chrome?

The options are supposed to open in its own tab. It's not what I see in the pic. Try accessing the options by clicking the title bar in uBlock's popup UI.

**Comment by Snapy** [comment]
See [this comment](https://github.com/gorhill/uBlock/issues/197#issuecomment-61366720).

**Comment by gorhill** [comment]
@Snapy Yes, it's what I was thinking. ~~However I don't see this yet in Chrome Beta 41.~~ Never mind, forgot flag.

**Comment by Taomyn** [comment]
I'm using Chrome v40

@Snapy that setting was disabled, but I decided to give the "Reset all to defaults" button a go and it seems to have cured the problem. Very strange.

**Comment by kurtextrem** [comment]
@gorhill I think the "fix" looks broken (I know it isn't). http://prntscr.com/63ital that does just look like CSS is missing in my opinion.

**Comment by gorhill** [comment]
I use the browser CSS (`chrome_style` below):

```
"options_ui": {
    "chrome_style": true,
    "page": "options_ui.html"
}
```

**Comment by kurtextrem** [comment]
The chrome_style doesn't change a lot: https://chromium.googlesource.com/chromium/src/+/5b6cdc6c/extensions/renderer/resources/extension.css#315 (only inputs). I'd recommend the following change: Add http://i.imgur.com/oQB3Xmn.png behind every link, so the user recognizes he should click to open in a new tab and the UI is not broken. (Icon from here: http://svgicons.sparkk.fr/ 2nd set)

**Comment by gorhill** [comment]
> chrome_style doesn't change a lot

Then I think you should open an issue with Chromium if you think their CSS needs re-design.

**Comment by kurtextrem** [comment]
That's not the problem here... it's this one:
- User right clicks the icon, select "Options"
- new tab is opened with a few underlined words with bullets in front of them _instead_ of the normal options page
  => What he thinks now is "something is broken, as I can see the options but only the headlines of the tabs". An icon which shows "if you click here it opens a new tab with the full settings displayed" solves that. (see suggestion above)

**Comment by gorhill** [comment]
Isn't it obvious these are links to be clicked?

![c](https://cloud.githubusercontent.com/assets/585534/6170388/5195fba0-b2a2-11e4-847e-7cc3a5f06b7c.png)

It's Chromium which is forcing the hand of extension developers: any extension which has setting UI pages which do not fit their little embedded widget have not choice but provide a set of links to the real setting UI pages.

Those links are rendered using the browser CSS, just like whatever else on `chrome://` pages, so I fail to see why it suddenly becomes confusing when the same CSS rendering is used by uBlock.

**Comment by ghost** [comment]
I have the same issue. This is why I call the Dashboard from either uBlock's toolbar button -> popup's title area, either from a simple bookmark to _chrome://ublock/content/dashboard.html_

**Comment by Deathamns** [comment]
As an [alternative](https://github.com/gorhill/uBlock/tree/nooptions_ui).

**Comment by gorhill** [comment]
@Deathamns Good idea, works well. Can you check-in changes in master?

**Comment by kurtextrem** [comment]
That solution is great (and I don't wanna be _that_ guy, but to be HTML5 valid a head-element is needed with an title element (it can be a space though))

```
<!doctype html>
<head>
<title> </title>
<script src="js/vapi-client.js"></script>
<script src="js/vapi-common.js"></script>
</head>
```

**Comment by gorhill** [comment]
Actually, I have a simpler fix: to just use a `<meta>` redirect.

**Comment by Deathamns** [comment]
@kurtextrem I know, I just didn't care, since the browser can handle it.

@gorhill `<meta>` - How would that work? With `<meta>` the page will be redirected, but still in that popup.

**Comment by gorhill** [comment]
@Deathamns never mind, I thought it worked, looks like I just tested it using your code. Duh me.
