### ISSUE TITLE
broken links in Chrome on www.sltrib.com

### ISSUE THREAD

**Issue by fjarlq** [uBlock-LLC/uBlock#687]
To reproduce:
1. go to http://www.sltrib.com/
2. leftclick on any link (like a headline)
3. observe that nothing happens
4. use uBlock icon to disable uBlock for this site
5. reload web page
6. try clicking links -- observe that they are working fine
7. reenable uBlock for this site
8. reload web page
9. try clicking links -- observe that they are broken again

System info:
- uBlock 0.8.6.0
- Chrome 40.0.2214.94
- Windows 7 SP1 64-bit
- been using uBlock for a couple days without problems, until this
- note: the same problem does not occur with Safari + uBlock (same filter set)

uBlock filter options enabled:
- auto-update filter lists
- parse and enforce cosmetic filters
- My filters (empty list)
- uBlock filters
- uBlock filters -- Privacy
- Anti-Adblock Killer | Reek
- EasyList
- Peter Lowe's Ad server list
- EasyPrivacy
- Malware Domain list
- Malware domains
- Malware domains (long-lived)
- Anti-ThirdpartySocial

**Comment by fjarlq** [comment]
Sorry, I submitted this duplicate of issue 686 accidentally.

**Comment by gorhill** [comment]
Dup of #686.
