### ISSUE TITLE
Cosmetic filtering should be disabled if page is under dynamic filtering `allow` rule

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#689]

**Comment by Snapy** [comment]
@gorhill I totally agree. It would fix completely #497 (and the discussion following my [comment](https://github.com/gorhill/uBlock/issues/497#issuecomment-69982616)).

**Comment by gorhill** [comment]
So from now on, if a web page itself is under a dynamic filtering `allow` rule -- directly or indirectly, this will disengage cosmetic filtering as well on that site:

**Comment by gorhill** [comment]
@Snapy note that this doesn't work as you expected it to work in #489: this will disengage cosmetic filtering for the current page, but you can't disengage cosmetic filtering for `#.embed-twitter` specifically: `#.embed-twitter` is a generic cosmetic filter, there is no way for ublock to know that `#.embed-twitter` is associated with `twitter.com`.

It has to be an all or nothing solution, but at least a user now can choose that all-or-nothing solution to apply only to specific web sites. The only doubt I have left regarding the current solution is whether to use the site's own cell (as it is now), or whether to introduce another row dedicated to control cosmetic filtering. To keep adding rows is not ideal however, so for now I settled to evaluate a site's own cell to determine whether cosmetic filtering should be turned off.
