### ISSUE TITLE
Dynamic filtering's default-deny is unusable

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#690]
Globally blocking the `all` cell causes everything to be blocked, including `css`, rendering the default-deny mode unusable in practice.

The `all` row, added in #682, has not been officially released yet, so it's a good time to fix this.

Solution: split the `all` row into two rows: `1st-party`, `3rd-party`.

**Comment by Snapy** [comment]
I would really appreciate it. Indeed I was thinking on opening an issue asking to extend the syntax of dynamic filtering rules to add 1st-party as it is in µMatrix but wasn't sure if it was appropriate for µBlock. So if you do could you also add other useful rules syntax I might have missed (if you don't mind).

**Comment by gorhill** [comment]
Just added a `3rd-party` row and kept `all` row. a `1sp-party` row would be unlikely be useful for users of default-deny mode. On the other hand a `all` row is useful to users of equivalent of "blacklist" mode. An `all` row may also sometimes be useful to any user who wish for example to "whitelist" a page while keeping ability to block specifically some stuff.

**Comment by gorhill** [comment]
For translators:

![d](https://cloud.githubusercontent.com/assets/585534/6046134/7d334276-ac6d-11e4-9e54-fabf041791f2.png)

`3rd-party` refers to any type of resource which is 3rd-party to the site.
