### ISSUE TITLE
Delete uBlock folder manualy

### ISSUE THREAD

**Issue by jcanonyme** [uBlock-LLC/uBlock#691]
Hello everyone;
Can't start Safari since i tried to intall it from:
https://extensions.apple.com/details/?id=net.gorhill.uBlock-96G4BAKDQ9
I have trouble localize ublock's folder.
tried: `/Library/Internet Plug-Ins`
and
`~/Library/Internet Plug-Ins`
no trace of it.
how can i fix my problem ?
thx

**Comment by chrisaljoudi** [comment]
Safari Extensions live in `~/Library/Safari/Extensions/`.

**Comment by jcanonyme** [comment]
find this:
/Users/jc/Library/Caches/com.apple.Safari/Extensions/µBlock.safariextension/
delete it; still broken.

**Comment by jcanonyme** [comment]
@chrisaljoudi  thanks
