### ISSUE TITLE
Cannot install uBlock firefox

### ISSUE THREAD

**Issue by Blocikinio** [uBlock-LLC/uBlock#692]
I just want to download the xpi file, but i cannot. Little box appears, i clicked "Allow". It were downloading, when suddenly new box appeared and says "Sorry, we cannot connect to github servers" can i get help? didn't know where to post it, i'm new here.

**Comment by gorhill** [comment]
Avast?

**Comment by brwolfgang** [comment]
Pretty sure it's your antivirus, try to avoid the direct install by right clicking on the download link and select "save as". If the file is downloaded go to File -> Open file and select the uBlock xpi file to begin the installation process.

If these steps don't work disable any antivirus software installed on your computer, install uBlock and then enable it again.

**Comment by Blocikinio** [comment]
@brwolfgang It works.

Thank you guys very much ;]

**Comment by brwolfgang** [comment]
You're welcome
