### ISSUE TITLE
Options page shortcut

### ISSUE THREAD

**Issue by ozar** [uBlock-LLC/uBlock#694]
Is there some other way to get to the uBlock Options page rather than having to go to the Add-ons Manager page in Firefox each time a change needs to be made?  If there is not one, would it be feasible to create a shortcut link within the uBlock power button window?

Please accept my apology if it already exists and I've missed it, or this question has been answered before, and I missed that with my search efforts.

Thank you for a fine extension, gorhill.  :)

**Comment by gorhill** [comment]
Click the title bar of the popup UI. There supposed to be a tooltip but it does not work on Firefox.

**Comment by ozar** [comment]
That works great... thanks again!
