### ISSUE TITLE
hung tab after unchecking all 3rd-party filters in Chrome

### ISSUE THREAD

**Issue by fjarlq** [uBlock-LLC/uBlock#695]
To reproduce:
1. Go to uBlock's Dashboard -> 3rd-party filters
2. uncheck all the filters and apply changes
3. observe that the tab is now hung: continuously spinning blue ball, all the filters grayed out
4. note that uBlock still seems to be okay.. problem does not recur after reloading the tab

System info:
- uBlock 0.8.6.0
- Chrome 40.0.2214.94
- OS X 10.9.5

**Comment by ghost** [comment]
I can reproduce this on both Chrome and Firefox, so I'm pretty sure it's not a platform-specific issue.
When refreshing the page, I can see that the settings were applied, though. Clicking on another tab, such as "My filters" also does the trick.

**Comment by gorhill** [comment]
I think this might have been filed before, not sure.

**Comment by my-password-is-password** [comment]
I reported something similiar but for uMatrix.

https://github.com/gorhill/uMatrix/issues/2

Don't know if its the same issue or the one you're were thinking of.
