### ISSUE TITLE
[Firefox] Yahoo Answers advertisments not blocking

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#696]
All Yahoo advertisements on Yahoo Answers are loading with uBlock 0.8.6 installed using Firefox 35.

I tried to load Yahoo Answers in Google Chrome with uBlock and the advertisements are blocked sucessfully with the same filter lists enabled.

Examples of affected URLs are:
https://answers.yahoo.com/question/index?qid=20150130103427AAkfwzj
https://answers.yahoo.com/question/index?qid=20150130103543AAc6K87
https://answers.yahoo.com/question/index?qid=20150126110120AAPd5B4

Screenshot of advertisement:
![upload](https://cloud.githubusercontent.com/assets/10857328/6052362/294970e0-ad26-11e4-9db9-e78bd02e26c5.png)

The filters I have enabled in uBlock Firefox are:

![filters](https://cloud.githubusercontent.com/assets/10857328/6052324/8a608f0e-ad25-11e4-8379-1747f21b9efe.png)

**Comment by gorhill** [comment]
Works fine here.

What are the two filters in your custom filters?

**Comment by ghost** [comment]
Ones for Tumblr:

```
||tumblr.com/video_file/*
||tumblr.com/*.gif
```

Edit: Tried deleting them, and refreshing page. The ads are still loading so I don't think it's those filters.

**Comment by gorhill** [comment]
Note that I don't see the other advertisements which one see if disabling uBlock. So it looks like a cosmetic filter issue.

Anything in your whitelist tab?

**Comment by ghost** [comment]
Just the defaults:

```
about-scheme
behind-the-scene
chrome-extension-scheme
chrome-scheme
data-scheme
file-scheme
opera-scheme
```

The request log shows a number of things being blocked so uBlock is doing some things.

**Comment by gorhill** [comment]
Yes it looks like this ad requires a cosmetic filter. I would like to see the class/id/etc. If you use the element picker on it, I would like to see all the suggested cosmetic filters in the element picker dialog box. It could be a new layout not covered by the current EasyList.

For example I get:

```
###dmRosAdWrapper-MainNorth-iframe
###dmRosAdWrapper-MainNorth.mt8
###ad-case
###qa-case.qa-container
###yan-question
###ya-m
###ya-c.rapidnofollow
###ya-center-rail.y-col.y-col2-1
###ya-content-apps.ya-grid
###ya-main-content.y-col2
###ya-body-container.ya-grid
###ya
```

**Comment by ghost** [comment]
Here's what I get:

![screenshot](https://cloud.githubusercontent.com/assets/10857328/6052636/358be4ca-ad29-11e4-9bc8-ff51b77870d4.png)

```
    Net filters
        about:blank
    Cosmetic filters Click, Ctrl-click
        ###dmRosAdWrapper-MainNorth-iframe
        ###dmRosAdWrapper-MainNorth
        ###yui_3_17_2_3_1423095504008_1933.Mstart-75.Mr-14
        ###ya-qpage-textads.Bgc-w.Pt-7.Mb-neg-10.Bdstart-1g.Bdend-1g
        ###ya-center-rail.Col2.Pos-a.Bxz-bb.Start-0
        ##.Answers
        ###MasterWrap
```

**Comment by gorhill** [comment]
Strange. I can't find any of your selectors in EasyList. The ad on my side located at the same position is filtered out through _EasyList_'s `#ad-case`. It's as if you stumbled onto a new Yahoo ad which is not covered by _EasyList_.

**Comment by gorhill** [comment]
How old is your _EasyList_? If you click on it in the 3rd-party filter lists, it will open whatever is being used.

**Comment by ghost** [comment]
EasyList is "Last modified: 05 Feb 2015 00:10 UTC"

**Comment by gorhill** [comment]
Maybe another extension is modifying the page? I really don't know what to say, as said, none of the selectors in there is a match in _EasyList_. You could report to _EasyList_ maintainers but it might be kind of awkward for them to see uBlock was used. But the CSS selectors are really what matters, and they are no hit.

**Comment by ghost** [comment]
I uploaded the HTML Yahoo is using at https://gist.github.com/metaphoricgirrafe/ef9bb7e48a7801acb107

They are serving totally different HTML for Firefox and Chrome, perhaps this is the issue?

**Comment by gorhill** [comment]
What I reported above was with Firefox.

**Comment by gorhill** [comment]
Me:

```
<div id="ad-case">
<style> #dmRosAdWrapper-MainNorth iframe{width:100%}</style>
<div id="dmRosAdWrapper-MainNorth" class="mt8">
```

You:

```
<div id="yui_3_17_2_3_1423096017604_1911" class="Mstart-75  Mr-14">
<style>#dmRosAdWrapper-MainNorth iframe {width: 100%}</style>
<div id="dmRosAdWrapper-MainNorth">
```

The cosmetic filter in action here on my side is `#ad-case` (a generic one).

**Comment by ghost** [comment]
I just restarted Firefox and loaded up YA again and the ads are gone. I inspected the HTML and it is now the same as yours.

I had the same problem with ads showing up on Yahoo Answers yesterday, so it looks like they must of being giving me a new layout and reverted me back to the normal one.

**Comment by ghost** [comment]
Scratch that. I'm getting served advertisements again in Firefox.

The HTML is now slightly different:

```
<div id="ya-qpage-textads" class="Bgc-w Pt-7 Mb-neg-10 Bdstart-1g Bdend-1g">
    <div id="yui_3_17_2_3_1423105641477_1929" class="Mstart-75  Mr-14">
        <style> #dmRosAdWrapper-MainNorth iframe {
            width: 100%
        }</style>
        <div id="dmRosAdWrapper-MainNorth">
            <noscript>
                <iframe id="dmRosAd-1-north" width="560" height="315" frameborder="0"
                        marginheight="0" marginwidth="0" scrolling="no"
                        src="http://dmros.ysm.yahoo.com/ros/?c=580c58ad&w=678&h=315&ty=noscript&tt=$title&r=$keywords">
                </iframe>
            </noscript>
        <iframe scrolling="no" marginheight="0" marginwidth="0" src="about:blank" id="dmRosAdWrapper-MainNorth-iframe" frameborder="0" height="225" width="560"></iframe></div>
    </div>
</div>
```

Seems like I will have to apply a filter to `#ya-qpage-textads`

Thank you for also taking a look into this issue.

Edit: Blocking everything from the YA domain also disables these new ad displays 
`||answers.yahoo.com`

**Comment by gorhill** [comment]
I suppose if `#ya-qpage-textads` is reported to EasyList, this would also benefit other users.

**Comment by ghost** [comment]
Alright, I've reported `#ya-qpage-textads` to EasyList :+1: 

Note: Using `#ya-qpage-textads` as a rule leaves a flash of unstyled content but using `||answers.yahoo.com` blocks it without the quick flash of ads during the load.

**Comment by ghost** [comment]
@metaphoricgirrafe - Looks like after a month, EasyList doesn't have your fix.
Can you please post it here, so I can manually add it to my blocker?

**Comment by gorhill** [comment]
What's your version of EasyList? I see it in there:

```
answers.yahoo.com###ya-qpage-textads 
```

"Last modified: 04 Mar 2015 12:10 UTC".

I checked, and it is also in the version of EasyList shipped with uBlock.

**Edit:** see https://hg.adblockplus.org/easylist/rev/16a4e027d6d1

**Comment by ghost** [comment]
I see yahoo updated their ad. It's now id="ya-q-8657-textads"
I presume this number can vary.
