### ISSUE TITLE
Not an issue, a simple filter lists purge question

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#697]
Hi,
uBlock 0.8.6.0 on Firefox 35.0.1 running smooth, fast. Brilliant.
My question is related to Purge all caches in uBlock -> Dashboard -> 3rd-party filters.

I opted for manual filter lists' update, that is Auto-update is unchecked.
I'd wish to now the pertinence of purging all caches before updating filter lists. I noticed that sometimes I have to (Update now, greyished, requires it) and other times I have the choice (Update now not greyished).

I assume the logic is that if I update the filter lists without purging first, the updated lists are added to existing ones and any removed filters from the sources are not removed from my database. Is this correct? If so, I'd have to purge systematically before updating to assure a mirror setting of all my filters? I'm missing something, obviously.

Thanks

**Comment by gorhill** [comment]
Not sure I understand the question.

The filter lists are downloaded, and the downloaded content is cached locally. When a new version of a filter lists is available, the new version is downloaded and the current cache version is overwritten by the new version. So a user ends up with a mirrored version of a remote filter list.

**Comment by ghost** [comment]
OK, gorhill, but then what is the purpose of purging the filter lists, If updating the lists overwrites exactly my lists with their sources? This is what I don't understand. Perhaps is purging made available in the case of a problem? I may be naive, certainy am, but I'm missing the point on the pertinence of purging. Thanks for your quick reply.

**Comment by gorhill** [comment]
Updating the filter lists will cause **only obsolete** filter lists to be fetched remotely. Sometimes you may want to force an update when you know that a remote filter list has been updated, but uBlock has no idea about this.

Roughly, in uBlock, a filter list is deemed obsolete if it's older than 4 days (I think I will bump that to 5 to ease load on remote servers), or if uBlock's generated checksum for a list has changed.

**Comment by ghost** [comment]
OK, I got it, thanks.
