### ISSUE TITLE
[Feature] Add ability to disable for main/root domain name

### ISSUE THREAD

**Issue by bbeardsley** [uBlock-LLC/uBlock#699]
Some sites I use that I don't want to use ublock on make extensive use of subdomains and I have to keep clicking the ignore button each time it switches to a different subdomain (ie  subdom1.domain.com, subdom2.domain.com, etc...)  Could we have a feature to Ctrl-Shift click and have it disable for the whole main/root domain?

**Comment by Matthewus** [comment]
uBlock dashboard/Whitelist tab - paste the main domain there
https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site

**Comment by bbeardsley** [comment]
Thanks for the link but I was thinking of something quicker and easier and there's already a Ctrl click.

**Comment by gorhill** [comment]
Having too many combos of modifiers is not user friendly. I will try to think of something which doesn't compromise the minimalist UI.

**Comment by smlx** [comment]
This feature would be very useful, particularly on mobile where copy/paste is more difficult than it is on the desktop.

One clean way to present it would be to **always** show the main domain even when all requests are to subdomains. (just display zero "+" symbols).
