### ISSUE TITLE
Blocked contents don't always disappear properly

### ISSUE THREAD

**Issue by JBey4you** [uBlock-LLC/uBlock#7]
When you try to a block an image in particular, there's a problem. Here's what appear on website 9to5Mac.com. They have this image (http://s2.wp.com/wp-content/themes/vip/9to5mac2/images/adblock-inline-ad-1.png) when an ad blocker is enabled. When you try to block this image, this appears : http://i.imgur.com/6xxBFac.jpg

When you use Adblock Plus for example, the image disappear completely (see: http://i.imgur.com/16jUIqg.jpg). If you know a fix...

**Comment by gorhill** [comment]
Solution is probably to redirect to a transparent 1px image. I don't know how ABP does it, but that is certainly the simplest fix I can think of, which doesn't require playing in the DOM. I will try that sort of fix first and see what happens.

**Comment by JBey4you** [comment]
With v.0.1.0.6, there is some progress. Although, it's not 100% fixed. :-)

Here are two captures that show that a white space is still here (I underlined the space in question: http://i.imgur.com/yFTyjrr.jpg & http://i.imgur.com/bhHgbdb.jpg

But good job on this release!

**Comment by gorhill** [comment]
Yes, the second part is the more challenging one, i.e. needs to put in infrastructure which doesn't exist yet (it didn't exist in HTTP Switchboard). I will have to think thoroughly to find the best way to implement this. Definitely possible, but I want to preserve efficiency advantage over other blockers.

**Comment by kurtextrem** [comment]
ABP doesn't use the 1px thing. Adblock uses that. (ABP uses Shadow DOM, however that works https://adblockplus.org/blog/on-the-adblock-plus-memory-consumption#c005367)

**Comment by gorhill** [comment]
I prefer to come up with my own solutions. I have various ideas, my point is that it's not going to be fixed as fast as the first part.

**Comment by gorhill** [comment]
Sorry but due to issue #18, I had to move redirection to no-op content, so the collapsing of the DOM counterpart of a request is the only solution.
