### ISSUE TITLE
Question about releases policy

### ISSUE THREAD

**Issue by chrisaljoudi** [uBlock-LLC/uBlock#701]
Hi @gorhill (posted here because I understood you prefer this).

What's the policy on bumping version no.s and drafting releases? Is it okay for me to, for example, bump the version to 0.8.7.0 and draft that for release as an alpha/beta?

**Comment by gorhill** [comment]
- +0.0.0.1 for bug fixes
- +0.0.1 for enhancing existing features
- +0.1 for non-trivial new features

**Comment by chrisaljoudi** [comment]
Got it — thanks.
