### ISSUE TITLE
Dynamic filtering: * * * block won't work with ff35

### ISSUE THREAD

**Issue by maycontainnuts** [uBlock-LLC/uBlock#703]
Disabled all filter lists except the µblock filters and added "\* \* \* block" as the one and only rule to "my rules". All of the global dynamic rules sections are dark red and i expected that all dynamic content should be blocked now. But adds, scripts, images will still be loaded from 1st and 3rd sites …
![ublock](https://cloud.githubusercontent.com/assets/10872215/6069902/746c2f56-ad88-11e4-80ea-4c8a81efea69.jpg)

.

**Comment by gorhill** [comment]
What version of uBlock? It's only available in dev version.

**Comment by gorhill** [comment]
Never mind, from the picture I see you are using v0.8.6.0. The support for `* * * block` is in the dev version. I created a [bleeding edge release](https://github.com/gorhill/uBlock/releases). Can only be installed manually.
