### ISSUE TITLE
Question: uBlock superseding uMatrix?

### ISSUE THREAD

**Issue by alejandrolemus** [uBlock-LLC/uBlock#705]
Posting here since there are no official forums that I'm aware of, sorry. 
With the new dynamic filter feature, does uBlock performs as uMatrix? Does it make sense still having both extensions at the same time?

Edit: I know there is this https://github.com/gorhill/uMatrix/issues/32, but I don't think dynamic filtering was included at the time.

**Comment by gorhill** [comment]
For someone who doesn't need the high granularity of uMatrix, uBlock is certainly becoming a better alternative, though it misses privacy features avilable in uMatrix -- but I intend to bring to uBlock what maybe helpful to a majority of users (clear cache, hyperlink auditing for examples).

Even for someone who like the higher granularity of uMatrix, uBlock's dynamic filtering may be attractive given the unique `noop` action, which allows static filtering to still take effect.

It's where HTTPSB failed: static filtering was slapped on top, not really integrated thoughtfully: it was block or don't block. In uBlock, both static and dynamic filtering work more harmoniously together: force block, force allow, or block/allow as per static filtering.

**Comment by alejandrolemus** [comment]
@gorhill Thank you for your insights on the matter. I was thinking that is kinda ironic that you are merging functionality again after deciding to split HTTPSB :)
But I certainly prefer to deal with a very configurable extension (improved uBlock?) rather than two.
Cheers!
