### ISSUE TITLE
uBlock not catching JW Player ads in Safari

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#706]
OS X Yosemite 10.10.2
Safari 8.0.3
uBlock 0.8.6.0

There are some sites that use JW Player to host videos with ads. On Firefox, the ads before the videos are blocked. However, on Safari, they still play.

JW Player: http://www.longtailvideo.com/jwpabout/?a=r&v=6.11.4923&m=f&e=a
Example: http://cinemassacre.com/2015/02/02/castlevania-rondo-of-blood-pc-engine-duo-turboduo-james-mike-mondays/

**Comment by chrisaljoudi** [comment]
Does this happen if you disable Flash? (Safari -> Preferences -> Security -> Allow Plug-Ins). Safari doesn't allow to block requests made by the Flash plugin.

However, if you disable Flash, you should get an HTML5 player in its place, which seems to work just fine (and have no ads) — including on your example.

**Comment by dibas** [comment]
I just checked the example link mentioned, uBlock blocks the ads perfectly fine with Flash disabled. Same versions of OS X, Safari and uBlock.

**Comment by ghost** [comment]
For some reason, this still does not work for me. I set flash to "Blocked" under the (Safari Preferences -> Security -> Allow Plug-Ins) and now it just says "Flash is blocked for this website." The video refuses to play until I allow Flash.

![screen shot 2015-02-06 at 3 26 56 pm](https://cloud.githubusercontent.com/assets/6693452/6087743/d2c48ad0-ae14-11e4-9c65-d0f48d4452c6.png)

**Comment by chrisaljoudi** [comment]
@vincentw8460 Disable plug-ins completely (you can also completely disable Flash, but for testing purposes disabling all plug-ins is easier).

Safari Preferences -> Security -> Uncheck Allow Plug-Ins

**Comment by ghost** [comment]
@chrisaljoudi OK yes, this works. I wasn't disabling all plug-ins, I was just blocking Flash. Those videos do play now, thanks.

**Comment by chrisaljoudi** [comment]
@vincentw8460 okay, sounds good. The thing is, it's really to your advantage to have Flash disabled — most websites will fallback to an HTML5-based player, which is more energy efficient and stable **and** will have its requests processed by µBlock.

If you absolutely, positively have to have Flash, then Safari might not be the best choice. The Safari extension API doesn't currently offer a way to intercept requests made by plugins such as Flash.

I'm glad this helped.
