### ISSUE TITLE
Could not install package on Chrome 39, Ubuntu 14.04 64b

### ISSUE THREAD

**Issue by JosefJezek** [uBlock-LLC/uBlock#711]
Could not install package: 'UTILITY_PROCESS_CRASHED_WHILE_TRYING_TO_INSTALL'. Could not install package because a utility process crashed. Try restarting chrome and trying again.

**Comment by gorhill** [comment]
You need to report this to Chromium developers: https://code.google.com/p/chromium/issues/list

Any browser crash is the responsibility of the browser developers, javascript is a scripted language, it's not supposed to crash a browser.
