### ISSUE TITLE
[Safari] Turning off uBlock for domain doesn't make the site load properly, disabling uBlock does

### ISSUE THREAD

**Issue by akaralar** [uBlock-LLC/uBlock#712]
this was discussed in #595 and marked as closed, however the issues still persist. let me explain:

although the drop down issue is gone, there were other issues on the page and they are not solved yet. for instance when you click the name of a neighbourhood normally it goes to a new page with restaurants that are serving to that neighbourhood. with ublock enabled the spinner spins constantly. screenshot: https://dl.dropboxusercontent.com/spa/6d4j003yz96ozkz/ggf5nwow.png

it is possible to select the neighbourhood from the drop down and click go, and list the restaurants. however various ui elements in that page were missing which were being loaded from images.yemeksepeti.com. i only encountered this once, and this problem faded away once i included yemeksepeti.com in whitelist. but when you make modifications to onscreen filters such as minimum serving amount, restaurant score etc the same spinner from above is encountered. so whitelisting doesn't solve that issue. screenshot: https://dl.dropboxusercontent.com/spa/6d4j003yz96ozkz/m_w70erd.png

i would be happy to share my membership credentials or anything else if it will help you debug the issue, just send me an email.

**Comment by chrisaljoudi** [comment]
I can't _quite_ reproduce the same symptoms you have, but I can see that it doesn't work.

However, it seems to also break on Chrome, as well (with µBlock enabled). Is it only occurring in Safari for you?

I'll continue to investigate nevertheless, but I'm not sure this is Safari-specific.

**Comment by chrisaljoudi** [comment]
@akaralar okay, fixed in bb9e590cb0.
