### ISSUE TITLE
Styles are not loading on livejournal without manual whitelist

### ISSUE THREAD

**Issue by extesy** [uBlock-LLC/uBlock#714]
Here's the sample url: http://zyalt.livejournal.com. Without explicitly whitelisting l-stat.livejournal.net the styles are not loading.

**Comment by chrisaljoudi** [comment]
@extesy can't reproduce using latest build here (Safari and Chrome). Whitelisting the website using the button in the popup works just fine.

What browser are you observing the issue on?

**Comment by gorhill** [comment]
I don't see any problem with the page. You need to tell me your filter lists and anything which is not stock settings.

`l-stat.livejournal.net` is not blocked on my side btw, using stock filter lists + both RU lists.

**Comment by gorhill** [comment]
Alright, you are using hpHosts I guess, it has this entry: `l-stat.livejournal.net`.

hpHosts has had a lot of false positive lately, I'm giving up on trying to make it usable by default (#17). So whoever use it, it's at their own risk, I can't provide support for 3rd-party filter lists. Report to maintainer of that filter list.

Here is a workaround meanwhile: `@@||l-stat.livejournal.net`.
