### ISSUE TITLE
ublock for opera is outdated.

### ISSUE THREAD

**Issue by blahxblah** [uBlock-LLC/uBlock#715]
ublock for Opera version is not up to date.
Please update.  :D

**Comment by gorhill** [comment]
Need a developer willing to take care of updating Opera store. I just don't have the time.

**Comment by gorhill** [comment]
Version 0.8.7.0 submitted to the Opera store.

**Comment by Havokdan** [comment]
Again!

**Comment by gorhill** [comment]
Again, coming...

**Comment by Havokdan** [comment]
Please, kindly, that the version of Opera is updated, and have a good day.
