### ISSUE TITLE
Interference with Xinha HTML editor

### ISSUE THREAD

**Issue by jhansonxi** [uBlock-LLC/uBlock#716]
The Wine AppDB uses Xinha v1263 for its HTML text editor.  When editing an empty text field with Xinha, normally the `<head>` section is empty.  With uBlock 0.8.6.0 active, additional `<style>` code is added:  

```
<html>
  <head>

    <style id="ublock-preload-1ae7a5f130fc79b4fdb8a4272d9426b5">[href^="http://www.freefilesdownloader.com/"]
{display:none !important;}</style> 
    <style id="ublock-preload-1ae7a5f130fc79b4fdb8a4272d9426b5">[href^="http://www.freefilesdownloader.com/"]
{display:none !important;}</style> 
  </head> 
  <body>All distribution forms of version 4 series. Specify exact version when submitting test results.

</body>
</html>
```

**Comment by gorhill** [comment]
I have no clue what "Wine AppDB" or "Xinha v1263" is, I can't investigate without detailed repro steps.

**Comment by jhansonxi** [comment]
Sorry.  Go to appdb.winehq.org and create an account.  Then go to this app version entry I maintain:
https://appdb.winehq.org/objectManager.php?sClass=version&iId=31438
Click the "Add test data" button located under the "Test Results" box.  Most of the text boxes in the next page use Xinha: http://trac.xinha.org/

**Comment by gorhill** [comment]
I tried to repro with Firefox, Chromium, and all the text fields are empty after I click _"Add test data"_.

**Comment by chrisaljoudi** [comment]
Tested on Safari — text fields that show up after clicking `Add test data` are all empty and initialize appropriately.

**Comment by gorhill** [comment]
@jhansonxi What are your filter lists?

**Comment by jhansonxi** [comment]
I'm using the default lists.  

I saw the result of the extra style text when I edited an entry and then submitted it.  When I saw the invalid result, I returned to the editor but didn't see anything until I switched it to raw HTML view.  That's when I found the style data.  I thought it might be malware so I did a grep of Firefox's profile data which showed the text in both Adblock and uBlock.  Adblock was disabled so I disabled uBlock and the problem disappeared (the style text wasn't added after I removed and edited the text again).  I enabled Adblock and still no problem.

I've now disabled Adblock and re-enabled uBlock but the problem isn't occurring, even after restarting Firefox.  I've had uBlock installed for about a week now and this is the first problem I've encountered.  

I noticed that I have both "Read Easily 1.0.9" and "Stylish 2.0.1" installed, mostly to allow disabling badly-designed styles.  Perhaps one or both of them is interfering.  I'll disable them and see if it happens again.

**Comment by gorhill** [comment]
Did you enter a hyperlink which URL starts with `www.free` as part of your HTML in the HTML editor?

**Comment by chrisaljoudi** [comment]
@jhansonxi still can't reproduce. Can you reproduce this with the current version?

Otherwise, we can close this issue.

**Comment by jhansonxi** [comment]
Hasn't reoccurred.
