### ISSUE TITLE
Revamp Firefox 35 Notification - Overhang Issues

### ISSUE THREAD

**Issue by Xiphoid** [uBlock-LLC/uBlock#718]
Currently, the way that the "requests blocked" notification appears on Firefox 35 is that it hangs over the toolbar barrier when the Bookmarks Toolbar is not selected. ![FF 35 Notification](https://cloud.githubusercontent.com/assets/10892810/6091016/b01347a0-ae42-11e4-8e24-3c958a228cd1.png)

If you altered it to how it appears in the Firefox Developer Edition, it would eliminate the overhang and look better in general. ![FF Dev Notification](https://cloud.githubusercontent.com/assets/10892810/6091023/f33a3e12-ae42-11e4-8687-a0e5e42ddc92.png)

**Comment by chrisaljoudi** [comment]
Dup of #545.

**Comment by ghost** [comment]
It looks like it's on the to-do list.
https://github.com/gorhill/uBlock/issues/550#issuecomment-70679251

> Implement toolbar button and pop-up with native API instead of CustomizableUI
