### ISSUE TITLE
3rd-party filters settings behavior is inconsistent

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#719]
I don't know what causes this issue, so I can't give you clear steps on how to reproduce it, but I've noticed that the settings for 3rd party filters in Firefox seems a bit messed up. I should mention that I've only been able to consistently reproduce this in Firefox, and that I haven't had this issue once in Chromium.
![oxfnaj 1](https://cloud.githubusercontent.com/assets/4343306/6091577/93117ef2-ae78-11e4-84e4-0fa24f20ac7d.png)
Using Firefox and uBlock 0.8.6.0, it looks like some filters don't get counted, even though they're being used (13 filters out of 50,000 filters), some filters are missing the options to purge the cache, and sometimes, filters say they're outdated or there's a new update available, even after clicking "Update now." (more on this below)
The negative number of filters used seems to have been introduced in 0.8.7.0.

I could just be insane, I don't know if it's just an issue with my computer, but I'm going to guess that this isn't intended.

Edit: I hope this explains the "outdated"/new update part better. Sometimes the "outdated" doesn't go away, even after updating filter lists.
https://a.pomf.se/gqtqlj.mp4

**Comment by Xylemon** [comment]
I see this too on Seamonkey.

**Comment by gorhill** [comment]
> missing/uncounted filters

This is normal, uBlock discards duplicate filters. So when a lot of filter lists are used, chances there will be duplicates which will be discarded. You have Fanboy Ultimate selected, so the figures shown are expected.

> some filters are missing the options to purge the cache

This can happen for filter lists hosted only on github/gorhill/uBlock: this means a filter list hosted only on github/gorhill/uBlock has not changed since the last shipped version, so there is no point to download and cache a copy.

> Sometimes the "outdated" doesn't go away, even after updating filter lists.

This can happen when a filter list cannot be downloaded from the remote location, for any sort of reasons: remote server down, network issues, etc. Notice that in your MP4, it was `adblockplus.org` that did not return the filter lists. So it was a remote server issue.

> negative number of filters

Weird. I will investigate. I did change some code related to counting when I fixed #665.

**Comment by gorhill** [comment]
I was able to reproduce with Firefox the negative count. Spotted where the problem is.

**Comment by ghost** [comment]
> This is normal, uBlock discards duplicate filters. So when a lot of filter lists are used, chances there will be duplicates which will be discarded. You have Fanboy Ultimate selected, so the figures shown are expected.

Oh, that's good. Sorry, I guess I should've read better.

> This can happen for filter lists hosted only on github/gorhill/uBlock: this means a filter list hosted only on github/gorhill/uBlock has not changed since the last shipped version, so there is no point to download and cache a copy.

That makes sense. Sorry about that.

> This can happen when a filter list cannot be downloaded from the remote location, for any sort of reasons: remote server down, network issues, etc. Notice that in your MP4, it was adblockplus.org that did not return the filter lists. So it was a remote server issue.

I can still access the websites/filter lists, it's just that my internet really sucks, so it takes a bit to fully download them.
![4125388123 1](https://cloud.githubusercontent.com/assets/4343306/6094419/fb2364b2-aeee-11e4-93cb-62c04fb375af.png)

**Comment by gorhill** [comment]
> it's just that my internet really sucks

Fixing issue #376 will definitely help there. I have the fix locally but I really need thorough testing etc. given auto-update is a critical feature.

The fix to auto-update will cause filter lists to be downloaded one by one in the background, with a good delay in between -- I am considering an hour -- and when they all have been downloaded, the filter lists will all be reloaded using the cached versions.
