### ISSUE TITLE
When detaching a tab, the "power button" does not work in the new window

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#72]
Windows 8.1 x64
Chrome 35.0.1916.153 m
uBlock 0.2.2.0

When detaching a tab from the browser, the uBlock power button does not work in the newly spawn window.
- Open a website in a new tab
- Detach tab from main window
- Disable/enable uBlock in the current tab with the "power button" in the new window

**Comment by ialexsilva** [comment]
Reproduced and Confirmed here...

**Comment by tailHey** [comment]
Issue also confirmed in Opera 22.0.1471.70

**Comment by gorhill** [comment]
Actually, the popup of the moved tab end up controlling whatever tab is activated in the previous window.
