### ISSUE TITLE
[Firefox] No popup menu with navigation bar disabled

### ISSUE THREAD

**Issue by nknwn** [uBlock-LLC/uBlock#720]
I'm using Firefox 35.0.1 on Win7. 
If navigation bar is disabled in Firefox, clicking the uBlock icon will not show any popup menu for it.
Any way to get the popup menu without having a navigation bar?

**Comment by elyrly** [comment]
I don't think this is possible because the Firefox Extension standard places the icon on the navigation bar for notification. Would be interested if you find another notification method on Firefox/Chrome.

**Comment by polyzen** [comment]
#549

**Comment by nknwn** [comment]
Thank you @polyzen , Pentadactyl is not supported in the newer versions of Firefox, i am using Vimperator. Using info from last post on that issue, https://github.com/gorhill/uBlock/issues/549#issuecomment-73571142, using that script with Stylish it breaks about:customize and other toolbars like StumbleUpon.

**Comment by polyzen** [comment]
@nknwn, Pentadactyl [can be used](https://code.google.com/p/dactyl/source/detail?r=59c43695e9ee09096fbfa3b2822082de749eaa52) (and works) if you use a dev build

**Comment by 1xch** [comment]
+1 
vimperator with gui=nonavigation

You can place the icon into the vimperator statusline, and numbers are shown, but no popup on click. Other icons in the statusbar do show popup on hover/click.

**Comment by singpolyma** [comment]
Another vimperator user.  I have the ublock icon on the tab bar.  I also have firebug, requestpolicy, and hello icons on that bar and they all have popups work fine, but ublock does not pop anything up when I click it.

**Comment by MoSal** [comment]
Another Vimperator user here.

I just tried Vimperator's built-in styling support to work around the bug and it seems to work. A proper fix from uBlock would be ideal, of course.

```
: style -name ublick * #nav-bar * { visibility: visible; }
```

**Comment by ewollesen** [comment]
:+1: but can confirm that the fix from @MoSal worked for me as well.

**Comment by tioteath** [comment]
> I don't think this is possible because the Firefox Extension standard places the icon on the navigation bar for notification. Would be interested if you find another notification method on Firefox/Chrome.

Could you please checkout for ghostery implementation. It seems it works pretty good in ghostery.

**Comment by AlexVallat** [comment]
Ghostery uses a legacy button API rather than the new CustomizableUI that uBlock uses. Since [0.9.4.0](https://github.com/chrisaljoudi/uBlock/releases/tag/0.9.4.0) you can have uBlock use a legacy button too by setting the `about:config` preference `extensions.ublock.forceLegacyToolbarButton` to true and restarting the browser. That should allow it to work in cases where the navigation bar has been hidden.

**Comment by akhy** [comment]
@MoSal nice workaround! it also seems to fix similar issue with another plugin's popups 

added this to my .vimperatorrc :+1:
