### ISSUE TITLE
[Firefox] uBlock 0.8.7.0-dev.5 breaks website

### ISSUE THREAD

**Issue by mawie** [uBlock-LLC/uBlock#723]
Hi,

The latest dev version (0.8.7.0-dev.5) breaks the following website: http://www.oovee.co.uk/forum/ if Fanboy’s Social Blocking List‎ is enabled. This issue does not occur with v 0.8.6.0.

**Comment by gorhill** [comment]
Good catch, thanks for this. I broke it [here](https://github.com/gorhill/uBlock/commit/7a5d09b4a2ef6cfebfa144eae92c9f8cba7ab7fe#diff-522a16ddeed280252d7c3a351261b441R1932).

**Comment by my-password-is-password** [comment]
Just installed 0.8.7.0-dev.6 and this happens.

![ublockdup](https://cloud.githubusercontent.com/assets/6408935/6095173/69860e46-af03-11e4-8921-390da5a4d162.gif)

Theres duplicates of `oovee.co.uk` if I do a refresh from within the popup.  New issue?

**Comment by gorhill** [comment]
@my-password-is-password Ugh.. side effect of removing the `all` row, forgot to fix the point at which all the non-static rows are removed.
