### ISSUE TITLE
Is there a blocked elements list and a feature to disable single filters from 3rd-party lists? Or will it be?

### ISSUE THREAD

**Issue by lebedev** [uBlock-LLC/uBlock#726]
On a certain site uBlock blocks (or hides, whatever) elements I don't want it to block. So I want to know what filter is responsible and disable it.
Now my options are: disable uBlock for the entire site, whitelist the entire site or disable filter list. That's not an options.

**Comment by gorhill** [comment]
Dup of #68.

**Comment by gorhill** [comment]
> disable uBlock for the entire site, whitelist the entire site or disable filter list

In the mean time, dynamic filtering can also [help to un-break sites](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide#important-3).

**Comment by lebedev** [comment]
> dynamic filtering can also help to un-break sites.

That helped, thanks.

And, btw, has anyone proposed to add hints to that popup? Like this: ![](http://i.imgur.com/XdpgVEq.png)
I think that would be helpful.

**Comment by gorhill** [comment]
[Advanced user features](https://github.com/gorhill/uBlock/wiki/Advanced-user-features):

> [...] advanced users are expected to read the documentation [...] Tool tips are useful for novice users, but can become annoying to advanced users. Tool tips are turned off for advanced users.

Believe me, once you know green is "allow", the tooltip will become very annoying. Reading the [quick guide](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide) once, and tooltip won't be needed.

Surely the doc can be improved a lot, but that's a long term thing.

**Comment by lebedev** [comment]
Got it. I have no more questions.
