### ISSUE TITLE
Bring the `all` row back

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#727]
> I removed the all row in c9ef306.
> 
> It's just the UI counterpart I removed, \* \* \* [allow|block|noop] is still supported.
> 
> The thinking is that the all row is very unlikely to be used by anyone: it makes little sense to block all, and for the blacklist mode, the rule \* \* \* allow can be added manually, and once this is done, clicking the local setting of the 3rd-party row and the current site row will effectively engage static filtering for the current site.
> 
> The vertical space is precious and limited, so I decided to remove the all row given that it's very unlikely anyone will use it.

Some feedback following this change:

> @anonish why remove it? at least make it optional, that was literally my favorite thing about this new version ;_;

and 

> @BenjaminProgram I used it a lot.

I want the case to be made about why it is deemed so useful.

Blocking the `all` cell in all likeliness completely breaks a web page, as even 1st-party resources are blocked. For someone wanting that kind of extreme control, uMatrix is better suited.

**Comment by anonish** [comment]
unless i'm mistaken, umatrix is not available in firefox? i can live with adding the rule manually, but the ui consistency was nice. i get that ui space is limited, would scrolling overflow not resolve this, as well as the glitchy UI in firefox?

**Comment by gorhill** [comment]
@anonish Use cases? I really want to understand why the `all` row is useful to you.

**Comment by gorhill** [comment]
Look what happens if I don't force the height of the popup to be that of the height of the basic pane:

![c](https://cloud.githubusercontent.com/assets/585534/6096930/c28be2a4-af76-11e4-9fd2-5afa2b8f871f.png)

That's for Chromium, on Firefox it's even worst, it becomes even more than glitchy, it becomes unusable:

![a](https://cloud.githubusercontent.com/assets/585534/6096935/0d9e5268-af77-11e4-82bb-ed684defdc20.png)

So having a freely vertically-resized popup is not an option, the left-most pane (dynamic filtering) has to be forced to be the same height as the right-most pane to fix all these issues. So back to the previous vertical space being limited, and why the `all` row is really needed. I am still open to be convinced with good arguments.

**Comment by anonish** [comment]
I see what you mean... would having a max-height/max-width with overflow not correct that? as far as a convincing argument, I really have none other than max control as you put it elsewhere.  I tend to block by defautl (as in noscript/RP allow none) and then work my way up in allowing a site.  I know for most users this is way too much work, so leaving the option available as a rule is good enough.   

I take it that the UI glitchiness is a beast unto itself, and would rather have the working UI than the added rule

**Comment by gorhill** [comment]
> block by defautl (as in noscript/RP allow none)

Alright. I have a bias that makes me more sympathetic to people who block all by default than allow all by default (the latter would need to work me more to convince me). I will add the `all` row back, I might just make it a bit less high than other rows.

**Comment by alejandrolemus** [comment]
Maybe something like this? Please ignore my lack of artistic skills with MS Paint, it's just to illustrate a point. 

![blockuntitled](https://cloud.githubusercontent.com/assets/9505902/6097413/26ac1394-af8b-11e4-9b85-7a490e456a1a.png)

**Comment by gorhill** [comment]
@alejandrolemus The `all` row is back, there is no need for anything more.

**Comment by gorhill** [comment]
@alejandrolemus Actually, looking at your screenshot, why are the cells in the `all` row set to `noop`?

**Comment by alejandrolemus** [comment]
I like to play with options :D 
For me that would be the same as no dynamic filtering. I put it like that when my wife asks me to use the browser for some quick tasks. Otherwise I need to be around to 'unbroke' each page.
That's why I would like some 'quick' switch, I know sharing the browser or session is not ideal, but it's practical in MY everyday life. 
My other half doesn't care or know about internet privacy, but I still would like some level of uBlocking for her.

**Comment by gorhill** [comment]
> that would be the same as no dynamic filtering

But by default there is no dynamic filtering. There is no point applying `noop` to the `all` cells. If there is no `allow` or `block` for these cells, they are implicitly `noop`. The only purpose of `noop` is to cancel an `allow` or `block` inherited from a broader cell, but nothing is broader than `all`.

**Comment by alejandrolemus** [comment]
Your answer came when I was editing my previous. I see what you mean, but I do use block rules for 3rd party frames and scripts, and since there is no global switch, I play to see what happens.

Edit: in that screenshot I obviously forgot to revert those cells to default.

**Comment by alejandrolemus** [comment]
Usually is like this:

![ublock](https://cloud.githubusercontent.com/assets/9505902/6097790/29b4a094-af98-11e4-99b2-ce6bd3d801b4.png)

Then I would do the "all noop" for her. Once she is done, I revert to this.
Hope that is not too confusing

**Comment by gorhill** [comment]
> Then I would do the "all noop" for her

Never mind, not that important. I just wished it was completely understood, as the more people understands it completely, the more they can help others understand it completely -- and this relieve me of having to be the one only who can explain it. To set the `all` cells to `noop` is a symptom of not understanding it completely. There is no harm in doing so, it's just pointless.

**Comment by alejandrolemus** [comment]
Well, I guess is back to RTFM to me, then :(

**Comment by gorhill** [comment]
> back to RTFM

No. Just ask yourself a question: "What does applying `noop` to the 'all' cells do?" Tell me what you think it does.

**Comment by alejandrolemus** [comment]
It was my understanding that it would completely bypass the dynamic filtering and <strike>apply only the rules</strike> block whatever as per chosen lists (EasyList, etc).
For instance, if I <code>noop</code> the global 'all', none of the global <code>block</code> rules (3rd party scripts and frames in my case) would then apply anymore.

**Comment by alejandrolemus** [comment]
I was reading your much improved explanation on this subject, and I think I get it now: I can <code>noop</code> something inherited, not try to force a <code>noop</code> to propagate to narrower scopes. Is that correct?

**Comment by gorhill** [comment]
> I can <code>noop</code> something inherited, not try to force a <code>noop</code> to propagate to narrower scopes

Exactly.

If you want to disable dynamic filtering when your wife uses the browser, best is just to un-check _"I am an advanced user"_, this disable completely dynamic filtering, returning uBlock to a mere ABP-like blocker.

**Comment by alejandrolemus** [comment]
> Exactly.

Finally! I'm just a lazy reader, not a complete moron :) Oh, and thanks for the time you took to educate me!

> best is just to un-check "I am an advanced user"

Too many clicks... sighs. Since there is no point for a <code>noop</code> in the "global all" cell, can you make it a shortcut for this? Or at least a quick switch somewhere in the popup? I know it's me been lazy again, that you have too much work already, and that you don't want more clutter in the popup, but that would be my pet request for uBlock.

**Comment by gorhill** [comment]
Well given the pic you shower early, just noop'ing the 3rd-party scripts/frames works to, it's actually what you were doing.

**Comment by gorhill** [comment]
Given the pic of your settings, just noop-ing 3rd-party scripts/frames is fine also. The whole point was just that noop-ing the global `all` cell was not needed.

**Comment by alejandrolemus** [comment]
Will do it like that for now. But I know that when uBlock matures, you will improve the UI in your spare time, eventually :D

**Comment by gorhill** [comment]
> I can noop something inherited, not try to force a noop to propagate to narrower scopes

I said "Exactly" earlier, but the right answer is "That's right, rules (inlucing `noop`) from a broader scope cannot override rules from narrower scopes". So the `noop` of the `all` scope **will propagate** down to narrower scopes for where there are no rules set, but it **will not override** when narrower scopes have a rule set.

**Comment by anonish** [comment]
thanks for bringing the "all" row back, browsing so much faster with "all" in red :dancers:
