### ISSUE TITLE
Implement uBlock for K-Meleon

### ISSUE THREAD

**Issue by Tnebi** [uBlock-LLC/uBlock#728]
Hi there. Is there any chance to see uBlock implemented for KMeleon? It is a nice browser and it uses firefox .xpi files but your extension seems to need some tweaks to get working. So I am asking you if you can create one for K-Meleon :) Here's the thread where we were trying to install uBlock http://kmeleon.sourceforge.net/forum/read.php?9,131872

**Comment by gorhill** [comment]
The way I see it given how little time I have left (none), is: one browser, one developer.

**Comment by Tnebi** [comment]
Ok :s. Thanks anyways for the fast reply... It was just a problem with the ublock.sqlite file but I understand you have no time ^^
