### ISSUE TITLE
Regarding default deny and lists…

### ISSUE THREAD

**Issue by wolftune** [uBlock-LLC/uBlock#729]
Can default deny work _with_ the block lists? Because I'd use a default-deny function only if I can test unblocking a request and then still have it blocked because it is in the block lists.

Today, using Request Policy _and_ uBlock, I can test things to see what unbreaks a website in Request Policy without worrying that something known to be invasive will go through because uBlock will still block it if Request Policy doesn't. I would only want to replace Request Policy with the uBlock feature if they worked hand-in-hand in this fashion…

**Comment by gorhill** [comment]
[Advanced user features](https://github.com/gorhill/uBlock/wiki/Advanced-user-features):

> advanced users are expected to read the documentation

[Dynamic filtering: quick guide](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide):

> Remember that `noop` rules bypass only broader dynamic filtering rules, static filtering is left completely intact

**Comment by wolftune** [comment]
thanks, will read thoroughly now. Sorry
