### ISSUE TITLE
[Firefox] Popup issues

### ISSUE THREAD

**Issue by quo** [uBlock-LLC/uBlock#730]
When I try to open the popup, with the dynamic filtering matrix enabled, it usually looks like this:

![ublock1](https://cloud.githubusercontent.com/assets/994915/6098179/f245af6a-afd6-11e4-95cc-3209cebe17ab.png)

Without the filtering matrix, it is cut off on the right side:

![ublock2](https://cloud.githubusercontent.com/assets/994915/6098183/33d92f1a-afd7-11e4-8d91-f22da00f1136.png)

It's probably the same issue. It looks like a race condition; every once in a while it'll open correctly (both with and without filtering matrix).

This is with 0.8.7.0-dev.8, it worked fine with 0.8.6.

There is also an annoying 'flickering' of the filtering matrix when you open the popup. This happens in 0.8.6 as well.

**Comment by chrisaljoudi** [comment]
Can't reproduce either issue on Firefox 35.0.1 (OS X) with latest µBlock (0.8.7.0-dev.8).

**Comment by ghost** [comment]
The advanced matrix is glitching here as well.  Happens when the matrix is left extended '+' and appears on subsequent toolbar reopenings, where the page is refreshed or browsing to a new page. 

Setting the filtering matrix back to '-' allows the toolbar pop up to display normally here.

Firefox 35.0.1 32 bit, Mint Mate 17.01 64 bit, µBlock 0.8.7.0-dev.8

Edit: no ui issues here with 0.8.6.0

**Comment by mquandalle** [comment]
I also encounter the same issue on Firefox developer edition (v37a) on ubuntu 14.10.

**Comment by chrisaljoudi** [comment]
From the screenshots you showed, this looks like a Firefox or window manager rendering bug more than anything else.

If you look at this:

![](https://cloud.githubusercontent.com/assets/994915/6098179/f245af6a-afd6-11e4-95cc-3209cebe17ab.png)

If you overlay the actual popup's size, it fits well with the partial popup you showed in your screenshot. Take a look:

![](http://chrisly.me/image/0Y2l3l1V412A/fits.png)

Ignore the typeface (looks like you're defaulting to ubuntu, maybe?), you can see that the **widths** (which aren't dependent on the typeface) seem to match.

---

Can anyone who's running Firefox on Windows/OS X reproduce this? I've been unable to reproduce on OS X, and the combination of all the above (plus the fact that all reports have been from Linux so far) makes me think it might be Firefox-on-Linux-specific.

**Comment by gorhill** [comment]
Yes, a Firefox issue, I have it all the time the first time I bring the popup. Not sure what can be done, if anything. @Deathamns should have better insights about the issue.

**Comment by gorhill** [comment]
The glitching is definitely an issue, but about the flickering, I doubt anything can be done. It's also present on Chromium, and I spent so much time earlier in the design of the dynamic filtering pane to get rid of it, I gave up in the end. No amount of CSS I threw at this would make any difference.

**Comment by chrisaljoudi** [comment]
@gorhill out of curiosity, would you mind sharing a minimal test case to reproduce the flickering?

**Comment by gorhill** [comment]
> minimal test case to reproduce the flickering

Toggle on/off the dynamic filtering pane.

**Comment by chrisaljoudi** [comment]
@gorhill hmm, am I doing the right thing here? http://chrisly.me/3q0c3F100F3O

If so, it doesn't seem like the flicker is happening — or am I not noticing it?

**Comment by gorhill** [comment]
@chrisaljoudi Yes, it looks clean. So it's a non-Safari problem, or a linux problem, to be determined.

**Comment by chrisaljoudi** [comment]
@gorhill 

> it's a non-Safari problem

I'm sorry I'm talking so much, but the screen recording is of Chrome on OS X. Sorry I didn't make that clear.

I'll try and test in Chrome on Windows to see (if it works on Windows but not on Linux, then it's likely a Linux-only problem for both Chrome and Firefox).

**Comment by ozar** [comment]
Like gorhill describes above, I get this issue in Firefox 35.0.1 right after it first starts and it happens on my Linux and Windows boxes.  It's usually fine after the first broken uBlock popup.  This has been an issue with all versions of uBlock that I've tried.
- Edit:  I just noticed that I am not having this issue with version 0.8.7.0 when in Firefox 35.0.1 and running Windows.  uBlock's popup window seems to be opening fine every time.

**Comment by my-password-is-password** [comment]
Tried on FF 33 on Windows XP and I see the flicker.  

Collapsing the dynamic filtering matrix shifts everthting to the left then the popup resizes to the smaller size.
![ublockpopupglitch](https://cloud.githubusercontent.com/assets/6408935/6098982/dc699ec4-afa2-11e4-9308-3b066ef956df.gif)

Video:
http://uux3.altervista.org/uBlockPopup.webm

**Comment by alejandrolemus** [comment]
Firefox 35.0.1 on Windows 7. This started after updating to 0.8.7.0 (final):

![df](https://cloud.githubusercontent.com/assets/9505902/6111502/3f7d2404-b057-11e4-8c6f-7a433980d971.png)

![df1](https://cloud.githubusercontent.com/assets/9505902/6111547/be825224-b057-11e4-9fed-b6c78c5aa42f.png)

Edit: a browser restart solved the issue, will report if it comes back.

**Comment by jschuck** [comment]
For me it's the same with version 0.8.7.0 on Firefox 35.0.1, on Archlinux with kernel 3.18.6-1-ARCH, x86_64.

I downgraded to 0.8.6.0 for the time being.

**Comment by ghost** [comment]
No popup issue here with uBlock 0.8.7.0 Final on Firefox 35.0.1 / Win7 x64 (never had any with previous uBlock 0.8.6.0 either).

**Comment by ghost** [comment]
With 0.8.7.1-dev.2 the advanced panel glitch is gone here. That is to say, it is working great.

Mint 17.01 64 bit; Firefox 35.0.1 32 bit

Edit: Dang, rebooted the browser and the glitch came back. sadpanda.jpg

**Comment by gorhill** [comment]
Someone posted a video of the glitch (in the Chrome store's feedback section), It looks more severe than what I get (I get the glitch only once):

https://vid.me/SK2e

(You will need to noop `d1wst0behutosd.cloudfront.net` if you use default-deny).

**Comment by ghost** [comment]
did fix; can confirm \o/

**Comment by jschuck** [comment]
Here too. Thanks.

**Comment by rodalpho** [comment]
Note this does not fix issue https://github.com/gorhill/uBlock/issues/505 .
