### ISSUE TITLE
inline scripts no being properly blocked (in firefox)

### ISSUE THREAD

**Issue by louiz** [uBlock-LLC/uBlock#733]
In firefox 35.0.1, with uBlock 0.8.7.0, blocking inline scripts does not seem to work for me.

For example on this page http://www.smbc-comics.com/index.php press the key “x”, and this will load a random comic. This feature is done using the inline javascript that start line 35 of HTML.
I’m using these settings: ![custom filters](http://pix.louiz.org/o/Ddibx.png)
With those, I would think that this script would be blocked and these keyboard features would be disabled, but in fact it doesn’t.

**Comment by gorhill** [comment]
Works as expected: the inline script tags are blocked when the page is loaded. If you toggle inline script tags, the page needs to reload for the rule to take effect.

**Comment by louiz** [comment]
It doesn’t work as expected with me.

The scripts are not blocked when I join suck a page for the first time (even if the inline scripts are already blocked for this site, in the dynamic filters, as shown in my previous screenshot, before I open that page).

But then, on the next page reload (without changing any filter), they are correctly blocked.

I simply reproduce like that:
- Configure dynamic filters like in my screenshot, for www.smbc-comics.com/
- Enter in the URL bar: http://www.smbc-comics.com/index.php?db=comics&id=3650
- Hit Alt+enter to open in a new tab
- Press 'x' -> the page reload a random comic (it should not)
- Reload the page with ctrl+shift+r
- Press 'x' -> nothing happens, as it should.

**Comment by louiz** [comment]
Oh, I think I have something important: apparently scripts are not blocked if the page is loaded in a new tab. If you however open a tab, load google.fr in it, then enter http://www.smbc-comics.com/index.php?db=comics&id=3650 in the address bar, hit enter, then the scripts are correctly blocked in that page.

**Comment by gorhill** [comment]
Yes, looks like #531.

**Comment by louiz** [comment]
Ok, if it’s already known, I’ll just wait for a fix of #531, thank you.
