### ISSUE TITLE
Safari can't install uBlock 0.8.7.0.

### ISSUE THREAD

**Issue by fletom** [uBlock-LLC/uBlock#735]
Received this out of the blue (presumably when uBlock tried to auto-update itself).

Also tried to download the new version from https://chrismatic.io/ublock/ and got the same error.
![screen shot 2015-02-08 at 10 53 17 pm](https://cloud.githubusercontent.com/assets/127497/6100824/75646e6e-afe5-11e4-8a04-c034eafaf021.png)

**Comment by chrisaljoudi** [comment]
@fletom is this still occurring? I think the server might've been failing to deliver the file because so many people were downloading at once.

I'll use a different method of delivery next time, but for now let me know if it's been resolved.

**Comment by fletom** [comment]
Yep. Still occurring. The download from your website completes successfully (and did the first time too), but I get the above error when opening the `.safariextz` and clicking "Install".

It also occurs if I try to manually install the update from Safari preferences:

![screen shot 2015-02-09 at 12 40 32 am](https://cloud.githubusercontent.com/assets/127497/6101569/4d46b5d6-aff4-11e4-964b-d3e5f5eac88c.png)

**Comment by chrisaljoudi** [comment]
@fletom been trying to reproduce for the last 20 minutes; haven't been able to.

Would you mind trying out the following?
- Uninstall µBlock
- Quit Safari (⌘ + q)
- Relaunch Safari
- Try to install µBlock (using the file from https://chrismatic.io/ublock)

I appreciate your patience, and sorry for the inconvenience.

**Comment by ghost** [comment]
I've been having the same issue, except that I didn't see any error alert. 
I couldn't manually install the update, either. It simply gave no response.
However, after trying the solution mentioned above, it is now solved already.

Safari 8.0.3

**Comment by ghost** [comment]
I too am noticing this error with new releases. It seems to occur most often when Safari has been running for a few days. Once the error has shown once, it would always fail to install as long as Safari is not restarted. As a workaround, restarting Safari would allow the installation to succeed.

I don't know what triggers the error. There don't appear to be any messages logged in Console.app related to this error.

I'm not noticing this error with other extensions, although those are not updated as frequently as µBlock is.

**Comment by mike-to-spec** [comment]
Just to let you guys know, this isn't an issue with the extension but rather than Safari. I've seen this many times in the past via various extensions including 1Password, Ghostery (_stopped using it of course for uBlock_), etc. 

It tends to happen more often if you leave Safari running for a long time like zr40 mentioned. A simple restart of Safari fixes this.

**Comment by ghost** [comment]
@MikhailTNY I tried restarting Safari and reinstalling the extension for several times before I finally solved it by using the new link mentioned above. And my former attempts didn't help actually....
Also, if I didn't turn off the automatic install of extension updates in Safari, the update of the 3rd-party filter would stick and the whole extension refused to work.
So maybe it's a different issue?

**Comment by fletom** [comment]
I can confirm that restarting Safari allowed the extension to be updated from Safari's preferences.

It could be a Safari bug, but I have never seen the same error messages from my other extensions (e.g. Reddit Enhancement Suite which updates all the time). I rarely close Safari.

**Comment by chrisaljoudi** [comment]
This is a Safari issue — working on it with Apple via a Technical Support Incident. It occurs with other extensions in certain scenarios, so I'm closing this.

**Comment by fletom** [comment]
Thanks @chrisaljoudi!
