### ISSUE TITLE
Popup height is too small

### ISSUE THREAD

**Issue by kirill9000** [uBlock-LLC/uBlock#737]
Hi.

I really like the dynamic filtering feature, but constant scrolling of tiny popup is very tedious, especially for sites that make lots of cross-domain requests. Please increase maximum popup height to match browser window's height.

Thanks!

**Comment by gorhill** [comment]
Dup of #658.

Also, not that obvious: https://github.com/gorhill/uBlock/issues/727#issuecomment-73413745
