### ISSUE TITLE
[Safari] 3rd party block would include installed extension's scripts

### ISSUE THREAD

**Issue by mike-to-spec** [uBlock-LLC/uBlock#738]
I don't think this is intentional but in Safari, if you block _3rd party_ in uBlock, it also blocks the scripts from the installed extensions. For an example, _honestbleeps.redditenhancementsuite-63dt2c85z6_ and _com.honestbleeps.redditenhancementsuite-63dt2c85z6_ are blocked by uBlock. This is the Reddit Enchancement Suite extension for Safari. 

It would be nice if uBlock ignore or put the extensions in its own category next to 3rd party. 

If it is not possible, no big deal. I can noop it globally but others might not know how to do this properly.

**Comment by gorhill** [comment]
> It would be nice if uBlock ignore or put the extensions in its own category next to 3rd party

Looks to me that what you report is very Safari-specific, and I certainly do not intend to hard-code exceptions for specific browsers. I haven't seen this behavior in other browsers.

Even if I agreed for an exception, I don't see it as possible, uBlock doesn't have any special knowledge that `honestbleeps.redditenhancementsuite-63dt2c85z6` is from "an extension": it certainly looks like a weird hostname, but it still a valid hostname, and uBlock won't starts to second-guess whether a hostname needs special treatment.

The solution is simply to allow (green) `honestbleeps.redditenhancementsuite-63dt2c85z6` by default, i.e. globally (the first column).

**Comment by harshanvn** [comment]
Or I believe, it can be whitelisted as part of behind-the-scene tab. I do not have safari. I am just pitching..
