### ISSUE TITLE
Dynamic Filtering (Default Deny) - Images not able to unblock using Image cell

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#739]
I have set up default deny with 0.8.7.0 in Firefox. 

<pre>
 * * 3p block
 * * 3p-frame block
</pre>

At this (https://github.com/gorhill/uBlock) home page, i see all the images are blocked by default, as expected. However adding a noop rule to local image cell, i see images are still blocked.

<code>
github.com \* image noop
</code>

Looking at the above rule, it created behind the scenes, looks like it is working as expected. However from UI perspective, i am assuming when one clicks noop for image (<b>which is party free</b>), it should unblock the images.

Not sure if my assumption is correct. If this is not an issue and working as expected, you can close the issue as invalid :)

**Comment by gorhill** [comment]
If the UI does not support it, it won't be supported maunally either (or behavior is undefined). You can't block images for a specific hostname in the UI.

Bottom-line, I don't plan to turn uBlock into uMatrix.

**Comment by gorhill** [comment]
Re-reading...

**Comment by gorhill** [comment]
Ok... [Remember?](https://github.com/gorhill/uBlock/issues/707)

See: [Dynamic filtering: precedence](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-precedence).

If you want higher granularity, there is uMatrix (I do not intend to turn uBlock into uMatrix).

**Comment by harshanvn** [comment]
> Ok... Remember?

Yes, this is what allowed me to raise the issue. I thought noop rule will be in effect for image cell, since it was party free. I wasn't aware of the precedence logic before.. 

However, after going through the precedence page in the wiki now. It tells, party aware has higher precedence over generic cells. like the example you have given -
<code> 3rd-party override images </code>

I am all set now. Once uMatrix comes to Firefox, i will use it instead of dynamic filtering.

**Comment by gorhill** [comment]
The `noop` rule is to turn a cell back to the equivalent of "no dynamic rule set for this cell".

When the image cell has no rule, 3rd-party images are blocked if `3p` is block.

Setting the image cell with a specific `noop` is to force it to not have any rule, but the precedence logic of rule processing stays the same, or else it is as if you are asking `images` without rule to not be blocked when `3p` is block, which of course is not something we want.

**Comment by harshanvn** [comment]
> but the precedence logic of rule processing stays the same, or else it is as if you are asking images without rule to not be blocked when 3p is block, which of course is not something we want.

Yes, Definitely not some thing we want. When taking precedence into the picture, i see what i was asking for, which is not reasonable.

However, i think, i will continue to use 3p script & 3p frames blocking vs 3p cell blocking. I am yet to assess which is better.

**Comment by gorhill** [comment]
Not wanting to block all images when `3p` is in block mode defeats the purpose of default-deny. What's the point of blocking all 3rd parties if each one of these 3rd parties could actually just embed a 1-pixel image in the web page so that a network request reaches all of them. In uBlock, allowing all images is a contradiction in default-deny mode. Might as well just disengage default-deny.

It's allowed in uMatrix because you do whatever you want in uMatrix.
