### ISSUE TITLE
Domain names are not always shown in uBlock .8.7.0 and a few ideas for My Rules page

### ISSUE THREAD

**Issue by mike-to-spec** [uBlock-LLC/uBlock#740]
On this github page, I had to allow several addresses to get the avatars and screenshots to show up and I kept thinking, there was an easier way before by allowing the main domain. Here's a screenshot: ![](http://miket.d.pr/15wdk/1MahRmxT.png)

Could uBlock try to list the domain name if it sees subdomain on the list?

Yes, I could just go to the uBlock's My Rules page and manually create the rule for the main domain. That works just as well, I was thinking uBlock might be easier to use if we can do this from the main view. 

A few other ideas for the My Rules page: 
1. It should have some AI to detect patterns to ask users if they want to collapse several subdomains into a domain filter. 
2. It should also sort the list by domain, then subdomain.

**Comment by ghost** [comment]
This would be very helpful.

**Comment by gorhill** [comment]
> Could uBlock try to list the domain name if it sees subdomain on the list?

It's actually exactly what it does.

Found in the [Public Suffix List](https://publicsuffix.org/):

```
// GitHub, Inc.
// Submitted by Ben Toews <btoews@github.com> 2014-02-06
github.io
githubusercontent.com
```

**Comment by harshanvn** [comment]
> It's actually exactly what it does.

hmm..then why is githubusercontent.com is not listed in mini matrix UI for this page. Or am i reading something wrong?

**Comment by gorhill** [comment]
> am i reading something wrong

Yes. Read carefully information at provided link.

**Comment by gorhill** [comment]
Bottom-line: asking me to treat `githubusercontent.com` as a domain is like asking me to treat `co.uk` as a domain.

**Comment by harshanvn** [comment]
Yup. Got it.
