### ISSUE TITLE
Safari 7.1.3 crashes can't open safari

### ISSUE THREAD

**Issue by balleinmebuik** [uBlock-LLC/uBlock#743]
I downloaded the newest version of uBlock for safari. 
Only when I downloaded it and installed it I found out that I won't work with versions earlier than 8.
Now every time when I try to launch safari it crashes.
What can I do to remove uBlock and use safari again?

**Comment by gorhill** [comment]
> Safari 7.1.3

[Installation / Safari](https://github.com/gorhill/uBlock#safari):

> There are currently no plans to support older versions of Safari. It's not recommended that you install µBlock on them (do it at your own risk).

**Comment by gorhill** [comment]
Dup of #593.

**Comment by Starefossen** [comment]
This should at least be detected, and not crashing my browser every time when I start it!

**Comment by chrisaljoudi** [comment]
@Starefossen It can't be checked — we would've done that, but µBlock never gets to even run. It crashes as soon as it's installed.

Working with Apple to see what the problem is (it's a Safari bug).

**Comment by Starefossen** [comment]
Ok, thanks a lot. I apologise for the rant if this is outside of µBlock's control :)

**Comment by gitguys** [comment]
This needs to be pulled from apple's extensions page ASAP.  I can't believe it's still even up there right now.  Pull it down now.
