### ISSUE TITLE
Power button should not be green

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#745]
Green may lead to confusion, especially when the dynamic filtering pane is opened.

In the dynamic filtering pane, green means "do not block network requests". So having the master switch colored green leads to confusion. Coloring the master switch black solves this: it's unambiguous.

**Comment by chrisaljoudi** [comment]
@gorhill I think you're absolutely right that green might be confusing, however, I'm worried black would be just as confusing in some cases.

Black, as a color, is typically "off" in all various contexts users are familiar with. It's almost never used to imply that something is activated. Then you have the translucent version of the button that's lighter (when the site is whitelisted):

<img src="https://cloud.githubusercontent.com/assets/2351359/6114646/cfef4ada-b05c-11e4-96c5-078c07d553cb.png" height=250> <img src="https://cloud.githubusercontent.com/assets/2351359/6114649/d2825f8a-b05c-11e4-9e2e-6cb8f7603437.png" height=250>

In my own, humble opinion, that's not visually intuitive which one is which.

---

As an alternate idea, perhaps something along these lines would work? (Quite different):

<img src="https://cloud.githubusercontent.com/assets/2351359/6114920/ed6707b8-b05e-11e4-8b7a-28dcd807ed68.png" height=250> <img src="https://cloud.githubusercontent.com/assets/2351359/6114926/f5660874-b05e-11e4-943b-c20042c24d74.png" height=150>

**Comment by Mikey1993** [comment]
@chrisaljoudi - I am backing you. Black is OFF universally no matter which varient is used, so you can expect more issues like #746 popping.

I think adding a "Whitelisted Page" / "This Page Is Whitelisted" text in bold and bright green color below the power button can help a lot better than switching to the black color.

**Comment by chrisaljoudi** [comment]
@Mikey1993 :+1: 

@gorhill on another note, black does look a bit... stark/dead. It doesn't feel like µBlock is "alive" if you know what I mean.

**Comment by gorhill** [comment]
> It doesn't feel like µBlock is "alive"

This matches my personality..

**Comment by gorhill** [comment]
I don't like uBlock's logo to the point of using it as a gigantic button. I am more fond of sober-looking UI, that get the job done instead of trying to be the center of attention.

**Comment by gorhill** [comment]
How about blue then? Green and red are no go. There are a lot of blue LED power buttons nowadays.

**Comment by Mikey1993** [comment]
I still don't think the color should be changed, because as you have stated many times before, people who use the Dynamic Filtering consider themselves as advanced users, who should read the wiki.
If the wiki says that clikcing the big **green** power button does X, it should do X.

This is why I think there is only need for an enchancement to alert the user about the state of the page by some text below the power button in the relative color to the state of the current **page** (no need to be aware of whole site whitelists? I think this is a benefit programmably, but I could be wrong in my assumptions), and not change the colors for the **whole user base** of uBlock, who can get confused a lot more than advanced users who previously enabled Dynamic Filtering and seeing red/green/gray a lot in their popup.

**Comment by chrisaljoudi** [comment]
@gorhill as a fallback, I think blue is fine — `deepskyblue` is a nice blue.

**Comment by gorhill** [comment]
I went with 450nm blue, the wavelength emitted by [blue LED](http://en.wikipedia.org/wiki/Light-emitting_diode#Ultraviolet_and_blue_LEDs) (see similarity with picture). An [online wavelength to RGB converter](http://academo.org/demos/wavelength-to-colour-relationship/) was used. This remove subjectivity from the process of choosing a color.

**Comment by chrisaljoudi** [comment]
@gorhill that looks great — I hadn't seen the commit when I posted my previous comment. The blue you choose works well.

Sorry if it appeared like I was second-questioning the blue choice. :P

**Comment by tjharman** [comment]
Excellent choice of colour, the new button looks great.
