### ISSUE TITLE
Block 3rd-party inneficient on clipconverter.cc

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#746]
Is it because of the .cc I have no idea, but having set block 3rd-party works perfectly except when I ran into clipconverter.cc

As you can see on the screenshot, 3rd-party is set on but clipconverter.cc connects to all sites -- even those I've "blacklisted" ...

http://img11.hostingpics.net/pics/240246ClipConverter.jpg

uBlock 0.8.7.0 on Firefox 35.01 / Windows 7 x64

**Comment by gorhill** [comment]
I can see you turned off uBlock for the site.

**Comment by ghost** [comment]
I haven't turned out uBlock for any site. Here's the list of my rules : http://pastebin.com/Yzu303gq

**Comment by gorhill** [comment]
> I haven't turned out uBlock for any site

![a](https://cloud.githubusercontent.com/assets/585534/6110807/58c44b72-b052-11e4-966e-1357935e3b4e.png)

Check what is in your whitelist if you haven't turned off uBlock for the site. Something in there matches the site's URL.

**Comment by ghost** [comment]
Terribly soorry, I goofed ... www.clipconverter.cc landed in my Whitelist, unintentionally. I mistaked somewhere inadvertently. Still learning this little gem!
Sorry for the bother : mea culpa (3 times!)

**Comment by gorhill** [comment]
You have your answer right there: `www.clipconverter.cc`. So you turned off uBlock for the site.

**Comment by ghost** [comment]
OK - Gosh, you know your application by heart -- Thanks -

**Comment by gorhill** [comment]
> you know your application by heart

Well the visual for the master switch made it obvious: if it's pale gray, this means uBlock is turned off for the site. ("turned off" = site is whitelisted).

**Comment by ghost** [comment]
Everything is perfectly logical and excellently organized. The brain-switch for the color is a bit slow to be fully, automaticaly activated here (and colors and I are not true friends). But I'm making it, just a matter of getting everything together in real-time.

One time I had AdblockPlus and RequestPolicy, then AdblockPlus and Policeman. Now uBlock does it all, which is not an arrogant comment on other applications, but uBlock does it all. This is really very nice, fast, low on RAM (Firefox here, without the Chrome popup ram problem), easy to set. I don't want to flatter the developer but only to express admiration.

**Comment by gorhill** [comment]
> The brain-switch for the color is a bit slow to be fully, automaticaly activated here

This will be fixed in next release: #745. Green is not a good choice here given how green is used in the dynamic filtering pane.

**Comment by ghost** [comment]
As far as I'm concerned it's more a problem of remembering and having that automatic notice of color->event relationship, but for those used to establishing a color relationship based on their experience then perhaps can we consider color symbols going further than the traditional green-yellow-red. But I think that a universality of color symbols is hard to meet unanimity when it goes further that the former three. You cannot please everyone. That said perhaps as always is there space for improvement but, concerning colors, hard to improve often. As a lite color-blind (though that didn't interfere in this post's story), the only thing I search for concerning colors is a "strong difference", no pastel (an application is not meant to be art!), bright colors -- or -- strongly differentiated shades (of gray ot of whatever other tone!).

End of speech -
