### ISSUE TITLE
Reload button on the popup isn't disappearing on internal pages

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#748]
For example, when entering `chrome://flags` on Chrome, and changing a Dynamic Filtering rule, the reload button on the popup isn't dispappearing after clicking it (though it does reload the page).
- Note 1: On FF Nightly, tested with `about:memory` page - same results.
- Note 2: The Element Picker icon isn't shown on the popup for for that page, is this derived from the same origin in the code?

**Comment by gorhill** [comment]
Element picker is not allowed to work on anything else than `http`/`https` web pages.

**Comment by chrisaljoudi** [comment]
@gorhill @Mikey1993 the problem with `chrome://flags` and `about:memory` is that an actual net request never occurs for their mainframes. 

As such, `logRequest` never gets called and the `pageStore` doesn't get a `contentLastModified` which is necessary for the reload button to go away in the popup.
