### ISSUE TITLE
uBlock blocks the youtube logo in the top left of the page

### ISSUE THREAD

**Issue by Someguy123** [uBlock-LLC/uBlock#749]
https://www.youtube.com/

uBlock seems to remove the YouTube logo in the top left as of recently.

**Comment by Mikey1993** [comment]
Can't reproduce.
What filters are you using?

**Comment by chrisaljoudi** [comment]
@Someguy123 mind sharing the browser, filters, and version of µBlock so we can investigate the issue?

**Comment by gorhill** [comment]
Can't repro using the provided repro steps.

**Comment by Someguy123** [comment]
http://i.imgur.com/muAYH6V.png

**Comment by gorhill** [comment]
Marking as "available" for whomever to investigate based on the provided information.

**Comment by gorhill** [comment]
The Youtube logo is at <https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif>. So _something_ is blocking this on your computer.

**Comment by gorhill** [comment]
The logo is downloaded from http://s.ytimg.com/yts/imgbin/www-hitchhiker-vflZjw0oc.webp, so something is blocking this on your computer.

**Comment by ghost** [comment]
@Someguy123 

what do you have under "My Filters" in the dashboard?

**Comment by Someguy123** [comment]
@gorhill 
Correct: if I disable uBlock for YouTube, the logo loads fine. If I turn it back on, it's gone again.

@kintpuash

See my other comment: http://i.imgur.com/muAYH6V.png

**Comment by Someguy123** [comment]
Strangely it seems like a filter list isn't doing this, but uBlock itself. When I look under the advanced list of what's blocked on the page, I'm unable to see the logo in the list, I can see various DoubleClick ads, but not the logo. Despite this, enabling/disabling uBlock directly affects the visibility of the YouTube logo.

If it helps, I'm on the latest version of Chrome on OSX 10.10

**Comment by gorhill** [comment]
@Someguy123 can you right-click on the logo and select "Inspect element"? I would like to have a snapshot of what is reported in the dev console -- make it as high as possible.

Like this:

![c](https://cloud.githubusercontent.com/assets/585534/6117129/78645cc8-b080-11e4-8886-b659d834caac.png)

**Comment by chrisaljoudi** [comment]
@Someguy123 My Filters is a different tab from 3rd Party Filters. The screenshot is of 3rd Party Filters. What do you have, if anything, under My Filters?

**Comment by gorhill** [comment]
@chrisaljoudi it says "0" aside _"My filters"_, so that's not the problem.

**Comment by gorhill** [comment]
By the description of the symptoms at this point, this appears to be the work of a cosmetic filter.

**Comment by chrisaljoudi** [comment]
@gorhill right, but since no one else can reproduce so far... it makes me suspect maybe @Someguy123 has another extension that's somehow changing/customizing YouTube? Any other extensions?

**Comment by ghost** [comment]
Not to be pedantic, however until a browser restart the third party filter tab doesn't indicate a change saved under "My Filters"

**Comment by Someguy123** [comment]
@chrisaljoudi No, when I turn off uBlock for YouTube, the logo comes back. I have no other DOM changing extensions that could affect this.

There is nothing under "My Filters".

@gorhill here you go:
![](http://i.imgur.com/124EGF3.png)

**Comment by gorhill** [comment]
@Someguy123 Thanks. However I needed you to select the `img` tag, as in my screenshot -- you selected the `a` tag. This way I can look at the CSS properties on the right pane.

**Comment by Someguy123** [comment]
@gorhill Looks like whoever maintained the filter has noticed this. I went to get the CSS for you, but the logo is back now.
