### ISSUE TITLE
List of blocked resources in the popup!

### ISSUE THREAD

**Issue by mubaidr** [uBlock-LLC/uBlock#75]
Is it possible that list of all blocked requests/resources for current tab/website can be shown in  extension popup? This will allow to easily and quickly white-list a request/resource (not just whole wbsite).

(Please have a look at another awesome tool https://addons.opera.com/en/extensions/details/contentblockhelper/?display=en)

**Comment by gorhill** [comment]
I want to keep the popup clean and simple. For more advanced users, there is HTTP Switchboard.
