### ISSUE TITLE
Feature request: Add a row to Dynamic Filtering to be able to whitelist Style sheets files (CSS)

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#750]
It's very common in a block all by default scenario to just want to see the site properly, so one could potentially just `noop` Images and Style sheets (CSS) to get sense if it needs to be more fine tuned for usuablity or not.

I think this one can bring a lot of ease to advanced user, and myself included.

**Comment by gorhill** [comment]
Won't work, see #739.

Anything more is uMatrix. I won't push uBlock anymore than it is toward uMatrix.
