### ISSUE TITLE
Inline script

### ISSUE THREAD

**Issue by Patryk-S-W** [uBlock-LLC/uBlock#751]
Chrome don't like inline scripts in extensions so i dev console say:

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' *". Either the 'unsafe-inline' keyword, a hash ('here is sha256'), or a nonce ('nonce-...') is required to enable inline execution.

when I using uBlock

**Comment by gorhill** [comment]
You are blocking inline scripts. That's the browser reporting about this. It's normal.
