### ISSUE TITLE
Kaspersky complaining on some new filterlist update since µBlock 0.8.7.0

### ISSUE THREAD

**Issue by HitomiTenshi** [uBlock-LLC/uBlock#752]
My Kaspersky is exploding everytime µBlock tries to update the filter lists. Happened since 0.8.7.0, screenshot time:

![1](http://puu.sh/fHkXh/0980deb803.png)
![2](http://puu.sh/fHl0z/b0baac902c.png)
![3](http://puu.sh/fHljh/589e316eb8.png)
![4](http://puu.sh/fHllr/05ade708d9.png)

Is this a false positive?

**Comment by gorhill** [comment]
> Is this a false positive?

Yes. Dan Pollock's hosts file (http://someonewhocares.org/hosts/) is shipped with the extension.

**Comment by gorhill** [comment]
Here if you want to see what changed inside Dan Pollock's hosts file: [diff](https://github.com/gorhill/uBlock/commit/b4b01ea06c21bacf26c867368640173e9a77b8d1#diff-ec564d319425471b5320025412ee87dc)
