### ISSUE TITLE
Lingering Question, Not An Issue

### ISSUE THREAD

**Issue by windyctyprog** [uBlock-LLC/uBlock#753]
Do the default filters in Easy List and Easy Privacy (or any of the Fanboy Lists) allow some advertising?

In other words, is the ABP allowable advertising problem done through the subscriptions or ABP itself?

I have always used Fanboy Ultimate list on ABP and ABE, but it got me wondering since I switched to uBlock.

BTW, great product.

In advance, thanks...

**Comment by gorhill** [comment]
> ABP allowable advertising

Adblock Plus uses a [separate filter list](https://easylist-downloads.adblockplus.org/exceptionrules.txt) for ["Acceptable ads"](https://adblockplus.org/en/acceptable-ads). This special filter list is not part of uBlock, though someone is free to import it as a custom filter list.

It has been requested in the past that uBlock supports it in the past: #66 (closed as `wontfix`).

**Comment by windyctyprog** [comment]
Thank you so very much...

I like your product, hate ads. period.

I have added Fanboy's Ultimate in lieu of Easy List/Easy Privacy, any issues from your perspective?

I kept the other default lists - always use Malware Domains, have for years.

Thanks, in advance.

**Comment by chrisaljoudi** [comment]
@windyctyprog Fanboy's Ultimate list is combined Easylist+Fanboy and does include EasyPrivacy. No issues there.
