### ISSUE TITLE
[Safari] Can't apply settings or download filters

### ISSUE THREAD

**Issue by AdamJ8** [uBlock-LLC/uBlock#754]
Whenever I try to change a setting and then apply - or - attempt to download filter updates the screen goes gray and the blue spinning ball will stay on the screen indefinitely.

OS: 10.10.2
Safari: 8.0.3
uBlock: 0.8.7.0

Troubleshooting (none have resolved):
1. Reset plug settings to default, closed and reopened Safari
2. Uninstalled plugin, restarted, reinstalled
3. Uninstalled, deleted local safari storage, deleted safari cache, restarted, reinstalled

The plugin appears to be 'functioning' using what I suspect are the pre-canned lists (either that or they are old lists I've downloaded in the past) but I can't download updates.

Seems like it could be related to:
https://github.com/gorhill/uBlock/issues/527
https://github.com/gorhill/uBlock/issues/613

Note: The issue does not occur on my Chrome(beta) using 0.8.7.0 install.

Let me know if there is any debug logging I can enable to help with this??

**Comment by chrisaljoudi** [comment]
@AdamJ8 Do you have any other extensions installed?

**Comment by AdamJ8** [comment]
Yes - but I've tried the above steps with those all marked as 'disabled' ? Is that not sufficient?

**Comment by chrisaljoudi** [comment]
@AdamJ8 that's probably fine.

> Whenever I try to change a setting

Any setting, or just filter list settings?

**Comment by AdamJ8** [comment]
It appears to only be on the '3rd Party Filters' page.

I notice that if I enable or disable a filter, then click "Apply Changes", then close the preferences page and come back the change appears to 'stick' - even if I close Safari and re-open.   

However the "Update Now" button does not seem to actually update the lists, as re-opening the page still shows they are outdated.

**Comment by chrisaljoudi** [comment]
Caused by #376.
