### ISSUE TITLE
strange issue with hotlinked video

### ISSUE THREAD

**Issue by anonish** [uBlock-LLC/uBlock#755]
I changed something, and I'm trying to narrow it down between ublock, policeman, or the userscript mouseover popup image viewer
The issue is this, as an example
https://twitter.com/AlexaBliss_WWE/status/564176808267223041
has a link to an instagram mp4 video.  mouseover PIV is supposed to hotlink and generate a popup with the video, as it does with images
the link created from MouseoverPIV is:

```
data:video/mp4;base64,AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAEyTbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAOvUAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAEDl0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAOqgAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAoAAAAKAAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAADqoAAAAAAABAAAAAA+xbWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAu1AACvyBVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAAPXG1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAADxxzdGJsAAAAlHN0c2QAAAAAAAAAAQAAAIRhdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAoACgABIAAAASAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAALmF2Y0MBQsAf/+EAF2dCwB/aAoBRsBEAAAMAZAAAF2oPGDKgAQAEaM48gAAAABhzdHRzAAAAAAAAAAEAAAHCAAABkAAAABhzdHNzAAAAAAAAAAIAAAABAAA"[…] 
```

I get the error in the web console:

```
"File can't be displayed.
RegExp: /((in|web\.)stagr(\.am|am\.com)|websta\.me)\/p\//i
URL: http://instagram.com/p/y0LxgmnP5u/
Popup: […the data above...] Mouseover_Popup_Image_Viewer.user.js:843
```

I have all block enabled, then on twitter i use noops for twitter.com, twimg.com, instagram.com.  Other links/popups work as intended (images, youtube).  I have tried enabling everything for twitter, enabling inline/3rd party scripts/frames, completely enabling all, etc.  I have done this with policeman addon completely removed.

mind you, it was working with all three addons enabled about an hour ago, and I must've changed something in either ublock or policeman that changed the behavior, as it now fails to show the video (even though other links/images do work).
I have tried disabling policeman and ublock separately and together and the link no longer works even with both addons off.  I even tried it on a new profile and it fails to load (with nothing running except greasemonkey/MouseoverPIV)

any ideas? it's driving me crazy because I _know_ it was working before... and now it doesnt. it happens with all instagram videos too, not just the example above.  maybe i'm just going crazy though :/

I know this is a long shot, but do you know any blocking issues with data:video urls?

**Comment by gorhill** [comment]
Is `data-scheme` whitelisted?

**Comment by anonish** [comment]
whitelist

```
about-scheme
behind-the-scene
chrome-extension-scheme
chrome-scheme
data-scheme
file-scheme
opera-scheme
```

**Comment by gorhill** [comment]
What is MouseoverPIV?

**Comment by gorhill** [comment]
Problem is a content security policy one: the instagram link is `http`, and the Twitter page has a content security policy set for `media-src`:

```
Content Security Policy: The page's settings blocked the loading of a resource at 
http://videos-h-13.ak.instagram.com/hphotos-ak-xfa1/t50.2886-16/10987043_391356431035673_1913031139_n.mp4 
("media-src https:")
```

**Comment by gorhill** [comment]
To find out, it was a matter of opening the browser console: `Ctrl`-`j`.

**Comment by anonish** [comment]
weird, even with security.csp.enable set to false it still wont work. not a big deal but it's bugging me that it worked and then stopped. thanks for looking into it
