### ISSUE TITLE
YouTube filtering options à la ABP

### ISSUE THREAD

**Issue by TempSpas** [uBlock-LLC/uBlock#756]
This is an enhancement request, rather than an issue per se. One of the filters I used heavily on Adblock Plus was the YouTube comment filters I got from this page: https://youtube.adblockplus.me/en/ When I switched to uBlock, I manually added all of the filters for the same effect, but I think it would be helpful to add those to uBlock's default list of 3rd-party filters, perhaps under "Social."

**Comment by Snapy** [comment]
Go to the "filters" tab in the dashboard and scroll down. You should see a box where you can add whatever filter list link you want.

**Comment by ghost** [comment]
@TempSpas  see #512 

Same problem. No license terms for the list are available. As @Snapy mentioned, you can remove the "!" from the lists at the bottom of the Third Party Filters tab in the Dashboard, parse and apply.

**Comment by TempSpas** [comment]
I see, thanks for the responses. Regarding the ones I mentioned, it's my understanding that using them will increase uBlock's memory footprint? Does this mean that every time I access a YouTube video with them enabled, the browser uses more memory?

**Comment by gorhill** [comment]
@TempSpas "it's my understanding that using them will increase uBlock's memory footprint? "

Memory usage in uBlock is not an issue, even less so when it's about filter lists as small as the ones in your OP.

**Comment by ghost** [comment]
[Adblock Plus YouTube customization filters](http://youtube.adblockplus.me/en/)

As Snapy wrote, from the filter lists available there, copy the url, clean it from what is meant to automatize the subscription to AdblockPlus/Edge, then copy the url to uBlock's Dashboard -> 3rd-party filters -> Custom (at bottom of the page), click Parse and you're done.

**Comment by gorhill** [comment]
Here, the URLs for convenience: [FAQ](https://github.com/gorhill/uBlock/wiki/FAQ#youtube-filtering-options-%C3%A0-la-abp-facebook-filtering-options-%C3%A0-la-abp)

**Comment by ghost** [comment]
@gorhill thanks! Looks better that way!
