### ISSUE TITLE
I presume ABP should be uninstalled – please include answer in the FAQ

### ISSUE THREAD

**Issue by statzhero** [uBlock-LLC/uBlock#760]
Sorry if I missed it somewhere.

**Comment by harshanvn** [comment]
It is not advisable to use other blocker, in order to benefit from its higher efficiency.

Link @homepage - https://github.com/gorhill/uBlock#note-for-all-browsers

**Comment by gorhill** [comment]
It's just common sense: why would someone use two extensions that do the same thing?
