### ISSUE TITLE
Strange behavior on polish information website www.o2.pl

### ISSUE THREAD

**Issue by ArchiwumX** [uBlock-LLC/uBlock#761]
This site is loaded without pictures. I have to scroll the page (mouse wheel) then pictures are loaded.
Everything is OK when I'm using ABP.

**Comment by gorhill** [comment]
Works fine for me with default settings.

**Comment by gorhill** [comment]
Ok, I see the described behavior if I activate malware domains (forgot I had them un-cheked). So the problem is in there.

**Comment by gorhill** [comment]
Strike that, I don't see any problem. There is a one-second delay for when the image appears, but they appear.

**Comment by gorhill** [comment]
uBlock or ABP, same behavior, there is a bit of a delay before the image appears, as they are downloaded through javascript I believe.

There is no issue.

**Comment by gorhill** [comment]
If you think there is really an issue, re-open and please provide more details.

**Comment by ArchiwumX** [comment]
One second delay is only when uBlock is switched off. When is ON, images dont appears. Never. I have to scroll the page using key down or mouse whell. I think this is a uBlock problem, because this is strange. I understand when filters are too strong and blocks images completely. But here what happend? Images are blocked and scrolling the page makes them unblocked?

**Comment by gorhill** [comment]
@ArchiwumX As said, I don't see this problem. So you need to provide me details with your settings. Without this I can't help you. So, browser version, filter lists, custom filters, dynamic filtering rules, etc.

**Comment by ArchiwumX** [comment]
I found it. Problem exist only with "Anti-ThirdpartySocial" filter in "Social media" group (I'm using PL version so I guess the name). OK, this is not a problem for me and this is not a big issue, but I wanna help you makes program better :)
Windows 8.1 64bit, Firefox 35.0.1

**Comment by gorhill** [comment]
> I wanna help you makes program better

Thanks. Now I think you should report this site breakage by _"Anti-ThirdpartySocial"_ to the maintainers of that list: https://forums.lanik.us/viewforum.php?f=64

This way they can fix the issue for everybody.

**Comment by ArchiwumX** [comment]
I added this filtr to ABP and problem appear. Now I know this is not uBlock issue. I could do it at the beginning :) Sorry. Thank you for quick response. You can close this thread.
Greetings.
