### ISSUE TITLE
CSS Selector Error

### ISSUE THREAD

**Issue by sanilunlu** [uBlock-LLC/uBlock#765]
I've seen that it prints the following error message on my dev console over and over:
`contentscript-end.js:350 Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '[a long css selector expression]' is not a valid selector.`
This is related to the following line: https://github.com/gorhill/uBlock/blob/master/src/js/contentscript-end.js#L350

I checked the selector expression and found that the part causing the error is:
`div[id="wptouch-head" class="metabox-holder"]`
I don't really know which abp subscription rule leads to this selector, since I didn't notice this before, it should've started recently.

**Comment by gorhill** [comment]
Did you look if it's in your own filters?

**Comment by gorhill** [comment]
I don't see this in any filter lists. To me it looks like you are feeding uBlock with this one way or another: custom filter lists or custom filters.

**Comment by sanilunlu** [comment]
Sorry for that, it's my mistake. I had a custom filter from the following site which contains the faulty selector:
http://adblock.gjtech.net/?format=adblock-plus
