### ISSUE TITLE
Better info display

### ISSUE THREAD

**Issue by marsfan** [uBlock-LLC/uBlock#766]
uBlock should have a better interface on displaying what is blocked. Either show the names of the urls blocked, the company, or a highlight of the blocked areas when the app info is opened. Even better, Have a combo of the three. 

Wish I understood javascript and Firefox plug in coding,
Marsfan

**Comment by gorhill** [comment]
The network request log will show you which URLs are blocked, see [Quick guide: popup user interface](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-number-of-requests-blocked): _"Click the eye icon to bring up the network request logger"_.

> the company

uBlock is developed on a purely voluntary basis, we do not have the resources to gather a gigantic database of worldwide domain name/entity name pairs. Feel free to contribute one.

> highlight of the blocked areas

By default these areas are collapsed, you can see them anyways. Even then, a majority of the blocked stuff has no visual counterparts.

**Comment by marsfan** [comment]
Ok, I just wanted to know because I am being told that 3 requests have been blocked on a site I know had just one ad

**Comment by gorhill** [comment]
EasyPrivacy blocks trackers/analytics and other such things. As said on the front page of the project: _"µBlock is not an ad blocker; it's a general-purpose blocker"_.

**Comment by marsfan** [comment]
Ah, sorry. Where is the Domains connected menu on Firefox?
