### ISSUE TITLE
[EasyPrivacy] Whitelist doesn't work

### ISSUE THREAD

**Issue by necromant2005** [uBlock-LLC/uBlock#768]
Page: https://www.truesocialmetrics.com/blog/google-analytics-multi-device-tracking-and-measurement-protocol
Added to whitelist: 
dn090igz07ndb.cloudfront.net
https://dn090igz07ndb.cloudfront.net/*
https://dn090igz07ndb.cloudfront.net/images/*

Images are still blocked.

**Comment by offhub** [comment]
Whitelist the main page: truesocialmetrics.com

See for more: https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site

OR

Allow cloudfront.net for https://www.truesocialmetrics.com/ from popup window or add it following rule to "My rules" in options: truesocialmetrics.com dn090igz07ndb.cloudfront.net \* allow

OR

Add it following rule to "My filters" in options: @@||cloudfront.net^$domain=truesocialmetrics.com

**Comment by Betsy25** [comment]
In the advanced panel, enabling "dn090igz07ndb.cloudfront.net" for site only (rightmost column) & click the reload button = the images show up just fine here.

**Comment by necromant2005** [comment]
Thank you ! It works! but it's definitely unclear behaviour

**Comment by offhub** [comment]
One of the filters is blocking the links.

![ublock_03960xx](https://cloud.githubusercontent.com/assets/6871698/6145243/6eaaa0c0-b1e8-11e4-9be7-08055bf600d1.png)

**Comment by gorhill** [comment]
_Whitelisting_ is to disable uBlock, not to filter stuff. What you want is an exception filter:

```
@@||dn090igz07ndb.cloudfront.net^$domain=truesocialmetrics.com
```

You may want to report this to EasyPrivacy maintainers: https://forums.lanik.us/viewforum.php?f=64
