### ISSUE TITLE
uBlock + Easylist Nomercy - Possible?

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#769]
I'm Adblock Edge user.
Can I use "Easylist NoMercy" with uBlock? If so, I'll try out your add-on.

NoMercy:
https://sw.estiva.org:419/aaw/publist/adblock.html

**Comment by Betsy25** [comment]
Can't even access that site over here.

[DownForEveryoneOrJustMe](http://www.downforeveryoneorjustme.com/sw.estiva.org/aaw/publist/adblock.html)
[same with the port 419 check](http://www.downforeveryoneorjustme.com/sw.estiva.org:419/aaw/publist/adblock.html)

@gorhill I would remain conservative at adding all those 1-10 users' blocklists to the default config, it will clutter the config window, and will blow up the difficulty for tracking all kind of related issues. People can already add them at their own will, if they really need them.

**Comment by harshanvn** [comment]
> I would remain conservative at adding all those 1-10 users' blocklists to the default config, it will clutter the config window, and will blow up the difficulty for tracking all kind of related issues.

Agreed :+1:

**Comment by offhub** [comment]
You can use "Easylist NoMercy" with uBlock. 

Options > 3rd party-filters > Add your URL to "Custom" box then Parse.

**Comment by gorhill** [comment]
Easylist Nomercy is way too likely to break everything, it's a list few will use in reality. It won't be added to the default list of filters, but you can import it as a custom external filter list. A real, meaningful "no mercy" mode is to use default-deny.
