### ISSUE TITLE
Issue with reverting temporary rules. (In Firefox nightly)

### ISSUE THREAD

**Issue by Betsy25** [uBlock-LLC/uBlock#772]
Browser : Firefox v38 (nightly) 32bit
OS : Win7, 64bit

Might be Firefox specific ??

There's something definitely not quite right with reverting temporary rules (in Firefox).
Here are the steps I take and the results they give me...
- On this very same page here, click images to temporary block images on this site only & reload. (avatars no longer loaded)
- Open up the "My Rules" page (clicked rule is in the temporary list)
- click "Revert"
- Now force reload this very page in the browser.
  Result : The images (user avatars) are still not visible.

Upon inspection using Fiddler, they _do_ get requested, and re-opening the "My Rules" page does not show the filter anymore. (which on itself, is correct) yet no avatars become visible.

Closing & Reopening the browser is needed for all images to become visible again.

Anyone can reproduce ?

**Comment by gorhill** [comment]
I can reproduce with Firefox and Chromium.
