### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by marsfan** [uBlock-LLC/uBlock#773]
I have read that the best way to learn a language is to start a project. Would it be possible to add copious amounts of documentation (bit by bit, so as not to overwhelm devs), so that people can jump into supporting the software better?

**Comment by chrisaljoudi** [comment]
What do you mean? Are you talking about in-code comments that document functionality?

**Comment by marsfan** [comment]
Yes, make it a little more clarifying than it is currently.

**Comment by chrisaljoudi** [comment]
@Marsfan okay. I'm happy to do that with all the Safari platform code unless @gorhill minds it.

**Comment by gorhill** [comment]
A non-issue as far as I am concerned. Please keep issues very specific, so that there is a way to we can close them with specific code changes.
