### ISSUE TITLE
Broken layout on http://carbonads.net/

### ISSUE THREAD

**Issue by trietbui85** [uBlock-LLC/uBlock#774]

**Comment by Betsy25** [comment]
In the advanced panel, green out the rightmost column next to "carbonads.net", and click the reload icon. If you visit this website regularly, you should make that temporary rule a permanent one, by clicking the padlock icon on the top left.

**Comment by chrisaljoudi** [comment]
@anticafe [Peter Lowe's](http://pgl.yoyo.org/as/serverlist) includes these two rules:

```
127.0.0.1 carbonads.com
127.0.0.1 carbonads.net
```

The Carbon Ads people use carbonads.net to deliver ads as well, it appears. EasyList has a `$third-party` qualifier for blocking that same domain, but Peter Lowe's is just a hostname list.

Ways to unbreak would be: whitelisting it, using dynamic filtering, or:

```
@@||carbonads.net$domain=carbonads.net,important
```

It's up to @gorhill whether we should add an exception rule to µBlock's patch rules, but this is no issue in µBlock itself.
