### ISSUE TITLE
Not an issue, just a question regarding AdblockPlus filter syntax

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#775]
I read on https://github.com/gorhill/uBlock/wiki/Filter-syntax-extensions : 
"µBlock supports most of Adblock Plus filter syntax. However µBlock does not support some very specific case, and also added its own extensions to ABP filter syntax."

What of Adblock filter syntax is not supported? 

I had imported custom filters from Adblock Plus when I switched to uBlock and I can see on my uBlock's Dashboard : 
My Filters: 417 used out of 452

I'd wish to know the filter syntax delta which leads to 35 filters unused (when none has a leading "!", in order to build future ones correctly as well as to remove those which are invalid.

Thanks

**Comment by my-password-is-password** [comment]
Uncheck all list except your filters and apply and see if it says 452 used of 452.  You might have some filter already included in another list so uBlock doesn't count duplicate fitlers.

**Comment by Zylinder** [comment]
Unchecking _My Filters_ leads to 0 used out of 452.
I note your remark on duplicate filters, same as it was with Adblock+

**Comment by my-password-is-password** [comment]
I mean keep `My Filters` checked and everything else unchecked.

**Comment by lewisje** [comment]
I think that page needs to be reworded: Originally it said that it didn't support regexes, but now it does, and that page doesn't say that it doesn't support the `$document` specifier for whitelist rules (preferring instead for whitelisted domains to go onto a separate whitelist) or the `$sitekey` specifier (used only by ABP so that its Acceptable Ads whitelist can work for major networks of non-intrusive ads).

**Comment by ghost** [comment]
OK, I see what you mean.
Well, unchecking all filters except mine leads to : _My filters‎: 424 used out of 452_
That means 7 of my filters are duplicates to other ones, ok.
Remain 28 of my filters which are invalid. This is why I'd wish to know the wrong syntax which invalidates them.
No privacy concerned, here's my list : http://pastebin.com/sEFfdDys

Thanks

**Comment by gorhill** [comment]
> What of Adblock filter syntax is not supported?

I revised the wiki to add `document`.

There is also `font`/`media` types, but this will be fixed (#649).

**Comment by gorhill** [comment]
Un-checking all filters except yours, I get 452 filters used, i.e. all of them:

```
45 network filters ＋ 407 cosmetic filters
```

**Comment by ghost** [comment]
@gorhill commented on [12 févr. 2015 14:40 UTC+1](https://github.com/gorhill/uBlock/issues/775#issuecomment-74071553):

> Un-checking all filters except yours, I get 452 filters used, i.e. all of them:
> 
>  45 network filters ＋ 407 cosmetic filters

Now indeed I have the same results, 45 & 407, which means all of my filters are available.
When I tested previously as above mentioned _My filters‎: 424 used out of 452_ : I don't get it. Anyway all is fine that carries on fine...

Thanks,
