### ISSUE TITLE
[EasyPrivacy] ublock incorrectly blocks login attempts on navyfederal.org

### ISSUE THREAD

**Issue by mikec83** [uBlock-LLC/uBlock#777]
Ublock is incorrectly blocking the log in functionality on www.navyfederal.org .  Have to disable the plugin on this site in order to log in.

**Comment by gorhill** [comment]
The problem is the filter `/b/ss/*&aqe=` in EasyPrivacy. You need to report the issue to maintainers of EasyPrivacy: https://forums.lanik.us/viewforum.php?f=64.

Meanwhile, you can use this custom filter to work around the issue: `@@/b/ss/*&aqe=$domain=navyfederal.org`.

**Comment by gorhill** [comment]
I just want to emphasize that it is important you report it to EasyPrivacy maintainers, this way the issue will be solved for everybody.

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/b0a77b63f37f
