### ISSUE TITLE
can i turn off 'blocked ads' counter?

### ISSUE THREAD

**Issue by noisia04** [uBlock-LLC/uBlock#778]
ublock has 'blocked ads' counter.
![image](https://cloud.githubusercontent.com/assets/8155307/6174251/d71de632-b330-11e4-83d0-6fd3630e480a.png)

can i turn off this counter? i does not want to use ads blocking log or statistics.

**Comment by gorhill** [comment]
No, you can't.

And just in case, I don't see the need to have yet-another setting just for such an uncommon preference.
