### ISSUE TITLE
[EasyPrivacy] Most recent version of uBlock breaks Stripe dashboard

### ISSUE THREAD

**Issue by kyleconroy** [uBlock-LLC/uBlock#779]
This is easy to reproduce: log into the [Stripe dashboard](https://dashboard.stripe.com), and you'll see that an AJAX request to `https://dashboard.stripe.com/ajax/api/analytics/bootstrap` is now being blocked. This request isn't for tracking purposes; it just returns data for display a graph.

Here's the entry from the uBlock log (it's colored red)

```
−   /api/analytics/ xmlhttprequest  https://dashboard.stripe.com/ajax/api/analytics/bootstrap
```

My guess is that a recent update to the default filter set on uBlock somehow caught this URL. Is there a process for fixing issues like this? Or should we just change the URL?

**Comment by gorhill** [comment]
There is a filter in EasyPrivacy: `/api/analytics/*`.

EasyPrivacy is third-party to uBlock, so you need to contact them for a fix: https://forums.lanik.us/viewforum.php?f=64.

This will also fix the problem for whoever is using _EasyPrivacy_ regardless of the blocker in use (ABP, AB, Adguard, etc.

**Comment by kyleconroy** [comment]
@gorhill Thanks for the link, I'll go ahead and close this and reach out to EasyList
