### ISSUE TITLE
Feature: add network rules in addition to cosmetic rules from within the element picker in one go

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#781]
It's very rare for one to hide an element but not wanting to prevent the net request/s behind it (or it's lower tree), for obvious performance wins and less page load.
So I think a blessed feauture would be to have an option to block a network request/s **and** the page elements **in one go**.

Something like a checked checkbox (by default) next to each net request will be great IMO.

**Comment by chrisaljoudi** [comment]
Hmm, interesting idea — that sounds like it might be handy.

It seems like it might be sufficient to be able to add network rules from the request log page, no? So unlike cosmetic filtering, you have a way to create a new filter by clicking on one of the rows in the net request log.
