### ISSUE TITLE
Dev versions have the same version no. in the manifest as the latest release

### ISSUE THREAD

**Issue by KDsMax** [uBlock-LLC/uBlock#782]

**Comment by chrisaljoudi** [comment]
Hmm. Did the previous dev builds not appear as such? @gorhill usually pushes the releases, and I didn't think there were any changes in the `manifest.json` for the dev releases.

**Comment by KDsMax** [comment]
I didn't try any other Dev version, just thought to give this Dev version a chance, just bored you know.

**Comment by chrisaljoudi** [comment]
71ba590b17

So next release will be fine.
