### ISSUE TITLE
Allow 3rd party / whitelist filter intallation via "abp:subscribe?location=whitelistURL"

### ISSUE THREAD

**Issue by vitalvital** [uBlock-LLC/uBlock#783]
Example: <a  href="abp:subscribe?location=http%3A%2F%2Fwww.whitelist.com%2Fwhitelist.txt">Install our whitelist</a>

This would give end users (and service providers as well, who are currently left out) additional freedom to (much easier than doing it manually) opt into a service (like some user benefiting affiliate action tracking) which may be blocked by uBlock.

It would be important to leave "abp:subscribe" in order to be compatible.

**Comment by gorhill** [comment]
Dup of #224.
