### ISSUE TITLE
[EasyList] Could not load plugins: File not found

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#784]
uBlock cannot block ads on connectcast.tv without blocking the video plugin as well.

This appears to be the same issue referenced in https://github.com/gorhill/uBlock/issues/166

**Comment by chrisaljoudi** [comment]
This is why the site is failing:

![Image](http://chrisly.me/image/031o05112L1c/Image%202015-02-12%20at%2010.09.03%20PM.png)

The same problem occurs with AdBlock Plus, by the way. Unsurprisingly, `vast.js` is indeed something that should be blocked per EasyList's adblocking — https://github.com/theonion/videojs-vast-plugin

This can be traced back to this rule in EasyList:

```
||jwpcdn.com^*/vast.js
```

You can report this to EasyList's maintainers via their (quite active) forum: https://forums.lanik.us/viewforum.php?f=64

---

This isn't an issue with µBlock. As you can see, it's executing the rule from EasyList perfectly. You can whitelist the website (click on the toolbar icon, and press the power button), and that'll make it work fine. 

You can also add your own rules under "My Filters" in preferences. It would look something like:

```
@@||jwpcdn.com^*/vast.js$domain=connectcast.tv
```

Which is basically making an exception for the `vast.js` rule when you're on `connectcast.tv`.

You should definitely report this to the EasyList people, as well, so everyone else using µBlock, ABP, or any other blocker with EasyList can get the fix as well.

**Comment by ghost** [comment]
Thanks for this, sorry for reporting it to the wrong place. I've posted on the easylist forums as well.

**Comment by chrisaljoudi** [comment]
@Tabrias not a problem; just trying to help get the issue fixed as throughly and completely as possible. :)

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/00038bca1a55
