### ISSUE TITLE
[Performance] Enhance the retrieval of frame id

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#785]
https://issues.adblockplus.org/ticket/1739
https://developer.chrome.com/extensions/runtime#property-MessageSender-frameId

Chrome 41 (stable release) now supports this property for a more efficient way (I assume) to retrieve the frame id of the request.

Can this also be beneficial for uBlock?

**Comment by gorhill** [comment]
uBlock does not work like ABP. Whatever problem is mentioned in there is foreign to uBlock.
