### ISSUE TITLE
could not remove pcbeta's ads

### ISSUE THREAD

**Issue by ivysrono** [uBlock-LLC/uBlock#789]
http://bbs.pcbeta.com/
With easylistchina
![google chrome 2015-02-14 22 53 29](https://cloud.githubusercontent.com/assets/2649544/6199971/afc80abe-b49c-11e4-83ad-85d1061b1ec5.png)

**Comment by gorhill** [comment]
Could not remove **what**?

**Comment by gorhill** [comment]
Please, provide details. We can't read mind.

**Comment by ivysrono** [comment]
sorry , I click wrong,I will add soon.

It is ok now.

**Comment by gorhill** [comment]
Many challenges here: the class names are random strings. Still, normally this should work: `bbs.pcbeta.com###wp .forum_top ~ div`.

Except that I cannot find the style injected by uBlock. It appears the web page is removing the style tag added by uBlock (need to investigate further as time allow).

When using a generic though, `###wp .forum_top ~ div`, it does work, so the page is not removing the style tag added after the page loads, only the one added before the page loads.

**Comment by gorhill** [comment]
I fixed the problem of having the site remove the style tag.

However, for the filter itself, users will have to figure it out using the dev console for when the site create random `class`, `id` or whatever else they do to make it difficult to create filters.

So anyways, with the fix, `bbs.pcbeta.com###wp .forum_top ~ div` works (until the site owner works around that specific filter).

**Comment by ivysrono** [comment]
0.8.8.0
and 
bbs.pcbeta.com###wp .forum_top ~ div
Works the same as ABP:the ads are white now.
Would you support to hide the white just as this css:
Remove ads for PCbeta - Themes and Skins for Pcbeta - userstyles.org
https://userstyles.org/styles/110389/remove-ads-for-pcbeta

**Comment by gorhill** [comment]
> Would you support to hide the white just as this css

No, that's really a job best left to Stylish.
