### ISSUE TITLE
default rules block content from site

### ISSUE THREAD

**Issue by pcause** [uBlock-LLC/uBlock#790]
I just installed ublock on firefox (aurora).  I'd previously used on Chrome.  WHen I enable advanced, the default rules block content from the source site.  For example, if I go to www.xx.com, various elements originating at www.xx.com are blocked and I have to enable content from www.xx.com  as a local rule to get the site displayed correctly.  Shouldn't the defaults allow content from the origin site?

Using the latest dev version.

**Comment by gorhill** [comment]
There are no rule set for any fresh install of uBlock. The only way for a dynamic filtering rule to exist is for the user to create one. Check what you have in _"My rules"_: whatever is there was added by a user on your computer.

**Comment by pcause** [comment]
I had imported some rules I set with chrome.  I uninstalled firefox, deleted all of the stuff in appdata related to firefox and did a clean install (latest nightly).  Installed dev-7.  I didn't import anything.  Clicked advanced user.  I do not see the left pane to set dynamic rules.

**Comment by pcause** [comment]
never mind.  figured out how to get panel.  seems ok now.  must have been my imported rules from umatrix that caused the problems
