### ISSUE TITLE
graphical interface chrome vs. FF

### ISSUE THREAD

**Issue by un99known99** [uBlock-LLC/uBlock#791]
Hi,
I really love the chrome extention which is clearly setup in line like cookie, CSS, pic, plugin, script, etc.
Within FF it seems not so clear. 
Will the look and feel from chrome be also adapted to FF?

Thx.
BR,
Mike

**Comment by gorhill** [comment]
You are confusing uBlock with uMatrix. Both uBlock-Chromium and uBlock-Firefox have the same look.

**Comment by un99known99** [comment]
u r correct, sorry was a _user to stupid_ thing, thx for ur quick reply

**Comment by un99known99** [comment]
could you do me one favor, where can I download uMatrix for FF?

**Comment by gorhill** [comment]
It's not ported to FF yet.

**Comment by un99known99** [comment]
any plans to do so, if so, when, any chance to follow announcements from ur side?
