### ISSUE TITLE
Dashboard: 3rd-party Filters Tab

### ISSUE THREAD

**Issue by ozar** [uBlock-LLC/uBlock#792]
The 3rd-party filters tab in the uBlock Dashboard is starting to become rather long in size and when using custom filters, one has to scroll down past a large number of "Regional, languages" filters to see their "Custom" filters information.

Is there some feasible method that wouldn't be too difficult to implement for collapsing each of the filter categories?  If not each of them, perhaps the "Regions,languages" category could be collapsed then re-opened by end users as needed, or maybe there is some other way to better organize the options on this tab.

Thanks for any consideration.

**Comment by elyrly** [comment]
The overall feel of the 3rd-party filter tab is not overbearing and simple to navigate. I don't see the necessity to implement a collapsible list but i maybe wrong.

**Comment by gorhill** [comment]
What blocks me from implementing this trivial fix is that I can't find a `localStorage` (or equivalent) available for the page on Firefox, like there is on Chromium. I do not want to add user settings just for this trivial local UI feature, and using `localStorage` make this possible. But there is no such local storage available for an extension on Firefox.

**Comment by Deathamns** [comment]
@gorhill While you can't use `localStorage` on `chrome:` pages, you can use the `localStorage` of any other page. Like this:

``` js
var ls = Services.domStorageManager.getLocalStorageForPrincipal(Services.scriptSecurityManager.getCodebasePrincipal(Services.io.newURI("http://µBlock", null, null)), '');
```

**Comment by gorhill** [comment]
@Deathamns So then I guess it's a matter of having a `vAPI` method to return "the localStorage object of the extension"?

**Comment by Deathamns** [comment]
@gorhill Yeah.

**Comment by gorhill** [comment]
For Firefox, Safari, this will be supported when #1010, #1011 are resolved.

**Comment by ozar** [comment]
Just noticed the dashes next to each filter category and gave them a try and they seem to be collapsing/working perfectly.  Thank you for the filters page enhancement.
