### ISSUE TITLE
[ABP Japanese filters] Blocking elements it shouldn't be?

### ISSUE THREAD

**Issue by lucasyvas** [uBlock-LLC/uBlock#793]
I'm on Amazon (.ca, to be specific) and I'm trying to click on details next to pricing. This by default appears to want to open a popup. uBlock is blocking the content, causing the window to close in the blink of an eye... why is this? This behaviour seems too intrusive for blocking and I've seen it happen on other sites too, simply breaking functionality. I'm having a hard time finding if you can actually let this through somehow.

![screen shot 2015-02-14 at 12 44 02 pm](https://cloud.githubusercontent.com/assets/3365616/6200992/3510e6ce-b447-11e4-98ca-d54623bc01a4.png)

Using Chrome for Mac, latest.

![screen shot 2015-02-14 at 12 56 00 pm](https://cloud.githubusercontent.com/assets/3365616/6201038/e42c9b20-b448-11e4-8b14-4f88de76a205.png)

**Comment by gorhill** [comment]
Give me a specific URL please. Also, which filter lists aside the default one.

**Comment by gorhill** [comment]
OK I tried randomly to find a URL (easier when provided by submitter, to avoid guessing): http://www.amazon.ca/gp/product/B00NZTHGN2/ref=s9_pop_gw_g107_i1?pf_rd_m=A3DWYIK6Y9EEQB&pf_rd_s=center-2&pf_rd_r=0P53ERNWYSD6YK2W0GHD&pf_rd_t=101&pf_rd_p=1375923562&pf_rd_i=915398

I clicked "Details" and the popup opened fine with default filter lists. So you will have to tell me how your settings differ from the default ones.

**Comment by chrisaljoudi** [comment]
Right. @vasilakopoulos it'd be great if you can share what browser you're using, too.

**Comment by lucasyvas** [comment]
Updated OP with browser.

I have like... every third party blocking filter enabled. No custom blocking rules whatsoever. That probably won't help you narrow it down... Should I just try and literally stab through it until I find which one it is? I guess it's not an issue with the blocker itself then.

**Comment by gorhill** [comment]
> Should I just try and literally stab through it until I find which one it is?

No. I want to know the filter lists you have enabled.

If you have dynamic filtering rules, provide them also.

Need accurate, specific details, this will ensure quick resolution.

**Comment by lucasyvas** [comment]
Will exported settings help you? Easier than copy/pasting all names from the settings ;)

Like I said, off of a fresh extension install, I have every setting in the third party filter tab ticked to yes. Everything else is default. No dynamic stuff.

https://drive.google.com/file/d/0B6SJ2BDiX2W-TmM0NFJQY2lsUFE/view?usp=sharing

**Comment by gorhill** [comment]
Enabling all the filter lists is asking for trouble, I can't provide support for 3rd-party filter lists, let alone all single one of them. Many of them might be of dubious quality on top of all this, the issue here being a proof of this. I can't even right-click to open a link.

**Comment by gorhill** [comment]
ABP Japanese filters: `^pop-$popup`.

**Comment by gorhill** [comment]
As per ABP filter semantic, `^pop-` should not have matched the `&pop-` in `http://www.amazon.ca/gp/help/customer/display.html/ref=mk_sss_dp_1?ie=UTF8&pop-up=1&nodeId=918742`:

> Separator character is anything but a letter, a digit, or one of the following: `_-.%`.

**Edit:** Never mind: `^` matches `&`, so the problem is in the filter list.

**Comment by lucasyvas** [comment]
I found it already. I shut it off for now (or forever).
