### ISSUE TITLE
Add a hotkey for element picker mode

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#794]
Using the element picker can be currently quite slow and cumbersome because as per [the wiki](https://github.com/gorhill/uBlock/wiki/Element-picker) you need to "open the extension's popup menu, and click the small "eye-dropper" icon" every time you want to add a new custom filter rule.

Adblock Edge/Plus have [Element Hider Helper](https://addons.mozilla.org/en-US/firefox/addon/elemhidehelper/) that have a nice hotkey by default.

**Comment by gorhill** [comment]
You can also right-click and click "Block element".

**Comment by Havokdan** [comment]
I agree with feature request.

**Comment by mzso** [comment]
This would certainly make life easier.

**Comment by gorhill** [comment]
Duplicate of #256.

**Comment by robsonreisunb** [comment]
I need this hotkey
