### ISSUE TITLE
Mac Firefox Count Display

### ISSUE THREAD

**Issue by ZeldaZach** [uBlock-LLC/uBlock#796]
The counter on Mac OS X 10.10.2 (Yosemite) seems to extend down into the bookmarks bar and isn't customizable to either disable it or move it.

![screenshot 2015-02-14 22 09 05](https://cloud.githubusercontent.com/assets/7460172/6201942/1ced4de0-b496-11e4-9b9a-7bbea41a9c20.png)

A potential idea is to move the counter to a location similar to Ghostery's (next to the icon higher up) or have a configurable option to disable the visible display of how many things were blocked per page.

**Comment by Snapy** [comment]
It's a known issue (see #545 and [this comment](https://github.com/gorhill/uBlock/issues/550#issuecomment-70679251) from Deathamns).
You can disable the icon count in the settings.

**Comment by gorhill** [comment]
Dup of #545.
