### ISSUE TITLE
Someday: any possibility of support for AdNauseam?

### ISSUE THREAD

**Issue by wolftune** [uBlock-LLC/uBlock#798]
I suspect the way uBlock works, this is not possible, but it would be a someday-maybe ideal to be able to work in conjunction with [AdNauseam](https://dhowe.github.io/AdNauseam/) (which I just learned about and haven't used but support somewhat in principle)

**Comment by Mikey1993** [comment]
Seems very interesting concept.
I think this does fit the uBlock philosophy of web tracking, so I support this for the long run.

**Comment by gorhill** [comment]
Regardless of how uBlock works, I think this is a terrible idea. The last thing I want is to leave a trace in a log on a remote server I consider to be a nuisance. AdNauseam defeats this purpose.

**Comment by wolftune** [comment]
I think it's perfectly fine to reject this, I just want to be clear: the idea isn't that this is good for you individually. The goal is to _poison_ the ad-network data. On a social level, it's positive. On an individual level, it's better not to run this at all. I think it would be nice to offer it. But I really don't feel strongly.

**Comment by ghost** [comment]
Open it, at least the source code is available. That's why I'm using it not ABP.
So to poison the adnetworks it would be great to let users decide with open source-solutions.
