### ISSUE TITLE
[Firefox] [request] Update url

### ISSUE THREAD

**Issue by iripu** [uBlock-LLC/uBlock#799]
Please add update url in "install.rdf". I use the dev build of Youtube Center, which has the following in "install.rdf" and it updates automatically:

`<em:updateURL>https://raw.github.com/YePpHa/YouTubeCenter/master/dist/firefox-update.rdf</em:updateURL>`

This way it can be updated automatically even though it's not in Mozilla Addons Official repository.

**Comment by gorhill** [comment]
Doesn't this defeat the purpose of having extension code reviewed by the Mozilla team? This would mean the extension will never be marked as trusted. I want it reviewed and marked as trusted by the Mozilla team.

**Comment by bpwned** [comment]
Would you consider adding a dev version of the addon with the update URL? So volunteers can always check the latest version before it hits AMO.

**Comment by gorhill** [comment]
I am still not too familiar with Firefox build... I suppose this means having a special `install.rdf` file for the dev version?

**Comment by bpwned** [comment]
Looks like it. Here's a diff between the AMO and the dev version of ABP:

```
$ diff abp-amo-install.rdf abp-dev-install.rdf
12c12
<     <em:version>2.6.7</em:version>
---
>     <em:version>2.6.7.3896</em:version>
18a19
>     <em:updateURL>https://adblockplus.org/devbuilds/adblockplus/update.rdf?reqVersion=%REQ_VERSION%&amp;id=%ITEM_ID%&amp;version=%ITEM_VERSION%&amp;maxAppVersion=%ITEM_MAXAPPVERSION%&amp;status=%ITEM_STATUS%&amp;appID=%APP_ID%&amp;appVersion=%APP_VERSION%&amp;appOS=%APP_OS%&amp;appABI=%APP_ABI%&amp;locale=%APP_LOCALE%&amp;currentAppVersion=%CURRENT_APP_VERSION%&amp;updateType=%UPDATE_TYPE%</em:updateURL>
602c603
<         <em:maxVersion>38.0</em:maxVersion>
---
>         <em:maxVersion>39.0</em:maxVersion>
610c611
<         <em:maxVersion>38.0</em:maxVersion>
---
>         <em:maxVersion>39.0</em:maxVersion>
618c619
<         <em:maxVersion>2.35</em:maxVersion>
---
>         <em:maxVersion>2.36</em:maxVersion>
626c627
<         <em:maxVersion>38.0</em:maxVersion>
---
>         <em:maxVersion>39.0</em:maxVersion>
634c635
<         <em:maxVersion>38.0</em:maxVersion>
---
>         <em:maxVersion>39.0</em:maxVersion>
```
