### ISSUE TITLE
Update lists manually?

### ISSUE THREAD

**Issue by JBey4you** [uBlock-LLC/uBlock#8]
I was wondering: when do the list are updated? Since we can't manually do it. Plus, there's no indicator. When you to the third tab, it says "À jour" (I'm French, so I guess it's "Updated in english). But that's it.

Thanks!

**Comment by gorhill** [comment]
Bon pour le bénéfice de tous, je vais répondre en anglais.

When you launch the extension (by launching the browser), it updates whatever needs updating. Thereafter it will check for update every ~~5~~ 4 days. That's how it was implemented in HTTPSB, and I kept the code the same. But I think for uBlock it makes sense to reduce the delay to two or three days.

**Comment by gorhill** [comment]
Update button available at bottom of list in _About_ tab, when updates are available.
