### ISSUE TITLE
uBlock icon blurry in Firefox 35.0.1 on Windows 7

### ISSUE THREAD

**Issue by gocemitevski** [uBlock-LLC/uBlock#800]
The uBlock icon is very blurry for me on Windows 7 - in both the small/toolbar version and the large/hamburger menu size. Probably something to do with anti-aliasing.

Not sure if you follow these recommendations for the icon size:
https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#iconURL

**Comment by ozar** [comment]
Just a quick comment to note that I usually run Linux, but I'm on my Window 7 machine at the moment with Firefox 35.0.1, and the uBlock icon doesn't look blurry, but looks fine like it does in Linux.  Not sure why I'm unable to reproduce the blurry icon on my end.

**Comment by Deathamns** [comment]
The icon uses and SVG image, it shouldn't be blurry.

**Comment by gocemitevski** [comment]
Here are two screenshots that might help:

![screenshot 2](https://cloud.githubusercontent.com/assets/359855/6238593/a90c8472-b6fc-11e4-829d-d9f06e948cb9.png)
![screenshot 1](https://cloud.githubusercontent.com/assets/359855/6238594/a90fd51e-b6fc-11e4-8edd-a88ff8080180.png)

**Comment by Deathamns** [comment]
It may seem blurry because there is a white border around the octagon, and the browser renders like that. If you look at the Restart, HTTPS, and rainbow icons, those are really blurry.

**Comment by gorhill** [comment]
So if it's render as SVG in FF, there is nothing more to do.

**Comment by gocemitevski** [comment]
Of course there is something to do more. Improving the quality of the SVG icon is one for start.

Unfortunately I cannot make you care about this issue, if you don't.

Anyway, closing this issue does not mean it has been resolved.

**Comment by gorhill** [comment]
It was already worked on by a contributor in the past. I am guessing anybody could always find it inadequate no matter how much work is put into it, since SVG can be rendered in _any_ resolution.

**Comment by gocemitevski** [comment]
It is not that I'm being picky. If the default Firefox icons can be as sharp as they are, and the uBlock icon is not, then the uBlock icon can be improved.

Using SVG instead of PNG as Mozilla recommends, might also be part of the problem.
https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#iconURL

**Comment by gorhill** [comment]
> the icon can be up to 48x48 pixels

So it will be scaled down in the toolbar... and we are back to square one. But now with more issues since if the icon needs to be scaled up above 48px, it will be pixellated. SVG ensures resolution-independent rendering, a fixed-resolution icon create more rendering issues.

**Comment by gocemitevski** [comment]
Yes, I am aware of the benefits of using SVG in the first place. All I'm trying to say is that even the SVG icon can be further improved.

Is the SVG icon freely available? Is it on GitHub?

**Comment by pR0Ps** [comment]
@gocemitevski: The icons are in the repository in [this folder](https://github.com/gorhill/uBlock/tree/master/src/img).

**Comment by gocemitevski** [comment]
@pR0Ps thanks!

**Comment by gocemitevski** [comment]
Here is a version of the uBlock SVG icon with improved anti-aliasing.

https://github.com/gocemitevski/uBlock/commit/09863a6814ef84c2d0c3af5ca21d3335f98db1bd

**Comment by gorhill** [comment]
![whichone](https://cloud.githubusercontent.com/assets/585534/6257385/8a62723e-b78d-11e4-8dba-4905e1af5afd.png)

Random order: which one is best?

**Comment by gocemitevski** [comment]
Actually, wrong comparison. The 16px SVG icon has not been optimized yet. But still, the first icon looks slightly sharper than the second one. 

Anyway, until I create an optimized version of the 16px SVG icon, try comparing ublock.svg against ublock-fixed-aa.svg in larger sizes.
