### ISSUE TITLE
Block favicons

### ISSUE THREAD

**Issue by andoruB** [uBlock-LLC/uBlock#802]
I really like using uBlock, and so far I haven't had any problems with it, but one "feature" that I miss from ABE is being able to block favicons. There are some sites that like having animated favicons, and those usually consume quite a good deal of CPU here. I've tried looking at the page source and copying the link to the favicon itself and add it to the filters tab, but it does not work. Is it possible to add a feature to block those pesky favicons?

**Comment by gorhill** [comment]
`/favicon.ico$image` should work to block all favicons.

**Comment by andoruB** [comment]
I don't want to block all favicons, I just want to block specific ones on some websites.

**Comment by gorhill** [comment]
Then use the domain option: `/favicon.ico$image,domain=example.com|example.org` etc.

**Comment by andoruB** [comment]
Doesn't work, this is what I added under "My filters" tab:
||/favicon.ico$image,domain=cvgm.net

I've also tried this one, same thing happens:

||/static/favicon.ico$image,domain=cvgm.net

**Comment by gorhill** [comment]
Why are you using double pipe `||`? You are creating an impossible filter. Use the one I suggested.

**Comment by andoruB** [comment]
All the other filters were having double pipes so I thought this one required it as well. Didn't think of removing them. Now it works, thanks!

**Comment by andoruB** [comment]
I take that back, the favicon popped up again without doing anything to the filter list.

**Comment by gorhill** [comment]
Probably because the network request was made [behind-the-scene](https://github.com/gorhill/uBlock/wiki/Behind-the-scene-network-requests) -- this is common with net requests for `favicon`.

**Comment by andoruB** [comment]
Okay, I found the link to the behind-the-scene network request, what do I do with it? I tried adding it to the filter list but that hasn't done anything, so I guess that's not what I'm supposed to do.
The filtering section of that linked wiki page isn't clear enough.

EDIT: Forgot to mention that I cannot "select" entries in the behind-the-scene list

**Comment by gorhill** [comment]
You shouldn't play with behind-the-scene unless you don't mind breaking important parts of your browser, like auto-update, or having all extensions work properly. It's not allowed to modify behind-the-scene unless you tick advanced users. But if you mess up things, you are on your own. At this point, assume there is no way to filter with 100% certainty favicons, and I certainly do not plan to support such a edgy feature.

**Comment by ghost** [comment]
@andoruB: clear browser cache (ctrl+shift+del) - works in Firefox.

**Comment by andoruB** [comment]
@gorhill: I don't see what does auto-update have to do with favicons. I wasn't going to blacklist all behing-the-scene request, just this one specific request.  
@gwarser: thanks, that works but only temporarily, after browsing a few pages on the site I get the annoying favicon again... (also ctrl+shift+del seems to bring up the Clear Recent History window instead).
Also I set the Cache size in Firefox on 0MB... weird how it still caches stuff.

**Comment by gorhill** [comment]
>  I wasn't going to blacklist all behing-the-scene request, just this one specific request

If you un-whitelist `behind-the-scene`, all requests will become candidate for filtering.
