### ISSUE TITLE
[Chromium/Linux] Element picker stalls when launched from context menu

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#803]
Issue on Chromium 40/Linux Mint Cinnamon.

"Stalls" = mouse cursor doesn't change shape, the picker's dialog box doesn't react to being hovered.
A simple click anywhere in the page un-stalls it.

No such issue on Firefox, and as per @Deathamns, "Chrome 40, Chromium 42, Nightly 38, Firefox 24 are working fine". ([Ref](https://github.com/gorhill/uBlock/commit/2642d5aa9252dfa76fe2708c2a65a87d37199bfc#commitcomment-9748840))

If anybody else has the same issue, please report OS/browser versions.

**Comment by ghost** [comment]
If you are talking about an hourglass then the same here. Crossbar comes up with eyedropper. However, with context menu, no problem creating the rules despite the hourglass. 

Mint Mate/ Firefox 35.0.1

**Comment by Deathamns** [comment]
The hourgalss is okay, that just indicates the waiting for a user action.

**Comment by ghost** [comment]
@Deathamns 

oops, Thanks.
