### ISSUE TITLE
URL of the Japanese filter changes again

### ISSUE THREAD

**Issue by xupefei** [uBlock-LLC/uBlock#805]
Hello,
The URL of AdBlock Japanese filter has now changed to `https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt`, as written in the last update of original list (Line 7 in `https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abp_jp.txt`).

Also, will you consider to process the `! Redirect:` command in filter list to avoid changing URLs manually?

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock

Please close this issue.
