### ISSUE TITLE
fanboy's thirdparty fonts filters list

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#808]
The extension lacks an option for fanboy's third party listed of this page: https://www.fanboy.co.nz/filters.html

**Comment by chrisaljoudi** [comment]
See [this comment](https://github.com/gorhill/uBlock/issues/649#issuecomment-73845212).

You can always just add the URL to the list, by the way:

![Screenshot](http://chrisly.me/image/473v3g0K1M1K/Image%202015-02-15%20at%205.17.58%20PM.png)
