### ISSUE TITLE
 Block chat

### ISSUE THREAD

**Issue by StVol33** [uBlock-LLC/uBlock#815]
http://www.igrul-ka.ru/ -block chat

**Comment by gorhill** [comment]
Can't make anything out of this two-word-one-URL bug report.

**Comment by StVol33** [comment]
На этом сайте блкируется чат! При попытке снять ограничения-  перестают работать "мои фильтры". В версии 0.8.6.0- это работало!

**Comment by Mikey1993** [comment]
> На этом сайте блкируется чат! При попытке снять ограниченияя перестают работать "мои фильтры". В версии 0.8.6.0- это работало!

My translation:

`On this site the chat is being blocked! When attempting to remove the blockage, the "My filters" are cease to work. In version 0.8.6.0 - it worked!`

**Comment by Deathamns** [comment]
I can't select the chat frame with element picker, if that is the problem.
`SyntaxError: An invalid or illegal string was specified   element-picker.js:357`

**Comment by Deathamns** [comment]
console log:
`
"#mchatIfm2"
"div"
"strong"
".box"
"http:"
`

**Comment by Mikey1993** [comment]
Right, I get this in the console after selecting the chat frame:
`Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Element': ':scope > http:' is not a valid selector.`

**Comment by Deathamns** [comment]
There is something like this in the source...
`<http: games-for-girls.ucoz.ru="" news="" rss=""><div class="box"><h3><span style="color: rgb(243, 42, 143)... </http:>`

**Comment by StVol33** [comment]
Должен ли я что-то добавить  в описании проблемы?

**Comment by gorhill** [comment]
Looks like a bug in the page. Not sure uBlock should start to ballet-dance around such messy HTML.

**Comment by gorhill** [comment]
@StVol33 нет

**Comment by StVol33** [comment]
Прошу объяснить: если диалог закрыт- то проблема исправиться или "Not sure uBlock should start to ballet-dance around such messy HTML"))

**Comment by gorhill** [comment]
The fix was trivial, so I didn't mind it. If it had been non-trivial, I would probably have not bothered fixing it.

**Comment by Deathamns** [comment]
@StVol33 As a workaround for now, manually add this to your filters: `||www.igrul-ka.ru/mchat/`

**Comment by StVol33** [comment]
Не работает!

**Comment by StVol33** [comment]
![2015-02-16_20-22-12](https://cloud.githubusercontent.com/assets/11031379/6216286/a1704570-b619-11e4-9f8f-eb31ffbbb5e4.png)
![2015-02-16_20-22-48](https://cloud.githubusercontent.com/assets/11031379/6216289/a8f8c290-b619-11e4-92ae-e40be9b7e16c.png)

**Comment by Deathamns** [comment]
I don't see the chat on your screenshot, so it's работаетing.
If you want to block the other two image, then:
`||www.igrul-ka.ru/graffiti/1/smajlik.gif`
`||www.igrul-ka.ru/graffiti/4/govor-ka.jpg`

**Comment by StVol33** [comment]
Должно быть так:
![2015-02-16_20-33-41](https://cloud.githubusercontent.com/assets/11031379/6216660/2c2269d4-b61d-11e4-9a64-dd7f8379b081.png)

**Comment by StVol33** [comment]
0.8.8.1
![2015-02-16_20-38-08](https://cloud.githubusercontent.com/assets/11031379/6216748/cede6b3c-b61d-11e4-8874-de16dddf3ab4.png)
![2015-02-16_20-33-41](https://cloud.githubusercontent.com/assets/11031379/6216760/de30a104-b61d-11e4-8d11-d5d7dca96183.png), хотя
![2015-02-16_20-34-27](https://cloud.githubusercontent.com/assets/11031379/6216785/27f215d4-b61e-11e4-995f-0c09fbf565f9.png)
![2015-02-16_20-37-01](https://cloud.githubusercontent.com/assets/11031379/6216792/39cd9328-b61e-11e4-8884-d648e8e6eeea.png)

0.8.6.0
![2015-02-16_20-36-18](https://cloud.githubusercontent.com/assets/11031379/6216868/05767544-b61f-11e4-9c16-e0de908a3b30.png)
![2015-02-16_21-03-56](https://cloud.githubusercontent.com/assets/11031379/6216924/7a78d058-b61f-11e4-81aa-a61c0b450701.png) настройки
![2015-02-16_20-59-43](https://cloud.githubusercontent.com/assets/11031379/6216943/b286798c-b61f-11e4-8511-ad7a448d90a1.png)
![2015-02-16_20-59-32](https://cloud.githubusercontent.com/assets/11031379/6217014/8f7d3a42-b620-11e4-8610-0851dfebc0bb.png)

**Comment by gorhill** [comment]
Why `www.igrul-ka.ru www.igrul-ka.ru * allow`? This [cancels cosmetic filtering](https://github.com/gorhill/uBlock/issues/689) on `www.igrul-ka.ru`.

**Comment by StVol33** [comment]
Все настройки я делал в 0.8.6.0 и там всё работало, но при обновлении до 0.8.8.1 начались проблемы! И при добавлении www.igrul-ka.ru/mchat/ в " белый список" блокировка продолжается!

**Comment by gorhill** [comment]
We need a translator, I have no clue what the problem is.

**Comment by 9seconds** [comment]
@gorhill he says: "I've set everything in 0.8.6.0 and it worked but after update to 0.8.8.1 problems happen! After I whitelist www.igrul-ka.ru/mchat/ uBlock still blocks!"

**Comment by gorhill** [comment]
Thanks.

I am still confused though. There is so many images, rules, I don't know what is expected to be there or not. And I don't see a filter for `www.igrul-ka.ru/mchat/`. What would be best is to tell me what he wants exactly, then I will say how to do it, rather than starts from his rules/filters and try to figure what he wants.

**Comment by Mikey1993** [comment]
I think he says that with 0.8.6.0 the chat with his rules didn't block the chat, but with 0.8.8.1, the chat is being blocked even though he added `www.igrul-ka.ru/mchat/` to the whitelist.

But I too don't see any `www.igrul-ka.ru/mchat/` filter in the images.
