### ISSUE TITLE
My filters

### ISSUE THREAD

**Issue by StVol33** [uBlock-LLC/uBlock#816]
В версии 0.8.8.1 не работают  "мои фильтры"  при создании  " моих правил" (см. №815 последний пост). В версии 0.8.6.0- работало корректно! При добавлении  www.igrul-ka.ru/mchat/ в " белый список"  блокировка продолжается!

**Comment by chrisaljoudi** [comment]
@StVol33 I don't know Russian — unless there's someone specifically that knows Russian, would you please submit this issue's description in English?

**Comment by heubergen** [comment]
@chrisaljoudi I take a translate tool and @StVol33 took reference to the issue  #815 last post:
In version 0.8.8.1 not working "my filters" when creating "my rules" (see No. 815 last post). In version 0.8.6.0 - worked correctly! Adding www.igrul-ka.ru/mchat/ in "white list" lock continues!

**Comment by yupi2** [comment]
Even though it would be best if issues are submitted in English, that won't always happen, so it may be helpful to use [Google](https://translate.google.com/) and/or [Bing's](https://www.bing.com/translator/) translating service.

> Version 0.8.8.1 don't work "my filters" {to create|for creating} "my rules" (see #815 last post). 0.8.6.0-version worked correctly! When you add www.igrul-ka.ru/mchat/ in "whitelist" the blocking continues!

**Comment by Mikey1993** [comment]
My translation (I know russian):

In version 0.8.8.1 the "My filters" not working when creating "My rules" (see #815 last post). In version 0.8.6.0- worked correctly! When adding  `www.igrul-ka.ru/mchat/` to "whitelist", the blocking continues!

Unfortunatly, I don't really understand what he means here, as he combines a lot of lists altogether in this report without concrete filters to really understand the problem thoroughly.

**Comment by StVol33** [comment]
"Unfortunatly, I don't really understand what he means here, as he combines a lot of lists altogether in this report without concrete filters to really understand the problem thoroughly"
0.8.6.0-  "My rules": www.igrul-ka.ru igrul-ka.ru \* allow
                                 www.igrul-ka.ru tir-strelok.3dn.ru \* block
               "My filters"- www.igrul-ka.ru###entryID983 > .eBlock > tbody > tr > td- working
0.8.8.1 "My rules": www.igrul-ka.ru igrul-ka.ru \* allow
                               www.igrul-ka.ru tir-strelok.3dn.ru \* block
             "My filters"- www.igrul-ka.ru###entryID983 > .eBlock > tbody > tr > td- does not work

**Comment by StVol33** [comment]
0.8.8.2 
![2015-02-17_12-43-45](https://cloud.githubusercontent.com/assets/11031379/6226094/06aad43a-b6a3-11e4-93cb-7be768c1942c.png)
but the problem persists, chat is blocked

**Comment by gorhill** [comment]
> `www.igrul-ka.ru###entryID983 > .eBlock > tbody > tr > td` does not work

Because `www.igrul-ka.ru igrul-ka.ru * allow`: `allow` on 1st-party hostname disable cosmetic filtering:

["Cosmetic filtering should be disabled if page is under dynamic filtering `allow` rule"](https://github.com/gorhill/uBlock/issues/689)

Use `www.igrul-ka.ru igrul-ka.ru * noop` instead.

**Comment by StVol33** [comment]
How to unlock chat?
www.igrul-ka.ru igrul-ka.ru \* noop- it does not make available to chat
What rule should I use?

**Comment by gorhill** [comment]
@StVol33 

_My filters_:

```
www.igrul-ka.ru###entryID983 > .eBlock > tbody > tr
@@||www.igrul-ka.ru/mchat/
```

_My rules_:

```
www.igrul-ka.ru igrul-ka.ru * noop
www.igrul-ka.ru tir-strelok.3dn.ru * block
```

**Comment by StVol33** [comment]
gorhill!
Great! Added@@|| www.igrul-ka.ru/mchat/ in "my Filters- it works, chat unlocked! Do I need to add www.igrul-ka.ru igrul-ka.ru \* noop- if without it all works!

**Comment by gorhill** [comment]
@StVol33 No, you do not really need `www.igrul-ka.ru igrul-ka.ru * noop` if you were using it just to try solving the chat problem.

**Comment by StVol33** [comment]
Thank you very much! Problem solved!))
