### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by allanblatt** [uBlock-LLC/uBlock#817]
Enjoying uBlock for Firefox very much and have switched from ABP.

Does uBlock for Firefox auto update itself.  I'm on 0.8.7.0.  I know my son's Chrome version updates but I'm not sure if that's uBlock or Chrome doing the updating.

**Comment by gorhill** [comment]
Chrome store and AMO updates on their own terms. I know Chrome store says it may take up to 24h before one receives an update. I suppose AMO is something like that too, to spread the bandwidth of updating everybody.

**Comment by Mikey1993** [comment]
To add on what @gorhill said:

This depends on where you got the extension.

Generally the browser handles the updating, and in any case this is true only if you install it from the Chrome store or AMO.

If you've got the extension from Github and installed it manually, you won't get automatic updates.

**Comment by Deathamns** [comment]
@Mikey1993 If he installed the Firefox version from GitHub, he we'll still get updates from AMO (once it's reviewed).

**Comment by Mikey1993** [comment]
@Deathamns Ah, sorry for misleading.

**Comment by allanblatt** [comment]
How often is it reviewed? 0.8.8.0 is still listed on https://addons.mozilla.org/en-US/firefox/addon/ublock/ .
