### ISSUE TITLE
Blocked ad returns

### ISSUE THREAD

**Issue by Steve-Wellens** [uBlock-LLC/uBlock#818]
On this page http://minnesota.cbslocal.com/2015/02/16/utah-faribault-coaches-address-state-dance-controversy/ I block "This Week's Circulars".   The ads disappear and a filter is created.  

How ever, when I refresh the page, the ads return.  It happens on all pages of the site.

**Comment by Mikey1993** [comment]
Can you upload an image showing the section you are trying to block?

**Comment by Steve-Wellens** [comment]
OK, here it is selected by uBlock:
]
![abfthy3 1](https://cloud.githubusercontent.com/assets/11036606/6220978/625551da-b602-11e4-8e25-70347956616e.png)

**Comment by Mikey1993** [comment]
Actually, I am able to not see this section of the page with only static rules as "circularhub.com" is being blocked on this page on my side (I can see the section on Chrome when whitelisting the site/`circularhub.com` domain on this site, but never get this one on FF).

Anyhow, try adding this rule manually to the "My rules" list in the dashboard:
`minnesota.cbslocal.com##iframe[id*="wm_iframe_"]`

**Comment by gorhill** [comment]
What are your settings? All details please: filter lists, custom filters, dynamic rules if any.

I don't see that section with default filter lists.

**Comment by gorhill** [comment]
@Mikey1993 This section is filtered out already with the EasyList rule `##.cbs-ad-unit-wrapper`.

**Comment by Mikey1993** [comment]
@gorhill Can you confirm this section isn't showing to you too on FF even after whitelisting the site?

**Comment by gorhill** [comment]
It's not, as said there is a generic cosmetic filter in EasyList which filters it out. I suspect OP whitelisted the site to create a specific filter than forgot to un-whitelist the site.

**Comment by Mikey1993** [comment]
> It's not, as said there is a filter in EasyList which filter it out.

No, what I've meant was to check if the site detects that you are using FF, and not serving this section to it becasue of that, or because of some other heuristics.

Whitelisting should disable network and cosmetic filters altogether, right?
If so, it's odd that on FF, the section doesn't show even after whitelisting the site, but on Chrome it does.

So, After a quick look at the network logging,
I definitely see other servings of the site when adding
`minnesota.cbslocal.com circularhub.com * allow` 
to "My rules" list, so this seems to not affect FF.

**Comment by Steve-Wellens** [comment]
This was my white list content:

`behind-the-scene`
`chrome-extension-scheme`
`chrome-scheme`
`minnesota.cbslocal.com`
`opera-scheme`

I don't know how `minnesota.cbslocal.com` got in there.   I had no reason to do that.

I took it out and it is working now.   The only issue left may be why does uBlock hide the element if it is going to show it later.

Thanks!

**Comment by gorhill** [comment]
> I had no reason to do that

Yes you had: to reveal the element which is hidden by default by EasyList. You created a specific cosmetic filter because this way the section will be hidden before the page renders, while the generic `##.cbs-ad-unit-wrapper` in EasyList _may_ cause the section to be removed after the page renders.

**Comment by chrisaljoudi** [comment]
@Steve-Wellens 

> The only issue left may be why does uBlock hide the element if it is going to show it later.

Because when you add it using the element picker, it gets explicitly hidden (ignoring the whitelist because the page is already loaded).

@gorhill maybe it'd be helpful to disable the element picker on tabs with whitelisted sites? I can implement that if you'd like.

**Comment by Steve-Wellens** [comment]
@chrisaljoudi 

> maybe it'd be helpful to disable the element picker on tabs with whitelisted sites?

IMHO: That could drive people crazy wondering why it is disabled.   It might be more user friendly to let them select an element and then WARN them that the site is white-listed and the element will not be hidden.

**Comment by gorhill** [comment]
> disable the element picker on tabs with whitelisted sites

No. The first implementation did this, but it's useful to have it available to create specific cosmetic filters, which are better than generic ones. When a site is whitelisted, there are plenty of visual hints about this: icon is grayed, power button is grayed.

**Comment by chrisaljoudi** [comment]
@gorhill 

> icon is grayed

My fault — that's currently missing from Safari. :( Will fix ASAP.

**Comment by chrisaljoudi** [comment]
Closed via 1a55ecfbcd1b0c4e1870b2305b96616c6cb7ca11.
