### ISSUE TITLE
Wiki says that it can be edited by anyone, but I can't do it

### ISSUE THREAD

**Issue by anewuser** [uBlock-LLC/uBlock#819]
[This page](https://github.com/gorhill/uBlock/wiki/Advanced-user-features) says that:

> it's a wiki, you can edit without asking permission -- I will just ensure all is technically accurate

But I see no "edit" button on it.  I do see it on [another project wiki](https://github.com/gollum/gollum/wiki) though.

I wanted to change "these project"  to "these projects" on the [Donations page](https://github.com/gorhill/uBlock/wiki/Why-don%27t-you-accept-donations%3F). 

By the way, [an article about uBlock](https://en.wikipedia.org/wiki/UBlock) has been created on Wikipedia.

**Comment by gorhill** [comment]
[Somebody messep up earlier today](https://github.com/gorhill/uBlock/wiki/%C2%B5Block-vs.-ABP:-efficiency-compared/_compare/aba246517c25b393bb66462bc9b974e667419cd9...800cd36fc3fb3f22bd1780967171469eb6354bff), and this cause an external link to no longer function. As the wiki is becoming bigger, I can't keep track of all edits if someone mess up.

**Comment by gorhill** [comment]
I will re-activate outside editing, but if this keeps happening I won't have choice to restrict.

**Comment by anewuser** [comment]
@gorhill thanks. I've updated the [Advanced user features](https://github.com/gorhill/uBlock/wiki/Advanced-user-features) to reflect your policies about the wiki.
