### ISSUE TITLE
Chrome extension stopped working

### ISSUE THREAD

**Issue by garygreen** [uBlock-LLC/uBlock#82]
The ublock icon is in red and has stopped blocking ads for a few days (it use to work great). Tried toggling the power button but still nothing. Any known issues or is this a silly thing I'm doing wrong?

**Comment by gorhill** [comment]
It works fine from here. Sometimes disabling and re-enabling an extension bring it back to life, as rarely I have seen an extension breaking for no reason. It does look sometimes, rarely, chromium/chrome updates can break extensions, I've seen this happen, and re-installing usually as a last resort work.

As I am updating often lately maybe it's more subject to that kind of problem.

**Comment by gorhill** [comment]
By the way, if you are comfortable with the dev console for extensions (only available in "Developer mode"), maybe looking if there is anything is reported in there for uBlock.

**Comment by gorhill** [comment]
What browser/version are you using?

**Comment by garygreen** [comment]
Thanks for the help Raymond! I've reinstalled the chrome extension and it's magically brought it back to life again! Strange that you've experienced this with extensions randomly breaking from the chrome store (personally I've never had a extension break like this and had to reinstall) anyhow all is good now! =]

**Comment by garygreen** [comment]
(will keep an eye on it and let you know if it happens again)

**Comment by gorhill** [comment]
> Strange that you've experienced this with extensions randomly breaking from the chrome store 

Not sure how all of this work in the browser, but I suspect something become out of sync internally with whatever data the browser caches about an extension. Often I have to click "Reload" (available for extensions loaded manually on the "Extensions" page in "Developer mode") to force the browser to use the latest code which was changed, but still not seen by the browser despite disabling/enabling the extension. For extensions loaded from the store, re-installing is the equivalent of force-reloading a locally installed extension.

**Comment by garygreen** [comment]
At home the extension broke as well (the one I re-installed to get it working again was on my work machine). Before I reinstall uBlock at home, is there anything I can do in the chrome debugger to check where the script is failing to 'kick things off' ? e.g. any breakpoints I can set in `contentscript-start.js` and `contentscript-end.js` ? (btw I see no errors in the chrome console related to the extension)

**Comment by gorhill** [comment]
> btw I see no errors in the chrome console related to the extension

I suppose it's too late now? I would want to know if there is something in the console output of the background page itself -- accessible when _"Developer mode"_ is enabled:

![to-forum](https://cloud.githubusercontent.com/assets/585534/3632947/30f7d320-0ed1-11e4-823c-997bb3d4d11f.png)

`contentscript_*.js` are just the injected scripts, not the core of the extension.

**Comment by garygreen** [comment]
Got it. These are the errors that appear.

![image](https://cloud.githubusercontent.com/assets/1702638/3633141/f5d5f4e2-0ed6-11e4-98c8-b5c6c6d904ea.png)

**Comment by gorhill** [comment]
Crap.

Thank you very much. There is indeed a bug in the code, I need to fix asap.

The bug shows up if one disable cosmetic filtering. Did you previously uncheck _"Parse and enforce Adblock+ element hiding filters."_?

**Comment by kurtextrem** [comment]
About the beta test thing: I guess you could use the webstore feature.

**Comment by garygreen** [comment]
@gorhill Thanks very much! Yes I did disable the "Parse and enforce Adblock+ element hiding filters" 

Glad the bug has been fixed. Will the chrome app update automatically?

**Comment by garygreen** [comment]
It has updated automatically and started working again! Thanks Raymond! :)
