### ISSUE TITLE
Videos blocked on zie.nl

### ISSUE THREAD

**Issue by zilexa** [uBlock-LLC/uBlock#821]
On this Dutch news site, videos are being blocked by uBlock. It is just completely black with no controls. When I disable ublock for the particular site, the video plays (usually showing video advertising first). 
Example:
http://www.zie.nl/video/algemeen/Aboutaleb-in-Witte-Huis-bij-top-radicalisering/yunzyptfgxy1

**Comment by gorhill** [comment]
Something in Peter Lowe's is preventing the video from loading. Narrowing down..

**Comment by gorhill** [comment]
The site need Google Analytics. Fixing.
