### ISSUE TITLE
Causes issues with musixmatch.com

### ISSUE THREAD

**Issue by neo01124** [uBlock-LLC/uBlock#822]
Clicking on various links on the homepage leads to this trace:

Uncaught ReferenceError: cxApi is not definedtrack-06f66939698fd4472dcf.js:18 N.createClass.rendercommon-55238ea648dce38e44eb.js:9 (anonymous function)common-55238ea648dce38e44eb.js:9 (anonymous function)common-55238ea648dce38e44eb.js:31 _.Mixin._mountChildByNameAtIndexcommon-55238ea648dce38e44eb.js:31 _.Mixin._updateChildrencommon-55238ea648dce38e44eb.js:31 _.Mixin.updateChildrencommon-55238ea648dce38e44eb.js:31 o.Mixin._updateDOMChildrencommon-55238ea648dce38e44eb.js:31 (anonymous function)common-55238ea648dce38e44eb.js:11 m.Mixin.performUpdateIfNecessarycommon-55238ea648dce38e44eb.js:11 m.Mixin.receiveComponentcommon-55238ea648dce38e44eb.js:31 o.Mixin.receiveComponentcommon-55238ea648dce38e44eb.js:9 (anonymous function)common-55238ea648dce38e44eb.js:9 R._performComponentUpdatecommon-55238ea648dce38e44eb.js:9 R.performUpdateIfNecessarycommon-55238ea648dce38e44eb.js:9 scommon-55238ea648dce38e44eb.js:12 a.performcommon-55238ea648dce38e44eb.js:12 a.performcommon-55238ea648dce38e44eb.js:9 g.performcommon-55238ea648dce38e44eb.js:9 (anonymous function)common-55238ea648dce38e44eb.js:12 a.closeAllcommon-55238ea648dce38e44eb.js:12 a.performcommon-55238ea648dce38e44eb.js:71 p.batchedUpdatescommon-55238ea648dce38e44eb.js:9 lcommon-55238ea648dce38e44eb.js:11 m.Mixin.replacePropscommon-55238ea648dce38e44eb.js:11 m.Mixin.setPropscommon-55238ea648dce38e44eb.js:27 (anonymous function)track-06f66939698fd4472dcf.js:19 U.indexcommon-55238ea648dce38e44eb.js:27 ocommon-55238ea648dce38e44eb.js:60 (anonymous function)common-55238ea648dce38e44eb.js:56 (anonymous function)common-55238ea648dce38e44eb.js:1 window.webpackJsonptrack-06f66939698fd4472dcf.js:1 (anonymous function)

The url gets changed to the url of the clicked link but the page doesn't load.

**Comment by neo01124** [comment]
Also logs me out when clicking on a link. On disabling the extension all the problems get fixed.

**Comment by neo01124** [comment]
Using Chrome Version 40.0.2214.111 (64-bit) + ubuntu 14.04

**Comment by nickdima** [comment]
`cxApi` is a function provided by google analytics so my guess is that uBlock is blocking GA
