### ISSUE TITLE
Popup UI usability issues

### ISSUE THREAD

**Issue by grigorig** [uBlock-LLC/uBlock#823]
uBlock works great, but the popup UI really needs some work IMHO. For instance, it's not really clear what the power button does without reading the tooltip text. I think a simple text menu would be more suitable.
I see similar problems with the other icons in the menu. The semantics are not clear and neither is what those tools are useful for. Also, the statistics are displayed very prominently, but most users aren't going to be interested in this. And I have yet to understand what "domains connected" actually means.

What do you think?

**Comment by gorhill** [comment]
I think that however the UI is designed, inevitably someone will open an issue about how the popup UI needs to be reworked.

Bottom-line: I like it this way, I do not intend to change anything anymore: this is uBlock, it's how it looks.
