### ISSUE TITLE
Make "3rd-party filters" tab work on Conkeror

### ISSUE THREAD

**Issue by scottjad** [uBlock-LLC/uBlock#827]
Hi,

In case you're not aware, there's a xulrunner based web browser called Conkeror that has a small but passionate community. Most of us use the ABP extension for Firefox. With ABP on Conkeror the normal Firefox UI for blocking and unblocking does not work but the UI under Extensions > Preferences does work.

We were very excited to hear about the Firefox port of uBlock and many of us have been anxious to use it in Conkeror. Unfortunately it does not quite work as-is, and I realize that Conkeror is probably not a high priority for you, but I wanted to reach out to you just in case it might be possible to make its basic functionality work with only minor changes. Perhaps somewhere you are calling a Firefox API where a Xulrunner one would work.

Right now most things under the Extensions > Preferences menu seem to work, or at least display fine, but the most crucial one, the "3rd-party filters" does load entirely and is unusable.

This is what the window looks like:
![uBlock Preferences in Conkeror](http://i.imgur.com/1hTRf1A.jpg)

When I first open the uBlock Preferences, before changing any tabs, this is the console output I get:

```
System JS : ERROR chrome://ublock/content/frameModule.js:37 - NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIInterfaceRequestor.getInterface]
Console error: [JavaScript Error: "NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIInterfaceRequestor.getInterface]" {file: "chrome://ublock/content/frameModule.js" line: 37}]
  Category: system javascript
System JS : ERROR chrome://ublock/content/frameModule.js:37 - NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIInterfaceRequestor.getInterface]
Console error: [JavaScript Error: "NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIInterfaceRequestor.getInterface]" {file: "chrome://ublock/content/frameModule.js" line: 37}]
  Category: system javascript
JavaScript error: chrome://ublock/content/js/vapi-client.js, line 90: addMessageListener is not defined
Console error: [JavaScript Error: "ReferenceError: addMessageListener is not defined" {file: "chrome://ublock/content/js/vapi-client.js" line: 90}]
  Category: chrome javascript
```

When I click on the "3rd-party filters" tab, this is the console output I get:

```
JavaScript error: chrome://ublock/content/js/vapi-client.js, line 156: removeMessageListener is not defined
Console error: [JavaScript Error: "ReferenceError: removeMessageListener is not defined" {file: "chrome://ublock/content/js/vapi-client.js" line: 156}]
  Category: chrome javascript
System JS : ERROR chrome://ublock/content/frameModule.js:37 - NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIInterfaceRequestor.getInterface]
Console error: [JavaScript Error: "NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIInterfaceRequestor.getInterface]" {file: "chrome://ublock/content/frameModule.js" line: 37}]
  Category: system javascript
JavaScript error: chrome://ublock/content/js/vapi-client.js, line 90: addMessageListener is not defined
Console error: [JavaScript Error: "ReferenceError: addMessageListener is not defined" {file: "chrome://ublock/content/js/vapi-client.js" line: 90}]
  Category: chrome javascript
```

I tried downloading easylist.txt and then importing it on the "My filters" tab, and it filled the textarea but when clicking "Apply changes" I get this console output:

```
JavaScript error: chrome://ublock/content/js/vapi-client.js, line 140: sendAsyncMessage is not defined
Console error: [JavaScript Error: "ReferenceError: sendAsyncMessage is not defined" {file: "chrome://ublock/content/js/vapi-client.js" line: 140}]
  Category: chrome javascript
```

If you are easily able to make these features (and basic blocking, which we haven't been able to test without applying any filters) depend only on xulrunner and not Firefox then it would be greatly appreciated by the Conkeror community.

If you are able to resolve these issues so that uBlock works minimally on Conkeror, then please add this to the install.rdf so that it's easier for users to install in Conkeror:

```
        <!-- Conkeror -->
        <targetApplication>
          <Description>
            <id>{a79fe89b-6662-4ff4-8e88-09950ad4dfde}</id>
            <minVersion>0.1</minVersion>
            <maxVersion>9.9</maxVersion>
          </Description>
        </targetApplication>  
```

Thank you very much,
Scott

**Comment by gorhill** [comment]
By the look of it, Conkeror does not support messaging API required by uBlock, so that's kind of a big showstopper. Best is for a developer familiar with Conkeror to contribute a port, if possible to workaround the messaging issue.

**Comment by Deathamns** [comment]
Well, this is not only a problem with "3rd-party filters" tab, but the whole thing won't work if this [interface](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIContentFrameMessageManager) cannot be accessed.

Also, I got errors about `gBrowser` is undefined, which is essential in many cases, so I probably won't look further.

**Comment by chrisaljoudi** [comment]
Until this is deemed feasible.
