### ISSUE TITLE
Discrepancy concerning lists enabled by default

### ISSUE THREAD

**Issue by neitsab** [uBlock-LLC/uBlock#828]
Current `README.md#philosophy` says:

> EasyList, Peter Lowe's Adservers, EasyPrivacy are enabled by default when you install µBlock.

(dates from commit 9056f0c -- 12 Jan)

Meanwhile [Firefox addon page](https://addons.mozilla.org/en-US/firefox/addon/ublock/) says:

> Out of the box, these lists of filters are loaded and enforced:
> - EasyList
> - Peter Lowe’s Ad server list
> - EasyPrivacy
> - Malware domains
> - Long-lived malware domains
> - Malware Domains List

and [Chrome web store](https://chrome.google.com/webstore/detail/%C2%B5block/cjpalhdlnbpafiamejdnhcphjbkeiagm) has the same.

On the other hand after installing µBlock 0.8.8.1 in latest Firefox, I see the following additional lists enabled compare to `README`:
- My filters
- µBlock filters
  
  > # Needed to unbreak sites affected by out of the box lists
- µBlock filters – Privacy‎
  
  > # Experimental list: use only if you don't mind potential breakage, I just
  > # don't have the resource to deal with lists, I do it because blocking these 
  > # are in the interest of users.
  > #
  > # These filters make use of the `important` filter option, which purpose is
  > # to guarantee that a filter won't be overriden by exception filters.
- Malware Domains List
- Malware domains

Makes sense not to mention the two first ones in `README` IMO, the third one being enabled seems a bit more surprising due to the experimental flag, Malware Domains{ List,} should just be added to `README.md` and Long-lived malware domain withdrawn from extension pages. Can submit a PR for he first part if you wish.

Thanks a lot for your work, I really like the mindset in which you develop this extension and I hope its momentum will keep growing!

**Comment by gorhill** [comment]
I will remove "experimental", clearly that list has never been reported as breaking anything, it's only `addthis.com` so far in there. Given it's only one entry, not worth mentioning in the README.

**Comment by neitsab** [comment]
My feeling too :-)
