### ISSUE TITLE
Add preview to element picker

### ISSUE THREAD

**Issue by mzso** [uBlock-LLC/uBlock#829]
Hello!

I think this would greatly improve the usability of the picker. Now I need to save it and refresh the page. Which can be rather problematic if I forget the element's name and/or if the id/class is turns out to be generic and the page gets mostly hidden or broken.

**Comment by mzso** [comment]
It can also be hard to find the rule if I have a lot of them since there's no option to view the applied filters for the specific page I'm viewing.

**Comment by gorhill** [comment]
What is highlighted **is** the preview of what will be removed.

**Comment by mzso** [comment]
It would be nice to see the end results. It's not obvious what it might be.
It doesn't account for the case when other elements have the same class (".something"), or identifier, does it?

**Comment by gorhill** [comment]
Yes it does account for all that will be affected on the page. You can try it by manually entering a selector which you know apply to more than one element.

Example: try `##.author` on this very page.

**Comment by mzso** [comment]
Okay. Cool then.
