### ISSUE TITLE
chrome://extensions tab opens with options tab

### ISSUE THREAD

**Issue by mikhaelkh** [uBlock-LLC/uBlock#830]
When I right-click on uBlock icon, then select `options`, two tabs opens - `chrome://extensions` and `options` tabs.

**Comment by Deathamns** [comment]
Probably a side effect of [#685](https://github.com/gorhill/uBlock/issues/685#issuecomment-74094038).
You can open the options page directly if you click the header in the toolbar popup.

**Comment by kurtextrem** [comment]
Can't be fixed I guess and this behaviour is definitely better than needing to click twice to get where you want.

**Comment by gorhill** [comment]
Yes, I don't see what can be done: it's Chrome opening the _Settings_ tab because of its new extensions' _Options_ UI, to which all extensions _have_ to convert eventually. This is the way the browser is designed.
