### ISSUE TITLE
[Fanboy's Enhanced Tracking] Can't use fedex.com tracking without a dynamic rule

### ISSUE THREAD

**Issue by bbeardsley** [uBlock-LLC/uBlock#831]
Trying to hit:
https://www.fedex.com/apps/fedextrack/?action=track&cntry_code=us
to enter a tracking number and it does nothing (when 3rd party filters set to [gorhill's selected filters](https://github.com/gorhill/uBlock/wiki/Filter-lists:-gorhill)).

If I add a dynamic rule:
www.fedex.com \* 1p-script allow

It does work then.  Using ublock version v0.8.8.2

**Comment by gorhill** [comment]
What are your filter lists? Also, any dynamic rules? Any custom filters? What is the exact URL on that site where the problem occurs?

I've tried [here](https://www.fedex.com/apps/fedextrack/?action=track&trackingnumber=555555555&cntry_code=ca_english), and all seems to work -- though I have nothing to track. Using default filter lists there is barely anything blocked on that site.

Actually, with default filter lists, nothing is blocked for `fedex.com`, so you have something more than default settings, you need to tell me what.

**Comment by bbeardsley** [comment]
I removed all my filters and dynamic rules.  The exact url is above.  My filter lists are exactly what was checked on your [recommended filters wiki page](https://github.com/gorhill/uBlock/wiki/Filter-lists:-gorhill)
![block dashboard_2015-02-17_13-19-15](https://cloud.githubusercontent.com/assets/9709/6236400/b618ae7a-b6a7-11e4-8b3a-709f252aceb6.jpg)

**Comment by bbeardsley** [comment]
@@||images.fedex.com$script,domain=fedex.com

seems to work if I put that in my filters.

**Comment by ozar** [comment]
The issue appears to be with Fanboy's Enhanced Tracking List:

/scripts/mbox.
 /s_code.

**Comment by bbeardsley** [comment]
Yes you're right.  It's excluding two javascript files with those names but it looks like I just need the one.

@@||images.fedex.com/templates/components/apps/contentim/scripts/s_code$script,domain=fedex.com

**Comment by gorhill** [comment]
If you can report to EasyList maintainers, everybody would benefit the fix: https://forums.lanik.us/viewforum.php?f=64

**Comment by gorhill** [comment]
By the way:

> My filter lists are exactly what was checked on your recommended filters wiki page

I never recommended this. I just got tired to have to answer the recurring question about what filter lists I used. I do warn in there:

> Use at your own risks
