### ISSUE TITLE
Not working behind hotspot

### ISSUE THREAD

**Issue by maxxer** [uBlock-LLC/uBlock#832]
I was trying to login to an hotspot's captive portal, but Chrome was stuck in "Waiting for uBlock extension....".
The same happens with poor connection, generally when internet is not fully available browsing is impossible.

**Comment by gorhill** [comment]
If you have a poor internet connection, I am guessing the message `Waiting for uBlock extension...` could happen if uBlock tries to update assets in the background. Try disabling "auto update", this may help to get rid of that message (just a guess).

**Comment by gorhill** [comment]
I don't know what to do with this issue: uBlock can't fix network issues.

**Comment by maxxer** [comment]
an hotspot is not a network issue. If there is no network uBlock should give up trying to update and just return. Tomorrow I'll be near an hotspot, if you need further debug/testing I'll be happy to support! thanks

**Comment by gorhill** [comment]
> uBlock should give up trying to update and just return

It does give up. There is a 30s time out, then it gives up.

**Comment by maxxer** [comment]
I didn't probably wait that long. 30s when waiting to load the login page are a very long time...
I'll try tomorrow and report back. thanks again

**Comment by gorhill** [comment]
Note that it's a non-blocking time out. So even though Chrome may report that it's waiting on uBlock, uBlock is not blocking the browser.

**Comment by maxxer** [comment]
Yes, not blocking Chrome but the connection. Tried now cannot repro... I'm closing until I can get more info. thanks

**Comment by gorhill** [comment]
> not blocking Chrome but the connection

Just to be clear to prevent a new myth: uBlock does not block the connection either. I think the issue is more one of Chrome reporting in a confusing way when there are connection issues.
