### ISSUE TITLE
[EasyPrivacy] Can't sign into Navy Federal

### ISSUE THREAD

**Issue by mi7chy** [uBlock-LLC/uBlock#833]
Works great so far except I can't sign into:

https://www.navyfederal.org/

Or, click on the link to bring this up:

https://www.navyfederal.org/nfoaa-signin.php

Works if I disable uBlock or use ADP.  Thanks!

**Comment by my-password-is-password** [comment]
Might want to try the solution in issue https://github.com/gorhill/uBlock/issues/777

**Comment by gorhill** [comment]
Dup of #777.

If users reported it to [EasyPrivacy maintainers](https://forums.lanik.us/viewforum.php?f=64), it would be solved for everybody.
