### ISSUE TITLE
Not an issue...but praise...

### ISSUE THREAD

**Issue by JeremyWW** [uBlock-LLC/uBlock#834]
In the light of the discussions here about alternative browsers / compatibility with uBlock thereof I wanted to let you know about another, excellent, 64 bit Firefox 'clone' that I've come across - 'Cyberfox'. Not only does it fly but it also offers much more in the way of customisation, it's own interface or Australis on installation, and it's compatible with the current Firefox release of uBlock. You might also like to know that uBlock is receiving high praise in the Cyberfox forum:

https://8pecxstudios.com/Forums/viewtopic.php?f=4&t=789

**Comment by gorhill** [comment]
Nice to see it works as is with Cyberfox.
