### ISSUE TITLE
uBlock Updates

### ISSUE THREAD

**Issue by allanblatt** [uBlock-LLC/uBlock#835]
With respect to this email I got from Mike:

"@Mikey1993 If he installed the Firefox version from GitHub, he we'll still get updates from AMO (once it's reviewed)."

I am still not clear about updates to the Firefox version of uBlock.

https://addons.mozilla.org/en-US/firefox/addon/ublock/ shows an older 0.8.8.0 and states it hasn't been reviewed.

Does that mean that uBlock as an addon hasn't been approved and updates will never get pushed out by AMO, or that version 0.8.8.0 hasn't been approved yet but prior updates would be pushed out?

**Comment by Deathamns** [comment]
Reviewing on AMO may take weeks, and only reviewed versions are pushed to users.
