### ISSUE TITLE
[Anti-Adblock killer] Can't watch youtube videos

### ISSUE THREAD

**Issue by cor** [uBlock-LLC/uBlock#836]
I get a black screen when trying to watch an youtube video on Safari

Safari version: 8.0.3
uBlock version: 0.8.8.1

**Comment by gorhill** [comment]
Is Youtube serving you Flash videos?

**Comment by cor** [comment]
Nope, HTML5 video

**Comment by gorhill** [comment]
What are your filter lists? Custom filters? Dynamic filtering rules?

**Comment by cor** [comment]
I just discovered the problem, it's the "Anti-Adblock killer" list.

That list should probably be removed from the preferences, or at least add a note that it breaks youtube

**Comment by gorhill** [comment]
Or report the problem to the list maintainers so that they fix it for everybody. This is how these lists are built, with feedback from the community, for the benefit of all.

**Comment by cor** [comment]
I just [reported](https://github.com/reek/anti-adblock-killer/issues/194) it, can we close this issue now?
