### ISSUE TITLE
Can't watch BBC News Videos with "ESP: Filtros Nauscopicos‎"

### ISSUE THREAD

**Issue by logos88** [uBlock-LLC/uBlock#837]
Hello. I can't watch BBC News Videos when I have the "ESP: Filtros Nauscopicos‎" filter activated. I have tried in Firefox and Chromium in Linux. 

http://www.bbc.com/news/video_and_audio/

**Comment by gorhill** [comment]
All filter lists are 3rd-party to uBlock -- except of course for the ones marked "uBlock". Any issue with these need to be fixed by their respective maintainers. These filter lists are just included as is for your convenience.

**Comment by gorhill** [comment]
The project looks dead, no commit in more than a year.

You need that filter to fix the problem: `@@||bbcimg.co.uk/*/analytics.js`.

Given the filter list is Creative Commons, you could fork and maintain it?

**Comment by logos88** [comment]
Thank you very much, it worked perfectly!
About fork it and maintain, I fear I don't have the knowledge to do it. I don't know how to programm. It's something I want to solve, but it will take me time yet. Sorry :(
