### ISSUE TITLE
3rd-party filter after whitelist

### ISSUE THREAD

**Issue by crepererum** [uBlock-LLC/uBlock#838]
It would be nice to have the following multi-level architecture:

```
START
Apply all rules where (site not on whitelist)
// at this point we have the result as it works currently
// e.g. whitelisted pages include ads and privacy-threats
Apply all rules where (rule or rule-list marked as important)
// now whitelisted pages include ads and NO privacy-threats
END
```

This would allow to whitelist some pages (e.g. because you visit them very often and they have fair ads) but at the same time block global trackers / privacy threats (e.g. Facebook Like Buttons).

For optimization, the following could be desirable, because it avoids double-processing of some rules:

```
START
Apply all rules where (site no on whitelist) && (rule or rule-list not marked as important)
Apply all rules where (rule or rule-list marked as important)
END
```

**Comment by gorhill** [comment]
Unlikely. There such a thing as not keeping adding complexity to a software in order to not ruin it. This is where uBlock is at now.

Now I am in keep open only those issues which have a chances to be addressed, in order to prevent runaway pile of issues.
