### ISSUE TITLE
Feature request: exception to the rule

### ISSUE THREAD

**Issue by inoyakaigor** [uBlock-LLC/uBlock#842]
Add the interface to create exceptions to the rule blocking

In the image:
1) as it is now
2) it should be

![cd94d7360f](https://cloud.githubusercontent.com/assets/1235286/6266417/a406d56e-b84a-11e4-8458-4b35ce8ad605.jpg)

**Comment by spaghetti2514** [comment]
Yeah, that'd be pretty cool. Like a button on the element hiding pane that lets you switch to an "exception" mode where all the placeholders of blocked elements are rendered visible (like uMatrix does?) and selecting them creates an exception for that element
