### ISSUE TITLE
Element picker - have to hover to see buttons?

### ISSUE THREAD

**Issue by MannyC** [uBlock-LLC/uBlock#843]
I assume this was intentional, but it seems unnecessarily confusing to me.  When I clicked block element I was put into a mode I had no idea how to get out of, with no visible buttons on the element picker dialog to help me out.  Without knowing that they were there I see no reason why I would bring the mouse over their location.

Can I at least ask what the reason for hiding them is?   Space doesn't seem like a good enough reason to me.  If it's deemed to be a requirement then can I suggest a visual cue, such as a smaller box in the very corner that remains visible.

**Comment by gorhill** [comment]
> Can I at least ask what the reason for hiding them is?

The filter string could extend under the buttons if it is long, which is crippling if you want to edit the filter string manually. The buttons are not completely invisible.

**Comment by MannyC** [comment]
Okay, I didn't notice that they were translucent because my laptop screen was tilted very slightly forward.  I'd still put in a more visible cue in the corner or drop them down to the "Cosmetic Filters" line, making that tall enough to hold them.  Of course, perhaps I'm the only one who's had this issue.

**Comment by Mikey1993** [comment]
#632 -> 5th point.

**Comment by gorhill** [comment]
Fix was to implement item 5 in #632 from @Mikey1993.

**Comment by MannyC** [comment]
Excellent job.  Thanks!
