### ISSUE TITLE
Finnish list "Wiltteri" isn't in development anymore

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#844]
As reported in feedback section of Chrome store.

**Comment by chrisaljoudi** [comment]
To be removed or just marked as obsolete?

**Comment by gorhill** [comment]
I'm trying to come up with a solution for a smooth transition. Currently thinking of moving those marked obsolete filter lists to the custom filter lists when in use. So they stay enabled for users using it, and just disappear for those not using it.

**Comment by Snapy** [comment]
You could replace it with [this list](http://iadb.azurewebsites.net/Finland_adb.txt)
