### ISSUE TITLE
--disable-plugins prevents entering Options

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#845]
I updated uBlock but now I cannot enter its Options due to `Plug-in blocked`, looks like this:
![disable plugins at cmdline does this to ublock options](https://cloud.githubusercontent.com/assets/5661825/6280376/477384e8-b8ac-11e4-883b-548030c3f2f4.png)

I have `--disable-plugins` in `/etc/chromium/default` file.
Removing `--disable-plugins` solves this problem.
tested with commit 7e77a0c17e46c896224d0b73b700b7aba7628ecc

Here's my full `/etc/chromium/default` file(just in case it might be something else causing this but makes it appear that's --disable-plugins' fault):
# Options to pass to chromium
# XXX: if the screen is black then change --enable-one-copy  to --disable-one-copy

CHROMIUM_FLAGS="--flag-switches-begin --disk-cache-dir=/tmp/chromiumcache --disable-sync-preferences --disable-plugins --cipher-suite-blacklist=0x0001,0x0002,0x0004,0x0005,0x0017,0x0018,0xc002,0xc007,0xc00c,0xc011,0xc016,0xff80,0xff81,0xff82,0xff83 --disable-component-extensions-with-background-pages --disable-background-networking --disable-internal-flash --disable-bundled-ppapi-flash --disable-default-apps --ssl-version-min=tls1 --disallow-autofill-sync-credential --disable-device-discovery-notifications --no-pings --disable-media-source --disable-ntp-other-sessions-menu --disable-prefixed-encrypted-media --disable-touch-adjustment --disable-views-rect-based-targeting --disable-webgl --disable-account-consistency --enable-async-dns --enable-deferred-image-decoding --enable-download-resumption --enable-drop-sync-credential --disable-material-design-ntp --disable-new-avatar-menu --disable-new-profile-management --enable-offline-auto-reload-visible-only --disable-offline-auto-reload --enable-offline-load-stale-cache --enable-one-copy --enable-panels --disable-password-generation --enable-permissions-bubbles --disable-pinch-virtual-viewport --disable-pinch --disable-quic --disable-save-password-bubble --enable-session-crashed-bubble --disable-settings-window --use-simple-cache-backend=on --enable-smooth-scrolling --disable-sync-app-list --disable-sync-synced-notifications --enable-tcp-fastopen --disable-touch-editing --enable-web-based-signin --enable-zero-copy --enable-harfbuzz-rendertext --ignore-gpu-blacklist --enable-impl-side-painting --enable-lcd-text --num-raster-threads=4 --disable-origin-chip --disable-overlay-scrollbar --remember-cert-error-decisions=-1 --enable-search-button-in-omnibox-always --enable-spelling-auto-correct --tab-capture-downscale-quality=fast --tab-capture-upscale-quality=fast --touch-events=disabled --wallet-service-use-sandbox=0 --enable-gpu-vsync --flag-switches-end"

**Comment by Deathamns** [comment]
This is how Chrome embeds the options page:

``` js
<object is="extensionoptionsbrowserplugin" type="application/browser-plugin" id="browser-plugin-10" style="width: 100%; height: 100%;"></object>
```

Via a plug-in. So, this is most probably an issue with the browser.

**Comment by ghost** [comment]
Thanks for the tip @Deathamns Deathamns
Accessing this directly(like uMatrix does) works: 
`chrome-extension://gjoodgkbbjmmggbmbaokehdhbnmjigoi/dashboard.html`
but as it stands now, it tries: 
`chrome://extensions/?options=gjoodgkbbjmmggbmbaokehdhbnmjigoi`
which fails.

EDIT: chromium Version 40.0.2214.111 (64-bit)

**Comment by Pitel** [comment]
I don't have `--disable-plugins` (but I still got Chrome set up in a way I have to enable them) in my command line and I don't see the "Plug-in blocked" warning, but I still can't open settings. I just see the same empty rectangle with uBlock icon as you show on the screenshot.

**Comment by ghost** [comment]
@Pitel do you also see the `Plug-in Blocked` icon ? (the text goes away and only the icon remains, after like 2 seconds)
**EDIT:** ah nevermind, you already answered! - how did I miss that?! well this is embarrassing :-)

**Comment by ghost** [comment]
Oh man, they removed `--disable-plugins` https://code.google.com/p/chromium/issues/detail?id=366349
The thing is, that I already have all (3) plugins disabled manually, but something extra gets disabled with `--disable-plugins` as this issue shows. 

**EDIT:** maybe related: https://code.google.com/p/chromium/issues/detail?id=22521
