### ISSUE TITLE
Sites loading as text only

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#846]
This could happens sometimes when network requests had to be evaluated **while** uBlock loaded its filter lists (at launch or during an update).

**Comment by harshanvn** [comment]
Thanks! I had this issue occurred randomly. But was not able to reproduce, hence did not file a bug.
Will see if it reproduces again.

**Comment by gorhill** [comment]
I had a Youtube video playing, which made it more likely to occur as more chances to have a network request firing while uBlock loaded.

**Comment by gorhill** [comment]
@Deathamns can we upload 0.8.8.2 to AMO? It's a bad bug.

**Comment by gorhill** [comment]
I uploaded 0.8.8.2, hopefully I did it correctly.

**Comment by gorhill** [comment]
Difference is in the `install.rdf` file:

![a](https://cloud.githubusercontent.com/assets/585534/6314856/f53b5040-b9bc-11e4-8e64-6e908ebb59b1.png)

**Comment by ghost** [comment]
> I uploaded 0.8.8.2, hopefully I did it correctly.

It seems so :-)
