### ISSUE TITLE
Disable without whitelisting?

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#848]
bah.

**Comment by offhub** [comment]
uBlock Options > Settings > Check "I am an advanced user ..." then check the following link:

https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-%C2%B5Block-everywhere

**Comment by aireca** [comment]
Thanks, but that still is not as convenient as just a click to disable.

**Comment by gorhill** [comment]
You can easily disable from add-on tabs.

**Comment by aireca** [comment]
Define easy, is tedious.

**Comment by gorhill** [comment]
> Thanks, but that still is not as convenient as just a click to disable

and

> Define easy, is tedious.

Why is it tedious? There is no place in the UI for a "disable everywhere". Re-designing the UI completely **is** tedious, and we are not talking about the filtering code etc., and all this for a feature which the browser provides already.

**Comment by gorhill** [comment]
Keep the add-on tab pinned, then it's easy to disable/enable whatever extensions.

**Comment by gorhill** [comment]
Dup of #40 btw.
