### ISSUE TITLE
backup files of chrome and firefox have should have browser indication in filename

### ISSUE THREAD

**Issue by eox-cs1** [uBlock-LLC/uBlock#849]
If one uses different browsers with different settings it would be helpful to indicate the browser in the filename of the backup files

**Comment by gorhill** [comment]
Why?

**Comment by eox-cs1** [comment]
To have them separated and still know which one is which.

Of course one can do as I did - rename the files later on or place them in different
directories.

ciao
Christian

**Comment by gorhill** [comment]
I fear this would confuse users: they may end up thinking that a back-up from one browser is not compatible with another browser, while the reality is that the backup data is browser agnostic.

**Comment by eox-cs1** [comment]
OK, understood. It was just a suggestion which appeared to me. I can live with my
work-around.

ciao
Christian

**Comment by gorhill** [comment]
I think I would be more willing to provide a field which can be modified by the user, and which would be used as the filename to use for backup.

By default it would be filled with the current default: `my-ublock-backup_{{datetime}}.txt`. A user could edit this default filename. For example `my-firefox-ublock-backup_{{datetime}}.txt`, or `my-latest-firefox-ublock-backup.txt`.

**Comment by eox-cs1** [comment]
Hi,

that would certainly be a good solution too, though associated with more effort from your
side, but circumventing the browser-agnostic problem.

As said, it was just a suggestion...

ciao
Christian
