### ISSUE TITLE
Most Dynamic Filtering rows aren't colored on youzeek.com

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#854]
Issue as the title says.

Can reproduce reliably on Chrome.

FF seems to not inhibit this issue.
Don't know about Safari as I don't have it installed.

**Comment by gorhill** [comment]
Can't reproduce. Screenshot?

**Comment by Mikey1993** [comment]
No idea what happend there.
I can't reproduce it after a restart of the browser anymore.

I am closing this. If I be able to reproduce again, I will reopen.

**Comment by Mikey1993** [comment]
Oh, I know what happend.
I've hit the "All" row mistakenly, and the rows collapsed without any visual identification.

I think there needs be some bolder borders between domain + sub domain rows so users won't get cofused (even advanced users like me it wasn't obvious what happend as I've hit the row mistakenly instead of the popup title).
