### ISSUE TITLE
Difference between stable versions here and on AMO

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#856]
Hi,

I noticed that uBlock 0.8.8.2 here at Github and on its AMO page (both latest stable of course) were not exactly the same (checksum). So I wish only to ask what are the differences and, when the stable version is released, if I'd better install it from Github or from AMO.

Thanks,

**Comment by gorhill** [comment]
Difference is in the `install.rdf` file:

![a](https://cloud.githubusercontent.com/assets/585534/6314856/f53b5040-b9bc-11e4-8e64-6e908ebb59b1.png)

You get automatic updates when you install from AMO.

**Comment by ghost** [comment]
Thanks! I'm very curious :)
Splendid add-on, happy to have noticed it was available on AMO, mainly because many new users will discover this exceptional piece of art, code-art !
