### ISSUE TITLE
Failed to install update in Safari

### ISSUE THREAD

**Issue by RSully** [uBlock-LLC/uBlock#858]
I have 0.8.7.0 installed and Safari tried to auto update to 0.8.8.2. During this update, and subsequent manual attempts to update, I just get an error 

> Safari can’t install this extension
> An error occurred while installing the extension “µBlock”.

**Comment by chrisaljoudi** [comment]
Please uninstall µBlock, quit Safari, launch, and then install the latest µBlock. This is a bug outside µBlock's control, unfortunately.

**Comment by RSully** [comment]
Having this problem again now. This is the only extension I have experienced this with.
