### ISSUE TITLE
[EasyList] Can't watch sports streams online - ublock blocking feed?

### ISSUE THREAD

**Issue by mpenguin** [uBlock-LLC/uBlock#859]
Hi all. Loving uBlock for FF, but I've encountered a problem. I live abroad and tend to watch a lot of sports through online streams, mostly rugby and cricket. After install uBlock, however, I've found that I can no longer load the streams while uBlock is active. Disabling uBlock on the site loads the streams but also lots of ads, so it seems like uBlock is blocking the actual stream. However, I don't really know how to sort out the stream from everything else and whitelist it.

Here's an example for cricket: 
http://www.webcric.be/cricket_live_streaming_online-3.htm (or any webcric.be stream)

Same for this:
http://watchcric.net/channel/live-cricket-1 (or any watchcric.net stream)

Is there any easy way to see the items being blocked and whitelist the actual stream while leaving the ads blocked?

Thanks!

**Comment by offhub** [comment]
The network request log will show you which URLs are blocked, see [Quick guide: popup user interface:](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-number-of-requests-blocked) "_Click the eye icon to bring up the network request logger_".

Also see: https://github.com/gorhill/uBlock/wiki/Advanced-user-features

**Comment by gorhill** [comment]
Same issue occur with ABP + EasyList. Report to maintainers of EasyList.
