### ISSUE TITLE
Cannot update 3rd-party filter lists

### ISSUE THREAD

**Issue by Blutgang** [uBlock-LLC/uBlock#860]
I installed `µBlock 0.8.8.2` from the `Firefox Add-ons homepage` on a new profile: `Firefox 35.0.1` (I did not test if the other browsers have this issue). I click on `Easylist` and `EasyPrivacy` to check the modified date: `15 Feb 2015 20:50 UTC`. I click `purge all caches` and then I click `update now`. I check the modified date again for `Easylist` and `EasyPrivacy`. The modfied date for both of these lists is the same as before: `15 Feb 2015 20:50 UTC`. The latest update for `Easylist` and `EasyPrivacy` is `22 Feb 2015 08:20 UTC` and `22 Feb 2015 08:21 UTC` respectively. I'm pretty sure that this issue is not a network problem because `µBlock 0.8.6.0` 3rd-party filter lists can be updated to the latest version.

Is anyone else experiencing the same issue?

**Comment by gorhill** [comment]
I just tried purging EasyList and it worked fine.

`15 Feb 2015 20:50 UTC` is the date of EasyList shipped with uBlock. It's not uncommon for the EasyList server to not respond. Check that you can get the list directly in your browser: https://easylist-downloads.adblockplus.org/easylist.txt. If it works, then force an update.

**Comment by ghost** [comment]
I can confirm this on Fx 36.

**Comment by gorhill** [comment]
I just got a `Unable to connect to https://easylist-downloads.adblockplus.org/easylist.txt`. Check if you get the same in the browser console, accessible through <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-J.

**Comment by gorhill** [comment]
I tried again and it worked now, I got the latest version.

**Comment by gorhill** [comment]
Is your list marked _obsolete_ in the _3rd-party filters_ pane?

**Comment by ghost** [comment]
I was wrong. Middle click opens embedded list, left click load updated list from server.

**Comment by Blutgang** [comment]
@gwarser is correct. I middle click the list instead of left clicking the list. I'm guessing that behavior was changed from the older versions? @gorhill I will close the issue. I'm sorry for the confusion.

**Comment by gorhill** [comment]
uBlock does nothing special with middle-click, it's Firefox doing this.

Left click:

```
chrome://ublock/content/asset-viewer.html?url=assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt
```

Middle-click:

```
chrome://ublock/content/assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt
```

It's like with middle-click, that part is removed from the URL: `asset-viewer.html?url=`. Weird.

**Comment by Deathamns** [comment]
@gorhill Those links are simple links (with `href` attribute), so you can middle click them.

**Comment by gorhill** [comment]
@Deathamns Ok I see, middle-click bypasses javascript handler on the page.

**Comment by Deathamns** [comment]
@gorhill Listen for `mouseup` instead (with ignoring `button === 2`).

**Comment by gorhill** [comment]
To not fire a `click` event when clicking on it with whatever mouse button, isn't more like a Firefox bug?

**Comment by Deathamns** [comment]
Or bug in Chrome, it depends how you approach it. I just recommended a solution to achieve the same behavior across browsers, but it's really minor, so...
