### ISSUE TITLE
[Safari] YouTube ads not being blocked and cannot be skipped

### ISSUE THREAD

**Issue by willrun4fun** [uBlock-LLC/uBlock#861]
YouTube ads are making it through on my Safari install of the last two versions.

The skip button for the ads does not show up either so you are stuck watching the whole thing.

**Comment by gorhill** [comment]
Are you using the HTML5 player for Youtube?

**Comment by willrun4fun** [comment]
Yes. No flash installed.

**Comment by chrisaljoudi** [comment]
@willrun4fun any other extensions installed?

Also, are you able to reproduce this consistently?

**Comment by lewisje** [comment]
I have a wild guess that it could be something that YouTube changed; as ABP developer Sebastian Noack said regarding a separate issue: https://adblockplus.org/forum/viewtopic.php?p=112510#p112510

> We inject code into the page, messing with YouTube's JavaScript code, disabling their ads. An approach that isn't trivial and requires quite some afford to be maintained. Therefore we can't do that for every website. _Also that approach only works because YouTube configures its video ads with **global JavaScript objects**, something most other websites don't do._

(emphasis mine)

Maybe YouTube stopped using objects in global scope to configure its video ads, possibly around the time it made HTML5 video the default for most browsers.

**Comment by chrisaljoudi** [comment]
@willrun4fun @lewisje @gorhill fixed in 29fa6cb2e8ddd49fe8c2f51147d5c7e2aeb555e8, which introduces blocking of pragmatic requests made by creating `Image()`s and better coverage of `XMLHttpRequest` blocking.

This is a major improvement to Safari's blocking!

**Comment by gorhill** [comment]
@chrisaljoudi I will let you create a 0.8.8.4 release if you want one.

**Comment by chrisaljoudi** [comment]
@gorhill yep.

**Comment by chrisaljoudi** [comment]
@lewisje perhaps, but unlike ABP, µBlock doesn't rely on those global variables to block YouTube ads. µBlock does it by blocking the requests the HTML5 player would use to get the ads.

That's much more general purpose, and it also means µBlock will block any ads it identifiers for any HTML5 player.
