### ISSUE TITLE
Adultswim Player Doesn't Work

### ISSUE THREAD

**Issue by eeeerrrr** [uBlock-LLC/uBlock#862]
Currently the adultswim player will not work with uBlock. It works just fine with ABP using the same filters I have with uBlock. I also tried disabling all filters but EasyList on uBlock, but it still won't play.

http://www.adultswim.com/videos/specials/bag-boy/

**Comment by gorhill** [comment]
There is a request of type `other` which is supposed to be of type `object`. Investigating.

**Comment by gorhill** [comment]
Found the problem, the request type normalizer exits too early.
