### ISSUE TITLE
[Suggestion/Discussion] Possible revolutionary ad-blocking idea

### ISSUE THREAD

**Issue by ShadowOfHarbringer** [uBlock-LLC/uBlock#863]
(Sorry for writing here, but there really is no other place to put this since you have no forum)

So I was thinking and I came to an idea that will be probably impossible(or extremely difficult/resource consuming) to do, but if it worked, it would be a real revolution when it comes to ad blocking.

In short: would it be doable to hide an element without the webpage's javascript noticing it ?

It would work through some kind of separation of current webpage's DOM and the "real" DOM that is avaiable to the browser & extensions. So browser code & extensions could change parameters of a DOM object so that the change is undetectable/invisible to the webpage we are currently browsing.

If it worked, could possibly be revolutionary because it completely obliterates any tries of detecting ad-blocking by anti-adblock scripts. It gives the power back to users (same as ad-blockers did at first, but now more and more webpages have anti-adblocking Javascripts).

**Comment by gorhill** [comment]
I want to keep the pile of issues tidy and only specific issues will be kept open.

**Comment by ShadowOfHarbringer** [comment]
So can we still discuss this here in "closed" or is it done ?

Can I post it some place else  ?

**Comment by gorhill** [comment]
ABP has a forum: https://adblockplus.org/forum/index.php

**Comment by ShadowOfHarbringer** [comment]
Well, now I am confused.
Are you a developer of ABP as well ?

**Comment by gorhill** [comment]
No, I just pointed to a forum that I know about, you were asking for a forum for your idea. Here it's to file very specific issues.

**Comment by gorhill** [comment]
Here is the thing: if you have an idea, prototype it yourself, make something of out it. Asking _others_ to explore _your_ ideas is not the right thing to do.

**Comment by ShadowOfHarbringer** [comment]
"Here is the thing: if you have an idea, prototype it yourself, make something of out it. Asking others to explore your ideas is not the right thing to do."

Thanks for the advice, I didn't think of it this way.
