### ISSUE TITLE
uBlock disables Rapportive on Gmail (Chrome 40.0.2214.111 (64-bit))

### ISSUE THREAD

**Issue by avyfain** [uBlock-LLC/uBlock#864]

**Comment by gorhill** [comment]
Can your be more specific about "disables"? What exactly is happening? Also obviously, **all** uBlock settings which differ from default settings.

**Comment by avyfain** [comment]
Not sure to be honest. When uBlock is enabled, a message appears that says
"Rapportive offline. Sorry, Rapportive didn't load correctly due to a
temporary problem. Please reload your Gmail tab to try again."

When I disable uBlock it works normally.

**Comment by gorhill** [comment]
> all uBlock settings which differ from default settings

**Comment by avyfain** [comment]
Sorry about that, for some reason the second part of your message did not show up on the email. On the _3rd party_ side I have everything that is not regional checked, and these are my custom filters:

```
facebook.com##div[id*="topnews"]
facebook.com##div[id*="pagelet_canvas_nav_content"]
facebook.com##div[id*="pagelet_games_rhc"]
facebook.com##div[class*="_5mym"]
facebook.com##div[class*="ego_section"]
facebook.com##div[id*="pagelet_ego_pane"]
nacion.com##div[class*="LNA_paywall_modal_wrapper"]
feedly.com##DIV[id="tipsModule_part"]
www.facebook.com###js_1k._42fz > ._55ln[href="/messages/691236577"]
```

**Comment by gorhill** [comment]
> everything that is not regional checked

Try with default filter lists. Majority of filter lists are 3rd-party to this project, I can't be asked to deal with page breakage for lists crafted by other people, unless the breakage occurs with the default filter lists, in which case I am willing to investigate.

Default filter lists:
- uBlock's lists
- EasyList
- Peter Lowe's
- EasyPrivacy
- Malware domains (two first)

**Comment by gorhill** [comment]
Closed due to lack of feedback.
