### ISSUE TITLE
Feature Requests: Block the entire page, block based on keyword in page

### ISSUE THREAD

**Issue by timuckun** [uBlock-LLC/uBlock#865]
I would like to prevent certain sites from being able to load anything. I would like to be able to specify those sites by either using a domain name (with wildcard) or by looking for keywords inside of the page.

**Comment by TteokbokkiNari** [comment]
Can't you just use [dynamic filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide) for that?
Or alternatively make your own [filters](https://github.com/gorhill/uBlock/wiki/Filter-syntax-extensions)?

**Comment by timuckun** [comment]
I tried the dynamic filters using the example "\* domain.name \* block" and this didn't work.

I then tried a filter where I put the domain name in the filer. This blocked a lot of stuff on the page but for didn't prevent things in the <script> tag from running. 

What I would like is to have a way to specify that the page should not be loaded at all based either on the domain name or the presence of certain words on the page.

**Comment by gorhill** [comment]
> a way to specify that the page should not be loaded at all based either on [...] the presence of certain words on the page

This makes no sense.

**Comment by timuckun** [comment]
Is there a way to prevent ANY content from being loaded on the page? No HTML, no Javascript, No images. Nothing whatsoever.

**Comment by gorhill** [comment]
As per ABP filtering semantic, no. I posted I don't remember where a link to the rationale from ABP as to why `document` filter option would no longer block the whole page -- it used to.

**Comment by gorhill** [comment]
@timuckun What browser are you using?

**Comment by timuckun** [comment]
chrome on mac

**Comment by gorhill** [comment]
You could install [uMatrix](https://github.com/gorhill/uMatrix), it does block whole sites: any blacklisted hostname will be completely prevented from loading in the browser:

![d](https://cloud.githubusercontent.com/assets/585534/6328351/862e38ce-bb34-11e4-9492-f4fb992504bc.png)

**Comment by WalterWW** [comment]
@timuckun: You could also add the domain name to your hosts file and completely block it system wide:

http://www.techzilo.com/edit-hosts-file-mac-block-sites-domains/

**Comment by timuckun** [comment]
Thanks for the tips!
