### ISSUE TITLE
Built-in 'Fanboy+Easylist-Merged Ultimate List‎' wrong url

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#866]
Hi,

Just noticed _3rd-party filters / Multipurpose / **Fanboy+Easylist-Merged Ultimate List**‎_ is : 
http://www.fanboy.co.nz/fanboy-ultimate.txt
When it should be : 
https://www.fanboy.co.nz/r/fanboy-ultimate.txt

Built-in url leads to a 404

EDIT : forgot to mention, former built-in url is disabled here since I've set a custom list with the latter.
I noticed the issue when calling the former to check since it displays 0 used out of 82 387 when my custom displays 81 818 used out of 82 486 : 82387 (with wrong url?) when I have 82486...

**Comment by gorhill** [comment]
It is using that URL: https://github.com/gorhill/uBlock/blob/master/assets/ublock/filter-lists.json#L85.

**Comment by ghost** [comment]
Well, left-click as well as center-click leads me to http://www.fanboy.co.nz/fanboy-ultimate.txt with a 404

**Comment by gorhill** [comment]
What browser is this?

**Comment by ghost** [comment]
Firefox 35.0.1

**Comment by gorhill** [comment]
I just tried and it properly loads the local copy of the list, not the remote one.

**Comment by ghost** [comment]
I've disabled my custom list, and applied changes,
Then I've checked built-in list, applied changes, was notified list was outdated,
Then I've updated, built-in list was updated, but when left/middle clicking the link I always land on http://www.fanboy.co.nz/fanboy-ultimate.txt

**Comment by gorhill** [comment]
Do you have any other add-on which could cause this?

**Comment by ghost** [comment]
I've found the culprit : the **_Clean Links_** add-on which cleaned the original link ...
Made an exception for ublock, now works correctly.
Good to know, sorry for the disturbance. All is fine now.

**Comment by ghost** [comment]
I just cannot manage to find uBlock the fingers in the jam jar. I try and try but the culprit (when one occurs) is always on my side.
Damned! -- OK, thanks gorhill :)
