### ISSUE TITLE
Google requests no longer being blocked

### ISSUE THREAD

**Issue by orokusaki** [uBlock-LLC/uBlock#868]

**Comment by gorhill** [comment]
First thing: disclose **completely** all the settings which differ from the default settings.

**Comment by orokusaki** [comment]
Hrmmm, I didn't change a single setting. In fact, this was the first time I've opened settings for uBlock... however, clicking "reset settings to defaults" fixed the issue. This is even more alarming, because it's as if the add on was somehow hacked. How convenient that only Google should be unblocked by such an incident though, right?

**Comment by gorhill** [comment]
> Does this mean that Google has paid the creators of uBlock to allow their ads to be shown
> 
> How convenient that only Google should be unblocked by such an incident though, right?

If you are going to freely throw that kind of innuendos around, let me counter with this:

How convenient would be FUD thrown around by someone working <sup>[1]</sup> for a [company](http://angelettigroup.com/services.html) which offers the following services:
- Online Marketing
- Google AdWords
- Banner Ad Campaigns
- Blog & Forum Marketing
- Press Releases
- Email Marketing

Fact: uBlock runs counter to the interests of the company for which you work.

[1] As per your Github page

**Comment by orokusaki** [comment]
Wow, I'm sorry. This has been a huge misunderstanding.

  1. I wasn't worried about **your** intentions, or the intentions of uBlock.
  2. I don't offer any of those services. I put that website online in 2009 in an attempt to change the direction of my career at that time because I was spending 100% of my time developing ecommerce websites and it was getting really old. however, the website was created to no avail, since I never performed any of those services, other than some A/B testing for my ecommerce clients, which isn't really marketing
  3. I'm not a shill, and I don't think it's FUD for me to suggest uBlock could have the same fate as AdBlock Plus, of which uBlock is kind of its successor

However, I truly apologize for the FUD nature of how I worded my reply, and I appreciate all your hard work on this project. I was legitimately worried that the same thing that happened to AdBlock Plus was happening to uBlock.

All that said, I seriously have no explanation for how my settings got adjusted in a way that allowed Google ads but no others. I really didn't change any settings. I hope the accusatory sounding nature of my request doesn't dissuade you from looking into possible explanations for that aspect of the request.

**Comment by orokusaki** [comment]
To clarify, when I said "creators of", I should have instead used different words to suggest that "hostile committers" could have entered the scene, and that mistake was asinine on my part. It's just that, in my mind, any large project with GitHub, with many collaborators, could be usurped, with the proper amount of effort from a giant like Google. My mistake was not recognizing that this project is also somebody's baby, rather than just some conglomeration of efforts. Again, I apologize for that statement.

**Comment by orokusaki** [comment]
@gorhill ^ (in case you don't ger notified within an @ mention)

**Comment by plsng** [comment]
rekt

**Comment by orokusaki** [comment]
@gorhill firstly, where does it state on my GitHub page that I work for that company? Using the domain of my email to visit a website (website I put up in 2009 - not my employer) and then posting that info herein and stating that it's my employer is very much like doxing. The domain of my email address cannot be used to infer employment, especially when GitHub has a Company field, I'm pretty sure that's obvious. I'm a software developer, not a marketer. If you continue to probe a little further into my personal life (e.g., LinkedIn), you can find that, but it's better to just not be creepy.

Secondly, I had a legitimate concern and asked a legitimate question. There is nothing illegal (that I know of) in being paid like AdBlock Plus supposedly was, and considering uBlock's existence is predicated on AdBlock selling out to Google, I wouldn't exactly say it's paranoia to simply ask such a question.

**Comment by chrisaljoudi** [comment]
@orokusaki 

> Does this mean that Google has paid the creators of uBlock to allow their ads to be shown, just like allegedly paid AdBlock Plus for the same reasons, or is this just a huge bug that only affects Google and that only I noticed? Or, am I missing something?
> 
> considering uBlock's existence is predicated on AdBlock selling out to Google, I wouldn't exactly say it's paranoia to simply ask such a question.

[Please read the MANIFESTO](https://github.com/gorhill/uBlock/blob/master/MANIFESTO.md).

---

By the way, µBlock isn't just ABP without "acceptable ads" — that would be [Adblock Edge](https://addons.mozilla.org/en-us/firefox/addon/adblock-edge/).

µBlock is written from scratch with a conscious focus on efficiency and customizability.

**Comment by gorhill** [comment]
>  I had a legitimate concern

No you didn't. If you actually did have real concerns, as a **"software engineer"** with suspicions that "uBlock's devs are paid by Google", you would have actually be eager to provide specific technical details to confirm your suspicions. There was nothing beyond vague claims of "uBlock does not block something", and when asked for details, all the claimed issues suddenly vanishes.

**Comment by orokusaki** [comment]
@chrisaljoudi you should look into that. It pays to know the difference between a question and an accusation. On a further note, a "manifesto" means exactly nothing. If you want people to not ask any questions, perhaps you should recommend to @gorhill that he add a corporate charter with the proper jargon to disallow such actions as I've inquired about.

**Comment by chrisaljoudi** [comment]
@orokusaki 

> a "manifesto" means exactly nothing

If that's true from your perspective, then it's pretty silly to ask a question for which the response is going to be effectively identical to what's in the manifesto, isn't it?

Note that you still refuse to share your settings (which is what @gorhill asked for in the first place) and would rather make petty assumptions and arguments. 

Your position is indeed one of paranoia. If uBlock was giving Google special treatment, you'd think that you wouldn't be the only one among over 500,000 users to notice on the Internet's most visited website, wouldn't you?

**Comment by chrisaljoudi** [comment]
To conclude, please use the latest µBlock (it seems like you're using 0.8.6.0 from what I can tell from your screenshot).
