### ISSUE TITLE
Color for domains with both blocked and unblocked content is too similar

### ISSUE THREAD

**Issue by WalterWW** [uBlock-LLC/uBlock#870]
On my old laptop with its crappy display, the yellowish brownish orangeish color for domains that have both blocked and unblocked content is too similar to the redish color that is being used, so it's basically indistinguishable in most lighting conditions.

Suggestion: Make it more yellow. Maybe also make the light red more red.

**Comment by gorhill** [comment]
I might remove the coloring altogether. It's kind of redundant information, given that the `+` and `-` already convey that information, and I believe it's kind of creating more noise than signal. When I look in the list, I look at the pluses/minuses to figure what happened, never the color.

**Comment by TteokbokkiNari** [comment]
I actually like the colors. Faster to look at the domain name and the color, than looking at the right column and switching back to the domain name column.

It also segregates the list making it easier to look at. 

If anything, making an option both for enabling colors and for customizing colors would please everyone. I'd understand if the work for doing that would be too much, though.

**Comment by ghost** [comment]
I agree with @Daniellynet.

**Comment by WalterWW** [comment]
I also like the colors for the reasons mentioned by Daniellynet. It's a lot quicker scanning the domain list with a glance at the colors than looking at the (very tiny) + and - signs. That's why it would help a lot to have colors that are a bit more distinguishable too. It might not be as pretty as it is now, but maybe more practical.

**Comment by gorhill** [comment]
Fixed with 6f155d55f8bb0f61a858ceee25745c6f6b0e1d3e.
