### ISSUE TITLE
The "About-the-required-permissions" wiki page is missing

### ISSUE THREAD

**Issue by rappo** [uBlock-LLC/uBlock#873]
The README points to a Wiki page that doesn't currently exist, https://github.com/gorhill/uBlock/wiki/About-the-required-permissions

Specifically, it's the first thing you see in the [Installation section](https://github.com/gorhill/uBlock#installation):

> Installation
> Feel free to read about the extension's required permissions.

**Comment by gorhill** [comment]
Thanks for reporting. I think he is just trying to help but he has been breaking many pages, so I had to block him: https://github.com/gorhill/uBlock/wiki/About-the-required-permissions/_history#

**Comment by gorhill** [comment]
Fixed.

**Comment by rappo** [comment]
Thanks for the quick fix/reply!
