### ISSUE TITLE
[Fanboy Social] uBlock disables sharing in ownCloud

### ISSUE THREAD

**Issue by law** [uBlock-LLC/uBlock#874]
Hello, I'd just like to report that uBlock mistakenly disables the Sharing button on assorted ownCloud installs (I've only tested with Firefox 35.0.1 with uBlock 0.8.6.0).  There are various issues raised in the ownCloud community, the most prevalent of which are: 
https://forum.owncloud.org/viewtopic.php?f=29&t=25622
https://github.com/owncloud/core/issues/8360

  Specifically, on the last few ownCloud versions, uBlock will disable the 'Share' button next to user's calendars - the icons should be in the order of "Share", "CalDav Link", "Download", "Edit" and "Delete", but uBlock (and apparently a few other adblockers) make the "Share" link invisible.

**Comment by offhub** [comment]
The problem is in third party list.

Try this: (Add it to Options > My filters) [replace example.com with your domain]

example.com#@#.icon-share

**Comment by gorhill** [comment]
Do you have Fanboy Social enabled?

If so, please report the issue to EasyList: https://forums.lanik.us/viewforum.php?f=64

**Comment by gorhill** [comment]
Ok, according to the thread you linked, this confirms this is a 3rd-party list issue, since the issue was occurring with AdBlock as well. As said, report to filter list maintainer, URL above.

**Comment by law** [comment]
I will do just that, thank you so much for the quick reply!

**Comment by law** [comment]
Adding the link here for future Googlers.  Looks like I'm not the first one to report this problem:
https://forums.lanik.us/viewtopic.php?f=64&t=20824&p=66962

  and the list maintainer doesn't seem to think the problem is fixable on their end due to the custom-domain nature of ownCloud.  Perhaps there's other options the Easylist maintainers aren't considering?

**Comment by gorhill** [comment]
I was curious to look into this myself, but the online demo is nowhere usable: UI all in Chinese with no obvious way to change the language, and I just wasn't able to get precisely to [that screen](https://doc.owncloud.org/server/7.0/user_manual/documents.html#share-a-document).

**Comment by gorhill** [comment]
I suspect this might be fixable, but someone will have to tell me **exactly** how to get to [that screen](https://doc.owncloud.org/server/7.0/user_manual/documents.html#share-a-document), what I get doesn't match the doc at all -- there is no _Share_ button, even without a blocker.

**Comment by law** [comment]
Well, I can't help if the demo server is screwed up, but if you want to shoot me a PM or an email, I'd be happy to set you up with a test account on my personal ownCloud instance.  Also, the docs you're referencing are for ownCloud 7.x, and the latest stable (at least, the one I'm running) is 8.0.

**Comment by gorhill** [comment]
If you disable uBlock for that page, then use the element picker to select that _Share_ button, then make a screenshot of the result so that I can see the CSS selectors offered by uBlock in the dialog, I may be able to see if I can figure an exception CSS selector. Example:

![c](https://cloud.githubusercontent.com/assets/585534/6353153/9352eed2-bc15-11e4-82a9-e2ebd2df5fcc.png)

Now, if it is possible, I would still have to fix #497, to support generic cosmetic exception filters (trivial).

**Comment by law** [comment]
Here you go sir, as requested.  
![screen shot 2015-02-24 at 10 54 15 am](https://cloud.githubusercontent.com/assets/732614/6356643/b2b7344c-bc13-11e4-84da-a33c383ec411.png)
