### ISSUE TITLE
[Safari] Facebook photo viewer breaks in certain cases

### ISSUE THREAD

**Issue by timothy1098** [uBlock-LLC/uBlock#878]
On Safari, 0.8.8.4, Yosemite 10.2, when viewing Facebook photos, and scrolling through photos within an album in the enlarged mode, after a number of photos, then photos become blocked and cannot be viewed anymore, and it remains black with the loading sign. 

After the first photo does not load, any subsequent photos will not load either while the 'ticker' on the uBlocker next to the address bar counts up, indicating that uBlocker is the one blocking access.

I have to close the large preview pane, and then click on a photo to reopen it, for it to work for a set number of photos again (eg. 10), before the 11th and thereafter to not work.

**Comment by gorhill** [comment]
First thing: a URL where issue can be reproduced.

**Comment by elyrly** [comment]
I tried reproducing the issue but with the default filters wasn't able to display the same issue. @timothy1098

**Comment by timothy1098** [comment]
It will happen in your own FB account, but was able to reproduce with a random facebook page.

https://www.facebook.com/CodCommunity/photos_stream?ref=page_internal

Click on one of their photos so it enlarges into the blackbox viewer (the expanded viewer), and scroll with arrow keys. After approx 10 photos, the ublock ticker starts counting up, and photos can no longer be loaded in the expanded viewer.

I have tried reinstalling the extension and was unable to resolve the issue. I am using only default filters.

Safari Version 8.0.3

**Comment by gorhill** [comment]
> It will happen in your own FB account

I don't have a Facebook account.

> After approx 10 photos, the ublock ticker starts counting up, and photos can no longer be loaded in the expanded viewer.

Using provided URL, I stopped after 40 photos, they all displayed fine.

What filter lists do you have selected aside the default ones?

**Comment by timothy1098** [comment]
Has still been happening to me.
Filter list:
MyFilter (nothing on it)
uBlock Filters
uBlock Filters - Privacy
Easy List (adblockplus.org)
Peter Lowe's Ad server list (yogo.org)
EasyPrivacy
Malware Domain List (malwaredomainlist.com)
Malware domains

This doesn't happen on AdBlockPlus, I installed it to try and it works.
After disabling AdblockPlus and enabling uBlock, issue reappears.

**Comment by gorhill** [comment]
Somebody with Safari will have to try to reproduce, I can't.

**Comment by ghost** [comment]
@timothy1098 Do you need Facebook to reproduce?

**Comment by chrisaljoudi** [comment]
@timothy1098 @gorhill can't reproduce here on Safari 8.0.5. Will continue trying to — meanwhile, it'd help **a lot**, @timothy1098, if you can find a simpler test case (Facebook is... let's say, _complex_, and can be very different for different users).

**Comment by chrisaljoudi** [comment]
@timothy1098 okay, reproduced and diagnosed. Quite the interesting issue. :)

Will fix and post explanation momentarily.

**Comment by chrisaljoudi** [comment]
@timothy1098 closed in 83975124a41e135374f1555f241525b12b5b53a6.

The thing was, Facebook issues tracking requests that, when **silently** blocked, break the part that loads the images. µBlock for Safari now throws an exception explicitly when blocking XHRs, which lets Facebook's JavaScript fallback appropriately.

**Comment by chrisaljoudi** [comment]
@timothy1098 P.S.: ABP doesn't block XHR requests on Safari at all.

**Comment by timothy1098** [comment]
@chrisaljoudi Looks like I'm late to the party; woke up and all done! :) Makes sense. Can confirm it's working now.

@gorhill @elyrly @BenjaminProgram and all others thanks for your help.

**Comment by alexv93** [comment]
I am still having the same issue on the new version 8.9.2.

**Comment by gorhill** [comment]
@alexv93 The fix is in the dev build.

**Comment by chrisaljoudi** [comment]
@alexv93 0.8.9.2 doesn't have the patch; [see the release notes](https://github.com/gorhill/uBlock/releases/tag/0.8.9.2).
