### ISSUE TITLE
Firefox 36: Menu disappears when uBlock is in it

### ISSUE THREAD

**Issue by garyking** [uBlock-LLC/uBlock#879]
In Firefox 36, if you move uBlock from the toolbar to the Menu where you can "hide" icons in, and then restart the browser, and then open and close the Menu a few times, then eventually the Menu will not be able to open anymore. 

This only happens when uBlock is in the Menu. If I move it out, then there are no problems. And the problem only started happening since upgrading to Firefox 36 today.

**Comment by Deathamns** [comment]
Duplicate of #638 and #876.
