### ISSUE TITLE
Block an element using XPath

### ISSUE THREAD

**Issue by PsyHaSTe** [uBlock-LLC/uBlock#880]
I want to block a frame, but it's overlapped by other elements and It's impossible to block lock it using pipette. So please add a feature when you can block an element on the page using XPath (for example I'm using Firebug, I'm copying XPath of specified element and add it in uBlock). The same feature is available in Remove it Permanently - It's very useful in some cases.

**Comment by gorhill** [comment]
You can also use "Copy CSS Path" in Firefox's dev console: This way you have a CSS selector which can be used as is in a ABP-compatible filter:

For example, "Copy CSS Path" for this comment box returns `#new_comment_field`. So one would just add `github.com##` in front of that CSS path and you have a valid cosmetic filter: `github.com###new_comment_field`.
