### ISSUE TITLE
uBlock 0.8.8 Panel does not show full domain name.

### ISSUE THREAD

**Issue by vonHabsi** [uBlock-LLC/uBlock#882]
When the active page is something like www.domain.com, or www2.domain.com, the display only shows domain.com, and doesn't seem to offer away of having different settings for www2.domain.com and www.domain.com.

Is that the way it is meant to work now?
How do you configure different settings differently?

**Comment by gorhill** [comment]
Click the `all` top cell.

**Comment by vonHabsi** [comment]
Thanks. Is there some reason behind that change in the design?

**Comment by gorhill** [comment]
#820. To simplify UI for first-timers, to reduce density of information.

When you expand it, it will be remembered.

**Comment by vonHabsi** [comment]
Thanks.
