### ISSUE TITLE
Popup "button" meaning

### ISSUE THREAD

**Issue by Gizmokid2005** [uBlock-LLC/uBlock#884]
I checked the [wiki page](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) for pointers on what the columns mean with the colored "buttons" but haven't found anything. Forgive me if this is dense, but what are these columns/buttons for? http://i.imgur.com/kbjovrn.png

**Comment by TteokbokkiNari** [comment]
[Here you go!](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide)

**Comment by Gizmokid2005** [comment]
Bah! After all that searching I somehow missed that wiki page! Thank you @Daniellynet
