### ISSUE TITLE
FF 36: Number of blocked requests on icon changes appearance

### ISSUE THREAD

**Issue by FatOrangutan** [uBlock-LLC/uBlock#885]
This started happening after upgrading to Firefox 36.0. The number of blocked requests normally looks like this:
![untitled](https://cloud.githubusercontent.com/assets/8336638/6375495/73ddb64e-bd3d-11e4-8bc8-a332351743bb.png)
But if I go into Customize (Firefox Menu -> Customize) and come back (don't necessarily have to change anything while in Customize mode), the icon now looks like this:
![untitlesd](https://cloud.githubusercontent.com/assets/8336638/6375533/ab885680-bd3d-11e4-9fd2-2e769469e6ad.png)
I am using the standard Firefox theme.

**Comment by TteokbokkiNari** [comment]
Can confirm it on my end, too. 

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0 ID:20150225030226 CSet: 07c04d7a483a

µBlock version: 0.8.8.5-dev.2

**Comment by gorhill** [comment]
Duplicate of #579.

**Comment by Deathamns** [comment]
Duplicate of #579.
