### ISSUE TITLE
Seamless migration to new list locations

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#887]
As per comments in 78cfd0472730bd50fc1ab36af4b8cc0d1cb87e26.

@chrisaljoudi An issue in order to keep track of progress and related code changes.

**Comment by gorhill** [comment]
Code to migrate seamlessly in a9ce435f1caa64512fb20ac9943dc6eb8d756909.

However, we can only start to migrate to new locations in `filter-lists.json` when everybody has uBlock's version which supports seamless migrations.

**Comment by chrisaljoudi** [comment]
@gorhill that makes sense.

**Comment by chrisaljoudi** [comment]
@gorhill 

> we can only start to migrate to new locations in filter-lists.json when everybody has uBlock's version which supports seamless migrations

Hmm; wouldn't the transition work smoothly as long as the [new code](https://github.com/gorhill/uBlock/commit/24611bab2990434c681028619cfd6a82f4baf718) is distributed alongside the updated `filter-lists.json`?

**Comment by chrisaljoudi** [comment]
@gorhill in other words: everyone who receives the new `filter-lists.json` also receives the new `storage.js`.

**Comment by gorhill** [comment]
Older versions will also be able to download the new `filter-lists.json` file, which means they will lose whatever they have selected which is no longer in the new `filter-lists.json`. This is why the change needed to be quickly reversed. As soon as a new `filter-lists.json` is committed, anybody with whatever uBlock version can pull it.

**Comment by chrisaljoudi** [comment]
> As soon as a new filter-lists.json is committed, anybody with whatever uBlock version can pull it.

Oh. Oh. Oh. _Got it._

**Comment by chrisaljoudi** [comment]
@gorhill how about this: for seamless transitions, keep the main entry as it is, but add a `newLocation` key in the `filter-lists.json`. That way, new versions will use that instead while old versions will simply ignore it.

That would maintain backward compatibility.

**Comment by chrisaljoudi** [comment]
@gorhill any thoughts? :)

> @gorhill how about this: for seamless transitions, keep the main entry as it is, but add a newLocation key in the filter-lists.json. That way, new versions will use that instead while old versions will simply ignore it.
> 
> That would maintain backward compatibility.

**Comment by gorhill** [comment]
Yes, thoughts I had, and I can't see how this would allow to keep a clean list of lists, as this would force us to keep obsolete entries, i.e. two entries for Peter Lowe's, etc. I want a clean, seamless transition, so that users are moved to the new list, and only the new list shows in the list of lists.

Currently I plan to wait one month or so, then we can start moving those obsolete lists to their new locations, assuming everybody has the code for the seamless transitions. From then on, there won't ever be an issue of having to keep obsolete filter lists in the _"3rd-party filters"_ pane.

There are other issues of obsolete lists having to be changed, this is why I have been waiting, there was no way to do it cleanly. Now the code is in, it's just a matter of waiting just enough so that everybody has the code for the seamless transition.
