### ISSUE TITLE
[Firefox] Graphical Issue:  Bold Black Dot Below uBlock Icon

### ISSUE THREAD

**Issue by ozar** [uBlock-LLC/uBlock#888]
![screenshot](https://cloud.githubusercontent.com/assets/3442421/6385942/f362ff5c-bd36-11e4-9dc8-5e4c4276871a.png)

Linux, Firefox-36.0, uBlock 0.8.8.5-dev.3

Sorry if I've missed a prior report on this issue, but I was unable to find it if exists already.

On pages where uBlock is turned OFF, there is a bold black dot at lower right corner of the button frame when the mouse is hovered over the uBlock button/icon.  When the mouse is moved away from the button, the frame disappears as intended, but the bold black dot remains.  I've tried going back to older versions of uBlock, but the dot remains.  Going into "customize" mode on Firefox removes the dot on exit, but then it reappears when Firefox is restarted.  The dot appears to be covered up by the blocked items count indicator when uBlock is ON and counting blocked items.  In uBlock's settings, unchecking "Show the number of blocked requests on the icon" doesn't remove the dot.

I'm thinking this issue may be related to the one where the "blocked items count" is moving around on the page for some users, but I'm just guessing.  The issue seems to have started when I first upgraded Firefox to version 36.0 on Linux, but I also upgraded uBlock at about that same time if that matters.  So far, the issue is not showing itself under Windows 7 with Firefox 36 installed.

**Comment by gorhill** [comment]
I got the same as soon as I upgraded to Firefox 36.

**Comment by ZeldaZach** [comment]
This isn't as severe on Mac OSX 10.10.2 (FF 36), but still strange
![screenshot 2015-02-27 22 35 00](https://cloud.githubusercontent.com/assets/7460172/6424677/ecd99b32-bed0-11e4-9463-840e116cb7e6.png)

What's interesting is that when I moved uBlock to the Menu and then moved it back, the dot appears to have vanished.

![screenshot 2015-02-27 22 44 48](https://cloud.githubusercontent.com/assets/7460172/6424717/3efa520c-bed2-11e4-976f-82246a0ecb40.png)

**Comment by Deathamns** [comment]
Possible fix in 9fe8f414.

**Comment by ozar** [comment]
Just a note to say that this issue has disappeared for me with the latest release (0.8.9.1) - the "blocked items count" indicator has moved to a position above the uBlock icon, but that isn't as bothersome as the bold black dot was.  Thank you...

**Comment by Deathamns** [comment]
@ozar [comment-76523311](https://github.com/gorhill/uBlock/issues/579#issuecomment-76523311) and [comment-9969890](https://github.com/gorhill/uBlock/commit/9fe8f41426d55e0bc5b4937d1381993d4d72f9eb#commitcomment-9969890).
