### ISSUE TITLE
a couple of usage questions

### ISSUE THREAD

**Issue by anonish** [uBlock-LLC/uBlock#889]
I did not see this mentioned in the guide/wiki or other issues
- how to enable same-host allow permanently? (the highllighted section of the screenshot).  I dont mean per site, i mean globally.
- can you explain the rows better? for instance
  - images, does that mean all images (1st and 3rd party) would be allowed/blocked?
  - inline-script vs 1st party script ( i assume this would be an in-page script vs a linked one?)
  - 3rd part vs 3rd-party scripts vs 3rd party frames and their relation to images/all ?

it would also be nice to see http/https as separate rows but that may be beyond the scope of ublock

![ublock](https://cloud.githubusercontent.com/assets/10761304/6386380/26280a62-bd3d-11e4-9f03-9b07363d4ed7.jpg)

**Comment by WalterWW** [comment]
> how to enable same-host allow permanently? (the highllighted section of the screenshot). I dont mean per site, i mean globally.

That could be achieved by adding an exception to the filter rules:

```
@@*$~third-party
```

This disables all filters for elements that are not from a third-party domain.

Please note that when I'm doing this in ABP, it gives me the snail indicator, meaning the rule might slow things down a bit. I don't know if the same would apply to how ublock handles these.

**Comment by gorhill** [comment]
> how to enable same-host allow permanently?

Globally blocking `3rd-party` results in this, i.e. don't block `all`, block `3rd-party`.

> images, does that mean all images (1st and 3rd party) would be allowed/blocked?

Yes. So long as there are no narrower rules taking precedence.

> inline-script vs 1st party script ( i assume this would be an in-page script vs a linked one?)

Yes.

> 3rd part vs 3rd-party scripts vs 3rd party frames and their relation to images/all ?

[Dynamic filtering: precedence](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-precedence)
