### ISSUE TITLE
Firefox 36 bug.Firefox menu won't open.It opens and closes immediately.Gets stuck.

### ISSUE THREAD

**Issue by smartfonreddit** [uBlock-LLC/uBlock#890]
I click on the Firefox 36 menu button, the 3 horizontal lines on top right.It opens and closes immediately.For a split of a second I can see the addon icons that I placed there.Right after it closes itself, the menu icon remains highlighted, as if it was still open.Clicking on the [now] highlighted menu button opens the menu window partially and keeps it open(as it's supposed to).When I say partially I mean it only displays the bottom panel of the menu (the Sync,Customize,question mark and the shutdown button), the addon icons are not present, as if the menu was empty.
I have verified it's a uBlock issue by enable/disabling and testing it after many browser restarts.
It was working fine with FX 35.0.1.

**Comment by Deathamns** [comment]
Duplicate of #638.
