### ISSUE TITLE
Chrome web store pre-release channel

### ISSUE THREAD

**Issue by JeremyWW** [uBlock-LLC/uBlock#891]
Hi,

Is it possible that you could have a pre-release channel in the web store? It's great to download pre-releases from here and check them out but, as you know, Chrome will nag to disable unofficial extensions on every start-up which can't be prevented.

Thanks.

**Comment by gorhill** [comment]
I just do not have the time to take on more things to do. As much as this seems not a big deal, when you have no time left, it becomes a big deal.

**Comment by JeremyWW** [comment]
That's appreciated. It's only a pain because it seems to take so long to get the latest versions updated in the store. And there's me champing at the bit to use the latest improvements... :-)
