### ISSUE TITLE
[Cyberfox] Not visible counter on Cyberfox with FT DeepDark

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#892]
Hello gorhill,

I have the issue on latest builds. Counter is hiding itself..
Please see the screenshot : http://i.imgur.com/pdeGmBm.png
I cannot see the counter when I dropped the uBlock next to "plus" icon see: http://i.imgur.com/2jDURJZ.png
I am using latest Cyberfox 36.0 which is based on latest Mozilla build, and I am using FT Deep Dark. uBlock version is 0.8.8.4
Can you please check it?

Thanks,
yigido

**Comment by Deathamns** [comment]
Possible fix in 9fe8f414.

**Comment by ghost** [comment]
It looks fixed. Thank you, but now I cannot see uBlock icon actually :) The counter covers half of the icon

**Comment by Deathamns** [comment]
Well, if you put the button on the toolbar, then you can expect that.
Your theme adds to it too, with the default theme it looks better. Also, the background color of the badge doesn't change to black with FT DeepDark for some reason.

**Comment by ghost** [comment]
Thank you, I can conrifm then it is totally fixed in v.0.8.9.1 :)
