### ISSUE TITLE
Adblock Gold Edition

### ISSUE THREAD

**Issue by tailHey** [uBlock-LLC/uBlock#893]
Hello everyone.
Just noticed a certain Adblock Gold Edition on Chrome Web Store : https://chrome.google.com/webstore/detail/adblock-gold-edition/kmooncpopldajlgigepneepagpcnehgg

Pay attention to the last description's line : "Used under GPLv3 from uBlock." Is it alright? Even though µBlock is open-source, can the author do so without letting you know for instance?

Just wondering you'd like to know that so that everything is made finely. Sorry for bothering you is everything is alright. Thank you for your work.

**Comment by lewisje** [comment]
Does Adblock Gold Edition release its source code? That's a key requirement of the GPL.

**Comment by Kyuzial** [comment]
The developer don't give the source code or the website of the project on the chrome web store.
Then it's possible to report this extension but if you want to be nice you can just send a pm to the developer :)

**Comment by gorhill** [comment]
The code is GPL, people are free to do whatever they want. What I do is just [list here](https://github.com/gorhill/uBlock/wiki/Forks-and-%22forks%22-of-%C2%B5Block) all the forks which I spot, so at least people have a way to find out what is behind a when it is not obvious that they are actually dealing with uBlock's code.

@lewisje The source code is available if you browse the extension's code, it's javascript.

**Comment by gorhill** [comment]
Another one showed up, "AdBlock Plus Free". Added to the list.

If anything, the owners of the brand "AdBlock" and "Adblock Plus" have more a case than me. Anybody, feel free to warn them.

**Comment by 0xBRM** [comment]
Haha, this is ridiculous. Absolutely pathetic.

**Comment by lewisje** [comment]
Sorry @gorhill I didn't know whether the creators of forks also needed to release any preliminary files used in the build process, not just the final Javascript; my first guess was that the CRX itself was sufficient, but I was hoping there was something we could ding them on.
