### ISSUE TITLE
Suggestion: warn users that adding multiple lists increases memory usage

### ISSUE THREAD

**Issue by Noexpert** [uBlock-LLC/uBlock#894]
If this is already implemented please close.
The temptation is to add all filters but clearly this increases memory usage.

To avoid complaints similar to: "ublock hogs memory!", could we add a simple warning either displayed by default, or only triggered if more than X filters are selected?

**Comment by gorhill** [comment]
> To avoid complaints similar to: "ublock hogs memory!"

I never heard such complaints. If there is such complaints, it's baseless, and I am not going to design uBlock according to nonsense.

I added 30 MB hpHosts' hosts.txt the other day:

928,721 filters = 228.87 MB for "Explicit allocations"

ABP with EasyList, EasyPrivacy, Malware domains, Peter Lowe's (uBlock's default lists):

~91,000 filters = 215.86 MB for "Explicit allocations"

**Comment by Noexpert** [comment]
I wasn't suggesting it uses more memory.

What I'm saying is that by designing an addon which is memory efficient, users will be tempted to select all filters, precisely because it's memory efficient.

Inevitably there will be users that miss the point thinking it uses more memory because they're doing this:

10,000 ublock filters = 10 ABP fliters
251MB > 250MB

**Comment by gorhill** [comment]
It has never been an issue, I fail to see why I should worry it becomes one. The mere fact of warning about memory sort of create a issue about memory, where there is none. Whoever makes such a complaint, I will be happy to officially set the record straight with real numbers.
