### ISSUE TITLE
Unable to open Facebook post menu

### ISSUE THREAD

**Issue by rangilin** [uBlock-LLC/uBlock#895]
![screen shot 2015-02-27 at 11 31 58](https://cloud.githubusercontent.com/assets/849838/6407061/4877897a-be74-11e4-9f8a-1773b36d02fe.png)

By "post menu" I mean the one you can open by clicking top right icon of a post.

Here is the link and rule that blocked it.
Rules : |https:*ad
Links : https://www.facebook.com/feed/options_menu/?button_id=u_ps_0_0_c&feed_context=%7B%22fbfeed_context%22%3Atrue%2C%22location_type%22%3A1%2C%22outer_object_element_id%22%3A%22u_ps_0_0_0%22%2C%22object_element_id%22%3A%22u_ps_0_0_0%22%2C%22is_ad_preview%22%3Afalse%2C%22is_editable%22%3Afalse%7D&story_token=S%3A_I100006030945567%3A335125900031772&tracking_message=qid.6120357732071150916%3Amf_story_key.-7646521427772994

I cannot find which filter this rule come from, I think it is too aggressive.

**Comment by gorhill** [comment]
What filter lists you have selected?

**Comment by gorhill** [comment]
The closest I can find to `|https:*ad` is the Japanese filter list. You have it selected?

**Comment by rangilin** [comment]
Yes, I do have JPN: ABP Japanese filters checked. Turn it off solve the problem.

**Comment by gorhill** [comment]
I see comments like so:

```
! False positives with product images starting at AD- using |https:*^ad- filter, reported via issue report, Feb 2, 2014
```

in the list. So this is definitely a rather broad filter. You may want to report to the maintainers, they are on Github: https://github.com/k2jp/abp-japanese-filters/

**Comment by rangilin** [comment]
I see, thank you, that was fast
