### ISSUE TITLE
uBlock blocks ajax

### ISSUE THREAD

**Issue by farag2** [uBlock-LLC/uBlock#897]
uBlock blocks ajax on https://mail.yandex.ru, so I have to press reload button to check new e-mails.

**Comment by gorhill** [comment]
I don't have an account there. Surely it must be one of the filter lists interfering. It could be Peter Lowe's or EasyPrivacy, try without one and/or the other and see if that fixes your prpblem. If yes, try ABP + the same filter lists in uBlock, and see if you get the same problem. If yes, report the issue to EasyPrivacy maintainers: https://forums.lanik.us/viewforum.php?f=64.

**Comment by farag2** [comment]
Hm... Perhaps not uBlock filters block it, but my own filters. http://pastebin.com/36qPXng7. I should be more careful...

**Comment by gorhill** [comment]
You can quickly disable your filters to test if this is the cause. Un-check _"My filters"_ (English version) in the _"3rd-party filters"_ pane (it's the first one in the list), then click _"Apply changes"_.

**Comment by farag2** [comment]
Yes, after I opened a topic, I disable my filters and made sure that it's their fault. It can be closed.
