### ISSUE TITLE
[Firefox] uBlock button breaks Firefox app menu

### ISSUE THREAD

**Issue by jimporter** [uBlock-LLC/uBlock#899]
This occurs on Windows 7 with Firefox 36.0 under a fresh profile. I wasn't able to reproduce on Linux.

Steps to reproduce:
1. Install uBlock (I tried with 0.8.8.2, 0.8.8.4, and 0.8.8.5-dev.3)
2. Customize the Firefox toolbars and drag the uBlock button to the app menu's popup (the thing with the 3 lines)
3. Navigate to a page where uBlock would block something
4. Try to open the app menu: it slides open and then immediately closes

**Comment by ZeldaZach** [comment]
Doesn't appear to affect FF 36 Mac OSX 10.10.2

**Comment by Deathamns** [comment]
Duplicate of #638.
