### ISSUE TITLE
Some images don't show up on Gmail and some thumbnails are also blocked.

### ISSUE THREAD

**Issue by gordonpn** [uBlock-LLC/uBlock#9]
Here's a screenshot of what I'm talking about: https://www.dropbox.com/s/tqbomlfzk8gpfb8/2014-06-24%2017_53_20.png

(Blurred out some private information).

I'm just wondering if this is happening to anybody else?

**Comment by gorhill** [comment]
Can you share the URL of the missing image by using the contextual menu and then "Copy image URL"? (if this doesn't result in sharing private info)

**Comment by gorhill** [comment]
Maybe related to #7? Blocked images do not show up with other blockers, so maybe the fact that they were hidden, you never noticed they were blocked.

**Comment by gordonpn** [comment]
Here's one of them: https://ssl.gstatic.com/ui/v1/icons/mail/profile_mask2.png

**Comment by gorhill** [comment]
Did you select more filter lists than what is selected out of the box?

**Comment by gordonpn** [comment]
Yes, I did.

Here are the ones I selected: https://www.dropbox.com/s/k7axtew1ql3cgte/2014-06-24%2020_54_35.png

Which one should I disable?

**Comment by gorhill** [comment]
> Which one should I disable?

No clue.. With HTTP Switchboard, I had a log from where I could find which ABP filter blocked a URL, but here I have nothing. That's why I created issue #10, it will be very helpful.

**Comment by gorhill** [comment]
Note that _"hpHosts’s Ad and tracking servers"_ has been found to be too zealous. Try without it.

**Comment by ghost** [comment]
"Dan Pollock’s hosts file (someonewhocares.org)" list causes this for me with ublock.
Try disabling that one.

**Comment by gordonpn** [comment]
Disabling Dan Pollock's worked for me, thanks Bizzy. 

Thanks gorhill.
