### ISSUE TITLE
improve UI

### ISSUE THREAD

**Issue by ialexsilva** [uBlock-LLC/uBlock#90]
Good like some interface improvements such as: 

1 - The color of notifications should be green to match the color of the button when it is enabled. 

2 - A more clean and more current interface ...

**Comment by gorhill** [comment]
> 1 -

What do you mean "notifications"? The count on the icon? These are for blocked requests, to me "blocked" is red. If ever I use green, that would be for the count of domains **not** blocked (#76).

The power button is whether uBlock is on or off, nothing to do with blocked requests.

> 2 -

It's a rather vague description of a rather subjective issue.

**Comment by kurtextrem** [comment]
I also don't think 1 is the best thing to do, the current color is fine (see gorhill's answer)
To 2., I think I understand what he means. If you compare uBlock's interface with AdGuard or Adblock (Plus) it looks... simpler. I wouldn't say it looks old, but just not that "modern". I don't think that's an issue though. Simple doesn't always mean it's not current.

**Comment by gorhill** [comment]
Ok, I need more specific issues, too vague and subjective at the same time. This is a hobby, so best is someone come up with concrete HTML code, CSS, etc. and I will consider it. Otherwise it's too unspecific as an issue.
