### ISSUE TITLE
 "MVPS HOSTS" filter list isn't updating to the latest release, even after "purge cache" is clicked

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#901]
This happens only on Chrome, on my machine. Firefox is OK.
Didn't happen on my 2nd machine at all, not even on Chrome.

Here is a screen cast reproducing the issue on Chrome on the affected machine:
https://www.youtube.com/watch?v=lB-F9RwtKPU

**Comment by gorhill** [comment]
Is uMatrix's behind-the-scene blocking it?

**Comment by Mikey1993** [comment]
Nope.
Disabling uMatrix completely, and trying again reproduced the same faulty result.

**Comment by gorhill** [comment]
I have 28 Feb. here. Check what uBlock's console says when you try to update the filter list.

**Comment by Mikey1993** [comment]
Nothing shows up at the Console.
It's plain empty after the updating process.

**Comment by gorhill** [comment]
What console did you look at?

**Comment by Mikey1993** [comment]
F12 -> Console (The Javascript console)

**Comment by gorhill** [comment]
No... The extension console, from _Extensions_: click `background.html` for uBlock when _Developer mode_ is enabled.

**Comment by Mikey1993** [comment]
Sorry, my bad, thought I would get the desired console from there.

Checking the extension console, It still shows blank console after the updating process.

Also, I don't seem to see any network requests in the "Network" tab even after purging all the caches and downloading the filter lists again.. is this normal? should I see it somewhere else? 
**Maybe a cached copy is handled to me even after purging the cache for that list?**

**Comment by gorhill** [comment]
The packaged copy is dated Jan. 24th. Looks like they updated today, so the remote server copy is Feb. 28th. I get Feb. 28th on Chromium. I don't know why you do not get the latest one after purging the cache. Try while leaving uBlock's dev console open, but select the _Network_ tab to see if the network request is made.

**Comment by gorhill** [comment]
That's what I get:

![a](https://cloud.githubusercontent.com/assets/585534/6426293/b2112582-bf21-11e4-9381-ec5627ef3c65.png)

**Comment by gorhill** [comment]
Something is wrong with the remote server. If I try to get the file directly from the browser, I get a truncated content as a result: http://winhelp2002.mvps.org/hosts.txt.

**Comment by Mikey1993** [comment]
Ahh, now I'm seeing something interesting..
I now can confirm that I am getting the list from cache, and not from the server as shown here:

![From Cache](https://i.imgur.com/zF1Mqem.png)

**Comment by Mikey1993** [comment]
> Something is wrong with the remote server. If I try to get the file directly from the browser, I get a truncated content as a result: http://winhelp2002.mvps.org/hosts.txt.

Comparing the cached list from Firefox (which got the Feb. 28 updated list), to the direct file from the browser, I can see the truncated result in both, which means the updated list is not complete/broken.

Should this be informed to the maintainer?

**Comment by gorhill** [comment]
> Should this be informed to the maintainer?

I guess. Personally I would wait till the end of the day, as the list was updated today, maybe it's just a transient problem due to high traffic. Will see if this resolves on its own by the end of the day.

**Comment by Mikey1993** [comment]
> Will see if this resolves on its own by the end of the day.

I agree.

But the question that still remains open is:
Why I don't get the remote list in Chrome even after purging it?

**Comment by gorhill** [comment]
> Why I don't get the remote list in Chrome even after purging it?

I don't know. I can get the (truncated) remote version. The only way I can reproduce what you have, is by blocking the remote server for behind-the-scene requests to that server, whether using uMatrix or uBlock.

**Comment by gorhill** [comment]
Try to restart the browser, sometimes after an update, it happens extensions act weird.

**Comment by Mikey1993** [comment]
Nothing seems to block it.
If this was something system wide, I wouldn't be able to update this list on Firefox..

There is definitely a bug in uBlock, as creating a new profile in Chrome, and installing uBlock with default settings + selecting MVPS HOST list, updates as it should.

**Comment by gorhill** [comment]
> There is definitely a bug in uBlock

See previous comment. Try it please, using your normal profile, but after restarting the browser.

**Comment by Mikey1993** [comment]
> Try to restart the browser, something after an update, it happens extensions act weird.

Restarting Chrome isn't helping.

**Comment by gorhill** [comment]
> Restarting Chrome isn't helping

Do you have _"Continue running background apps when Chromium is closed"_ enabled?

**Comment by Mikey1993** [comment]
> Do you have "Continue running background apps when Chromium is closed" enabled?

No, I have disabled this options long ago, before I had this problem.

**Comment by gorhill** [comment]
I will investigate further.

**Comment by Betsy25** [comment]
I have the same experience here on Firefox nightly, when downloading the list from http://winhelp2002.mvps.org/hosts.txt

It's cutting off with **0.0.0.0 medi** being the last line.
It's also cutting off at the same spot when opening
chrome://ublock/content/asset-viewer.html?url=assets/thirdparties/winhelp2002.mvps.org/hosts.txt

**Comment by gorhill** [comment]
@Betsy25 That's a server problem. @Mikey1993's problem is that he doesn't even get that version, he gets only the packaged version, which dates from January 24th. The only way I can reproduce such behavior is by preventing a network connection to the remote `winhelp2002.mvps.org` server.

@Mikey1993 : I just can't repro. Something in your Chrome settings is preventing a connection to the remote server. How do you get 236K + 70K filters? I also notice the number of custom filters is different in your Firefox and Chrome.

**Comment by gorhill** [comment]
Note that if `winhelp2002.mvps.org` sends you back an empty file, uBlock will consider this an error and fall back onto the packaged version.

**Comment by gorhill** [comment]
@Mikey1993 Can you repeat you flush-cache-apply-change scenario as seen in the video, but with the behind-the-scene network request logger opened and see what it says?

![a](https://cloud.githubusercontent.com/assets/585534/6426509/bb75214a-bf2c-11e4-9fff-a9b22b619b62.png)

**Comment by Mikey1993** [comment]
> Can you repeat you flush-cache-apply-change scenario as seen in the video, but with the behind-the-scene network request logger opened and see what it says?

Yes, I do get the same result in the logger as yours after repeating the scenario.

**Comment by Mikey1993** [comment]
Oh, if I hit the "Disable cache" from the Console, and then repeating the scenario, I get the file from the server and not from the cache!

If, then, I uncheck it, I can no longer reproduce and get the Jan. list (the outdated cached file).

This got resolved through the Console, but I am pretty sure there is a bug in uBlock, which somehow not clearing/updating cached content as it should because of the fact that, if telling Chrome explicitly to not use the cached version + seeing that an XHR request was actually sent(?) in the logger, sorted out this issue.

**Comment by Mikey1993** [comment]
Interestingly, when browsing to:
`%AppData%\Local\Google\Chrome SxS\User Data\Default\Extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm\0.8.9.0_0\assets\thirdparties\winhelp2002.mvps.org\hosts.txt`

I still have the Jan. list file (outdated list).

Is this expected?
Is there anywhere else where the cached version should be?

**Comment by gorhill** [comment]
Yes it is expected, it's the packaged version. The cached version is opaque to users, it's in a Chrome API storage.

**Comment by gorhill** [comment]
Are you using a version of uBlock which is built locally from the code repository?

**Comment by Mikey1993** [comment]
> Are you using a version of uBlock which is built locally from the code repository?

No. 
The Firefox version has been installed from Github (from release XPIs, not compiled manually from code repository).
And Chrome is being updated through Chrome Store.

**Comment by gorhill** [comment]
> I am pretty sure there is a bug in uBlock

Look, I cannot prevent the browser from returning it's own internal cached copy instead of querying the remote server. You probably had MVPS updated shortly before they updated to their newer (broken) version, and the browser had that copy cached internally.

**Comment by Mikey1993** [comment]
> Look, I cannot prevent the browser from returning it's own internal cached copy instead of querying the remote server.

Sure thing, 
At least I now know how to overcome this issue if it ever happens again.

**Comment by Mikey1993** [comment]
The list hasn't been updated from Feb 28. and still broken.
Should we inform the creator? 
I think he isn't aware of this.

**Edit**: The list has been fixed.
