### ISSUE TITLE
Please include cosmetic filters in the network request logger

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#902]
We had discussed this issue [earlier](https://github.com/gorhill/uBlock/issues/87#issuecomment-49548755). ABP for Chromium doesn't show them either - but simply because it's not on par with the Firefox version which does. I've just installed ABP in Firefox again to confirm this.

I'm still convinced that users would benefit from logging them, particularly in the case of false positves. Your argument was that introducing more features would lead to more feature requests and bloat. However, since then µBlock has changed a lot and is no longer a "simple" blocker but - with the introduction of Dynamic Filtering - a tool which offers features for advanced users. I think an advanced user can also expect that cosmetic filters are logged in order to get a complete picture.

So please consider again to add this feature.

**Comment by Mikey1993** [comment]
Dup #308

**Comment by ghost** [comment]
Ah, sorry - I had missed that ...
