### ISSUE TITLE
[Firefox] Counter of blocked requests on the icon overflow

### ISSUE THREAD

**Issue by sha-265** [uBlock-LLC/uBlock#904]
Version: 0.8.9.0
Firefox: 36 on Windows 7
![ublock](https://cloud.githubusercontent.com/assets/4103710/6426800/15312584-bf74-11e4-9cec-1bdea7e54d55.JPG)

**Comment by Deathamns** [comment]
Try [0.8.9.1](https://github.com/gorhill/uBlock/releases/tag/0.8.9.1).
Probably duplicate of #892.

**Comment by sha-265** [comment]
Better, but still I think it's not in the right position. Does it?
![ublock](https://cloud.githubusercontent.com/assets/4103710/6426875/45be7ae6-bf77-11e4-999a-e954bb104c27.JPG)

**Comment by Deathamns** [comment]
The position is OK, but the background color should be darkgrey.

**Comment by harshanvn** [comment]
v0.8.9.1 fixed the issue for me. It is perfect now! Thanks (FF v36, Dev Theme)
![ublock counter](https://cloud.githubusercontent.com/assets/779630/6426924/cecaca5a-bf96-11e4-8167-e919992d9977.PNG)
