### ISSUE TITLE
Option to configure blacklists that get disabled by the off button

### ISSUE THREAD

**Issue by lightonflux** [uBlock-LLC/uBlock#907]
I really like that the big off button disables ublock only for the current domain, which is very handy.

Many sites earn through ads so i want to disable ublock for them. Which works, but this also means that all the social media widgets don't get blocked anymore.

It would be great if the user could configure which blocklists get disabled when s/he clicks on the off button.

**Comment by gorhill** [comment]
That button is to create whitelist directives. Whitelist directives on a per filterset basis is way beyond complicated, in code and UI-wise.

**Comment by gorhill** [comment]
By the way, just to be clear, no feature should be rationalized using the "my site" argument, this is a tool to serve users only.
