### ISSUE TITLE
[Request] Ignore first party trackers

### ISSUE THREAD

**Issue by FatOrangutan** [uBlock-LLC/uBlock#909]
It would be great if uBlock could ignore first party trackers, "for example: ignore instances of DoubleClick tracker on doubleclick.com", similar to how Ghostery does it. It is something that needs to be done manually anyways, to make the website any usable.

**Comment by gorhill** [comment]
I don't understand the request. You can create whatever filter you want.

**Comment by FatOrangutan** [comment]
Consider this scenario:
At the moment, I have \* bannersnack.com \* block as one of my filters.
This works fine as long as I don't visit bannerstack.com.
When I do, the webpage looks like this:
![untitled](https://cloud.githubusercontent.com/assets/8336638/6432023/de496a0e-c068-11e4-9342-466503ae9033.png)
This, although expected, requires an extra step to make the website any usable, that to noop bannerstack.com on bannerstack.com.
My request was to automate this process of nooping every tracker etc. on its own website, since it will be required in pretty much every scenario otherwise the website becomes / looks useless as in the screenshot.
This is also how Ghostery handles things by default: If I have whatever is the Ghostery equivalent of facebook.com \* block, then this particular filter would be automatically ignored when I visit Facebook.com.

**Comment by gorhill** [comment]
Dynamic filtering is for advanced user, those who accept that there will be micro-managing to do.

uBlock can't decide on user's behalf to automatically create an unblocking rule **after** the user entered a blocking rule, that goes counter to what the user may want, and counter to good security habit. No way uBlock will automatically create a rule which causes all javascript on site to execute after the user created a block rule. Maybe it's what you want, but uBlock can't read mind.

As you say, the workaround is simple, create a `noop` rule if you care about not breaking a specific web site, that's the safest approach.
