### ISSUE TITLE
Record blocked requests for popup

### ISSUE THREAD

**Issue by gorhill** [uBlock-LLC/uBlock#91]
As discussed in #85.

I am curious too about knowing how the requests was blocked. This feature will also serve to confirm the net request associated with the root document of the popup was effectively blocked.

**Comment by harshanvn** [comment]
Thank You!

**Comment by gorhill** [comment]
On the surface, trivial, however not so internally. Thing is, one specific URL can be opened in many tabs, so it may be impossible to reliably reverse look-up a tab id from a URL if this URL is opened in more than one tab.
