### ISSUE TITLE
High CPU, especially noticeable on gmail. Reverting to AdBlock fixes the CPU issue

### ISSUE THREAD

**Issue by namit** [uBlock-LLC/uBlock#911]
As you claim that uBlock is significantly leaner in CPU usage than AdBlock, I'm assuming something unique is going on in my browser that I see a completely opposite behavior. I'm using the stock uBlock or AdBlock, and in addition, I have LastPass & Google Docs extensions enabled in Chrome. I usually have 4-5 tabs open, where two are always gmail and google calendar.

Now, gmail has slowed down to almost a halt! Every click and typing event doesn't give me feedback for a second or two. CPU usage varies from 60% to 90%. If I disable uBlock, everything goes back to normal. Please let me know what I can do to help you find the cause.

**Comment by gorhill** [comment]
Browser / version / filter lists / custom filters / any settings which is different from defaults.

**Comment by gorhill** [comment]
I iinstalled Google Docs, LastPass, went into the only Gmail account I have, for testing purpose, ran a profiling session, and all was fine. Gmail UI is certainly CPU-intensive, but uBlock barely adds to this, the profiling results are virtually no different with or without uBlock.

So I need more details about your specific settings with uBlock.

Also, when you say "CPU usage varies from 60% to 90%", can you tell me what is the process for that kind of CPU usage? Use Chromium's Task Manager to see this.

**Comment by namit** [comment]
Browser: 
Version 40.0.2214.115 (64-bit)

Active Filter lists:
 My filters‎: 0 used out of 0
 µBlock filters‎: 133 used out of 133
 µBlock filters – Privacy‎: 2 used out of 2
 EasyList‎ (adblockplus.org): 55,707 used out of 55,737
 Peter Lowe’s Ad server list‎ (yoyo.org): 2,405 used out of 2,447
 EasyPrivacy‎ (adblockplus.org): 10,292 used out of 10,293
 Malware Domain List‎ (malwaredomainlist.com): 1,350 used out of 1,350
 Malware domains‎: 21,747 used out of 21,850
 Malware domains (long-lived)‎: 7 used out of 3,367

Custom filters: None

Settings: All default

I have re-enabled uBlock to reproduce the error and give you details from Chrome's Task Manager. I'll post an update when I see the slow-down again (it doesn't happen immediately).

**Comment by namit** [comment]
Since disabling and enabling uBlock once, I haven't been able to reproduce the issue.

**Comment by namit** [comment]
Okay, I see the issue again. I've already given you the details about the setup. Here are few more details about the Task Manager:
- The task "Tab: Inbox - gmail" has 3GB and 100%+ CPU
- Then I turn off the uBlock extension
- Then I go back to the gmail tab and click around, and within 10 seconds, memory is 2.3GB and CPU is less than 10%

Please let me know if you need any more details.

**Comment by gorhill** [comment]
Maybe related: https://adblockplus.org/forum/viewtopic.php?t=22803?

There are sites which will start to misbehave when something get blocked. For instance, http://www.notcot.org/, if you disable _uBlock filters_ = 100% CPU.

So when this happens again, please look at the developer console, accessible through <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-i, or hamburger menu, then _"More tools"_ then "Developer tools". Look at the console output and see if there is anything in there.

**Comment by chrisaljoudi** [comment]
@1ny interesting. What OS is this on? (Shouldn't matter, but just curious). I'm trying to see if I can reproduce here on Chrome 40/OS X.

Out of curiosity, when you were seeing the high CPU usage, was it just in Chrome's Task Manager or your OS' task manager as well? (Activity Monitor on Mac/Task Manager on Windows/`top` on *NIX).

**Comment by namit** [comment]
I'm on Yosemite 10.10.2. I was seeing the high CPU usage on both task managers. In Chrome's it was pointing to the gmail tab, and in OS's it was pointing to the Chrome Helper.

Last time when I disabled/enabled the extension, it took me a few days to see the problem again. I'm finding it hard to explain that.
