### ISSUE TITLE
Dynamic filter settings not saved for certain domains

### ISSUE THREAD

**Issue by eNTi** [uBlock-LLC/uBlock#912]
having trouble with slashdot.org and fsdn.com... even though i keep setting it to allow and clicking the "lock" symbol afterwards... what is this lock symbol there for again? is it really to "save" the settings or something completely different?

**Comment by gorhill** [comment]
The padlock is to save the rules you created in the current pane. Give me a specific example with detailed steps.

**Comment by eNTi** [comment]
not sure if this happens only on linux... need to test my windows installation for that, but when i open a new slashdot article vie feed the settings i stored for the domains slashdot.org and fsdn.com are set from allow back to deny. could other addons be the cause for the problem? to you somehow rely on cookies for example?

i do have everything set to deny per default. so i'm basically white listing all domains i'm visting. this is my prefered behavior to replace noscript and policy-request.

i've noticed the same happend for imdb.com for another person. i removed the addon and installed  a new version and then it seemed to work.

i can't really pin point the cause. is there away to provide you with more debug feedback?

also... why doesn't it save the the rules for a page automatically? why the need for that extra click, is there a reason or a way to get around this?

**Comment by eNTi** [comment]
so i'm thourougly confused now... i definitely had to set up ublock for certain domains like 20 times already. at least slashdot.org works for NOW. i'll post in this thread again if that changes for some reason.

i hate elusive bugs like that. is there any logs? any debug settings?

**Comment by gorhill** [comment]
> specific example with detailed steps

Please. I can't help you without this. So far, you are the only one reporting problems, so I am assuming it's not a "elusive" bug, but a misunderstanding.

> why doesn't it save the the rules for a page automatically?

By design. See #731.

**Edit:** When I say "detailed", I mean give me exact URL, then what happens, and what you do at each step.

**Comment by eNTi** [comment]
edit:

sorry, i just found the problem, while writing this.

so it seems this has something to do with sub domains. the slashdot articles open are in different categories and those appear in different sub domains. like http://yro.slashdot.org and http://science.slashdot.org. ublock only shows slashdot.org (not the sub domain) and white listing slashdot.org for the current page only whitelists it for the current subdomain. is that by design?

**Comment by gorhill** [comment]
> 1. click on a slashdot feed

I had to stop reading at that point: what's the URL for "slashdot feed"?

**Comment by eNTi** [comment]
http://rss.slashdot.org/~r/Slashdot/slashdot/~3/joIyVeAyoZQ/story01.htm
http://rss.slashdot.org/~r/Slashdot/slashdot/~3/KXE0NtEuUEo/story01.htm

but i found "the issue". read above. both are opened in different sub domains of the site and need to be set separately.

**Comment by gorhill** [comment]
> both are opened in different sub domains of the site and need to be set separately

Yes, the hostname of the URL in the address bar is used as scope.

This is why I advise in the wiki to use default-deny with blocking globally the `3rd-party` cell, not the `all` cell. The `all` cell requires more micro-managing.

Somebody somewhere (I can't remember where, it was in Russian) suggested the ability to select broader scope (like in uMatrix), which would help in your scenario. I might implement this eventually, using space in the title bar to offer a drop down list with hostname or domain as the scope to use.

**Comment by eNTi** [comment]
alright.
