### ISSUE TITLE
[3rd-party] Modifications needed to the malware list

### ISSUE THREAD

**Issue by midas02** [uBlock-LLC/uBlock#913]
Hello,

I don't know what data was used to compile the list of malware domains (https://github.com/gorhill/uBlock/tree/04d501e7e85ee01445fc799ecb123aa6e4436752/assets/thirdparties/mirror1.malwaredomains.com/files), but it contains this entry:
users.telenet.be

That's an outrage. Those are the user pages of Belgium's largest ISP! Needless to say they are not malware at all and should be removed asap.

Best regards

**Comment by Betsy25** [comment]
I'm a Telenet user myself, and indeed, this rule most probably blocks 9/10th of Belgian webspaces.

Those blocklists are created by mostly American volunteers who probably never heard about Belgium, let alone about the major ISP here. ;)

@gorhill temporary whitelisting **users.telenet.be** over the malwaredomains list probably ain't a bad idea. I have contacted the list admin, but still awaiting a response.

**Comment by gorhill** [comment]
@midas02 Please, this list is 3rd-party to uBlock, report to maintainer of the list: http://www.malwaredomains.com
