### ISSUE TITLE
[Request] "Polski filtr adblock" should replace "POL: Adblock Polska"

### ISSUE THREAD

**Issue by konto-andrzeja** [uBlock-LLC/uBlock#917]
As @gorhill suggested, I'm opening a new issue.

[POL: Adblock Polska](https://raw.githubusercontent.com/adblockpolska/Adblock_PL_List/master/adblock_polska.txt) seems not to be actively updated anymore and it contains some exceptions filters clearly meant to allow ads.

[Polski filtr adblock](http://www.certyficate.it/adblock/adblock.txt) doesn't have those problems.

**Comment by gorhill** [comment]
Will move all at once the other filter lists which need to be replaced as per issues: #887, #844, #805.

**Comment by Matthaiks** [comment]
_Polski filtr adblock_ breaks some sites.

**Comment by gorhill** [comment]
Another solution is for a volunteer to fork Adblock Polska, it's GPLv3 right here on github. Then remove the offending filter.

**Edit:** Or file an issue to ask to remove the broad exception filter, maybe they will respond.

**Comment by konto-andrzeja** [comment]
@Matthaiks:

> Polski filtr adblock breaks some sites.

Could you give an example?

**Comment by Matthaiks** [comment]
@konto-andrzeja

No header:
http://sourceforge.net/

No minutes in the live coverage:
http://eurosport.onet.pl/pilka-nozna/liga-wloska/as-roma-juventus-turyn-relacja-na-zywo/eqxqw

**Comment by konto-andrzeja** [comment]
@Matthaiks 

You're right. I guess it's not a very good idea to use it then.

Maybe someone can suggest some other up-to-date filter lists for Polish users.

**Comment by MajkiIT** [comment]
each of you whiny, but does not appreciate the fact that someone is trying and doing something. It seems to me that someone should tell your problems. As you can see the new version removes the errors that are listed here. As for me, you can add these filters are present date. As you know nothing is perfect but you can see that they are working to do something about it.

**Comment by konto-andrzeja** [comment]
@marek45 

I'm not sure if I understood you correctly, but adding a filter list which breaks sites to uBlock default 3rd-party filters isn't a very good idea, that's all. For me it's better than deliberately allowing ads, but still not good enough.

**Comment by gorhill** [comment]
Looked into the candidate list, and there is no GPL or CC license like the current one, so this won't be included.

**Comment by MajkiIT** [comment]
I wrote yesterday to the creators of the filter. As you can see errors corrected. They said that they do this hobby and did not know about the error. I renew my request to add filters.

**Comment by gorhill** [comment]
> License: GNU GPL v3

Was this just added or did I miss it yesterday?

**Comment by MajkiIT** [comment]
I don't know. I just sent them a link yesterday with errors on websites that have been improved here indicated here. I got the answer that they thank and improved filters.

**Comment by MajkiIT** [comment]
hey I found on their website, they say that from the beginning that the filters are licensed under the GNU GPL. http://certyficate.it/polski-filtr-adblock/

**Comment by MajkiIT** [comment]
Are you add this filters to ublock?

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/issues/887#issuecomment-76065503

**Comment by MajkiIT** [comment]
Thank's

**Comment by MajkiIT** [comment]
Is the problem with adding new lists to uBlock have been solved and that you plan to add a list http://certyficate.it/polski-filtr-adblock/ of the next issue uBlock?

**Comment by gorhill** [comment]
See https://github.com/gorhill/uBlock/issues/1127#issuecomment-87671544.
