### ISSUE TITLE
Missing Fanboy subscriptions

### ISSUE THREAD

**Issue by mubaidr** [uBlock-LLC/uBlock#92]
Some of the fanboy subscription lists are missing.

Fanboy Complete List (This includes Easylist, Easyprivacy, and Enhanced Trackers List)

Fanboy Ultimate List (This includes Easylist, Easyprivacy, Enhanced Trackers List and Annoyances List)

https://www.fanboy.co.nz/filters.html

**Comment by ialexsilva** [comment]
Fanboy Ultimate List it has already been added (Fanboy+Easylist-Merged Ultimate List (fanboy.co.nz))
Fanboy Complete List is missing...

**Comment by gorhill** [comment]
Any reason why selecting EasyList, EasyPrivacy and Enhanced Tracker is not ok?

I did include Fanboy Ultimate because it's recommended all over internet, but Fanboy Complete I don't see it mentioned much.

**Comment by mubaidr** [comment]
This is fine if fanboy ultimate list is added.
