### ISSUE TITLE
How do I block pop-ups and pop-unders for certain sites?

### ISSUE THREAD

**Issue by xerogabe106** [uBlock-LLC/uBlock#921]
I poked around the wiki but wasn't able to find an answer. Maybe I'm dumb tho, can anyone give me a hand?

**Comment by gorhill** [comment]
You need to create filters to block whatever it is you want to block. Provide specifics: URL where the problem occurs, etc., and in any case, I don't maintain filter lists here, go to [EasyList forum](https://forums.lanik.us/index.php) to report something which you think should be blocked, along with **all** the details so it saves time for everybody.
