### ISSUE TITLE
[Request] Extend dynamic filtering rule syntax

### ISSUE THREAD

**Issue by Snapy** [uBlock-LLC/uBlock#926]
I would like the option to add multiple domains and/or request types in the same rule separated by pipes or commas. For example `* domain1.com|domain2.com * block` or `* * 1p-script,3p-script block`. So the rules tab could be a little more compact and clear to look at.

**Comment by Mikey1993** [comment]
This can be beneficial for everyone who is messing with the Dynamic Filtering rules manually, though it would be neat if uBlock could add and subtract the rules dynamically instead of adding a new rule every time. 

**There just the need to insure there won't be a very long rule somehow, as this can surely break readability**

So +1 from me, if the right balance is found.

**Comment by gorhill** [comment]
Gave some thoughts to this, and I don't believe it's worth it. The output is pretty much a straight representation of how data is organized internally, so this would add  a lot of complication in the code for just something nice to have, maybe.

**Comment by Snapy** [comment]
Thanks for the answer. I just need one more clarification about what you said in issue #840. If there is no UI related for a feature it is not likely to be implemented or am I wrong ?

**Comment by gorhill** [comment]
Supporting types in hostname-based rules lead to ambiguity:

```
* imgur.com image noop
* imgur * block
```

Cell for `imgur.com` would be red, yet image requests are not blocked. The UI ends up "lying". In uMatrix that ambiguity does not exist, the UI does not lie, hence it's allowed in uMatrix.

There is no UI for "images from imgur.com", as opposed to uMatrix.

**Comment by Snapy** [comment]
Thanks for clarification. Dynamic filtering remains powerful but I will use another extension as I need more control. I also really enjoy the recent improvements of the network request logger.
