### ISSUE TITLE
i18n: logFilterPrompt/statsFilterPrompt inconsistency

### ISSUE THREAD

**Issue by chrisaljoudi** [uBlock-LLC/uBlock#928]
In 6e28b68cb32ced17ab07fdecceb67a11992cb4d2, a bunch of translations for `statsFilterPrompt` were merged (which is great). However, the **English** `messages.json` was changed to `logFilterPrompt`.

Inconsistency should be resolved one way or the other, it seems.

It's worth noting that [the actual file uses `statsFilterPrompt` right now](https://github.com/gorhill/uBlock/blob/master/src/devtool-log.html#L13).

**Comment by gorhill** [comment]
I have all changes locally, I am waiting for some more translations before checking in everything.

**Comment by chrisaljoudi** [comment]
@gorhill got it; sorry.
