### ISSUE TITLE
Cannot log in to IBM

### ISSUE THREAD

**Issue by ayeec** [uBlock-LLC/uBlock#930]
uBlock version 0.8.8.2

Having the blocker activated it is impossible to log in by pressing the button.
For example, this address:
https://www-947.ibm.com/account/userservices/jsp/login.jsp?persistPage=true&page=/support/entry/myportal/fixcentral_redirect&PD-REFERER=none&error=
changes to this one after clicking
https://www-947.ibm.com/account/userservices/jsp/login.jsp?persistPage=true&page=/support/entry/myportal/fixcentral_redirect&PD-REFERER=none&error=#

Disabling it by clicking the "On/Off" button then reloading proved to be successful.

Here it is the backup configuration:

{
  "timeStamp": 1425433000591,
  "version": "0.8.8.2",
  "userSettings": {
    "advancedUserEnabled": false,
    "autoUpdate": true,
    "collapseBlocked": true,
    "contextMenuEnabled": true,
    "dynamicFilteringString": "",
    "dynamicFilteringEnabled": false,
    "experimentalEnabled": false,
    "externalLists": "! Examples:\n! https://easylist-downloads.adblockplus.org/antiadblockfilters.txt\n! https://easylist-downloads.adblockplus.org/fb_annoyances_full.txt\n! https://easylist-downloads.adblockplus.org/fb_annoyances_sidebar.txt\n! https://easylist-downloads.adblockplus.org/fb_annoyances_newsfeed.txt\n! https://easylist-downloads.adblockplus.org/yt_annoyances_full.txt\n! https://easylist-downloads.adblockplus.org/yt_annoyances_comments.txt\n! https://easylist-downloads.adblockplus.org/yt_annoyances_suggestions.txt\n! https://easylist-downloads.adblockplus.org/yt_annoyances_other.txt",
    "firewallPaneMinimized": true,
    "parseAllABPHideFilters": true,
    "showIconBadge": true
  },
  "filterLists": {
    "assets/user/filters.txt": {
      "group": "default",
      "off": false,
      "entryCount": 0,
      "entryUsedCount": 0
    },
    "assets/ublock/filters.txt": {
      "title": "µBlock filters",
      "group": "default",
      "off": false,
      "entryCount": 128,
      "entryUsedCount": 128
    },
    "assets/ublock/privacy.txt": {
      "title": "µBlock filters – Privacy",
      "group": "default",
      "off": false,
      "entryCount": 2,
      "entryUsedCount": 2
    },
    "assets/thirdparties/raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt": {
      "off": true,
      "title": "Anti-Adblock Killer | Reek",
      "group": "ads",
      "homeURL": "https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt"
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt": {
      "title": "EasyList",
      "group": "ads",
      "homeURL": "https://easylist-downloads.adblockplus.org/easylist.txt",
      "off": false,
      "entryCount": 53131,
      "entryUsedCount": 53102
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easylist_noelemhide.txt": {
      "off": true,
      "title": "EasyList without element hiding rules",
      "group": "ads",
      "homeURL": "https://easylist-downloads.adblockplus.org/easylist_noelemhide.txt"
    },
    "assets/thirdparties/pgl.yoyo.org/as/serverlist": {
      "title": "Peter Lowe’s Ad server list",
      "group": "ads",
      "homeURL": "http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext",
      "off": false,
      "entryCount": 2445,
      "entryUsedCount": 2403
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt": {
      "title": "EasyPrivacy",
      "group": "privacy",
      "homeURL": "https://easylist-downloads.adblockplus.org/easyprivacy.txt",
      "off": false,
      "entryCount": 9819,
      "entryUsedCount": 9818
    },
    "assets/thirdparties/www.fanboy.co.nz/enhancedstats.txt": {
      "off": true,
      "title": "Fanboy’s Enhanced Tracking List",
      "group": "privacy",
      "homeURL": "https://www.fanboy.co.nz/enhancedstats.txt"
    },
    "assets/thirdparties/mirror1.malwaredomains.com/files/immortal_domains.txt": {
      "off": true,
      "title": "Malware domains (long-lived)",
      "group": "malware",
      "homeURL": ""
    },
    "assets/thirdparties/mirror1.malwaredomains.com/files/justdomains": {
      "title": "Malware domains",
      "group": "malware",
      "homeURL": "",
      "off": false,
      "entryCount": 23008,
      "entryUsedCount": 22890
    },
    "assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt": {
      "title": "Malware Domain List",
      "group": "malware",
      "homeURL": "http://www.malwaredomainlist.com/hostslist/hosts.txt",
      "off": false,
      "entryCount": 1358,
      "entryUsedCount": 1358
    },
    "assets/thirdparties/spam404bl.com/spam404scamlist.txt": {
      "off": true,
      "title": "Spam404",
      "group": "malware",
      "homeURL": "http://spam404bl.com/spam404scamlist.txt"
    },
    "assets/thirdparties/www.fanboy.co.nz/fanboy-antifacebook.txt": {
      "off": true,
      "title": "Anti-ThirdpartySocial (see warning inside list)",
      "group": "social",
      "homeURL": "https://www.fanboy.co.nz/fanboy-antifacebook.txt"
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/fanboy-annoyance.txt": {
      "off": true,
      "title": "Fanboy’s Annoyance List",
      "group": "social",
      "homeURL": "https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt"
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/fanboy-social.txt": {
      "off": true,
      "title": "Fanboy’s Social Blocking List",
      "group": "social",
      "homeURL": "https://easylist-downloads.adblockplus.org/fanboy-social.txt"
    },
    "assets/thirdparties/someonewhocares.org/hosts/hosts": {
      "off": true,
      "title": "Dan Pollock’s hosts file",
      "group": "multipurpose",
      "homeURL": "http://someonewhocares.org/hosts/hosts"
    },
    "assets/thirdparties/www.fanboy.co.nz/fanboy-ultimate.txt": {
      "off": true,
      "title": "Fanboy+Easylist-Merged Ultimate List",
      "group": "multipurpose",
      "homeURL": "https://www.fanboy.co.nz/r/fanboy-ultimate.txt"
    },
    "assets/thirdparties/hosts-file.net/ad-servers": {
      "off": true,
      "title": "hpHosts’s Ad and tracking servers",
      "group": "multipurpose",
      "homeURL": "http://hosts-file.net/.%5Cad_servers.txt"
    },
    "assets/thirdparties/winhelp2002.mvps.org/hosts.txt": {
      "off": true,
      "title": "MVPS HOSTS",
      "group": "multipurpose",
      "homeURL": "http://winhelp2002.mvps.org/hosts.txt"
    },
    "assets/thirdparties/liste-ar-adblock.googlecode.com/hg/Liste_AR.txt": {
      "off": true,
      "title": "ara: Liste AR",
      "group": "regions",
      "homeURL": "https://liste-ar-adblock.googlecode.com/hg/Liste_AR.txt"
    },
    "assets/thirdparties/stanev.org/abp/adblock_bg.txt": {
      "off": true,
      "title": "BGR: Bulgarian Adblock list",
      "group": "regions",
      "homeURL": "http://stanev.org/abp/adblock_bg.txt"
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easylistchina.txt": {
      "off": true,
      "title": "CHN: EasyList China (中文)",
      "group": "regions",
      "homeURL": "https://easylist-downloads.adblockplus.org/easylistchina.txt"
    },
    "assets/thirdparties/raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt": {
      "off": true,
      "title": "CHN: China: cjxlist (main focus on Chinese sites)",
      "group": "regions",
      "homeURL": "https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt"
    },
    "assets/thirdparties/cjxlist1.googlecode.com/svn/cjxlist.txt": {
      "off": true,
      "title": "CHN: China: cjxlist (obsolete, will be removed)",
      "group": "regions",
      "homeURL": "https://cjxlist1.googlecode.com/svn/cjxlist.txt"
    },
    "assets/thirdparties/raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt": {
      "off": true,
      "title": "CZE, SVK: EasyList Czech and Slovak",
      "group": "regions",
      "homeURL": "https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt"
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easylistgermany.txt": {
      "off": true,
      "title": "DEU: EasyList Germany",
      "group": "regions",
      "homeURL": "https://easylist-downloads.adblockplus.org/easylistgermany.txt"
    },
    "assets/thirdparties/adblock.schack.dk/block.txt": {
      "off": true,
      "title": "DNK: Schacks Adblock Plus liste",
      "group": "regions"
    },
    "assets/thirdparties/abp.mozilla-hispano.org/nauscopio/filtros.txt": {
      "off": true,
      "title": "ESP: Filtros Nauscopicos",
      "group": "regions",
      "homeURL": "http://abp.mozilla-hispano.org/nauscopio/filtros.txt"
    },
    "https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt": {
      "off": true,
      "title": "EU: Prebake - Filter Obtrusive Cookie Notices",
      "group": "regions",
      "homeURL": "https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt"
    },
    "assets/thirdparties/raw.githubusercontent.com/wiltteri/wiltteri.txt/master/wiltteri.txt": {
      "off": true,
      "title": "FIN: Wiltteri",
      "group": "regions",
      "homeURL": "http://raw.githubusercontent.com/wiltteri/wiltteri.txt/master/wiltteri.txt"
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/liste_fr.txt": {
      "off": true,
      "title": "FRA: EasyList Liste FR",
      "group": "regions",
      "homeURL": "https://easylist-downloads.adblockplus.org/liste_fr.txt"
    },
    "assets/thirdparties/www.void.gr/kargig/void-gr-filters.txt": {
      "off": true,
      "title": "GRC: Greek AdBlock Filter",
      "group": "regions",
      "homeURL": "https://www.void.gr/kargig/void-gr-filters.txt"
    },
    "assets/thirdparties/www.hufilter.hu/hufilter.txt": {
      "off": true,
      "title": "HUN: hufilter (obsolete, will be removed)",
      "group": "regions",
      "homeURL": ""
    },
    "assets/thirdparties/indonesianadblockrules.googlecode.com/hg/subscriptions/abpindo.txt": {
      "off": true,
      "title": "IDN: ABPindo",
      "group": "regions",
      "homeURL": "https://indonesianadblockrules.googlecode.com/hg/subscriptions/abpindo.txt"
    },
    "assets/thirdparties/adblock.gardar.net/is.abp.txt": {
      "off": true,
      "title": "ISL: Icelandic ABP List",
      "group": "regions"
    },
    "assets/thirdparties/raw.githubusercontent.com/AdBlockPlusIsrael/EasyListHebrew/master/EasyListHebrew.txt": {
      "off": true,
      "title": "ISR: EasyList Hebrew",
      "group": "regions",
      "homeURL": "https://raw.githubusercontent.com/AdBlockPlusIsrael/EasyListHebrew/master/EasyListHebrew.txt"
    },
    "assets/thirdparties/dl.dropboxusercontent.com/u/1289327/abpxfiles/filtri.txt": {
      "off": true,
      "title": "ITA: ABP X Files",
      "group": "regions",
      "homeURL": "https://dl.dropboxusercontent.com/u/1289327/abpxfiles/filtri.txt"
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easylistitaly.txt": {
      "off": true,
      "title": "ITA: EasyList Italy",
      "group": "regions",
      "homeURL": "https://easylist-downloads.adblockplus.org/easylistitaly.txt"
    },
    "assets/thirdparties/raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abp_jp.txt": {
      "off": true,
      "title": "JPN: ABP Japanese filters (日本用フィルタ)",
      "group": "regions",
      "homeURL": "https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt"
    },
    "assets/thirdparties/raw.githubusercontent.com/szpeter80/hufilter/master/hufilter.txt": {
      "off": true,
      "title": "HUN: hufilter",
      "group": "regions",
      "homeURL": "https://raw.githubusercontent.com/szpeter80/hufilter/master/hufilter.txt"
    },
    "assets/thirdparties/www.fanboy.co.nz/fanboy-korean.txt": {
      "off": true,
      "title": "KOR: Fanboy's Korean",
      "group": "regions",
      "homeURL": "https://www.fanboy.co.nz/fanboy-korean.txt"
    },
    "assets/thirdparties/margevicius.lt/easylistlithuania.txt": {
      "off": true,
      "title": "LTU: Adblock Plus Lithuania",
      "group": "regions",
      "homeURL": "http://margevicius.lt/easylistlithuania.txt"
    },
    "assets/thirdparties/gitorious.org/adblock-latvian/adblock-latvian/raw/master_lists/latvian-list.txt": {
      "off": true,
      "title": "LVA: Latvian List",
      "group": "regions",
      "homeURL": "https://gitorious.org/adblock-latvian/adblock-latvian/raw/master%3Alists/latvian-list.txt"
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easylistdutch.txt": {
      "off": true,
      "title": "NLD: EasyList Dutch",
      "group": "regions",
      "homeURL": "https://easylist-downloads.adblockplus.org/easylistdutch.txt"
    },
    "assets/thirdparties/home.fredfiber.no/langsholt/adblock.txt": {
      "off": true,
      "title": "NOR: Norsk adblockliste",
      "group": "regions",
      "homeURL": "http://home.fredfiber.no/langsholt/adblock.txt"
    },
    "assets/thirdparties/raw.githubusercontent.com/adblockpolska/Adblock_PL_List/master/adblock_polska.txt": {
      "off": true,
      "title": "POL: Adblock Polska",
      "group": "regions",
      "homeURL": "https://raw.githubusercontent.com/adblockpolska/Adblock_PL_List/master/adblock_polska.txt"
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/advblock.txt": {
      "off": true,
      "title": "RUS: RU AdList (Дополнительная региональная подписка)",
      "group": "regions",
      "homeURL": "https://easylist-downloads.adblockplus.org/advblock.txt"
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/bitblock.txt": {
      "off": true,
      "title": "RUS: BitBlock List (Дополнительная подписка фильтров)",
      "group": "regions",
      "homeURL": "https://easylist-downloads.adblockplus.org/bitblock.txt"
    },
    "assets/thirdparties/www.fanboy.co.nz/fanboy-swedish.txt": {
      "off": true,
      "title": "SWE: Fanboy's Swedish",
      "group": "regions",
      "homeURL": "https://www.fanboy.co.nz/fanboy-swedish.txt"
    },
    "assets/thirdparties/www.fanboy.co.nz/fanboy-vietnam.txt": {
      "off": true,
      "title": "VIE: Fanboy's Vietnamese",
      "group": "regions",
      "homeURL": "https://www.fanboy.co.nz/fanboy-vietnam.txt"
    },
    "assets/thirdparties/www.zoso.ro/pages/rolist.txt": {
      "off": true,
      "title": "ROU: RO-LIST (modified)",
      "group": "regions",
      "homeURL": ""
    }
  },
  "netWhitelist": "behind-the-scene\nchrome-extension-scheme\nchrome-scheme\nopera-scheme\nwww.scribd.com",
  "userFilters": ""
}

**Comment by gorhill** [comment]
EasyPrivacy blocks `https://www.ibm.com/common/stats/stats.js` because of the filter `||ibm.com/common/stats/`. Please report the issue to EasyPrivacy maintainers: https://forums.lanik.us/viewforum.php?f=64.
