### ISSUE TITLE
[Request] List the date of the last restore if the settings were restored

### ISSUE THREAD

**Issue by mike-to-spec** [uBlock-LLC/uBlock#932]
I often back up my settings to restore in various browsers on multiple computers to keep them in sync. 

Would it be possible for ublock to show the last backup and restore timestamps?

**Comment by Mikey1993** [comment]
+1

**Comment by elyrly** [comment]
+1

**Comment by gorhill** [comment]
For translators:

![c](https://cloud.githubusercontent.com/assets/585534/6540082/e0c70662-c458-11e4-9b11-8ba106e22424.png)

**Comment by mike-to-spec** [comment]
@gorhill You are the man. I wish I can donate to you and Chris for the continuous great work on uBlock.

**Comment by my-password-is-password** [comment]
@gorhill, When you back up the file and change the file name to something else it still shows up as the generated file name, `my-ublock-backup_3/6/2015,_9:05:36_PM.txt`, in the settings page.

**Comment by gorhill** [comment]
@my-password-is-password Yes, there is no such thing as the browser firing event for file name change. The file system does not even exist from javascript code point of view, for security reasons.
