### ISSUE TITLE
[Firefox] Image fails to load on github, when page is reloaded after whitelisting image cell..

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#933]
As the title says, 
<b>Step 1:</b> configure uBlock as below -
![ublock image block](https://cloud.githubusercontent.com/assets/779630/6481866/f510b194-c22e-11e4-8c0c-c082ffa0c653.png)

And load the <a href="https://github.com/gorhill/uBlock/commit/9ee707624f9078fb067ddf474e19c7f18ce188e0">url</a>

As expected, image will not load, since, Images are blocked through dynamic filtering.

<b>step 2:</b>Now whitelist image cell and reload using <b>uBlock Refresh </b> as shown below -
![ublock image allow](https://cloud.githubusercontent.com/assets/779630/6481881/14108dd0-c22f-11e4-88f4-c454ec601761.png)

Now image will fail to reload and github says "Sorry, something went wrong. Reload?". If i do a refresh through browser next, it reloads properly.

Below are the logs -
- when image failed to load at <b>step 2</b>
  ![ublock refresh problem](https://cloud.githubusercontent.com/assets/779630/6482025/4eb75b98-c230-11e4-8ff5-c39c53c03085.png)
- Loaded properly when doing an refresh through browser icon
  ![ublock refresh ok](https://cloud.githubusercontent.com/assets/779630/6482033/5a596392-c230-11e4-9087-b8de9d2e9e64.png)

Filter Selected: Ads (1,4), Privacy (All), Malware Domains (1, 4), Social (1, 2), Mulitpurpose (All)
Firefox v36, W7 OS

**Comment by Deathamns** [comment]
If you know how to build it, try with the current master branch.

**Comment by harshanvn** [comment]
Unfortunately, i do not know how to do it.
And also, am not in front of personal PC :)

**Comment by harshanvn** [comment]
dev build : <code><a href="https://github.com/gorhill/uBlock/releases/tag/0.8.9.3-dev.0">0.8.9.3-dev.0</a></code> fixes the issue. Closing it.
Thanks @Deathamns  for the quick fix!

**Comment by harshanvn** [comment]
@gorhill i do not see this issue linked to release page. shouldn't we do that, for consistency?

**Comment by gorhill** [comment]
I don't see any code change attached to this issue.

**Comment by harshanvn** [comment]
this was the <a href="https://github.com/gorhill/uBlock/commit/4a10a51d20a732dc704e57ec60247c0e8ff4e44b">commit</a> fixed the issue. And @Deathamns can confirm it.

**Comment by gorhill** [comment]
Was the bug in a dev build only or was it ever in an official release?

**Comment by harshanvn** [comment]
this bug existed in <code>0.8.9.2</code> and fixed with <code>0.8.9.3</code>

**Comment by gorhill** [comment]
The only change in 0.8.9.2 was Safari code, so this can't possibly have been introduced in 0.8.9.2.

Here is the thing: if a bug surfaced in a dev build, and it is fix in a dev build, i.e. if a bug has never been part of an official release, it should not be documented in a release, as this would lead users to believe the bug affected them in a previous release.

So was this ever in an official release?

**Edit:** I will list them, but in a separate section, which will make clear this affected only users of dev builds.

**Comment by harshanvn** [comment]
> The only change in 0.8.9.2 was Safari code

What i meant was, i encountered/observed the issue in 0.8.9.2 build. It may have been existed before.

Anyways, I see that the issue is still present with <code>v0.9.0.1-dev1</code>. But with a <b>different url</b>, original url works fine!

Steps to reproduce the issue remains the same.

Test URL: https://github.com/gocemitevski/uBlock/commit/c8bc75d315852a1d96c8b4ad12670d7233bb9394

**Comment by Deathamns** [comment]
I don't know why Firefox is being clumsy about this, but I think this is a browser bug. It happens also when I restarted the browser without using dynamic filtering.
It seems that bypassing the cache on reload will help.

**Comment by harshanvn** [comment]
Thanks @Deathamns for the fix https://github.com/gorhill/uBlock/commit/48503f700955726ca01ca541e2af444055122675
Bypassing Cache helps the situation here. 
I think we are good now. It should cause no more issues, as always do force-refresh.

@gorhill shouldn't we do force refresh every where, to be in cosistent with firefox implementation. Also, i think it will be ideal to have force refresh, when we unblock/block the requests thru dynamic UI pane.

**Comment by gorhill** [comment]
> shouldn't we do force refresh every where

I don't understand what you mean.

**Comment by harshanvn** [comment]
> force-refresh

meaning Ctrl+F5

**Comment by gorhill** [comment]
But that's what the refresh button is for. I'm lost.

**Comment by harshanvn** [comment]
Is it. Then, for some reason in FF it is not doing Ctrl+F5. To fix it, @Deathamns , had to pass the bypass_cache flag to reload method. 
I think we are all set then.
We can close the issue.

**Comment by gorhill** [comment]
> bypass_cache flag to reload method

Ok you mean to bypass cache for all platforms (Chromium, Safari)?

**Comment by harshanvn** [comment]
Yes..
But you already said, Refresh button on popup UI already does that (i.e., ctrl + f5). Or am i missing something here..

**Comment by gorhill** [comment]
> am i missing something here

I am completely lost.

Let's stick to what matters: is the issue originally reported fixed or not? If yes, close please, if not, tell me specifically what does not work.

**Comment by harshanvn** [comment]
Yes, Reported Issue is fixed.
Will close the issue.
