### ISSUE TITLE
Add an options button to the popup

### ISSUE THREAD

**Issue by PhyxionNL** [uBlock-LLC/uBlock#934]
I first had to look up that you can use the version number bar to go to the settings, this isn't logical. How about adding a settings button / icon somewhere (can also be in the version number bar) to make it obvious that you can go to the options through the popup.

**Comment by Deathamns** [comment]
#694.

**Comment by DDGo** [comment]
I kind of agree with Phyxion. When I used uBlock for the first time, I couldn't figure out the setting page. After some random clicking I found teh setting pages reachable from the top of the popup. I really found it obnoxious, as I had to find out myself (as a techy person) to click that

**Comment by PhyxionNL** [comment]
Just an icon (a wrench / gear) would do, can be added next to the version number of something.

@Deathamns I didn't found it but regardless, it's a different kind of issue.

**Comment by gorhill** [comment]
There are other ways to get to options. The title bar is just a nice way to get there once you know about it. I don't want visual pollution. (I did try the gear icon in the title bar a while ago, found it was awful).

**Comment by PhyxionNL** [comment]
I understand you don't want to clutter the interface but something like this is greatly helping with user interaction. Something like this (but then a nice / smaller icon) for example isn't really cluttering the interface.

![ublock](https://cloud.githubusercontent.com/assets/7643972/6483925/ddb549ae-c276-11e4-937f-09221cf2f51b.png)
