### ISSUE TITLE
[Chromium] don't show popup help messages in advanced mode

### ISSUE THREAD

**Issue by 7nolans** [uBlock-LLC/uBlock#935]
Don't show popup help messages in advanced mode (checkbox I am an advanced user (Required reading))
http://i.imgur.com/RNPJpmy.png

advanced mode
http://i.imgur.com/FVyQQJ8.png

windows 7 64bit, chrome 43 64bit

**Comment by DDGo** [comment]
For me it makes sense. Advanced people should already know what the shortcuts are, while people that are not that technically will not use the feature and look for the popups if they need help.

Just my two cents.

**Comment by Deathamns** [comment]
@7nolans You should have read the "[Required reading](https://github.com/gorhill/uBlock/wiki/Advanced-user-features#no-tool-tips)".
