### ISSUE TITLE
[Request] Padlock should only save temporary rules created on the same site you are currently on

### ISSUE THREAD

**Issue by hackel** [uBlock-LLC/uBlock#937]
In advanced mode, I often add temporary rules for a one-off site I will never visit again.  I don't wish to save these rules.  When I later go to a site where I _do_ want to save the rules, those old rules from the previous site are still in the temporary rules buffer and get saved along with the good rules for the current site.  I currently find myself having to go into My Rules all the time to manually edit the temporary rules prior to committing them.

What I propose to solve this issue is, when clicking on the padlock icon to save temporary rules, to only save rules matching the site you are currently on, along with global rules.  As long as this is clearly documented, I believe most users would be able to adapt to it easily and understand the improved workflow.

Another option would be to maintain a separate list of temporary rules for each site (or tab?), but I imagine this would get unnecessarily complicated.

**Comment by gorhill** [comment]
> when clicking on the padlock icon to save temporary rules, to only save rules matching the site you are currently on

That's how it works.

**Comment by hackel** [comment]
Of course you are correct!  In the absence of actual testing, I just assumed it worked that way because I still saw the entries in the temporary rules list, and have been manually removing things for nothing.  Thank you for your continued work on this amazing extension!
