### ISSUE TITLE
[Safari] Pictures on Facebook won't Load

### ISSUE THREAD

**Issue by alexv93** [uBlock-LLC/uBlock#938]
On Facebook when you are looking through an album of pictures when the number of requests block increases the next image or video will not load. If you close the picture and open it again it works again. I am currently using the 8.9.2 version of ublock on Safari 8.0.3 on OS X 10.10.2. I was not able to reproduce the issue in Chrome or Firefox.

**Comment by chrisaljoudi** [comment]
Dup of #878 — fixed in 83975124a41e135374f1555f241525b12b5b53a6.
