### ISSUE TITLE
Blink ads (ABP ok)

### ISSUE THREAD

**Issue by pvlb** [uBlock-LLC/uBlock#939]
In all pages www.opennet.ru on first entry flashes/blink ads (for ABP ok), next opening appears to be normal.
For example: http://www.opennet.ru/opennews/art.shtml?num=41787

µBlock v0.8.9.1
Chromium 43.0.2322.0 (64-bit) and Firefox 36

**Comment by gorhill** [comment]
[By design](https://github.com/gorhill/uBlock/wiki/Does-%C2%B5Block-block-ads-or-just-hide-them%3F#cosmetic-filters).

Solution: create cosmetic filters for these ads. For example:

```
www.opennet.ru##form > table > tbody > tr:nth-of-type(1) > td:nth-of-type(3)
```

Etc.

**Comment by gorhill** [comment]
Regarding "ABP ok":

Yes, at the cost of holding back page load while it injects 14,000 (20,000+ if using Fanboy Social, more if more lists, etc.) CSS rules in the page + **each frame** on the page. And there is no workaround in ABP to prevent this.

There is a workaround in uBlock to ensure the proper cosmetic filter is injected before the page loads.
