### ISSUE TITLE
"Your filters" does not take effect, at least not with all (ABP) .txt

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#94]
So, I'm using Chromium v38x64 and uBlock v0.2.3.4 and I'm using this list:

https://easylist-downloads.adblockplus.org/yt_annoyances_full.txt

That list above should remove YouTube comments and other annoyances, but it's not working. This list works great in ABP.

![capture](https://cloud.githubusercontent.com/assets/8084723/3675661/96d22620-1280-11e4-8d18-71ece876d2c3.PNG)

And I did click Apply afterwards.

**Comment by ghost** [comment]
Of course this doesn't work. You can add own filters to "Your filters" but **not** filterlists.

You can simply copy and paste the rules from that rather short list which you mentioned to "Your filters".

**Comment by gorhill** [comment]
Importing from URL is not implemented yet: #6.

**Comment by gorhill** [comment]
By the way, EasyPrivacy and Fanboy Ultimate are already available in the preset lists, there would be no need to add them.

**Comment by ghost** [comment]
Haha, lol. Yeah, I did it wrong. It's working now. Great extension btw.
