### ISSUE TITLE
uBlock blocks "Add to cart" functionality

### ISSUE THREAD

**Issue by steffen-sa** [uBlock-LLC/uBlock#940]
Site in question: http://bikstok.sonymusicshop.dk/bikstok-dk/albums.aspx
With uBlock, "Add to cart" (The green button - "læg i kurv") doesn't work when uBlock is enabled.
With it disabled, I was able to add items to the cart.

**Comment by 0xBRM** [comment]
That's most likely a list.
Next time do this https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-disabling-cosmetic-filtering-for-the-current-site

**Comment by steffen-sa** [comment]
Thanks for the reply, I'll remember that. Didn't know if this was worth an issue post, but thank you for the help.

**Comment by 0xBRM** [comment]
Strangely enough, it only worked when I disabled network filtering for google-analytics, and that alone.

http://www.google-analytics.com/ga.js
||google-analytics.com^ is the filter

**Comment by gorhill** [comment]
Can I have a screenshot of how that "Add to cart" button looks? I can't see a difference between the site with or without uBlock.

**Comment by 0xBRM** [comment]
uBlock doesn't hide the button. It's the dark green one.

**Comment by gorhill** [comment]
Oh ok, "doesn't work". So I need to provide a counter filter because `google-analytics.com` in blocked in Peter Lowe's.
