### ISSUE TITLE
"Hide placeholders of blocked elements" does not work with file:// protocol

### ISSUE THREAD

**Issue by dbdr** [uBlock-LLC/uBlock#942]
Trivial case:

```
<!DOCTYPE html>
<html>
<body>
<img src="http://liadm.com">
</body>
</html>
```

Even though I have "Hide placeholders of blocked elements" on, the img is visible as the stock "broken" image.

Seen with uBlock 0.8.8.2, both with FF 36.0 and chromium 40.

**Comment by gorhill** [comment]
I need a URL to test, I don't have a local server set up.

**Comment by dbdr** [comment]
OK, that helps narrow it down. This happens when using the file:// protocol. This is not a huge issue, though if it could be fixed that would help: now I thought I had reproduced a more complex issue with a trivial file, while it's actually a different issue (which I need to investigate before possibly reporting, it's happening with a webapp in development, so not public yet).

**Comment by chrisaljoudi** [comment]
@dbdr Currently, uBlock doesn't fully keep statistics for `file://` pages, nor does it inject the scripts (which are needed to hide the placeholders).

@gorhill from what I can tell by looking, if we wanted to support `file://` protocol pages (which are basically local `.html` files opened in the browser), [manifest.json line 29](https://github.com/gorhill/uBlock/blob/master/platform/chromium/manifest.json#L29) and [manifest.json line 35](https://github.com/gorhill/uBlock/tree/master/platform/chromium/manifest.json#L35) would both have to have `file://*/*` added to them.

And [tab.js line 54](https://github.com/gorhill/uBlock/blob/master/src/js/tab.js#L54) would probably have to accept `file` in addition to `http`, as well.

So @gorhill did you want to support `file://` pages?

**Comment by gorhill** [comment]
I know what the problem is, there is nothing to investigate.

**Comment by gorhill** [comment]
> And tab.js line 54 would probably have to accept file in addition to http, as well

I've never stumbled upon a `file://hostname/` form. Does this ever happen?
