### ISSUE TITLE
Whitelist sites

### ISSUE THREAD

**Issue by petersmith67** [uBlock-LLC/uBlock#946]
How do I properly go about white listing certain sitesDo I just add the url to the box under the whitelist tab.Also why not a dropdown whitelist feature when clicking toolbar button like ABP has?Thanks for any help.Stock ublock settings.Firefox.This is also in the whitelist box by default

behind-the-scene
chrome-extension-scheme
chrome-scheme
opera-scheme

**Comment by gorhill** [comment]
Click he power button:

[![how di you miss this](https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/popup-1b.png)](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button)

**Comment by petersmith67** [comment]
Silly me.Awesome gorhill.So simple that I didnt even think of clicking.

**Comment by ghost** [comment]
The Power button has a story, its color has. Nice blue with a true color reference (forgot the exact denomination). 
That was my participation. Helpful?!

**Comment by gorhill** [comment]
> forgot the exact denomination

["450nm-blue-LED"](https://github.com/gorhill/uBlock/releases/tag/0.8.8.0)
