### ISSUE TITLE
About TLD in My Filters

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#947]
Not an issue, just wondering if I can replace two filters applied to google.com and to google.fr with one only applied to google.tld :

~~||google.com/coop/cse/*~~
~~||google.fr/coop/cse/*~~
-> ||google.tld/coop/cse/*

Thanks.

**Comment by gorhill** [comment]
`||google.*/coop/cse/*` should work.

**Comment by ghost** [comment]
Okay... that would include long TLDs such as google.co.uk I presume.
Didn't think it would work.
The point is I could check but the filters apply to pages I'd have difficulty to reproduce, cannot remember when/where I had built them (migrated from AdBlock Plus, back in the old days...)

Thanks gorhill. uBlock is climbing like a rocket towards the stars, and we have the privilege to be on board : _Houston, we have no problems_ :)

**Comment by ghost** [comment]
@gorhill :

> `||google.*/coop/cse/*` should work.

Now I'm a bit confused. Doesn't this contradict what you wrote [here](https://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-28#post-2465561)?

**Comment by gorhill** [comment]
@tlu1024 "Doesn't this contradict"

No. Above is a filter (ABP filtering syntax). On WS, it was about a rule (dynamic filtering).

**Comment by ghost** [comment]
Sorry - you're right, of course.
