### ISSUE TITLE
x(n-1).bandcamp.com block

### ISSUE THREAD

**Issue by saltushy** [uBlock-LLC/uBlock#949]
a7ie.bandcamp.com,  N8STROM2618.bandcamp.com etc
how to disable forever block for  website?

**Comment by lewisje** [comment]
If you want to whitelist all bandcamp.com subdomains, just add `bandcamp.com` to the Whitelist section.

**Comment by gorhill** [comment]
[How to whitelist a web site: Plain hostname](https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site#plain-hostname)
