### ISSUE TITLE
Suggestion: Custom Lists and Element Hider Features

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#95]
I found your HTTP Switchboard extension a few days ago and it has given me features that I previously could only find in Firefox (NoScript and RequestPolicy), but in a better way than any other extension.

I use HTTP-SB alongside ABP, because HTTP-SB didn't allow custom ABP Subscriptions, or an Element Hide Helper.

I then found this extension which is more efficient, but it doesn't have those features either.

I'd like to request these as features in uBlock and HTTP-SB, because they would allow me to totally bin ABP/Adblock, and if in HTTP-SB would make it even more of a one stop shop for taking control of the broswer and privacy.

**Comment by gorhill** [comment]
Element picker is accessible through the small slashed eye in the popup.

Custom subscription URLs is already filed as issue #6.

I will let you close the bug if you can confirm that uBlock's element picker is what you were looking for.

**Comment by ghost** [comment]
Ah yes, sorry I didn't see that.

I'll close this then, and thank you for your work on these great extensions
