### ISSUE TITLE
Problems with Zenfolio

### ISSUE THREAD

**Issue by jefferai** [uBlock-LLC/uBlock#950]
There is an issue loading Zenfolio (http://www.zenfolio.com) photo sites with uBlock that does not appear with AdBlock or AdBlock Plus. It only appears when the particular Zenfolio site has Google Analytics tracking enabled. When this is the case, loading hangs after the GA code is blocked.

I can point someone to a test site in a PM if desired.

**Comment by chrisaljoudi** [comment]
@jefferai please do share a link to a test site.

Also, browser/filter lists enabled?

**Comment by gorhill** [comment]
From what I gather, Zenfolio is shared hosting. I won't blanket whitelist Google Analytics for all `zenfolio.com`. See if you have the same problem with ABP + EasyPrivacy. If so, then the issue is not uBlock specific.

**Comment by gorhill** [comment]
Just to be clearer, if an exception filter is needed, it will be for a specific site, not for whole Zenfolio.

**Comment by jefferai** [comment]
@gorhill I'm not asking for GA to be whitelisted for Zenfolio. But uBlock uses the same filter lists as ABP (at least, the filters blocking GA come from either EasyPrivacy or EasyList, and as I said in the OP, ABP does _not_ cause this problem.

**Comment by gorhill** [comment]
Peter Lowe's is the one blocking `google-analytics.com`. Use that list in ABP and you will get the same result.

**Comment by jefferai** [comment]
Just tested. Both EasyPrivacy and Peter Lowe's list cause this problem in ABP. I didn't realize EasyPrivacy wasn't included in ABP per default, so thought this was a uBlock problem specifically.

Closing this as it's not uBlock specific (I've already been trying to get Zenfolio Customer Support to get this info over to the developer team...)
