### ISSUE TITLE
[EasyList] Skips Yahoo ads

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#951]
![1](https://cloud.githubusercontent.com/assets/5372918/6514209/469b01bc-c389-11e4-9f80-dea57ac7c88e.JPG)

**Comment by chrisaljoudi** [comment]
@vibrasphere can you please post a link to that page where this occurs?

(We'll also probably want what filters you have enabled, browser/version, etc. — but link is most crucial).

**Comment by ghost** [comment]
https://answers.yahoo.com/question/index?qid=20130221222909AAmzZB8

**Comment by ghost** [comment]
Agreed, I was about to post this as well. This issue exists in Firefox. It exists in Adblock Plus too.

**Comment by ghost** [comment]
All available filters enabled. (More than the default) Firefox version 36. Windows 7.

**Comment by ghost** [comment]
I've noticed, in Firefox adblock plus, the issue exists, however in Chrome adblock plus, the issue does not exist.

**Comment by gorhill** [comment]
I can't see this. Reminds me of #696, which I could never reproduce.

Please read the comments in #696, and report what you see, just like in https://github.com/gorhill/uBlock/issues/696#issuecomment-72970259.

**Comment by ghost** [comment]
Yes, this is it exactly.

**Comment by gorhill** [comment]
In #696, it turns out a new filter was needed in EasyList, and I see it is now part of EasyList: `answers.yahoo.com###ya-qpage-textads`. So now we need to find out just like in #696 what is the new filter needed, apparently Yahoo changed something again. [This](https://github.com/gorhill/uBlock/issues/696#issuecomment-72970259) is the way to find out.

**Comment by ghost** [comment]
Can this be added to "µBlock filters‎"?

**Comment by gorhill** [comment]
First, we need to find out the CSS rule. Then once found out, yes it can be added to uBlock filters. However I favor having the rule added to EasyList, as this will benefit **all** users, regardless of the blocker they use.

**Comment by ghost** [comment]
What is the policy regarding what gets added to 'µBlock filters‎' vs being added to 'easylist'? Why is there a separate µBlock filter at all?

**Comment by ghost** [comment]
Looks like it's in an iframe, but without a src.
![temp](https://cloud.githubusercontent.com/assets/11338894/6515489/3595199c-c358-11e4-9db6-32b0bade44b3.png)

**Comment by ghost** [comment]
I checked, the noscript above it has the iframe too. Best to block the div with the id "dmRosAd*" pretty much.

**Comment by chrisaljoudi** [comment]
> Best to block the div with the id "dmRosAd*" pretty much.

Well, that would hide it, but you can actually stop the request that grabs the ad info:

https://answers.yahoo.com/ros/?ct=1&c=cbdde9a2&w=1&h=1&si=north%3A560x315&ty=exclusiveBkt&sp=2115500184&sr=8dcdJIASEk&sa=exclusiveBkt&u=https%3A%2F%2Fanswers.yahoo.com%2Fquestion%2Findex%3Fqid%3D20130221222909AAmzZB8&r=&tt=How%20good%20is%20house%20of%20cards%3F%20%7C%20Yahoo%20Answers

**Comment by chrisaljoudi** [comment]
Adding something like this filter seems to do the job at some level:

```
answers.yahoo.com/ros/
```

**Edit:**

```
yahoo.com/ros/
```

No reason to limit it to Yahoo Answers; sorry.

**Comment by ghost** [comment]
Indeed, this blocks the ad, but leaves a blank space there.

**Comment by gorhill** [comment]
I don't want to see through the Firefox inspector, I want as reported by the element picker.

**Comment by ghost** [comment]
![temp](https://cloud.githubusercontent.com/assets/11338894/6515780/cdf2f04a-c35a-11e4-8014-0b4afca603b9.png)

**Comment by gorhill** [comment]
What's the best match in the cosmetic filter stack? The broadest one which fits the ad?

**Comment by ghost** [comment]
answers.yahoo.com###ya-q-9653-textads.Bgc-w.Pt-7.Mb-neg-10.Bdstart-1g.Bdend-1g.Mih-175

However this code seems arbitrary. (The numbers here may probably vary for each user)

**Comment by chrisaljoudi** [comment]
@litehacker that's not the broadest one, I believe. That's incredibly specific.

I think `###dmRosAdWrapper-MainNorth-iframe` and `###dmRosAdWrapper-MainNorth` are probably a good start.

**Comment by gorhill** [comment]
Ok... This matches the other case:

```
Cosmetic filters Click, Ctrl-click
    ###dmRosAdWrapper-MainNorth-iframe
    ###dmRosAdWrapper-MainNorth
    ###yui_3_17_2_3_1423095504008_1933.Mstart-75.Mr-14
    ###ya-qpage-textads.Bgc-w.Pt-7.Mb-neg-10.Bdstart-1g.Bdend-1g
    ###ya-center-rail.Col2.Pos-a.Bxz-bb.Start-0
    ##.Answers
    ###MasterWrap
```

Again, the one just above `#ya-center-rail`.

So you get a different number every time in `#ya-q-9653-textads`? If so, not difficult to get around maybe, especially given we are dealing with a specific cosmetic filter here. Example:

```
answers.yahoo.com##[id^="ya-q-"][id$="-textads"]
```

**Comment by ghost** [comment]
@chrisaljoudi 

![temp](https://cloud.githubusercontent.com/assets/11338894/6515879/c52e7302-c35b-11e4-8c49-3de478d7b7c8.png)
vs
![temp](https://cloud.githubusercontent.com/assets/11338894/6515888/d08c5eda-c35b-11e4-8d27-14125306edb0.png)
vs
![temp](https://cloud.githubusercontent.com/assets/11338894/6515897/dd078cde-c35b-11e4-9011-b33733ec97cd.png)

**Comment by gorhill** [comment]
Or maybe even safer:

```
answers.yahoo.com###ya-center-rail > [id^="ya-q-"][id$="-textads"]
```

**Comment by chrisaljoudi** [comment]
@litehacker you have a `ya-q-9308-textads` in there, which is different for me (and presumably different for every client as time goes by). The `dmRosAdWrapper-MainNorth` and `###dmRosAdWrapper-MainNorth-iframe` IDs, however, are consistent.

**Comment by ghost** [comment]
gorhill's solution looks good to me.

**Comment by ghost** [comment]
but adding in chrisaljoudi's solution to stop the connection in the first place makes sense as well.

**Comment by ghost** [comment]
This is quite funny. If I were working at the ad department at yahoo, I'd have a script that automatically goes through the easylist every time it's updated, to check if the ad is blocked now, and update the keywords again. :P

**Comment by gorhill** [comment]
Yes, blocking the resource in the `iframe` is the most important part really. Then specific cosmetic filter to avoid the visual glitch. Since I **can't** reproduce the ad, I worry that a filter is too broad and would end up blocking good stuff too. What does "ros" might mean?

**Edit:** typo, "can" = "can't"

**Comment by gorhill** [comment]
Probably related: [EasyList: answers.yahoo.com [ads]](https://forums.lanik.us/viewtopic.php?f=62&t=21252&p=67549).

**Comment by chrisaljoudi** [comment]
@gorhill 

> Since I can't reproduce the ad

Oh, I didn't realize. Is that because you're blocking all 3rd-party-frames, or is it also not reproducible with default configuration?

**Comment by gorhill** [comment]
I use default config when investigating issues. I wasn't able either in the earlier similar bug. I've been wondering if it's because Yahoo give up serving ads to Linux users. I don't know really why. I didn't try with Windows because I find it tedious to launch the VM etc.

**Comment by chrisaljoudi** [comment]
@gorhill I don't know what `ros` is supposed to stand for, but it's pretty clear it's meant for requests for serving ads; here's the JavaScript from the Yahoo page:

```
var R = document.location.protocol + "//answers.yahoo.com/ros/?ct=1&c=" + a(O) +
/* lots of params; truncated */
"&u=" + a(l.location.href.substring(0, 800)) +
"&r=" + a(l.referrer.substring(0, 800)) +
"&tt=" + a(l.title.substring(0, 250)),
w = l.createElement("script"), W = l.head || l.getElementsByTagName("head")[0];

w.type = "text/javascript";
w.src = R;
if (window.LH && window.LH.isInitialized) {
    var N = LH.mark("dmAdCall")
}
```

`LH` is a tracker API that sends events back to Yahoo by sending the event information in the URL of an `Image()`.

**Comment by chrisaljoudi** [comment]
@gorhill Oh, and those `/ros/` requests return a script that calls back a function `dmRosAdCallback` with the ad info.

**Comment by gorhill** [comment]
Well, out of curiosity, I launched Windows/Chrome, and sure enough, I could now see the ad.

**Comment by chrisaljoudi** [comment]
@gorhill interesting. :)

**Comment by gorhill** [comment]
Well I don't know, it's probably all random. Yahoo is probably "rolling out" its new ad CSS id so as to not flood everybody with ads at once. Once all blockers catch up, they will workaround them in a few weeks I suppose.

**Comment by gorhill** [comment]
I tried `||answers.yahoo.com/ros/?`, and I don't get any hit on that filter when reloading the page.

**Comment by chrisaljoudi** [comment]
@gorhill hmm. Here's what I get (Chrome):

![netlog](http://d.pr/i/5em3+)

**Comment by gorhill** [comment]
I went with the cosmetic filter only for now. I fear using `||answers.yahoo.com/ros/?`:
- On my side, I can't see any request matching this
- I am assuming if it's not in EasyList, there is maybe a good reason for this

**Comment by ghost** [comment]
Something you may be already aware of. Gonna be a long battle.

http://marketingland.com/yahoo-acquires-anti-ad-blocker-startup-clarityray-96242

**Comment by ghost** [comment]
Wait, so... I still see the ads.

**Comment by gorhill** [comment]
@vibrasphere Did you get the updated _"uBlock filters"_? If so, then you will have to find out more information like was done above with the element picker.

**Comment by ghost** [comment]
I don't know. I just updated to latest dev version. Where do I get "uBlock filters"?

**Comment by gorhill** [comment]
It's updated automatically. Go in _"3rd-party filters"_ in the dashboard, and see if it is marked as "new version available". If not, click on the list and see if the entry

```
# https://github.com/gorhill/uBlock/issues/951
answers.yahoo.com###ya-center-rail > [id^="ya-q-"][id$="-textads"]
```

appears at the end.

If it is marked as "new version available", click _"Update now"_.

**Comment by ghost** [comment]
I don't know if I did anything, but the ads do not show up anymore. Thanks.

**Comment by ghost** [comment]
So, what is your policy about what goes into the uBlock filter vs easylist?

**Comment by gorhill** [comment]
@litehacker 

What goes in uBlock filters:
- Interim filters to until they make it to EasyList/EasyPrivacy (can be block filters or exception filters to unbreak sites)
- Exception filters to un-break specific sites broken by the use of Peter Lowe's (because it ships enabled by default)
- Filters which are beneficial to uBlock, for example, the [entity-based cosmetic filters](https://github.com/gorhill/uBlock/wiki/Filter-syntax-extensions#cosmetic-filters) related to Google, as this allows these cosmetic filters to be injected earlier
- All additions are explained, so you can find out why something was added

**Comment by AmperAndSand** [comment]
> ```
> # https://github.com/gorhill/uBlock/issues/951
> answers.yahoo.com###ya-center-rail > [id^="ya-q-"][id$="-textads"]
> ```

Just want to add here that [this filter has recently been added in EasyList](https://forums.lanik.us/viewtopic.php?p=67693#p67693).
