### ISSUE TITLE
Enable regional filter lists based on browser locale

### ISSUE THREAD

**Issue by mikhaelkh** [uBlock-LLC/uBlock#957]
I think it'll be a good idea to enable regional filter lists based on browser locale (or some other method) to make this extension even more usable to newbies who complains that it doesn't block ads out of the box.

**Comment by gorhill** [comment]
There are all kind of complaints, including those who think it blocks too much. Given that the regional lists are of widely variable quality, I rather let the users pick explicitly for anything else than the default ones.
