### ISSUE TITLE
Erroroneous "slow addon" message in firefox

### ISSUE THREAD

**Issue by PalmerAL** [uBlock-LLC/uBlock#958]
I have no idea if this is a firefox issue or a ublock issue, but in firefox nightly the "slow addon" message is appearing constantly for ublock. As far as I can tell, the addon isn't actually running slowly, though.

**Comment by TteokbokkiNari** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1137369
There is a bug about this.

**Comment by gorhill** [comment]
Duplicate of #824.

Background info: http://www.ghacks.net/2015/02/18/firefox-38-notifies-you-about-add-ons-that-slow-down-the-browser/
