### ISSUE TITLE
Ublock Images Missing & Breaking Site Images...

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#960]
Hello,

I use Firefox 31.5.0 ESR In Linux and I noticed that the popup window, I tried for both versions, 0.8.9.2 & 0.9.0.0 is missing.

Also the images next to; `on this page` are missing...

Please see the attached image.

![ublock_popup](https://cloud.githubusercontent.com/assets/11289036/6544079/ca1c9676-c533-11e4-9c0d-0e0447a6f89c.jpg)

**Comment by ghost** [comment]
Oh I also realized there are strange images that appear when I look at the `request log`

![request_log](https://cloud.githubusercontent.com/assets/11289036/6544094/95f36f4a-c534-11e4-8f86-35808562ef17.jpg)

I noticed too that on Githib a lot of the images are being broke;

![github](https://cloud.githubusercontent.com/assets/11289036/6544099/04aeb5fc-c535-11e4-809f-b1b47f59c8d9.jpg)

![github_2](https://cloud.githubusercontent.com/assets/11289036/6544101/267499cc-c535-11e4-9f3c-936cf2a897c3.jpg)

**Comment by ghost** [comment]
Are you forcing fonts?

see #629

**Comment by ghost** [comment]
Ahhh I'm sorry, my mistake.

I did have `browser.display.use_document_fonts` on zero... :(

All good now...

Sorry again

**Comment by gorhill** [comment]
Duplicate of #629.
