### ISSUE TITLE
Question: Adblock & Ublock - Ok Together?

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#961]
Is it ok to use Adblock Plus and ublock together in FIrefox, and does it help, or pointless using both?

I also use NoScript, I'm assuming that is good to keep with ublock?

thank you

**Comment by TteokbokkiNari** [comment]
It's pointless to use both at the same time, and probably detrimental to your browser performance.
Just use uBlock with your preferred blocking filters. 
And I'd say NoScript is still good to use, since uBlock doesn't exactly block/protect against the same things as NoScript does.

**Comment by gorhill** [comment]
> Adblock Plus and ublock ... pointless using both

Yes pointless. Use one or the other, depending on what features/traits you favor.

**Comment by ghost** [comment]
Ok, well to be honest the only feature I use in Adblock is the drop down menu, so you can easily disable it, this would be nice to incorporate also into uBlock.

Beyond this, all I want is the best blocking possible.

What drew me to uBLock is what I read online about it's performance over Adblock, but does it block as well, or better?

Something I noticed is that `Fanboy’s Social Blocking List‎` is added by default into Adblock, why isn't this also checked by default in uBlock?

thank you

**Comment by gorhill** [comment]
Fanboy's Social is **not** selected by default in Adblock Plus, you have to enable it. Same thing in uBlock, you have to enable it.

**Comment by ghost** [comment]
Ahh, ok, well when I installed Adblock I clicked all 3 buttons they now have on their fancy install page, hehe... I guess that's what did it. :)

**Comment by ghost** [comment]
I forgot to ask, in Linux do you know what Firefox uses this path for?

/storage/persistent/moz-safe-about+home

By the way, what do you guys think of Disconnect?

https://github.com/disconnectme/disconnect

thanks
