### ISSUE TITLE
Text field with no placeholder in the Network Request Log [0.9.0.0]

### ISSUE THREAD

**Issue by mike-to-spec** [uBlock-LLC/uBlock#962]
![](http://miket.d.pr/1bsaU/2MPT303h.png)

In the improved network request log view, there's an open text field next to the log filter with no placeholder to explain what it is.

**Comment by Mikey1993** [comment]
There is only a tool tip when hovering the textbox.
I agree it should be consistent as much as possible.

**Comment by mike-to-spec** [comment]
Oh there is. I didn't see any tooltip in the first text field, so I didn't even realize there would be one on the second one.

**Comment by gorhill** [comment]
There is no place for a embedded prompt in the second field. And as for a label, I've seen some of the translations, and they are way too long to fit in there.

**Comment by gorhill** [comment]
There is just no place for placeholder text. Even if I would use `max entries` in English, I can guarantee that most translations won't fit. The toolip is the least worst solution.

**Comment by chrisaljoudi** [comment]
@gorhill indeed.

Out of curiosity, what's the default value for the max entry limit? `25,000`? I think it **might** help to have that default number be a placeholder (hits two birds with one stone).

**Comment by mike-to-spec** [comment]
Why does it have to be inside the box? You can't use _Limit requests to_: [25,000]?

Why not just move the text fields to the leftmost position, leave the icons on the right side. So, it'd look like this: 

Search logs for: [images] and limit logs to [25,000 request].  [Refresh icon][Clear icon][Filter? icon]
