### ISSUE TITLE
3rd-party filter list update: show status/progress indications in UI

### ISSUE THREAD

**Issue by chrisaljoudi** [uBlock-LLC/uBlock#965]
When updating 3rd-party filter lists, it's not uncommon to have one of the servers be down or slow every once in a while. Usually, trying again some time later resolves the issue.

In the current implementation, however, the whole 3rd-party filter list page is "whited out" while the update is in progress. There aren't any individuals indicators next to the filter lists, which creates uncertainty in the user's mind what's going on (has uBlock froze or is the update just not going perfectly?).

It seems like it'd be very helpful to the user to, instead of whiting out the whole page with no status indication, have a "progress bar"/"status text" next to each filter list getting updated.

In that case, for example, if a request times out from one of the servers, one would simply see that error message next to the filter list (<kbd>remote fetch timed out</kbd> or something) and try again later.

This will also enable users to see which updates succeed (the status next to the filter would be <kbd>last updated on 03/08/2015 3:25AM</kbd> or some such).

@gorhill I'll be going through tomorrow figuring out a plan/general idea on implementing this, but I'd like to hear your opinion.

Some related issues: #719, #376, #860, #964 (probably).

**Comment by gorhill** [comment]
> I'll be going through tomorrow

I have already work to do in there: #954, + another issue I can't find right now which is about showing the last time a list was updated.

As I say somewhere in here, I work on this project because I like to code.

**Comment by chrisaljoudi** [comment]
@gorhill I understand! If you'd like to work on that, that's completely fine — I just thought I'd offer as to help out with workload.

**Comment by Mikey1993** [comment]
I support this.
Users often find themselves in a mystery to why is the updating process taking so long. 
This disengage users from updating manually their lists regularly for sure.

**Comment by gorhill** [comment]
Fixed in 39ad1585e90acdd824774fdc37a5c283dba01f33.
