### ISSUE TITLE
Provide an in-extension new version check

### ISSUE THREAD

**Issue by TiagoTiago** [uBlock-LLC/uBlock#970]
Since AMO seems to be so many versions behind, it would be nice to have the option of having the extension itself check for new versions on GitHub automatically, and provide a reminder to the user about it until the user installs the latest version available (perhaps an added small symbol in the toolbar button; and, optionally, a toaster every N minutes/hours ?).

**Comment by TiagoTiago** [comment]
Hm, how do I add labels? (to mark this as an enhancement)

Or is that ability limited to the owners?

**Comment by chrisaljoudi** [comment]
@TiagoTiago Just some relevant thoughts. :)

One of the things that's nice about uBlock is that once you have it installed and it's working a way you like, we don't want to ever force you to leave that. uBlock releases are, in a sense, atomic at some level. 

As such, updates are completely up to the user and the browser as you configure it. This doesn't mean that the functionality won't be added (the decision isn't completely mine), but there does exist an argument for not making updates "obtrusive."

**Comment by chrisaljoudi** [comment]
@TiagoTiago yes, adding labels is limited to project collaborators and owners.

**Comment by TiagoTiago** [comment]
@chrisaljoudi 

Me, as a user, would like to be made aware of new versions with fixes and improvements as soon as they are available. But I understand that some people would rather to not be bothered and stick with outdated versions; so making it an option seems like the ideal solution.

While Firefox does provide automatic updates, it's restricted to extensions that have been approved on https://Addons.Mozilla.Org , and it seems it's always many versions behind; I understand not wanting to create a competing automatic update service just for the extension, but I would like to at least have the option of manually installing new versions as soon as they're made available, and for that I would need a way to be made aware when they are.

**Comment by chrisaljoudi** [comment]
@TiagoTiago here's a feed of GitHub releases, if that'd help:

```
https://github.com/gorhill/uBlock/releases.atom
```

**Comment by chrisaljoudi** [comment]
I really think an in-extension check-for-updates mechanism would cause all sorts of issues and frustration if/when it conflicts with the browser's mechanism. I do understand the problem you're describing, but I'm not sure whether it'd be "safe" or worth it to build-in the solution into uBlock.

Subscribing to the feed (see link above; it's just an Atom [RSS-like] feed) should notify you of releases quite swiftly, at which point you can upgrade uBlock if you wish to.

**Comment by TiagoTiago** [comment]
Why would it not be safe to automatically check GitHub for new versions, and add a little icon to the toolbar button, or pop a toaster if the version number is higher than the version installed? Or do you mean you think I shouldn't trust the versions posted on GitHub, and stick with what gets approved on AMO, regardless of how outdated it is?

I know I could keep checking the page here and crosschecking the version number of the latest version with what I have installed every once in a while; but that isn't reliable (I might have my mind too busy with other stuff to remember to check some days), and comparing values is the type of thing computers do much better than people.

**Comment by gorhill** [comment]
> I could keep checking the page

The Atom feed sounds like a good idea to me.

**Comment by chrisaljoudi** [comment]
@TiagoTiago 

> Why would it not be safe to automatically check GitHub for new versions

Oh, it'd be perfectly safe (~~[although it starts to edge on GitHub's ToS](https://help.github.com/articles/github-terms-of-service/)~~ never mind; it's not related to the discussion — sorry) to check. The problem begins when you consider how users are supposed to react.

Most users simply have auto-update on. If we give them a notification badge when a new version is "out" telling them they're outdated, they will:
1. think auto-update isn't working.
2. try to force an update from their browser vendor's store
3. that won't work in most cases (see: AMO)

At that point, the only way for them to be "up to date" is to manually go and download the uBlock build and install it. Automatic browser extension updates are then **worthless**. 

That's just nuts, I'm afraid. We'll be flooded with GitHub Issues of people complaining about the extension not "updating itself".

I hope you understand the problem and why this isn't viable.

**Comment by TiagoTiago** [comment]
What if the option to enable the update check explains to the user what is going on? (perhaps hide it while the user hasn't marked the "I'm an advanced user" checkbox?)

And if having the extension parse the page is gonna upset GitHub, why is it ok to have the browser check the feed? Or does the browser only check feeds manually? (I haven't ever really used feeds)

**Comment by chrisaljoudi** [comment]
@TiagoTiago 

> What if the option to enable the update explains to the user what is going on?

This isn't a common enough scenario of interest. Software shouldn't have **every toggle you can think of** just because somebody, somewhere might use it. It makes software, as a whole, less usable.

> And if having the extension parse the page is gonna upset GitHub

Regardless of what the actual answer is, I shouldn't have brought that up (it would just derail the conversation); I apologize. 

> why is it ok to have the browser check the feed?

GitHub provides the feed automatically. That's what they provide it for. :)

There's a large number of ways to subscribe to an Atom feed, and most would automatically check periodically.
