### ISSUE TITLE
µBlock and others: Benchmark - Privacy Badger?

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#971]
Hi gorhill,

I noticed the testing on this link;

https://github.com/gorhill/uBlock/wiki/2014-07-22:-%C2%B5Block-and-others:-Blocking-ads,-trackers,-malwares

But as it pertains to PrivacyBadger did you see this section on their website?

---

Why doesn't Privacy Badger block all ads?

Because Privacy Badger is primarily a privacy tool, not an ad blocker. Our aim is not to block ads, but to prevent non-consensual invasions of people's privacy because we believe they are inherently objectionable.

---

So then I'd assume uBlock does a better job, but with EFF's approach more Privacy focused, I wonder if it's a good choice to add alongside uBLock?

thanks

**Comment by gorhill** [comment]
I don't know.

**Comment by chrisaljoudi** [comment]
@meuwe the comparison that has Privacy Badger in it doesn't measure ad blocking per se, but rather third-party server exposure. A third-party server resource is, in many cases, used for tracking (though surely not always). 

![Bench](https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/privacy-benchmark.png).

**Comment by ghost** [comment]
Ok thanks guys...
