### ISSUE TITLE
[EasyList] Unblocked rarbg.com ads

### ISSUE THREAD

**Issue by AmperAndSand** [uBlock-LLC/uBlock#972]
Sample URLs:
https://rarbg.com/torrents.php?imdb=tt0113749
https://rarbg.com/torrent/coivs2x

The ads are fake 'download' links that actually lead to an ad (with a drive-by download).

Screenshots, ads encircled in red:
![](http://i.imgur.com/ZQhZkut.png)
![](http://i.imgur.com/YWiMh5C.png)

[EasyList has previously blocked this ad](https://hg.adblockplus.org/easylist/rev/a48b345869da), but it seems that rarbg.com changed the names of the blocked links.

**Comment by ghost** [comment]
`"/adpub_"` -> `"/ad_pub_"`

**Comment by gorhill** [comment]
Contact EasyList maintainers: https://forums.lanik.us/index.php.
