### ISSUE TITLE
[Firefox] Fake poor user review

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#973]
Edit: links removed

**Comment by quilloss** [comment]
More accurately he offers to provide a good software description for $5.
He might be trying to get uBlock to pay for him for a new description.

**Comment by ghost** [comment]
@quilloss 

> He might be trying to get uBlock to pay for him for a new description.

Yes. It appears a form of coercion. 

I'm reticent to detail publicly how to follow the trail as it would dox the user even more than these links do. The review is clearly a violation of AMO user review standards.

gorhill has interacted with the user on another social media site. There the user complained the description for the extension was inadequate. Seems his retaliation was to leave a one star review.

**Comment by gorhill** [comment]
> gorhill has interacted with the user on another social media site

I did?

**Edit:** Ah yes, here: http://www.reddit.com/r/firefox/comments/2y6gwh/for_those_who_were_waiting_ublock_has_been/cp6tv9u

Anyways, I don't really care, especially that this kind of review doesn't reflect very well on the reviewer, as anybody can read for themselves the description which is right there.

**Comment by TteokbokkiNari** [comment]
Would love to see a source.

**Comment by ghost** [comment]
Well, here goes nothing...user accounts are probably fake anyway

Edit: links removed

**Comment by TteokbokkiNari** [comment]
"Really, none of those are specific and precise enough for me to pass around and understand in the time it would take to read one sentence at the very start of the description. "
Yeah, that pretty much makes me pretty sure he's trying to coerce Gorhill.
@gorhill could report him, but I agree that it probably won't really affect anything, especially since bogus reviews like that are somewhat common, so people know to avoid them. 
The average review score is also extremely high, so there's that.

**Comment by ghost** [comment]
> Anyways, I don't really care, especially that this kind of review doesn't reflect very well on the reviewer, as anybody can read for themselves the description which is right there.

@gorhill 

Sounds good. Will close to reduce the clutter.

**Comment by ghost** [comment]
Umm well, there appears to be a bit more than that.

Edit: Links removed

**Comment by chrisaljoudi** [comment]
@kintpuash I think it really doesn't matter. We're not going to worry about everyone who writes an unjustified negative review. There's too many _"rude"_ people out there.

Giving them, singularly, attention when the project has hundreds of thousands of users is rewarding to them, and seeking attention is probably part of their motive. It is not a behavior that should be encouraged — it's a behavior that should be, it seems, ignored and dismissed.

**Comment by ghost** [comment]
> seeking attention is probably part of their motive

@chrisaljoudi 

After a bit more research, and looking at what the author is involved in, I think you nailed it.

**Comment by harshanvn** [comment]
Another Fake and Nonsense Review on <a href="https://addons.mozilla.org/en-us/firefox/addon/ublock/reviews/686340/">AMO</a>

Flagged it! Had to put my <a href="https://addons.mozilla.org/en-us/firefox/addon/ublock/reviews/686426/">review</a>, to share my view and experience.

**Comment by ghost** [comment]
@harshanvn 

Flag appears to have been recognized.
