### ISSUE TITLE
Ads reappear and disappear quickly in google and youtube searches *video clip included*

### ISSUE THREAD

**Issue by turmoggy** [uBlock-LLC/uBlock#98]
searched for headphones and a visual advertisement appears and then disappears quickly. 

http://a.pomf.se/bqemkq.mp4

searched for macbook air and same result

http://a.pomf.se/omchrk.mp4

did a youtube quick search in the address bar for headphones and the word advertisement in the right of the screen appears and then disappears. 

http://a.pomf.se/byfjiq.mp4

Using default updated filters.

**Comment by gorhill** [comment]
There were missing entity filters, I added them. Go to _About_ tab, scroll down, there should be an _Update_ button.
