### ISSUE TITLE
Feedback: Google, Amazon 'n' pals fork out for AdBlock

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#980]
Hi gorhill,

I don't know if you mention this anywhere on your project, but maybe something worth considering if there is really any merit to the claims.

From what I've been reading, the likes of Google, Amazon and Microsoft have been paying out to Adblock. Reading this doesn't look, paying out to allow their ads to by pass filters.

Again if any truth to it, this would be really good information to post here on your site's README so new end-users can also see another great reason to steer clear of Adblock Plus.

Here's some links I found, but with some Googling around you can find plenty more;

http://www.theregister.co.uk/2015/02/02/google_amazon_taboola_microsoft_adplock_plus_unblock/

http://www.theverge.com/2015/2/2/7963577/google-ads-get-through-adblock

**Comment by chrisaljoudi** [comment]
@meuwe just as an aside, I recall it being mentioned in the [MANIFESTO](https://github.com/gorhill/uBlock/blob/master/MANIFESTO.md). I think it's mentioned in other places throughout, as well.

**Comment by gorhill** [comment]
Yes, it's spelled out in the manifesto.

**Comment by ghost** [comment]
Ahh ok, well I meant you should consider placing information right on the home page, so to speak;

https://github.com/gorhill/uBlock

A little more info really spelling it out wouldn't hurt too.

Keep up the great work!
