### ISSUE TITLE
Processing of Second Level Domains (SLD)

### ISSUE THREAD

**Issue by maycontainnuts** [uBlock-LLC/uBlock#981]
I'm using dynamic filtering and the **\* \* \* block** filter. To access a web side i have to add at least a local noop (or allow) rule by clicking the target in the third (local) column. Selecting the SLD there will not add an SLD rule. This is not expected.

Example: http://www.rstudio.com/
- Selecting _rstudio.com_ cell should result in [rstudio.com rstudio.com \* noop]
- µblock will add [www.rstudio.com rstudio.com \* noop]  instead
- Selecting a Third Level Domain cell will result in a Third Level Domain rule

**Comment by gorhill** [comment]
`www.rstudio.com` is the scope, and it is the hostname from where the web page is pulled. Using the root domain name by default (`rstudio.com` in the current case) is not a good idea. If I create a rule while on `groups.google.com`, I surely do not want that rule to be created for the whole `google.com`.

Workaround is to edit your rule manually in the _"My rules"_ pane.

**Comment by maycontainnuts** [comment]
I know that i can edit manually. Thats not the point. 
And following your example - if you want to have a rule on groups.google.com only you can select groups.google.com you don't have to use google.com. 
- Dynamic filtering is an advanced user tool ("requires reading"), so i guess they know what they are doing. 
- Would be the same behavior like in µmatrix

**Comment by gorhill** [comment]
> if you want to have a rule on groups.google.com only you can select groups.google.com you don't have to use google.com

You are confusing source with destination. The source is set to the hostname of the URL. The destination can be anything which appears in the list, `rstudio.com`, `www.rstudio.com`, `facebook.net`, `connect.facebook.net`, `marketo.net`, `munchkin.marketo.net`, etc.

You gave me the example `rstudio.com rstudio.com`. What about `rstudio.com marketo.net`? Obviously uBlock is not going to arbitrarily use `rstudio.com` as the source for all rules created on the page, that would defeat the purpose of using the strictest rule which accomplish the job for the page. You are using block-all mode, yet you wish for looser rules by default, this is contradictory.

> i guess they know what they are doing.

That's not a argument, this contributes nothing.

> Would be the same behavior like in µmatrix

In uMatrix you can easily pick scope from the dropdown list. There is no scope selector in uBlock, thus it's set to the hostname of the URL, i.e. the strictest rules which will work for the page.

**Comment by maycontainnuts** [comment]
No, no. I'm not confusing source and destination. But i've just realized, that there is a different behavior in Firefox and in Chromium. In my common Firefox profile i can pick www.rstudio.com from dropdown-list, and so i could add that "www" rule. In Chromium and/or a new, blank Firefox profile you can't. Very strange.

![cromium](https://cloud.githubusercontent.com/assets/10872215/6582835/48e38c70-c760-11e4-8533-b4cf53bedb64.jpg)
![firefox](https://cloud.githubusercontent.com/assets/10872215/6582841/4f62b6b6-c760-11e4-9c81-52d07ac0c97d.jpg)

Sorry for wasting your time. 
Great job btw. Thank you. 
I will be patient and wait for µmatrix release for Firefox.

**Comment by benoit-pierre** [comment]
Click the '+' on the left of the 'all' label.

**Comment by gorhill** [comment]
Whether the list is collapsed or not, the **source hostname** of a local rule will **always** be the hostname extracted from the URL of the page, `www.rstudio.com` in the current case. The purpose of the list is to pick the **destination hostname** of a rule.

**Comment by maycontainnuts** [comment]
Yeah. Got it now ;-)
