### ISSUE TITLE
abp:subscribe, new automated import of ABP filters leads to undefined description

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#982]
This is on the daily build, with the experimental automatic ABP filter list import feature.

To recreate go to:

https://youtube.adblockplus.me/en/

(or the other list pages)

Importing a filter list will lead to the Filter title description as "undefined." Manually importing a new filter into the text field results in "undefined" as well.

Additionally, commented out filter lists appear to drop down into the next line enabling them.

**Comment by gorhill** [comment]
I can reproduce by just pasting the URL in the custom filter lists area, so not related to `abp:subscribe`.

**Comment by gorhill** [comment]
This happens when the remote server doesn't return the resource.

Fixed locally.

**Comment by ghost** [comment]
https://github.com/gorhill/uBlock/issues/1030
