### ISSUE TITLE
[Safari] v0.9.0: 3rd-party filters tab does not load; remains faded with spinner

### ISSUE THREAD

**Issue by NM-Clio** [uBlock-LLC/uBlock#983]
Safari 8.0.3
OS X 10.10.2

---

Often, ~50% of the time, the 3rd-party filters tab of uBlock never loads successfully. It remains faded and the mouse spinner just keeps on spinning.

**Comment by chrisaljoudi** [comment]
@NM-Clio I don't quite get what you mean by "loads". Is this when you update, or...?

A list of steps to reproduce would help greatly.

**Comment by gorhill** [comment]
This could happens if uBlock is not able to fetch `filter-lists.json` and `checksums.txt` from the Github repo.

**Comment by NM-Clio** [comment]
@chrisaljoudi Here is a screencast of my steps and the behaviour: https://copy.com/INRrUJQfYtnK9CWG

**Comment by gorhill** [comment]
Disregard what I said above, uBlock will fall back to local resources if it cannot fetch remotely. Sorry for interfering.

**Comment by chrisaljoudi** [comment]
@NM-Clio if you wait 30-60 seconds, does that stay faded/frozen?

**Comment by NM-Clio** [comment]
If it loads successfully, it does so within two seconds; if not then I'm afraid it remains frozen indefinitely.

**Comment by chrisaljoudi** [comment]
@NM-Clio okay. Would you mind taking a look at the error console when this freeze occurs to see if there's anything there? <kbd>⌘</kbd> + <kbd>alt</kbd> + <kbd>c</kbd> will bring up the console.

**Comment by NM-Clio** [comment]
I'm sorry but the Console is blank.

**Comment by chrisaljoudi** [comment]
@NM-Clio the `0.9.0.1` release (coming out soon) has significant changes/enhancements to filter list updates and Safari storage. It will likely fix this issue, but if it doesn't, the new UI for updating will provide a lot more information on what might be causing the freeze.

Would it be okay to wait until the `0.9.0.1` release?

**Comment by NM-Clio** [comment]
Of course. There is no rush.

**Comment by chrisaljoudi** [comment]
@NM-Clio Hi! So 0.9.1.0 is out now, and I'm curious to hear whether you're still having the issue with it.

**Comment by NM-Clio** [comment]
That issue is solved but new ones have arisen.

Either the 'Apply' button never appears when uBlock's preferences are launched OR if the button does appear and the choice of applied filters changed, clicking the 'Apply' button then leads to the same issue shown in the video.

**Comment by chrisaljoudi** [comment]
@NM-Clio sounds like you're not waiting long enough for it to finish updating when you "Apply".
