### ISSUE TITLE
Icon in menu

### ISSUE THREAD

**Issue by DotTheI** [uBlock-LLC/uBlock#984]
Using FF with OS X. After the add-on icon is placed in the menu (three bars icon), the menu cannot be opened.

**Comment by chrisaljoudi** [comment]
@DotTheI which version of Firefox? Any themes/extensions installed?

**Comment by DotTheI** [comment]
Hi! Yes, I have many add-ons installed:
![2015-03-10 23 01 20](https://cloud.githubusercontent.com/assets/10737439/6584033/71ba0dd6-c779-11e4-9249-5abc5c63f8bf.png)
No themes, however. FF version is 36.0.1.
I just noticed that the menu with the uBlock icon in it opens fine when I'm in the add-ons management console or on a blank page

**Comment by chrisaljoudi** [comment]
@DotTheI hmm: is it the **whole menu** (with the three bars) that is not opening, or just uBlock's popup when it's in the menu?

**Comment by DotTheI** [comment]
It's the whole menu. Actually, when I click it opens for less than a second, when I click the second time it show only this
![2015-03-10 23 06 45](https://cloud.githubusercontent.com/assets/10737439/6584127/273f20ba-c77a-11e4-9d40-ab8b35f87667.png)
When I click the third time, it opens for less than a second again. And so on...

**Comment by chrisaljoudi** [comment]
@DotTheI huh, odd. Sorry for so many questions, but does this still happen with [uBlock 0.9.0.0](https://github.com/gorhill/uBlock/releases/tag/0.9.0.0)?

If it does still happen with that, does it happen with all the other extensions disabled?

(Appreciate your feedback — I just couldn't reproduce it here on Firefox 36.0.1 on OS X so far).

**Comment by ozar** [comment]
DotThel, it looks like you are using uBlock 0.8.8.2 but have you tried the latest version, 0.9.0.0, to see if the issue persists?

EDIT:  oops, chrisaljoudi beat me pressing the ENTER key!  :)

**Comment by DotTheI** [comment]
Thank you!! I did not realize there's a newer version! The case is closed :) Thank you again!!
