### ISSUE TITLE
[Safari] storage doesn't use database quota — was limited below 100MB

### ISSUE THREAD

**Issue by chrisaljoudi** [uBlock-LLC/uBlock#985]
Working on this; will be using IndexedDB/WebSQL, which actually gets the quota. Right now, it's a horrendous mistake (the quota isn't currently related to and doesn't affect the actual storage hack :().

**Comment by gorhill** [comment]
If I understand correctly, there was a limit below the expected one for the amount of storage available to users? If so, can we rename the issue is a way that make it understandable for users in the change log of the next release? "Storage limited to xMB" or something.

**Comment by chrisaljoudi** [comment]
@gorhill done!

**Comment by gorhill** [comment]
What was the effective limit?

**Comment by chrisaljoudi** [comment]
@gorhill depended on the machine, really — it would silently throw away data after a certain point (depending on how much free space the user has on their disk).
