### ISSUE TITLE
uBlock updated icon/logo

### ISSUE THREAD

**Issue by ialexsilva** [uBlock-LLC/uBlock#989]
A make this removing the µ style
![untitled-1](https://cloud.githubusercontent.com/assets/6363160/6598739/7877634c-c7e4-11e4-8e86-511764b25522.png)

**Comment by ialexsilva** [comment]
AI Project Download: http://www.mediafire.com/download/6kt1g5olzbk6gah/ublock+logo.zip

**Comment by gorhill** [comment]
Likelihood is that I don't accept any work re. logo, even less so when the logo is so completely different than the original one, shape-wise, color-wise, proportion-wise, etc.

**Comment by TteokbokkiNari** [comment]
Yeh, I don't like it. It reminds me of a metro icon. 
Edit: By metro I mean subway.

**Comment by torzsmokus** [comment]
@ialexsilva 

> removing the µ style

I found this issue when looking for how and when the actual icon changed from _µ_ to _u_.
could you (or someone else) point me to the right issue?

**Comment by Snapy** [comment]
@torzsmokus There is no specific issue. Just a comment in a commit where @gorhill says he was tired of people asking how to pronounce and the fact fact that he doesn't pronounce "micro block".

**Comment by torzsmokus** [comment]
thx
