### ISSUE TITLE
[Safari] [Development tracking] backups on Safari (make them work)

### ISSUE THREAD

**Issue by chrisaljoudi** [uBlock-LLC/uBlock#993]
@gorhill backups use `vAPI.download` which is defined in `vapi-common.js`. The thing is, the function [uses `vAPI.messaging.channel`](https://github.com/gorhill/uBlock/blob/master/platform/chromium/vapi-common.js#L64):

```
var messager = vAPI.messaging.channel('_download');
```

That's only defined in [`vapi-client.js`](https://github.com/gorhill/uBlock/blob/master/platform/chromium/vapi-client.js#L89). However, `vapi-background.js` seems to [overwrite `vAPI.messaging` altogether](https://github.com/gorhill/uBlock/blob/master/platform/chromium/vapi-background.js#L290) and does **not** define `channel()` for it. 

How/why does `vAPI.download` work at all in this case?

The problem is, it does not work on Safari — and the error is exactly that `vAPI.messaging.channel` is undefined (which, I guess, makes sense).

Is there something obvious I'm missing? :)

**Comment by gorhill** [comment]
`vapi-client.js` is for auxiliary pages, not for the background process.

**Comment by gorhill** [comment]
So if I understand, on Safari, the auxiliary pages see everything in the background process?

**Comment by chrisaljoudi** [comment]
@gorhill hmm, nope, that's not/shouldn't be the case. Let me look into this for a bit more.

**Comment by chrisaljoudi** [comment]
@gorhill `backupUserData` is handled by `messaging.js`, which seems to be in `background.html`:

```
<script src="js/vapi-common.js"></script>
<script src="js/vapi-background.js"></script>
...
<script src="js/messaging.js"></script>
```

Given this, how's `vAPI.download` supposed to see `vAPI.messaging.channel`?

**Comment by gorhill** [comment]
`vapi-common.js` is included in the background process, and optionally in auxiliary pages.

There is always a `vAPI.messaging` when `vapi-background.js` or `vapi-client.js` is included.

**Comment by chrisaljoudi** [comment]
@gorhill I understand that, but clicking "Backup User Data" sends `backupUserData` over the `settings.js` channel, right?

That seems to be handled by `messaging.js` (in the background process), and in that context, `vapi-client.js` isn't included — which means `vAPI.messaging.channel` isn't defined.

**Comment by chrisaljoudi** [comment]
@gorhill 

> There is always a vAPI.messaging when vapi-background.js or vapi-client.js is included.

_Yep!_ `vAPI.messaging` is there, but `vAPI.messaging.channel` is **not** when you just have `vapi-background.js`. That simply does not define `vAPI.messaging.channel`.

**Comment by gorhill** [comment]
Wait, I am confused, looking into this..

**Comment by gorhill** [comment]
So this code path is not executed on Chromium, and I am guessing neither for Firefox. Looks like this was meant to be fallback code for when a browser does not support the `download` property on `a` tags. So unmaintained/forgotten code?

**Comment by gorhill** [comment]
Ok.. so my change in d8b949ecbe42fa651a402cdbe8e0cda976ed4297 broke backing up for Safari?

The download operation used to be in the auxiliary page, now it's in the background process.

**Comment by chrisaljoudi** [comment]
@gorhill I guess, yeah. Changing the code in `vapi-common.js` to use `broadcast`of the `gotoURL`  instead of a channel should solve the issue. Does that sound good to you?

**Edit:** no, it won't. Never mind.

**Comment by gorhill** [comment]
I think this should be more something like if `channel` does not exist, call `vAPI.tabs.open()` directly -- this is what `gotoURL` is essentially. There are other auxiliary pages still using `vAPI.download`.

**Comment by gorhill** [comment]
It might make sense to have a property which tell whether the current scope is the background process or an auxiliary page, this would be more easy to understand the code.

**Comment by chrisaljoudi** [comment]
@gorhill yes, that would work, but I think the problem is that mixed types of pages (both background and auxiliary) are using `vAPI.download`.

Edit:

> It might make sense to have a property which tell whether the current scope is the background process or an auxiliary page

Perfect.

**Comment by chrisaljoudi** [comment]
@gorhill 03797626cf should've fixed this. I applied the same changes across Firefox and Chrome for:
- consistency
- [really old versions that don't support the `download` attribute](http://caniuse.com/#feat=download)

**Comment by gorhill** [comment]
Not being able to backup feels like kind of a big deal for Safari users... You think we should isolate the fix and apply it to 0.9.0.0 and create a 0.9.0.1 release just for Safari users?

**Comment by chrisaljoudi** [comment]
@gorhill yes, I'm surprised it wasn't reported.

Hmm, that might cause problems unless we also distribute the fixes for Safari storage (4720ecdf586d6dde84f487120516cd524c8bc88d and 10f656f8fe6d1318b7655300694b5bd7c3b8ec2b), which are pretty major.

At that point, that includes almost everything for Safari.

**Comment by gorhill** [comment]
Major changes require more testing. Can Safari users install the dev version? I was about to release a new one.

**Comment by chrisaljoudi** [comment]
@gorhill 

> Can Safari users install the dev version?

Nope. :(

The way auto-update works for Safari, there would have to be a different update manifest setup, which is not done (yet). Should I do that?

**Comment by chrisaljoudi** [comment]
@gorhill Also, right now, the backed-up file doesn't consider the filename in Safari (defaults to `Unknown`). I'm working on that right now.

**Comment by chrisaljoudi** [comment]
@gorhill bad news: Safari simply doesn't have a way to control the filename from JavaScript. Users will have to do <kbd>⌘</kbd> + <kbd>s</kbd> and then choose a filename if they wish.

I know this is not as good because of the timestamped filenames, but it's what Safari is for now.

The **only** way to achieve the same functionality (auto-download and a generated filename) would require sending the backup to a server and back. While a server is available, I think that's really iffy privacy-wise.

**Comment by chrisaljoudi** [comment]
@gorhill what do you think about the [problem I mentioned above](https://github.com/gorhill/uBlock/issues/993#issuecomment-78404066)? Do you think we'll have to live with the limitation for now (given that sending the backup data to a server and back is iffy privacy-wise)?

**Comment by gorhill** [comment]
> Do you think we'll have to live with the limitation for now

Yes.

Sending users' private information on the wire is out of question. Eventually Safari will support the `download` property I expect.
