### ISSUE TITLE
[Safari] Video ads not being blocked on mtv.com and mylifetime.com

### ISSUE THREAD

**Issue by ultrahumanite** [uBlock-LLC/uBlock#994]
Steps to Reproduce
1. Go to http://www.mtv.com/shows/catfish/video/full-episodes/
2. Click on any of the available episode it should start playing automatically.
3. I get a video ad at the beginning of the show and during the show at the intervals indicated on the seekbar of the player. The ads might not play at every single interval but they do play at most of them.

![mtvads](https://cloud.githubusercontent.com/assets/11432363/6609710/9b39d7ce-c82b-11e4-80e6-10d0dd69571d.jpg)
1. Go to http://www.mylifetime.com/shows/preachers-daughters/video/season-2/episode-8/caught-in-the-act
2. The episode should start playing automatically. Video ads play at each interval indicated on the seekbar. Same behavior for all other shows/episodes I tired on this site.

![lifeads](https://cloud.githubusercontent.com/assets/11432363/6609768/62393446-c82c-11e4-8e41-463d0c68015a.jpg)

Okay so that's the issue, video ads on both of these sites are not being blocked.

uBlock version:
    0.9.0.0
Browser and version:
    Safari 8.0.3
OS and version:
    OS X 10.10.2

**Comment by chrisaljoudi** [comment]
Both of those sites seem to require Flash for playback.

The Safari extension API has limitations which prevent extensions from modifying requests done from Flash or other plug-ins.

**Comment by chrisaljoudi** [comment]
@ultrahumanite On the other hand, installing [ClickToPlugin](http://hoyois.github.io/safariextensions/clicktoplugin/) makes `mtv.com` work with HTML5, and that means uBlock will work just great with that.

**Comment by ultrahumanite** [comment]
Okay. That's unfortunate. On the other hand thanks for the ClickToPlugin suggestion, that works great.
