### ISSUE TITLE
Double clicking to select word in "My rules" resets changes made

### ISSUE THREAD

**Issue by my-password-is-password** [uBlock-LLC/uBlock#995]
## Steps to Reproduce
1. Go to "My rules" in the dashboard
2. Make some changes to the Temporary rules
3. Try double clicking to select a word
## Symptoms

Double clicking to select a word resets any changes made because `.on('dblclick', editStartHandler);`

![ublockdoubleclickundos](https://cloud.githubusercontent.com/assets/6408935/6612113/499af616-c833-11e4-99ce-10cfd33b5a6e.gif)

**Comment by chrisaljoudi** [comment]
Fixed in 4b2ecee.

**Comment by harshanvn** [comment]
how to record and generate an animated gif..

**Comment by my-password-is-password** [comment]
@harshanvn  I use ScreenToGif. https://screentogif.codeplex.com/

**Comment by harshanvn** [comment]
Thanks @my-password-is-password .
I already encountered this issue before. But was lazy to report the issue. Screen recording makes it easier to describe! :+1:
