### ISSUE TITLE
[Firefox] Can something be done to improve popup oppening animation?

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#996]
![flckr](https://cloud.githubusercontent.com/assets/886325/6620612/1161214a-c8d2-11e4-82d1-6b0125ba6db7.gif)

Looks like this is on Fx 37b. On Opera (Chrome?) this 'flickering' is barely visible.

**Comment by gorhill** [comment]
The dynamic filtering pane is hidden by default, I don't understand how you can get this behavior -- it is as if the browser return the size of the pane as if dynamic filtering pane is enabled. By the look of it, looks more like a browser issue.

**Comment by gorhill** [comment]
The code to deal with resizing is already dubious, to work around arbitrary browser behavior, and frankly I think the issue should be opened on Firefox side instead.

**Comment by ghost** [comment]
My glicthes a little too, but not as bad looking as this image that is playing.

My actually fickers a little when it opens.

I'm using 31.5.0 ESR in Linux.

**Comment by ghost** [comment]
On Opera I must try couple times, but can be reproduced. It's lot faster, but still visible.
![chropra](https://cloud.githubusercontent.com/assets/886325/6648152/a6e65550-c9d6-11e4-8d13-90756893b2ee.gif)

**Comment by gorhill** [comment]
There are two different things happening here:
1. The popup needs to confiigure itself according to whether the dynamic filtering pane is visible or not.
2. As a consequence, the frame which contains the popup UI may need to resize accordingly:
   - For Chromium-based browsers, uBlock doesn't have to resize itself that frame, the browser takes care of this.
   - For Firefox, uBlock has to resize the frame, Firefox is not doing it properly.

Which language is this by the way? The request type strings are way too long. An issue should be filed on Crowdin for that issue.

**Comment by gorhill** [comment]
For part 1, it could be useful to pre-configure the visibility of dynamic filtering pane to the last known state without waiting for an asynchronous answer from the background process, maybe the `localStorage` object talked about in issue #792 could help with this. Still, given how Firefox container frame work, not sure this would solve the problem, but I feel this may help.

**Comment by ghost** [comment]
@gorhill commented on [13 mar 2015, 23:37 CET](https://github.com/gorhill/uBlock/issues/996#issuecomment-79497986):

> Which language is this by the way? The request type strings are way too long. An issue should be filed on Crowdin for that issue.

Polish

**Comment by harshanvn** [comment]
@gwarser 
One more thing here, if using a laptop in power saver mode, i could see the flickering as you recorded. How ever it is not slow as yours. And if balanced/high performance mode selected, no more flickering visible.

Are you using a laptop in power saver mode?

**Comment by ghost** [comment]
Not a laptop, but old PC (Dual-Core E2160@2,4GHz).
But this is just a popup... :(

**Comment by ghost** [comment]
Nothing change after https://github.com/gorhill/uBlock/commit/aadd95ca7778ba0e2cf17387c9715aaec94876cc

**Comment by gorhill** [comment]
> Nothing change after aadd95c

I don't know what to do then.

**Comment by Betsy25** [comment]
Here's how it looks in FF nightly v39 http://i.imgur.com/V246MLE.gif

EDIT: Exactly the same experience, either with 0.9.0.1 and 0.9.1.1

**Comment by ghost** [comment]
Hardcoding `<div id="panes" class="dfEnabled">` helps.
Still not smooth, but no longer flickers and jumps left/right.

**Comment by gorhill** [comment]
> Hardcoding `<div id="panes" class="dfEnabled">` helps

Then it will become ugly for a majority of users, those who do not use dynamic filtering.

**Comment by ghost** [comment]
https://github.com/gorhill/uBlock/commit/db158617e08dd6c851837cb1727ff2204c73c7c0 still nothing

**Comment by gorhill** [comment]
File an issue with Firefox. Looks like resizable popup UI is just not very well supported.

**Comment by ghost** [comment]
Looks good most of the time after https://github.com/gorhill/uBlock/commit/3d43ad4d0063682efb8740bba3ea02b4fd983a02

**Comment by chrisaljoudi** [comment]
774e30aec6 should help this, too.

Things are now pretty much perfect in my testing (Firefox 36.0.1; OS X), especially when toggling dynamic filtering.

**Comment by Halibut80** [comment]
Maybe, <a href="https://github.com/futpib/policeman/commit/3c4c7630dbbfc8420c1713b7426af531fe803e31">this</a> help.

**Comment by mike-to-spec** [comment]
This now affects Safari as well in #1068. I'm also now seeing it in Chrome but it is not consistent as it is in Safari. 

Would it be possible for advanced users like myself to have an option to always show it in a specific size without ever resizing it?

**Comment by devnoname120** [comment]
@gorhill Wouldn't it be possible to set the panel as invisible, render it, get its size, resize the frame, and then display it? There would be a small latency, but at least it wouldn't flicker this way.
