### ISSUE TITLE
[Firefox]New badge color BUG

### ISSUE THREAD

**Issue by wasd--** [uBlock-LLC/uBlock#997]
With the latest version(0.9.0.1 dev-3) the badge is red, but if you enter in personalization menu(about:customizing)once you left that menu its gray again.

-Open Firefox, its red.
-Go to about:customizing
-Close customization tab.
-Its gray again.

**Comment by Betsy25** [comment]
Same thing happened here when I dragged the newest .xpi onto FF to update.

**Comment by Deathamns** [comment]
Fixed in d660604.
