### ISSUE TITLE
Manual update shouldn't take so much time on all browsers except Safari

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#998]
After the change that has made to workaround a bug in Safari #978 ,
there is a wait time between each downloaded list, which I think should be lower or non existent to other browsers except of Safari.

Most of us don't have connection issues, and I think there is a possibility to lower this value for most of the users, except of the ones of Safari.

**Comment by chrisaljoudi** [comment]
It's worth noting, however, the sequential downloading itself has benefits across all browsers (a quick benchmark on Chrome 41 here reveals that uBlock's peak memory usage is 30% less if the updates are done sequentially vs. all at once).

**Comment by Mikey1993** [comment]
> Just wanted to mention: this has nothing to do with connection issues.

I have mentioned this to emphasize that there is no real deal breaker in reverting to the previous update mechanism on browsers other than Safari.

> a quick benchmark on Chrome 41 here reveals that uBlock's peak memory usage is 30% less if the updates are done sequentially vs. all at once.

Right, that's nice, but isn't the 30% difference in memory drops down after a couple of garbage collections?

Anyhow, even lowering the delay time to half of what is on Safari could gain some nice numbers in the memory compartment, and not to slow down by a high factor (depends on the number of the lists you have) the update mechanism on all other browsers.

**Comment by chrisaljoudi** [comment]
@Mikey1993 yep, indeed.

I agree that the delay might be reducible (or even unnecessary) on other browsers. Just sharing some data/experiments in case you're interested. :)

---

Opinion follows (not at all disagreeing, just my opinion): all-in-all, I personally feel like there's not much harm coming from having the 5-second delay — updating filter lists from remote should be a relatively infrequent task. It seems like a fine way for uBlock to defer *just in case* resources are that sparse.

**Comment by gorhill** [comment]
> should be lower or non existent to other browsers except of Safari

No. by design. if you end up flushing all caches and forcing an update all the  time, this is really bad, you should not do so by respect for remote servers who host for free the filter lists.

**Comment by gorhill** [comment]
For the record, benefits of the current way:
- Lower CPU/memory resource peak
- ~~Beneficial to users with slower connections~~ Correcting myself: actually the beneficial part is to not download more than one at the same time, not the delay in between.
- Beneficial to remote servers: the : "update slowness" acts as a deterrent for those who would abusively update their filter lists too often
  - Unless there is a specific filter list known to have a specific fix which is sought after by a user, there is no point in updating all filter lists all the time
