### ISSUE TITLE
No indication of purging when clicking on the "Purge all caches" button

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#999]
<h1>After clicking on the "Purge all caches" button:</h1>

1) It may be clicked more than once, leaving the user in a total disorientation.
2) No indication of the cleaning process as it was before (no 'disabled' effect of the page).

This seems to affect Firefox the most as it takes couple of seconds on my machine to purge all the caches.

Using FF Nightly v39, uBlock 0.9.0.1-dev.3

**Comment by gorhill** [comment]
It's an instantaneous operation from my side. Test with an official release, I won' t fix such issue which may be only present on a bleeding edge dev version.

**Comment by gorhill** [comment]
I tested with default filter lists... How many filter lists were selected before clicking _"Purge all caches"_?

**Comment by Betsy25** [comment]
Using the very last dev commit on todays FF nightly, I can only click that button once, then it becomes disabled, and "Update Now" lights up, so cannot reproduce your problem (using commit https://github.com/gorhill/uBlock/commit/d660604b8de7842ea7af6106c8d09249f7b7e905 )

**Comment by gorhill** [comment]
I could cause the button to be disabled immediately upon click, but anything more than this would be overdoing it (indicator, etc.), as it is most likely an operation which completes in a fraction of second -- an indicator would be annoying visually to a majority of users.

**Comment by gorhill** [comment]
Actually, I changed my mind trying it more, while trying to reproduce: I agree. With Chromium, there is a very slight delay (still, less than one second), but I can see how dimming the whole screen is preferable for those cases in which a longer delay occur, however uncommon. Trying it, I didn't really find the fraction of second whole-page dimming annoying.

**Comment by Mikey1993** [comment]
Much much better than before.
Thanks @gorhill
